### ISSUE TITLE
Can't connect slack to my private repositories 

### ISSUE THREAD

**Issue by simonmcl** [ZenHubIO/support#1002]
Hi,

Not sure if this is a bug, or an unsupported feature. I have multiple private repos on my personal github account. I've recently invited a few friends to collaborate on one of them and we decided to use Zenhub to track some tickets. I setup a slack channel for us and wanted to get notifications about tickets there. 

When I go to the zenhub dashboard it brings be straight to the organisations page (I'm a member of 1 org unrelated to this private repo) and only allows me to choose repo's from that org, of which I have none. There seems to be no way for me to view my personal repos as oppose to the org repos.

I tried creating a public repo as well as a test and that also didn't show up.

Any help would be great

**Comment by kendramoroz** [comment]
Hey @simonmcl, Kendra here from the ZenHub success team.  Currently, the Slack setup is located within the integrations tab of organization settings when opening up the dashboard. Since your private repo isn't part of an organization, this is probably why you weren't able to locate it! 

![image](https://cloud.githubusercontent.com/assets/11036230/21616741/99e12608-d197-11e6-9fab-e3d29f9cfb83.png)

**There's a few options here:**

- If you want to keep the repo you're collaborating on private, if you signup for a GitHub organization and log out/back in to the ZenHud dashboard, the organization should appear and you get this setup. 
- GitHub also offers free organizations for public repos! If you make your repo public, you'll be able to create the organization and setup Slack the same way. 

We're also going to look at ways to solve this in the meantime for teams like yours that use ZenHub on private repos, but that aren't part of an organization.

If there's anything else I can help with here, let me know 🙆 !

**Comment by kobkrit** [comment]
👍 I have the same issue. Please enable Slack integration for private repo.

**Comment by irthos** [comment]
+1

**Comment by jukafah** [comment]
+1

**Comment by clang676** [comment]
+1

**Comment by vhalik** [comment]
+1

**Comment by woutor** [comment]
+1

**Comment by christoribeiro** [comment]
+1000

**Comment by sonlichao** [comment]
+1

**Comment by git-nk** [comment]
+1

Please do it..

**Comment by kendramoroz** [comment]
👋  Hey Everyone! 

The team is working on getting the Slack integration for personal repositories accessible natively in the product, but I wanted to share an interim solution to connecting ZenHub and Slack for personal repos. 

We've documented the steps to getting this setup in this getting started PDF: 
[Slack Integration Setup Guide.pdf](https://github.com/ZenHubIO/support/files/1363874/Slack.Integration.Setup.Guide.pdf)

Which leverages the script below to get it working. 

If you encounter any errors getting this connected let us know!

```js
var zenhub_url = 'https://api.zenhub.io';
var org = 'OrgName';                                          // TO REPLACE - Organization
var repo = 'RepoName';                                        // TO REPLACE - Repository
var webhook_title = 'WebhookTitle';                           // TO REPLACE - Choose a title for your webhook eg: The organization and name of the repository
var webhook_url = 'https://hooks.slack.com/services/X/Y/Z';   // TO REPLACE - Generate your webhook url here: https://my.slack.com/services/new/incoming-webhook/

function setWebhook(token) {
  $.ajax({
    url: zenhub_url +'/v2/' + org + '/' + repo + '/webhook/slack',
    type: 'PUT',
    beforeSend: function(xhr){xhr.setRequestHeader('x-authentication-token', token);},
    data: {url: webhook_url, title: webhook_title}
  })
  .done(function(res) {
    console.log('Webhook successfully created', res);
  })
  .fail(function(err) {
    console.log('Error creating webhook', err);
  });
}

function getWebhooks(token) {
  $.ajax({
    url: zenhub_url +'/v2/' + org + '/' + repo + '/webhook/slack',
    type: 'GET',
    beforeSend: function(xhr){xhr.setRequestHeader('x-authentication-token', token);}
  })
  .done(function(res) {
    console.log('Webhook for ' + org + '/' + repo, res);
  })
  .fail(function(err) {
    console.log('Error getting webhooks', err);
  });
}

function removeWebhook(token) {
  $.ajax({
    url: zenhub_url +'/v2/' + org + '/' + repo + '/webhook',
    type: 'DELETE',
    beforeSend: function(xhr){xhr.setRequestHeader('x-authentication-token', token);},
    data: {url: webhook_url}
  })
  .done(function(res) {
    console.log('Webhook successfully removed', res);
  })
  .fail(function(err) {
    console.log('Error removing webhook', err);
  });
}

chrome.storage.sync.get(['api_token'], function(data){
  // Comment / Uncomment the following lines depending on the action
  setWebhook(data.api_token);
  //getWebhooks(data.api_token);
  //removeWebhook(data.api_token);
});
```

**Comment by kendramoroz** [comment]
## Today is the day! ✨ 

Very happy to let everyone subscribed to this issue know that you no longer have to use your console and code to connect Slack to your personal repositories 🎉 .

<img width="1102" alt="screen shot 2018-02-28 at 3 40 06 pm" src="https://user-images.githubusercontent.com/11036230/36819366-1a92f720-1c9e-11e8-8e1a-999b63ed93c8.png">


If you head to the URL here, modifying `kendramoroz` to your own username first, https://app.zenhub.com/dashboard/o/kendramoroz/integrations, you'll be able to access the Slack integration. Alternatively, you can click on the ZenHub extension, then select [Dashboard](https://app.zenhub.com/dashboard/) or head to [app.zenhub.com ](app.zenhub.com) and click your profile photo to get to the same location:

![image](https://user-images.githubusercontent.com/11036230/36819345-0160a612-1c9e-11e8-92ad-e30db0edccc6.png)

Ping us here if you are running into any issues getting things up and running!
