### ISSUE TITLE
Bug: Double click on ToDo when ToDo is opened freezes it until page reload.

### ISSUE THREAD

**Issue by pedroadame** [ZenHubIO/support#1009]
Steps to reproduce:
Enter GitHub with ZenHub activated.
Click "ToDo" to open the window.
See the `#todo` at the directions bar? OK
Rapidly double-click "ToDo" again (to close and reopen it).
ToDo won't open because it thinks it's already opened (The `#todo` remains at the URL)

Found at work today because I was bored and reading the empty ToDo messages 
Additional comments: You should put the `#todo` at the URL when ToDo finishes loading.

**Comment by kendramoroz** [comment]
@pedroadame Thanks for sending this in! I was able to reproduce it and have moved it over to known issues. Good catch 👍
