### ISSUE TITLE
Unable to access a zenhub board url directly which contain a ':' in the label

### ISSUE THREAD

**Issue by infracas** [ZenHubIO/support#1010]
Steps to reproduce:

1: Create a label which contains a colon ':' in the label name
2: Filter Zenhub board via that label containing a ':'
3: A URL is generated containing the label.
4. Copy the URL generated into a new tab.
5: You are defaulted back to the boards with no labels selected.

**Comment by kendramoroz** [comment]
Hey @infracas, Kendra here from ZenHub! Thanks for sending over this 🐛  report. I've logged it with the team and am bumping this over to known issues. If there's anything I can help with in the meantime don't hesitate to let me know!

**Comment by azenMatt** [comment]
Hi @infracas - this is fixed in the latest version 😁
