### ISSUE TITLE
pressing "load more issues..." link in "closed" pipeline actually does the opposite!

### ISSUE THREAD

**Issue by xoba** [ZenHubIO/support#1012]
i.e., shows fewer issues instead of "more," and if you keep pressing it, eventually no issues get shown. 

it seems to be "sticky" too, meaning still there on closing page and re-opening. sometimes they show up again though, don't know why.

thanks!

**Comment by azenMatt** [comment]
Hi @xoba - that's not how it is supposed to work! 

Can you confirm if this happens on all boards, or just under a certain combination of filters?
 
For example, does it occur on this repos support board for you?

**Comment by kendramoroz** [comment]
@xoba Hey Mike! Kendra here following up on the last message Matt left for you—Any more insight on what's happening with your closed pipeline? We'd love to help you get this fixed!

**Comment by mnapoli** [comment]
Hi everyone, after several weeks of experiencing this I think I nailed it down to epics: if you filter the board view with an epic, then the "Load more" is broken. The rest of the time it seems to work.

The problem for me is that I do some reports at the end of the sprint for time spent on each feature, so when I filter by an epic (which is a feature) I end up with wrong results (and wrong reports) because I can't load all issues.

**Comment by xoba** [comment]
thanks for looking into it @mnapoli! no more insights from my end yet though, @kendramoroz.

**Comment by jmiller56** [comment]
is this fixed yet?

**Comment by kendramoroz** [comment]
@jmiller56 in our backlog to tackle! I'll post here once we get this fixed :)

**Comment by jmiller56** [comment]
Ok thanks Kendra!

 

Joe

**Comment by jmiller56** [comment]
Hi Kendra, 

 

Is it possible to have a brief phone call with you?

 

Joe

**Comment by kendramoroz** [comment]
Bug fix for this is live 🎉 if anyone notices any strange behaviour for the `load more` functionality let us know 🚀

**Comment by schlenks** [comment]
When I click `load more...` on a multi-repo board, it currently does not show any more issues that are in the closed column. Happy to discuss with someone at Zenhub if they want more information.

**Comment by azenMatt** [comment]
Hi @schlenks - we still have a known issue that if a filter is applied, the issues loaded do not take the filter parameters into account. This can cause it to look like no issues are being loads, but in actuality - they are, but are just being filtered out by the front end. Could that be the case here? or is it something else?
