### ISSUE TITLE
Unable to disconnect a repository from a Board

### ISSUE THREAD

**Issue by drenalin23** [ZenHubIO/support#1015]
We want to disconnect a repository from an existing board.  We get the message 'Something went wrong. Please check your permissions.'

Any ideas on how to resolve this?

![screen shot 2017-01-17 at 10 43 46 am](https://cloud.githubusercontent.com/assets/12398902/22034791/3b140dc8-dca2-11e6-9c9d-e58a1ef0c930.png)

**Comment by kendramoroz** [comment]
Hey @drenalin23, Kendra here from the ZenHub team! Thanks for sending this in—would you be able to confirm that you have **write-access** for the repo that you're looking to disconnect? If you do, if something has recently changed can you try a simple logout/back in to see if you still experience this?

**Comment by drenalin23** [comment]
Hi @kendramoroz - I don't have write-access to that repository, and I don't believe anyone on our team with access currently has write-access.

**Comment by kendramoroz** [comment]
Hey @drenalin23 Kendra here again! To disconnect the repo from the board view, you'll have to have someone who is using ZenHub get write access to remove it. My recommendation next step would be to ask your GitHub administrator for temporary access to disconnect the boards, or have them download ZenHub if they don't already to perform the action themselves. Let me know if you have any other questions here!

**Comment by drenalin23** [comment]
I was able to disconnect after asking for write access.  As I'm sure you know the UX of that isn't great and could be problematic for people who can't get write access.  Thanks for your help and updates.
