### ISSUE TITLE
Accidental pipeline deletion

### ISSUE THREAD

**Issue by mfranc213** [ZenHubIO/support#1017]
Hello,

I accidentally deleted a pipeline.  The issues within it appear to have been moved to a previous pipeline.  I have several questions and requests:

1. Without having to do an exhaustive audit, are all of the issues from the deleted pipeline safe?
2. Without having to do an exhaustive audit, are all of these issues now in the same pipeline as one another?  If so, which one?
3. Is there a way to reinstate the deleted pipeline, using the same name, and have the issues formerly in it automatically brought back to it?
4. Can the pipeline gear be moved to a location farther away from the issues?
5. Can the pipeline gear be made to look significantly different from the issue gear (I realize, now, that issues cannot be deleted, at least not via the issue gear icon--but I'm relatively new to Zenhub and so didn't know this at the time).
6. Can the ability to delete a pipeline be removed from certain users?
7. Can certain pipelines be made un-deletable by any user?

I apologize if my questions are answered elsewhere; I've looked but couldn't find anything on this particular topic.

Thank you.

**Comment by kendramoroz** [comment]
Hey @mfranc213, Kendra here from the ZenHub team! Thanks for getting in touch. I've answered each question below, let me know if there's any other questions I can help with. Some great feedback as well, thanks for taking the time to send this over.

---

> Without having to do an exhaustive audit, are all of the issues from the deleted pipeline safe?

Yes! **All your issues are safe** :) Deleting a pipeline will only move the issues, not delete them. 

---

> Without having to do an exhaustive audit, are all of these issues now in the same pipeline as one another? If so, which one?

They’ll have been moved to your **first pipeline**, bundled below all other issues that were already in that pipeline. 

---

> Is there a way to reinstate the deleted pipeline, using the same name, and have the issues formerly in it automatically brought back to it?

While there’s no automatic way to move these issues back to the pipeline, the best next steps would be to **re-create the pipeline and use the multi-action feature to en bulk transfer them back to the new pipeline that’s named the same as the old one.** 

---

You can use multi-action by clicking on the avatar image of all the issues that are now at the bottom of the first pipeline and use ‘move pipeline’ to select where they need to go. 

![image](https://cloud.githubusercontent.com/assets/11036230/22120144/3ee11f1c-de33-11e6-9289-32ccc3921d85.png)

---

> Can the pipeline gear be moved to a location farther away from the issues? + Can the pipeline gear be made to look significantly different from the issue gear (I realize, now, that issues cannot be deleted, at least not via the issue gear icon--but I'm relatively new to Zenhub and so didn't know this at the time).

Great feedback here! I’ll loop in our design team ( @brianleung11-3 ) to take this into consideration for future enhancements. 

---

> Can the ability to delete a pipeline be removed from certain users? + Can certain pipelines be made un-deletable by any user?

ZenHub leverages the permissions that GitHub provides a user, so if someone has write-access in a repository, they’ll have the ability to manage and modify the board. 

As we continue to make enhancements, additional permissions is something we’ve heard from customers before! **I’d love to learn more about you’d ideally like to see a permission model for your team and what benefits that would provide for your workflow.** Any insights you're open to sharing?

**Comment by mfranc213** [comment]
Hi Kendra,

Thanks so much for your really helpful responses.

As far as our permissions model: we have an essentially flat structure so unfortunately we wouldn't be a good source of information about use cases on this topic.  I'm sorry.

Thanks again.
Margaret

**Comment by kendramoroz** [comment]
My pleasure, @mfranc213 if anything else comes up send a message our way! Have a great week 🎉
