### ISSUE TITLE
Cannot view issues from boards on Firefox

### ISSUE THREAD

**Issue by chase-dwelle** [ZenHubIO/support#1019]
When I am in a board and try to view an issue I get the error:

`The GitHub page cannot be loaded. Make sure that Issues are enabled on the repository settings.`

Issues are turned on for the repository, and doing the same actions in Chrome works as expected, bringing up the requested issue.

**Comment by kendramoroz** [comment]
Hey @chase-dwelle Kendra here from the ZenHub team! Strange behaviour here—Would you be able to [create a new Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and confirm that it's still happening on a clean profile? Sounds like there might be a 3rd party extension interfering with ZenHub!

**Comment by chase-dwelle** [comment]
@kendramoroz The problem was fixed with a clean profile. But upon disabling all my extensions and plugins (except ZenHub), I still get the same issue. Is there a way to track down this issue further, or is it best to start from a fresh profile?

**Comment by kendramoroz** [comment]
Hey @chase-dwelle great to hear the fresh profile helped! Looks like there's old profile data conflicting with ZenHub, so the best next steps would be to stick with the fresh profile if you want to skip disabling/re-enabling each extension you have one-by-one on the other profile. If you don't have too many, you can also try this! 

One quick way around discovering which other extension is conflicting is to look into ```about:addons``` and see if there's any keys being modified that could be responsible for blocking ZenHub. 

A typical culprit is often **Privacy Badger**, so if you have this extension, it's a great place to start! 

Let me know if you need any help with this :)

**Comment by chase-dwelle** [comment]
@kendramoroz I reinstalled all the same extensions under a new profile and don't have any issues. My current profile was migrated from a different computer, so maybe there was an issue there. In any case, this can be considered closed. I didn't fix the underlying issue, but it's much simpler to just work off of a new profile.

**Comment by kendramoroz** [comment]
Thanks for letting me know, @chase-dwelle I'll have our team keep an eye on this to see if we can pinpoint the cause. If anything else happens let me know :D
