### ISSUE TITLE
User profile image is overlayed on default picture on boards

### ISSUE THREAD

**Issue by kevinwlau** [ZenHubIO/support#1021]
I had a PNG with transparency as my Github picture, and on the board view, I could see the default person image behind my picture.

Screenshot attached:
![image](https://cloud.githubusercontent.com/assets/689163/22256589/d924fa12-e220-11e6-867c-f5998c91ab74.png)

**Comment by kendramoroz** [comment]
Hey @kevinwlau I've confirmed this behaviour, thanks for reporting it! I've created an issue for our team to tackle it. If there's anything else that comes up don't hesitate to send it our way.

**Comment by kendramoroz** [comment]
@kevinwlau the latest version of ZenHub, 2.29.19 has a fix that fixes the transparency issue :). Let me know if you notice anything odd with the profile images once you get on this version. 🚀

**Comment by kevinwlau** [comment]
Looks like it works fine now.
