### ISSUE TITLE
In-board creation of issues prone to loss

### ISSUE THREAD

**Issue by dhaltmayer** [ZenHubIO/support#1025]
When creating an issue from the board view, accidentally clicking outside of the modal will lead to a loss of the issue. Maybe there could be some kind of warning, if the board view issue modal is up and any edits have been made, before dismissing the modal.

**Comment by kendramoroz** [comment]
@dhaltmayer Thanks for sending this our way! The issue modal should be saving your text, similar to GitHub's behaviour—looks like you captured a 🐛  here! I'll spin up an issue to get this tackled by our dev team.

**Comment by mnapoli** [comment]
Happened to me too and I realized that only a few days later, it's really surprising!

**Comment by kendramoroz** [comment]
@mnapoli is the text being lost still? Should be all fixed now so let us know if it's still happening!  
🔥 🚒

**Comment by mnapoli** [comment]
Well the problem is that you can leave the tab or close the window because you think the issue is created. It's not really a bug to me but rather a usability issue: it should be very explicit that the issue is not created (e.g. a modal or anything else).

**Comment by kendramoroz** [comment]
@mnapoli great point! I'm 🚢 this off to our design team as feedback on how we can make the board experience better for our users.
