### ISSUE TITLE
Firefox Electrolysis (multi process) support for the extension

### ISSUE THREAD

**Issue by audax** [ZenHubIO/support#1026]
The extension deactivates the new multi process engine of Firefox.
https://wiki.mozilla.org/Electrolysis

Since the extension already works in Chrome, porting it to the new engine shouldn't be too hard.
When I force-enable the new engine anyway, Zenhub seems to work fine, so maybe it's just a configuration in the extension manifest.

**Comment by kendramoroz** [comment]
@audax Thanks for starting the conversation here! Our team is staying in the loop with the recent Firefox changes and as we work to make browser support enhancements, we'll keep supporting Firefox multi-process on our radar. Currently the extension should still run in Firefox, so it's not a high priority issue at the moment, but bumping this over to discussion to see how other users feel about the recent upgrades and how that's impacting workflows. 

If there's any other questions I can help with, let me know!

**Comment by stof** [comment]
Well, it runs in Firefox by forcing to disable the new Firefox architecture. This does not seem good.

Btw, if you use the Firefox addon SDK and stick to high-level APIs of the SDK, your extension should already be compatible (as the compatibility is handled by the SDK itself), meaning that it is just a matter of marking the extension as compatible in the manifest.

**Comment by kendramoroz** [comment]
Thanks for the follow-up, @stof Our team is looking at what can be done 🚀  Updates will be posted here as they become available 🎉

**Comment by cemsbr** [comment]
Just a note with a hope of raising this priority: Firefox is much faster after disabling ZenHub add-on and, thus, enabling its multiprocess feature. It's really annoying to keep Firefox slower only to use ZenHub.

**Comment by kendramoroz** [comment]
Thanks for the note @cemsbr — It reminded me to make an update here that we're actively working on this to bring the extension compatible with multiprocess. I'll make an announcement here once the work is complete 🚀

**Comment by jrwesolo** [comment]
@kendramoroz Any update on making this compatible with multiprocess?

**Comment by azenMatt** [comment]
Hi @jrwesolo - it is very nearly there! We should be able to push out a version shortly once testing is finished

**Comment by jrwesolo** [comment]
@azenMatt Thanks for the update! That's great news.

**Comment by lissyx** [comment]
Hello @azenMatt, can you provide an ETA on the availability of that new build of the addon ? 54 shipped, this is getting more and more urgent :)

**Comment by cemsbr** [comment]
I'm using the web site right now, but it's a bit different. For example, I can't access my ToDo list without the extension.

**Comment by jrwesolo** [comment]
@azenMatt Seems like there have been a few releases since Jun 13. Are there some outstanding issues with the multiprocess support?

**Comment by azenMatt** [comment]
Hi Everyone, 

No outstanding technical issues with FF multi-process support - just process ones! 

We are currently blocked on this as we can't roll it out to our Enterprise (on-prem) customers yet as a number of them are on older versions of FF that aren't compatible with multi-process. 

To resolve this, we are going to do one more Enterprise release (Aug 3rd) on the old architecture, then merge in these changes to our .com version. 

This gives our Enterprise customers enough time to upgrade before the October Enterprise release. 

So..... what this means is that we should be FF multi process compatible around mid-August

**Comment by jrwesolo** [comment]
@lissyx ^

**Comment by DavidCao22** [comment]
From what I understand, Electrolysis/multi-process support is different from WebExtensions. Are there plans to make this extension into a WebExtension for FF 57+ support?

**Comment by Mathieuu** [comment]
The current ZenHub firefox addon uses [the legacy addon API](https://developer.mozilla.org/en-US/Add-ons/SDK). Unfortunately, [some of them are incompatible](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox) with multi-process. Because of that, Firefox disables multi-process when ZenHub is detected. Porting the ZH addon to Web-extensions will allow us to use Multi-process friendly API.

**Comment by cyberyoung** [comment]
It's mid-August now, do we have any update on this? Thanks

**Comment by Mathieuu** [comment]
Our current sprint (ending Thursday 24th) includes the release of Multi Process support.

The implementation is done. We are currently doing some QA, we will release in the couple of days if  no major issue is found.

**Comment by Mathieuu** [comment]
And it's live.

It took a few more days than expected due to last minutes changes in the deployment process.

Enjoy!

**Comment by jrwesolo** [comment]
Fantastic! Thank you! It's working great.

![screen shot 2017-08-24 at 10 32 25](https://user-images.githubusercontent.com/344114/29679873-b2896698-88b7-11e7-8f8e-1ad538c6269b.png)

**Comment by gibfahn** [comment]
>We are currently blocked on this as we can't roll it out to our Enterprise (on-prem) customers yet as a number of them are on older versions of FF that aren't compatible with multi-process.

Sorry if this is the wrong place, but is there a Zenhub enterprise update compatible with multi-process yet? It seems from https://www.zenhub.com/enterprise/releases/2-20 that 2.20 is the latest version of Zenhub enterprise. I've been using Firefox nightly (because it's super-fast) but haven't found a version of Zenhub enterprise that works on it.

**Comment by kendramoroz** [comment]
@gibfahn Kendra here! We're going to be launching web extensions to Enterprise in our next release, 2.22  which will be coming early Nov!
