### ISSUE TITLE
Add Firefox multiprocess compatibility

### ISSUE THREAD

**Issue by cemsbr** [ZenHubIO/support#1027]
Firefox [add-on compatibility](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/) reporter says that ZenHub add-on is not compatible with multiprocess. This means that this add-on blocks the Firefox multiprocess feature. If the user wants to enable it, ZenHub add-on must be disabled.

**Comment by kendramoroz** [comment]
Related to #1026, @cemsbr feel free to join in on the discussion there!
