### ISSUE TITLE
Why is the list of repos in the Boards' dropdown sorted like it is?

### ISSUE THREAD

**Issue by jeanrajotte** [ZenHubIO/support#1028]
The alphabet would work vey well there, particularly as the list keeps growing...

**Comment by kendramoroz** [comment]
@jeanrajotte great point! A should definitely come before S here. We currently sort by **repo ID** but the alphabet would make a lot of sense. As the list keeps growing, I'd leverage the search—it'll speed up the time the list takes to load and result in much easier sorting order. 

I'll add over your suggestion to our development board to be considered for future enhancements! 🎉

**Comment by kendramoroz** [comment]
@jeanrajotte We've recently added alphabetical sorting to the repo switcher! Let me know if you have any questions or anything else I can help with here :)
