### ISSUE TITLE
swap Milestones for Pipelines: view to prioritize issues across Milestones

### ISSUE THREAD

**Issue by bbest** [ZenHubIO/support#103]
Would be extremely helpful to plan when to accomplish issues over time. Milestones associate issues with a deadline. I like labeling Milestones by "date: task" where task is some abbreviated version of the biggest overarching task to be handled. With the Milestones arranged horizontally, I'd like to be able to move issues to different Milestones and prioritize vertically within.

Here's an example view using Huboard:

![image](https://cloud.githubusercontent.com/assets/2837257/3739222/f372ce30-1748-11e4-9d2a-1a3110e54161.png)

Although Huboard provided this basic view, had to do some [nasty hacking to set the priority](https://github.com/OHI-Science/ohiprep/wiki/Using-GitHub#issues).

This is similar to #44, but distinct from organizing issues across repositories.

For more on our approach to issue management, see [Issues Workflow](https://github.com/cmap-ucsb/issues/wiki/Issues-Workflow). Comments always welcome :)

**Comment by azenMatt** [comment]
We have a number of open issues on this topic, merging them all into #46 so we have a single point for updates!

**Comment by evfishr** [comment]
would love to have this re-opened this as its own issue - this is way more useful than #46 :+1: +1

**Comment by azenMatt** [comment]
@evfishr - Milestone view would be the first part we tackle for this new view :grinning:

**Comment by evfishr** [comment]
@azenMatt awesome!
