### ISSUE TITLE
The GitHub page cannot be loaded. Make sure that Issues are enabled on the repository settings. 

### ISSUE THREAD

**Issue by amolkedar** [ZenHubIO/support#1031]
I keep getting this error even while trying to open a GitHub tickets from the zen hub board, none of my colleagues have this issue . i am using firefox 

![screen shot 2017-02-01 at 5 04 18 pm](https://cloud.githubusercontent.com/assets/5334610/22528266/7e1bbb34-e8a0-11e6-94c8-59ff3afcc27b.png)

![screen shot 2017-02-01 at 5 04 52 pm](https://cloud.githubusercontent.com/assets/5334610/22528285/92075c3e-e8a0-11e6-93f4-ded0c41e50e0.png)

**Comment by azenMatt** [comment]
Hi @amolkedar - to confirm, issues are enabled for this repo? are any issues present?

**Comment by amolkedar** [comment]
yes issues is enabled...and yes lot of issues present 😄 


![screen shot 2017-02-01 at 5 18 41 pm](https://cloud.githubusercontent.com/assets/5334610/22528737/9906c6bc-e8a2-11e6-840c-059e06da81ca.png)

**Comment by azenMatt** [comment]
would you be able to supply a screenshot of what the board looks like when you hit this error? and also any errors that occur in the developer console?

**Comment by amolkedar** [comment]
This is what i get when i refresh the page and then when i click on the ticket on the board

![screen shot 2017-02-01 at 6 27 53 pm](https://cloud.githubusercontent.com/assets/5334610/22530949/36932c00-e8ac-11e6-8182-2b716427bbc5.png)

**Comment by amolkedar** [comment]
Hi Matt,
Is that helpful?

**Comment by kendramoroz** [comment]
Hey @amolkedar Kendra jumping in here from the ZenHub team—Based on the error consisting of something blocking the page, would you be able to [open a new Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) with no other extensions and see if the issue persists?

**Comment by amolkedar** [comment]
won't i need a new zen hub license? as my previous license would be taken up on the other zenhub plugin?

**Comment by amolkedar** [comment]
yes that works...thanks a lot, but now how can i use this on my original profile. how do i find out what is clashing?

**Comment by kendramoroz** [comment]
🎉 Glad we were able to uncover that there's a clash. @amolkedar Are you by chance using any ad block extensions, such as privacy badger? A bit manual, but a good place to start is disabling each extension you have in addition to ZenHub 1-by-1 and see if the problem persists. Could also be there's an old extension that caused an issue and there's still that bad data in the old profile.
