### ISSUE TITLE
The Firefox extension slows down the Github UI

### ISSUE THREAD

**Issue by stof** [ZenHubIO/support#1032]
It looks like the execution of the github javascript code is delayed until the Zenhub UI has been loaded when using the Firefox extension. This is really annoying, because it slows down the usage of Github itself, while I often don't care about the Zenhub UI at this time (for instance when wanting to merge a PR, and having to wait until the merge button becomes usable). This is even more annoying when I know that the repo does not use Zenhub features at all (see #757 & co) as I know I'm waiting for nothing.

My coworker using Chrome told me that this does not happen in Chrome.

**Comment by kendramoroz** [comment]
Hey @stof thanks for sending this our way! I spoke with our development team and we're working on a few fixes that we're hoping will improve this situation for you. Chrome and Firefox load a bit differently, but we still need to make sure our Firefox users have a great experience 💪 . Moving this over to known issues/will keep you updated as we have more details for you on a potential fix!

**Comment by kendramoroz** [comment]
@stof Kendra here again! Now that we've launched a Firefox version that leverages multiprocess, I wanted to check in on performance and see how things were going?

**Comment by stof** [comment]
I stopped using Zenhub a few months ago, so I cannot answer you

**Comment by azenMatt** [comment]
Lets close this one then as the new multiprocess mode really helps here
