### ISSUE TITLE
Question: Can ZenHub show me the issues in which I'm participating and/or mentioned?

### ISSUE THREAD

**Issue by nickykrause** [ZenHubIO/support#1033]
Here is something I want to do in ZenHub, but which I am not sure how to do. Maybe I just don't see how to do it, or maybe it isn't possible - I'm not sure. (I'm sort of a ZenHub newbie.)

Anyway, here it is:

> Show me not only the issues that are assigned to me, but also those in which I am `participating`

I am not sure exactly how GitHub defines "participants," but I can see that it appears as meta data on issues. Seems to add me as a participant once I comment.

In a similar vein, I want to be able to say

> Show me not only the issues to which I am assigned, but also those in which I am mentioned. 

I use ZenHub to track issues that I am responsible for (assigned), but part of what I am responsible for is responding to other people's work (through mentions/participation), and I sometimes find myself losing track of those kinds of tasks because the only record of them is in my carefully-filtered email (which means I have to go to two places to look for work I need to do -- my email list of mentions + ZenHub to see issues assigned to me).

**Comment by kendramoroz** [comment]
@nickykrause some great ideas in here! There's not currently a board filter or subscription model that targets mentions/participations specifically, but we have a few existing conversations here in the support repo that I encourage you to jump on. 

**filter board by Subscribed to:** https://github.com/ZenHubIO/support/issues/1023

**Ability to filter the board by issues that I participate in:** https://github.com/ZenHubIO/support/issues/914

While you're currently able to leverage the **assignee filter** to filter for those assigned to you, it's not able to currently pick up subscriptions/mentions. A great feature request though! I encourage giving a 👍  to the other two issues.

Going to close this one out and copy over your comments to those issues to keep the conversation bundled 😊  Let me know if you have any questions!

**Comment by nickykrause** [comment]
Thanks!
