### ISSUE TITLE
Remove ZenHub from my GitHub account

### ISSUE THREAD

**Issue by spences10** [ZenHubIO/support#1034]
Why are there no instructions on how to remove ZenHub from your GitHub account?

Anyone able to help with this?

Thanks

**Comment by kendramoroz** [comment]
@spences10 Kendra here from the ZenHub team—sending an email your way to help you close out your account.

**Comment by spences10** [comment]
Logged #1035 as this was closed prematurely

**Comment by blafasel42** [comment]
Same issue here. I revoked access but still habe the menu items in github

**Comment by spences10** [comment]
Have you removed the Chrome extension? That was what fixed it for me 👍

**Comment by kendramoroz** [comment]
@blafasel42 as @spences10 noted, removing the extension will remove the additional menu items that ZenHub adds! Feel free to get in touch at support@zenhub.com if you're encountering any troubles or write to me here for further help 🙋

**Comment by blafasel42** [comment]
ok, this worked. Thank you!
