### ISSUE TITLE
Remove ZenHub from my GitHub account

### ISSUE THREAD

**Issue by spences10** [ZenHubIO/support#1035]
Why are there no instructions on how to remove ZenHub from your GitHub account?

Anyone able to help with this?

Thanks

---

This time, before closing the ticket please make sure that the user can uninstall this 👍 

I followed the instruction [which by the way is what I tried before logging a ticket] 

And now I don't have zenhub authorised and still have the anoying overflow menus and a log into zenhub badge

![image](https://cloud.githubusercontent.com/assets/234708/22709046/58b15212-ed70-11e6-998f-62438c1c9313.png)

![image](https://cloud.githubusercontent.com/assets/234708/22709060/69e6a032-ed70-11e6-8b71-97a0ff46420c.png)

**Comment by kendramoroz** [comment]
Replied to your email, @spences10! Let me know if the uninstall + revoke doesn't work for you. I'll keep this open until you confirm.

**Comment by spences10** [comment]
I didn't uninstall the chrome extension Doh!

And it's gone!

Thank you for guiding me through my stupidity
