### ISSUE TITLE
Keyboard Shortcut Documentation Missing

### ISSUE THREAD

**Issue by gmuresan** [ZenHubIO/support#1036]
The keyboard shortcuts are no longer viewable at https://www.zenhub.com/product#KeyboardShortcuts.

Is there a different page where we can see the shortcuts?

**Comment by kendramoroz** [comment]
@gmuresan Hey George, Kendra here from the ZenHub team! You can find the [shortcuts listed here](https://www.zenhub.com/documentation/streamline-my-github-workflow#keyboard-shortcuts)

Also pasted them here for easy access:

![image](https://cloud.githubusercontent.com/assets/11036230/22716869/c4e59778-ed4c-11e6-8a03-684008fa13d4.png)
