### ISSUE TITLE
The number of completed issues in an epic is off by one

### ISSUE THREAD

**Issue by stof** [ZenHubIO/support#1038]
The summary of issues in an epic is really weird, because it counts the epic itself.
IMO, the epic itself should not be counted as an issue inside the epic (unless someone really creates an epic attached to itself, in case you don't forbid it)

![zenhub_epic](https://cloud.githubusercontent.com/assets/439401/22796439/9a54feea-eefa-11e6-8a72-8bf96e31a811.png)

this UI tells me that there is still something to be done here, while the work is actually done and we could close the epic itself (which we did just after taking the screenshot btw)

**Comment by kendramoroz** [comment]
@stof Thanks for drawing our attention to this! I've looped in our product team to go over the expected behaviour here. I'll get back to you once I know more 🕵️‍♀️
