### ISSUE TITLE
Velocity tracker Sprint end date is different

### ISSUE THREAD

**Issue by Altxal** [ZenHubIO/support#1039]
on the velocity tracker page, the date for the end of the sprint in the table is different when you hover over the bar

**Comment by kendramoroz** [comment]
Hey @Altxal can you send over a screenshot of where you're seeing the dates differ on your velocity report? Feel free to fire it over to support@zenhub.com or paste it here. I tried to reproduce with no luck so I want to see if there's something unique to your reports I'm missing in debugging.

**Comment by kendramoroz** [comment]
@Altxal following up here—Are you still experiencing this issue :)?

**Comment by kendramoroz** [comment]
@Altxal closing out this issue since we haven't heard from you, but if this is still occurring for you please let me know and we'll dig in to investigate 🕵️‍♀️
