### ISSUE TITLE
Checkbox states are not saved when clicked

### ISSUE THREAD

**Issue by hanneman** [ZenHubIO/support#1044]
Checkbox ( [ ] ) states are not saved when clicked and closing the modal.

**Comment by kendramoroz** [comment]
Hey @hanneman Kendra here from the Success team! I was attempting to repro this issue and couldn't get the checkboxes to not save—Are you having trouble with the first level of checkboxes, or a deeper level in? If you could send over a small gif of what's happened, that'd be great! 

- [ ] first level
    - [ ] second level
        - [ ] etc.

**Comment by erikhuisman** [comment]
It might be a problem for checkboxes that are included from a 'ISSUE_TEMPLATE.md'

**Comment by erikhuisman** [comment]
This is our issue template 

```

<hr />

### Frontend Team

-  **Design**
    - [ ] Design pixel perfect (_desktop_)
    - [ ] Design pixel perfect (_mobile_)
- **CSS**
    - [ ] Lintfree css and js
    - [ ] Is the scss concentric? ([What is concentric?](http://rhodesmill.org/brandon/2011/concentric-css/))
- **Shared code**
    - [ ] Is it shared code? make it shared code ;)
    - [ ] Remove all duplicate css and js
- **Translations**
    - [ ] Translations for all strings
- **Issue**
    - [ ] Works as intended?
    - [ ] Is the issue done? fill the issue with feedback
    - [ ] Issue checked with Han?
    - [ ] Manually add entry (one line) to the [Changelog](https://github.com/StriatumVentures/ZUPR/blob/master/CHANGELOG.rst): english_problem_and_solution_description (#issue)

### API/Backend

- [ ] Tests
- [ ] Flake8/isort
- Endpoint
  - [ ] Permissions
  - [ ] Filters
  - [ ] Expand
- [ ] SQL Queries checked
- [ ] Is the issue done? fill the issue with feedback
- [ ] Issue checked with Han?
- [ ] Make sure any new fields are included in the Django Admin.
- [ ] Manually add entry (one line) to the [Changelog](https://github.com/StriatumVentures/ZUPR/blob/master/CHANGELOG.rst): english_problem_and_solution_description (#issue)


See for changelog format also the section: [What makes a good change log?](http://keepachangelog.com/en/0.3.0/)

<hr />

PASTE IMAGE IF NEEDED
```

**Comment by erikhuisman** [comment]
These checkboxes don't seem to work in GitHub either so this isn't a ZenHub issue

**Comment by kendramoroz** [comment]
@erikhuisman Happy to hear that it looks like an isolated incident! I'd suggest next steps be to reach out to GitHub to see if they're going to be adding support here. I'm going to close out this issue here but please let me know if there's anything else I can do to help you with this or anything else ZenHub 🎉
