### ISSUE TITLE
create issue in specific repo

### ISSUE THREAD

**Issue by gVolop** [ZenHubIO/support#1046]
when i'm on repo X on a merged board (from X & Y repo), and i wanna to create new issue - it's automatically created on repo X, are you can maybe add an option to choose in what repo i want create the issue?

**Comment by kendramoroz** [comment]
Hey @gVolop great question! You are able to select the repo you'd like to post the issue on if it's different from the repo you originally clicked into to view your Multi-repo Board by using the **+ button** next to the **new issue button**

![image](https://cloud.githubusercontent.com/assets/11036230/23109171/3c2f8960-f6cb-11e6-8829-4eb8dafc46db.png)

Once you select the repo the modal that appears will automatically create the issue in that selected repo. 

Let me know if you don't see this and or need a hand! 🙆

**Comment by gVolop** [comment]
nice!
many thanks!!!
