### ISSUE TITLE
Changing Due Date on a Multi-Repo Milestone disconnects the milestones

### ISSUE THREAD

**Issue by knightstick** [ZenHubIO/support#1050]
If you create a many-repo milestone from the board, then change the due date for that milestone, the milestone gets split into two separate milestones, one for the repo you were in when you changed the due date, and one connected to the other repos that were once connected.

**Comment by knightstick** [comment]
Update: Changing the due dates on "each" milestone will join them back up.

**Comment by kendramoroz** [comment]
Hey @knightstick thanks for sending this in! The behaviour of the multi-repo milestone create button is to enable cross-repo milestones that have the same dates/naming conventions to empower cross-repo reporting. If the milestones are named slightly differently, or have different dates associated with them, ZenHub will treat them as separate milestones currently. However if everything across dates and names align, it'll treat them the same. 

Currently the modal is for creating issues, not editing them after creation. 

Let me know if you have any questions about this functionality!

**Comment by knightstick** [comment]
Hey @kendramoroz,

Thanks for the clarification! I'm assuming that there's no way to update the due date on linked milestones all at once at the moment then? No big deal, stick it in the "Would be nice to have" pile I guess!

**Comment by kendramoroz** [comment]
@knightstick currently bulk editing isn't supported in the milestone modal, only creation! We've added this to our backlog, however :). 

Let me know if I can help with anything else!

**Comment by knightstick** [comment]
Nope, that was all, thanks @kendramoroz
