### ISSUE TITLE
Zenhub is not showing issues inside Epic or that an issue is part of an Epic on Chrome

### ISSUE THREAD

**Issue by carlomas** [ZenHubIO/support#1054]
I am running ZenHub on 2 browser FF 45.5.1 and Chrome 54.0.2840.90 (64-bit) on RHEL 7

Using Chrome Browser I can't see any Epic information, like the issues included in the epic or for an issue, the Epic which the issue belongs to

This are the details of ZenHub plugin running on Chrome:
![selection_516](https://cloud.githubusercontent.com/assets/18550707/23413730/8687e572-fdd1-11e6-86d7-1e2d68a2c431.png)

Adding screenshots of the same epic and issue:
- **FF**
epic
![selection_515](https://cloud.githubusercontent.com/assets/18550707/23412086/62fc14f2-fdcc-11e6-9c54-5db213707128.png)
issue
![selection_512](https://cloud.githubusercontent.com/assets/18550707/23411997/12c60c90-fdcc-11e6-87a8-762d7cfcc2b0.png)

- **Chrome**
epic
![selection_514](https://cloud.githubusercontent.com/assets/18550707/23412044/39fa1b8a-fdcc-11e6-9dd9-f5d936f5a7f9.png)
issue
![selection_511](https://cloud.githubusercontent.com/assets/18550707/23412004/19ebda72-fdcc-11e6-85d4-28b04bea0cbb.png)

**Comment by carlomas** [comment]
Sorry, the problem was a VPN connection to AWS which could not make it possible to reach to zenhub.innovate. If I close that VPN it works fine.
But FF doesn't show the same problem

**Comment by kendramoroz** [comment]
@carlomas glad to hear you were able to get everything sorted! If there's any other questions or anything I can help with related to ZenHub, happy to grab a quick call 🎉  Have an awesome day!

**Comment by carlomas** [comment]
thanks @kendramoroz you too!
