### ISSUE TITLE
zenhub board pipeline should support multiple labels selected as filter

### ISSUE THREAD

**Issue by goupeng212** [ZenHubIO/support#1057]
We defined many labels, such as priorities: Priority:High,  Priority:Medium, Priority:Normal. When reporting our status weekly, the managers want to see the opening issues with priority:High and Priority:Medium. But the current zenhub can not support that!
Any idea?

**Comment by kendramoroz** [comment]
@goupeng212 thanks for getting in touch! When you note that ZenHub doesn't support status updates, are you referring to a particular bug within the labels or the board, or something else? Happy to debug here—Would you be able to send over a screenshot of what you're looking at and a bit more details on what you're looking to achieve with these status updates? One more question—Are you currently using ZenHub Enterprise on GitHub Enterprise or ZenHub on GitHub.com?

Look forward to hearing from you 🎉

**Comment by goupeng212** [comment]
@kendramoroz 
We are using zenhub plugin onto our internal github. So It is impossible to provide you the URL.
Maybe I didn't explain clearly about the requirement.

We have three labels: Priority:High, Priority:Medium, Priority:Normal
So we are tagging the label on the issues. The three labels are exclusive. One issue only have one priority. 
For the zenhub pipeline boards, we want to filter such issues: We care about the opening high or medium issues. That means we will multi-select Priority:High and Priority:Medium in the Labels Drop list.  But the current labels drop list is a kind of "**AND**" filter operation. That means the multi-select operation will filter out the issue with "Priority:High" **AND** "Priority:Medium". The filter result will be empty, since there is no issue with "Priority:High" **AND** "Priority:Medium". 
We need the "Labels" droplist in the Zenhub board pipeline support "**OR**" operation. We need filter out the issue with "Priority:High" **OR** "Priority:Medium".

Is that clear?

**Comment by kendramoroz** [comment]
@goupeng212 thanks for that additional insight! The 'OR' functionality is something we have in our roadmap for the first half of this year :). Issue #865 captures this as well if you'd like to join the conversation there. I'll be sure to keep you updated on when this get launched 🎉  . 

As always, feel free to pass forward any feedback, feature requests, or get in touch with questions you have.

**Comment by jleni** [comment]
Any updates?

**Comment by kendramoroz** [comment]
@jleni closing in favor of #865 to keep updates consolidated. We'll share more than once we have news to share on priority of or filtering!
