### ISSUE TITLE
"Loading issues in this epic..." doesn't load

### ISSUE THREAD

**Issue by alexfinnarn** [ZenHubIO/support#1060]
This is a public repo so hopefully you can see [https://github.com/CuBoulder/express/issues/820](https://github.com/CuBoulder/express/issues/820).

It is an issue with the "epic" label where the sub-tasks never load. I do see some console errors that might be relevant. 

https://api.zenhub.io/v4/repositories/50196783/issues/820/events leads to 
`{"message":"missing authentication token in headers"}`

https://api.zenhub.io/v4/repositories/50196783/epics/820 leads to 
`{"message":"missing authentication token in headers"}`

Let me know if you need any more information, but I have no idea about missing authentication tokens. I am logged in under my Chrome Extension apparently.

**Comment by azenMatt** [comment]
Hi @alexfinnarn - thank you for reporting this, I can also replicate it. We are investigating and will get a fix live

**Comment by azenMatt** [comment]
Hi @alexfinnarn - this was just fixed, can you confirm accessing that epic works for you now?

**Comment by alexfinnarn** [comment]
Yes, this works now. You can close if you don't need any more info.
