### ISSUE TITLE
Combined repositories on board whilst keeping privacy intact

### ISSUE THREAD

**Issue by adriangauci** [ZenHubIO/support#1065]
**Is it possible to have private and third party repositories combined in boards without letting the collaborators to view our private github issues?**

Currently our organisation uses 2 kinds of different repositories:
- **Private repos**, used by the company employees where most of the work is done.
- **External repos**, used by the company employees to collaborate with third parties.

Whilst collaborators can use the external repo to work with us, they aren't allowed to see our private repos for security reasons. On the other hand, the company employees can see everything.

We would like to have a Zenhub board where we can view different repositories at the same time whilst still maintaining privacy settings intact. Is this possible?

**Comment by adriangauci** [comment]
@kendramoroz Thanks for the input. This helped me a lot.

Probably a lot of confusion arose due to the fact that the keyword 'merge' on Zenhub filter was misinterpreted as literally merging issues together in one repository.

Thanks again :)

**Comment by kendramoroz** [comment]
@adriangauci my pleasure! Don't hesitate to get in touch if there's anything else I can help with :)

**Comment by adriangauci** [comment]
@kendramoroz Another question:
What if the outside contributors also use Zenhub and rename/add more pipelines in their repository. Would it break our main repository since pipelines get merged?

**Comment by kendramoroz** [comment]
@adriangauci The pipeline names will currently change across everyone's views if edited by one individual. This means all merged repos would get the updated names as well. The permission to write is universal across all related boards, so even though they wouldn't have access to view the other merged boards it'll update it across all boards. 

I'd suggest sending a message to all collaborators to not update the names of pipelines without first consulting the entire team :).

**Comment by adriangauci** [comment]
Thanks so much @kendramoroz !
