### ISSUE TITLE
pulse, graph, settings menu z-index

### ISSUE THREAD

**Issue by puppycodes** [ZenHubIO/support#1068]
a quick fix is adding to the stylesheet

```
.reponav {
    z-index: 31;
}
```
 
<img width="332" alt="menu" src="https://cloud.githubusercontent.com/assets/5248271/24077645/e1d3e626-0c11-11e7-9758-09d5d288b784.png">

**Comment by kendramoroz** [comment]
@puppycodes Kendra here! The latest GitHub enhancements have made it possible to disable the `Projects` tab if you're not using them and using ZenHub Boards. With this tab turned off, pulse, graph and settings get bumped back to the main navigation 💪 

Heading to `settings` will give you this option right on the main settings page:

![image](https://cloud.githubusercontent.com/assets/11036230/24993051/74cab880-1fd9-11e7-9fdd-d7877fe68f05.png)

![image](https://cloud.githubusercontent.com/assets/11036230/24993059/7ff65ade-1fd9-11e7-8a6b-1f7d33b17585.png)

**Comment by kendramoroz** [comment]
👋  Updating some older Issues! This should now be fixed :) if you encounter any issues feel free to ping me!
