### ISSUE TITLE
Using ZenHub without an extension

### ISSUE THREAD

**Issue by wvengen** [ZenHubIO/support#1074]
While having ZenHub available within Github is a great experience, I've seen it only work reliably for a subset of developers (~60%). For the rest, #641, #1032 and other issues have been a nuisance, or worse a blocker, for years.

Instead of trying to catch-up with browsers and Github changes, why not provide an ordinary web-interface as well? As a minimum, this could provide viewing boards and velocity charts, but ideally it would also be possible to assign storypoints and so on. This would be much more stable, and make the product accessible to more users as well (like #53, #156) - especially important for a heterogeneous development team.

**Comment by azenMatt** [comment]
Hi @wvengen - thank you for your thoughts here, you'l be pleased to know that #156 is currently in progress and is a top priority for us at the moment. You can subscribe to that issue for updates 😄

**Comment by wonderwarthog** [comment]
How does a mobile app address the problem of ZenHub being buggy and slow on Firefox? When I'm at work I'm looking at my desktop browser. I definitely don't want to switch to a mobile device with an awkward virtual keyboard and consider that a solution or improvement?

**Comment by azenMatt** [comment]
Hi @wonderwarthog - #156 also covers a webapp which will be desktop accessible - so no need to switch to a mobile device to use it
