### ISSUE TITLE
Filtering by label doesn't work with labels containing uppercase letters

### ISSUE THREAD

**Issue by tamias** [ZenHubIO/support#1078]
If a label contains uppercase letters, filtering by that label does not show issues with that label on the project board.

![image](https://cloud.githubusercontent.com/assets/478001/24457620/68ab46ba-145c-11e7-9a52-09c740f8ae81.png)

![image](https://cloud.githubusercontent.com/assets/478001/24457643/73c2abce-145c-11e7-8ebe-52f1d90949db.png)

**Comment by azenMatt** [comment]
Hi @tamias - we have just pushed an update to fix this, can you try updating your extension and see if it is still a problem?

**Comment by tamias** [comment]
It works now.  Thank you!

**Comment by azenMatt** [comment]
Happy to help :)
