### ISSUE TITLE
Choose the repos that I want to give access to zenhub in my organisation

### ISSUE THREAD

**Issue by arnaudlopez** [ZenHubIO/support#1086]
As a Zenhub user

I would like to choose the repo that I allow zenhub to access

In order to share limited information. :)

**Comment by azenMatt** [comment]
Hi @arnaudlopez 

The good news here is that GitHub are working on new permission structures to allow more granular permission handling. 

Once this is available for public release it will be a priority for us to implement it. Right now, it is still in pre-release and I am not aware of any deadlines set for when it will enter release status

**Comment by arnaudlopez** [comment]
Hi @azenMatt Thanks for time you've past to respond to all my answers ! That's a great tool anyway :D 
Regards

**Comment by diracdeltas** [comment]
@azenMatt any update on whether that was implemented? I am doing security review for integrating zenhub within our organization, and we would strongly prefer to only allow zenhub access to the single repo that needs it.

**Comment by jankeesvw** [comment]
I'm a freelancer and I am part of a lot of organisations, I can't use ZenHub because you need access to all project organisations code.

![image](https://user-images.githubusercontent.com/167882/50638984-f64c0e00-0f5f-11e9-8b79-af3954c731ef.png)

Is there a workaround?
