### ISSUE TITLE
Have the Pipeline and the Estimate button in the milestone view

### ISSUE THREAD

**Issue by arnaudlopez** [ZenHubIO/support#1087]
As a ZenHub user

I would like to have the Pipeline and Estimate button in the milestone view when you check an issue like the other github buttons

In order to handle the process of estimation faster (not to have to go in the issue view)

![capture d ecran 2017-04-05 a 10 43 18](https://cloud.githubusercontent.com/assets/10036824/24697454/83e464d4-19ed-11e7-9d67-e752c645bfdc.png)

**Comment by azenMatt** [comment]
Hi @arnaudlopez - thank you for your suggestion! It is a popular one :) we have an issue tracking it here - https://github.com/ZenHubIO/support/issues/151 - that you can subscribe to for updates.
