### ISSUE TITLE
Have the same milestone sorting in Zenhub than in GitHub milestone view

### ISSUE THREAD

**Issue by arnaudlopez** [ZenHubIO/support#1089]
As an ZenHub user

I would like to find the sort that I've made in the github milestone view in the sorting that I have in the ZenHub board view

To be able to sync the prioritization that I have made in Github in the zenhub board view

>I prioritize in the milestone view:

>![sans titre](https://cloud.githubusercontent.com/assets/10036824/24699049/10267766-19f3-11e7-9c4d-969662a858a4.png)

>But the milestone sort is not giving me the same sort in the tool:

>![capture d ecran 2017-04-05 a 11 18 33](https://cloud.githubusercontent.com/assets/10036824/24699054/14de8a00-19f3-11e7-84aa-fe9b99a33908.png)

**Comment by azenMatt** [comment]
Hi @arnaudlopez - GitHub do not expose this sorting data anywhere in the API or Web hooks implementation, so unfortunately this is not feasible. 

For what it's worth - I agree with you that it should be so, we have requested that this data is provided, and if it ever is we will look into implementing a syncing between the two!
