### ISSUE TITLE
Viewing board for public fork?

### ISSUE THREAD

**Issue by ecurtin** [ZenHubIO/support#1091]
Howdy,

I'm working on a project that's a public fork of another public project. https://github.com/ecurtin/spark-bench My fork is enrolled in Zenhub, the original project is not (to my knowledge). 

It seems like nobody else can see the boards for my fork, even people I've added to the project as collaborators.

Am I missing something? Is there an access setting I've overlooked? Is this a limitation of using a fork?

Thanks for your support!

**Comment by ecurtin** [comment]
Nevermind! I figured it out! You need to download the Zenhub extension to view the boards :)

**Comment by kendramoroz** [comment]
Hey @ecurtin great to hear you've debugged this! If anything else comes up don't hesitate to send us a note here or through support@zenhub.com :) Happy to lend a hand. 👋
