### ISSUE TITLE
Problem moving issue beteen pipelines using API

### ISSUE THREAD

**Issue by claeyswo** [ZenHubIO/support#1093]
When doing a POST to ```https://api.zenhub.io/p1/repositories/22334594/issues/569/moves``` with data
``` json
{"pipeline_id": "58ced60b91f2ae310d8df667", "position": "top"}
```

I get a 400 ```{"message":"Invalid Field for pipelineId: undefined"}```

**Comment by kendramoroz** [comment]
@claeyswo Kendra here from the ZenHub team! Would you be able to send us an email at support@zenhub.com so we can dig a bit deeper? We'd like to confirm you're using JSON :).

**Comment by claeyswo** [comment]
That was the problem, forgot to set my Content-Type header. Thanks!

**Comment by kendramoroz** [comment]
@claeyswo glad to hear it's resolved! If anything else comes up don't hesitate to let me know 👋

**Comment by andy-sigsci** [comment]
@kendramoroz could you add language to the api docs that instructs us to use a content-type header?
