### ISSUE TITLE
Bulk close issues

### ISSUE THREAD

**Issue by ysmazda** [ZenHubIO/support#1094]
I'd like a way to close the selected issues in bulk in the same way as 'Move to Pipeline', 'Apply Lables', 'Set Milestone' etc.

**Comment by kendramoroz** [comment]
@ysmazda thanks for the feedback here! Currently the best way to quick-close an issue is to drag and drop it into the closed pipeline. Bulk closing is on our radar, though! Bumping this over to the discussion pipeline for further community input.

**Comment by azenMatt** [comment]
The 'move to pipeline' bulk action now has the option to bulk close issues - you just need to select to move it to the 'closed' pipeline and ZenHub will close the issues

**Comment by shahneela-rahman** [comment]
@azenMatt Do you know what version of zenhub supports this? I don't see "closed" in the "Move to pipeline" option. I see the other pipelines, but not closed. 
![image](https://user-images.githubusercontent.com/29610435/29641233-7e4bbe26-8817-11e7-8bce-b2072535387e.png)

**Comment by azenMatt** [comment]
@shahneela-rahman  Which version are you on?

If you are on the Enterprise version, this feature is on v2.20 https://www.zenhub.com/enterprise/releases/2-20

**Comment by shahneela-rahman** [comment]
@azenMatt  yes, Enterprise 2.20

**Comment by shahneela-rahman** [comment]
@azenMatt turns out that i was on an older version of the plug-in. Once I updated to 2.2, I see it on the Move to Pipeline menu. Thank you
Is there a way to do auto update for Firefox? Thanks.

**Comment by azenMatt** [comment]
Great news! Firefox should be auto-updating by itself. 

To avoid sending out too many messages to other subscribers of this thread - can you send an email to support@zenhub.com and we can take a closer look? Thanks!
