### ISSUE TITLE
When connecting a PR to an issue, the issue is moved back to the first pipeline

### ISSUE THREAD

**Issue by hankthewhale** [ZenHubIO/support#1098]
Checked in the known issues pipeline and didn't see this. This might only apply to the enterprise version of ZenHub, but here's what's up.

### Steps to reproduce
1. Have an issue in a column other than the first pipeline, "New Issues" in our case
2. Open a PR and connect it to the issue from step 1

**Expected result**
The issue remains in the pipeline that it was in before connecting a PR to it

**Actual result**
The issue is tossed back to the first pipeline

**Browser**: Chrome 57.0.2987.133
**OS**: Mac OS X

The problem here is that we have issues "In Progress", attach a PR, then have to move the issue back to "In Progress" because it gets placed back into "New Issues." It's an easy thing to do on our end, but a hard thing to always remember. This causes things to seem to disappear from our board when really they have just been thrown back into "New Issues."

**Comment by kendramoroz** [comment]
@hankthewhale thanks for writing into us with this! Sounds like the default pipeline for pull requests hasn't yet been set, causing the connection to bump the connected issue/PR back to new issues. 

When submitting your next pull request can you verify that you've indicated a different pipeline here where pull requests should be sent?

![image](https://cloud.githubusercontent.com/assets/11036230/25972059/59e50882-3653-11e7-86fc-ecbabf85725b.png)

Once defined, when connecting an issue the issue/pr connection should move to the pipeline indicated from the dropdown 🎉 . 

Let me know if it's still sending issues back when this is set to the proper pipeline!

**Comment by kendramoroz** [comment]
@hankthewhale Hey Dave! Following up here: would you be able to confirm if the steps above helped solve the issue, or if you're still experiencing this with a default pipeline set that's not the new issues pipeline?

**Comment by hankthewhale** [comment]
Sorry. I was out on vacation over the last two weeks. I'll give this a shot tomorrow and report back. Thanks!

**Comment by hankthewhale** [comment]
This seems to fix the issue. Thanks for the clarification.
