### ISSUE TITLE
dashboard can merge the repo under other ORG

### ISSUE THREAD

**Issue by swizardlv** [ZenHubIO/support#1101]
That would be great for big project under different organization. currect we can only merge the repos under the same org.

Thanks.

**Comment by kendramoroz** [comment]
@swizardlv Thanks for getting in touch! You can actually merge from other Organizations today as long as you have **write** access to the repo you're looking to connect. 

When going to merge a repo from the Board, select the option under the search filter for `Or merge from another organization`

![image](https://cloud.githubusercontent.com/assets/11036230/25972315/582936f2-3654-11e7-981f-56871e784114.png)

Once you select this option you will have to type in the org name as well as the repo and it will connect them together!

![image](https://cloud.githubusercontent.com/assets/11036230/25972338/829f4f3e-3654-11e7-8134-27d96cd3b48c.png)

⚠️  With all merge actions, we do recommend speaking with the team using the Board today if it's different than your own as merge actions impact both Boards and alter the workflow across both workspaces. 

Let me know if you have any questions about this!
