### ISSUE TITLE
Feature request: API to add and remove issues from Release

### ISSUE THREAD

**Issue by 7omasz** [ZenHubIO/support#1103]
From
https://www.zenhub.com/guides/release-reports
>The most efficient way to add issues to your Release is by using the multi-select functionality on your ZenHub Board.

We'd like to do this programmatically.

**Comment by kendramoroz** [comment]
@7omasz Thanks for taking the time to issue this up! Adding API support for Releases is on our radar. I'll be sure to update this issue when this is in progress on our end :). Any other feedback on how you'd like to leverage the API to build onto the Release workflow would be helpful to pass to the team. 

Let me know if I can help with anything else here in the mean time!

**Comment by 7omasz** [comment]
Thanks @kendramoroz ! As far as our use case, we'd like to be able to automatically add issues to release so that we can track velocity via reports. Our workflow is fairly distributed so we don't often know this upfront when an issue, and may need to revisit when an issue is closed or a new branch is created/merged.

**Comment by azenMatt** [comment]
Hi @7omasz - the API has just been updated with Release actions - https://github.com/ZenHubIO/API#release-reports

So you can now use the API to add issues to the reports :)

**Comment by 7omasz** [comment]
@azenMatt awesome, thanks!
