### ISSUE TITLE
Permission errors when trying to create release reports

### ISSUE THREAD

**Issue by cdparra** [ZenHubIO/support#1104]
I am the admin of the repositories under the organization socialappslab, and yet, everytime I try to create a release I get `no permissions for release report` error message

![image](https://cloud.githubusercontent.com/assets/630150/25565410/2003f6cc-2d94-11e7-93ef-a80aa2bc87cc.png)

In my repos, branches are protected and require pull requests to be approved before merges. Can that be the culprit?

**Comment by kendramoroz** [comment]
@cdparra Thanks for sending this through! Would you be able to send us a note at support@zenhub.com with the details of the branch protection settings you have on so we can debug this one further?

**Comment by cdparra** [comment]
Just sent the details @kendramoroz!

**Comment by kendramoroz** [comment]
🙌  closing this and replying to the email :)
