### ISSUE TITLE
Difference between releases and milestones?

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1105]
Just a quick question, but what is supposed to be the difference between releases and milestones? We were already using milestones for our releases, and I don't see what added value the releases really add to the workflow?

**Comment by claeyswo** [comment]
It is described in their book: https://www.zenhub.com/book/github-project-management/.

Basically a milestone = a sprint.

**Comment by smeijer** [comment]
With CI/CD a milestone / end of sprint is often also a new release. Would be nice if the `Reports` could be based on a `milestone` instead of a `release`.

**Comment by smeijer** [comment]
Still confusing; with CI/CD a sprint is quite often also a release.
