### ISSUE TITLE
Plugin not compatible with Firefox Nightly 55.0a1

### ISSUE THREAD

**Issue by lkappeler** [ZenHubIO/support#1108]
With the following config option the plugin works
https://wiki.mozilla.org/Add-ons/ShimsNightly

**Comment by azenMatt** [comment]
Hi @lkappeler - thank you for the information here. 

Making sure we are multi-process/web-extension compatible is on our radar and being tracked here - #1026 

We will make sure that we have this out before the FF 57 goes fully live 

Right now, we have an early version working, but it has some performance problems that need to be ironed out before it can be released. 

I'm going to close this issue so we can keep conversation in #1026
