### ISSUE TITLE
Shows dates on issue card

### ISSUE THREAD

**Issue by ambynair** [ZenHubIO/support#1110]
With new release we can control what shows up on issues card. wondering if I can get created date or pipeline move date ( second image)

![image](https://cloud.githubusercontent.com/assets/10192159/25911200/d1dbf7c0-3567-11e7-8c5e-08593d45b2cf.png)

Pipeline event date info like moved to this pipeline x days ago. it would be nice to show that x days on issue card.

![image](https://cloud.githubusercontent.com/assets/10192159/25911234/efcb1658-3567-11e7-8a31-891119ec4add.png)

**Comment by kendramoroz** [comment]
@ambynair great suggestion on ways we can improve the Board cards! While this information isn't yet accessible on the issue cards, I'll be sure to send this through to the design team. While we work on #156 / #1076 this is great feedback. Feel free to add any other feedback here related to information you'd like to continue to customize on your ZenHub Boards!

**Comment by kendramoroz** [comment]
Closing to track dates on cards here https://github.com/ZenHubIO/support/issues/737! Please subscribe there for updates :)
