### ISSUE TITLE
Zenhub Extension fails to install on GitHUB

### ISSUE THREAD

**Issue by schueren** [ZenHubIO/support#1114]
Using GitHUB Enterprise on Win 7 platform - Browser is Firefox v52. Installed ZenHub for FF, Installed Successfully message after plugin installed but no "Z" icon appears on Fire Fox tool bar and inside GitHUB the Boards option doesn't exist - options available "Code, Pull requests, Projects, Wiki etc.."

Have removed FF, Rebooted and reinstalled a fresh install of FFv52, install Zenhub plugin for FF but no change after successful message.

**Comment by kendramoroz** [comment]
@schueren would you mind sending through a private email to support@zenhub.com with the Enterprise environment your team is using? Sounds like you may be downloading the extension version meant for the cloud version of GitHub.com, where as ZenHub Enterprise have unique extensions that need to be downloaded. Happy to help you get started in the right direction. For privacy reasons, it's best to continue the conversation via email. 

Chat soon!

**Comment by Kevellen** [comment]
I have this same issue on a MacBook with Firefox 59.02 (64 Bit), Firefox add ons show ZenHub Extension 2.37.20 installed successfully but no Boards displayed.

**Comment by kendramoroz** [comment]
Hey @Kevellen can you contact us via support@zenhub.com with more information on whether you're using github on .com, or the Enterprise version, as well as any potential errors you're seeing - we can take it from there!
