### ISSUE TITLE
Zenhub Extension fails on Chrome for Mac.

### ISSUE THREAD

**Issue by aag0121** [ZenHubIO/support#1116]
I'm experiencing some issues with my extension of ZenHub. I'm using the extension for **Mac** (10.12.14) and the browser is **Chrome** (58.0.3029.110). 

How about the issue? Sometimes I start Chrome and I can see all the pages like this:
![c--nsgqxkaacbo5 1](https://cloud.githubusercontent.com/assets/22575055/26008784/8828dcb6-3746-11e7-9a33-c4fb1487c0d3.jpg)

I'm contact with Chrome support and told me that I can try _delete some extensions_ at once... and finally i determine that the extension that is caused the problem is ZenHub extension. I don't know why.

**Comment by kendramoroz** [comment]
@aag0121 Thanks for sending these details our way! ZenHub only interacts with GitHub, so it shouldn't be interfering with anything related to Google. Would you be able to open up the console (right click on the page, inspect elements, then proceed to the console tab) to show any errors that are related to seeing blocked out screens?

Any steps to reproduce this would also be super helpful! 

![image](https://cloud.githubusercontent.com/assets/11036230/26020236/e5c52a20-3730-11e7-9982-d96d7306bcfc.png)

**Comment by aag0121** [comment]
Yes, is _really strange._ Sorry but the console looks like this when the issue appears: 

<img width="1266" alt="2017-05-14 19 12 47" src="https://cloud.githubusercontent.com/assets/22575055/26036245/416bd784-38da-11e7-89f3-f0220c8a0efc.png">

Sorry, I don't know **how** and **why.** The only thing that I know is that when the issue appears, if I deleted Zenhub extension, the issue disappeared.

Any suggestions or recommendation?
