### ISSUE TITLE
Issue card not updated after attaching a release (refresh required)

### ISSUE THREAD

**Issue by fabriziocucci** [ZenHubIO/support#1123]
### Steps to reproduce
1. open a random issue on the board (or create a new one);
2. attach a random release to that issue;
3. close the issue pop-up (this brings you back to the board);
4. the issue card does **not** contain the release just attached;
5. refresh page;
6. the issue card now contains the attached release.

### Notes
* verified with ZenHub for GitHub Enterprise 2.16.2 on Chrome.

**Comment by kendramoroz** [comment]
@fabriziocucci good catch! Bumping this over to known issues while we work on a fix 💪 🐛

**Comment by azenMatt** [comment]
This is live :)
