### ISSUE TITLE
Boards not Loading Multiple Repos

### ISSUE THREAD

**Issue by mrdiegel** [ZenHubIO/support#1125]
The feature that allows multiple linked repos to load in one board is no longer working for this project with around 75 linked repos:

![screen shot 2017-05-23 at 3 58 24 pm](https://cloud.githubusercontent.com/assets/15656203/26373730/ac38f536-3fd0-11e7-969d-5c4af40207cb.png)

**Comment by kendramoroz** [comment]
@mrdiegel Hey Michael, Kendra here! Mind sending through any errors you're seeing in the dev console when getting this error? Feel free to post here or fire them over to support@zenhub.com

One other question: what operating device/browser are you leveraging when seeing this error?

**Comment by mrdiegel** [comment]
![screen shot 2017-05-23 at 4 20 25 pm](https://cloud.githubusercontent.com/assets/15656203/26374690/37dfa19a-3fd4-11e7-8288-424a0dcce50e.png)

**Comment by mrdiegel** [comment]
@kendramoroz 

**Chrome:** 58.0.3029.110 (64-bit)
**Mac OS:** 10.12.3 (16D32)  

![screen shot 2017-05-23 at 4 26 56 pm](https://cloud.githubusercontent.com/assets/15656203/26374827/adfaf79e-3fd4-11e7-987d-9435b9a952e6.png)

![screen shot 2017-05-23 at 4 20 25 pm](https://cloud.githubusercontent.com/assets/15656203/26374690/37dfa19a-3fd4-11e7-8288-424a0dcce50e.png)

**Comment by kendramoroz** [comment]
Just closing the loop here as well! Your team was able to report that a recent fix we launched has fixed the issue :). Let me know if it resurfaces!
