### ISSUE TITLE
How to unmerge two repos?

### ISSUE THREAD

**Issue by JKGisMe** [ZenHubIO/support#1126]
We have merged the boards for two repositories but now we would like to separate them again. I cannot figure out how to unmerge them. Is there a way?

**Comment by kendramoroz** [comment]
@JKGisMe You can unmerge Board views by heading back to the original dropdown where you merged them and hovering over the repo you'd like to disconnect! On the right is a link that'll appear. Click there to disconnect the repo :)

![image](https://cloud.githubusercontent.com/assets/11036230/26422791/1323ea58-4080-11e7-8812-75d53d27df54.png)

Let me know if you have any other questions I can help with!

**Comment by JKGisMe** [comment]
I dont know how I didn't see this! Thank you so  much. 😆
