### ISSUE TITLE
Add time estimate for reviewing pull requests

### ISSUE THREAD

**Issue by onesneakymofo** [ZenHubIO/support#1128]
We use time estimate tracking ZenHub with the following:
- Issues contain how much time we think they will take
- Pull requests contain how much time we actually spent on the issue

I would like to request a feature that adds the ability to attach time estimates to a code review. This would provide more insight on developer's estimates during each sprint.

**Comment by kendramoroz** [comment]
@onesneakymofo thanks for writing in! A great suggestion and a popular one amongst the community. Bumping this over to discussion for the time being. I'll be sure to post any updates on functionality around time tracking when they become available 😄

**Comment by kendramoroz** [comment]
Hey @onesneakymofo I'm working on cleaning up our support community, consolidating time tracking into a single issue for better tracking. If you're still interested in tracking updates, please subscribe to https://github.com/ZenHubIO/support/issues/218!
