### ISSUE TITLE
Add an option to close multiple issues/move them to "Closed" pipeline

### ISSUE THREAD

**Issue by aamorozov** [ZenHubIO/support#1134]
Currently, it is only possible to move them across the pipelines, but not actually close them or drag them to "Closed" pipeline. "Move to pipeline" modal has only options to move them across existing pipelines, but again, not actually close the ticket: 

![screen shot 2017-05-31 at 4 55 56 pm](https://cloud.githubusercontent.com/assets/10227658/26653686/e6f1ea32-4621-11e7-8f1f-ef831ed5d11e.png)

**Comment by kendramoroz** [comment]
@aamorozov Delightful news for you! We're going to be launching a way to bulk close issues via multi-select actions very soon 🚀 . This will allow you to filter by a milestone, for example, select-all, and bulk-close at the end of the sprint to save time manually closing each issue. Here's a sneak peak :)

![may-31-2017 14-06-05](https://cloud.githubusercontent.com/assets/11036230/26654138/7e38f7e0-460a-11e7-9eb7-8b7546da1275.gif)

**Comment by aamorozov** [comment]
@kendramoroz Awesome, thank you for quick response !

**Comment by azenMatt** [comment]
This is now live - issues can be closed via movement to the closed pipeline :)
