### ISSUE TITLE
Add "blocked" icon on issue cards in the board

### ISSUE THREAD

**Issue by matgerard** [ZenHubIO/support#1135]
It should be very useful to directly see in the board that an issue is "blocked" by the new (awesome !) Dependency feature.

May be also add the possibility to add a "blocking" icon, less useful for me but could be in other cases...

Of course, icons display should be enabled/disabled in the "View options -> Show on issue card" menu.

**Comment by kendramoroz** [comment]
@matgerard Great suggestion and a common one we've heard since launching dependencies. Bumping this over to discussion—I'll be sure to provide updates as soon as they come available on enhancements with dependencies :)

**Comment by matgerard** [comment]
@kendramoroz Thank you for the feedback !

**Comment by aramir** [comment]
this is definitely will be useful

**Comment by jonnycornwell** [comment]
We are currently adding dependencies then manually adding a blocked tag so it is visible on the board. Obvious problem here is that when it is unblocked the board won't update to reflect this automatically.

It would also be great to filter to find blockers too

**Comment by azenMatt** [comment]
please see - https://github.com/ZenHubIO/support/issues/1184#issuecomment-328232362 - for more details on this. 

I'l close this issue to help keep discussion in one place. If you subscribe to the issue above, I can let you know once this is live 😄
