### ISSUE TITLE
zenhub saying a regular issue opened 11 minutes ago has been an epic for 5 days

### ISSUE THREAD

**Issue by ldemailly** [ZenHubIO/support#1144]
See https://github.com/istio/istio/issues/373

![screen shot 2017-06-06 at 3 15 36 pm](https://user-images.githubusercontent.com/3664595/26854481-2b3fec40-4acb-11e7-9530-a734a1a9224e.png)

I wonder if it's triggered because I added that issue to 2 epics

**Comment by ldemailly** [comment]
meta off topic question: where is the data about epic<->issues linkage stored and can it be queried (and in this case checked/debugged) outside of the UI ? api to dump the extra info ?
and couldn't that be done through regular git comments / references?

**Comment by ldemailly** [comment]
hi @kendramoroz, thanks for looking into this, did you find anything ?

**Comment by kendramoroz** [comment]
@ldemailly Thanks for the follow-up! We're digging into the issue — I'll post updates here shortly!

**Comment by kendramoroz** [comment]
@ldemailly Checking out the initial issue where this occurred it looks like the timezones has balanced out with the timestamp—Have you noticed this same timestamp issue happening across other issues?

**Comment by ldemailly** [comment]
the epic loop seems to have disappeared now - but 5 days delta can't be timezone issue

**Comment by kendramoroz** [comment]
🤔  That's true! We'll keep our eyes on this one, but if you notice this happen again please let me know and we can dig into the specific case you find it occurring on.

**Comment by ldemailly** [comment]
Any idea about https://github.com/ZenHubIO/support/issues/1144#issuecomment-306633935 ?

Otherwise you can close this as it fixed itself (but curious about the above for next time)

**Comment by kendramoroz** [comment]
@ldemailly Best place to access that information is through [our public API endpoints](https://github.com/ZenHubIO/API)!

**Comment by ldemailly** [comment]
thx
