### ISSUE TITLE
Keep getting logged out

### ISSUE THREAD

**Issue by lukescott** [ZenHubIO/support#1151]
In the past couple weeks I've been logged out of ZenHub on a daily basis. My session used to persist, but now I have to re-login every day.

**Comment by kendramoroz** [comment]
@lukescott Hey Luke! Sorry to hear you've had some logout troubles here. Is there anything in particular that you noticed when this started happening? Such as having left a tab open and it signing you out in the morning?

If you could send through any other additional insight that you can think of it'd help us dig into specifically what might be happening!

**Comment by kendramoroz** [comment]
@lukescott Just following up to make sure you're not experiencing this issue still. Any notes from your end?

**Comment by lukescott** [comment]
My session has been persisting at least the last few days. Appears to no longer be an issue.
