### ISSUE TITLE
Moving an already closed issue 

### ISSUE THREAD

**Issue by SvanBoxel** [ZenHubIO/support#1153]
When I want to move an issue to a different repo, Zenhub gives the user 2 options:

The user can either clone the issue to a new board, without affecting the original issue, OR the user can clone the issue and close the original issue.

However, if I want to clone an already closed issue, it still gives me the option to close the original issue. 

This causes unclarity for the user. Am I moving the right issue? Why isn't this thing already closed? etc.. 

<img width="532" alt="screenshot 2017-06-14 21 21 38" src="https://user-images.githubusercontent.com/24505883/27150511-cc2d7190-5147-11e7-9a34-d081128ed970.png">

_Closed issue that I want to move_

**Comment by kendramoroz** [comment]
@SvanBoxel Thanks for sending this through—Good catch! I'll send this to our product team. 
Feel free to send through any other feedback or questions I can help with.

**Comment by SvanBoxel** [comment]
GitHub offers this feature now as well. https://help.github.com/articles/transferring-an-issue-to-another-repository/
