### ISSUE TITLE
Closed issues/PRs not being displayed in 'Closed' column

### ISSUE THREAD

**Issue by djlebersilvestre** [ZenHubIO/support#1154]
I'm not sure what happened. The issues were being displayed earlier today but now I can't see them on the board in the last column. The only way to see all closed PRs and issues now is by going to milestone view or burndown chart. 

The board - `Closed` column with only one issue:
<img width="1387" alt="screen shot 2017-06-15 at 6 34 16 pm" src="https://user-images.githubusercontent.com/815122/27204555-e61e0f4e-51f9-11e7-95da-7257118a0c72.png">

The view selection for the project board:
<img width="345" alt="screen shot 2017-06-15 at 6 34 01 pm" src="https://user-images.githubusercontent.com/815122/27204585-0391e596-51fa-11e7-9430-d6da3d65fe6a.png">

The closed issues under burndown chart view:
<img width="1218" alt="screen shot 2017-06-15 at 6 35 09 pm" src="https://user-images.githubusercontent.com/815122/27204611-1d77220a-51fa-11e7-8c98-2171811ce0a7.png">

**Comment by djlebersilvestre** [comment]
Another observation: this might be related to `Connect with an issue` button since all the PRs that are not showing on the board, were connected and then disconnected from an issue.

**Comment by kendramoroz** [comment]
@djlebersilvestre Thanks for sending this our way—I'm going to loop in our engineering team to see what might be causing this. One thing: If you click `load more issues` in the closed pipeline do they appear at all?

Would you also be able to check the dev console for any errors that might be appearing?

**Comment by djlebersilvestre** [comment]
I tried that (`load more issues`). Nothing happens.
Errors in dev console:
![image](https://user-images.githubusercontent.com/815122/27234278-6db0b8a4-528a-11e7-8596-86c72ab2839a.png)

![image](https://user-images.githubusercontent.com/815122/27234291-7d07a3a8-528a-11e7-82b3-88d61f2abfe2.png)


Thanks

**Comment by djlebersilvestre** [comment]
Another info, if I open the Epic that contains the PRs associated and click on `See this Epic on the Board` it works:
![image](https://user-images.githubusercontent.com/815122/27234549-6535522e-528b-11e7-9399-6ae6896836e2.png)

![image](https://user-images.githubusercontent.com/815122/27234585-83fff2a4-528b-11e7-8859-ada419950775.png)

**Comment by kendramoroz** [comment]
@djlebersilvestre I recognize it's been a while on this one 😬 - please let me know if you're still experiencing filter woes and we'll re-open this and get to the bottom of it ASAP.

**Comment by psugihara** [comment]
Still seeing it. Had 16 points in the column, hit "Load more issues..." and had 26.
