### ISSUE TITLE
Estimated point is limited to 40

### ISSUE THREAD

**Issue by piwii** [ZenHubIO/support#1155]
Why extimated point is limited to 40 ?
I would like to macro estimate EPIC but i cant set more than 40 points :-(

**Comment by kendramoroz** [comment]
@piwii You can customize the story points if you'd like! Simply type the number value you're interested in adding and click the create story point option. 

[This guide here walks through](https://www.zenhub.com/guides/what-are-software-estimates#changing-estimates-in-zenhub) this in more detail but let me know if you have any other questions I can help with!

![create-new-story-point](https://user-images.githubusercontent.com/11036230/27233180-71e29bd0-526d-11e7-93c2-8f2513590f43.png)
