### ISSUE TITLE
Add dependency button and search only showing issues #1 and #2

### ISSUE THREAD

**Issue by VhatAmI** [ZenHubIO/support#1156]
![image](https://user-images.githubusercontent.com/10841983/27234057-4e62bc4e-5281-11e7-826d-0fe7c51e3762.png)

Trying to add blockers to a story but only allows me to select from 2 issues. I have 10 open issues.

**Comment by kendramoroz** [comment]
@VhatAmI Thanks for sending this through and sorry to hear you're having some trouble here—I'm going to loop in our engineering team here and see what might be happening. I'll get back to you shortly!

**Comment by VhatAmI** [comment]
This problem was when I was in the "Issues" Tab of the repo looking at individual issues, When I went to the "Boards" Tab and opened the issue I was able to see all issues and afterwards when back in the issues tab things were populating correctly again.

**Comment by kendramoroz** [comment]
@VhatAmI Glad to hear it's resolved! Keep us in the loop if the problem persists
