### ISSUE TITLE
Can't get the set estimate api to work

### ISSUE THREAD

**Issue by markwilkie** [ZenHubIO/support#1158]
Hoping you guys can point me in the right direction.  The GET end points are working well....

**URL:**
https://api.zenhub.io/p1/repositories/70183192/issues/971/estimate

**Header:**
User-Agent: Fiddler
X-Authentication-Token: xxxxxxxx
Host: api.zenhub.io
Accept: application/json
Content-Length: 18

**Request Body:**
{
"estimate":1
}

**Error Received:**
{"message":"estimate value must be a number NaN undefined"}

**Comment by kendramoroz** [comment]
@markwilkie Thanks for getting in touch and sorry for the few days delay here! Looks like there's a potential 🐛  with this endpoint. Our development team is investigating. I'll get back to you shortly :)

**Comment by markwilkie** [comment]
@kendramoroz thanks!

**Comment by ahuling13** [comment]
@kendramoroz Any update on this? I believe I'm hitting the same issue.

**Comment by olegzd** [comment]
I've tried recreating the issue with no luck.

Can you try the following curl command? (replace with your repository id, issue number, and token)

```
curl -X PUT \
  https://api.zenhub.io/p1/repositories/REPO_ID/issues/ISSUE_NUMBER/estimate \
  -H 'content-type: application/json' \
  -H 'x-authentication-token: YOUR_TOKEN' \
  -d '{
	"estimate":1
}'
```

If that doesn't work, drop us an email: support@zenhub.com

**Comment by ahuling13** [comment]
It appears that the problem was not including the 'content-type': 'application/json' header. The original poster also did not list this in one of his headers. The curl command you shared worked and the only difference from my python request was the additional header. Adding that header addressed the issue. Thank you for your help!

**Comment by olegzd** [comment]
Awesome! Glad to help :)
