### ISSUE TITLE
I want to be able to choose what elements on issue cards appear when viewing the board

### ISSUE THREAD

**Issue by denisvlr** [ZenHubIO/support#116]
The "advanced view" checkbox doesn't show up anymore, so i'm stuck in the advanced mode where all the labels are displayed.

![image](https://cloud.githubusercontent.com/assets/3200104/4178171/1a1297e6-367f-11e4-8203-f0e94a39cea9.png)

I'm on Chrome 36 on Ubuntu, and there are no errors in the console.

Did I miss something?

**Comment by kendramoroz** [comment]
@danbartlett @kfbishop @denisvlr Happy to announce that we've launched **Board View Settings** where you can now customize your board view from one easy dropdown, including toggling labels! If you don't see the **View** button left of the repo filter, a quick re-install of the extension will bring you up to the latest version with this option. 

Look forward to hearing your feedback on the latest enhancements to the board 🎉 

![screen shot 2017-01-31 at 10 19 17 am](https://cloud.githubusercontent.com/assets/11036230/22478479/dc89c7c2-e79e-11e6-852c-496f8912fbaf.png)
