### ISSUE TITLE
change-pipeline keyboard shortcut is broken

### ISSUE THREAD

**Issue by olets** [ZenHubIO/support#1160]
According to https://www.zenhub.com/guides/time-saver-features#keyboard-shortcuts, `p` is the shortcut to "change an issue's pipeline." I'm guessing that means it opens the Pipeline pop-up? Regardless of whether it does that or something else, it conflicts with GitHub's `p` shortcut for opening the Projects pop-up.

**Comment by kendramoroz** [comment]
@olets Good spot! We're removing this from our documentation. With `p` now taking Projects, we'll work on updating our Pipeline dropdown shortcut.
