### ISSUE TITLE
make keyboard shortcut documentation more findable/prominent

### ISSUE THREAD

**Issue by olets** [ZenHubIO/support#1162]
I found the some keyboard documentation at https://www.zenhub.com/guides/time-saver-features by digging around the ZenHub site, only after extensive Googling got me nowhere

**Comment by kendramoroz** [comment]
Hey @olets 👋  We've just launched our shortcut improvements 🎉 .

You can check out the complete suite of new shortcuts here: https://www.zenhub.com/guides/keyboard-shortcuts as well now easily navigate to the complete list through the `Settings` dropdown (or in the web app using `z` `s`):

![image](https://user-images.githubusercontent.com/11036230/31569772-825b39d6-b032-11e7-91cb-f12d36ff6ffc.png)


Let us know what you think ✨
