### ISSUE TITLE
add backtick ` to keyboard shortcut documentation

### ISSUE THREAD

**Issue by olets** [ZenHubIO/support#1163]
Backtick (`` ` ``) is an undocumented ZenHub shortcut to open the Boards. It's mentioned in https://github.com/ZenHubIO/support/issues/531#issuecomment-208106766, and is probably familiar to anyone who uses ZenHub and types Markdown (because it's easy to inadvertently trigger a switch to Boards), but it isn't listed in https://www.zenhub.com/guides/time-saver-features#keyboard-shortcuts

**Comment by kendramoroz** [comment]
A fix will be live shortly that adds this to the shortcuts! Thanks for mentioning this 🚀
