### ISSUE TITLE
Get "message":"missing authentication token in headers" message when token is already in the header

### ISSUE THREAD

**Issue by bigmianhua** [ZenHubIO/support#1164]
Hi, I am using zenhub API to get the epics of an repository, I've generated the token in the setting but both including it in header and adding it in url as "access_token=" are not working, but this token works for github api, I wonder where can I get the right token for zenhub api

**Comment by kendramoroz** [comment]
@bigmianhua Thanks for getting in touch! Can you try signing out and back into ZenHub (through the extension by clicking on it and heading to _signout_? This plus a refresh should help eliminate the issue you're having :)

**Comment by bigmianhua** [comment]
@kendramoroz Thanks for response. But I just tried, it still doesn't work for me, is it because I am using zenhub enterprise?

**Comment by kendramoroz** [comment]
@bigmianhua Would you be able to send through more details about the Enterprise extension you're using / your organization via support@zenhub.com and we can follow-up in more detail to make sure you're on the right track!

**Comment by bigmianhua** [comment]
@kendramoroz I have sent the email to support@zenhub.com, thank you
