### ISSUE TITLE
Select burn pipeline not working in reports for closed milestones

### ISSUE THREAD

**Issue by mjuez** [ZenHubIO/support#1165]
Hello, I am trying to select Review/QA pipeline when making reports, with open milestone is working good, but with closed ones is not working. It only shows the issue closing point (few weeks ago this worked fine).

![imagen](https://user-images.githubusercontent.com/7154276/27530560-8563796a-5a59-11e7-9147-a4a7b6e7ad42.png)

I think the problem may be related with the behaviour in reports view, which gets the milestone issues with the state "New Issues".

![imagen](https://user-images.githubusercontent.com/7154276/27530707-218624b4-5a5a-11e7-9bbb-fc5beb4a1da5.png)

Thank you.
Regards, Mario.

**Comment by kendramoroz** [comment]
Hey Mario, thanks for getting in touch!

The Burn Pipeline will pick up on when the Issue was moved into the pipeline you've selected to define as "complete" — Looks like the completed issues in that list as you said are still in the New Issues Pipeline. On your Board are they appearing in the QA pipeline?

**Comment by mjuez** [comment]
Hello Kendra.

No, in the board appears as closed (because are closed). My problem is that I want to see the chart of the QA pipeline, and it only shows the closed pipeline. Currently the pipeline of those issues is "Closed" but before closing them, their pipeline was QA, and is not possible to see that in the chart.
For me, the last state is QA, and after the review process I close all issues at the same moment, thats why the chart of closed pipeline is not useful for me.

**Comment by mjuez** [comment]
Understood.
Thank you @kendramoroz, I thought that I was able to use ZenHub weeks ago as I described before.

Best regards.
