### ISSUE TITLE
Remove or fix tab dropdown

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#1168]
Since GitHub has combined several tabs into the "Insights" dropdown tab, the dropdown added by ZenHub looks out of place. And at most appears to only include one tab now.

![](https://user-images.githubusercontent.com/136959/27614485-b4713170-5b67-11e7-8c2a-6ad4be17ee08.png)

I'm probably being nit-picky, but this dropdown is no longer aesthetically pleasing and is no longer necessary. 

I'm not sure how others would feel, but to me the "Reports" tab could be moved into the "Insights" dropdown, but only if you feel like you *must* narrow the navigation tab bar.

**Comment by kendramoroz** [comment]
@Mottie Thanks for writing in! We've fixed this button to not be so large now 👍 . If you're not seeing this change yet, you should have the fix auto-update in your extension over the next 24 hours. Let me know if you don't see it come your way.
