### ISSUE TITLE
Board not show any issues

### ISSUE THREAD

**Issue by Ardenexal** [ZenHubIO/support#1170]
In the board no issues are being display at all, even closed ones 
![image](https://user-images.githubusercontent.com/2852475/27664109-02623c48-5ca9-11e7-9ca3-17174b7b4b8e.png)

as you can see there are open and closed issues that are assigned to me
![image](https://user-images.githubusercontent.com/2852475/27664150-2f3c96e6-5ca9-11e7-895f-fe7af077f971.png)

Only my user seems to be affected everyone one else's board in our company is  working fine.

Is this a Zenhub issue, was working fine yesterday?

**Comment by kendramoroz** [comment]
@Ardenexal Thanks for sending this in! We're working on a fix for this 🐛 - it should be live shortly! I'll post an update once it's live :)

**Comment by BenDTU** [comment]
Sounds like you guys are on top of this -  if it helps, it only seems to be only be occurring to users with Capital letters in their name.

**Comment by kendramoroz** [comment]
@Ardenexal @BenDTU We've released a fix for this ☀️

You can force an update on your extension by removing and re-adding the extension via our website, [zenhub.com](https://zenhub.com) otherwise the extension should auto-update with this fix over night :). Let me know if you don't see it over the next little while!

Cheers,

**Comment by BenDTU** [comment]
I'm getting a "Manifest File is Invalid" error when trying to install from the website now 😭

**Comment by kendramoroz** [comment]
🙊  Looks like you caught it mid-upgrade! If you[ grab it from the Chrome store ](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd)it should be good to go.

**Comment by Ardenexal** [comment]
Confirming fix works that for the fast turn around
