### ISSUE TITLE
ability to save / bookmark board views (filter presets)

### ISSUE THREAD

**Issue by zahrens** [ZenHubIO/support#1178]
@haoliu119 Hello, I was just trying this and it is not working in Firefox 52.2.1, with the plug-in I just re-installed.

**Comment by kendramoroz** [comment]
@zahrens Thanks for getting in touch! When you're using the extension and on the Board, applying filters. Can you send through a screenshot that includes the URL in it? The filters you set should be saved as parameters in the URL, which makes the link bookmark-enabled for future use! Let me know :)

**Comment by zahrens** [comment]
Hello @kendramoroz it appears that it is working now, maybe you delivered a patch or it was temporary.  I'll let you know if I see this issue again.  Thank you for getting back to me quickly!  BTW, I'm at IBM and my team is really enjoying using ZenHub.  Thank you!!

**Comment by kendramoroz** [comment]
Great to hear it's all fixed up! Let me know if anything else pops up 🎉
