### ISSUE TITLE
Move "Boards - Reports - Notifications" switcher in app.zenhub/mobile to the menu

### ISSUE THREAD

**Issue by aramir** [ZenHubIO/support#1179]
Currently there is too much real estate wasted on mobile with "Boards - Reports - Notifications" switcher. it would be nice if it could collapse into the menu instead of always being on-screen.

And if you can hide "filters"/"new issue" there - that would be even better.

**Comment by kendramoroz** [comment]
@aramir Thanks for the suggestion here! I've passed this through to our design team :). Bumping to discussion in this repo while we take a look at how to improve this experience.

**Comment by azenMatt** [comment]
we are revamping the navigation at the moment which will help with this
