### ISSUE TITLE
Move multiple issues to a pipeline

### ISSUE THREAD

**Issue by carlosperez** [ZenHubIO/support#118]
I just started using this minutes ago so I may just haven't discovered how to do this, but so far it hasn't been obvious how to move multiple issues to a pipeline at once... whether from the board view or from GitHub's Issues list page.

**Comment by robinzimmermann** [comment]
The enterprise tool we currently use lets you select multiple issues in a pipeline and drag them up or down. This is extremely convenient and having to go back to doing one at a time is a real drag. (See what I did there? ;) )

This is for the case where you may have a clump of stories or issues that you want to move as a block.

> We have discussed the ability to multi select and move but felt most use cases favoured moving individual issues as they are updated. 

Don't forget to also cater to your power users. It's good to aim for simplicity to attract new users, but power users performing repetitive tasks can get frustrated by the over-simplicity. :)

I vote for this issue.

**Comment by jorisnoo** [comment]
+1 – Being able to select multiple issues and change their milestone would be a killer feature.

**Comment by bradical** [comment]
:+1:

**Comment by andycleff** [comment]
+1 for multi select/move

**Comment by pjutard** [comment]
:+1: to multiple select / bulk actions!

**Comment by grantgordon** [comment]
Any movement on this?

**Comment by tomusiaka** [comment]
:+1:

**Comment by adambair** [comment]
Any updates?

**Comment by Nowaker** [comment]
Extremely needed.

**Comment by azenMatt** [comment]
v 2.15.1 was just released that allows you to move multiple issues at the same time :smile: 

Just hover over the right hand corner of the card, and select the gear icon:

![image](https://cloud.githubusercontent.com/assets/7584089/12286190/c92f11f2-b976-11e5-85a2-509bce07741c.png)

**Comment by Nowaker** [comment]
@azenMatt #310 suggests this is a ticket for mass changing milestones too. If so, it's not a case, it's still not possible.

**Comment by azenMatt** [comment]
Hi @Nowaker - I feel you on how much of a PITA that is... 

You are right that you can not do this at the moment, we have some awesome changes coming up for #424 that will be a positive step towards making this better. 

But I will make a new issue to explicitly track moving multiple issues into a milestone.

**Comment by torkiljohnsen** [comment]
@Nowaker Maybe I misunderstood here, but moving 20 issues from one milestone to another takes but 3 seconds using "vanillla" Github functionality?

1. Go to issues list, filter by milestone A
2. Mark all issues
3. Use the milestone dropdown to apply new milestone

Done.

**Comment by bradical** [comment]
> From the board view it's a bit harder indeed ;)

yes, and I think this is the point. I can quickly select multiple cards from the board using certain visual queues -- e.g. assignee, pipeline -- and then I might want to change their milestone. Right now, I'd locate those issues in the board and then open up the issue list in a different tab and find/multi-select the same set of issues that I located in a pipeline in the Zenhub board. It's just a bit more tedious.

**Comment by stephenakearns** [comment]
Hi @azenMatt - I'm trying this functionality out for the first time. I am able to do the multi-select, but when I click-n-drag to another pipeline, only the issue I click-to-drag moves, the others remain - no change. Very odd... user error?

**Comment by andycleff** [comment]
are you sure you've "multi-selected" issues? Function works fine for me, MacOS + Chrome.

**Comment by azenMatt** [comment]
Hi @stephenakearns - I am also unable to recreate this - would you be able to share a quick video of it happening? 


Also - as a heads up, next week we will be temporarily removing this functionality for a short period while we move over to our new board infrastructure. We are aiming to have it back 1-2 weeks later but don't want to delay the performance gains of the new version to migrate this over

**Comment by phil-homecu** [comment]
there is a whole host of "multiple" features needed.  

After selecting multiple cards:
- [ ] assign all to one person
- [ ] move to pipeline
- [ ] close
- [ ] assign label
- [ ] assign to milestone/epic
- [ ] ...

**Comment by torkiljohnsen** [comment]
Any news on when multi-select will be back in @azenMatt? No such option under my pipeline cogs right now from what I can tell, only "rename" and "delete" available?

**Comment by Startouf** [comment]
Can we reopen the issue please ? I'm missing that too ! My browser is really slow with all those extensions and multiple select -> pipeline transfer would be awesome.
During our sprint, we usually leave our finished issues in the "done" pipeline, so at the end of a sprint we can review what was done before closing the issues (which may include issues for several milestones).

**Comment by bradical** [comment]
👍  for @Startouf's request. We typically bulk move both "completed" and "unfinished" issues at the end of the Sprint and similarly bulk move a list of issues from the Backlog into the Sprint at the beginning. For us the ability to bulk update the Pipeline and the Milestone are the two most important capabilities here. Obviously, Milestone can be updated in bulk natively in Github but not using the issue's currently pipeline in Zenhub.

**Comment by azenMatt** [comment]
Hi @Startouf @bradical 

The good news here is that this is currently being worked on! It is being tracked here - https://github.com/ZenHubIO/support/issues/832#issuecomment-249014855 where you can also see the designs. 

This new implementation will also include the ability to bulk update other items such as milestone / epic / label / etc 

We are aiming to have this ready for internal testing by the end of this week - so it will hopefully make it live by the end of November, if not a little after 

Il re-open this issue to make it easier to track

**Comment by azenMatt** [comment]
this is live once again 😄  https://www.zenhub.com/blog/task-board-bulk-actions/

**Comment by Startouf** [comment]
Is it just me, or is it simply impossible to close all the selected issues ? When I click the move to pipeline, I don't have the option to close all issues ? SO how do I close my "done" issues at the end of the sprint ? :S

**Comment by cemsbr** [comment]
I can't select closed issues. I want to add them to a release that I've just created.

**Comment by kendramoroz** [comment]
@cemsbr I'd suggest subscribing to #999 to track progress on that one!

@Startouf pardon the delayed reply on your note here 😅  - Multi-select allows closing multiple Issues now through the Move to Pipeline > Closed option

**Comment by slamorte** [comment]
I just found out about Project Boards. I'm just looking for a way to bulk add 200 issues to a new project, rather than perform 200 individual drag-and-drops.

**Comment by kendramoroz** [comment]
Hey @slamorte if you are looking to populate and make bulk changes to Issues on your ZenHub Board, you can either leverage our [write API endpoint for pipelines](https://github.com/ZenHubIO/API#move-an-issue-between-pipelines) or if each batch of changes you're looking to make is less than 50 Issues, you can leverage our in-app multi-select to move issues enbulk without performing individual actions 🎉

**Comment by slamorte** [comment]
The API is beyond me at the moment. And in-app multiselect doesn't seem to work from the Add Issue column in Projects, unless I am missing something — do you mean the website when you mean in-app?

**Comment by kendramoroz** [comment]
@slamorte Sounds like you may be using GitHub Projects, which is separate from ZenHub Boards as it's a native GitHub function that isn't supported by ZenHub. Would you mind emailing us at support@zenhub.com with a screenshot and bit more details about your workflow so we can keep the conversation going without triggering a notification to others who subscribed to these issue previously? Happy holidays!
