### ISSUE TITLE
How to create a Webhook on Git.

### ISSUE THREAD

**Issue by viniiifarias** [ZenHubIO/support#1180]
I'm new at Zenhub's API and i want to know how can i create a webhook on GIT.

What URL i have to put at 'new webhook'?
How can i get this URL?

**Comment by kendramoroz** [comment]
Hey @viniiifarias thanks for getting in touch!

ZenHub webhooks provide events for ZenHub data, such as Estimates, Epics, or the movements of Issues in the Board between pipelines. The documentation for how to set up ZenHub wehbooks, as well as the events and their properties [can be found here](https://github.com/ZenHubIO/API#webhooks).

GitHub webhooks [https://developer.github.com/webhooks/] can be set up to subscribe to events on GitHub data (new Issues being created, new comments on existing issues, labels added to an Issue, comments on an issue, among others).

Let me know if you have any questions about getting anything set up in particular 🎉
