### ISSUE TITLE
App version - keyboard shortcuts

### ISSUE THREAD

**Issue by aramir** [ZenHubIO/support#1186]
Should be the same as in main version, in particular "F" and "B" shortcuts are not working.

**Comment by kendramoroz** [comment]
@aramir good spot! Issuing this up for the team and bumping to known issues while we get this fixed up in the web app :)

**Comment by kendramoroz** [comment]
✨  @aramir We've just launched a suite of 35 new Keyboard Shortcuts! You can check them out here: https://www.zenhub.com/guides/keyboard-shortcuts
