### ISSUE TITLE
Cannot access private repos on app.zenhub.com

### ISSUE THREAD

**Issue by connorjsmith** [ZenHubIO/support#1188]
I am the owner of a private repository on GitHub with 3 other users added as collaborators. When I navigate to app.zenhub.com and log in, I can see all of my private repositories and use the app as expected. However, when one of the other collaborators tries to do the same, the private repository does not appear and they are forced to use the extension on github.com instead.

**Comment by kendramoroz** [comment]
@connorjsmith thanks for getting in touch! Currently the web application, app.zenhub.com will pick up all GitHub Organizations, but if you’re using a private repo plan, you’ll have to change the URL to access these Boards via the web app outside of the extension. 

	For example, changing: https://app.zenhub.com/workspace/o/zenhub/getting-started

	To: https://app.zenhub.com/workspace/o/private-repo-name/private-repo-name

This is something we have on our radar if it’s the culprit, but hopefully this works for you!

**Comment by azenMatt** [comment]
Hi @ connorjsmith - this is now fixed, via the org selector in the webapp, you can now select other private repos you have access to (as long as they have granted ZenHub permissions) and also search for open source repos 

Let me know if this isn't working as expected for you!

**Comment by connorjsmith** [comment]
Seems to be working great, thanks a lot!
