### ISSUE TITLE
velocity report not showing story points for closed milestones so average velocity is messed up

### ISSUE THREAD

**Issue by robneville73** [ZenHubIO/support#1189]

**Comment by kendramoroz** [comment]
@robneville73 Thanks for getting in touch and sorry about the trouble you're experiencing with Velocity reports. 

Mind sending through a few screenshots of what you're seeing to help us debug further? Feel free to fire them over to support@zenhub.com so as to not post private information in our public forum here. 

Looking forward to hearing from you!
