### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by pfista** [ZenHubIO/support#119]
Any plans for slack integration to give updates on issues moving through the pipeline?

**Comment by joshwouden** [comment]
This would be extremely useful. Please keep us updated?

**Comment by ian** [comment]
+1

**Comment by alanjames1987** [comment]
+1

**Comment by CumpsD** [comment]
+1

**Comment by prathe** [comment]
+1

**Comment by neellukka** [comment]
+1

**Comment by aj-thilakan** [comment]
+1

**Comment by sattarab** [comment]
+1

**Comment by jperl** [comment]
+1

**Comment by michaelpelletier** [comment]
+1

**Comment by alexparish** [comment]
+1

**Comment by bozkay** [comment]
+1

**Comment by lavluda** [comment]
+1

**Comment by KiloTango** [comment]
+1

**Comment by bozkay** [comment]
@azenMatt Our team uses zenhub+github+slack - we would love to see issues move through the pipeline in slack. Also, seems that slack integration is the most popular feature request. Any news on it's development?

**Comment by LionHottabych** [comment]
+1

**Comment by sweetrocker22** [comment]
:+1:

**Comment by Smashmint** [comment]
+1

**Comment by matejkastner** [comment]
Hallo @azenMatt, how many votes are needed to get this issue to sprint?

**Comment by azenMatt** [comment]
Hi @matejkastner - I think this has enough :+1:s already to make it a high priority :smile: 

Coming very soon!

**Comment by matejkastner** [comment]
Wow! @azenMatt thanks for good news! Looking forward :+1: :)

**Comment by dshahin** [comment]
:+1:

**Comment by vsteward** [comment]
any updates? last comment was 24 days ago.  Looking forward to Slack integration too

**Comment by andreackinney** [comment]
+1

**Comment by matejkastner** [comment]
Hallo @azenMatt :) I hope you have same great day as we in Czech Republic :) do we know already in which sprint/milestone/month is integration with slack planned to start development / be developed..? :) have a sun shining :sunny:

**Comment by azenMatt** [comment]
Hi @matejkastner - thank you, it is a lovely sunny day here in Vancouver as well :) 

No hard ETA for release right now, but @Mathieuu is working hard on it - as soon as he is happy with it we will get it in your hands :smile:

 `if you are going to twist my arm for a release date.... then i'd say mid-July (but don't tell anyone I told you that :wink: )`

**Comment by aherve** [comment]
That would be brilliant !

**Comment by matejkastner** [comment]
*wooooooooooow :)* eagerly waiting and being almost horny about that :) combination of zenhub plus slack makes me fly :+1: :)

**Comment by ijin** [comment]
+1 can't wait!

**Comment by fruwe** [comment]
+1 me too

**Comment by dsklikes** [comment]
+1

**Comment by nickbuddendotcom** [comment]
+1

**Comment by zippeurfou** [comment]
+1

**Comment by azenMatt** [comment]
Slack integration is here! :boom: 

Here is how to get set up... 

Head over to your ZenHub Dashboard - https://dashboard.zenhub.io and select the 'slack' tab 

Once this populates all your repositories, you should get something like this: 

![image](https://cloud.githubusercontent.com/assets/7584089/8964864/de9a0b96-35dc-11e5-9c0b-1abcde43810c.png)

From here, you just need to select which repository you would like to add to slack, generate a webhook from the slack webpage (via the 'generate a hook here' link), add that hook into the ZenHub dashboard along with an optional description:

![image](https://cloud.githubusercontent.com/assets/7584089/8964945/4d036aa0-35dd-11e5-981d-955040aa96e9.png)

Hit 'add' and then you are good to go:

![image](https://cloud.githubusercontent.com/assets/7584089/8964964/69061338-35dd-11e5-947e-feb68458817a.png)

![image](https://cloud.githubusercontent.com/assets/7584089/8965055/ea9edd94-35dd-11e5-9464-f458a1f7ae7f.png)

In order to see these, the user who moves the issue will need to be on v2.4.1and above - which was released last night so the Chrome store should have sent it to at least 90% of users by now. 

Please give it a try and let me know your feedback!

**Comment by sweetrocker22** [comment]
@azenMatt This is great to hear! As you said, after you add the hook you're good to go. I checked that I'm on the most recent version of Zenhub after adding the hook and I wasn't able to get any notification after moving cards. Does it require further customization within the webhook?

**Comment by azenMatt** [comment]
That should be it... Can you send an email through to support@zenhub.io and we can troubleshoot?

**Comment by sweetrocker22** [comment]
yep I’m on it :)

**Comment by zippeurfou** [comment]
Works fine here!
Awesome!

On Wed, Jul 29, 2015 at 2:16 PM, Caitlin Daily <notifications@github.com>
wrote:

> yep I’m on it :)
>
> On Wed, Jul 29, 2015 at 1:15 PM, Matt Butler <notifications@github.com>
> wrote:
>
> > That should be it... Can you send an email through to support@zenhub.io
> and we can troubleshoot?
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ZenHubIO/support/issues/119#issuecomment-126046847
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/119#issuecomment-126047239>.
>



-- 
Marc Ferradou : www.marc.ferradou.fr                       [image: View my
profile on LinkedIn]View my profile
<http://www.linkedin.com/in/marcferradou>

**Comment by azenMatt** [comment]
Thats great @zippeurfou! 

We also have it working for @sweetrocker22 now :smile:

**Comment by pjkelly** [comment]
Works great!  Thanks so much. :tada:

**Comment by aherve** [comment]
Awesome

**Comment by lavluda** [comment]
Awesome , it works :)

**Comment by matejkastner** [comment]
Hallo @azenMatt - slack integration is great thing :) thanks a lot :+1: :smile: 
just i have found one difference to classic ZH window in Chrome - when you *reprioritize* GH isse in ZH, then it gives you message, that you have *moved* issue in same pipeline, this would be better to change and notify slack about *reprioritization* instead, thanks a lot ;)

and btw if you would even post pictures of users to slack it would be fabulous - just an idea, thing above is more important. thanks ;)

![slack-vs-zenhub-reprio](https://cloud.githubusercontent.com/assets/10279303/9039936/0938d212-39ff-11e5-8ad9-36616d05fcd7.png)

**Comment by azenMatt** [comment]
Thanks for the feedback @matejkastner - we are looking at this right now and will have a fix out soon!

**Comment by notmyrealcode** [comment]
For some of our users the Slack integration says ** instead of their name, even though they now have GitHub names. Anyway to fix this? Or is it some sync that will happen at some point?

**Comment by azenMatt** [comment]
Hi @notmyrealcode - we have a fix coming for this one soon! 

It is occurring when a user does not have a full name attached to their GitHub account - we are making a change so that in this case we will fall back to their GitHub username.

**Comment by azenMatt** [comment]
Both of these fixes are now live in 2.5.3

- [x] Usernames are shown if full name is not found 
- [x] Reprioritization has its own message

As before - all your team members will need the latest version to see them

:beers:
