### ISSUE TITLE
Reports: view progress on Epics

### ISSUE THREAD

**Issue by kashif-fh** [ZenHubIO/support#1191]
ZenHub has a nice milestone burndown chart but I don't see a similar chart or report that shows progress for all epics, each of which would usually span milestones. I see an epic's progress when I open the Epic Issue, of course, but it would be nice to see this centralized in the reporting area.

**Comment by imwra** [comment]
I spent a decent 30 min searching for older requests that might be similar to this one but couldn't find any... have no users asked for this?

Do ZenHub user only use the `Boards` view to see the progress of epics?

We also need this same type of reporting/view. I imagine it would be very similar to GitHub's Milestone overview page:
![issues_milestone_overview](https://user-images.githubusercontent.com/16008216/28990976-9d7753da-7950-11e7-9581-a713e12a2b51.png)

We use a ZenHub competitor that allows us to view all our Milestones (cross-repo) and the progress (% and deadline) on one page. That is very helpful and the only reason we have stayed with them.

@kendramoroz is this something on the roadmap?

**Comment by kendramoroz** [comment]
@imwra Great question! Having a home for Epics that enhances the information available to track progress is definitely on our radar! I'll be sure to post further updates here about improvements we're making as they become available 🚀

**Comment by imwra** [comment]
Taking a closer look at ZenHub seems like the same would be applicable for Releases....

**Comment by imwra** [comment]
Hey @kendramoroz, I recently came across the Milestones page... did some searching and didn't find any blog post or similar talking about this, was this a new release or just something I had not seen previously?

**Comment by kendramoroz** [comment]
@imwra It's a new feature to the web app, but there wasn't any official blog post on this one! Surfacing feature launches in a more present way is on our radar - is having these types of new feature notifications in-product something you'd find value in? Any particular medium you'd like to learn about new functionality?

**Comment by imwra** [comment]
Just a blog post would be great. Does ZenHub have a public roadmap or something?

**Comment by umkaline** [comment]
I'm interested in such report. Any progress?

**Comment by kendramoroz** [comment]
Closing in favor of #665 to track Epic-specific Burndowns!
