### ISSUE TITLE
Zenhub not allowing to create new story point estimates

### ISSUE THREAD

**Issue by clickthisnick** [ZenHubIO/support#1194]
![Zenhub Issue](https://user-images.githubusercontent.com/7855189/28538032-c8377aac-707a-11e7-9889-01007c9450de.png)

#### Reproduction Steps:
1.) Go to a pull request
2.) Go to estimate and type in a number that currently does not exist ( .75)
3.) Click the "Create a new story point"

#### Outcome:
The "How complex is this issue?" modal closes, no estimate is on the pull request, and .75 is not part of the list of points

#### Wanted Outcome:
This works at least a couple weeks ago where it would actually assign that .75 points to the pull request and create the .75 as another point value in the estimate dropdown

This is the second issue with the points, please allow us to keep entering non whole numbers here, its def a deal breaker for my team :(

**Comment by kendramoroz** [comment]
@clickthisnick If you had a 0 in front of the `.` it should work!

**Comment by clickthisnick** [comment]
@kendramoroz You da best
