### ISSUE TITLE
Integrate labels and boards

### ISSUE THREAD

**Issue by kimberlyplima** [ZenHubIO/support#1195]
Gitlab allows integration between labels and boards. So, when you create a board a new label integrated with this board is automatically created (and it also has the same name). Furthermore, when you moves an issue in the pipeline, the label is updated according to the board.
However, I don't use gitlab rs and I think it would be pretty sweet if you could implement this enhancement.

Here's a gif showing what I explained above:
![jul-25-2017 10-42-25](https://user-images.githubusercontent.com/22302027/28575148-73928d00-7126-11e7-9c98-21ce63ce2fbe.gif)

**Comment by caharding** [comment]
+1 I need auto labels assigned to work stages. This way my developers can filter issues in list view by what stage they are in.

**Comment by kendramoroz** [comment]
👋  Hey everyone - thanks for your support on this Issue! We've decided to close this out to focus on delivering a great user experience that helps teams build better workspaces and report on scope changes. You can read more here: https://github.com/ZenHubIO/support/issues/19#issuecomment-359064793
