### ISSUE TITLE
Multi repo boards

### ISSUE THREAD

**Issue by falconmick** [ZenHubIO/support#1196]
I tried following this: https://www.zenhub.com/blog/multi-repo-boards-have-arrived/ to connect the issues to the main repo for my project (we are working with a forking methodology where all changes are made on another repo and we send a cross-fork PR to get our changes in) but once I finish selecting where to put the merged issues it just goes to the settings page for a second and then snaps back to the boards page with no new repo in the repos list.

I have push access to both repos and have tried merging in both directions

**Comment by kendramoroz** [comment]
@falconmick That's odd behaviour! Would you be able to try re-merging once more and send over anything that appears in the developer console once this action is done but doesn't actually merge? Sounds like there might be a background error here preventing the merge! Feel free to post here, or if you'd like to, you can send it my way at support@zenhub.com!
