### ISSUE TITLE
Velocity report is not rendering

### ISSUE THREAD

**Issue by dylans** [ZenHubIO/support#1199]
For at least a few weeks, our velocity report is failing to display

* URL: https://github.com/dojo/meta/milestones#reports?report=velocity
* Console error: Failed to load resource: the server responded with a status of 400 (Bad Request)
api.zenhub.io/v4/repositories/36094309/reports/velocity 
* Platforms tested: Chrome (59.0.3071.115) and Firefox (54.0.1) on macOS (10.12.5)

**Comment by kendramoroz** [comment]
Hey @dylans thanks for getting in touch and sorry about the trouble here. 

Just a few questions to help debugging:
- How many connected repositories do you have on the workspace where you're seeing this error?
- Approx. how many issues are within each of your last few closed Milestones? 
- How many Issues, approx., do you have across your workspace where you're seeing this error? 

(Feel free to reach out via support@zenhub.com if you'd prefer to keep this information private)

**Comment by dylans** [comment]
Sorry for the delayed reply...

* ~ 35 repos
* >100 issues per milestone (we run our milestones by month), < 1000
* Including closed issues, probably a few thousand issues and PRs in total

**Comment by kendramoroz** [comment]
Thanks for the info, @dylans! Based on those numbers and the error you're seeing, looks like you might be hitting the rate limit error based on the size of the report that's being generated in the background. Can you confirm that you're seeing the same error every time you head to Velocity, despite if you haven't done any other GitHub/ZenHub activity within the hour?

**Comment by dylans** [comment]
I can confirm I've seen this error for weeks regardless of activity within the hour. All other ZenHub boards work, as well as the burndown chart.

**Comment by kendramoroz** [comment]
Thanks for confirming, @dylans - working with the team on this one. I'll post an update shortly.

**Comment by kendramoroz** [comment]
Hey @dylans - Kendra here! Sorry for the delayed update on this one. The Velocity report not loading is now a known issue that the team is looking at fixing. It's based on timeouts when the chart has to pull in a significant amount of data (in this case you have quite a large multi-repo Board and information within your milestones). Once we push a fix I'll update this issue to give you a heads up!

**Comment by dylans** [comment]
Thanks for the update @kendramoroz !

**Comment by kendramoroz** [comment]
We've recently launched performance updates for the Velocity chart that should help with this issue! @dylans - mind letting me know how things are going with your chart?

**Comment by dylans** [comment]
Unfortunately still getting a similar error, https://github.com/dojo/meta/milestones#reports?report=velocity

main.js:39 GET https://api.zenhub.io/v5/repositories/36094309/reports/velocity 400 (Bad Request)

**Comment by kendramoroz** [comment]
Thanks for confirming, @dylans!

To support the dev team debugging, can you send through an additional debugging piece, which is the HAR file from the network tab. To get the HAR file, if youre able to reproduce the error once more, instead of viewing the console tab, go to the Network tab.

As the error occurs, you should see the Velocity row appear, but in red. This should indicate that there is a failed request. Right click on it and select Save as HAR with content, and send this back to us via support@zenhub.com - This would be very helpful!

![image](https://user-images.githubusercontent.com/11036230/32119657-c9d18efe-bb0a-11e7-82ee-3748086a46e2.png)

**Comment by kendramoroz** [comment]
Hey @dylans we launched a fix today for velocity that should fix this problem for you! Can you confirm if you're able to load the Velocity chart now?

**Comment by dylans** [comment]
Hi @kendramoroz, thanks, I can confirm that we're now able to see the velocity chart! Apologies for not sending over the HAR previously, I missed your request among the flood of all the other notifications!
