### ISSUE TITLE
select all in pipeline

### ISSUE THREAD

**Issue by hiphapis** [ZenHubIO/support#1201]
Hi Zenhub!
I need 'select all in pipeline' many time

In our case,
When we are did deploy then all 'Staging' issues are move to 'Closed'

**Comment by bmunkholm** [comment]
This could also be really useful if you are migrating from another tool (e.g. Waffle) or just have labels  that represent the pipeline states. You want to filter for the specific label, and then move all issues in a pipeline to another (correct) pipeline.

**Comment by bmunkholm** [comment]
Also given that there is an (artificial?) limit of "select-all" of only 50 issues. That means if I filter a specific label I can't "select-all" issues and move them to the appropriate pipeline.

**Comment by kendramoroz** [comment]
Great suggestions here! Bumping over to discussion while we work to fit this type of enhancement into the roadmap. The current select all functionality was limited to 50 to help with performance and speed. Being able to improve this workflow is on our radar, so stay tuned for more updates!

**Comment by pleku** [comment]
Another use case for this:
I want to apply a milestone to all the issues in my `Icebox` column, so that I can show easily to the users that these issues are not on planned for development currently.

If I have to go and click through over 100 issues, I will go crazy. Forcing the users to use zenhub for seeing this is not an option. For eg. Waffle, this would be easy as all the issues in a certain column have a label on them, so I could select all by filter in github and apply a milestone to them.

**Comment by randydinh** [comment]
Any updates on this enhancement?

**Comment by cdepace** [comment]
Guys, it's incredible that such a basic feature is still unavailable. Any update about the roadmap?

**Comment by kendramoroz** [comment]
👋 Appreciate the ping, @cdepace — We don't currently have this on our short-term roadmap at the moment, but should anything change we'll keep the issue updated.

**Comment by cdepace** [comment]
hi @kendramoroz, thanks for the answer. It looks a quite basic functionality for me: selecting 50 tickets 1-by-1 is really painful. Why does it have such a low priority in the roadmap?

**Comment by EzraBrooks** [comment]
Agreed. During my team's triage, when we bulk tag to the next sprint, it's tedious to select everything in the backlog and in progress pipelines just to tag them to a milestone.

**Comment by mpittkin** [comment]
Would also like to see this added, it is such a seemingly small feature to add and it's such a pain in the butt to not have it...

**Comment by aseigle** [comment]
This would be a useful feature, and by useful, I mean almost a necessity.

**Comment by ChristianVermeulen** [comment]
I second this highly! Pretty amazed how this is not in there...

**Comment by jmcgrory** [comment]
Throwing my hat in, would speed up our workflow massively ✋🎩

**Comment by Startouf** [comment]
Would also love it. Our use case is similar as the one described in the OP's comment. We have a "Validated" columns when issues were validated in staging, a "Live" comment with our issues deployed  (we do not have continuous deployement yet, so we group several issues in deployments), and at the beginning of every week/Kanban milestone, we need to move all out "Live" issues to "Closed"

(our "Live" Pipeline is useful so during our retrospective/week start team meetings we can highlight the issues deployed to production)

**Comment by kendramoroz** [comment]
👋 It's been a great journey here in this GitHub Issue! We're going to be sunsetting this repo and moving to a new product feedback portal, [hosted here](https://portal.productboard.com/zenhub/c/13-improve-the-select-all-functionality-to-enable-select-all-in-a-pipeline?utm_medium=social&utm_source=portal_share) to streamline requests and share our roadmap more openly. 

We encourage everyone interested in this next chapter of Workspaces and ZenHub to vote, add feedback, and join the conversation 🎄! Upwards and onwards to 2019 🚀

**Comment by jmcgrory** [comment]
I'll remember the good times we had.
