### ISSUE TITLE
Collapse pipeline should be possible with one click.

### ISSUE THREAD

**Issue by bmunkholm** [ZenHubIO/support#1206]
Instead of hiding "Collapse" under the options icon, it would be nice to have that icon readily available with one click. Just like it is when the pipeline is collapsed. Everything else under the Pipeline options is only used when setting up the board. 

On a related note, you can completely remove the "Expand" option, as the pipeline is always expanded when you can open the "options" menu :-) Option menu is not available when the pipeline is collapsed.

**Comment by azenMatt** [comment]
We just released this change :) it should be with you soon
