### ISSUE TITLE
Milestone editing is broken

### ISSUE THREAD

**Issue by adius** [ZenHubIO/support#1208]
When I try to change the milestone start and due date on `https://app.zenhub.com/workspace/o/<user>/<repo>/milestones`
I get following error in the console:

```
index.f9e25601de5f420aedae.js:2 Uncaught TypeError: Cannot read property 'trim' of null
    at Object.<anonymous> (index.f9e25601de5f420aedae.js:2)
    at Object.t [as trim] (index.f9e25601de5f420aedae.js:2)
    at t.value (index.f9e25601de5f420aedae.js:80)
    at Object.r (index.f9e25601de5f420aedae.js:51)
    at a (index.f9e25601de5f420aedae.js:51)
    at Object.s [as executeDispatchesInOrder] (index.f9e25601de5f420aedae.js:51)
    at p (index.f9e25601de5f420aedae.js:51)
    at m (index.f9e25601de5f420aedae.js:51)
    at Array.forEach (<anonymous>)
    at r (index.f9e25601de5f420aedae.js:65)
```

**Comment by adius** [comment]
You should use http://elm-lang.org to develop your frontend, then this wouldn't have happened 😂

**Comment by kendramoroz** [comment]
Hey @adius thanks for sending this our way! 
Would you be able to provide a bit more details around the workflow you're going through when you see this error? I've been attempting to re-create the edit-milestone error you're seeing with no luck. Can you confirm that you have write permissions to the repo you're attempting to edit within?

**Comment by adius** [comment]
Mhh. I want to set / change the start & due date of a milestone.

Details:

2017-W01
Start date: No start date
End date: Past due by about 7 months
Created in 1/13 repos in this workspace

There are no Issues in this Milestone

**Comment by adius** [comment]
It's an organization account and I have admin rights.

**Comment by locriani** [comment]
@kendramoroz I am also encountering this issue (unable to set milestone start or end dates) using the chrome Github plugin. It is also an organization account to which I have admin rights.

**Comment by kendramoroz** [comment]
> @kendramoroz I am also encountering this issue (unable to set milestone start or end dates) using the chrome Github plugin. It is also an organization account to which I have admin rights.

@locriani are you editing the start date directly on the Burndown? The milestone management page originally referenced here is in the web app only currently! (We're digging into what could be causing this on the web app)

**Comment by locriani** [comment]
@kendramoroz correct. I'm on the burndown page and unable to edit the start date.

**Comment by kendramoroz** [comment]
Hey @locriani and @adius are you both still running into issues editing start dates?

**Comment by locriani** [comment]
@kendramoroz this has been resolved for me.

**Comment by kendramoroz** [comment]
🎉 thanks for confirming! I'll close this issue for now, but if you experience this issue come up again please feel free to re-open and let me know.

**Comment by adius** [comment]
The same procedure as every week: 😭

![image](https://user-images.githubusercontent.com/969983/30281247-6f9f329c-9701-11e7-9c0a-12be5240d1a1.png)

**Comment by kendramoroz** [comment]
@adius Kendra here again! Our team is debugging and want to confirm: are you seeing this error when trying to save, or when clicking on the date range?

**Comment by adius** [comment]
This error is logged when I click on "Save Changes"

**Comment by kendramoroz** [comment]
@adius Kendra again! We've launched a change that should fix this issue 🎉  would you mind letting us know if you can now save changes without the error 😊 ?

**Comment by adius** [comment]
Well, almost. For a few milestones it worked, but then I got following error:

![image](https://user-images.githubusercontent.com/969983/30610740-b1ee50d8-9d6e-11e7-8236-0b60f1fab4f1.png)

The request URL was `https://api.github.com/repositories/101338174/milestones`
and the response body was:

```json
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Milestone",
      "code": "already_exists",
      "field": "title"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/issues/milestones/#create-a-milestone"
}
```

**Comment by kendramoroz** [comment]
@adius based on the error message, looks like that error is related to an existing Milestone with that name. Did this error come up when you were creating a new one, or editing the name of an existing one? Can you confirm that the same name isn't being used across any other Milestones?

**Comment by adius** [comment]
The 2017-W38 milestone already exists in the feram-io repo. I wanted to bulk edit the start and end date of the milestone and it worked for every other repo, but not this one.

**Comment by kendramoroz** [comment]
@adius were you trying to edit the name, or just the dates? If the name was always there, and you were just trying to edit the date you shouldn't get an already exsists error unless the other exsisting Milestone is disconnected from this one - it'll then be creating two copies with different dates, which is causing the name to throw a duplication error. 

I'll wait to close this Issue until you can confirm!

**Comment by adius** [comment]
Just the dates. How can they be disconnected. I thought the only connection they have is the same name!?

**Comment by kendramoroz** [comment]
Thanks for confirming! There's 3 things that keep them all connected:
- same name
- same start date
- same end date

Glad to hear it's resolved! If you encounter any issues moving forward, feel free to re-open here or open a new ticket - always here to lend a hand.

**Comment by adius** [comment]
Ah, I see. I'd prefer them to only be connected via their name, but I assume this would break things for a few people...

Thanks for finally fixing this issue! :blush:
