### ISSUE TITLE
Can I fetch previous events for closed issues from API?

### ISSUE THREAD

**Issue by tatterdemalion** [ZenHubIO/support#1209]
As far as I understand, Zenhub does not maintain closed state of the issues and let Github handle the situation. That's understandable. But when I want to fetch which pipelines the issue has passed before it got closed, I get an empty list. Do you guys delete all the events when an issue is closed? Or is there any way to fetch all previous events even for closed issues?

On the other hand, what happens when an issue reopens? Can we get it's all previous events or just the ones after opening it again?

**Comment by kendramoroz** [comment]
We do not delete the events for an issue once it’s been closed.

Hey @tatterdemalion Kendra here! Happy to lend a hand. 

To confirm, are you using this route to get all events: `GET https://api.zenhub.io/p1/repositories/:repo_id/issues/:issue_number/events`

ZenHub can get all the previous events after re-opening, and post-reopened events.
Would you be able to take a screenshot of the issue page’s events list you're trying to fetch pipelines for, and the route you're using with the response? 

I can send this back to the team to continue debugging :)

**Comment by tatterdemalion** [comment]
Hi @kendramoroz 

Ok. That was mistake. I was trying it with issue id, not issue number. Thanks for your help.
