### ISSUE TITLE
How can I make labels such as Milestone and Assignees mandatory? 

### ISSUE THREAD

**Issue by kdpadua** [ZenHubIO/support#1210]
I need to enforce that when an issue or an epic is created, the milestone and assignee labels are properly assigned. Is it possible to enforce them as mandatory fields during issue creation?

**Comment by kendramoroz** [comment]
Hey @kdpadua thanks for getting in touch! 
Currently when creating an Issue, only the Issue title is set by default as a mandatory field. Currently across GitHub and ZenHub there's no native functionality that enforces other inputs to create Issues, but I'd recommend getting in touch with the GitHub support team to submit a feature request there way for this one! Assignees and Milestones are both native to GitHub, so they'd be able to provide a bit more clarity around best next steps for this type of behaviour. 

If there's anything else that comes up, don't hesitate to send a note my way! Happy to lend a hand :).
