### ISSUE TITLE
Filter by milestone shows epics and all issues associated with epics

### ISSUE THREAD

**Issue by CJ-Wright** [ZenHubIO/support#1211]
Would it be possible for filter by milestone to show all the epics and issues associated with those epics on the board?

**Comment by kendramoroz** [comment]
@CJ-Wright thanks for getting in touch! Currently the filter for Milestones will only include Issues/Epics explicitly assigned to that Milestone in the Issue themselves. If you'd like to have all Epics and Issues in that Epic associated with a particular Milestone, a quick way to get this set up would be to filter by the Epic, then use the **select all** function that appears to enter Multi-select where you can assign to a Milestone!

![image](https://user-images.githubusercontent.com/11036230/29428744-255c64f6-8343-11e7-9e40-e4050bb3ce63.png)

**Comment by CJ-Wright** [comment]
Thank you for the prompt response!

My current workflow is that issues are assigned to epics which are collated into releases which are assigned to milestones (this way we can release/solve problems across an entire stack at once) so I'd rather not have all the issues associated with the milestone as it just clutters things up a bit. Also this would mean that every time I add an issue to an epic, I'd also need to add it to a milestone, which seems like a few clicks too many.
