### ISSUE TITLE
New issue functionality is broken

### ISSUE THREAD

**Issue by kashif-fh** [ZenHubIO/support#1213]
On clicking "New Issue", filling in the title field with some text and hitting "Submit new Issue", I always get an "An error prevented the creation of the issue".

The workaround is to actually click the dropdown next to "New Issue" and select a specific repository, which then creates the issue in that particular repo.

**Comment by kendramoroz** [comment]
@kashifnoorani thanks for submitting this! Can you send through a screenshot of the developer console  and share the error you're seeing when submitting the issue? Can you also confirm that you have sufficient privileges to the repo/Board where you're trying to create a new issue?

A screenshot of the error message that pops up in-context would also be very helpful to debug the workflow here!

**Comment by kashifnoorani** [comment]
@kendra - I own all our repositories so permissions are not a consideration.

Which developer console are you referring to? The screenshot is attached.

**Comment by kendramoroz** [comment]
@kashifnoorani If you could right click on the Boards page, and inspect the page and then navigate to the tab console, anything that appears in red there when you try to create the Issue would be helpful!

Looks like the screenshot didn't make it's way through to the Issue. Mind sending directly to support@zenhub.com?

**Comment by kashifnoorani** [comment]
@kendra - the screenshot is attached to my previous comment.

On the console output below, the updateLastSeen errors happened when I reloaded ZenHub while the 410 (Gone) happened after the new issue error occurred.

[Error]  (1)
Possibly unhandled updateLastSeen — index.e07b2c98f7ba13a3b467.js:80:365062i — index.e07b2c98f7ba13a3b467.js:80:364942(anonymous function) — index.e07b2c98f7ba13a3b467.js:80:295858get — index.e07b2c98f7ba13a3b467.js:80:365574updateLastSeen — index.e07b2c98f7ba13a3b467.js:80:295684(anonymous function) — index.e07b2c98f7ba13a3b467.js:51:161588r — index.e07b2c98f7ba13a3b467.js:13:35434_callHandler — index.e07b2c98f7ba13a3b467.js:80:1192609_settlePromiseFromHandler — index.e07b2c98f7ba13a3b467.js:80:1192789_settlePromiseAt — index.e07b2c98f7ba13a3b467.js:80:1195043_settlePromises — index.e07b2c98f7ba13a3b467.js:80:1197259_consumeFunctionBuffer — index.e07b2c98f7ba13a3b467.js:51:269038consumeFunctionBuffer — index.e07b2c98f7ba13a3b467.js:51:268428run — index.e07b2c98f7ba13a3b467.js:51:58594s — index.e07b2c98f7ba13a3b467.js:51:58096
possiblyUnhandledRejection (index.e07b2c98f7ba13a3b467.js:80:1171710)
_notifyUnhandledRejection (index.e07b2c98f7ba13a3b467.js:80:1197863)
r (index.e07b2c98f7ba13a3b467.js:13:35434)
_consumeLateBuffer (index.e07b2c98f7ba13a3b467.js:51:269212)
_consumeFunctionBuffer (index.e07b2c98f7ba13a3b467.js:51:269081)
consumeFunctionBuffer (index.e07b2c98f7ba13a3b467.js:51:268428)
run (index.e07b2c98f7ba13a3b467.js:51:58594)
s (index.e07b2c98f7ba13a3b467.js:51:58096)
[Error]  (1)
Possibly unhandled updateLastSeen — index.e07b2c98f7ba13a3b467.js:80:365062i — index.e07b2c98f7ba13a3b467.js:80:364942(anonymous function) — index.e07b2c98f7ba13a3b467.js:80:295858get — index.e07b2c98f7ba13a3b467.js:80:365574updateLastSeen — index.e07b2c98f7ba13a3b467.js:80:295684(anonymous function) — index.e07b2c98f7ba13a3b467.js:51:161588r — index.e07b2c98f7ba13a3b467.js:13:35434_callHandler — index.e07b2c98f7ba13a3b467.js:80:1192609_settlePromiseFromHandler — index.e07b2c98f7ba13a3b467.js:80:1192789_settlePromiseAt — index.e07b2c98f7ba13a3b467.js:80:1195043_consumeFunctionBuffer — index.e07b2c98f7ba13a3b467.js:51:269038consumeFunctionBuffer — index.e07b2c98f7ba13a3b467.js:51:268428run — index.e07b2c98f7ba13a3b467.js:51:58594s — index.e07b2c98f7ba13a3b467.js:51:58096
possiblyUnhandledRejection (index.e07b2c98f7ba13a3b467.js:80:1171710)
_notifyUnhandledRejection (index.e07b2c98f7ba13a3b467.js:80:1197863)
r (index.e07b2c98f7ba13a3b467.js:13:35434)
_consumeLateBuffer (index.e07b2c98f7ba13a3b467.js:51:269212)
_consumeFunctionBuffer (index.e07b2c98f7ba13a3b467.js:51:269081)
consumeFunctionBuffer (index.e07b2c98f7ba13a3b467.js:51:268428)
run (index.e07b2c98f7ba13a3b467.js:51:58594)
s (index.e07b2c98f7ba13a3b467.js:51:58096)
> Selected Element
< <div class="zhc-topbar__bottom-menu">…</div>
[Error] Failed to load resource: the server responded with a status of 410 (Gone) (issues, line 0)

**Comment by kendramoroz** [comment]
@kashifnoorani Kendra here! Are you still experiencing issues creating new issues?

**Comment by kashifnoorani** [comment]
Yes @Kendra - if a fix wasn’t issued, then this bug will always occur :)

Thanks,

Kashif

**Comment by kendramoroz** [comment]
@kashif-fh following up here - To continue with debugging, the team has requested a bit more information to help uncover why you're experiencing the error. 

In the javascript console tab of the developer consoler, would you be able to look for an error line starting with `An error prevented the creation of the issue` and send over a screenshot of what you see?

Second, in the network tab, would you be able to clean the tab before clicking "submit", click "submit", and post a screenshot of the result?

**Comment by kendramoroz** [comment]
One more note! If you're unfamiliar with these steps in the console, would you be able to send through an email to support@zenhub.com with some times you're available (and your timezone) to jump into a quick debugging call? We want to ensure you get setup properly as quickly as possible!

**Comment by kashif-fh** [comment]
its best to do a quick call - I can meet next week anytime from 1-3 pm.

**Comment by EFF** [comment]
Hey there. While I was testing out to see if we move our entire project management workflow to ZenHub I couldn't create a single issue. See screenshot.

![screen shot 2017-11-16 at 11 31 54 am](https://user-images.githubusercontent.com/955524/32903046-0029c09a-cac2-11e7-9686-65cc75814c44.png)

I inspected js errors in Chrome dev tools console and the error seems to be coming from github api. 

![screen shot 2017-11-16 at 11 34 37 am](https://user-images.githubusercontent.com/955524/32903125-362460ba-cac2-11e7-818b-9220301fa04e.png)

What's up with this ?

**Comment by azenMatt** [comment]
Hi @EFF 

410 (gone) is a new one to us.... 

Would you be able to check a couple of things for us:

1) Has this repo been recently renamed? 
2) If you use the Github.com interface - can you create an issue in this repo?

**Comment by EFF** [comment]
Hi @azenMatt,

the repo has indeed been renamed but that wasn't the issue. I realized issues weren't enabled on the repo. I assumed they were enabled by default on GH. 

You guys might want to add something more explicit as error message. So people don't get confused.

**Comment by AdamVStephen** [comment]
I second the comment above.  This is a significant bug.   The dialogue should explicitly replace the text "an error prevented the creation of this issue" by "repository settings have not yet enabled issue creation".   It's taken me 10 minutes to figure this out and others will also be affected.  If diagnosing the condition that prevents the issue creation from working is not practical, then a simple workaround would be as a minimum to expand the text to "an error, or possibly repository setting, has prevented..."
