### ISSUE TITLE
Advanced "New Issue" templates

### ISSUE THREAD

**Issue by kashif-fh** [ZenHubIO/support#1214]
The current implementation requires too much clicking and repetition. At the beginning of sprint planning, a bunch of issues are created, which are usually clustered around common settings (same engineer, same epic, same release etc.).

A couple of suggestions:

1. Allow a "create new issue like this issue"
2. Allow creation of templates such as New UI Issue or New Backend Issue
3. Allow default value settings
4. Use ML to predict settings based on text entered in the title

Any of these solutions are acceptable and have pros/cons. (3) is the most obvious one and something ZenHub is already following a bit as a default pipeline is filled out when a new issue is being created. (4) sounds like a cute research project :)

**Comment by azenMatt** [comment]
The GitHub based new issue templates are now live! 

in terms of the more advanced features mentioned - I am going to rename this issue to better capture them and move this back to the backlog to capture them

**Comment by kashif-fh** [comment]
I don’t see it on my zen board - are there any screenshots or wiki that you explains the design so I can check it out?

**Comment by azenMatt** [comment]
Hi @kashif-fh - sure thing, 

Do you have the new issue template set up in GitHub? https://help.github.com/articles/creating-an-issue-template-for-your-repository/

With this set up, it should auto-populate the issue body in ZenHub, the same way that it does in GitHub

**Comment by kashif-fh** [comment]
ok - but that's not what I need and not what this enhancement is about.

**Comment by azenMatt** [comment]
sorry @kashif-fh - you are right. I got confused based on the issue title and bucketed this in with a number of other open issues we had on 'new issue template' that were talking about the GitHub templates. 

Please ignore my responses above. 

In terms of solutions to reduce the number of clicks required when creating an issue, we don't have any firm ETA for this yet, but it is certainly a frustration we share and are keeping an eye on.

**Comment by kashif-fh** [comment]
no problem. I am planning a new sprint on Monday so that will be a day of frustration :(

**Comment by Startouf** [comment]
Hey the Github issues templates are great but they don't support different types of templates (eg template for a feature, a bug, a refactoring, a graphical bug, a user story, etc.)

Would save a lot of time to support creating several custom issue templates and being able to choose one easily (including adding tags, releases, etc. automatically)

**Comment by iCynara** [comment]
Would also love issue template support title in the template

**Comment by Startouf** [comment]
Hello @azenMatt I just ran across [this article](https://github.com/blog/2495-multiple-issue-and-pull-request-templates) that explains that github actually supports multiple issue templates via the `?template` url param, I would love to see this in zenhub, should the discussion about this be continued here or in a different/existing ticket ?

**Comment by azenMatt** [comment]
Hi @Startouf 

We also spotted that :) we will make sure to roll out support for this in the future. Although it is not likely to be before we complete the current work on #139

**Comment by tay1orjones** [comment]
It'd be great if ZenHub simply supported the [query parameters URL structure](https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/) that GitHub supports.

- `&pipeline=Backlog`
- `&release=Beta`
- `&epic=MyEpicName`
- etc ...

This would allow multiple templates by simply linking via URL. These URLs could be included as image link "buttons" on `readme.md` at that point, or the project wiki, `contributing.md`, etc. 

This would also degrade gracefully, not breaking the native GitHub functionality if a user doesn't have ZenHub installed.

**Comment by tdayton** [comment]
I need this capability, to do at least approximately what I am accustomed to doing with JIRA. There is no way I can get my team members to laboriously create the structure in each issue, that we need for doing useful project management with ZenHub.

**Comment by ygnoh** [comment]
As a side note, Github has started to support [advanced issue template](https://blog.github.com/2018-05-02-issue-template-improvements/) since May 2018.

**Comment by kendramoroz** [comment]
🙌 Hey y'all - we're going to be supporting GitHub's new issue template workflow very soon! We're just spec'ing this feature out and are hoping to tackle this in our upcoming Sprint. We'll keep everyone posted on the status.

**Comment by kendramoroz** [comment]
👋 Here's a sneak peak! We just finished scoping user stories and edge cases and will be beginning work on supporting multiple Issue templates in the next sprint. 

In prep for this, let us know if you have any questions or need advice on templates we recommend! We'd be happy to share our thoughts based on your team's workflows :) just get in touch via support@zenhub.com!

🎉 

![screen shot 2018-09-25 at 1 55 14 pm](https://user-images.githubusercontent.com/11036230/46042628-b8229100-c0ca-11e8-9ca0-67ea70ef6b63.png)

**Comment by florianrusch** [comment]
@kendramoroz can't wait for it 😊 Do you already know, when this feature will reach production?

**Comment by kendramoroz** [comment]
It's in our upcoming Sprint - we're aiming for end of month :) - I'll post back once our Sprint kicks off to provide another update! But it should be live soon 🎉

**Comment by andykenward** [comment]
https://github.com/ZenHubIO/support/issues/387#issuecomment-439016222

**Comment by cwalo** [comment]
@andykenward @kendramoroz seeing the same issue here...

**Comment by pakivika** [comment]
> The GitHub based new issue templates are now live!
> 
> in terms of the more advanced features mentioned - I am going to rename this issue to better capture them and move this back to the backlog to capture them

This is great news. Just one question. I already had templates in ./github/ISSUE_TEMPLATE/ folder in multiple repositories. How to make ZenHub to pick them up automatically without clicking and copy/paste in the UI?

**Comment by cwalo** [comment]
@andykenward @pakivika I just received an email noting that this is fixed and it appears to be working for us. Take a quick look now.
