### ISSUE TITLE
Useless Home tab gets automatically selected when clicking on Reports

### ISSUE THREAD

**Issue by lacostenycoder** [ZenHubIO/support#1218]
This home splash screen is pretty annoying to be the default.  Can we disable or get rid of it? Currently I have to first click on "Burndown" to first get there, then another click to select the burn down period.  Seems like a needless waste of time.

![screen shot 2017-08-18 at 12 28 09 pm](https://user-images.githubusercontent.com/6077905/29468132-f79045a0-8410-11e7-9efb-ca369f12eae0.jpg)

**Comment by kendramoroz** [comment]
Hey @lacostenycoder thanks for sending this in and sharing feedback! It should be defaulting you back to burndown once seen so I'll work with the team to fix this up.

**Comment by adamreisnz** [comment]
This does to straight to burndown in the same session, but after a refresh, it will go to the welcome tab again. Probably best to store this "has seen" setting in local storage to maintain it across sessions.

**Comment by kendramoroz** [comment]
@adamreisnz We're modifying the experience to recall the last report you were viewing! Hopefully this helps make it not default to home, but also help keeps the focus on the report most meaningfully to you :)

**Comment by adamreisnz** [comment]
Yes, that'd be great, thanks!

**Comment by azenMatt** [comment]
This is live - reports will now go back to the last report that you viewed for that particular repo
