### ISSUE TITLE
Board shifted to the top, area's of page cut off

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1219]
This has started happening since today;

![image](https://user-images.githubusercontent.com/490562/29493161-3321472e-85e5-11e7-8c9e-efda00bacde0.png)

For some reason it scrolls the page to the footer of Github and the top of the page is inaccessible.
Even a refresh doesn't always fix it.

**Comment by kendramoroz** [comment]
@adamreisnz good spot! I've reported this to the team.

**Comment by tetreault** [comment]
i have a similar issue in Chrome on OSX (Version 60.0.3112.101 (Official Build) (64-bit)).

<img width="1250" alt="screenshot 2017-08-23 10 06 20" src="https://user-images.githubusercontent.com/5934354/29620319-9ef12728-87eb-11e7-86f6-bbee6055e509.png">

**Comment by azenMatt** [comment]
Thanks for the additional info @tetreault - the team is looking into this one at the moment

**Comment by tetreault** [comment]
Thanks @azenMatt - love the product!

**Comment by adamreisnz** [comment]
@azenMatt thanks for the quick response. 

Would you mind taking a look at https://github.com/ZenHubIO/support/issues/1181 as well? I've raised that weeks ago, with clearly reproducible steps and an error trace from the console, but it hasn't been looked at since. It's really hurting our workflow as we suffer from that bug several times per day at least.

**Comment by azenMatt** [comment]
Thanks @adamreisnz - i've added thoughts to #1181

**Comment by azenMatt** [comment]
Hi @adamreisnz @tetreault - we just released v2.35.9 which will contain a fix for this. 

if you are using the Browser Extension version of ZenHub, it will update itself today - or, you can manually force an update via the extension page in the browser to pick it up soon. 

Please let me know if you spot this one again!

**Comment by tetreault** [comment]
Will do @azenMatt - thanks for the good communication!

**Comment by adamreisnz** [comment]
Thanks, looks good now I think! Will keep an eye on it.
