### ISSUE TITLE
Collapsing and width-sizing pipelines

### ISSUE THREAD

**Issue by awesomi** [ZenHubIO/support#122]
#### Collapsing
All pipelines are identically dimensioned but different team members focus on just a particular subset of pipelines. Suppose pipelines define development process. Developers would be focused on particular pipelines related to their work, testers to another subset etc. This could be done by collapsing individual pipelines so they don't take as much width as uncollapsed ones do. These collapsed states should of course be saved per-repository and per-user.

#### Width sizing
A similar feature could be pipeline width adjustment. So whenever user sees their pipelines of interest they're also able to drag-set their individual widths. This is especially useful when pipelines require more width than windows can provide. One could make them a bit narrower to see the whole kanban.

**Comment by coderjonny** [comment]
:+1:

**Comment by scien** [comment]
any update on this issue?

**Comment by coderjonny** [comment]
:+1:

**Comment by coderjonny** [comment]
I'm looking for the same thing that huboard has, where the columns can be collapsed.

**Comment by erinneff1** [comment]
Please adjustable width pipelines! As a PM its very difficult to get a clear view of even the top priorities in the to-do column when I can only fit 4-5 tickets on my screen. 

Simply the option to drag this column to a larger width while I am working in this view would greatly alleviate this issue. Saving previous views and additional fanciness would be a nice to have but not necessary to alleviate the immediate pain point. Thanks!

**Comment by minetteyou** [comment]
Any update on this yet?

**Comment by azenMatt** [comment]
@minetteyou - Actively being worked on for a upcoming release - so should be with you very soon :smile:

**Comment by azenMatt** [comment]
And we are live! :fireworks: 

Version 2.8.1 updates the board to let you expand and collapse pipelines as needed, 

![image](https://cloud.githubusercontent.com/assets/7584089/10205622/1e431b86-6777-11e5-8b37-89eec08ef32c.png)

Please let me know any feedback!

**Comment by minetteyou** [comment]
Have been waiting for this, very exciting! 
One small UI suggestion is the ability to directly edit the pipeline names by clicking on the names, that way the settings icon can just be a delete icon.

**Comment by azenMatt** [comment]
Thanks @minetteyou ! 

Also, you can edit the pipeline names by double clicking :smile:
