### ISSUE TITLE
Start date displayed on burndown report is incorrect

### ISSUE THREAD

**Issue by kimberlyplima** [ZenHubIO/support#1220]
![ago-21-2017 13-51-08](https://user-images.githubusercontent.com/22302027/29529964-2d34159c-8678-11e7-8f03-2577de8dee97.gif)

Same milestone, displayed on velocity tracking:
![captura de tela 2017-08-21 as 14 02 52](https://user-images.githubusercontent.com/22302027/29530309-780c1910-8679-11e7-8f3d-0d802ed74b9a.png)

As you can see, I selected the period between 21st and 25th Aug., but on burndown report start date displayed is 20th Aug.

**Comment by kendramoroz** [comment]
@kimberlyplima good spot! Definitely a 🐛 . Sending to the team now! I'll update this issue once we launch a fix.

**Comment by kendramoroz** [comment]
@kimberlyplima we've launched a fix for this! It should automatically make it's way to auto-update your extension, but if you'd like to force an update you can uninstall and re-install to get the fix right away :).
