### ISSUE TITLE
Uni-directional multi-repo association

### ISSUE THREAD

**Issue by bmunkholm** [ZenHubIO/support#1222]
As a user with many repos, I would like to be able to select which repos should be associated with each other in a uni directional fashion.
E.g. when looking at repo A, I want to see A and B.
But from B, I want to to see B and C.
But today I would have to make all repos visible from all repos.

Consider the case where you have 20 projects/repos for different teams.
You might have one master-repo (with e.g. overall product issues and releases defined).
In each team repo, you only want to see the teams repo + the master-repo.
But from the master-repo, you may want to be able to see all team repos and e.g. define a general release across all repos.

**Comment by chriswu42** [comment]
+1

**Comment by kendramoroz** [comment]
Very excited to update this issue that we're working on workspaces, which will help with this use case :). Updates and more details can be tracked via #139!
