### ISSUE TITLE
PRs always move issues over to "New Issues" column

### ISSUE THREAD

**Issue by LandonSchropp** [ZenHubIO/support#1225]
Whenever I create a new pull request and link it to an issue, ZenHub always moves the issue from our "In Progress" column back to the "New Issues" column. Is there a way to prevent that behavior? 

Ideally, ZenHub would move the issue over to "In Review" by default, but if that's not possible it would be great to at least have it stay where it is.

**Comment by SeanyB** [comment]
Actually, this is already a feature of ZenHub. When you create a PR, you can select the default pipeline for the PR (and associated Issue) to be moved to. I've attached a screenshot of the area just under the PR description.

<img width="724" alt="zenhub - default pipeline for pr" src="https://user-images.githubusercontent.com/421723/29592109-49df576c-8770-11e7-9ec1-203e1783639d.png">

**Comment by kendramoroz** [comment]
Hey @LandonSchropp! As @SeanyB (thanks for jumping in and supporting the community!) mentioned, you can change the default pipeline when merging PRs to help with where the Issue/PR get linked together by default. Feel free to get in touch if you have any questions or are having trouble getting this setup :)

**Comment by LandonSchropp** [comment]
Thanks!
