### ISSUE TITLE
Discrepancy for how user actions are displayed

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1230]
Compare:

![image](https://user-images.githubusercontent.com/490562/29738349-bac21300-8a74-11e7-9c9f-d0217f4d4056.png)

Why don't the first two items also show a picture of the user instead of the `@` symbol?

**Comment by kendramoroz** [comment]
@adamreisnz good spot! This 🐛  is currently being worked on by the team - it should be the user profile :)

**Comment by azenMatt** [comment]
This is now fixed on v2.35.10!
