### ISSUE TITLE
Start date set (or displayed) incorrectly

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1231]
![image](https://user-images.githubusercontent.com/490562/29747107-9a823826-8b42-11e7-9d84-b24857f7ef6b.png)

I selected the 28th as the start date. It displays the 27th instead.
If I select the 27th, it displays the 26th.

Timezone issue?

**Comment by kendramoroz** [comment]
Hey @adamreisnz thanks for this report! We recently launched a bug fix for this - can you confirm that you're using 2.35.9 and still seeing this behaviour?

**Comment by adamreisnz** [comment]
I have just updated manually from 2.35.7 to 2.35.9, but the bug is still present.
Note that I am in the NZST timezone.

**Comment by kendramoroz** [comment]
Ah ha! The NZST was the perfect tidbit to replicate - Issuing this up for the team. I'll report back once a fix is launched 💪

**Comment by adamreisnz** [comment]
Note that this only affects the start date, not the end date.
It might also be related to https://github.com/ZenHubIO/support/issues/987

Ideally, the start date should be at 0:00 and the end date at 23:59, that way they encapsulate a whole day, and that way selecting a start date that is the same as end date also makes sense.

**Comment by azenMatt** [comment]
Hi @adamreisnz - we have released a fix for this in v2.35.13 

Would you be able to confirm it works? Also fingers crossed it resolves #987 for you as well...?

**Comment by adamreisnz** [comment]
@azenMatt thanks, this issue has been resolved, not #987 though. I'll comment on that issue with my findings.
