### ISSUE TITLE
API to create/edit milestone

### ISSUE THREAD

**Issue by seocam** [ZenHubIO/support#1232]
Currently github does not support start date for a milestone. We'd like to use ZenHub API to create a new milestone setting it's start date. That would be specially useful for our team because we have an integration of a internal management tool with github. Our milestones are created in our tool and them replicated to github by api. If we could instead actually use your api we would set the start date there instead of doing it manually after.

**Comment by azenMatt** [comment]
Hi @seocam - we have just added this endpoint - https://github.com/ZenHubIO/API#set-milestone-start-date :)
