### ISSUE TITLE
Can not add new one to todo list

### ISSUE THREAD

**Issue by Durant35** [ZenHubIO/support#1239]
#542 
## Possible Reasons
+ Reach the upper limit number of todos? Now it's 19 todos.
+ A bug? I have changed the last added todo, renaming the corresponding issue.

**Comment by Durant35** [comment]
It seems that it's due to a system crash in Zenhub's server

**Comment by sisskind** [comment]
@Durant35 can confirm I had same issue.  Thanks for adding.

**Comment by kendramoroz** [comment]
@Durant35 @sisskind Thanks for reporting! We're working on launching a fix - I'll post once it's out!

**Comment by kendramoroz** [comment]
👋  Kendra here again! A fix has been pushed to production. You should now be able to add ToDo items without getting an error. Feel free to re-open and post if you're still seeing Issues!

**Comment by Durant35** [comment]
Great! Thanks!! Desperately in need for completely removing TODO's!!!
