### ISSUE TITLE
Velocity Report label filtering does not span multiple repos

### ISSUE THREAD

**Issue by brandonlogan** [ZenHubIO/support#1241]
The velocity report will only show the progress of labels in the repository that is currently being used to access the velocity report.

For example, Assume I have `issue#1` in `repoA` and `issue#2` in `repoB` and both have the same label `bug`.  If I go to the `Reports` link on the `repoA` page and view `Velocity Reports` and filter by the label `bug`, I will only see `issue#1` being represented.

Both `repoA` and `repoB` are in the same workspace.

**Comment by kendramoroz** [comment]
@brandonlogan thanks for sending this in! Can you also confirm that the Milestone is the same across both repos, showing up like this on the chart below Velocity:

![image](https://user-images.githubusercontent.com/11036230/30929687-0f78f5a4-a374-11e7-9916-a7a8a1f788c1.png)

**Comment by brandonlogan** [comment]
@kendramoroz I can confirm the Milestone is the same across all of our repos.  I was using 2 repos as an example but we have more than that.

**Comment by kendramoroz** [comment]
Hey @brandonlogan pardon the long follow-up here 😓  - I wanted to circle back to see if you're still experiencing this issue? 

The label filtering should apply to all connected milestones, as long as the milestone is closed across all the connected repos. I'd recommend using [the Milestone Management page](https://www.zenhub.com/guides/managing-cross-repo-milestones) to manage edits/closing of Milestones to ensure none are missed! 

Let me know.
