### ISSUE TITLE
Modals on Board flickering, buggy on hover states Chrome with MacOS 10.11.6

### ISSUE THREAD

**Issue by lacostenycoder** [ZenHubIO/support#1244]
See attached video clip.  Elements flicker, move around, and disappear on hover states.

I'm using Chrome version  61.0.3163.79 (Official Build) (64-bit) on MacOS 10.11.6

https://drive.google.com/file/d/0B2LSbbDip0CUSHR0aXFLbGljeHc/view?usp=sharing

**Comment by kendramoroz** [comment]
@lacostenycoder Following up here in addition to the email followup! I noticed that you have quite a few active extensions as well - Would you be able to create a new Chrome profile and re-install ZenHub as the only extension to see if you’re experiencing the same behaviour? There is a possibility that one of the other extensions or Chrome modifications you have is interfering with the ZenHub Extension. 

Having a new profile will help verify it’s another extension or not.

**Comment by lacostenycoder** [comment]
This issue is resolved by making sure hardware acceleration is enabled on google chrome.  You might want to add some documentation somewhere that your plugin requires this option set on to work properly in chrome.

I had hardware acceleration disabled on my Chrome because of a known bug on MacOS 10.11.6 which causes color artifacts when watching youtube videos in full screen.  Kind of a pain because I have to restart chrome whenever toggling this setting.
