### ISSUE TITLE
new issue not applying template from .github folder

### ISSUE THREAD

**Issue by rudimusmaximus** [ZenHubIO/support#1247]
I'm not seeing templates work at all.

For example, in repositories that have a .github subfolder with md files for issues, pull requests, or contributing instructions, the issue template functionality does not seem to work when clicking new issue from the app.zenhub.com interface. 
![screenshot 2017-09-17 at 9 40 26 pm](https://user-images.githubusercontent.com/21182598/30527862-d19ef946-9bf2-11e7-8500-992722969b3d.png)

In the case of issues, the file functions like a template for issues and a copy is created when new issues are generated.

**In github, clicking new issue gets you a new issue with the default content; in app.zenhub.com, it does not.**

Is this a bug, or can you add support for the various ways github supports templates?

An enhancement might also be to support these and a choice of templates? but that's another note.

Thank you. I love ZenHub!

**Comment by rudimusmaximus** [comment]
also see #1238

**Comment by kendramoroz** [comment]
@rudimusmaximus Thanks for reporting this! We're currently looking at fixing this and improving template workflows in the app 💪 We'll post updates here once we have more to share!

**Comment by azenMatt** [comment]
@rudimusmaximus this is now live!
