### ISSUE TITLE
Link to ZenHub Dashboard in docs

### ISSUE THREAD

**Issue by zoechi** [ZenHubIO/support#1249]
https://www.zenhub.com/faq#faq-permissions-privacy

> Go to your ZenHub Dashboard, sign out, then back in again. You should see the following:

I don't know what "ZenHub Dashboard" is or where to find it. A link would be helpful.

**Comment by kendramoroz** [comment]
@zoechi here you are! https://dashboard.zenhub.io/

You can also access the dashboard at anytime by clicking on the extension and selecting `dashboard`

<img width="493" alt="screen shot 2017-09-20 at 2 28 29 pm" src="https://user-images.githubusercontent.com/11036230/30668573-0ab16826-9e10-11e7-9bb6-51b5fb3b36e2.png">

Or via app.zenhub.com through clicking on your avatar and heading to `manage organizations`:

![image](https://user-images.githubusercontent.com/11036230/30668603-1bc74b6c-9e10-11e7-987a-661c349b1b93.png)

Let me know if you have any questions I can help with!

**Comment by zoechi** [comment]
Thanks!
I think there should be a link in the docs where itßs mentioned.
The dashboard site navigation is broken as well.
After clicking the link in your comment, I'm not able to navigate back here using the back button.

**Comment by kendramoroz** [comment]
Great suggestions! I'll get that link in the FAQ today :) - thanks for taking the time to send through this feedback!
