### ISSUE TITLE
Firefox 57 Legacy Extension

### ISSUE THREAD

**Issue by jugdemon** [ZenHubIO/support#1250]
Dear Zenhub support,

I am running the developer version of Firefox and today came the upgrade to version 57 which instantly disabled the zenhub extension as it uses legacy methods. At what time can we expect a web extension based version of zenhub?

Best wishes,
jugdemon

**Comment by kendramoroz** [comment]
@jugdemon Thanks for getting in touch! We've already launched a web extension version of ZenHub for Firefox on our cloud offering 🎉 ( #1026 ). Would you be able to send more information about the team you are on and whether you're on Enterprise or Cloud to support@zenhub.com? We'll make sure you get set up with the right extension :).

**Comment by banool** [comment]
What about regular Zenhub users? I can't find the Zenhub extension anywhere for Firefox 57. Should I be installing it from the Chrome store? Github doesn't prompt me to install it when I go to a repo in Firefox 57 as it normally does.

**Comment by azenMatt** [comment]
Hi @banool - if FF hasn't updated it for you yet, you can re download from - https://www.zenhub.com/extension

**Comment by banool** [comment]
Ahh thanks a lot, I was really struggling to find the link for that!
