### ISSUE TITLE
Unable to download chrome extension

### ISSUE THREAD

**Issue by jfgossage** [ZenHubIO/support#1252]
I am running Google Chrome 61.0.3163.79 on Windows 10 Professional 64 bit with Creator's update. I am on page https://www.zenhub.com/choose-platform and when I press the "Add the extension to your browser" nothing happens. How can I add your extension to my browser?

**Comment by jfgossage** [comment]
It turns out that I had actually installed your extension without realizing it. It would make the referenced page a bit better if it told one that the extension was already installed.

**Comment by kendramoroz** [comment]
Happy to hear you're all setup @jfgossage  - great suggestion for improvements on that page. We'll issue that up internally 👍 

If you have any other questions or issues getting started feel free to re-open this issue or spin up a new one!
