### ISSUE TITLE
Add all repos to board in one go

### ISSUE THREAD

**Issue by erasmus** [ZenHubIO/support#1257]
When adding repositories to a board, I'd like to be able to select multiple and add in one go. Now I have to add them one-by-one via the "Repos" dropdown, which is quite cumbersome for larger projects.

**Comment by MikeLund** [comment]
It would be nice; but keep in mind the performance improvements that might impact you, if you don't already know (see https://github.com/ZenHubIO/support/issues/930 and https://github.com/ZenHubIO/support/issues/1159)

**Comment by kendramoroz** [comment]
@rashagen we are working on making improvements to the multi-repo Board merge workflow so we'll keep this pain point in mind - agreed it could be smoother. 

Bumping over to discussion. We'll post updates for feedback once we have them available!

**Comment by kendramoroz** [comment]
👋  Hey everyone! We're working on a new improve workspace builder that will tackle this feature request! You can check out what we're up to here: https://github.com/ZenHubIO/support/issues/139#issuecomment-356132787
