### ISSUE TITLE
Unable to move issue after sort "newest"

### ISSUE THREAD

**Issue by Technology-PRS** [ZenHubIO/support#1260]
Afer using sort to arrange newest to oldest issues cannot be moved to a new swim lane

**Comment by kendramoroz** [comment]
@Technology-PRS thanks for reporting! This is a 🐛  that we have issued up internally. Moving over to the known issues pipeline for tracking.

**Comment by kendramoroz** [comment]
Hey @Technology-PRS Looks like this bug has since been resolved! Sorry for the delay 😅 - if you have any trouble dragging and dropping issues in and out of sorted pipelines please ping here once more and we'll take another look 🚀
