### ISSUE TITLE
Zenhub enterprise Issue with repo merge 

### ISSUE THREAD

**Issue by sudeepsukumar** [ZenHubIO/support#1262]
Version 2.18.2

I get the following message when I try to merge another repository in my ZenHub board

**Are you sure you want to continue? main is already connected to another Board. Clicking merge will disconnect it from that Board, which may impact other members of your team.**

_Note: main is the name of my repo_

I get this message only for a specific repo "main" and I am not sure what is the reason here. This repo specific board is being used by developers of a specific service and I am trying to consolidate all service tasks and in repo and add this to a Milestone.

- Why am i getting this message and how could i resolve this?
- How will my merge affect them? 

Thanks!

**Comment by kendramoroz** [comment]
Hey @sudeepsukumar thanks for sending this our way! Happy to help explain a bit more about the multi-repo Board process. 

Currently a repo can only be attached within 1 multi-repo Board. 

If you have the following setup:

`Repo A` + `Repo B` together in a Board
and separately:
`Repo C` + `Repo D` + `Repo E` in a Board

But decide that `Repo D` should also be with `Repo A` + `Repo B`, `Repo D` (in this case `Main`) will be disconnected from `C & E` and placed in with `A & B`.

This is why you're receiving this message: Main is already connected with another groupings of repos. 

Disconnecting `Main` to add it into your workflow will cause all the Issues from that repo to be removed from the Board your colleagues are viewing, as well as be removed from all associated reports and Epics. Before transferring where this Repo sits, I'd recommend having a chat to see if the workflows across all the Boards can be shared, to ensure no one team loses data. 

Let me know if you have any clarifying questions! I'll leave this in discussion until I hear back :)

**Comment by sudeepsukumar** [comment]
Well.. thanks @kendramoroz . Clear now.
