### ISSUE TITLE
Unable to edit labels

### ISSUE THREAD

**Issue by CoryCalm** [ZenHubIO/support#1263]
<img width="882" alt="screen shot 2017-10-11 at 12 36 47 pm" src="https://user-images.githubusercontent.com/31014818/31462251-fbc3904c-ae80-11e7-990c-6b169a4b0071.png">

**Comment by kendramoroz** [comment]
@CoryCalm Thanks for sending this our way! Looks like this might be related to a GitHub error - Would you be able to confirm that you're exprienecing this only when ZenHub is enabled, or does it still occur with ZenHub disabled? As Labels are native to GitHub and ZenHub doesn't add additional functionality, if it's occurring with ZenHub disabled still I'd recommend reaching out to GitHub Support.

Let me know!

**Comment by CoryCalm** [comment]
@kendramoroz Thanks for responding.  I was able to edit labels correctly on a specific github issue page.

I was not able to edit labels where I popped up the issue on the #boards page.

This is a new issue, I was able to do this behavior yesterday.  I also tried logging in and out of github and still experience the 🐛

**Comment by kendramoroz** [comment]
👍 Thanks for confirming! We're working on getting a fix issued. I'll send a ping here once a version is launched with the fix!

**Comment by kendramoroz** [comment]
We've launched a fix that ensures the new label edits don't break the Modal! If you're having any other issues, don't hesitate to send us a note.

**Comment by azenMatt** [comment]
Hi @CoryCalm - we were able to release a fix for this, would you be able to confirm that everything is working as expected?

**Comment by CoryCalm** [comment]
@azenMatt Yes!  All is working now, thank you
