### ISSUE TITLE
Submit new issue button is disabled

### ISSUE THREAD

**Issue by cdparra** [ZenHubIO/support#1264]
I can no longer add issues to my repos from zenhub boards
![image](https://user-images.githubusercontent.com/630150/31466744-aecc7b5e-aeae-11e7-8549-6898d851b71a.png)

**Comment by kendramoroz** [comment]
@cdparra Thanks for submitting this! A known bug we're working on issuing a fix for 💪 - moving to in-progress. I'll ping you once a fix is launched.

**Comment by cdparra** [comment]
Ok, thanks! It started just Today for me. Has there been an update to zenhub (or github api) that started it?

**Comment by rosalynhart** [comment]
Just noting that I am experiencing the same thing.

**Comment by kendramoroz** [comment]
Fix is live! To force an update, if you head to `manage extensions` and turn on Developer mode, you'll see an option to manual update your extension:

<img width="775" alt="screen shot 2017-10-11 at 4 37 25 pm" src="https://user-images.githubusercontent.com/11036230/31472307-c816ccba-aea2-11e7-9c9c-b34fb72aa21a.png">

Please let us know if you're experiencing any other issues!

**Comment by cdparra** [comment]
Working again now. Thanks!
