### ISSUE TITLE
"Submit new issue" disabled sometimes

### ISSUE THREAD

**Issue by eljobe** [ZenHubIO/support#1267]
Sometimes, when I'm adding a new issue to ZenHub, the "Submit new issue" button is not enabled, and I cannot figure out what I need to do to make it become enabled.

![image](https://user-images.githubusercontent.com/679924/31481073-c8fd3de2-af21-11e7-89fc-21e7b4dde83b.png)

**Comment by besteman** [comment]
@eljobe I have the same issue and I was about to make one. Thank you for doing it!!!

![alt-text](http://besteman.io/1K0V1C0P2X3J/[e847c5bbb864adc0416b3d729b7b2d5f]_Image%202017-10-12%20at%2010.49.15%20AM.png)

**Comment by kendramoroz** [comment]
Hey @besteman @eljobe this was a bug yesterday that had a fix launched - looks like your extensions might not be updated yet.

To force an update, if you head to `manage extensions` and turn on Developer mode, you'll see an option to manual update your extension:

<img width="775" alt="screen shot 2017-10-11 at 4 37 25 pm" src="https://user-images.githubusercontent.com/11036230/31472307-c816ccba-aea2-11e7-9c9c-b34fb72aa21a.png">

Please let us know if you're experiencing any other issues or this doesn't solve it!

**Comment by besteman** [comment]
@kendramoroz Looks good on my end

*Love your product*

**Comment by kendramoroz** [comment]
Great to hear @besteman - Thanks for sharing the kind words! As always, keep the feedback coming 🙃 !

**Comment by cybervigilante** [comment]
Problem occurred again.

**Comment by Borrelworst** [comment]
Hi, this issue is back again, trying to create an issue in https://github.com/Microsoft/msphpsql/issues

**Comment by D-E-F-E-A-T** [comment]
Find any solution?

**Comment by Ramadevi1235** [comment]
not working

> 
> 
> Hey @besteman @eljobe this was a bug yesterday that had a fix launched - looks like your extensions might not be updated yet.
> 
> To force an update, if you head to `manage extensions` and turn on Developer mode, you'll see an option to manual update your extension:
> 
> <img alt="screen shot 2017-10-11 at 4 37 25 pm" width="775" src="https://user-images.githubusercontent.com/11036230/31472307-c816ccba-aea2-11e7-9c9c-b34fb72aa21a.png">
> 
> Please let us know if you're experiencing any other issues or this doesn't solve it!

Not working...!!!
