### ISSUE TITLE
Reports are extremely slow in Firefox

### ISSUE THREAD

**Issue by cemsbr** [ZenHubIO/support#1268]
Using the extension, after I click in Reports and select Release report, one CPU core goes to 100% for more than a minute and the fan makes noise. There's also a warning shown by Firefox in a top yellow bar saying that this extension is causing Firefox to slow down and showing options to stop ZenHub for GitHub or wait. The processing eventually finishes. I noticed it is fast in Chromium, so the extension needs some tuning for Firefox.

I'm running Debian 9 (stretch) and Firefox 57.0b7 (quantum), but I was also having this issue with version 56.

**Comment by kendramoroz** [comment]
@cemsbr Thanks for sharing this with us - would you be able to provide more info on the size of your Releases? Specifically,

- Roughly how many Issues are in the Release?
- How many connected Repos feed into the Release?
- Roughly how many open/closed Releases do you have?

**Comment by cemsbr** [comment]
Before, I'd just like to emphasize that it is quite fast in chromium. Requested data:

- 4 in backlog, 1 issue in review, 22+ closed (I tried to know the exact number, but clicking in "Load more issues" does nothing);
- 12 repos;
- 2 open Releases, zero closed.

**Comment by cemsbr** [comment]
I don't have this problem anymore. I'm currently using Firefox 57.0b12.
