### ISSUE TITLE
Be able to move(transfer) Epics to another Repos 

### ISSUE THREAD

**Issue by besteman** [ZenHubIO/support#1271]
Just want to say quickly - Love your product.

I don't think this currently possible but I would love to have. A way to move or assign epics to other repos other than the repo it is created under. 

![alt-text](http://besteman.io/0K0J232d3c39/Image%202017-10-17%20at%208.42.21%20PM.png)

So it here there could possibly be a drop-down menu to move or assign it under another repo.

This would be great because when I was learning zenhub, I made all the epics under one repo then made multiple repos to split the project up. I realized that I can't move Epics to other repos so I had to close then and make new epics.

**Comment by kendramoroz** [comment]
Thanks for sharing this feedback! Bumping over to the discussion pipeline as a future enhancement opportunity for Epics :). If there's any updates on this type of feature we'll be sure to post it here!

**Comment by releon02** [comment]
Yes please.  Just ran into this on a project.

**Comment by kendramoroz** [comment]
Consolidating with #730! Subscribe there for updates :)
