### ISSUE TITLE
Slow to load page to edit Epics (16 seconds)

### ISSUE THREAD

**Issue by danmosemsft** [ZenHubIO/support#1276]
It may relate to the number of issues in my repo: dotnet/corefx.

Eg., I click on "modify epic" on https://github.com/dotnet/corefx/issues/24739 and it takes 16 seconds to render the list of issues to choose from.

In case it's relevant, I have several repos in my dropdown:
![image](https://user-images.githubusercontent.com/6385855/31805358-dcac5424-b514-11e7-9881-8b2b69bf5d2a.png)

Once it's loaded it's snappy but it makes forming epics less "agile" to wait.

**Comment by danmosemsft** [comment]
I looked at this in the profiler but can't say much because the code is obviously minimised. Almost all of the time seems to be in script execution, no surprise.

**Comment by kendramoroz** [comment]
Thanks for sending this feedback our way - we're constantly making performance improvements, so this is helpful to know. 

In response to the time it takes to load, having a significant amount of connected repos where there's a lot of issues in these repos could be contributing to the speed. 

To document this internally, would you be able to let me know if there's any performance improvement via the web app? [app.zenhub.com](app.zenhub.com)

**Comment by danmosemsft** [comment]
@kendramoroz on app.zenhub.com the same operation takes ~32 seconds instead of ~16 seconds.

It would be great if someone could profile the scenario and see if there's something obviously wrong.

**Comment by kendramoroz** [comment]
@danmosemsft we've made a ton of significant performance improvements over the past year! Closing for now, but let me know if you're still experiencing this issue :)
