### ISSUE TITLE
Can't Set Release When Creating Issue

### ISSUE THREAD

**Issue by BenMatase** [ZenHubIO/support#1279]
I'm having issues choosing a release when creating an issue.  In the creation window, I'll click on the release drop down and select the release I want, but it won't persist.  As soon as I click outside of the drop down, it goes back to saying that the issue isn't assigned to a release.  The only way I can do it is to create the issue fully and then go back and modify the release field.  Is this known?

**Comment by kendramoroz** [comment]
Thanks for reporting this, @BenMatase - Looks like a 🐛  - the Release report should stick before the creation of the issue! I'll drop an update here once we launch a fix :)

**Comment by BenMatase** [comment]
I've been creating issues and it seems to be fixed.  I haven't tested it that much, but it works in the use cases that I have been using.

**Comment by kendramoroz** [comment]
Hey @BenMatase - pardon the late follow-up. We launched a fix for this last week so I'm happy to hear that everything has returned to normal for you. If it comes back up, or if you notice anything else in the meantime don't hesitate to send us a note 🚀
