### ISSUE TITLE
ZenHub Chrome Extension page not found?

### ISSUE THREAD

**Issue by chadfurman** [ZenHubIO/support#1280]
https://chrome.google.com/webstore/detail/ogcgkffhplmphkaahpmffcafajaocjbd

Where's the chrome extension?

**Comment by kendramoroz** [comment]
Hey Chad @chadfurman just tweeted back to you! 🤕 It's momentarily down, but we're working on a fix to get it back up! [app.zenhub.com](app.zenhub.com) is fully available while we re-launch! 💜 I'll be sure to ping you once this is fixed.

**Comment by kendramoroz** [comment]
Extension is back up! You can head to https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd to grab it :)

Let us know if you encounter any issues getting it up and running.
