### ISSUE TITLE
Your Issue is loading . Zenhub stuck !

### ISSUE THREAD

**Issue by timeturnback** [ZenHubIO/support#1286]
stuck add issue loading
Your Issue is loading ... 
at 12 AM it work fine , now 12 :50 it stuck and does not recover.
pls review , thank

**Comment by timeturnback** [comment]
and github remove the issues tab on my repo.
So basically , I can't edit any of my issues , only can add

**Comment by timeturnback** [comment]
I figure it out , I uncheck 

> Issues 
> GitHub Issues adds lightweight issue tracking tightly integrated with your repository. Add issues to milestones, label issues, and close & reference issues from commit messages.
from my repo to prevent orther user to add issuse to my public repo .
But zenhub need to add some alert for the user than just stuck on the loading page .

**Comment by kendramoroz** [comment]
@timeturnback thanks for letting us know it's resolved! If there's anything else we can help with let us know :)
