### ISSUE TITLE
Entering a percent sign into the Epic search box breaks the user interface and throws a console error.

### ISSUE THREAD

**Issue by chr15m** [ZenHubIO/support#1288]
Steps to replicate:

 1. Create a new epic.
 2. Click in the issue search box in the top right.
 3. Type "80%".

You will see the following error on the Javascript console and the UI will stop responding:

```
Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Object.getQueryIndex (main.js:56)
    at S (main.js:70)
    at P (main.js:70)
    at G (main.js:70)
    at Object.Z [as view] (main.js:70)
    at main.js:70
    at Function.<anonymous> (main.js:39)
    at l (main.js:39)
    at d (main.js:39)
```

**Comment by kendramoroz** [comment]
Thanks for reporting this, @chr15m - I was able to get the console error you described above with the reproduction steps. 

Can you provide additional detail on what UI is breaking for you as the error appears?

**Comment by chr15m** [comment]
@kendramoroz great that you could replicate the bug.

Most of the user interface stops responding to input once the bug is triggered. For example:

 * Typing a new search does not update the issues list.
 * Clicking the "comment" tab does not switch tabs.
 * The "Create epic" and "previous" buttons do nothing.
 * The issue filters have no effect.

**Comment by kendramoroz** [comment]
Thanks for confirming! I've issued this up internally to get fixed.

**Comment by kendramoroz** [comment]
👋 Hey @chr15m We just pushed a fix that should solve this. If you're using the web app, give it a hard refresh or logout/back in to see the change, and on the extension a push will be auto-pushed over the next few hours but if you'd like to force a refresh you can head to your extension manager, turn on developer mode on the top right of the page, and push a manual update! Let me know if you are still experiencing issues 🚀

**Comment by chr15m** [comment]
Fixed! :tada:
