### ISSUE TITLE
Advanced Filter options for Pull Requests

### ISSUE THREAD

**Issue by gmontard** [ZenHubIO/support#129]
Hello,

I've just discovered ZenHub and really starting to like it.
By thinking about how we could use it in my team workflow i was struck with a little concern.

Our Workflow starts by creation an issue (feature, bug etc.), then using ZenHub we'll be able to move it in the pipeline which is perfect. At the time we are ready to ship we create a pull request. The problem is that a Pull Request is also an issue and then on the ZenHub Board we've got two issues when there is only one. Even worst the new issue doesn't have any pipeline tag so this is really messy....

Will it be possible to exclude PR issues from the ZenHub board ?

The other option will be to convert issue to PR but this is way more complicated and Github is even back pedaling on the feature so I guess it's not the right path...

Thanks for your time,

Guillaume.

**Comment by gmontard** [comment]
Still new news on this one?

Thanks.

**Comment by mnacos** [comment]
should be an easy/small change

**Comment by davidrans** [comment]
This would be a huge improvement to our workflow! As it is, our only idea is to put all of our pull requests in a separate column and ignore them.

**Comment by luislew** [comment]
+1 (!)

**Comment by llaski** [comment]
+1

**Comment by oialvarez** [comment]
While I would like this feature to 'clean' a little the board, I also need to filter the board and see only the PRs for a given milestone.

Having a filter to see issues of a given type or kind, would be very helpful, since de have the PR in the flow.

Looking fordward to a related feature here. Not the same but related.

**Comment by coderjonny** [comment]
:+1: Please let there be an ability to toggle them off the board.

**Comment by coderjonny** [comment]
What do you guys do currently? I have a Pull Request Column.. curious what other teams are doing for Pull requests.

**Comment by jserle** [comment]
+1

**Comment by phemmer** [comment]
Agree with @oialvarez's idea. In addition to only showing issues, I also want to be able to only show PRs. This will make it easy to see what state PRs are in (unreviewed, needs more work, etc).

**Comment by azenMatt** [comment]
Thank you to everyone for the feedback on this issue, we just pushed out an update - v2.0.1 - that contains a simple version of this functionality, letting you toggle on/off the ability to view PRs (very similar to the mockup from @chibicode :smile:) 


![image](https://cloud.githubusercontent.com/assets/7584089/7423431/ca921ad2-ef49-11e4-8491-ca78074b4af8.png)

Your choice will be saved for the next time you come to the board. 

I am going to keep this issue open to track the V2 of this feature that will give more granular options 

- View all 
- View PR's only
- View Issues only

**Comment by chibicode** [comment]
:+1:

**Comment by azenMatt** [comment]
We just shipped version 2.3.9 - which as well as having an awesome board search feature, lets you pick between: 

- Issues and Pull requests
- Issues only
- Pull requests only

![image](https://cloud.githubusercontent.com/assets/7584089/8840114/cb623580-3091-11e5-9fc9-66a4b8482764.png)

Enjoy!

**Comment by geoffrey** [comment]
:beers:  :+1:

**Comment by sxgao3001** [comment]
@geoffrey we will you buddy!

**Comment by gaboesquivel** [comment]
@azenMatt  waffle.io handles this nicely by appending the PR to the issue 
![](http://bit.ly/2bhL6Rb)
https://github.com/waffleio/waffle.io/wiki/FAQs#prs-connect-keywords 
I'd love to see that in zenhub. 
We are chosing zenhub because it already supports burndown charts and it's nicer to have everything on the same UI.

**Comment by azenMatt** [comment]
Hi @gaboesquivel  - you can take a look at some of the ZenHub designs for this here - https://github.com/ZenHubIO/support/issues/466#issuecomment-194584927 

Which will work similar to as described in that link. 

We should be finishing that feature off over the next couple of sprints

**Comment by gaboesquivel** [comment]
@azenMatt that's fantastic!

**Comment by jezpersoderlundwintse** [comment]
@azenMatt Where did this feature go?

**Comment by harrybiddle** [comment]
+1. This feature looked great, what happened to it?

**Comment by jongsung7707** [comment]
Its location is changed.
![screen shot 2018-06-18 at 10 15 49 am](https://user-images.githubusercontent.com/10756394/41514748-4d0f5eea-72e4-11e8-93b4-9fb5eb71865d.png)
