### ISSUE TITLE
Search takes forever, need to cache the epics created/view on client side

### ISSUE THREAD

**Issue by iSimar** [ZenHubIO/support#1290]
When you need to add an epic to an issue it takes forever to search for an epic. Perhaps you can cache an array of epics created/viewed in the last 48 hrs on client side, so that the results show up right away.

<img width="374" alt="screen shot 2017-11-06 at 10 34 52 am" src="https://user-images.githubusercontent.com/5649414/32448931-3ea40e7a-c2de-11e7-8b03-26b2d2145a70.png">

**Comment by kendramoroz** [comment]
Thanks for issuing this up, @iSimar - We're constantly working on performance so I'll issue this up with the team. Don't hesitate to continue sending feedback - we are always open to hearing from our community!

**Comment by kendramoroz** [comment]
We've since made performance improvements to this dropdown!  Please let me know if you are still experiencing issues opening up the modal or searching :)
