### ISSUE TITLE
Error: the issue creation has failed

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1294]
![image](https://user-images.githubusercontent.com/490562/32673830-69ca3842-c6b5-11e7-9b23-34bd50ea85fb.png)

This is not really the best way to tell users that an issue has failed to create. There is no recoverability here. All entered text is gone, no way to retry, etc.

**Comment by kendramoroz** [comment]
😅 agreed, @adamreisnz! Can you share more details on anything that came up in the console/if you're able to reproduce the error? We'd like to issue up the cause and ensure we fix this experience beyond just the error message handling!

**Comment by adamreisnz** [comment]
I didn't check console logs, but you should be able to reproduce this the following way:

1) Start creating an issue
2) Disconnect your wireless connection
3) Try to save the issue

The steps I took were slightly different, as I obviously didn't try to save with no internet connection, but when I tried to save the new issue, I noticed my internet connection was messed up so I turn off/on my connection after which this happened.

**Comment by kendramoroz** [comment]
Ahh perfect, thanks for these steps! I'll issue this up internally as a bug fix - Looks we actually handle this error different across our platforms, where the web app handles this with a mini error notification where your information doesn't get lost, but the extension takes over the modal, losing work. We'll work to bring this experience to parity to ensure your efforts don't get lost as you create Issues!

**Comment by farrokhi** [comment]
I am seeing the same error when creating a new issue via boards. Here is the JS error message:
```
main.js:39 POST https://null:null@github.com/farrokhi/dnsdiag/issues 422 (Unprocessable Entity)
```

**Comment by lezhnev74** [comment]
The same 422 response in my case.

**Comment by kendramoroz** [comment]
👍 thanks, @farrokhi and @lezhnev74 we're digging into as it's been reported again via #1317 - I'll post updates in both locations once we pinpoint the cause.

**Comment by kendramoroz** [comment]
👋 hey everyone! After some digging, looks like we might have identified a common thread. For individuals on Chrome version ending in .108, this issue occurs. Can you please verify what version of Chrome you're using for those hitting this error? It'll help ensure that we're not missing something if it's happening for non .108 Chrome versions.

**Comment by lezhnev74** [comment]
I am on 
```
Google Chrome is up to date
Version 63.0.3239.108 (Official Build) (64-bit)
```

**Comment by farrokhi** [comment]
Here is the version string:
```Version 64.0.3282.39 (Official Build) beta (64-bit)```
Also running uBlock Origin 1.4.22, but disabling it didn't help either.

**Comment by wilfredstegeman** [comment]
Having this issue as well. I'm on a Chrome version ending in .108

![screenshot 2017-12-21 12 01 07](https://user-images.githubusercontent.com/5968782/34253143-acf53b7a-e646-11e7-95b9-4d840cf04f98.png)

**Comment by jchubber** [comment]
Same problem here. Also same version of Chrome, ending in .108. Is there any way to recover what I entered into the form? I put a ton of work into that issue!

**Comment by kendramoroz** [comment]
@jchubber Just got back to you via Twitter! We're working on fixing the issue you've described—it's related to the latest Chrome updates for versions ending in .108. Unfortunately we can't grab the submission you lost, but if you use http://app.zenhub.com  while we fix the extension it'll save your work moving forward.

---
@wilfredstegeman @farrokhi @lezhnev74 @adamreisnz 
As we work to launch the full solution, we've just released a hot fix that will allow you to bypass the broken modal and leverage the GitHub new issue template so you won't lose any more data creating new issues. 

Everyone who's reported the issue can force an extension update by turning on `developer mode` in the extension settings page of chrome via [chrome://extensions/ ](chrome://extensions/ ) and hitting update.

<img width="773" alt="screen shot 2017-12-21 at 5 10 17 pm" src="https://user-images.githubusercontent.com/11036230/34281206-dfdc19ac-e671-11e7-99d1-70bb37d6044f.png">

We'll keep this updated as a complete solution gets rolled out.

**Comment by kendramoroz** [comment]
👋  Hey everyone! Thanks for your patience as we got this workflow properly fixed!
The `New Issues` button from the Board should now work as expected without opening in a new tab or causing any errors. Let us know if you notice anything otherwise and we can re-open the issue.
