### ISSUE TITLE
One Board for many projects?

### ISSUE THREAD

**Issue by chris-sammut** [ZenHubIO/support#1296]
Considering we have **one** board with **one** pipeline structure (Awaiting input, In Progress, Done) BUT many projects with different pipelines, how can I auto sync the issues in that project with the pipeline on that ONE board?

**Comment by kendramoroz** [comment]
Hey @chris-sammut thanks for reaching out! Happy to send through some best practices - to better understand what you're looking to achieve and the current structure of your Board/repo ecosystem, do you have a few minutes end of Week/early next to jump into a support call to talk more in depth? Feel free to send through a few times/timezone you're in to kendra@zenhub.com!

**Comment by chris-sammut** [comment]
That would be great! Thanks @kendramoroz

**Comment by kendramoroz** [comment]
@chris-sammut Feel free to send me an email or ping me the best email to reach you at and we can set up a time :) - Looking forward to it!
