### ISSUE TITLE
Buttons styling look off in Firefox

### ISSUE THREAD

**Issue by Anahkiasen** [ZenHubIO/support#1298]
Not sure if this is just the extension being behind, but enabling Zenhub on Firefox changes the styling of all buttons, making them look "off". Seems the styles are applied in a different order than on Chrome from what I could gather but that's just from a quick inspector lookup so it may be something else.

**Chrome**

![screen shot 2017-11-15 at 15 57 16](https://user-images.githubusercontent.com/1321596/32842565-ae013608-ca1d-11e7-9d5e-8f859e1904c9.png)

---

**Firefox (Zenhub disabled)**

![screen shot 2017-11-15 at 15 57 56](https://user-images.githubusercontent.com/1321596/32842600-c8003716-ca1d-11e7-92c9-ff5459320182.png)

---

**Firefox (Zenhub enabled)**

![screen shot 2017-11-15 at 15 58 01](https://user-images.githubusercontent.com/1321596/32842607-cd334084-ca1d-11e7-9dc7-84b9c5f1f85c.png)

**Comment by kendramoroz** [comment]
😅  oops! We'll get these fixed up - UI bug on the loose! Thanks for sending this over, @Anahkiasen

**Comment by Anahkiasen** [comment]
Any news on this one maybe? It's been around 6 months now :/ 
All it seems to me is you use the same classes are Github so your styles override theirs, but couldn't/shouldn't the classes for the buttons loaded in by Zenhub be scoped in some way anyway?

**Comment by kendramoroz** [comment]
@Anahkiasen Thanks for the reminder here - we have this documented with the team but unfortunately haven't yet got to prioritizing this one. We'll keep the issue updated if anything changes.

**Comment by kendramoroz** [comment]
🙏 we have a fix in code review for this! I'll update once it's live in production.

**Comment by Anahkiasen** [comment]
Thanks!

**Comment by kendramoroz** [comment]
👋 This is now live!  Buttons are now fixed — let us know if you're not noticing still odd in the wild 🦁

**Comment by Anahkiasen** [comment]
Nope all good now 👍
