### ISSUE TITLE
Can't create epics

### ISSUE THREAD

**Issue by hollybrenan** [ZenHubIO/support#1309]
Hello,

I'm experiencing something similar to issue #826. When I try to convert in issue to an epic using the option on the right of the Issue modal, nothing happens. If I try to create an epic from scratch, after I've added the stories to the epic and press save, it tells me there's been an error and instead creates a new story. 

Thanks for your help!

**Comment by kendramoroz** [comment]
Hey Holly! Thanks for writing in - I followed up to the email you sent through to support@zenhub.com.
