### ISSUE TITLE
Cycle time reporting for issues

### ISSUE THREAD

**Issue by paoloaprile** [ZenHubIO/support#1310]
It'd be useful to see how long an issue stayed in a pipeline so that we can do cycle time reporting.

- A report that allows you to toggle between all the pipelines or a subset to see how long issues were in those pipelines would be really great and would let us build SLAs on our agile boards.
- Date range filter so that you can narrow down on days, weeks, months as well.
- Label filters so that you can narrow down on which features, bugs, enhancements, etc.

**Comment by kendramoroz** [comment]
Great suggestions, @paoloaprile - closing to track Kanban inspired reporting via #559 - please subscribe here to stay tuned with updates on this area!

**Comment by kendramoroz** [comment]
@paoloaprile Forgot to mention, if you head to https://medium.com/adphorus-engineering/introducing-cycle-time-for-zenhub-3101509187c8 one of the teams in our community has open sourced a cycle time report they built on top of ZenHub 🥇  Please do check this out in the meantime!
