### ISSUE TITLE
Need labels in the REST GET response of an issue

### ISSUE THREAD

**Issue by vaslot** [ZenHubIO/support#1312]
I am trying to write some automation tools but a key missing piece of information is the labels assigned to a card (issue). Labels are an important part of our development process mapping onto Zenhub. So I'd love to get them in the JSON response. Thanks.

**Comment by kendramoroz** [comment]
Hey @vaslot thanks for writing in! You can ping the GitHub API to gather the label information in a second call - this should help you get the missing label info you need! Let me know if you have any questions :)
