### ISSUE TITLE
Cannot Create Issue with Zenhub New Issue Button

### ISSUE THREAD

**Issue by nickhagen** [ZenHubIO/support#1317]
This has only been an issue for the last couple of days, however, whenever I try to create an issue using the New Issue button on the Boards tab, I receive this error:

Error: the issue creation has failed

I can still create issues using Github's native Issue button, then go back and categorize and label it in Zenhub.

**Comment by nickhagen** [comment]
Here are the console errors:

/DigitellInc/feather/issues Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
main.js:39 POST https://github.com/DigitellInc/feather/issues 422 (Unprocessable Entity)
send @ main.js:39
ajax @ main.js:39
_customFormSubmission @ main.js:70
dispatch @ main.js:39
g.handle @ main.js:39

**Comment by kendramoroz** [comment]
Thanks for sending this through Nick! I'll have the team dig in here. Just a few questions to help with debugging:

- Can you confirm if the **Settings** option for **Issues** is still turned on for the repo? You can do this by heading to the settings cog, then on the first page you should see Issues:

![image](https://user-images.githubusercontent.com/11036230/34173614-e59be44e-e4aa-11e7-91e2-ffc026f48b72.png)

- Can you confirm if there is an **active ZenHub webhook** for the repo via the Settings page as well? This is found under the repo level settings > webhooks. You'll see a URL starting with this: 

![image](https://user-images.githubusercontent.com/11036230/34173724-49b4a9b6-e4ab-11e7-86e9-43cc849c0ccb.png)


- Can you confirm if under your Profile Settings > Applications > Authorized OAuth Apps ([](https://github.com/settings/applications)) > ZenHub (click on the title and it'll link you to the screenshot page below) that the organization for the repo has a green check beside it, authenticating ZenHub access:

![image](https://user-images.githubusercontent.com/11036230/34173677-1c975d5c-e4ab-11e7-9621-320253bca875.png)

- Can you also check if you're encountering the same issue via [app.zenhub.com](app.zenhub.com)?

---

If everything is ✅  above, would you be able to open the **Network tab** and right click on any item that appears in red during the failed Issue creation, and select **Save as HAR content**, sending it to support@zenhub.com? This will help dig into anything else that can be causing the error!

**Comment by nickhagen** [comment]
Thank you for getting back to me, I have verified all the information you
supplied to check and it all seems good to me and app.zenhub.com worked
just fine to create an issue.  Attached is the HAR file you requested.

**Comment by kendramoroz** [comment]
Thanks for confirming @nickhagen looks like the file didn't get attached - to post to the GitHub issue it needs to be compressed (zipped) as GitHub doesn't support .har files as an upload. Let me know if there's an easier way to get the file if email doesn't work for you!

**Comment by nickhagen** [comment]
Here is the har file compressed.  Let me know if you need anything else.

[nickhagen.zip](https://github.com/ZenHubIO/support/files/1576651/nickhagen.zip)

**Comment by Sandu1213** [comment]
Same issue, checked with your suggestion, it seems good.

**Comment by kendramoroz** [comment]
👋 hey everyone! After some digging, looks like we might have identified a common thread. For individuals on Chrome version ending in .108, this issue occurs. Can you please verify what version of Chrome you're using for those hitting this error? It'll help ensure that we're not missing something if it's happening for non .108 Chrome versions.

**Comment by darSynereo** [comment]
i can verify

**Comment by cayetanobv** [comment]
Hi team,

I have Chrome 63.0.3239.108 (Ubuntu last build) and I've got this error. Do you have any news about it?

Thanks!

**Comment by azenMatt** [comment]
Hi @nickhagen @cayetanobv and everyone else suffering from this problem - it is being worked on as the top priority at the moment. We will keep you updated with the resolution progress

**Comment by johnlaine1** [comment]
Verified, I am running:
Version 63.0.3239.108 (Official Build) (64-bit)

Thanks for working on this because otherwise, ZenHub Rocks!

**Comment by kendramoroz** [comment]
👋 📢 

As we work to launch the full solution, we've just released a hot fix that will allow you to bypass the broken modal and leverage the GitHub new issue template so you won't lose any more data creating new issues. 

Everyone who's reported the issue can force an extension update by turning on `developer mode` in the extension settings page of chrome via [chrome://extensions/ ](chrome://extensions/ ) and hitting update.

<img width="773" alt="screen shot 2017-12-21 at 5 10 17 pm" src="https://user-images.githubusercontent.com/11036230/34281206-dfdc19ac-e671-11e7-99d1-70bb37d6044f.png">

We'll keep this updated as a complete solution gets rolled out.

**Comment by cayetanobv** [comment]
@kendramoroz Are there any news about this issue?

**Comment by kendramoroz** [comment]
@cayetanobv we launched the hot fix a week ago, and are still working on the permanent fix. With the holidays, it's been a few extra days but we're confident to have this fully fixed soon :) - we'll post back once it's live!

**Comment by cayetanobv** [comment]
Thanks.

**Comment by kendramoroz** [comment]
👋  Hey everyone! Thanks for your patience as we got this workflow properly fixed!
The `New Issues` button from the Board should now work as expected without opening in a new tab or causing any errors. Let us know if you notice anything otherwise and we can re-open the issue.

**Comment by johnlaine1** [comment]
Yeah, Thanks!
