### ISSUE TITLE
Issue View in same page

### ISSUE THREAD

**Issue by ravitez** [ZenHubIO/support#132]
It would be really cool to display the issue desc on click of a given issue without navigating away from the page.

Saves lot of time in navigation and will have great user experience.I am not sure if this is feasbile

**Comment by aupright** [comment]
Hey @ravitez - now that our new issue modal has gone live (addressing many of your suggestions here), I'm going to close this one out. Thanks again for the feedback!

**Comment by ravitez** [comment]
Thanks
