### ISSUE TITLE
New Issue is making a new tab

### ISSUE THREAD

**Issue by besteman** [ZenHubIO/support#1321]
When I want to make a new issue on the board it is making a new tab in chrome. Is it possible to make the new issue be a modal? It is slowing down my development because of the context switch here

**Comment by besteman** [comment]
@kendramoroz Thank you so much for the communication!

**Comment by kendramoroz** [comment]
👋  Hey @besteman ! Thanks for your patience as we got this workflow properly fixed!
The `New Issues` button from the Board should now work as expected without opening in a new tab or causing any errors. Let us know if you notice anything otherwise and we can re-open the issue.

**Comment by besteman** [comment]
@kendramoroz thank you so much!
