### ISSUE TITLE
Pro Desk Analytics

### ISSUE THREAD

**Issue by joenipko** [ZenHubIO/support#1323]
Epic to collect the analytics and issues related to the Pro Desk work.

**Comment by kendramoroz** [comment]
Hey @joenipko Kendra here from ZenHub! Just wanted to check to see if you meant to create this Issue for the Pro Desk Analytics piece here. If so, would you be able to dig more into how this type of Integration with ZenHub would be beneficial for your team so we can dig into how to improve your experience some more :)?

Let me know!
