### ISSUE TITLE
New "create issue" flow is displaying closed epics

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1325]
In the create issue flow, when selecting an epic, it's displaying all epics I've ever created, even closed ones.

In the edit issue flow (using the "old" layout), it's correctly filtering only open epics.

cc @liatreis

**Comment by kendramoroz** [comment]
@adamreisnz thanks for catching this! Issuing it up for the team - it should only display open Epics.

**Comment by adamreisnz** [comment]
Thanks. There's another related issue (which was fixed earlier), and that's that after selecting an epic, the list of epics doesn't disappear. Since you can only select one epic, it should select it and close the list, just like with milestones.

**Comment by adamreisnz** [comment]
Maybe related to https://github.com/ZenHubIO/support/issues/998

**Comment by kendramoroz** [comment]
Reported both to the team!

**Comment by kendramoroz** [comment]
👋 Hey @adamreisnz, closed Epics shouldn't appear anymore in the dropdown during Issue creation! Please let me know if you see anything otherwise 🚀

**Comment by adamreisnz** [comment]
Yep, thanks this appears fixed!
