### ISSUE TITLE
Markdown table header is disconnected

### ISSUE THREAD

**Issue by ripla** [ZenHubIO/support#1328]
### Steps to reproduce
1. Create a new issue in ZenHub with contents:
```
foo|bar
---|---
john|doe
jane|doe
```
2. Switch to preview

### Actual result
Table header is disconnected as seen here:
<img width="771" alt="screen shot 2018-01-15 at 11 06 52" src="https://user-images.githubusercontent.com/106030/34934747-48b8db2e-f9e4-11e7-96dd-9d74fe1383a8.png">

### Expected result
Table is rendered exactly as in GitHub.

Tested in macOS, Chrome 63.

**Comment by kendramoroz** [comment]
👍  great spot! Bumping over to `known issues` as we work to get this prioritized in our backlog!

**Comment by kendramoroz** [comment]
Doing some cleaning and forgot to give this one an update! We fixed the markdown issues with tables, but let me know if you're still seeing this incase we missed something 🚀
