### ISSUE TITLE
Better Warning For Connecting Repo

### ISSUE THREAD

**Issue by gkadillak** [ZenHubIO/support#1330]
## Background
Our organization has separate groups with different privileges, webhooks, etc. Recently, we wanted to connect an issue between repos that each existed in a different group. Naturally, we used the 'Merge Repos' feature that displayed the following modal:

![image](https://user-images.githubusercontent.com/7519543/35175363-2e44d396-fd28-11e7-91f0-5a9d9b063497.png)

The problem is that I was under the impression that merging and then splitting the repositories had fewer consequences than I had anticipated. For instance, the permissions were merged and webhooks were removed, just to name a small subset.

## Suggested Improvement
The consequences for this action need to be thoroughly outlined, specifically laying at that the repository that is being merged 'will have the following settings reconfigured'. The modal should display the list of settings, ideally with the current and new values for each as well as the number of issues, lanes, milestones, etc that will be affected by this change and that the reversal process is _painful_.

**Comment by kendramoroz** [comment]
@gkadillak Thank you for taking the time to write this up despite the pain your team just went through in this workflow 😬 . We're currently working on designing out improvements to the merge process as part of our new workspaces functionality, #139 so this is a timely request! I've cc'd in @brianleung11-3 the lead designer on workspaces who will take a closer look at how we can improve user notifications here!

**Comment by nachiketar** [comment]
Is there a way we can restrict this merge option only to leads or Admin. This feature has caused lot of pain. We should be restricting this option.

**Comment by kendramoroz** [comment]
Hey @nachiketar thanks for the ping here! We're working on adding additional elements to this workflow to make it more explicit what's going on to mitigate that potential pain. In addition, #139 will really help with this as it'll allow a lot of flexibility in how teams merge workspaces together. Relief is coming 🙏

**Comment by kendramoroz** [comment]
It's been a while, and I wanted to circle back to this issue to provide an update! Back in March we launched an additional step to the merge workflow when activity is present in the Board. 

The release notes can be found here: https://www.zenhub.com/changelog/month/march-2018#03-08-2018

If a team is merging a new repo, and there's already been activity or organization of the Board, we now provide insight into the impact this will have on the team and ask for confirmation. 

We still have further plans to address this workflow via #139, but in the meantime, we've seen this help teams avoid accidental merges!

**Comment by gkadillak** [comment]
@kendramoroz excellent! I hope the generation that comes after ours will appreciate the lack of hardship they will have to endure.
