### ISSUE TITLE
Incorrect label text colors

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1331]
### Case 1
Color on the board:

![image](https://user-images.githubusercontent.com/490562/35200371-f525536e-ff71-11e7-9bc4-d82784106ad5.png)

Color when showing a label change:

![image](https://user-images.githubusercontent.com/490562/35200366-e4a087e8-ff71-11e7-94ef-dfdb4ed29b9a.png)

Text is black instead of white.

### Case 2
Color on the board:

![image](https://user-images.githubusercontent.com/490562/35255749-6de6b674-0055-11e8-9d59-162ced77b4cf.png)

Color in the edit issue modal:

![image](https://user-images.githubusercontent.com/490562/35255739-618febb6-0055-11e8-88ad-7a24637b6863.png)

Tetx is black instead of white.

**Comment by adamreisnz** [comment]
It appears this has to do with Github recently changing their label colors (again).
After I changed the colors of some of our faulty labels, they were working ok again.

**Comment by kendramoroz** [comment]
Thanks for the heads up, @adamreisnz - as this was a GitHub Issue, I'm going to close it out, but keep us informed of anything else that comes up 🚀

**Comment by adamreisnz** [comment]
I would recommend you do keep it open and have someone look into it, because if github did change  whether black/white text is displayed for certain label colors, then you should at least follow suite and ensure consistency.
