### ISSUE TITLE
Issue observed with ZenHub 2.20.2 on FF 52.5.3 macOS when creating epic

### ISSUE THREAD

**Issue by joel-loewenstein** [ZenHubIO/support#1334]
## Issue
i have witnessed two time now that when selecting new issue in board then saving this as epic and instantly creating new issues for that yet not saved epic within the epic editor that with 5 merged repositories another issue with the same number is elevated to epic the the newly created child issues are linked to that other wrongly elevated epic instead of the one i had in the epic editor ... 

## To Do
I will monitor this further, if this may by any means some wrong usage or such by myself or if i can wittnes this behaviour some more often.

**Comment by kendramoroz** [comment]
Hey @joel-loewenstein thanks for reporting! This was a bug we fixed in the latest version of ZenHub Enterprise, but looks like you might be one version back. 

Mind getting in touch with us via support@zenhub.com with what team you're part of and we'll continue the conversation to ensure your team's admins get upgraded to help with the resolution of this bug. 

🚀

**Comment by joel-loewenstein** [comment]
Hello, could you state the versions? I verified that our internal install site has 2.22 while FF had still 2.20.2 plugin. In which version was it fixed?

**Comment by joel-loewenstein** [comment]
Via email i got the info that it was fixed in ZHE 2.22. I was not able though to see that mentioned in the release calendar.

**Comment by kendramoroz** [comment]
Apologies for the release content not reflecting this, looks like it missed the published content. We'll be sure to include fixes in the next round for 2.24 🙏 

If anyone notices this on 2.22, please do let us know as it should be resolved for all our cloud customers, and any Enterprise team using 2.22 🚀
