### ISSUE TITLE
Markdown checkbox with inset text

### ISSUE THREAD

**Issue by nowk** [ZenHubIO/support#1337]
Good day,

When writing markdown using github's checkbox support `- [ ]` any inset text does not render in preview or it shows up inline.

    - [ ] A Task

      Some info about this task

---

These are previews using github's own markdown to show you what they end up looking like:

__No inset text rendered__

- [ ] A Task

__Inset text is rendered inline__

- [ ] A Task Some info about this task

---

A few notes,

- Changing the number of spaces before the inset determines if it's not displayed or it goes inline.
- Regular list item `-` (no checkbox syntax) renders correctly.
- Code written using Zenhub (both through browser plugin and through your web app) display this type of issue.

  *Github renders all correctly.*

- I have only used Zenhub on Chrome, so can only speak to that browser.

Any help on this would be great!

Thanks!

**Comment by nowk** [comment]
One thing I didn't notice at first. This is only through Zenhub's own add/update issue forms. When Zenhub renders Github's issue forms, it works fine.

**Comment by kendramoroz** [comment]
Good spot! I've issued this up internally 🐛. We'll update this issue once we have a fix live 🎊

**Comment by kendramoroz** [comment]
🎉 this should be fixed! Let us know if you're still experiencing any issues :)
