### ISSUE TITLE
Board not visible after installing ZenHub

### ISSUE THREAD

**Issue by Katerina-Coufalova** [ZenHubIO/support#1340]
The option "board" is still missing in all repositories after installing ZenHub. I installed and removed ZenHub several times, I restarted the computer, but the board is not appearing

**Comment by kendramoroz** [comment]
Hey @Katerina-Coufalova 👋  Just a few debugging questions to help you get back on track:

- Are you using GitHub Enterprise, or Github on github.com? 
- Do you have any third party extensions blocking ZenHub, typically an ad blocker? (Privacy Badger is a known issue) If you try installing the extension in a new browser profile where no other extensions but ZenHub exist can help rule this out
-   If using Firefox, check the history settings for the browser - they need to be set to remember. If set to "never remember" the Boards won't appear as ZenHub needs to create session history to load properly. 
- Can you access https://app.zenhub.com?

Let me know!

**Comment by Katerina-Coufalova** [comment]
Hello @kendramoroz ,
1. I am using  GitHub Enterprise: https://github.ibm.com/ 
2. I tried to open my repositories in Google Chrome (I usually use IE). I can see that Zenhub has been added, I ´ve logged in, but the option Board is still not accesible : 
![image](https://user-images.githubusercontent.com/36041771/35719790-60c90ca6-07eb-11e8-9da5-dd502ecff5a5.png)
3. My IE set up is by default  - Remember History:
![image](https://user-images.githubusercontent.com/36041771/35720284-411bff74-07ed-11e8-9d6c-6f0910433e26.png)
4. Yes, I can access  https://app.zenhub.com

But I am still facing the issue.

**Comment by kendramoroz** [comment]
Thanks for getting back to me! If you’re using Enterprise, there is a different version for GitHub Enterprise for your team :). Would you mind sending an email to support@zenhub.com? We will forward over the proper extension and web app access for your team! 

Using the version specific for your Enterprise setup will get you back on track 😀

**Comment by Katerina-Coufalova** [comment]
Thank you. I´ve sent an email.

**Comment by Katerina-Coufalova** [comment]
It´s looks like closed circle. After sending the email to support@zenhub.com I received a generic reply: 
![image](https://user-images.githubusercontent.com/36041771/35722104-3c0ad8cc-07f5-11e8-99b1-911b8e292670.png)

**Comment by kendramoroz** [comment]
Hey Katerina, that was me replying! Sorry it came across as generic. GitHub Enterprise and GitHub.com are different. Enterprise teams must use a different version than what you get via zenhub.com. This is why your Boards aren’t appearing. 

Looks like the link didn’t appear properly in the email. I’ll follow up once more. The link is unique to your team so I wanted to make sure it stayed secure. You should see a second email with the link once more shortly.

**Comment by Katerina-Coufalova** [comment]
Thank you very much, Kendra. I was able to enable option Boards in Google Chrome. I am still facing the issue for IE. Would you know what could be the issue? Thanks

**Comment by kendramoroz** [comment]
Glad to see things are working in Chrome for you!
Currently the extension is only available via Firefox and Chrome, but using the web app you can use ZenHub via the browser on Edge :). 

I'm going to close this Issue out since you're back on track, but feel free to ping me if anything comes up or you have additional questions!

**Comment by szyjwu** [comment]
Dear friends,

May I know How I got the zenhub Enterprise extension file? which would be installed in Chrome, because I cannot have board display in my Chrome browser as well.

Thanks.

**Comment by teldin2002** [comment]
Hi, i am using the same enterprise github as Katerina.. would you be able to share the solution with me?
