### ISSUE TITLE
One user can't move issues on one repo

### ISSUE THREAD

**Issue by jamiefolsom** [ZenHubIO/support#1342]
A member of our team who is correctly permissioned to create and edit issues on an organizational repo can't move one he created from New Issues to Backlog. 

Other users with the same permissions can move issues on that repo.

He's logged out of github and zenhub, cleared all sessions and localstorage, updated and restarted Chrome, and attempted the move on a different machine, in a different browser. No dice.

He can do what he needs to do on other repos.

**Comment by kendramoroz** [comment]
Hey @jamiefolsom this sounds like a permission caching Issue - were they recently granted permissions from a previous read-only status? If so, this caches and be uncached by either waiting 3 hours and or going to the Settings > Application > oAuth page ([quick link here](https://github.com/settings/applications)) and revoke ZenHub access, then re-authenticate by refreshing the page and using the `sign in now` button for ZenHub that'll appear on the bottom right of the page.

The permission cache issue is something we're actively working on fixing to ensure team members don't get blocked, but hopefully this helps in the meantime! If not, please let me know and we'll continue debugging from there.

**Comment by kendramoroz** [comment]
@jamiefolsom ping on my previous message! Let me know if your team member is still encountering issues. 🕵️

**Comment by jamiefolsom** [comment]
Thanks, @kendramoroz! I'll see if my colleagues @stevemarvin and @lwjameson have a minute to try the steps you mentioned today.
