### ISSUE TITLE
ZenHub displays deleted GitHub milestones

### ISSUE THREAD

**Issue by cbeams** [ZenHubIO/support#1343]
To reproduce (or rather to witness) this behavior for yourself:

1. Visit the [Bisq DAO ZenHub board](https://github.com/bisq-network/dao#boards?notFullScreen=false&repos=109988226,98167773,49885611,116823480,98185908,99353473,97114370,102643052,116818906,17662022,116062100,98294002,98102137,112501061,108313985,116850531,98107428,101154555,102888128,102358506,114626265,116793384,98288588,114884140)
2. Click on the `Milestones` drop down and select `2017.32`
3. In the `Closed` column, click on the first matching issue you see, e.g. bisq-network/website#23
4. Notice that the issue is not in fact part of the `2017.32` milestone
5. Visit https://github.com/bisq-network/website/milestones and notice that in fact no such milestone `2017.32` exists.

Background: the `2017.32` milestone _did_ exist, but I deleted it recently. I did not remove the milestone from each individual issue before doing this, I just deleted the milestone outright.

The behavior seen above leads me to believe that ZenHub is caching milestone information in its own data model, and that this cache does not get invalidated when a milestone is deleted.

Workarounds: none that I know of. It seems I'm stuck with these phantom milestones in ZenHub in perpetuity. Note that I deleted the milestones in question days ago; it seems they'll be around indefinitely at this point.

**Comment by kendramoroz** [comment]
Hey @cbeams - that doesn't seem like the right behaviour here! Once deleted, it should auto-unassign from the Milestone and no longer be available in the filter as there should no longer be assigned Issues to that Milestone. 

If you did this a few days ago, and it's not picking up the changes (which should be instant!) there may be a problem with the repo's webhooks. 

Can you navigate to the [settings > webhooks](https://github.com/bisq-network/dao/settings/hooks) page for this repo and check to ensure there is a webhook URL showing for ZenHub?

<img width="323" alt="screen shot 2018-02-02 at 1 38 13 pm" src="https://user-images.githubusercontent.com/11036230/35755989-584c3002-081e-11e8-9a1d-f9316cfca2a9.png">

**Comment by cbeams** [comment]
> Can you navigate to the settings > webhooks page for this repo and check to ensure there is a webhook URL showing for ZenHub?

I've just verified that the webhook is indeed in place for the affected repositories, i.e. those associated with these "phantom" milestones.

**Comment by kendramoroz** [comment]
Thanks, @cbeams - I've been debugging with the team, and they've suggested that  there might be an issue with the Issue cache. You might have done this over the past few days, but to double confirm, can you **add a label to an Issue via the GitHub UI** and then after it saves as being added, **remove the label**?

If this doesn't help clear the Milestone on the Board - is there any other connected repository in the list of 23 repos that might have that Milestone still exist? If the Milestone was created in more than 1 repo, but only deleted in some of those connected workspaces, it could still be assigned to an Issue in a different repo, where the milestone still exists. 

If neither of these land on a solution, mind reaching out directly to kendra@zenhub.com with your timezone and a few times to do a live debugging session with one of our engineers? I want to ensure we get you back to a clean board as soon as possible 💪

**Comment by austinsmorris** [comment]
@kendramoroz what was the solution?  I seem to be having the same problem.  adding/removing the label did not work for me.
