### ISSUE TITLE
Filter by Author

### ISSUE THREAD

**Issue by chompomonim** [ZenHubIO/support#135]
On zenhub desk there are filters by Milestone, Label and Assignee but there are no possibility to filter by Author. I sometime would like to see my reported tasks and their status, that would help a lot.

**Comment by aupright** [comment]
Hey @chompomonim - Aaron here! 

As it doesn't look like we're getting much additional feedback on this one, I'm going to close this issue out. Going forward, this is something that we can continue to keep in mind and revisit at a later time. Thanks again for the suggestion, if there's anything else I can help with please let me know!
