### ISSUE TITLE
Firefox not loading boards

### ISSUE THREAD

**Issue by JordanDDisch** [ZenHubIO/support#1351]
Cant load zenhub boards in firefox.

Firefox Version: 58.0.1 (64-bit)

![screen shot 2018-02-08 at 9 24 55 am 2](https://user-images.githubusercontent.com/4076759/35981185-429a8a36-0cb2-11e8-8ef2-c87de20aeafc.png)

**Comment by kendramoroz** [comment]
Hey @JordanDDisch this doesn't look expected! 

Can you confirm if you're able to access ZenHub on any other Board or is it across all Boards?

Here's a few other things to check that will help with debugging:
- Can you access the unity-theme Board via [app.zenhub.com](app.zenhub.com)?
- Do you have any other extensions that have recently been added that perhaps are interferring? A good way to check is to disable all other extensions and 1-by-1 try re-enable to see if the Board loads without them enabled
- Did any firewall settings on your network change recently?
- Do you have your **history settings set to: remember**? In order for the Boards to load in Firefox, this needs to be turned on. 

Once I hear back, we'll continue debugging accordingly!

**Comment by JordanDDisch** [comment]
@kendramoroz yea firewall... thanks for your help, closing.
