### ISSUE TITLE
Wrong informations displayed in Velocity report, for Milestones

### ISSUE THREAD

**Issue by abenhamdine** [ZenHubIO/support#1352]
I have a milestone due by Feb 16 2018 : 
![image](https://user-images.githubusercontent.com/7466144/36100777-b046f36e-1007-11e8-939f-2a6521f3b3ab.png)

but in https://github.com/Arhia/payroll-app/milestones#reports?report=velocity, the end date displayed is Feb 17 :  
![image](https://user-images.githubusercontent.com/7466144/36100754-9e4374ee-1007-11e8-9671-18792822cd0e.png)

And the duration displayed (4 days) is also wrong, because from 12 to 16 feb give 5 days

**Comment by kendramoroz** [comment]
Hey @abenhamdine thanks for reporting this! We've identified that there's a bug in the way the reports pick up on the end date timing for the Milestone and how that interacts with timezones. We've issued this up internally to fix and will report back once a fix is live! 🚀

**Comment by laurencesmithever** [comment]
I'm also having issues with Velocity Tracking reports - I've emailed support@zenhub.com with the details.
