### ISSUE TITLE
Double click on "submit new issue" makes multiple issues

### ISSUE THREAD

**Issue by hitochan777** [ZenHubIO/support#1354]
In Board > New Issue, when I double-clicks on "submit new issue", it makes multiple issues.
It would be nice if the button is disabled after being clicked once.

**Comment by kendramoroz** [comment]
Good spot, @hitochan777! I'll issue this up internally - bumping over to known issues!

**Comment by hitochan777** [comment]
@kendramoroz thanks a lot!

**Comment by hitochan777** [comment]
@kendramoroz Could you please share the current status? Looks like this is not fixed yet.

**Comment by kendramoroz** [comment]
@hitochan777 thanks for the ping! This is a low priority bug in our backlog and isn't prioritized for the short term roadmap at the moment. We'll keep you updated if anything changes on this!

**Comment by kendramoroz** [comment]
We have a fix for this going through code review! Should be released early next week.

**Comment by kendramoroz** [comment]
A fix is live for this 🎉
