### ISSUE TITLE
Unable to add a specific repo to my board

### ISSUE THREAD

**Issue by wreyniers** [ZenHubIO/support#1356]
I have a board which currently is connected to 20 different repos. I have confirmed I can add additional repos, except for the repo in question.

### How:
1. Click "Repos 1/20" down arrow
2. Scroll to bottom of list and click "Add Repo +" (this link is partially obfuscated behind the bounds of the select - screenshot 1)
3. Select the troublesome repo I want o add
4. Drag and drop pipeline cards (I have tried taking the default suggestion as well as moving pipelines around)
5. Click merge

### Expected behavior:
1. Repo is added to the board and the repo count = 21

### Instead I get:
1. Repo is not added to the board and the repo count = 20

**Screenshot 1:**
![image](https://user-images.githubusercontent.com/2293035/36455815-1bd7bc14-165f-11e8-8b7a-99423313ac9f.png)

I'm guessing there's something ailing the repo I'm trying to add which is breaking the merge function.

I'd be happy to grant permission to the repo to support staff for diagnostics.

**Comment by kendramoroz** [comment]
Hey @wreyniers that doesn't sound expected! Before we grant permissions to your environment for someone on our team, would you be able to open the merge window once more with the developer console open? 

If you are unfamiliar with the console, here's how to open it:

- Right click anywhere on the page when the error comes up
- From the dropdown that appears, select `Inspect`
- An in-browser window will appear. Navigate to the second tab labeled `Console`

During the merge, is there anything in red that appears in the console? 
Can you also confirm that you have write access in GitHub for the 21st repo?
