### ISSUE TITLE
Bug! Can't load my Hub

### ISSUE THREAD

**Issue by archivum** [ZenHubIO/support#1360]
![bugs](https://user-images.githubusercontent.com/7467364/36628926-c55832da-1981-11e8-9e65-c3193b1410fe.png)

**Comment by kendramoroz** [comment]
Hey @archivum I replied to your email via support@zenhub.com, but in case you see it here first, I've pasted the typically culprit of this error below!

We've seen this occur when there's too rigid of firewall settings. We have a [troubleshooting guide here](https://www.zenhub.com/guides/somethings-not-zen#websocket-error) with more information, but if you can verify that your firewall has ZenHub whitelisted this should resolve the problem!
