### ISSUE TITLE
Support emojis in labels

### ISSUE THREAD

**Issue by amenity** [ZenHubIO/support#1365]
When working with a ton of labels, [Github's emoji-in-label](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/) support is a great way to keep them compact. It would be wonderful if emojis rendered in ZenHub boards to help reduce visual clutter...and, ya know... keep things fun. 
💃 🥇 🍕 🦒🧣🧀

![screen shot 2018-02-28 at 8 51 26 pm](https://user-images.githubusercontent.com/1463708/36869040-e9dd2318-1d5f-11e8-9ef1-9425f377d3d4.png)

**Comment by kendramoroz** [comment]
Agreed 🙆! Labels should work when added via GitHub on ZenHub renders of labels, so if there's something that is breaking let us know. On the flipside, we've issued up internally bringing the ability to use the `:ship:` syntax to render emojis in line with the ZenHub experience. We'll post here once we move this one in progress! ✨

**Comment by ryopark** [comment]
It seems that Zenhub still doesn't support [Github's emoji-in-label](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/). 
Is there any update?

**Comment by troyschneringer** [comment]
Any update on this?

**Comment by kendramoroz** [comment]
👋 @troyschneringer this repo is now sunset in favor of our new product feedback portal here: https://portal.productboard.com/zenhub/tabs/2-under-consideration don't hesitate to add this there and add your impact vote / notes for the product team!
