### ISSUE TITLE
Please do not drop ToDo

### ISSUE THREAD

**Issue by shenghu** [ZenHubIO/support#1366]
I see the message `In the next version of ZenHub Enterprise (2.24), ZenHub's ToDo feature will no longer be available.
To ensure you don't lose track of outstanding tasks, please take note of your ToDo Issues before the next release. To stay up-to-date with the launch date of 2.24, check the release notes.`

But I think ZenHub ToDo is a key feature for people to collaborate on github, which helps people to track the most interesting issues among tons of issues. I don't find alternative to replace Zenhub's ToDo. 

Can you consider to keep this feature?

**Comment by kendramoroz** [comment]
Hey @shenghu thanks for your support for ToDo! While we appreciate that ToDo has been adopted by some of our community members, we're really excited about future enhancements that create workspaces where everyone can collaborate and track projects. While we won't be keeping ToDo, I'd keep an eye on #139 which might help with some of the tracking workflows you're aiming to achieve!

**Comment by ljm22** [comment]
@kendramoroz having spent half an hour looking for this, could you guys make an edit to https://www.zenhub.com/blog/to-do-productivity-feature/ to note that it is no longer a thing? Thanks!

**Comment by slagelwa** [comment]
2nd @ljm22 's request to add a note that the ToDo feature is no longer available.
