### ISSUE TITLE
"New Issue" --> "Submit new issue" button remains ghosted and non-functional

### ISSUE THREAD

**Issue by ajelden** [ZenHubIO/support#1368]
Hello. I love ZenHub, but have an issue.

On ZenHub "Boards" tab.
Click "New Issue" button
After entering a Title and a Comment, the "Submit new issue" button remains ghosted and non-functional.

I am able to apply a create a new Issue normally outside the ZenHub Boards interface.

Environment:

- ZenHub for GitHub Enterprise 2.14.2
- GHE 2.12.5
- Chrome 64.0.3282.186 (Official Build) (64-bit)
- Mac OS High Sierra, 10.13.3 (17D47)

**Comment by kendramoroz** [comment]
Thanks for reporting! Can you reach out via enterprise@zenhub.com with what team you're part of? Based on your note, we've experienced this issue where the extension is out of date and it simply needs a fresh install to fix. Reaching out via email using your work address will enable us to provide the unique URL to your team to further debug if this solution works!

**Comment by kendramoroz** [comment]
Closing the loop on this issue: We discovered that this is related to an outdated extension version. Re-installing the specific Enterprise extension for your team should help solve the issue. If you re-install and are still experiencing this, reach out to the team via enterprise@zenhub.com!
