### ISSUE TITLE
Cannot apply a Label to an Issue: "You can't perform that action at this time."

### ISSUE THREAD

**Issue by ajelden** [ZenHubIO/support#1369]
I'm having a problem applying a Label to an Issue when going through "Boards" tab.

On ZenHub "Boards" tab.
Click an Issue.  Modal window with Issue comes up.
Try to apply a label. Results in an error message "You can't perform that action at this time."

I am able to apply a Label to an Issue normally outside the ZenHub Boards interface.

Environment:
- ZenHub for GitHub Enterprise 2.14.2
- GHE 2.12.5
- Chrome 64.0.3282.186 (Official Build) (64-bit)
- Mac OS High Sierra, 10.13.3 (17D47)

**Comment by kendramoroz** [comment]
Hello again! I'm going to close this one in favor of the previous one you submitted, https://github.com/ZenHubIO/support/issues/1368, - if you can reach out via enterprise@zenhub.com we can further debug!
