### ISSUE TITLE
Personal cross project/repo board

### ISSUE THREAD

**Issue by leandrodvd** [ZenHubIO/support#1371]
I work on multiple projects and each one has it's own multi repo Board.

I would like to create a personal board that I can use to track my issues in all other projects/repos that I'm currently working on.

I tried to create a new repo under my user and create a multi repo board adding the other repos that I want to track but I get a message stating that if I do that, the repo will be disconnected from the original board that it belongs to (so other developers would be unable to track that board in the main multi repo board).

Any chance we could have one repo added to more than one multi repo board ? So one multi repo board would be my own  "my-stuff-tracker-multi-repo-board"

**Comment by azenMatt** [comment]
Hi @leandrodvd - #139 sounds like what you are after here in terms of: 

> Any chance we could have one repo added to more than one multi repo board

This is one of our top priorities at the moment that we are working on :)
