### ISSUE TITLE
Tab bar corrupted with Projects enabled

### ISSUE THREAD

**Issue by erkkijakobson** [ZenHubIO/support#1372]
If a repo has enabled Github native Projects tab
![image](https://user-images.githubusercontent.com/16906555/37280783-85aa514a-25f7-11e8-88aa-d1c059ad21ea.png)
1. opening Projects causes half of the tab bar to unexpectedly shift to a new line
![image](https://user-images.githubusercontent.com/16906555/37280868-bbb1da9c-25f7-11e8-90c2-d7ea341282b7.png)
2. moving from Projects tab to Boards or Reports delivers an empty page (refresh doesn't help)
![image](https://user-images.githubusercontent.com/16906555/37281605-4d3aef88-25fa-11e8-9f8a-ad6190513592.png)

Tested with Chrome and Firefox, workaround is to click on another tab first then on Boards or Reports

**Comment by azenMatt** [comment]
thanks for reporting @erkkijakobson - we have some UI updates coming over the next couple of weeks that should resolve this.

**Comment by kendramoroz** [comment]
Closing as we have launched a new sidebar that should have fixed this! Please let us know if you're still experiencing issues.
