### ISSUE TITLE
Ability to use Github's own form for creation as you do when you edit/update

### ISSUE THREAD

**Issue by nowk** [ZenHubIO/support#1373]
Is there a way to get the old Github form for creating issues? The zenhub form that is currently loaded for creating issues (throw the modal) doesn't do any of the things that the github form does, such as displaying the issues ref lists when typing `#`, which makes zenhub a hurdle when it normally makes life easier.

**Comment by azenMatt** [comment]
Hi @nowk - we used to be able to do this, but some changes on the GitHub side have meant that we can no longer use their form on this modal which is why we (reluctantly) have started to use our own
