### ISSUE TITLE
Table markdown is rendered incorrectly in Zenhub issue creation dialog

### ISSUE THREAD

**Issue by aneilbaboo** [ZenHubIO/support#1376]
The example table from Github's documentation:

| First Header  | Second Header |
| ------------- | ------------- |
| Content Cell  | Content Cell  |
| Content Cell  | Content Cell  |

With Zenhub issue creation dialog: http://recordit.co/7bLDKqDwAh

With Github issue creation dialog (Zenhub disabled): http://recordit.co/Wsg4sAx5pJ

**Comment by kendramoroz** [comment]
Thanks for reporting, @aneilbaboo! A known issue we've documented to get fixed ✨ We'll report back here once a fix is live!

**Comment by kendramoroz** [comment]
We've fixed the way tables are rendered in the web app! Let us know if you still are seeing issues with the way that tables appear.

**Comment by aneilbaboo** [comment]
Thanks, @kendramoroz !
