### ISSUE TITLE
two-way sync between GitHub Project board and Zenhub board

### ISSUE THREAD

**Issue by mmatiaschek** [ZenHubIO/support#1378]
Is there a way to sync the GitHub project board and the Zenhub board?
I want a two-way-integration so github-only users can see and change the progress of issues.

- https://app.zenhub.com/workspace/o/welthungerhilfe/childgrowthmonitor/boards?repos=115618808
- https://github.com/Welthungerhilfe/ChildGrowthMonitor/projects/1

i manually created Pipelines/columns with the same name in both boards (if they were not already there, like "Done").
When i move an issue from one column to another in either boards they don't sync. 

Github board:
![image](https://user-images.githubusercontent.com/3010105/37518388-3410087c-2915-11e8-93d7-69d398510e8a.png)

Zenhub board:
![image](https://user-images.githubusercontent.com/3010105/37518410-4a28ad30-2915-11e8-81b9-e49ae567f60d.png)

**Comment by azenMatt** [comment]
Hi @mmatiaschek - we don't have any syncing options with Projects on our radar at the moment. 

The best way for GitHub-only users to get involved with ZenHub data is through the ZenHub browser extension https://www.zenhub.com/extension
