### ISSUE TITLE
Multiple `Velocity tracking` report bugs

### ISSUE THREAD

**Issue by laurencesmithever** [ZenHubIO/support#1379]
## What happens now

The Velocity tracking report is showing :

- milestone `v1.7.0` and milestone `v1.7.1` as open.
- milestone `v1.7.0` as having `0` points.
- milestone `v2.0.1` ass **not** in the list of milestones.
- no "Average story points" line.

Here are some screenshots:

​
**Velocity tracking report**

<img width="439" alt="screen shot 2018-03-15 at 11 35 14" src="https://user-images.githubusercontent.com/3215076/37520954-e36b04b0-2916-11e8-9265-c9404889015b.png">

**Milestones page**

<img width="1035" alt="screen shot 2018-03-15 at 11 40 50" src="https://user-images.githubusercontent.com/3215076/37520958-e933d264-2916-11e8-81ef-210f43ae61b0.png">

## What should happen

The Velocity tracking report should show:

- milestone `v1.7.0` and milestone `v1.7.1` as closed.
- milestone `v1.7.0` as having `43` points.
- milestone `v2.0.1`in the list of milestones.
- an "Average story points" line.​

---------------------------

Please can you take a look at this and let us a know when it is likely to be fixed?

**Comment by kendramoroz** [comment]
Hey @laurencesmithever just responded to your email! Let's consolidate there :)
