### ISSUE TITLE
Release report chart seems to be wrong

### ISSUE THREAD

**Issue by patdolem** [ZenHubIO/support#1380]
I found one case when the release chart is not reflecting the numbers (see below)
![release chart](https://user-images.githubusercontent.com/5685914/37623260-4bb063b4-2b81-11e8-9e47-ae4d4cce557f.png)
The figures below the chart are correct and there are no un-estimated issues.
I tested some other products and the release reports were good. The only difference I found between this report and the others is that the release is ending before the desired end date.

**Comment by azenMatt** [comment]
Hi @patdolem 

@pnavarrc - have you seen the above occur before?

**Comment by patdolem** [comment]
I also noticed the _**Show predicted end date (BETA)**_ doesn't work. It returns the following message:
_**There is not enough information to calculate a predicted end date**
The predicted end date will be shown when there are more data points in the Release_

**Comment by patdolem** [comment]
@azenMatt Any news about that? We found some other charts showing some strange results such as the one above.

**Comment by patdolem** [comment]
Another chart with the same issue (total story points (162) not fitting the chart):
![rbc](https://user-images.githubusercontent.com/5685914/38207353-51c468ea-3662-11e8-8b72-94e713836eca.png)
Also unable to provide a predicted end date.

**Comment by azenMatt** [comment]
Hi @patdolem - as per the follow up email, we will need to set some time up to see what is happening here. 

I'l close this issue and we will get this fixed for you in that session
