### ISSUE TITLE
"Show issues not in an epic" shows some issues that are in an epic also

### ISSUE THREAD

**Issue by ledina** [ZenHubIO/support#1381]
The option returned me mostly issues with no epic but also some that already had an epic assigned. I don't know if it makes any difference but the issues I was looking at were all closed (235 of them).

When I went through and manually assigned an epic to half the issues on my list (had to do this by clicking on each and assigning an issue as unfortunately the option doesn't exist to associate an epic with closed issues in the epic tool), they disappeared off the list as I went through each one, which was great.

But once the page refreshed later in the day, I had all 235 issues showing as having not been assigned. If I look into it, half of them are now assigned and half are not. But zenhub search seems to be confused.

**Comment by kendramoroz** [comment]
Pardon the delayed reply here - Definitely doesn't sound expected. Are you still experiencing this?

**Comment by kendramoroz** [comment]
👋 Closing as we haven't heard back! Feel free to re-open if you're still experiencing this :)
