### ISSUE TITLE
Firefox Extension: GitHub performance degraded a lot when ZenHub plugin is enabled

### ISSUE THREAD

**Issue by n-rook** [ZenHubIO/support#1383]
Hi! I'm enjoying using ZenHub, but I recently ran into some severe performance issues with the Firefox extension.

Specifically, when I'm using GitHub, it frequently becomes unresponsive for about 2 seconds due to a GC pause. I think this is because the ZenHub plugin is triggering a lot of garbage collection. I've seen memory use go above 30MB, while I've never seen it above 10MB when the ZenHub plugin is disabled. The GC pauses make using GitHub a lot less responsive.

I'm using Firefox Developer Edition 60.0b3. I can provide a memory snapshot on request.

**Comment by kendramoroz** [comment]
Thanks for pointing this out - definitely not intended! I've looped in our team internally to dig into the performance issue here. Will post back updates once we know more!

cc @Mathieuu

**Comment by n-rook** [comment]
Cool, thanks! As I mentioned earlier, let me know if there's any help or information I can provide.

**Comment by n-rook** [comment]
How is this investigation going? I've been enjoying using ZenHub's own website, but I would be happier if I could reinstall the browser extension and use it directly on GitHub.

**Comment by mnelson4** [comment]
Firefox just auto-updated to 60.0 for me and I'm now experiencing this issue too. Pretty annoying, but glad I can use app.zenhub.com instead

**Comment by cas--** [comment]
Fixed in release 60.0.1 and looks like the issue has been resolved.

From https://www.mozilla.org/en-US/firefox/60.0.1/releasenotes/?utm_campaign=whatsnew&utm_medium=firefox-browser&utm_source=firefox-browser:
> Avoid overly long cycle collector pauses with some add-ons installed (Bug 1449033)

@Mathieuu fyi, it's handy to have the upstream bug report linked here
