### ISSUE TITLE
Can't associate a PR to an issue

### ISSUE THREAD

**Issue by MuazOthman** [ZenHubIO/support#1385]
The PR page doesn't have an option to connect it to an issue anymore.
Also, PRs that used to be connected to an issue are not anymore.

**Comment by kendramoroz** [comment]
Hi @MuazOthman can you send through a screenshot of what you're seeing? With the extension installed, you should be able to see the following:

![image](https://user-images.githubusercontent.com/11036230/37853252-02570914-2ea3-11e8-8323-8e8a35504412.png)

Let me know what you're seeing!

**Comment by MuazOthman** [comment]
Thanks for the response, the functionality is back.
At the time of reporting, my account and my coworker's, under the same organization, had the reported issue for at least a couple of hours. Now the issue is resolved.
