### ISSUE TITLE
New Milestones don't appear in dropbown

### ISSUE THREAD

**Issue by andrewkelly83** [ZenHubIO/support#1391]
If I create a new milestone on Zenhub and then switch to my board still on the Zenhub site, when I click the `milestones` button the newly created milestone is not visible.

If I then go to my board on Github then it is also not visible, however if I go to the `Issues` section on Github and then select `milestones` I can see the newly created milestone.

However....

If I then go back to my board and select any issue to open, in the `milestones` dropdown on the right the new milestone is available!

Do the milestones only become visible once they are assigned to at least one issue?

**Comment by andrewkelly83** [comment]
Having poked around a bit more, I think I see the workflow for this now.

I create a milestone, then assign it to issues either individually or bulk selection. Then it will be available in the `milestones` filter.

I think it would still be good that it appears in the filter even if there are no issues assigned to it.

**Comment by azenMatt** [comment]
Hi @andrewkelly83 - thats correct, the current behaviour is that only 'populated' milestones are in the main board view filter
