### ISSUE TITLE
When an issue is created the Epic settings is sometimes lost

### ISSUE THREAD

**Issue by drobiazko** [ZenHubIO/support#1392]
I'm experiencing this issue sporadically. Sometimes when I create a new issue and choose an Epic in the dropdown on the right-hand side, the link to the Epic is lost when the issue is persisted. The browser is showing me an alert with an error. I experienced this issue twice this morning. Will provide you more details once I run into it again.

**Comment by kendramoroz** [comment]
Hey @drobiazko it's been a few weeks now! Are you still experiencing this issue?
