### ISSUE TITLE
Github name change causes issues with Zenhub

### ISSUE THREAD

**Issue by LilMinmax** [ZenHubIO/support#1395]
I changed my name on github.

We have a zenhub board with 8 repositories in it. My name was on dozens of cards in each repo. After the name change, Zenhub picked it up on maybe 1/6 of the cards, I was assigned to, leaving the name as old on the other cards for filtering purposes. Opening a card in Zenhub doesn't solve the problem even though when I open the card I see the new name as the assignee, even after closing the filter in zenhub for assignee won't show that card, I need to use the old name. No idea why some of the cards moved to the new name successfully for filter purposes, there seems to be no pattern.

This is the workspace in question

https://app.zenhub.com/workspace/o/digital-pi/omega/boards

And image attached to show bifurcated user.

Workaround is, remove user from card (even though it has new name) then re-add the same user back. Which I'm not going to do but that does cause the filtering to start working for that card.

**Comment by LilMinmax** [comment]
Well, I've been slowly working through the issues and so they are changing over to the new name and am tired of the bifurcated names so I'll just be opening and resaving the rest of them today and the example will have passed.

**Comment by LilMinmax** [comment]
@azenMatt I went into the NIghtstalker project in github, and created a new release/tag. And then I renamed it. I think this is what you meant.

In Zenhub the issues in that repo have not updated, they still show my old name.

**Comment by PeteMontgomery** [comment]
After a username change I still see the old username here

    oldusername changed the pipeline from New Issues to Ready 3 hours ago
