### ISSUE TITLE
Board issues broken on Github and Zenhub

### ISSUE THREAD

**Issue by lukakerr** [ZenHubIO/support#1398]
Both on github and zenhub board issues are broken for me (excuse the blacked out stuff):

<img width="1084" alt="screen shot 2018-04-04 at 2 43 49 pm" src="https://user-images.githubusercontent.com/20056300/38288950-00208bd4-3817-11e8-986d-1398b672020a.png">

Restarting Chrome not working - cant seem to fix this, it persists.

**Comment by lukakerr** [comment]
@kendramoroz I've just disabled all Chrome extensions, but the issue is still there. It doesnt happen on Safari or Firefox though

**Comment by drobiazko** [comment]
The board is completely screwed up. See #1404 and #1405

**Comment by krzysztofspilka** [comment]
@kendramoroz Unfortunately, we can only confirm this. We cannot open options for the board and pipelines.

**Comment by kendramoroz** [comment]
@drobiazko thanks for bringing this up! I've confirmed both and shared with the team - we'll update each respective issue with a fix once it's live. 

Unfortunately we still haven't been able to reproduce the blank screen on issues originally reported here - if anyone is still experiencing this, please let us know a few times to debug live via support@zenhub.com!
