### ISSUE TITLE
A button on the Issue page that creates a branch linked to a particular Issue

### ISSUE THREAD

**Issue by Jessalyst** [ZenHubIO/support#140]
Hey ZenPros, 

We've had some interest in a button, on the Issue page, that creates a branch that is linked to a particular issue.

If this is something of interest to you please +1 or add your feedback :) 

Cheers!

**Comment by enidvangils** [comment]
+1

**Comment by nikunjtrapasiya** [comment]
+5

**Comment by kendramoroz** [comment]
👋  Doing some clean up of our community Board and we've decided to close out this Issue as we continue to focus on core workflow experiences around Boards and Reports. Keep an eye on the `Priorities` and `In Progress` pipelines to stay updated on what we're up to 🚀 !
