### ISSUE TITLE
History of actions in issue aren't sorted

### ISSUE THREAD

**Issue by dsp0549** [ZenHubIO/support#1402]
when viewing a single issue, the history of actions isn't sorted correctly

here's a sample

![image](https://user-images.githubusercontent.com/1154913/38536635-d9f8ffa8-3c4f-11e8-8561-6875c70d5e46.png)

**Comment by kendramoroz** [comment]
@dsp0549 🙀 good spot! Definitely a pesky 🐛 here - Will report back once we have a fix!

**Comment by kendramoroz** [comment]
🎉 a fix for this is live! 

You can force an update if you toggle on developer mode, and hit update (in Chrome) or re-install the extension [here](https://zenhub.com/extension).:

<img width="632" alt="screen shot 2018-04-11 at 1 01 18 pm" src="https://user-images.githubusercontent.com/11036230/38640291-bf5215c4-3d88-11e8-9d72-e12af09b4888.png">


Please let us know if you notice any other oddities!
