### ISSUE TITLE
The options pop-up on the board is broken

### ISSUE THREAD

**Issue by drobiazko** [ZenHubIO/support#1405]
When opening the options pop-up (to use`Send to Top`) the window is reloaded and the issue is being selected. The popup does not open. However, if opens in an ugly way if you have Chrome Developer Tools open.

![platform 2018-04-11 09-56-21](https://user-images.githubusercontent.com/464220/38603692-9e25cea0-3d6e-11e8-81c3-7016d8245c41.png)

````js
vendor.675514894dc5f95c2de0.js:38 TypeError: t.getBoundingClientRect is not a function
    at t.value (index.e43139f2ee7c857f223f.js:35)
    at t.value (index.e43139f2ee7c857f223f.js:35)
    at commitLifeCycles (vendor.675514894dc5f95c2de0.js:38)
    at w (vendor.675514894dc5f95c2de0.js:38)
    at y (vendor.675514894dc5f95c2de0.js:38)
    at v (vendor.675514894dc5f95c2de0.js:38)
    at g (vendor.675514894dc5f95c2de0.js:38)
    at interactiveUpdates (vendor.675514894dc5f95c2de0.js:38)
    at Ue (vendor.675514894dc5f95c2de0.js:38)
````

**Comment by krzysztofspilka** [comment]
Confirmed, pipeline options don't work as well.

**Comment by iprunache** [comment]
I noticed this too yesterday. It was not working on github.com but was working fine on app.zenhub.com. Now it's broken in the web app too.

Our team would appreciate a fix for this, it's highly inconvenient. Thanks!

**Comment by michaelklopf** [comment]
Same here, fix asap please.

**Comment by romanoweblife** [comment]
Please fix, blocking work.

**Comment by kendramoroz** [comment]
😱 definitely unexpected behaviour. I'll share with the team and update here once we have a fix ready!

**Comment by kendramoroz** [comment]
A fix was :shipit:'d ! The updated extension version is: 2.37.26

You can force an update if you toggle on developer mode, and hit update (in Chrome) or re-install the extension [here](https://zenhub.com/extension).:

<img width="632" alt="screen shot 2018-04-11 at 1 01 18 pm" src="https://user-images.githubusercontent.com/11036230/38640291-bf5215c4-3d88-11e8-9d72-e12af09b4888.png">


Please let us know if you notice any other oddities!
