### ISSUE TITLE
Multiple boards as we have multiple GitHub projects

### ISSUE THREAD

**Issue by ricmalta** [ZenHubIO/support#1408]
In our project, as most of the projects, we have different phases and intervinientes, such as:

- Requirements breakdown
- Functional and technical specification
- Development team sprints
- QA 

Each of these phases have different needs in terms of board pipelines. 
Before we use ZenHub we used the GitHub projects to setup different pipelines.

It's possible to create multiple boards? By the documentation it's possible, but I won't figure it out how!
How can I do it and how can we move issues from one board to another (if it's even possible). If not, it's in you roadmap?

**Comment by ricmalta** [comment]
The only way to do this ia by having multiple repos?

**Comment by azenMatt** [comment]
Hi @ricmalta - this is one of our top priority items at the moment. 

Introducing 'workspaces' to allow for a repository to existing in multiple ZenHub instances (so each having their own boards / workflows) can be tracked in #139
