### ISSUE TITLE
Filter by Milestone doesn't work (Chrome)

### ISSUE THREAD

**Issue by andreapunzi** [ZenHubIO/support#1415]
In particular when using Chrome.

Filter issue by Milestone doesn't work... all the cards disappear

**Comment by robertecurtin** [comment]
I'm having the same issue. No matter which milestone I click, it gives me the link for "Issues with no milestone". If I go to a filtered page that I visited yesterday through an old link, that page loads and is filtered correctly.

**Comment by mjracca** [comment]
Me too!! This is vital to me 🙏

**Comment by azenMatt** [comment]
Hi everyone - can you update your ZenHub extensions. We have released a new version which fixes this problem

**Comment by ahmedkaludi** [comment]
same issue.

**Comment by azenMatt** [comment]
@ahmedkaludi - please update your extension version and this will be working again for you 😄 

(sometimes it can take a day or so for Chrome/FF to automatically update it)
