### ISSUE TITLE
Browser extension: Adding Epics by pressing Enter

### ISSUE THREAD

**Issue by jaller94** [ZenHubIO/support#1419]
Browser: Firefox Nightly 61.0a1 and Chrome 65
Lowest extension version tested: 2.37.45
Highest extension version tested: 2.37.47

![screen shot 2018-05-23 at 17 38 21](https://user-images.githubusercontent.com/10872136/40458297-2ce5b04e-5eb0-11e8-8f4c-a2e9e1d911b3.png)

### Steps to reproduce:
1. Have at least one epic
2. In an issue or pr click on epics
3. Using arrow up and down pick an epic
4. Press Enter

### Expected:
The epic gets added to the ticket.

### Actual:
The epic does not get added.

### Notes:
Estimates are selectable on Enter.

**Comment by haffmaestro** [comment]
+10

**Comment by haffmaestro** [comment]
@kendramoroz 👋 just kidding, you do you, but this would be so great

**Comment by kendramoroz** [comment]
👋 @haffmaestro @jaller94 You'll be happy to know that we have a fix for this coming out shortly! I'll post back once it's in production. 🎄 🎁

**Comment by haffmaestro** [comment]
@kendramoroz awesome :)

**Comment by kendramoroz** [comment]
👋 This is now live! Let us know if you're not noticing it in the wild 🦁
