### ISSUE TITLE
Ability to change the default pipeline for a new pull request

### ISSUE THREAD

**Issue by chibicode** [ZenHubIO/support#142]
Woud love to see this feature from Waffle:

[Pull Request Configuration](https://waffle.io/blog/2014/07/16/pull-request-configuration/)

TLDR: Instead of always starting a pull request from the leftmost pipeline, allow it to start on a different pipeline.

> Until recently, this [pull request] card would appear in the leftmost column of your Waffle board. This, most likely, doesn’t fit your development and work process. For example, the Waffle team would always move these pull request cards directly into our “Needs Review” column which sits between “In Progress” and “Done”.
>
> Now you’re able to configure exactly where the pull request card is placed upon the issuing of the pull request. 

Note that Waffle distinguishes pull requests submitted by collaborators and non-collaborators:

> Note the two toggles on each column for pull requests: “Collaborator PR Start” and “Non-Collaborator PR Start”.
>
> These two variants are available to support our open source customers. “Non-Collaborator PR Start” places pull requests submitted by third parties into a specified column (i.e. individuals who are not collaborators on your GitHub project, such as open source contributors). We default these to the “Backlog” in order to keep the cleanest possible workflow for open source projects. When a non-collaborator submits a pull request, it makes sense to not have it interrupt your existing work in progress. “Collaborator PR Start” controls pull requests submitted by GitHub project collaborators. These default to “In Progress” as they are most likely more contextually important to your existing work.

**Comment by morewry** [comment]
I just came here looking to find out of the exact scenario described was already possible or not. Want to put PRs in our Code Review pipeline by default.

**Comment by snario** [comment]
+1 -- same thing for us

**Comment by cjquinon** [comment]
:1 -- same use cases as morewry above.

**Comment by Anvil102** [comment]
+1 -- the majority of PR's for us should start in the code review column, with a much smaller subset needing to start in "in progress."

**Comment by thisisfranciswu** [comment]
+1

**Comment by kiramclean** [comment]
+1

**Comment by rachel-carvalho** [comment]
+1

**Comment by azenMatt** [comment]
This is now live - on the PR page, you can set which pipeline should be the default for new PRs to be added into. 

![image](https://cloud.githubusercontent.com/assets/7584089/17535554/196745d2-5e44-11e6-8f83-3ae2661b7d87.png)


Let me know any comments 😄

**Comment by Anvil102** [comment]
Great to see! Thanks, Matt!
