### ISSUE TITLE
Assignee List not loading

### ISSUE THREAD

**Issue by pflenker** [ZenHubIO/support#1420]
Hi,
I see the following issue on zenhub:
- Open an issue on zenhub (not on github)
- Click the cog icon next to "Assignees"
- Expected behaviour: A list of potential assignees shows up (same as on github directly)
- Actual behaviour: The list never finishes loading.

**Comment by kendramoroz** [comment]
Hey @pflenker thanks for reporting! Can you share a bit more information to help us debug:

- Are you on ZenHub Enterprise or using .com?
- Can you share the repo name and your GitHub organization name?
- Do you know roughly the number of assignable users on the repository where you're seeing this?
- Can you share a screenshot of the console when loading the assignee list

Thanks!

**Comment by pflenker** [comment]
Hi @kendramoroz ! Thanks for taking care of this. Here are the information you requested:
- We are on .com
- OpusCapita/pimline-specs (It's a private repository)
- Roughly 200 users
- Here is the screenshot:
![image](https://user-images.githubusercontent.com/4085533/39800464-25bf839c-5368-11e8-8d27-d31d90ab8320.png)

If you need any more input, I'll be happy to provide!

**Comment by kendramoroz** [comment]
Thanks for sharing, @pflenker - I've shared with the team! We'll have more shortly ✨

**Comment by kendramoroz** [comment]
😬 pardon the delay on this one - @pflenker can you share if you're still running into this issue?

**Comment by pflenker** [comment]
Hi there,

yes, we are still experiencing this issue.

Best regards,

Philipp

**Comment by pflenker** [comment]
Hi @kendramoroz - any news on this issue?

**Comment by pflenker** [comment]
Nope, looks good to me. I will close it. Many thanks!
