### ISSUE TITLE
Notifications on issue/pr additions to a pipeline

### ISSUE THREAD

**Issue by jasonkuhrt** [ZenHubIO/support#1421]
We have a pipeline called `ready for qa`. We would like developers to be able to move their issues/pull-requests into that pipeline and have QA team notified that a new issue/pr is ready for qa.

**Comment by kendramoroz** [comment]
Great suggestion, @jasonkuhrt - post #139, this type of notification system is something we'd love to automate and help teams add to their workflow. In favor of 139, as well as https://github.com/ZenHubIO/support/issues/31 which captures the notifications via pipeline changes, I'm going to close this one.  Keep the feedback coming!
