### ISSUE TITLE
Name/title of a issue with ZenHub API?

### ISSUE THREAD

**Issue by thiago11122** [ZenHubIO/support#1424]
Hi.

I would like to know if there is a way to access the name/title of a Zenhub board using the ZenHub API, and not only it's number?

Thanks!

**Comment by kendramoroz** [comment]
Hey @thiago11122 thanks for the suggestion! This is currently possible to grab via the GitHub API when paired with the ZenHub API :). Let me know if you're having any trouble locating where to do this.
