### ISSUE TITLE
"See older events" hides important comments with no way of turning it off

### ISSUE THREAD

**Issue by hankthewhale** [ZenHubIO/support#1426]
![screen shot 2018-05-11 at 10 12 58 am](https://user-images.githubusercontent.com/5420223/39928864-79cbdbe6-5504-11e8-8422-04f2d4ac9698.png)

Not sure how new this feature is, but I'd like for it remember if I want to see github comments by default or not. I keep missing parts of conversation because it only shows the latest couple of comments now, requiring me to always expand history. 

Honestly, I'd prefer to not have the feature at all, though I imagine some users like it. So possibly have a setting that allows me to turn it on or off? Maybe there is one already and I can't seem to find it? 

Any insight would be appreciated. Thanks!

**Comment by shinytoyrobots** [comment]
Agreed. My team was discussing last week how infuriating this feature is, and how much we miss by not realizing there are previous comments and discussion on issues.

I can understand a filter for "events" like pipeline changes, or label updates. But by default hiding comments, and not having a way to turn it off, it's definitely undermined the user experience.

**Comment by kendramoroz** [comment]
👋 Hey all - the collapse events functionality on the web app shouldn't be hiding comments 😱! Can you please send us a screencast to support@zenhub.com if possible showcasing an issue where it's collapsing comments for you? I just dug through a few test cases and only events were being collapse (label changes, estimate changes, etc.) 

If hiding even the events is also causing grief, please let us know! We'd love to hear how we can also improve the event collapsing experience 👍

**Comment by finnribm** [comment]
Screenshots sent showing the collapsed and expanded view, with comments being hidden when collapsed. This was on a github Enterprise instance, not github.com

**Comment by kendramoroz** [comment]
@finnribm thanks for confirming and apologies for the delay! Mind shooting us an email via support@zenhub.com using your work email and we can check what version you're on and whether there is a new version that has the fix for this?

**Comment by jconsidi** [comment]
I've seen this trigger with comments in the last two hours that I had not viewed yet. Very frustrating. That was with Github Enterprise. Zenhub 2.22.2.

**Comment by shaina33** [comment]
I see this feature hide comments all the time. Very annoying. It's reached the point where I specifically direct colleagues to check the hidden comments on an issue to see important info. Github Enterprise and Zenhub 2.22.2.

**Comment by finnribm** [comment]
I received an email from ZH:

After some further investigation, this looks to be an issue with how ZenHub is handling issue events following the latest GitHub Enterprise release.

Later this week (June 1st) we'll be upgrading your enterprise's instance of ZenHub to our latest version (ZHE 2.24) which disables the "hide events" functionality and should solve this issue for you and your team. If you're still seeing this error after the upgrade has been completed, please reach out to let me know and we can continue looking into a fix for this.

**Comment by hankthewhale** [comment]
Just confirming that we are also on enterprise. I'll discus with our internal tools team to see when we're planning to get the next zenhub upgrade to fix this. It's been such a killer to productivity.

**Comment by kendramoroz** [comment]
Hey everyone, thanks for keeping us sharp on this issue! As @hankthewhale mentioned, this should be fixed one the team does the upgrade on your ZenHub Enterprise version. Once the upgrade has been completed we'll be sure to post back here, but you can also follow along via your internal channels.

**Comment by docwhat** [comment]
Is there a work around until we upgrade to a newer version of ZenHub?

**Comment by docwhat** [comment]
Yeah, this is worse than I thought... it actually changes the order of things!  Events that happened 7 minutes ago got buried in events/comments from last week.  yuck.

**Comment by kendramoroz** [comment]
Hey everyone! Can everyone confirm if you're now on the ZenHub Enterprise 2.24 extension? We did the upgrade last week and this issue should be resolved in this version. If you're unsure what version you're on, right click on the extension to select 'manage' and verify in the Chrome settings, or Firefox add on's menu. 

You can force an update in settings, or if you need to re-download you can get in touch via support@zenhub.com for the appropriate link!

**Comment by finnribm** [comment]
Yes, 2.24.2 seems to have done the trick for our Enterprise instance, thanks.

**Comment by docwhat** [comment]
In 2.24.2 I haven't found any issues with the "see older events" thingy, yet.
