### ISSUE TITLE
Moving Unfinished Tasks in a Sprint- Burndown removes the moved task

### ISSUE THREAD

**Issue by tetris12367** [ZenHubIO/support#1427]
Hey! 

I apologize if this is a duplicate issue but I didn't see many other issues relating to it but I'm working on a uni project and when I move unfinished tasks at the end of a sprint to a new sprint, it just removes those tasks from the burndown chart as if they weren't in the sprint in the first place. It would be good if we have unfinished tasks at the end of a sprint, the burndown chart acknowledges that the unfinished task was part of that sprint but was also moved to the new sprint. This gives more accurate information of tracking how well we are working via our burndown otherwise it just says that we are always finishing our tasks in each sprint. 

I was using this link to create my sprints: https://www.zenhub.com/guides/your-first-sprint-using-zenhub.

If you need more information on my issue just let me know, thanks!

**Comment by kendramoroz** [comment]
Hey @tetris12367, totally understand this pain point! We've been working on some prototypes for what this would look like here: https://github.com/ZenHubIO/support/issues/1283 - feel free to subscribe and follow along there for updates as they become available!
