### ISSUE TITLE
Markdown doesn't render line breaks

### ISSUE THREAD

**Issue by zanona** [ZenHubIO/support#1429]
With the updated markdown rendered line breaks are not following Github format anymore whereas only paragraphs are rendered correctly with an empty line in between them but whenever a line break, things don't show as expected.

```markdown
Line 1
Line 2
Line 2
```

### Github output
```
Line 1
Line 2
Line 3
```

### Zenhub output
```
Line 1 Line 2 Line 3
```

**Comment by kendramoroz** [comment]
👍 Thanks for reporting, @zanona - a pesky 🐛 !

**Comment by kendramoroz** [comment]
The fix is in production! let us know if you're still experiencing this :)

**Comment by zanona** [comment]
Thanks @kendramoroz that seems to work well now.
