### ISSUE TITLE
-1 support

### ISSUE THREAD

**Issue by bluong** [ZenHubIO/support#143]
Hey, starting to use the Zenhub product and it looks great from a workflow standpoint, especially with the +1 feature.  I was wondering if you could also have a -1 feature that is separate from +1.  In our current workflow, we use +1s to signal our positive intent over a pull request and a -1 to signal a disintent over a pull request and if you decide to implement this feature, we'd like this 2 metrics to be kept separate.  Thanks!

**Comment by azenMatt** [comment]
you can now 👎  with GH reactions :)
