### ISSUE TITLE
Feature Request: Cumulative Flow Diagrams

### ISSUE THREAD

**Issue by Charlenes1** [ZenHubIO/support#1432]
Any chance of adding a report that give you a cumulative flow diagram? These are features that both JIRA and VersionOne offer.  It would be really helpful to assess bottlenecks better.

Here's a good description of what it is and all the different things you can assess from the diagram/chart - http://brodzinski.com/2013/07/cumulative-flow-diagram.html

**Comment by kendramoroz** [comment]
No immediate announcements in the roadmap to tackle Kanban reporting, but you can subscribe here: https://github.com/ZenHubIO/support/issues/816 to stay tuned on updates around timelines!
