### ISSUE TITLE
I want to connect a merged pull request to an issue, because I forgot to connect it before I merged the PR

### ISSUE THREAD

**Issue by bchociej** [ZenHubIO/support#1434]
I have an open Issue, to which I want to link an already-merged pull request. In the UI, trying to do this silently fails with no error indication, and the network tab shows a 400 error: `{message: "Invalid request Must connect an open issue"}`

I would like to be able to connect the merged PR to that issue even though the PR has been merged, since I simply forgot to do so earlier, and now I can't re-open the PR to connect it.

**Comment by kendramoroz** [comment]
Hey @bchociej Apologies on the delay on this one! Based on the 400 error, something seems unexpected here. Can you reach out via support@zenhub.com and share a few times that work to jump into a debugging call? Let me know!

**Comment by kendramoroz** [comment]
Closing this here, but let us know if you're still experiencing issues!
