### ISSUE TITLE
Newly created releases don't show up in release filter

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1437]
1. Create a new release from the board interface, using the green + button
2. Save the release
3. Try to filter on issues in that release
4. Observe that the newly created release is not in the list

**Comment by kendramoroz** [comment]
@adamreisnz can you share a screenshot of where you're not seeing the Release? Currently the filters at the top of the Board will only show those Releases (same with Epics and Milestones) where Issues on the Board are already assigned to them. In multi-action, or on the sidebar of an Issue however, you should be seeing all potentially assignable options, which should include the newly created Release! Let me know :)

**Comment by kendramoroz** [comment]
Thanks for verifying! This currently is intended, as no issues are yet in this Release on the Board. Once you add Issues on the Board into the Release, it'll appear in this filter 🚀. Let me know if you have trouble with this once adding Issues in there!
