### ISSUE TITLE
FR: Board lacks time tracking

### ISSUE THREAD

**Issue by dwarf-jdu** [ZenHubIO/support#1440]
Highest on our wish list and definitely a need to have: 

We are a department of Project Managers who really miss a time logging/tracking feature. Today we "convert" story points to "hours", and use these to manage time and budget. But we have no overview of completion level nor of how much time was spend compared to estimated on issue level.

Suggested solution:
- Should be possible to integrate to Workbook or any other popular time logging system.
- A field in ZenHub with a bar that indicates how much time has been registered, how much time was estimated, and time remaining.

This solution would help us manage the project budget and allocate the ressources much more effectively.

**Comment by kendramoroz** [comment]
Hey @dwarf-jdu thanks for the great suggestion, it's a popular request! While we don't have any immediate roadmap plans to incorporate time tracking, if anything changes you can follow along on https://github.com/ZenHubIO/support/issues/218 and subscribe for updates.
