### ISSUE TITLE
Extension does not generate the URLs of avatars correctly

### ISSUE THREAD

**Issue by jaller94** [ZenHubIO/support#1442]
Browser: Firefox Nightly 62
Zenhub extension: 2.37.50

I just noticed today that Zenhub fails to generate correct URLs to my avatar, when adding entries to the timeline in a PR on github.com.

### Steps
1. Open a ticket on github.com with the Zenhub extension enabled
2. Perform an action that causes Zenhub to append something to the timeline (e.g. switch the pipeline)

### Expected
The new row in the timeline shows my avatar.

### Actual
The new row in the timeline does not show my avatar. I have to reload the tab for my avatar to display properly.

On the screenshot my avatar shows up as `@j` and the URL is `?size=32`.
_______________________________
![screen shot 2018-05-28 at 12 49 06](https://user-images.githubusercontent.com/10872136/40627795-f51a9804-6275-11e8-87e3-42c11a17d2b6.png)

**Comment by kendramoroz** [comment]
Hey @jaller94 thanks for sharing this - similar to my message on your previous issue, we don't officially support Nightly/Developer editions of Firefox, but will ensure this doesn't creep into any official releases of Firefox versions!
