### ISSUE TITLE
Future of Zenhub now that Github is taken over by Microsoft?

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1446]
Any thoughts about the future of Zenhub after this acquisition?

I imagine Microsoft will possibly make things quite difficult if not impossible for Zenhub to keep integrating with Github the way it does, or do you not think it'll get to that?

**Comment by azenMatt** [comment]
Hey @adamreisnz - we put out a short blog post here to address this - https://www.zenhub.com/blog/what-microsofts-acquisition-of-github-means-for-zenhub/

You can rest assured that we are going to keep working on ZH 😄
