### ISSUE TITLE
Card content not opening with Firefox on Windows 10

### ISSUE THREAD

**Issue by mikehug** [ZenHubIO/support#1448]
I have installed Firefox extension on Windows 10 Firefox Version 60.0.1 but when I  open a card on the board I get this message:

The GitHub page cannot be loaded. Make sure that Issues are enabled on the repository settings.

When I use Chrome Version 67.0.3396.62 with Zenhub extension on the same machine it works fine.

**Comment by kendramoroz** [comment]
Hey @mikehug - Looks like my team mate @annabelleglass is corresponding on this via email with you 😊 - closing this issue to ensure we keep the thread of debugging in the same location.
