### ISSUE TITLE
Middle clicking sidebar menu causes navigation away from Board view

### ISSUE THREAD

**Issue by alexchantastic** [ZenHubIO/support#145]
When middle clicking any of the sidebar menu items (see screenshot), you are navigated away from Board view. Typically a middle click is used to open a new tab for the middle clicked link while remaining on the same view.

![image](https://cloud.githubusercontent.com/assets/604167/4848724/4017836e-605c-11e4-8127-a72a129525d0.png)

As a matter of fact, even clicking the small empty space above "Code" and below "Graphs" navigates you away from Board view. Perhaps there is an erroneous click handler on the sidebar?

**Comment by Mottie** [comment]
I'm having this issue too... I also concur, it's a bug, not a feature request!

To clarify, while the *board is open*, middle clicking any of the icons (except the burndown icon) in the side bar will *reload the board page as the repo code page* and open the middle-clicked icon page in a new tab. I expect that only the middle-clicked on page would open.

**Comment by crazydog115** [comment]
I want to add that when this bug occurs, you cannot make the board reappear without refreshing the page.

**Comment by azenMatt** [comment]
this is fixed with the new GH layout :/
