### ISSUE TITLE
Opening images from the Board Issue Modal results in blank page

### ISSUE THREAD

**Issue by kendramoroz** [ZenHubIO/support#1451]
https://github.com/ZenHubIO/support/issues/1447

## Reproduce

1. Open an Issue with an Image (ie. this one)
2. Click on said image from the Board modal 
3. Blank page in new tab appears
4. Open image from native GitHub UI and image opens in new tab no problem

![image.png](https://images.zenhubusercontent.com/5833aa0bb9dc3c6220225356/567c8da5-cfd2-4522-9a2f-785477e08cf8)

---

@azenMatt

**Comment by CoryCalm** [comment]
bump for this one :)

**Comment by azenMatt** [comment]
bug fix in progress 😄

**Comment by kendramoroz** [comment]
Fix is in production! If anyone is still experiencing issues, let us know :)
