### ISSUE TITLE
ZenHub history items show up in wrong order

### ISSUE THREAD

**Issue by teeberg** [ZenHubIO/support#1453]
Why does the most recent one (5 minutes ago) show up at the top, before a bunch of other ones that happened 2 hours ago?

![image](https://user-images.githubusercontent.com/199071/41264127-e49244fc-6d9f-11e8-9ef2-99b80de75f89.png)

**Comment by kendramoroz** [comment]
Hey Jonas, that looks unexpected 😱 ! Let me do some investigating and see what's causing this. Stay tuned for updates ✨

**Comment by kendramoroz** [comment]
Hello again! Can you share more about the extension version you're using @teeberg?

**Comment by teeberg** [comment]
Right now I have 2.37.20 installed

**Comment by kendramoroz** [comment]
Sounds like this might be a case of an outdated version! If you're using chrome, you can force an update by going to manage extensions, turning on developer mode, then clicking update.

![image](https://user-images.githubusercontent.com/11036230/41884990-d65e15bc-78aa-11e8-88fc-5f14ec14494c.png)

Alternatively you can uninstall and reinstall via https://zenhub.com/extension 

Post re-install let me know if you still encounter this 😊

**Comment by teeberg** [comment]
Apparently ublock somehow caused zenhub to not update itself and after uninstalling, the Chrome Store didn't let me reinstall... Disabling ublock pulled in the new version, so I'm on 2.37.55 now. Let's see how that goes! I'll close for now! :)
