### ISSUE TITLE
Unable to login with Chrome

### ISSUE THREAD

**Issue by grappler** [ZenHubIO/support#1459]
I am getting the following errors in the console.

> Refused to connect to 'https://api.zenhub.io/login' because it violates the following Content Security Policy directive

> vendor.js:32 Possibly unhandled Error: auth:error:not_authed

ZenHub version: 2.37.55
Chrome on Mac version: 67.0.3396.99

**Comment by kaushal98** [comment]
I too have a similar issue. Can't login using GitHub from Chrome extension. Nothing happens after clicking **Sign In with GithHub**

ZenHub version: 2.37.55
Chrome on Ubuntu: Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by grappler** [comment]
I tried it again now and it seems to work for me. So I am not sure what the issue was.

**Comment by kendramoroz** [comment]
👋 Thanks all for your reports! We were experiencing a momentary issue with login but things have since been resolved. Can everyone confirm if you're able to successfully get back into ZenHub?

**Comment by kaushal98** [comment]
Seems to be working for me too. But spent so much time yesterday debugging it - uninstalled/installed the  Chrome plugin several times, restarted computer etc, but nothing worked.

Anyway, is there anyplace where you update the status of services? For me this wan't a momentary issue, I think it lasted whole day.

This along with the Slack outage yesterday - perfect storm :)

**Comment by kaushal98** [comment]
Never mind, still having issues in logging in

![image](https://user-images.githubusercontent.com/2553890/42055707-e92ec9c4-7ae5-11e8-8161-e5c55427c7e0.png)
