### ISSUE TITLE
Closed issues are not moved to the closed column

### ISSUE THREAD

**Issue by liatreis** [ZenHubIO/support#1460]
This used to work before. When I pick up an issue and close it, it doesn't go into the closed column, and will stay in the current column until I refresh the page.

**Comment by arist0tl3** [comment]
Piggybacking here. 

I think there is probably a larger issue that is causing a stale boards view. Making an update to an issue never results in an update on the board view without a refresh. 

While on the board view, there is no network activity being logged.

**Comment by kendramoroz** [comment]
🤔 unusual! Definitely looks like something is going on here. The team is investigating!

**Comment by kendramoroz** [comment]
Hey everyone! The team found the issue and a fix is live. Please let us know if you're still experiencing this :)
