### ISSUE TITLE
Expand the height of the comment box when editing - it only shows 4 lines 

### ISSUE THREAD

**Issue by ssucher** [ZenHubIO/support#1462]
When editing the main/first comment on a card, the default view only shows 4 lines, regardless of the amount of text in the card. We have to expand this almost every time we edit a card in order to have a usable workspace. 

When you click to edit a comment, it would be nice to have this auto-expand to the height of the full comment or at least to to the visible part of the page if the comment is longer. 

See below:

Current:
![image](https://user-images.githubusercontent.com/18265660/42114883-f94de3b2-7bad-11e8-8e4e-387e4456c274.png)

Desired:
![image](https://user-images.githubusercontent.com/18265660/42114957-49c16c24-7bae-11e8-9c15-b550cad558ad.png)

**Comment by kendramoroz** [comment]
👋 Hey there! Thanks for sending this our way. By default, we use the same height as that of GitHub for the default comment view. I'd recommend reaching out to the GitHub team at support@github.com with this feature request as it touches native GitHub functionality 😊

**Comment by ssucher** [comment]
@kendramoroz maybe my request wasnt clear.  When I first write a comment, the box looks fine.  The problem occurs when I go back to edit the comment. When I edit the comment, the height is collapsed using zenhub. This actually behaves different from GitHub. When I edit a comment in GitHub, the height of the box expands to the height of the message. I'd actually like zenhub to behave like GitHub when editing a comment.

**Comment by ssucher** [comment]
@kendramoroz let me know if you have any questions.
