### ISSUE TITLE
Is it possible to set estimate when creating an issue with template?

### ISSUE THREAD

**Issue by YanFenGuo** [ZenHubIO/support#1463]
I Googled but didn't found the answer, this is a basic requirement I think.

In my Github repository, I have an issue template, but according to [About automation for issues and pull requests with query parameters](https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/), supported query parameters doesn't include Zenhub specific properties like Estimate, Pipeline, Epic and Release. I'm expecting to be able to set them automatically like labels. So when I create an new issue with template, I can have predefined content including Labels and Estimate.

Thank you.

**Comment by kendramoroz** [comment]
👋 At the moment when creating new Issues, we don't have a meta-data setting that can apply an estimate when creating an Issue. We recommend as a best practice that estimates shouldn't be auto-assigned, as each Issue is unique and ideally gets discussed by the team in a sprint planning, backlog, or estimate-specific session. 

Let me know if you have any best practices questions we can help with! Closing this for now as we don't have plans to change this behaviour at the moment.
