### ISSUE TITLE
Closing issues using keywords

### ISSUE THREAD

**Issue by ivasic** [ZenHubIO/support#1465]
When using predefined keywords, such as FIX, FIXES, CLOSE etc.. as defined [here](https://help.github.com/articles/closing-issues-using-keywords/), the issue is always closed. This is most of the time desirable with GitHub flow (only open/closed status). However, in ZenHub we have multiple columns so it would be very handy if developers could move an issue to a specific column (e.g. "QA") using keywords (commit messages / PRs / comments) rather than having to move tickets manually.

**Comment by kendramoroz** [comment]
Thanks for submitting, @ivasic - at the moment we don't have plans to override GitHub's keyword closing.
