### ISSUE TITLE
Rule Change - Toll Linehaul - Aaron Knight

### ISSUE THREAD

**Issue by LegChecker** [ZenHubIO/support#1467]
Driver:                  Aaron Knight

Division:               Adelaide

Aaron Knight was created as a standard driver, he has now become a BFM driver on the 01/07/2018

Can you please change his rule at your end

**Comment by kendramoroz** [comment]
👋 Looks like you accidentally created an Issue here! Just cleaned up the issue so your personal information isn't hanging around the support Board.
