### ISSUE TITLE
Burndown Report misidentifies closed issues as being in New Issues pipeline

### ISSUE THREAD

**Issue by guerrini** [ZenHubIO/support#1468]
Within a Burndown Report's "Completed Issues" list, closed issues are misidentified as being in the "New Issues" pipeline.  @kendramoroz observed this in https://github.com/ZenHubIO/support/issues/1165 (in 26 June 2017 comment), but it may not have elevated to a bug report as issue 1165 made a different request.  

To be clear, only issues that appear in the Closed pipeline on the board are misidentified on the Burndown report as being in the New Issues pipeline.  Issues in other pipelines, regardless of whether selected as a "Burn Pipeline," are correctly labeled.

**Comment by kendramoroz** [comment]
👋 Hey @guerrini mind sending over a few screenshots of what you're observing, this doesn't sound expected!

**Comment by guerrini** [comment]
@kendramoroz Is my description and that screenshot enough for you to work with to investigate the issue?  I am happy to provide additional information to help.

**Comment by kendramoroz** [comment]
Thank you for sharing! We'll see what's going on and let you know if we need anything else to investigate!

**Comment by kendramoroz** [comment]
👋 Spoke too soon! Can you confirm:
- Your extension version
- The GitHub org and repo names of where you're seeing this

**Comment by guerrini** [comment]
I am using ZenHub for GitHub Enterprise 2.24.3.  I am seeing the issue in my company's GitHub Enterprise instance...not sure the org and repo names would help you (let me know if I am mistaken).

**Comment by kendramoroz** [comment]
Ah - Enterprise! We won't be able to dig into the logs in that case. Let me sync with the team on next steps.

**Comment by guerrini** [comment]
Before you do that...I replicated the issue (no pun intended) on GitHub in a personal, public, forked repo.  For this I used ZenHub for GitHub 2.37.62.  Try this repo:  https://github.com/guerrini/youtube-g

**Comment by annabelleglass** [comment]
Hey @guerrini ! Stepping in for Kendra here. I tested this on my end as well and noted the same behaviour. I think there is something funky going on, so I will file an issue with our development team here to investigate this further. Thank you for all of your help in the initial troubleshooting and testing process, it is much appreciated!

**Comment by guerrini** [comment]
@kendramoroz So the fix is to remove the pipeline identifiers altogether?  The update fixes the misleading information, but it also removed very useful information—especially when selecting more than two burn pipelines (a daily use case for us).  

I request reopening the ticket and considering these preferable solutions, remembering that other pipeline indicators were reporting correctly and could have been left alone:
1. Set the pipeline indicator for closed issues to "Closed."
2. Remove the pipeline indicator only for Closed issues.  

I humbly offer a few implementation options:  

1. The code already knows whether an issue is that special closed state in order to apply the special `.zhc-icon zhc-icon--issue-closed-red` and `.zhc-badge zhc-badge--estimate-closed` class names/selectors.  Why not leverage that same logic to set the text of `.zhc-issues-list-item__pipeline span`?

2. Although a little "hacky," you could use jQuery:  `$('.zhc-icon--issue-closed-red').closest('.zhc-issues-list-item').find('.zhc-issues-list-item__pipeline').html('<span class="zhc-icon zhc-icon--board-light"></span>Closed')`.  

3. You could not use CSS as currently coded, since all class names that indicated closed status are cousins of the pipeline indicator; however, you could use CSS to set the text if you add a class name at the `.zhc-issues-list-item` level.  Adding such a class may be worth considering anyway so you can set that state in one element and style lower levels via CSS rather than using more complex code logic, and managing so many specific class names.

Hope that helps, and thanks for your consideration!
