### ISSUE TITLE
Allow CSS customization (e.g. by adding data attributes for each state)

### ISSUE THREAD

**Issue by chibicode** [ZenHubIO/support#147]
This is a follow-up to my comment on this thread: https://github.com/ZenHubIO/support/issues/129#issuecomment-61154692

One of the nice things about Chrome is that it lets you load your own CSS by using [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en), [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en) and others. So if there are some things on ZenHub that users don't want to display for instance, they could write custom CSS to hide those elements.

I tried doing this to hide pull request cards from boards, but failed b/c there aren't specific classes I can target w/ a CSS selector. It'd be nice if the card's state is exposed on some `data-` attributes so they can be selected and styled.

![image](https://cloud.githubusercontent.com/assets/992008/4854041/d51811f6-608c-11e4-9317-251fe5ab3232.png)

There will probably be very few people requesting this feature, but it seems like a simple fix that can help many. Maybe this can be "an experimental" or "debugging" feature that users opt in, etc.

**Comment by dshahin** [comment]
:+1: This would help by allowing cards to be colored based on type (PR/BUG/FEATURE) or other data.  This would help simulate the use of colored cards in real life issue boards.

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
