### ISSUE TITLE
How to change the default repo used when I click "New Issue"?

### ISSUE THREAD

**Issue by l2fprod** [ZenHubIO/support#1475]
I have two repos linked together in a board:

![image](https://user-images.githubusercontent.com/12746550/43528223-c100f822-95a8-11e8-87e3-4cb5de2c85ed.png)

When I press "New Issue", it picks the second repo - and in my case most of the time it is the incorrect repo, it is the first one I'd like to use

![image](https://user-images.githubusercontent.com/12746550/43528258-da9d715c-95a8-11e8-9dc1-65329147c50d.png)

How do I select which repo is picked when pressing "New Issue"?

I know I can press the "+" button to select the repo but I'd like to be able to specify the default repo for this board.

**Comment by kendramoroz** [comment]
Hi there! Currently the new Issue pipeline will create the Issue in whichever repository you navigate into the Board from. If you navigate from the repo that's 2nd in the list, the button will create the Issue there. If you're on that repo, but need to create it in the first one on the list, you can use the `+` button to switch where the Issue gets created when creating it :).
