### ISSUE TITLE
Use GitHub-flavored markdown

### ISSUE THREAD

**Issue by lia-simeone** [ZenHubIO/support#1476]
I'm guessing a bit as to the source of the problem, but _I think_ it's because ZenHub uses a different flavor of markdown than GitHub. The difference created a bit of confusion for me because I see different formatting while using Zenhub to write an issue compared to when it's actually created in GitHub.

This screenshot is while I'm writing a new issue via ZenHub. I wrote out each word and hit "return":
![screen shot 2018-08-02 at 1 07 07 pm](https://user-images.githubusercontent.com/11477059/43599479-bb459ebc-9655-11e8-9e05-12cf179b8b1e.png)

But when I click preview, I see each word on the same line:
![screen shot 2018-08-02 at 1 07 14 pm](https://user-images.githubusercontent.com/11477059/43599550-fc7351f4-9655-11e8-9cc6-e286538d6b54.png)

But if I do the same thing directly in GitHub _not_ via Zenhub, I see the words formatted on individual lines:
![screen shot 2018-08-02 at 1 16 14 pm](https://user-images.githubusercontent.com/11477059/43599704-7d8664d4-9656-11e8-8aeb-3b86ef70672e.png)

Obviously this example is pretty trivial. Putting two spaces will give you a new line in some versions of markdown and that worked here. But it does seem like the markdown versions should be aligned long-term if the goal is to make ZenHub seamlessly interact with GitHub.

**Comment by kendramoroz** [comment]
👋 Hey @lia-simeone can you confirm if you're on .com, or Enterprise? We have fixed this bug in .com, so looks like you might be a bit outdated version.

**Comment by lia-simeone** [comment]
@kendramoroz just back from vacation. Oops meant to include that. We're on Enterprise 2.24.6. Has it been fixed there?
