### ISSUE TITLE
Please add 'Projects' on the new issue form.

### ISSUE THREAD

**Issue by Chris-Kim** [ZenHubIO/support#1480]
Github's new issue form has this `Projects` on the right column to set where the issue belongs to.

This is missing from the ZenHub

![image](https://user-images.githubusercontent.com/6469890/43747989-55e9f4da-9a30-11e8-82b3-8dab0b48395e.png)

**Comment by kendramoroz** [comment]
👋 Hey @Chris-Kim At the moment we don't have plans to pull Projects in to the ZenHub experience. We encourage teams to book time with us 1-1 to help with a transition off Projects into ZenHub! We support the same functionality and offer additional insights and reporting teams won't get in Projects and native GitHub UI alone, so let us know if you have any questions that we can help with!
