### ISSUE TITLE
User gets Invalid Date when entering Start Date for Milestones in Zenhub Enterprise

### ISSUE THREAD

**Issue by sshadmand** [ZenHubIO/support#1485]
When using reports, I get an "Invalid Date" error when trying to add a start date. Even when I add variations of the date (e.g. 08/01/2018, 8/5/2018), the system does not accept the input.

![screen shot 2018-08-13 at 1 13 22 pm](https://user-images.githubusercontent.com/68735/44055604-c0e28dc8-9efa-11e8-88d2-eddd55981fc5.png)
![screen shot 2018-08-13 at 1 13 04 pm](https://user-images.githubusercontent.com/68735/44055605-c1799b64-9efa-11e8-8f2d-d47d9b2a263a.png)

**Updated:** (~Zenhub~ Github Enterprise v2.14, Zenhub 2.13.2 Chrome 68.0.3440.106 )

**Comment by sshadmand** [comment]
@kendramoroz thanks for the heads up. Updated incorrect version info in original post. Now reads: Github Enterprise v2.14, Zenhub 2.13.2 Chrome 68.0.3440.106. Your original answer still stands.

**Comment by sshadmand** [comment]
@kendramoroz 

FYI: It sounds like our DevOps has had a lot of trouble getting the upgrade to take, which is why it is so far behind. 😢

**Comment by kendramoroz** [comment]
Oh no! If the team gets in touch with more details of what’s happening we can certainly try help debug to get you upgraded. Let us know how we can help 🚑. The upgrade to 2.24 contains a significant amount of improvements from your current version!
