### ISSUE TITLE
Copy URL should not be the main option

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1487]
It's much more common to want to edit an issue rather than copying the URL, can we please have the Edit option more accessible? It was great to have the pencil there before to get 1 click editing. Now it's two clicks with the menu, but if the Edit option can be placed first on top that will save some time scanning for the option and clicking it.

![image](https://user-images.githubusercontent.com/490562/44375213-75f3b600-a546-11e8-8b58-c900f02b4b50.png)

**Comment by kendramoroz** [comment]
Hey @adamreisnz thanks for submitting! I'd recommend reaching out to support@github.com to let GitHub know about this request. We use the same GitHub UI within the extension once an Issue has been created. We err on the side of modifying GitHub features as little as possible as they are always evolving their design and functionality and we want to partner with their look, not accidentally break it should the override conflict. At this time we have no plans to modify this area of the Issue modal.
