### ISSUE TITLE
Request increasing the char limit in Project Board notes/cards

### ISSUE THREAD

**Issue by ibm-jeff** [ZenHubIO/support#1488]
We tend to put lists in our Project Board notes, and the listed items often have URL references, and together use up a lot of characters.  We frequently run out of room in a note, and need to create follow-on notes on the same topic.  If we could increase the character limit (like at least double), it would be very helpful/handy. Is this a possibility?  Thank you.

**Comment by kendramoroz** [comment]
👋 Hey @nachiketar thanks for sending this in - At the moment we don't have intentions of overriding the permission behaviour of GitHub's native Projects feature as this is separate from ZenHub. I'd recommend you send a note to GitHub's support team to send through a feature request their way (support@github.com)!
