### ISSUE TITLE
Enter key on keyboard should select epic from list

### ISSUE THREAD

**Issue by agaripian** [ZenHubIO/support#1489]
When selecting an epic, the enter key should select the epic for you instead of having to use the mouse to select it. 
![image](https://user-images.githubusercontent.com/3413259/44537054-dc561100-a6cb-11e8-8430-e3592a438c6d.png)

**Comment by kendramoroz** [comment]
Hey @agaripian You'll be happy to know that we have a fix for this coming out shortly! I'll post back once it's in production.

**Comment by agaripian** [comment]
That's great news thank you!

**Comment by kendramoroz** [comment]
👋 This is now live! Using `enter` now selects the Epic :)
