### ISSUE TITLE
Recent activity + news feed

### ISSUE THREAD

**Issue by fprochazka** [ZenHubIO/support#149]
It would be nice, if the recent activity contained also items from news feed in the relevant organization (or it can be even filtered to the repository you're in currently)

![snimek obrazovky porizeny 2014-10-31 11 16 14](https://cloud.githubusercontent.com/assets/158625/4859136/f77ea73c-60e6-11e4-880d-7eec325ea65f.png)

**Comment by kaufmann42** [comment]
+1 obviously a little late on this, but did this ever go through?
