### ISSUE TITLE
ZenHub tab not working when Projects tab is open

### ISSUE THREAD

**Issue by zackgemmell** [ZenHubIO/support#1490]
![aug-23-2018 13-44-56](https://user-images.githubusercontent.com/6632499/44551148-20044700-a6db-11e8-9b17-d06c1ac2396a.gif)

**Comment by mjracca** [comment]
Same when I'm in Code>Releases

**Comment by kurtify** [comment]
I have this issue on Chrome.

**Comment by devinmcinnis** [comment]
We have released a fix for this. It will be in the latest version of the extension. Thanks all.
