### ISSUE TITLE
Zenhub cannot show board with js error

### ISSUE THREAD

**Issue by ericwei0919** [ZenHubIO/support#1491]
When Zenhub tab is clicked, it shows loading, and then empty dashboard is shown. Web console shows js error:

```
TypeError: undefined does not have a method named "toLowerCase"
    at vendor.js:1
    at t (vendor.js:1)
    at vendor.js:1
    at vendor.js:1
    at vendor.js:1
    at Array.sort (native)
    at vendor.js:1
    at vendor.js:1
    at t (vendor.js:1)
    at vendor.js:50
```

**Comment by ericwei0919** [comment]
Maybe it's under maintain. Board is OK now.

**Comment by ypresto** [comment]
Two of our team mates (one is me) reporting this issue. Clearing browser cache does not resolve the issue.

**Comment by ypresto** [comment]
app.zenhub.com is ok.

**Comment by kendramoroz** [comment]
Thanks for reporting! The team here is working on a fix at the moment 😀

**Comment by kendramoroz** [comment]
Everything should be working again! Please let us know otherwise.
