### ISSUE TITLE
Label and Milestone Management

### ISSUE THREAD

**Issue by nachiketar** [ZenHubIO/support#1494]
Any user with write access can modify or delete a Label. There is no way to revert the change.  Write access to these needs to restricted to repository Admin.
Or at least there should be an audit trail on why or who modified these .  In a large teams if some member deletes a label or milestone it can cause lot of issues.

**Comment by kendramoroz** [comment]
👋 Hey @nachiketar thanks for sending this in - At the moment we don't have intentions of overriding the permission behaviour of GitHub's native permissions. As labels and Milestones are native GitHub features, I'd recommend you send a note to GitHub's support team to send through a feature request their way (support@github.com)!
