### ISSUE TITLE
Filtering stops working once I switch to new "Any" option

### ISSUE THREAD

**Issue by bradical** [ZenHubIO/support#1497]
I mentioned this here: https://github.com/ZenHubIO/support/issues/865#issuecomment-417303552 but I I'm seeing an issue where after switching to the Any option, filtering appears to stop working. I originally tried it for labels but once switching to Any, I can't get a basic Milestone filter to work anymore. I tried a cache clear which seemed to help temporarily but  now I'm back to not being able to filter. Switching the mode back to "All" doesn't seem to help either. I'm happy to provide a private demo video of this if you'd like. Thanks!

**Comment by releon02** [comment]
Thankful for the new any / all filtering options, but I'm also having trouble getting milestone filtering to work now.

**Comment by bradical** [comment]
I think I may have partly figured out what's going on and it seems to have to do with the request params. When Milestone filtering wasn't working, I noticed the following:

```
...?milestones=<milestone_name>&filterLogic=any&activeFilters=milestones&repos=<list_of_repos>&showPRs=false
```

specifically `filterLogic=any&activeFilters=milestones`. For some reason this `any` option seems to persist when filtering by a single milestone even after switching back to the All option. Also, it seems like the interpretation of `any` when a single Milestone selected is just wrong.

I was able to get Milestone filtering to work again by forcibly changing `any` to `all` in the request params but the change doesn't stick.

Hope that helps.

**Comment by juriewessels** [comment]
@bradical Thanks a lot for the detailed info! Really appreciate it.

**Comment by bradical** [comment]
Sure @juriewessels your colleague (I think?) asked for a call to show her this in action: https://github.com/ZenHubIO/support/issues/865#issuecomment-417409800. I'm still happy to do this if you need it.

**Comment by juriewessels** [comment]
@bradical can you consistently reproduce this? If you can I would really appreciate it if we could schedule a quick call just to see the bug in action and to get the steps to reproduce from you. Sorry for not making my relation to @kendramoroz and ZenHub clearer earlier.

**Comment by bradical** [comment]
Yes, I'm able to consistently reproduce. Happy to jump on a call today at
your availability. It's causing us some pain so would be happy to try to
get it resolved.

**Comment by mjracca** [comment]
Filtering by milestone is breaking consistently for me as well, which is killing out productivity 😭 

`/issues#boards?milestones=September%203rd%20-%20Canvas%232018-09-03&filterLogic=any&activeFilters=milestones&repos=3388472,57234942,96333050,113491346,7629833,6712910,8758733,87943454&showPRs=false`

The gifs shows that even when filtering by milestone the issues remain the same, not working at all.
![zenhub](https://user-images.githubusercontent.com/3976257/44919718-82c99400-ad14-11e8-972a-ce6bb675725b.gif)

Filtering by `Issues with no milestone` of course don't work as well, but it now shows me all PRs, which I have configured to hide

**Comment by mjracca** [comment]
Ok, so if I manually change `filterLogic=any` to `filterLogic=all` and refresh it starts working 😐 ... i will work as a partial hack I guess

**Comment by juriewessels** [comment]
@mjracca @bradical I think I have figured out how to reproduce the bug. In both your cases you have `showPRs` set to false. In an effort to to save as much of your time as possible, could I ask you to try the steps you described after setting switching the `Pull Request` option in the `Show on Board` settings on? Could you let me know if the bugs you are experiencing persist? 

So sorry for the inconvenience. We are working to get this fixed as soon as possible.

**Comment by bradical** [comment]
Confirmed that turning on PRs fixes the problem with milestone filtering
and with the multiple labels with "ANY" not working as described in the
linked to issue.

**Comment by mjracca** [comment]
Activating PRs make filtering by milestone work **but** filtering by  `Issues with no milestone` is still broken to me (it shows me issues with milestones)

**Comment by juriewessels** [comment]
@bradical @mjracca 🙏 Thanks guys! This gives me enough to work with. Really appreciate your swift response.

**Comment by bradical** [comment]
> ... but filtering by Issues with no milestone is still broken to me (it shows me issues with milestones)

same here.

**Comment by mjracca** [comment]
News? This is deeply hurting productivity.

**Comment by juriewessels** [comment]
@bradical @mjracca The problem should be resolved. Please let me know if you are still experiencing issues.

**Comment by bradical** [comment]
Confirmed! Thank you!

**Comment by robbieaverill** [comment]
Just noticed this was fixed too, thanks team!

**Comment by mjracca** [comment]
✨ thank you so much!

**Comment by juriewessels** [comment]
@bradical @mjracca @robbieaverill Thank so much for feedback. Sorry I broke it to begin with. 😬

**Comment by bradical** [comment]
Ha, no worries. Thanks for being responsive. Always happy to help
troubleshoot.
