### ISSUE TITLE
Reset +1's on commit pushed

### ISSUE THREAD

**Issue by bluong** [ZenHubIO/support#150]
One common workflow we use is to apply +1's onto a pull request and if the author updates the pull request via a push, the +1's are reset to signal a rereview.

**Comment by aupright** [comment]
Hey @bluong, it's looks like it's been quite a while since there's been any new feedback here. Although we can still keep this feature in mind going forward, I'm going to close out this issue for now. Thanks again for the suggestion, and props for still using ZenHub! :v:
