### ISSUE TITLE
Hide Epics but show subtasks

### ISSUE THREAD

**Issue by mjracca** [ZenHubIO/support#1501]
I wish I could hide epic but still show subtasks.

![image](https://user-images.githubusercontent.com/3976257/44930495-dea41500-ad34-11e8-9c9d-81a15aa62bf1.png)

When I'm prioritizing, the Epic issue (more like a smart "folder"/label) gets always in the way and I have to keep moving them to bottom, etc).

I hope that makes sense :)

**Comment by kendramoroz** [comment]
👋 We've launched the ability to hide Epics on the Board! There's a new setting under the `Epic` filter :) 
![screen shot 2018-10-15 at 10 44 49 am](https://user-images.githubusercontent.com/11036230/46968159-6042ce80-d067-11e8-95dc-dced5a0b2f81.png)
