### ISSUE TITLE
Search no longer works when filtered to a milestone in Github

### ISSUE THREAD

**Issue by lacostenycoder** [ZenHubIO/support#1503]
If I filter to a specific milestone, searching for a keyword no longer works.  If I remove the milestone filter (clear filters) search is still broken until I reload page.

What is very weird is I had my teammate try the exact same steps using same version of Chrome and extension and he was unable to reproduce the buggy behavior.

But it works correctly when I use the Zenhub app from app.zenhub.com

UPDATE:  I found that if i add another filter such as "Issues with no Release" and set filters to ALL it works as expected.  But I have no way of setting this to All when I'm just filtered to a milestone and use the search feature.  This is very buggy and I use this all the time.  Please fix ASAP!

**Comment by kbergin** [comment]
Plus one - also seeing this bug!

**Comment by lacostenycoder** [comment]
As a temporary work around I have to also add filter by `Issues with no Release` then chose `Matching ALL filters`.  Then search scope works as expected.  But hopefully this will be fixed so we don't have to use hacks like this.

**Comment by annabelleglass** [comment]
Hi @kbergin @lacostenycoder 👋,

The fix for this issue should be in the latest release (released yesterday afternoon, build 2.37.74 🚀 ). Please try this functionality out with the updated extension and let me know how it goes! If the issue is not yet fixed please let us know here or through support@zenhub.com. 

Cheers,

Annabelle

**Comment by lacostenycoder** [comment]
Thanks for the quick reply. Looks like this is now fixed.
