### ISSUE TITLE
Add pipeline identifiers to closed issues on Burndown Report (update #1468 fix)

### ISSUE THREAD

**Issue by guerrini** [ZenHubIO/support#1518]
@kendramoroz The fix for #1468 removed the pipeline identifiers altogether, which fixed the misleading information, but it also removed very useful information—especially when selecting more than two burn pipelines (a daily use case for us).

Please consider these preferable solutions, remembering that other pipeline indicators were reporting correctly and could have been left alone:

Set the pipeline indicator for closed issues to "Closed."
Remove the pipeline indicator only for Closed issues.
I humbly offer a few implementation options:

The code already knows whether an issue is that special closed state in order to apply the special .zhc-icon zhc-icon--issue-closed-red and .zhc-badge zhc-badge--estimate-closed class names/selectors. Why not leverage that same logic to set the text of .zhc-issues-list-item__pipeline span?

Although a little "hacky," you could use jQuery: $('.zhc-icon--issue-closed-red').closest('.zhc-issues-list-item').find('.zhc-issues-list-item__pipeline').html('<span class="zhc-icon zhc-icon--board-light"></span>Closed').

You could not use CSS as currently coded, since all class names that indicated closed status are cousins of the pipeline indicator; however, you could use CSS to set the text if you add a class name at the .zhc-issues-list-item level. Adding such a class may be worth considering anyway so you can set that state in one element and style lower levels via CSS rather than using more complex code logic, and managing so many specific class names.

Hope that helps, and thanks for your consideration!

**Comment by devinmcinnis** [comment]
Hi @guerrini, apologies for the implementation on this - that was an oversight on my part. It should/will show what you've described in your first suggestion:

> Set the pipeline indicator for closed issues to "Closed."

I will look into this and give you an update within the week - thanks.

**Comment by devinmcinnis** [comment]
I just pushed this to production. It's live on the Webapp and extension (though you may need to manually update your extension to see the changes). Let me know if something is off - thanks.
