### ISSUE TITLE
"Filter Board by Issue Dependencies" does not work

### ISSUE THREAD

**Issue by tdayton** [ZenHubIO/support#1521]
"Filter Board by Issue Dependencies" does not change which issues are displayed. It does add the filtering icon at the top of the board. "Clear Dependencies Filter" removes that filtering icon but does not change which issues are displayed.

But maybe this broken control is irrelevant. Is this control supposed to do the same thing as clicking the "Show all Epic issues" button?

Is is really supposed to show this issue and all its dependencies both ancestors and descendants? Or only its descendants?

**Comment by kendramoroz** [comment]
> "Filter Board by Issue Dependencies" does not change which issues are displayed. It does add the filtering icon at the top of the board. "Clear Dependencies Filter" removes that filtering icon but does not change which issues are displayed.

Thanks for sending this in—Can you provide a screen gif or screen shots of what's not working as expected, as well as whether you are using the extension or web app (and which version if the extension)? This is working on my end, so just want to ensure we're debugging the same things :) 

Clicking this will look the complete chain of blocked Issues. If Issue is blocked A, and A is blocked by B, further B is blocking C and D as well, the Board will filter down to this full chain. You can use the legend and icons to understand what's blocking, blocked, or doing both.

![screen shot 2018-09-26 at 4 27 25 pm](https://user-images.githubusercontent.com/11036230/46114801-13c34c00-c1a9-11e8-9b4d-6621aaf5828d.png)

**Comment by tdayton** [comment]
Oh, sorry, I misunderstood. I mistakenly generalized from the Show All Epic Issues button's behavior. I thought this action would show only the clicked issue and the chain of issues blocking it. But now I realize it shows the chains in both directions--issues that this issue blocks, and issues that are blocking this one.

It would be very useful to be able to choose which of these to show:
1. Only issues blocking this issue.
2. Only issues that this issue blocks.
3. Both of those types.
4. The number of degrees of separation--only the immediate children and only the immediate parents, grandchildren and grandparents, and so on.
