### ISSUE TITLE
Milestone change doesn't apply to all selected issues

### ISSUE THREAD

**Issue by mjracca** [ZenHubIO/support#1524]
This happens to us many times. We select multiple issues and we change their milestone. Frequently only a few issues are assigned to the milestone successfully and other don't, so we have to got one by one.

**Comment by devinmcinnis** [comment]
Thanks for reaching out @mjracca. There is not much we can do here as it is a bug in the GitHub API. We have reached out to them and will update when we can. 

Duplicate of #1520
