### ISSUE TITLE
Add multiple select toggle to Pipeline

### ISSUE THREAD

**Issue by mjracca** [ZenHubIO/support#1525]
I usually use filter to select some features and do something to them. I wish I could just toggle a selection to all the items in that filtered pipeline. One time I had to manually click on 200 issues (literally), and because of this bug https://github.com/ZenHubIO/support/issues/1524, i had to do it multiple times.

**Comment by kendramoroz** [comment]
Hey @mjracca We're actually working on spec'ing this out 🎉 You can follow along in  #1201

**Comment by mjracca** [comment]
@kendramoroz thanks!

Also, select items from pipeline and drag them together to sort them either higher or lower (but not top/bottom) in the same pipeline would be great for easier priorization!! do you have that?
