### ISSUE TITLE
Organization avatar is compacted when using the ZenHub Chrome plugin

### ISSUE THREAD

**Issue by reinhouthooft** [ZenHubIO/support#1526]
Viewing the organization main page (which lists all repos within the organization) shows the organization avatar compacted (horizontally).

**Comment by kendramoroz** [comment]
👋 Hey @reinhouthooft mind sharing a screenshot of what you're experiencing to ensure we're debugging in the same spot?

**Comment by reinhouthooft** [comment]
Here you go!

<img width="554" alt="screen shot 2018-09-28 at 12 09 35 am" src="https://user-images.githubusercontent.com/12446870/46193375-d3e88b80-c2b2-11e8-8893-a0cd9f58527e.png">

**Comment by kendramoroz** [comment]
Thanks for this! The team is working on a fix to get this back to normal :) 🔥

**Comment by devinmcinnis** [comment]
All fixed. You can update to the latest version of the extension via `chrome://extensions` or `about:addons`.
