### ISSUE TITLE
ZenHub Chrome Extension mess up organization page

### ISSUE THREAD

**Issue by kj415j45** [ZenHubIO/support#1527]
ZenHub Extenstion disable:
![image](https://user-images.githubusercontent.com/18349191/46216355-f55c7c80-c371-11e8-99c9-71bfc4d6e1dd.png)

ZenHub Extension enable:
![image](https://user-images.githubusercontent.com/18349191/46216394-0f965a80-c372-11e8-8d05-5c0dd162cd44.png)

I'm not sure what happened

ZenHub Extension: 2.37.87
Chrome: 69.0.3497.100

**Comment by kendramoroz** [comment]
Thanks for reporting! We are working on a fix 🔥

**Comment by devinmcinnis** [comment]
Fixed on the latest version of the extension.

Duplicate of #1526
