### ISSUE TITLE
Adding repository to multiple workspaces

### ISSUE THREAD

**Issue by bsipocz** [ZenHubIO/support#1532]
It seems to be impossible to add the same repository to multiple multi repository workspaces, even when those workspaces belong to different organizations.

My use case would be that some issues from an open source library are related to a project I'm involved in. The workspace then obviously rather project focused, but as I'm also a maintainer of that library, I would like to add it to my personal workspace, too where I'm tracking my maintenance related tasks and assignments.

**Comment by kendramoroz** [comment]
👋 Hey @bsipocz this will be part of phase 3 of workspaces! You can follow along here: https://github.com/ZenHubIO/support/issues/139
