### ISSUE TITLE
Having multiple workspaces using one multi repo board

### ISSUE THREAD

**Issue by andrewkelly83** [ZenHubIO/support#1536]
Before the invention of workspaces, we had created a multi repo board that allowed us to see all the issues from our 130 repos on one board (this is great)

Now with the addition of workspaces, I would like to have two workspaces with both of them containing all of our repos. Reason being is I would like to have one workspace called `Sprint`, where the board only has `sprint backlog`, `blocked`, `in progress`, `ready for testing` and `done`. I would also like to keep our existing workspace that has all of these columns but also has `Triage`, `Icebox`, `Product Backlog`, `Questions` and `Blocked`. 

Having these two workspaces would mean that the dev team could stay in the `Sprint` workspace and not have to see any of the noise of the other columns going on during a sprint. The other workspace would then be used by the product owner etc for tracking progress and also managing the product backlog.

Is this actually possible with workspaces? I know that the simple solution would be to have the dev team just reduce the size of all the pipelines that they don't need to see, but I'd like something a bit better

**Comment by kendramoroz** [comment]
👋 Hey @andrewkelly83 that will absolutely be possible with phase 3 of Workspaces! Phase 3 introduces the ability to have multiple workflows on the same Workspace, as well as have repos belong to multiple Workspaces (or multiple multi-repo Boards). 

We have a detailed release plan with timelines in our roadmap here: https://resources.zenhub.com/H1TPiia-7

Hopefully with Phase 3 we can reduce that count of 130 drastically to speed up performance and better organize projects :).

**Comment by kendramoroz** [comment]
👋 It's been a great journey here in this GitHub Issue! We're going to be sunsetting this repo and moving to a new product feedback portal, [hosted here](https://portal.productboard.com/zenhub) to streamline requests and share our roadmap more openly. 

We encourage everyone interested in this next chapter of Workspaces and ZenHub to vote, add feedback, and join the conversation 🎄! Upwards and onwards to 2019 🚀
