### ISSUE TITLE
Changes to Issues are lost

### ISSUE THREAD

**Issue by likern** [ZenHubIO/support#1542]
When I change Issue text and save it - then, after reload, these changes are **become lost**.

That is **totally unacceptable** because it is a _crucial part of your service_.

**Open Issue**
![screenshot from 2018-10-22 15-03-12](https://user-images.githubusercontent.com/842306/47291338-e3d26180-d60b-11e8-90d1-8775edd957fe.png)
**Reload Issue** and see **changes disappeared** (_Acceptance Criteria_).
![screenshot from 2018-10-22 15-03-39](https://user-images.githubusercontent.com/842306/47291335-e3d26180-d60b-11e8-9a51-ce4ca7551bab.png)
**Reload again and it appears.**
![screenshot from 2018-10-22 15-04-02](https://user-images.githubusercontent.com/842306/47291333-e3d26180-d60b-11e8-8074-cc9442ed891b.png)

**In developer console:**
![screenshot from 2018-10-22 15-09-49](https://user-images.githubusercontent.com/842306/47291529-b803ab80-d60c-11e8-82e4-bd5547737756.png)
![screenshot from 2018-10-22 15-09-31](https://user-images.githubusercontent.com/842306/47291530-b803ab80-d60c-11e8-9bc9-df1efbd78c58.png)
![screenshot from 2018-10-22 15-09-08](https://user-images.githubusercontent.com/842306/47291531-b9cd6f00-d60c-11e8-96ba-6a105c392d32.png)

**Comment by bmunkholm** [comment]
Was this during the github outage? I experienced related hiccups in that period.

**Comment by likern** [comment]
@bmunkholm Yes, that was during github failure. I think we can close issue.
