### ISSUE TITLE
Error when creating new milestone

### ISSUE THREAD

**Issue by spapke** [ZenHubIO/support#1543]
After creating a new milestone in a workspace, the new milestone does not appear in the list of milestones.

Attempting to create a milestone with the same name as the previously attempted milestone results in an error, "There was an error creating the Milestone in <repos>." 

Refreshing the list of Milestones may cause the new Milestone to appear, but the number of repos in which it exists will vary. For instance, on one refresh, the page may say that the Milestone is created in 2/9 repos, then later may say 5/9 repos, or it may not appear at all.

The same issues occur when attempting to create a Milestone on a native Github page while using the ZenHub extension.

**Comment by kendramoroz** [comment]
Hey @spapke this was part of the GitHub outage earlier this week! Everything should be fixed :)
