### ISSUE TITLE
zenhub tab doesn't show project reports (js errors)

### ISSUE THREAD

**Issue by v-andr** [ZenHubIO/support#1547]
Cannot access my zenhub tab after trying to open reports, shows empty page:
![image](https://user-images.githubusercontent.com/22767954/47626596-e7fc0300-db66-11e8-9921-81350c1f0c9f.png)

console has errors:
![image](https://user-images.githubusercontent.com/22767954/47626560-be42dc00-db66-11e8-83b5-2d55555ce325.png)

**Comment by kendramoroz** [comment]
👋 @v-andr thanks for reporting! We identified this is due to setting a burn pipeline, then navigating away, and coming back to reports. We are working on a fix!

**Comment by v-andr** [comment]
thanks, the problem is I cannot reset the zen hub now, I have to access my boards through another repo. any recommendations on how to switch it from reports to board with issues?
