### ISSUE TITLE
Cumulative Flow bug? Table shows same last 4 days no matter which period is selected

### ISSUE THREAD

**Issue by bmunkholm** [ZenHubIO/support#1550]
No matter which period I choose to show with:
![image](https://user-images.githubusercontent.com/1215687/47651274-0cfe6f00-db83-11e8-9578-18e85436129c.png)

I always see a table with the last 4 days here:
![image](https://user-images.githubusercontent.com/1215687/47651178-c4df4c80-db82-11e8-9b65-f49806404031.png)

Is that intentional or a bug?

**Comment by kendramoroz** [comment]
👋 Hey @bmunkholm we're going to be updating this to change as the data changes! It's one of our refinement Issues for the Cumulative Flow :)

**Comment by kendramoroz** [comment]
👋 Hey @bmunkholm - quick update here. We're going to be sunsetting this repo and moving to a new product feedback portal, [hosted here](https://portal.productboard.com/zenhub) to streamline requests and share our roadmap more openly. We have this particular item already documented in our backlog, but if there's anything else you'd like to share with us don't hesitate to drop us a line there!
