### ISSUE TITLE
Bug since trying to add a burn pipeline

### ISSUE THREAD

**Issue by AlEmerich** [ZenHubIO/support#1551]
Hello everyone

**What I did**

Today, I tried to add the column "Done" as a Burn Pipeline but when I did, It was not being saved when I refreshed the web page i.e. the "Closed" is the only burn pipeline.

**Problem occured**

Since then, the "Zenhub" tab in GitHub does not show anything and an error occurs in the console of Chrome:

```
vendor.js:77 TypeError: Cannot read property 'addBurnPipeline' of undefined
    at main.js:1
    at vendor.js:1
    at vendor.js:1
    at Module.e (vendor.js:1)
    at E (main.js:1)
    at v (main.js:1)
    at g (main.js:1)
    at y (main.js:1)
    at t.initReportsSettings (main.js:1)
    at t.value (main.js:1)
main.js:1 Mon Oct 29 2018 14:30:22 GMT+0100 (heure normale d’Europe centrale) "Error in openRepoPage: " TypeError: Cannot read property 'addBurnPipeline' of undefined
    at main.js:1
    at vendor.js:1
    at vendor.js:1
    at Module.e (vendor.js:1)
    at E (main.js:1)
    at v (main.js:1)
    at g (main.js:1)
    at y (main.js:1)
    at t.initReportsSettings (main.js:1)
    at t.value (main.js:1)
```

I am able to acces my board directly from Zenhub website but I still cannot add a burn pipeline. Does anyone already has this issue and has a workaround ?

**Comment by kendramoroz** [comment]
👋 Hey @AlEmerich - Can you try to log out and log back in to ZenHub as well as clear your local storage and let me know if this still persists? 

To clear storage, open up your console and head to `application` --> find the GitHub URL on the side and then click the 🚫 sign (three in the image below). 

![image](https://user-images.githubusercontent.com/11036230/47669694-b5530a00-db68-11e8-95df-840199fc4b1d.png)

**Comment by AlEmerich** [comment]
Hi @kendramoroz, 
perfect, it is working as it should now !
I noticed also that it is totally normal that chosing other column as Burn Pipeline is not persistent, I thought something went wrong with that action.

Thank you !
