### ISSUE TITLE
The new (beta) github feature to "transfer issue to another repo" doesn't work in zenhub

### ISSUE THREAD

**Issue by bmunkholm** [ZenHubIO/support#1555]
I tried the new github feature to transfer an issue between repos. It works better than the zenhub "Move Issue" as it preserves everything (who did what), but it appears to also create a redirect from the old repo to the new. And for Zenhub it doesn't discover this redirect, so it appears the issue is still in the old repo ...

**Comment by aramir** [comment]
+1 - currently have 2 issues stuck in the board (original one, the one there were transferred from), which are closed, yet cannot be removed and just sit in the "New" queue.

**Comment by pblitz** [comment]
+1, same here. I thought the transfer button was the zenhub "move issue" button :(

**Comment by mjasinski5** [comment]
Just faced the same issue, calls are throwing 404 and board is broken.

**Comment by sminnee** [comment]
We’ve got this issue on github.com/SilverStripe/SilverStripe-framework as well. Any eta or info on a fix would be much appreciated!

I’ve we’ve inadvertently used the feature before realising this bug, can data be cleaned up through a support request or something?

**Comment by mori-hisayuki** [comment]
Just faced the same issue.
The deleting function has disappeared from github, but it is not reflected in zenhub.
As a result, the Velocity Report and the Release Report are not displayed as they are being read.

please, need a way to activate the report.

**Comment by lacostenycoder** [comment]
Yes, having the same issue

**Comment by aramir** [comment]
We now have 2 "Issue cards" stuck in a queue (which were previously copied). Their actual issues are closed, but the cards show as "open" and when we try to close them they disappear, but on any page refresh they back here again. How do we get rid of those?

**Comment by kendramoroz** [comment]
Hi all, for anyone experiencing lingering issues, please send a request to support@zenhub.com with the following details for the location where you're experiencing the issue:

GitHub organization name:
Repo name:
Username of **an admin in this repo**: (It's important that it is an **admin** as we cannot help clear the cache without an admin's username. 

I'll be closing this Issue as we have launched a fix for future delete/transfer movements, and any lingering Issue requests will be addressed when sent via support@zenhub.com.
