### ISSUE TITLE
Cumulative flow never showing new pipelines

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#1567]
We've create a new pipeline since the cumulative flow report was released.
This new pipeline never gets ticked by default in the report:

![image](https://user-images.githubusercontent.com/490562/48300404-a2194480-e541-11e8-8007-ddcc29d79cf7.png)

We always have to manually tick it to see it in the report.

So many issues with the cumulative flow report, has it been tested at all prior to release?

**Comment by devinmcinnis** [comment]
Hi Adam, I'm trying to dive into this but I can't seem to reproduce it. Is this still a problem on your end?

Here are the steps I've gone through:
- Create new pipeline from the Board
- Go to Cumulative Flow, see new pipeline checked (correct)
- Uncheck new pipeline
- Open Cumulative Flow in new tab, see new pipeline unchecked (correct)

**Comment by adamreisnz** [comment]
I haven't tried to create a new pipeline anymore, and I think after a refresh the new pipeline was being ticked properly and stayed that way since, so perhaps it's fixed now!
