### ISSUE TITLE
Issues moved between Github repos get stuck in Zenhub forever

### ISSUE THREAD

**Issue by lacostenycoder** [ZenHubIO/support#1579]
We have used the new github move issues feature to move an issue from 1 repo to another.  This functionality on Github's side seems to effectively delete the issues from the original repo completely and auto-forwards all requests from the original issue to the new issue on the target repo.  I have confirmed the same behavior on the frontend as well as via Github's API.  The problem is that the original issues is no longer reachable and permanently stuck in  New Issues pipeline on Zenhub.

![zenhubissue](https://user-images.githubusercontent.com/6077905/49023372-13254280-f165-11e8-8441-4977f0212bb7.gif)

**Comment by vst** [comment]
Looks like it relates to to https://github.com/ZenHubIO/support/issues/1555?

**Comment by kendramoroz** [comment]
This is being addressed through a support email ticket, so I'm closing this!

For anyone experiencing lingering issues like this in the future, please send a request to support@zenhub.com with the following details for the location where you're experiencing the issue:

GitHub organization name:
Repo name:
Username of **an admin in this repo**: (It's important that it is an **admin** as we cannot help clear the cache without an admin's username.
