### ISSUE TITLE
Velocity tracking report: Only showing velocity per repo not workspace of repos

### ISSUE THREAD

**Issue by lfunkhouser** [ZenHubIO/support#1583]
#### Expected behavior
Should see the past, current and future Milestones in the Velocity tracking report for my Workspace, which consists of 12 connected repos

#### Current behavior
Velocity tracking report is only showing one repo at a time instead of all connected repos in a workspace
Milestones for the repo being shown in Velocity tracking report are stacked in a single bar chart rather than individual bars.

![image](https://user-images.githubusercontent.com/3800729/49118971-51049280-f25b-11e8-9dbc-9b979b03394e.png)

##### Additional Information
Milestones were created using the **Create new Milestone** option from the Burndown report to ensure all Milestones in the repos connected in the Workspace were consistently named

#### Environment
This issue occurs both in ZenHub for Chrome and through zenhub.com

**Comment by kendramoroz** [comment]
👋 Hey @lfunkhouser based on the screenshot, I'm seeing the `3 repos` appear next to the first milestone in the list. --> This is how multi-repo Milestones appear. Only when there are estimated issues in the milestone in that repo will it contribute to the Milestone, appearing cross-repo. 

To clarify, is the issue you're experiencing having multiple Milestones stack visibly in the chart, or, that a multi-repo created Milestone isn't appearing on the chart (where it has estimated Issues in that Milestone from the various repos existing)?

**Comment by lfunkhouser** [comment]
Thanks, @kendramoroz
