### ISSUE TITLE
Issue template doesn't set default issue labels

### ISSUE THREAD

**Issue by DHedgecock** [ZenHubIO/support#1587]
I have a Github issue template that includes a default issue label like:

```
---
name: Bug report
about: Project bug report
title: ''
labels: 'Type: Bug'
assignees: ''
---
```

When I create a new issue using the Zenhub dashboard and select the template the default issue label isn't applied.

When I create a new issue in the Github issue workflow the default 'Type: Bug' issue label is applied to the new issue.

Please let me know if additional details are needed.

**Comment by brienpafford** [comment]
I am having the same issue, when specifying labels in the format above in the template

**Comment by kendramoroz** [comment]
Hi everyone, this repo is now sunset! You can add your ideas and requests for feature enhancements here: https://portal.productboard.com/zenhub/tabs/2-under-consideration 🚀
