### ISSUE TITLE
Allow connecting a PR to multiple issues

### ISSUE THREAD

**Issue by olivoil** [ZenHubIO/support#1599]
I feel like this is worth its own issue.

I wasn't able to find it mentioned elsewhere, but let me know if it's a duplicate or there's a more appropriate venue for this feature request.

_Originally posted by @shacharz in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDI3OTg1NDk5Mg==/timeline/issue_comment#issuecomment-279854992_

**Comment by kendramoroz** [comment]
👋 This is a sunset repo. Please submit your ideas via our new product portal: https://portal.productboard.com/zenhub 🚀
