### ISSUE TITLE
Expanded Pipeline View

### ISSUE THREAD

**Issue by chrisbalt** [ZenHubIO/support#163]
As a user of ZenHub pipelines with a large list of issues, I would like the ability to "expand" my view of issues within a given pipeline in order to see, as much as possible, a large number of issues in a single screen _without scrolling down_ – even if it means re-arranging into several columns. This would be immensely helpful in our team's ability to do our issue prioritization.

Currently, when comparing prioritization of an issue at the top of a Pipeline, it is not possible to see more than 7-10 issues (depending on viewport height), while the Pipeline may contain many times more issues than that.

This is one of the biggest pain points in my team's experience with ZenHub thus far.

**Comment by azenMatt** [comment]
Hi @chrisbalt - some good news for you today! We just put this feature live as part of version 2.8.1 - 

![image](https://cloud.githubusercontent.com/assets/7584089/10205593/ee5d6a70-6776-11e5-9bde-3c3b38786834.png)

So you can collapse down the pipelines you don't need to see, and increase those that you need to see more from

Enjoy!
