### ISSUE TITLE
You don't have permissions...

### ISSUE THREAD

**Issue by SoftGrad-HQ** [ZenHubIO/support#166]
I installed zenHub and was trying to create a board. The result you may see at the attached image - I'm getting "You don't have permission..." error message. What am I doing wrong? I'm owner of the relevant organization. I was trying to transfer repository from organization to human account - result was the same.
![zenhub board](https://cloud.githubusercontent.com/assets/9988189/5260414/ead2a088-7a27-11e4-95b2-84ead9347753.jpg)

**Comment by hh** [comment]
I'm having the same issue over at https://github.com/instantinfrastructure/edison-src#boards 
![image](https://cloud.githubusercontent.com/assets/31331/5691638/8ab1f2bc-9886-11e4-8549-7aba1157edf6.png)

**Comment by kendramoroz** [comment]
👋  Kendra here from ZenHub! Closing this Issue as it's quite old, but if anyone is having Issues with permissions please post or get in touch with us at support@zenhub.com.
