### ISSUE TITLE
Modify labels, milestones, and asignee from board view

### ISSUE THREAD

**Issue by cosmiceric** [ZenHubIO/support#169]
It would be great to be able to change labels, milestones, and asignee from board view.

It's really annoying to have to go in to a specific issue to make these changes. Not sure if this is possible due to native GitHub functionality.

![screen shot 2014-12-10 at 9 56 52 am](https://cloud.githubusercontent.com/assets/2242624/5381094/fdbee2de-8052-11e4-9fed-45ead3316aa9.png)

**Comment by p-run** [comment]
+1, related to #199.

**Comment by aupright** [comment]
Hey everyone, a quick update for those following along here!

Earlier today we released our new board re-design featuring 'pop-over' issues directly on the board. This update sets the stage for much of the functionality discussed above (updating labels, milestones, assignee, estimates, etc. from the board view) which we are hoping to roll out in the coming weeks. Thanks again for all of your patience and support here! :beers:
