### ISSUE TITLE
Button to create a PR from Issue

### ISSUE THREAD

**Issue by sebald** [ZenHubIO/support#17]
Would love to have this implemented in ZenHub: https://github.com/steveklabnik/issue2pr

BTW: :heart: ZenHub! :)

**Comment by kendramoroz** [comment]
👋  Doing some clean up of our community Board and we've decided to close out this Issue as we continue to focus on core workflow experiences around Boards and Reports. Keep an eye on our `Priorities` and `In Progress` pipelines for what goodies are coming to your ZenHub experience soon! 🚀
