### ISSUE TITLE
As a PM, I would like the ability to right click on a ticket and "Send to Top"

### ISSUE THREAD

**Issue by rmacasieb** [ZenHubIO/support#170]
When I create a new ticket, the ticket appears at the bottom of the backlog. This is fine, except that it makes it a little annoying when the ticket you're currently creating should be at the very top of the list.

I would like to be bale to right click ( or hit gear icon ), and choose "Send to Top" which would then refresh the list and make the new ticket the one at the very top of the current swimlane.

**Comment by jayzip** [comment]
I think this issue speaks to the pain in maintaining a big backlog within a ZenHub board... This is just one scenario.

**Comment by robinzimmermann** [comment]
We are new to ZenHub and I haven't had to need this yet until we add more issues. But I know from using our current enterprise tool that this capability is used a lot.

Dragging and dropping works fine for moving an issue a short distance. But for large-scale or quick reorganizing – or as @rmacasieb said, moving a new issue to the top – being able to send an issue to the top or to the bottom is a lot more efficient.

I vote for this.

**Comment by prathe** [comment]
+1

**Comment by prathe** [comment]
Maybe a workaround could be to create a "Drag" pipeline as a single-task bucket to take a task from the top of "Backlog", dragging it in "Drag", scrolling down "Backlog" and then dragging it from "Drag" to "Backlog"

**Comment by sgarciac** [comment]
+1

**Comment by jleven** [comment]
+1

**Comment by jleven** [comment]
@aupright we have over a hundred tickets in our backlog. Dragging take a long time, and sometimes so long that the page does what appears to be an autosave and takes the issue out from under me while dragging.

**Comment by azenMatt** [comment]
Hi all, 

This has been released in the latest version of ZenHub :fireworks: 

You can now use the corner of an issue card to select to send to the top or bottom of a pipeline! 

![image](https://cloud.githubusercontent.com/assets/7584089/12524382/874a31ca-c111-11e5-9fcf-659baa3cac42.png)


This current has one small gotcha... it will not work in the first pipeline of a board. We are working on fixing this but wanted to get it live for everyone everywhere else before then!
