### ISSUE TITLE
As a PM, I would like it so that when I assign a ticket, everyone with ZenHub open automatically gets the assignment update

### ISSUE THREAD

**Issue by rmacasieb** [ZenHubIO/support#171]
Right now, when I create a ticket or move it through the board, anyone who has the board open also sees the ticket modification, without having to do a refresh.

For some reason, when I assign someone to a ticket, this "live" functionality doesn't occur. You have to reload the page to see the update(s)

**Comment by robinzimmermann** [comment]
It is a bit odd to make a change in a ticket and switch back to the board (usually in another browser tab) and not see the change you just made reflected there. Or to see someone else with the board open not see the change without refreshing.

The enterprise tool that we currently use does this, so it's noticeable as we evaluate ZenHub: functionality one is used to stands out when it's suddenly gone. :)

The world we live in today demands real-time updates and live status. I think any modern tool should be adopting an "everything real-time all the time" mentality. 

Moreover, ZenHub integrates with GitHub which does do this. For example, if I fix an issue in one browser tab, and it's open somewhere else, the status is automatically updated very quickly.

I vote for this feature.

**Comment by azenMatt** [comment]
> It is a bit odd to make a change in a ticket and switch back to the board (usually in another browser tab) and not see the change you just made reflected there. Or to see someone else with the board open not see the change without refreshing.

Agreed Robin, We have lots of functionality we want to introduce to the board view to make it a much better experience for the user, with this being an important one of them. Watch this space!

**Comment by azenMatt** [comment]
This should now be working for everyone. 

Please let me know if you see any further issues
