### ISSUE TITLE
As a Team, different members need different Pipeline "Perspectives" (groupings), to help increase focus

### ISSUE THREAD

**Issue by RickCogley** [ZenHubIO/support#174]
One way in which pipeline hiding, expanding or collapsing (referenced in #122 #130 #163) could be handled is to implement some kind of pipeline "perspectives" mechanism. 

Pipelines could be grouped into perspectives, like "All Pipelines" the default, and custom ones that are created by users, perhaps "My Pipelines" for that user, or ones an admin sets up like "Dev Team" or "Test Team" and so on. 

It would be trivial for the user to select these perspectives from a dropdown at the top of the board view, to switch between the groupings.

**Comment by sweetrocker22** [comment]
:+1:

**Comment by azenMatt** [comment]
@RickCogley - the ability to collapse and expand pipelines is now live on version 2.8.1 

I will keep you updated on pipeline groupings, but hopefully this should be a useful first step for you!

**Comment by kendramoroz** [comment]
Closing in favor of #689 — please 👍 /comment to stay in the loop!
