### ISSUE TITLE
As a Flowdock user, I want the option to get pinged about tracking events from github, not just pushes or new issues.

### ISSUE THREAD

**Issue by RickCogley** [ZenHubIO/support#175]
I linked my flowdock chat up to a github repo, to check what will happen on various events in the Github UI. What I observed - 
- Commits and Issue adds or comments trigger the push to flowdock, but other tracking actions like changing tags, assignee, or milestone do not. 
- Flowdock (and Hipchat for sure, not sure about Slack) makes use of any appended hashtags in search. It might conflict with the purpose of certain hash-tag-like constructs in Github world, like linking to an issue number. 
- Although github displays tracking/workflow events nicely in the per-issue log, these do not include pipeline changes. None of these "minor" events are sent to the flowdock API anyway. 

A safe place to inject information would be either the detailed description of a commit, or, any issue message. As in the attached screenshot, a great value add for zenhub would be to allow users to build a kind of injection template, which is appended when certain tracking events happen. 

It could be realized in the style of IFTTT triggers, where, we can select text and variables to be injected. 

```
Repo: %zh-reponame%
Tags: %zh-tags%
Milestone: %zh-milestone%
Assignee: %zh-assignee%
```
- Markdown is ubiquitous in github, and so sometimes gets in the way when variablizing, for example, if the repo name were `this_and_that` the md processor tries to parse the and as italics. 

--Rick

![zenhub 2014-12-23_16-44-51](https://cloud.githubusercontent.com/assets/512328/5535524/e019b990-8ac3-11e4-86eb-2494018eb73b.png)

**Comment by aupright** [comment]
Hey @RickCogley - some more great feedback here!

We're hoping to push out a few robust integrations for notifications in 2015 so I definitely appreciate your suggestions around this topic! Although we're still discussing things at a pretty high level, this is definitely something that I can take back to our engineering team as we move forward with our conversations. Even though there are some similar threads around notifications and a public ZenHub API, I'll keep this issue open in our backlog so that we can continue to get some feedback around it.

**Comment by RickCogley** [comment]
Thanks @aupright. By the way, I explored Github Flavored Markdown by writing a cheatsheet/syntax guide about it (https://github.com/RickCogley/Github-Markdown-Reference). I learned that GFM supposedly ignores underbars in strings, because of their common presence in the source code it's used to parse. My last point is probably not correct, therefore. I also learned that GFM's implementation differs a little from how Github is presenting the rules in their documentation. FYI.

**Comment by techpeace** [comment]
:+1: I'm also a Flowdock user, so an official integration would make me more likely to choose ZenHub. Thanks!

**Comment by kendramoroz** [comment]
👋 Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
