### ISSUE TITLE
As a user of a zenhub board, I want to be able to remove a low priority issue from the board, so that it helps me focus on high priority issues

### ISSUE THREAD

**Issue by andersr** [ZenHubIO/support#181]
We have tons of issues in our repo.  However, we don't want all of them to appear on our zenhub board (eg issue slotted for a future release) 
However, there does not seem to be a way to remove an issue from a board once added, except for by closing the issue, which we do not want to do.

**Comment by aupright** [comment]
Hey @andersr - one of the things thats really helped us manage all of our open issues is to filter our boards by milestone. Although this doesn't physically remove the issue from the board, it helps to keep us focused by getting rid of the issues that aren't relevant for what we're working on. 

It would be interesting to explore your idea in further detail though - I'll move this issue to our discussion pipeline to see if we can get some more feedback! Is hiding issues from the board something that other people would find valuable as well? If so, please show your support and +1!

**Comment by andersr** [comment]
Hi @aupright  - filtering by milestone may be a better solution.  On that note, it would be great for that filter to persist. Pls see #182

**Comment by treygriffith** [comment]
I would use a feature like this to filter out Pull Requests. Most of the time, PR's aren't really something that we track on the board, so being able to filter them out, or hide them entirely would be great.

**Comment by aupright** [comment]
Hey @andersr, it looks like it's been a while since we've last had any feedback on this one. Although we'll still keep this in mind as something to explore going forward, I'm going to close this one out for now. 

Thanks again for the suggestion :beers:
