### ISSUE TITLE
As a user of a zenhub board, I want filtering state to persist across sessions, so that I do not have to apply the same filter repeatedly

### ISSUE THREAD

**Issue by andersr** [ZenHubIO/support#182]
I would like the filter settings to be those of my most recent view of the board, including across sessions.

When working in a sprint, we are usually filtering our issues based on the features for that sprint.  Additionally, we are also featuring our issues for the next milestone/release. Currently, we need to re-apply those filters each time we open the board.

**Comment by aupright** [comment]
Hey @andersr - thanks for issuing this one up as well!

This topic has come up in discussion before - it was actually a feature that we used to offer before we made the switch to using URL parameters to allow users to bookmark  boards. As there is already a thread around this, I'm going to close this issue and move the discussion over to #87 - feel free to +1 and show your support there :)

**Comment by andersr** [comment]
Thanks!  Just +1'd the other issue.


-Anders
*______________________________________*

Anders Ramsay Consulting LLC
540 President St. 3rd floor
Brooklyn, NY 11215
917-742-6085
