### ISSUE TITLE
Hide/Collapse pipelines

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#184]
I would like is the ability to hide or collapse pipelines. Something similar to the Labels dropdown would work in letting us toggle the view. Then, I could hide pipelines that I am not currently working with, mostly because I don't like scrolling left & right.

Another option would be to collapse empty pipelines, like when filtering labels. An empty pipeline could collapse to some minimum width like 50px, which should be just enough space to drop an issue into it.

**Comment by Mottie** [comment]
Hmm, I think this a duplicate of #122.

Anyway, this is what I am envisioning (with ideas from #174)

![2015-01-18 16_00_19-](https://cloud.githubusercontent.com/assets/136959/5794259/cb0a4c3c-9f2b-11e4-9ce5-7d003f6b07a2.png)

**Comment by aupright** [comment]
Hey @Mottie - there are a few other open issues, but it's always great to get fresh feedback! 

As was mentioned in the other threads, collapsing and expanding pipelines is something that the team is actively working on. So far however, most of our designs have involved controlling the width of the pipeline directly from the pipeline itself. I think it would be interesting to explore the idea of toggling the pipelines from a drop down menu similar to the image that you shared above.

I'm going to close this issue for now, but I'll definitely bring your suggestion back to our product team. 

Thanks again for sharing!
