### ISSUE TITLE
Margin shift with browser resize

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#185]
While resizing my browser window in Chrome (not tested in other browsers), the entire ZenHub Boards page shifts to the right and is partially offscreen.

[Screenr](https://www.screenr.com/WluN)

**Comment by aupright** [comment]
Hey @Mottie - I'll have our engineering team look into this further! 

In your screen cast it looks like you are using some customized styling for GitHub. Could you let us know what extension you are using (or what custom CSS you are using) so that we can better diagnose?

**Comment by Mottie** [comment]
I am using the [Stylish Chrome extension](https://chrome.google.com/extensions/detail/fjnbnpbmkenffdnngjfgmeleoegfcffe) with the [GitHub-Dark style](https://userstyles.org/styles/37035/github-dark).

The shift happens with and without the style applied.

**Comment by Mottie** [comment]
It's adding a `margin-left` to the `.container` div:

![2015-01-20 18_43_12-boards zenhubio_support](https://cloud.githubusercontent.com/assets/136959/5829209/50cf1aa6-a0d4-11e4-89d5-f9956d72c127.png)

**Comment by aupright** [comment]
Thanks for the screenshots @Mottie - we'll look into this further and have an answer for you as soon as we can!

**Comment by Mottie** [comment]
Actually, nevermind... I just figured it out.

The problem is the [Octotree Chrome extension](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc?hl=en-US). It adds a slide in repository file list from the left side. I'll report it over there.

Sorry about that!
Rob
