### ISSUE TITLE
ZenHub Extensions

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#186]
I would like to request the ability to add extensions to ZenHub (mostly because I don't want to make a bunch of bookmarklets).

Doing so would allow users to add further customizations, such as code to toggle labels (see #183) or to make a pipeline resizable.

One idea for implementation would be to have a user paste in a URL pointing to a gist or even a repository (a `package.json` file may be needed in this case) with the code.

**Comment by aupright** [comment]
Hey @Mottie - great suggestion!

You might be interested to know that we are actually working on a public API for ZenHub that will allow users to customize their experience even more (see #172). I've heard from a few users that would prefer not to have to build out different bookmarklets, so it's definitely on our radar to try and improve. 

I'm going to move this issue into our 'discussion' pipeline to see if we can get some more feedback around it from the rest of the community. If you would like, you can also head over to the issue that I've created around our Public API and show your support there!

**Comment by Mottie** [comment]
I've been thinking about this idea... maybe you can emulate how [Stylish](https://github.com/JasonBarnabe/stylish-chrome) adds an extension option page with an editor that allows adding custom css. Of course, this idea would need javascript and maybe css.

The author of stylish has a website (https://userstyles.org/) for people to browse, obtain and submit styles.
