### ISSUE TITLE
Support for Chromium

### ISSUE THREAD

**Issue by p-run** [ZenHubIO/support#191]
I am getting this message when trying to install zenhub:

An error has occurred
Could not install package: 'UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL'. Could not install package because a utility process crashed. Try restarting chrome and trying again.

<pre>
% chromium --version
Chromium 40.0.2214.91 Built on 8.0, running on Debian 8.0
</pre>

**Comment by gliurun** [comment]
+1

**Comment by azenMatt** [comment]
Hi @p-run, 

Thanks for bringing this issue to our attention. At the moment we are only supporting Chrome. But to see if we could re-create this we fired up the latest build of Chromium - 42.0.2296.0 on Mac OS X and it worked fine. 

It might be worth trying to install ZenHub again if a newer version of Chromium is available for Debian?

**Comment by p-run** [comment]
Supporting chrome only is understandable, but do you think you can provide an error message that describes what the issue is so that I can attempt to troubleshoot it?

**Comment by kendramoroz** [comment]
👋 Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports. Teams looking to use ZenHub outside of Chrome/Firefox can always use [the web app experience which was launched back in July!](https://app.zenhub.com) 

Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
