### ISSUE TITLE
Invisible file upload blocking space on diff comments

### ISSUE THREAD

**Issue by ajwhite** [ZenHubIO/support#193]
When commenting on PR diffs, you can see that there's space taken up by the file uploader but there's not actually a file uploader. For example, on this issue description you can see the space allocated for the actual file upload button, but when commenting on line diffs on a PR, that space is taken up with no button.

![screen shot 2015-02-10 at 12 42 44 pm](https://cloud.githubusercontent.com/assets/656630/6132727/8f3f67d8-b122-11e4-87e1-a9f6a0f99323.png)

VS

![screen shot 2015-02-10 at 12 44 23 pm](https://cloud.githubusercontent.com/assets/656630/6132730/92cabf74-b122-11e4-8652-f871e210c4d2.png)

Obviously a very small issue, just sometimes [/r/mildlyinfuriating](http://www.reddit.com/r/mildlyinfuriating/top/?sort=top&t=all)

**Comment by aupright** [comment]
Hey @ajwhite thanks for reaching out!

Looks like there are quite a few votes for a fix here. I've issued this up internally so that we can take a look at it in more detail and hopefully put together a quick fix. Thanks again for the feedback!

**Comment by p-run** [comment]
+1, if there is no uploader the space should not be taken up.

**Comment by ccpmark** [comment]
@aupright any updates on this?

I've noticed the same behavior when creating a pull request. It would be great to have the entire text box width when the button is not available, it takes up quite a lot of room!

**Comment by aupright** [comment]
Hey @ccpmark, thanks for the follow up!

Although there are still a few high priority items we're looking to finish up in our current roadmap, we are still planning to circle back on this one. As soon as we push out a fix I'll make sure to ping everyone here with an update!

**Comment by ajwhite** [comment]
@aupright please, my sanity. I need it back!

**Comment by azenMatt** [comment]
@ajwhite - please enjoy the return of your sanity :smile: 

![image](https://cloud.githubusercontent.com/assets/7584089/8194673/036ea318-1432-11e5-8432-617ce2edb907.png)

**Comment by ajwhite** [comment]
Thanks @azenMatt and team! :clap: :clap: :clap:

**Comment by ccpmark** [comment]
Thanks @aupright, really appreciate it!

**Comment by Rican7** [comment]
Woot!!! Thank you!!! :+1: :clap:
