### ISSUE TITLE
Dismissing tutorials with keyboard

### ISSUE THREAD

**Issue by p-run** [ZenHubIO/support#195]
As a new user I am shown various help prompts. These prompts are not dismissable via keyboard.

Example: the glowing dot next to repository name.

When these tutorials are rendered (e.g., after clicking on a glowing dot), keyboard shortcuts for e.g. bringing up zenhub board and dismissing the board (escape) work, but escape dismisses the board under the tutorial with tutorial remaining visible.

Escape should dismiss tutorials first, then zenhub board.

**Comment by azenMatt** [comment]
I am going to close this one in favour of #196 - we will take care of these at the same time :)
