### ISSUE TITLE
Viewing tutorials with keyboard

### ISSUE THREAD

**Issue by p-run** [ZenHubIO/support#196]
As a new user I am shown several tutorial prompts with glowing dots. These glowing dots are very bright and animated and, hence, distracting. I need to go through the tutorials to regain the ability to work in github in peace.

There is, however, no way to efficiently go through all tutorials. I must individually navigate to each glowing dot, click it, then dismiss each tutorial with the mouse (#195). This is cumbersome.

Instead I would like to, say, press "h" key and go through each tutorial in sequence, dismissing them with escape, or perhaps left/right arrows.

**Comment by azenMatt** [comment]
Thank you for the feedback @p-run 

You are actually one of our first users to go through the new on-boarding process as we have only just released it - so these are really useful thoughts for the team to improve it. 

To give you some more context around this process - we were receiving a lot of user feedback that first experiences with the application could be confusing as we left the user to find all the feature inside GitHub themselves. So this is what we were aiming to solve with the new process. 

I will take a look at how we can make this process less intrusive and easier to exit

**Comment by p-run** [comment]
Thanks, that is a good point regarding discovering what features are available. Looking forward to what you come up with.
