### ISSUE TITLE
Unclickable gap in issue name link

### ISSUE THREAD

**Issue by alexchantastic** [ZenHubIO/support#200]
There is a small gap within the issue name link that is not clickable to navigate to the issue (denoted by the red box):

![image](https://cloud.githubusercontent.com/assets/604167/6263093/11f6a4a8-b7c6-11e4-984c-403607a7c187.png)

This is due to the `line-height` of the item. This is easily fixable by adding `display: block` to the `<a>` element. I believe the selector would be `.zh-pipeline-issue-title a`.

**Comment by p-run** [comment]
+1

**Comment by azenMatt** [comment]
Well spotted @alexchantastic - we will have this one fixed shortly at the same time as #194

**Comment by geoffrey** [comment]
Hey @alexchantastic, we just released ZenHub version `1.2.12`.

Now the entire issue card is clickable and will open a new tab for that issue.
Please update your extension and let us know what you think about it.

**Comment by alexchantastic** [comment]
@geoffrey perfect :+1:

**Comment by azenMatt** [comment]
@alexchantastic - we had to roll this one back briefly due to a performance issue. We are doing a quick fix and it will be live again very soon
