### ISSUE TITLE
View all issues for a milestone concurrently

### ISSUE THREAD

**Issue by p-run** [ZenHubIO/support#201]
As a product manager, in order to prioritize issues for an upcoming milestone I want to see all issues in said milestone at the same time.

Currently the backlog shows about 4-7 issues at a time depending on how many labels an issue has and how detailed its title is. In a milestone with 50 issues which is about normal for us this means there are 7-12 pages of backlog. It is impossible to prioritize issues while they are spread over 7, much less 12, pages.

**Comment by azenMatt** [comment]
Hi @p-run we are going to have a new feature for issue #163 live shortly which will help you here - as you will be able to expand your backlog pipeline to a larger width to see more issues onscreen at once. 

I am going to close this issue and keep #163 open for updates on this - should be very soon!
