### ISSUE TITLE
Ability to hide file uploader

### ISSUE THREAD

**Issue by aupright** [ZenHubIO/support#202]
A few users have reached out to us requesting the ability to hide the file uploader feature providing more horizontal space when typing out large comments. Is this a function that other people from the community would find helpful as well? ie. the ability to toggle on/off the file uploader.

If so, feel free to +1 and add your comments below!

**Comment by alexchantastic** [comment]
Maybe rather than hiding it. You could attach it to the bottom of the textarea like this:

![image](https://cloud.githubusercontent.com/assets/604167/6341271/b712ce20-bb7d-11e4-81f8-6e098ce135cf.png)

**Comment by p-run** [comment]
+1 to hide

**Comment by laughedelic** [comment]
+1

**Comment by azenMatt** [comment]
And it's gone :smile: 

in favour of the GitHub uploader
