### ISSUE TITLE
The drag order is broken

### ISSUE THREAD

**Issue by jperl** [ZenHubIO/support#203]
I confirmed this on two different computers / accounts.

![cannotdrag](https://cloud.githubusercontent.com/assets/1136652/6375486/65acf614-bce5-11e4-8200-6acb92997f81.gif)

**Comment by azenMatt** [comment]
well spotted @jperl - we just pushed a fix for this, can you check if you still have the problem on v1.2.1? 

(you can force chrome to update the extensions on the extension tab here:
![image](https://cloud.githubusercontent.com/assets/7584089/6381265/a268849c-bcf4-11e4-9771-ed40d088e50c.png)

)

**Comment by jperl** [comment]
Still not working. I verified I am on v1.2.1 and restarted chrome.

**Comment by jperl** [comment]
I inspected the websocket messages -- the transferIssue seems to have the right index, but the response has 14 issues in it for the pipeline, but the board only shows 10.

**Comment by azenMatt** [comment]
hmmm, ok - let me dig further into this one and I will get back to you!

**Comment by azenMatt** [comment]
@jperl - just a quick update on this, we have been able to replicate this issue - so we should have a fix for you soon!

**Comment by azenMatt** [comment]
@jperl - the fix for this just :ship: 'd

If you can try it on 1.2.6 - the issue should be resolved. 

please re-open the issue if you have any problems :grinning:

**Comment by jperl** [comment]
Thanks, it works.
