### ISSUE TITLE
Add integration with slack

### ISSUE THREAD

**Issue by lavluda** [ZenHubIO/support#204]
We are using zenhub and slack. will love to see these 2 integrated. so, i can see what happening in zenhub board directly from slack .

**Comment by jperl** [comment]
@lavluda We just started working on a pretty cool github and slack integration. https://github.com/DispatchMe/meteor-slack-releases It does not work yet, but we would love any help.

**Comment by azenMatt** [comment]
Hi @lavluda - Slack integration is on our roadmap :smile: 

We have issue #119 open to track this, so I am going to close this one to keep the updates to one thread.
