### ISSUE TITLE
Boards Won't Open

### ISSUE THREAD

**Issue by shawnaten** [ZenHubIO/support#208]
Just started with ZenHub and I can't get boards to work.

![screen shot 2015-03-19 at 1 33 57 pm](https://cloud.githubusercontent.com/assets/6790347/6737916/ad978eae-ce3c-11e4-824e-a18da6afc22e.png)

**Comment by geoffrey** [comment]
Sorry about that @shawnaten, we just released a fix that should solve this error. 
Could you please try again and close this issue if the bug does no longer exists :) ?

**Comment by shawnaten** [comment]
Works now. Thanks!

![screen shot 2015-03-19 at 1 55 09 pm](https://cloud.githubusercontent.com/assets/6790347/6738373/af2f8232-ce3f-11e4-91c8-ce9e2cc74596.png)
