### ISSUE TITLE
Style for already voted on issues

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#209]
It would be nice to have a style applied to cards so I can tell I've already voted on the  a comment in the issue. Even something as simple as a green border would suffice.

I hadn't visited the boards in this repository for a few weeks and now I find myself opening issues of interest to discover that I had already voted on them.

Thanks

**Comment by aupright** [comment]
Hi @Mottie thanks for the suggestion here!

We're looking to incorporate more style elements from our upcoming rebrand into the boards/issue views - I think this could make for an interesting idea to explore. I'm moving this into the discussion column to see if we can generate some more feedback! :beers:

**Comment by smiller171** [comment]
:+1:
