### ISSUE TITLE
Button Elements & Styling

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#210]
GitHub changed all of their buttons yesterday, so now various buttons need to be fixed. 

* Export issue (issue pages)
* Labels, Milestones & Assignee (board pages)
* The "View closed issues" checkbox needs a `vertical-align: middle;` (board pages; that's my OCD talking)

**Comment by azenMatt** [comment]
Thanks @Mottie - we are on it :grinning:

**Comment by azenMatt** [comment]
@Mottie v1.2.12 has a fix for this, Chrome should be updating this for you any moment now....
