### ISSUE TITLE
Fallback Website

### ISSUE THREAD

**Issue by jbenet** [ZenHubIO/support#212]
I really like how nice ZenHub integrates with github. 

We have a problem though-- we're a very security-conscious group. We work with cryptographers and security experts. For many, installing an extension or authorizing an application that gets full R/W to all of github.com is simply out of the question. Some of us can, but it would be ideal to be able to collaborate with those users through a "fallback" website. Something like waffle.io. I very much understand you went for a different start, but i think this would give a complete solution.

Thanks!

**Comment by azenMatt** [comment]
thanks for the feedback @jbenet 

I understand your use case here and we will take this onboard with future product decisions - at the moment our focus is on providing a solution that reduces the overhead of context switching by existing inside GitHub. But I can certainly see us offering a separate view for teams where this is not as high of a priority. In terms of authorizing applications - we do have a comprehensive privacy policy here - https://www.zenhub.io/privacy - please let me know if I can offer you any other information that will help with your teams confidence level!

**Comment by jbenet** [comment]
@azenMatt 
> at the moment our focus is on

Well understood. :+1: keep making a great product. too bad it can't work out for us atm, but keep up the good work! the design is beautiful and it works very well.

> But I can certainly see us offering a separate view for teams where this is not as high of a priority.

Great! If you'd like a test project for this, tag me if this ends up happening.

> In terms of authorizing applications - we do have a comprehensive privacy policy here - https://www.zenhub.io/privacy

This feedback may be useless, but i'll leave it here anyway, take it as well-meaning comments from the security-conscious in aims to get better. :smile:  

How _ZenHub_ uses the information is not important. From an INFOSEC standpoint, authorizing R/W access to _all_ repos to _all_ these sorts of integrations (not just ZenHub) is a security nightmare. It's a terribly weak chain where compromising the websites of the weakest of these integrations grants the attacker full access to _all_ of the user's repositories. Most of the fault here lies on github, as their OAuth policies are totally coarse and do not allow granular (per repo) access. (To be fair, it _is_ a UX nightmare to do this right. However, between a security and a UX nightmare, ...) In any case, integrations (like ZenHub) can do two things:
1. ask github to make more coarse oauth permissions
2. implement roundabout ways for granting access (like per-repo webhooks, or implementing per-repo ACLs for the security conscious).

**Comment by azenMatt** [comment]
Thanks for the kind words! and for the well-meaning feedback - 

Trust me, we (along with every other GH API dev team!) are following up with GitHub for more coarse oauth permissions :smile: 

I will take a look into your second idea and see what we can do - i'l keep you updated if/when we have updates.
