### ISSUE TITLE
Can't open boards

### ISSUE THREAD

**Issue by blunderdome** [ZenHubIO/support#214]
![screen shot 2015-03-31 at 1 00 28 pm](https://cloud.githubusercontent.com/assets/4333625/6924346/f31f88e2-d7a5-11e4-8dc6-a432b9900fae.png)

It gets this far and then freezes forever. Happens in every repo I try to open the boards for.

**Comment by geoffrey** [comment]
Hi @blunderdome 

We are trying to investigate this issue and would love your help to make sure we are going to the right direction.

Could you please run this little javascript snippet in your console on any GitHub page and give me the result you got from it.

```
var user_id_from_img = parseInt($('#user-links a:eq(0)').find('img[data-user]').data('user'), 10);
var user_id_from_meta = +$('meta[name=octolytics-actor-id]').attr('content');
console.log('img', user_id_from_img, 'meta', user_id_from_meta);
```

You don't have to copy the exact ids you get from the result here though, we just need to make sure both values are defined.

Thanks for your help!

**Comment by blunderdome** [comment]
I'm not a developer (we use Github/Zenhub for issue tracking for nontechnical folk as well), so not sure if I did this right. Is this what you want?

![screen shot 2015-03-31 at 2 25 31 pm](https://cloud.githubusercontent.com/assets/4333625/6926076/f2257788-d7b1-11e4-9eb3-4261b3558267.png)

**Comment by geoffrey** [comment]
Thanks, that helped us a lot :) 
We are working on a fix right now, you can expect an extension update in an hour max.

**Comment by geoffrey** [comment]
@blunderdome we just release ZenHub `1.2.14`

could you please give it a shot by manually upgrading your extensions in `chrome://extensions` and let us know if it has fixed your issue (you need to check `Developer mode` option to see a `Update extensions now` button)

**Comment by blunderdome** [comment]
It works! Thanks guys.
