### ISSUE TITLE
Viewing boards hangs indefinitely

### ISSUE THREAD

**Issue by heytrav** [ZenHubIO/support#215]
I'm trying ZenHub for the first time and created a few issues in one of my [projects](https://github.com/heytrav/ParseUtil-Domain). Whenever I try to look at the *Boards* view, the page just hangs indefinitely with the message 

>*We are loading your issues...
#SuperCharge your GitHub workflow with Zenhub!*

After waiting several minutes on a few occasions, I only get out of this by clicking on the breadcrumbs above to go back to the main repository page.

I am using Chrome Version 41.0.2272.104 (64-bit) on Mac OSX (Yosemite)

**Comment by azenMatt** [comment]
Hi @heytrav 

Is this the same issue as #214? if so please update to 1.2.14 and that will fix it for you! 

If not, please let me know and we will investigate further!

**Comment by heytrav** [comment]
@azenMatt yep that looks like it indeed fixed it. Thanks a lot!
