### ISSUE TITLE
Recent Activities doesn't show activity from the current repository

### ISSUE THREAD

**Issue by minton** [ZenHubIO/support#216]
This issue has started only recently. When viewing a repository issues, I click the ZenHub Chrome Extension and see a drop down showing *Recent Activities*. However, the stuff listed is for a different repository than what I'm currently viewing.

**Comment by azenMatt** [comment]
Hi @minton 

Apologies for the late response on this one, the extension notification centre shows updates from across all organizations you are  a member of, so it does not take into consideration what the current repo you are looking at is. 

I agree that this is not ideal and there is much we can do to make this button more valuable to the current situations content. 

Improvements for this are in the pipeline :smile:
