### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by shahmirj** [ZenHubIO/support#217]
We had icons for pull-request and links next to each board, this seems to have disappeared?

**Comment by azenMatt** [comment]
Hi @shahmirj - would you be able to post a screen shot to confirm the area that has disappeared and we will investigate? Thanks!

**Comment by shahmirj** [comment]
![screen shot 2015-04-21 at 15 38 05](https://cloud.githubusercontent.com/assets/313498/7254700/a235212e-e83c-11e4-94d7-e11c99ce9b29.png)

#46 is a pull request and it has no icon

**Comment by azenMatt** [comment]
Well spotted @shahmirj - these should now be back on your boards! 

Please re-open if you have any further issues with this,
