### ISSUE TITLE
Milestone filter on board stopped working

### ISSUE THREAD

**Issue by jeffsuarez** [ZenHubIO/support#220]
We are no longer able to filter issues by milestone on our board even though the issues have milestones properly set. When we choose a milestone, no issues are shown.

**Comment by azenMatt** [comment]
Hi @jeffsuarez - would you be able to let me know which version of the extension are you on? 

Also, do you have any errors in the developer console when you select a milestone (View -> Developer -> Developer tools) if so, can you provide a screenshot?

**Comment by jeffsuarez** [comment]
It looks like I am on version 2.0.2 of the extension. 

I do not see any errors in the developer console when I select a milestone.

The other interesting thing that I noticed is that some of my milestones are select-able (and filter properly), but some aren't. When I select one of the ones that is not working, I also don't see the option for "Clear milestone filter" in the milestone drop-down list. It just doesn't seem to be properly selected.

**Comment by azenMatt** [comment]
We pushed out an update on the backend that has solved some minor issues on the board. 

I have not been able to replicate this one since - would you be able to confirm that this is working for you now?

Please re-open the issue if you are still having issues!

**Comment by jeffsuarez** [comment]
I don't seem to be able to re-open the issue. But it is still happening for us. I think it may be related to the fact that our milestone names have double quotes in them. I am going to update the names and see if it resolves the issue.

**Comment by azenMatt** [comment]
Nice debugging @jeffsuarez - I can replicate this if I include double quotes in milestone names! 

We will get a fix out for this soon. 

-----------

As a brief aside, when changing milestone names, you may have to wait a short while for this to reflect on the board. This is because the GitHub API does not count milestone name changes as a 'change' when we query the API for any changes. So we only get them when we ask for a fresh copy.

**Comment by azenMatt** [comment]
Hi @jeffsuarez this is now fixed in extension version 2.1.8 :beers: 

Any further problems, let me know!

**Comment by jeffsuarez** [comment]
Awesome, thanks @azenMatt ! 

Also, I am loving the new story points and turndown chart!
