### ISSUE TITLE
Selected/unselected tags not immediately reflected on board

### ISSUE THREAD

**Issue by abbyad** [ZenHubIO/support#221]
After changing the tag on an issue the old tag still shows for at least 10 minutes, which means it doesn't respect the filter as you can see here: 
![image](https://cloud.githubusercontent.com/assets/789512/7422101/ff6518be-ef57-11e4-9748-e3f8472b4cc9.png)

A refresh was needed to eventually get the tags to be updated, but even refreshing did nothing for at least 10 minutes. Refreshing after 2 hours the tags were properly read. Having the tags (and corresponding filters) take effect automatically and in near-realtime would make it possible to use the boards more effectively since it would be a live representation of the issues.

**Comment by sxgao3001** [comment]
Hey @abbyad, this one is on our radar. Thanks for bringing it up. We're actively working to resolve it. Will update you when it's fixed.

**Comment by sxgao3001** [comment]
@abbyad this issue should be resolved now. I'll leave this issue open for a while for you to verify.

**Comment by abbyad** [comment]
Just tested and works well now. Thanks for quickly resolving it!
