### ISSUE TITLE
Add ability to filter based on whether an issue/PR is assigned

### ISSUE THREAD

**Issue by ketan** [ZenHubIO/support#224]
In addition to `no:assignee` github supports an `is:assigned` filter. This filter will allow to see issues that are assigned.

If zenhub were to allow support for this `is:assigned` then it'll allow us to track work that is in progress across the board, separately from work that is not assigned (which we can already track)

PS: Thank you very much for a great product!

**Comment by aupright** [comment]
Hi @ketan, thanks for the kind words about ZenHub!

I agree that that would be be useful to filter the board by only those issues that are assigned. Our immediate product roadmap is focused on increasing the amount of functionality available from the board, so this seems like a good fit as a feature to explore! I'll make sure this finds a way into the discussion at our next roadmap meeting!

**Comment by phemmer** [comment]
perhaps zenhub can offer a filter box where a text filter can be typed (like on the standard github issues/PRs pages). This doesn't preclude the possibility of adding a specific checkbox or whatever for this specific filter, but it would provide a much more flexible solution.

**Comment by azenMatt** [comment]
This can now be performed on a per-pipeline basis with the sort by assignee feature - which will allow you to easily seperate those that are assigned to those unassigned.
