### ISSUE TITLE
org level repos with different milestones

### ISSUE THREAD

**Issue by slajax** [ZenHubIO/support#225]
Congrats on shipping multi-repo! Long awaited.

Am I supposed to be able to filter across milestones? Seems like I can only select one milestone, which implies they need to be sync'd across all repos?

It's a pretty huge assumption that all repos would follow the same milestone namespace, wouldn't it?

Feel free to reference an existing issue and close if this has already been answered.

**Comment by slajax** [comment]
@roham - little help?

**Comment by roham** [comment]
Hey @slajax ! Glad you like the multiple repo boards. You bring up an important point re: the Milestones. This is something we've talked about internally and are looking at implementing in a future iteration of the Boards. Our short-term priorities are pushing out a few more key features; we'll circle back to polishing this shortly thereafter. 

Please keep the feedback coming!

**Comment by slajax** [comment]
Bummer, but we'll try to work around it for now. If you hear of any workflow adjustments or otherwise we can use to alleviate this pain point, could you please ping me?

Essentially, we just want to be able to focus our board view to the specific milestones across each repo's given context. Repos might have different milestones, so we would want to be able to multi select milestones. This would also require some indication on the milestone of what repo it belongs to, but would result in a view where we populate all the current milestones on all the repos into the board.

Thanks for the quick ping back @roham!

**Comment by roham** [comment]
Will do @slajax - please get in touch if you have any more questions. Your suggestions have all made it onto our internal ZenHub Board so it's only a matter of time :)
