### ISSUE TITLE
Add ability to only show current board (if multiple are merged).

### ISSUE THREAD

**Issue by Ferada** [ZenHubIO/support#226]
At the moment with merged boards there is only the "show all" option. It would be great if that button changed to "show only this" (better caption?), instead of being disabled, so that switching between showing everything and just the current board is easier.

**Comment by aupright** [comment]
Thanks for the suggestions @Ferada, 

We'll definitely take this into consideration as something to update! Does anyone else here in the support repo find the current copy confusing, and if so, would the changes prosed above make things more clear?

**Comment by jefforshalick** [comment]
I do find it strange that the `show all` button grays out after a click. I think the `show all` / `show just one` toggle is pretty common. Maybe the copy for the state after `show all` is clicked could be `show only this repo`? A little bit longer than @Ferada's suggestion but maybe a little bit clearer?

**Comment by azenMatt** [comment]
Hi @jefforshalick @Ferada - we have just released this on 2.5.9 - when all repos are selected, the button will now be 'show one' letting you view just the 'owner' repo. Enjoy!
