### ISSUE TITLE
"Switch repository" button breaks style a bit

### ISSUE THREAD

**Issue by jimon** [ZenHubIO/support#228]
When github page is loaded they have this vertical space here :
![image](https://cloud.githubusercontent.com/assets/1333661/7573503/6a1f63fe-f826-11e4-8ed3-bd932c3d3fea.png)
And after 0.5-1 seconds zenhub kicks-in and add switch repositories button, which increase vertical space here :
![image](https://cloud.githubusercontent.com/assets/1333661/7573508/77987bce-f826-11e4-9fab-6c67b5fa97ac.png)

It's a small issue but it's really annoying !

**Comment by aupright** [comment]
Hi @jimon, 

I appreciate you reaching out! Even though it might be a small issue, it's still worth brining back to the team to see if we can improve the transition. I'll keep you in the loop with any updates here. If there's anything I can help with in the meantime, please don't hesitate to reach out :smile:

**Comment by azenMatt** [comment]
Hi @jimon - we have changed how we load the repo switcher so you should be noticing a much smoother experience :smile:
