### ISSUE TITLE
New issues don't remember estimate or pipeline

### ISSUE THREAD

**Issue by iBeliever** [ZenHubIO/support#229]
**Steps to reproduce**

 1. Create a new issue, entering an estimate and selecting the pipeline
 2. Save the issue
 3. The estimate is empty and pipeline shows as New Issues instead of the selected pipeline
 4, Enter an estimate and/or select a pipeline
 5. Refresh the page
 6. The estimate and/or pipeline shows correctly now

**What should happen**

 The pipeline and estimate should save the first time.

**Comment by azenMatt** [comment]
Thanks for reporting this @iBeliever - I can also recreate this. 

High priority fix coming up....

**Comment by azenMatt** [comment]
Fixed on 2.1.9 - now live on the chrome store!

**Comment by iBeliever** [comment]
Thanks for the quick fix!
