### ISSUE TITLE
Change "Boards" and "Burndown" button position under the "Wiki" button

### ISSUE THREAD

**Issue by awakia** [ZenHubIO/support#231]
I like ZenHub! but unfortunately, ZenHub buttons appears about a second after the page loaded. It cause miss click when I want to click pull request button etc.

![screen_shot_2015-05-14_at_9_16_23_pm](https://cloud.githubusercontent.com/assets/272083/7631569/e98ebac2-fa7e-11e4-833e-df08be08198e.png)

To improve loading speed is difficult, so why don't you change the button place to keep default button positions?

**Comment by creasty** [comment]
+1

**Comment by morizotter** [comment]
+1

**Comment by azenMatt** [comment]
Thanks for the feedback here @awakia - I agree with you that on a slow load this can prove awkward. 

We are working on a solution at the moment to make sure we keep a good user experience

**Comment by phemmer** [comment]
Aside from the slow loading issue, I also don't like the placement as it moves things around to much. I go to the "issues" and "pull requests" tabs on various projects fairly frequently. I'm used to those 2 tabs being in their usual spot (2nd and 3rd). Having zenhub sticking it's own icons in their place is rather interruptive.

I like @awakia's proposed placement a lot better. But at the very least, after the pull request tab.

I would also think the new "burndown" tab makes sense down next to the "graphs" tab, as they both serve similar purposes.

**Comment by awakia** [comment]
Thanks you @azenMatt to attach this issue to "Enhancement" label.

@phemmer 's suggestion is also acceptable for me. From my own experience, position change of issue and PR buttons after installing ZehHub is the strongest obstacle to spread ZenHub to my colleague, since this create downside for their productivity at least for the first week.

So, I'm happy when ZenHub team take one of these idea into account during enhancement discussion.

1. Create ZenHub buttons section between Wiki and Pulse. (my first idea)
2. Boards to under PullRequest, Burndown to under Graphs. (@phemmer's idea)
3. Customisable button placement.

**Comment by aupright** [comment]
Hi @awakia, we've just pushed out a release (v2.1.12) that resolves the side bar loading issues you mentioned in your first message—when you load a page in GitHub, all of the buttons should now appear at the same time! 

If the extension wasn't already pushed to your account, you can manually update it by visiting your extensions page (chrome://extensions/), checking "developer mode", and then clicking "update extensions now". 

Let me know if you have any questions!

**Comment by phemmer** [comment]
@aupright Can implement the same fix on the other sidebar stuff (pipeline, labels, milestone, estimate, ...). it suffers the same issue, where pipeline and estimate show up a second or so after loading, and I frequently end up clicking the wrong thing.

**Comment by aupright** [comment]
Thanks for the suggestion @phemmer - I'll bring it back to the team to see if we can build off the work we've done here and roll something into the next release :beers:

**Comment by azenMatt** [comment]
The new GitHub UI helps resolve this issue as we have moved the location and resolved much of the 'popping' issue: 

![image](https://cloud.githubusercontent.com/assets/7584089/11308186/9be21002-8f71-11e5-9412-79ae3ce93995.png)

We are still iterating to make sure the new UI experience is as smooth as possible so please let me know any feedback!
