### ISSUE TITLE
Draw burndown chart with issues on specific pipelines.

### ISSUE THREAD

**Issue by computeus** [ZenHubIO/support#232]
We have a pipeline that called "Done". There are issues in this pipeline that are not closed yet, but the work on the issue is finished. We close the issues when issues are merged to master.

So it will be good to select the issue pipeline for burndown chart, that it will assume issue on the selected pipeline as done, when drawing the chart.

**Comment by azenMatt** [comment]
That makes a lot of sense @computeus - I will add this into the improvements we have planned for a V2 of the burndown charts!

**Comment by torkiljohnsen** [comment]
:+1: Yes!

**Comment by laurencesmithever** [comment]
+1 - really need this!!

**Comment by azenMatt** [comment]
This is now live on the burndown page - you can select which pipelines will 'burndown' an issue
