### ISSUE TITLE
Display pipeline on PR/issue list view

### ISSUE THREAD

**Issue by ajwhite** [ZenHubIO/support#234]
It would be great if we could see the Pipeline when looking at all issues and PRs, rather than only when you have them opened. I realize the boards are meant to be utilized to see where issues fall in the pipeline, but it'd also be a useful utility to have these labeled in the list views as well.

Also with the new introduction of story point Estimates (representing issue complexity), it'd be great to see these too!

On top of this, would be awesome if there were filters via issue-view as well.

**Comment by azenMatt** [comment]
Thanks for the feedback @ajwhite 

This is a popular request (also recorded here - #127) and we are looking into how we can improve this. 

Im going to close this issue to keep all the discussion in #127 - but you can be assured that on our internal roadmap we have collected all your feedback :smile:

**Comment by ajwhite** [comment]
Thanks, tried searching for an existing as I thought it may have been brought up :+1:
