### ISSUE TITLE
Non collaborators can manage estimates 

### ISSUE THREAD

**Issue by ajwhite** [ZenHubIO/support#235]
It appears that non-collaborators can manage Estimates on issues that should otherwise be read-only or hidden.

![screen shot 2015-05-15 at 11 51 48 am](https://cloud.githubusercontent.com/assets/656630/7656511/e44e9256-faf8-11e4-8698-16fa3d333d4c.png)

**Comment by azenMatt** [comment]
well spotted @ajwhite - this should be a small fix - we will take care of it in a coming release!

**Comment by azenMatt** [comment]
non collaborators can not longer save estimates against issues. 

the 'change' icon does still appear so we will get that tidied up soon :+1:
