### ISSUE TITLE
User images in board should not be `circled`

### ISSUE THREAD

**Issue by basarat** [ZenHubIO/support#238]
See my image vs. images in boards 

![image](https://cloud.githubusercontent.com/assets/874898/7696327/7231367a-fe3f-11e4-83e7-91d0b84e66e4.png)

These should be square like the rest of github otherwise the people's images are distorted (poorly) :rose:

**Comment by aupright** [comment]
Hey @basarat, thanks for the suggestion!

We're actually in the process of re-designing some board elements as a part of a coming update for ZenHub. I'll pass your feedback here on to the design team to see if they would be interested in incorporating it into future versions! 

Thanks again for reaching out :smiley:
