### ISSUE TITLE
Display current milestone when coming from the Github milestone view

### ISSUE THREAD

**Issue by seb-koemei** [ZenHubIO/support#24]
When I am on https://github.com/<user>/<repo>/issues?milestone=<milestone_id> and I click on the Zenhub Board icon, I'd like the board for that milestone to be displayed.

Currently it displays the board for the latest milestone visited in the  Zenhub board.

**Comment by kendramoroz** [comment]
👋  Doing some clean up of our community Board and we've decided to close out this Issue as we continue to focus on core workflow experiences around Boards and Reports. To help with filtering, if you're coming from the GitHub Milestone view, you can always leverage the filter option to jump the Board with the Milestone view automatically added 🎉 

![image](https://user-images.githubusercontent.com/11036230/35174078-e004af8a-fd22-11e7-8add-818c0cd77c78.png)

Keep an eye on our `Priorities` and `In Progress` pipelines for what goodies are coming to your ZenHub experience soon! 🚀
