### ISSUE TITLE
Shortcut for boards (d) interferes with `alt+d`(which I use to select url)

### ISSUE THREAD

**Issue by basarat** [ZenHubIO/support#240]
Try it : press `alt+d` and you are moved to boards

**Comment by kfranqueiro** [comment]
FWIW Ctrl+L works for that too as a workaround, but I agree.  I've used alt+D for years and it's easier to type.

Also, when this happens, clicking back doesn't work, you have to reload the page to get back to where you were.

**Comment by azenMatt** [comment]
Hi @basarat @kfranqueiro - a fix is coming for this soon so that only 'd' will act as a ZenHub shortcut

**Comment by aupright** [comment]
Hey @basarat and @kfranqueiro!

We just pushed a fix out for this one earlier this afternoon. You should now be able to use `Alt+d` to copy the URL and `d` to bring you to the burndown chart page :smiley:

**Comment by kfranqueiro** [comment]
Seems to be resolved.  Thanks very much!
