### ISSUE TITLE
Cannot create a board

### ISSUE THREAD

**Issue by cgranitto** [ZenHubIO/support#242]
Hi!
I've just installed ZenHub, selected a (empty yet) repo and tried to open a board, but simply couldn't create any board. How can I create it? 
And when I click on "Boards", nothing happens. 

Is there any issue with permissions?

Thxs.

**Comment by aupright** [comment]
Hi @cgranitto thanks for reaching out, I'll have the team look into this one.

To help us with troubleshooting, would you be able to let us know which organization you are using ZenHub with and for which repo you are trying to create a board? If you could include a screenshot of any error messages that you are seeing, that would be helpful as well.

**Comment by cgranitto** [comment]
Hi @aupright , sorry for my late answer. 

I think here we are some clue: when I enter to my dashboard, I don't see any organization. The message is clear: "You are not part of any organizations."

Also I don't see any button to add my account to any organization.

**Comment by cgranitto** [comment]
I see it then. I requested access for Zenhub to my organization. I'll be waiting for the approval and will try again.

**Comment by cgranitto** [comment]
Yeah it's working now!
Thanks.

**Comment by aupright** [comment]
Thanks for the updates @cgranitto - let me know if there's anything else I can help with!
