### ISSUE TITLE
Group issues by Milestone

### ISSUE THREAD

**Issue by matthewlmcclure** [ZenHubIO/support#243]
I'd like boards to group issues by milestone. I imagine a board could show issues from all milestones simultaneously, with all the issues for the each milestone appearing above all the issues for subsequent milestones.

For example:

```
     New     Backlog     ...
M1
     I1      I2
M2
     I3     I4
     I6     
M3
     I7     I8
            I9
```

**Comment by aupright** [comment]
Hi @matthewlmcclure, thanks for the suggestion!

I think that type of hierarchy would be an interesting feature to explore. I'll move this conversation into the discussion pipeline to see if we can get some more feedback and +1's from the rest of the community.

To the ZenHub community: If this is something that you would like to see in ZenHub, please vote by adding a +1 or providing some additional feedback below!

**Comment by azenMatt** [comment]
Lets close this issue and merge the conversation with #46 - more ways to view your information on the ZenHub board are coming soon :smile:
