### ISSUE TITLE
Burndown defaults to the newest milestone

### ISSUE THREAD

**Issue by iBeliever** [ZenHubIO/support#245]
I originally create a "Version 0.1" milestone. Later I created a "Version 0.2" milestone to move some issues of lesser importance to a future release. Now the burndown chart defaults to "Version 0.2" instead of "Version 0.1". I'm assuming it picks the most recently created issue.

Wouldn't it make more sense to default to the milestone with the earliest due date? It might also be nice to save the selected milestone so teams can change the current focus for development.

**Comment by aupright** [comment]
Thanks for the feedback @iBeliever,

One of the assumptions we made when choosing the default milestone was that the most recent milestone would likely be the most relevant in people's workflows. Having said that, we're always open to revisiting things if our users feel that it would better meet their needs. 

I'd like to open this one up to the rest of the community to vote on and see if it's something that they would find helpful as well. To the ZenHub Community: please indicate your support with either a +1 or a comment below if this would be a welcome change!

**Comment by kenjiuno** [comment]
Hi. I have same issue too.
I'll be happy if there is an option to select or remember my working milestone.
Thanks.

**Comment by myktra** [comment]
Agree, I'm using the Burndown view to actively manage the *current* milestone based on its start/end date. Not logical to me to show the most "recently added" milestone.

It might even make sense to tabify this interface rather than show the milestones in a dropdown list...show only open milestones, with current milestone with the closest end date the "active" tab. Closed milestones could be accessed through some alternative widget for historical purposes.

**Comment by lbergelson** [comment]
Defaulting to the most recent milestone doesn't make any sense to me.  We tend to plan several milestones ahead, so the most recent one is never the active one.  It would be much better to show the one with the closest due date or just remember the last one I looked at.

**Comment by azenMatt** [comment]
@lbergelson - A fix is working its way to the chromestore as we speak :grinning:

**Comment by azenMatt** [comment]
This is now live in version 2.5.9! 

:beers:
