### ISSUE TITLE
Milestone appearing twice

### ISSUE THREAD

**Issue by wmbutler** [ZenHubIO/support#246]
I've been using Zenhub for a while. Love it. Just modified the due date on a Milestone and Zenhub is now listing it twice. It also seems to have lost track of items that were assigned to it. Github has it correctly but Zenhub seems out of sync.

Steps so far:

- removed and re-added the zenhub plugin

**Comment by aupright** [comment]
Thanks for bringing this to our attention @wmbutler!

We'll look into things further here to see where this error might be occurring. Were you able to replicate the error when you removed and re-added the extension, or was this just a one time issue that you experienced? Any additional information or steps taken to reproduce would go a long way in helping us troubleshoot. Thanks again for reaching out!

**Comment by torkiljohnsen** [comment]
I had this issue happen right now. I changed the name of a milestone and now both the old and new milestone names are appearing in the milestone filter dropdowns. I thought at first that this was just an issue that my colleagues had, but I see now that I have the duplicated milestones too. 

Another issue that is probably related is that an issue we have that is "In progress" on the milestone in question is not appearing on the board at all. When I go to GitHubs normal milestone view of the issues list, I can see the issue just fine, but it does not show up on the board.

The native GitHub milestone dropdown, for instance the one that appears when you edit an issue's milestone, contains the correct list of milestones. In the burndown page, the milestone dropdown is correct. It's only in the board view that it contains the duplicate.

To reproduce: Rename a milestone that has issues in it.

**Comment by torkiljohnsen** [comment]
The worst thing about this is that the burndown list is now showing 21 open issues while the board is showing only 13. This renders the board essentially useless.

**Comment by torkiljohnsen** [comment]
"Fixed" the issue by creating a new milestone and moving all open and closed issues to that milestone.

**Comment by aupright** [comment]
Thanks for the updates here @torkiljohnsen! On our end, we've determined this issue to be due to caching inconsistencies that we're currently addressing with an update. I'll reach out as soon as we've gone live with a fix and let you know!

**Comment by losandes** [comment]
We just had this happen too, after we renamed a milestone.

**Comment by azenMatt** [comment]
@losandes - thanks for letting us know - we are currently testing the fix and are aiming to have it live towards the end of next week

**Comment by azenMatt** [comment]
Hi all - please see this comment - https://github.com/ZenHubIO/support/issues/244#issuecomment-115873135 - for details of the fix put live for this issue

il keep that thread updated for future changes!

**Comment by seperman** [comment]
I did not rename the milestone. Only updated the deadline of it and I'm seeing duplicate milestones in the board too. Also not sure related to this or not but not all the milestone issues show up when choosing the milestone from the board view.

**Comment by aupright** [comment]
Thanks for reaching out @seperman - this does appear to be related to the same errors that we were seeing in #244 with the milestone inconsistencies. I'll have our team manually refresh the cache for your repo to remove the duplicate milestones :beers:
