### ISSUE TITLE
Messy labels on burndown chart x-axis

### ISSUE THREAD

**Issue by torkiljohnsen** [ZenHubIO/support#248]
Not sure why, but the labels on the x-axis are messy. Both overlapping and with unequal spacing between them.

![skjermbilde 2015-06-02 kl 10 34 52](https://cloud.githubusercontent.com/assets/318089/7931763/9888e1a4-0913-11e5-9a44-66e2bcee6fff.png)

**Comment by aupright** [comment]
Thanks for issuing this up @torkiljohnsen!

I'll bring this one back to the team to see if we can implement a quick fix here. Hopefully removing the leading 0's for the dates (ex. 05/06/15 to 5/6/15) will help save some space and prevent the dates from overlapping. I'll keep you in the loop with any progress updates that I hear!

**Comment by azenMatt** [comment]
This is now live, the new x axis is much tidier! 

![image](https://cloud.githubusercontent.com/assets/7584089/8343423/ebef2312-1a89-11e5-9feb-63f0a8720cca.png)

**Comment by adamreisnz** [comment]
@azenMatt It's still a bit messy if a milestone spans several months. I think some of the labels should be skipped to have a lower density:

![image](https://cloud.githubusercontent.com/assets/490562/25312319/87227bdc-286a-11e7-9eb2-fed9c7991b4d.png)
