### ISSUE TITLE
Display checkbox progress on cards

### ISSUE THREAD

**Issue by dshahin** [ZenHubIO/support#249]
using markdown, we can add checkboxes to issues
![screen shot 2015-06-02 at 5 02 56 pm](https://cloud.githubusercontent.com/assets/933826/7949985/428aeb54-0949-11e5-8d96-1122b00f573e.png)

Standard issues UI shows a progress bar related to how many checkboxes are checked
![screen shot 2015-06-02 at 5 01 45 pm](https://cloud.githubusercontent.com/assets/933826/7949977/235235e4-0949-11e5-8b0f-d5b442d3f987.png)

It would be very useful to see this, especially when cards are in the "in progress" pipeline.  This + issue #236 (Display point estimates on the board) would really make the board a bit more indicative of the current state of things.

Thanks for considering this, I love your product!

**Comment by azenMatt** [comment]
Hi @dshahin 

I love this idea! It already has some support on this repo in issue #126 and we have it in our private backlog as well. 

To help keep all the conversation in one place, I am going to close this issue in favour of #126 - please feel free to head over and +1 that issue as well!
