### ISSUE TITLE
Add "me" as a first item of the assignee dropdown

### ISSUE THREAD

**Issue by jirihelmich** [ZenHubIO/support#250]
- on GitHub, your name is always the first in the list, so now it's confusing when it's not
- they have the "assign yourself" link, something like that would be even better to quickly list my issues

**Comment by azenMatt** [comment]
Thanks for the feedback @jirihelmich - added into the roadmap!

**Comment by azenMatt** [comment]
@jirihelmich - this is now live in version 2.5.5 :grinning:

**Comment by jirihelmich** [comment]
Cool, thanks!

**Comment by jirihelmich** [comment]
It seems that this does not work anymore.

**Comment by azenMatt** [comment]
you are right - looking in to it now :)

**Comment by jirihelmich** [comment]
Great!
Mon, 25 Jan 2016 v 22:04 odesílatel Matt Butler <notifications@github.com>
napsal:
