### ISSUE TITLE
As a PM I want to be able to entirely remove a pipeline stage to get more screen real estate

### ISSUE THREAD

**Issue by kevinstumpf** [ZenHubIO/support#259]
If I remove a pipeline stage, the released screen real estate is taken up by the "Add a Pipeline" "column". It would be nice if the Add feature was hidden in a less space consuming way

**Comment by azenMatt** [comment]
Thanks for the feedback @kevinstumpf 

We have been looking into this one and it is an upcoming feature to improve the boards. 

We have an issue open for this here - #163 - so I am going to close this issue. Feel free to comment or +1 #163 to show your support :smile:
