### ISSUE TITLE
Middle-click issue to open new tab

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#262]
Previously, left-clicking on an issue link in a pipeline would open a new tab. Now we get a popup. This is great, but I'd still like to have issues open in a new tab.

Would you make the changes needed so that a middle-click on a link can allow the default link behavior of opening in a new tab? Thanks!

**Comment by azenMatt** [comment]
Hi @Mottie, 

This is already the designed behaviour, 

Left click = Open in board 

cmd+click / ctrl+click / middle-click will open in a new tab

Is this not working for you?

**Comment by Mottie** [comment]
Not in Chrome/Windows 8.1

![middle-click](https://cloud.githubusercontent.com/assets/136959/8288502/346d5078-18dc-11e5-87c7-eceee7e96a75.gif)

**Comment by azenMatt** [comment]
ok - thanks for letting us know :+1: 

We will take a closer look!

**Comment by azenMatt** [comment]
A fix for this is now live on version 2.2.15 :beers:

**Comment by Mottie** [comment]
Awesome! Thanks!
