### ISSUE TITLE
As a PM, I want to be able to add issues to milestones from a board

### ISSUE THREAD

**Issue by lexsf** [ZenHubIO/support#264]

**Comment by azenMatt** [comment]
Hi @lexsf - thanks for the feedback, 

The quickest way to do this is to left-click the issue to enter the 'issue pop-up' and change the milestone there: 

![image](https://cloud.githubusercontent.com/assets/7584089/8343663/ac9d3b06-1a8c-11e5-9257-71b56e4b532f.png)

I hope this helps!

**Comment by lexsf** [comment]
Thank for the response @azenMatt   I probably should have changed the title to a "bulk" way of adding issues to a milestone from the board ui, not the detail screen of an issue.

The use case is this:  We are on the board and adding issues from the product backlog into the sprint.   We can easily drag and drop the issues onto the sprint column.  However, to generate the burndown chart I have to add those issues to the milestone, so it is now one click to get to the details, one click to select the milestone, and one click to close the details.   Multiply that by 20 or so issues per sprint and it is a lot of unnecessary time spent just to make the burndown charts look correct.  

I'm not sure if in the future these might be more closely coupled (I know that burndown charts are brand spanking new) but the underlying issue is that the board view (which the daily status and activity occurs) doesn't necessarily match the milestone view (where the burndown chart is) without manual work to make sure they are in synch.

Anyhow, great work so far on ZenHub.

**Comment by azenMatt** [comment]
that makes a lot of sense. Something like #46 sounds like it will also be useful here - as you can instead drag and drop issues to the correct milestone. Even better combined with the ability to multi-select issues to move several at once that we also have on the backlog. 



> Anyhow, great work so far on ZenHub.

Thanks :smile: lots more to come!
