### ISSUE TITLE
Changing a pipeline or estimate fails to save the value from popup issue editor

### ISSUE THREAD

**Issue by jtwalters** [ZenHubIO/support#265]
## Bug

- Boards view
- Open an issue (as a popup)
- Change the pipeline
- Close the popup
- Pipeline isn't actually updated

Same with estimates.

**Comment by azenMatt** [comment]
Hi @jtwalters - would you be able to provide some more information here, is this just a delay in updating in the board view, or does not information not persist at all? 

If you select an issue again that you have just seen this problem on, do the pipeline values / estimates still show as the old values? 

We have a big update going live later this week to our job system that is going to improve the speed and stability of these updates - I will let you know when this is live and we can see if it helps this issue

**Comment by jtwalters** [comment]
@azenMatt 
Seems like it was a temporary issue. Checked again this morning and it's working.

**Comment by braneof** [comment]
I just experienced this problem too. Then I restarted my browser (it had been open a few days) and it works fine now.
