### ISSUE TITLE
Be able to move 'closed' board, 

### ISSUE THREAD

**Issue by colinmegill** [ZenHubIO/support#267]

**Comment by azenMatt** [comment]
Hi @colinmegill 

This isn't currently on the roadmap, as we are working under the idea that most users will want issues to move from the left side of the board through a custom flow into the closed pipeline on the far right of the board. 

No technical reason why it can't move though - and im always open to be proved wrong! lets open this one up to the community and get some +1's from teams that will find this useful. This will help us fit it into our Product Roadmap
