### ISSUE TITLE
see milestone as a label on the issue

### ISSUE THREAD

**Issue by andreackinney** [ZenHubIO/support#268]
Hi there. It would be nice to see the GitHub milestones displayed as labels. It helps with organizing the backlog, etc. without having to use a filter.
![milestone](https://cloud.githubusercontent.com/assets/11392151/8313613/e23c42e2-19b1-11e5-8e22-b83f0b34c6f2.png)

**Comment by azenMatt** [comment]
Hi @andreackinney - an interesting idea! I can see how this would be useful to a lot of users. 

Moving this to the discussion pipeline to get some +1's against it to help us prioritize it into our roadmap

**Comment by andreackinney** [comment]
+1 ;)

**Comment by ehausen** [comment]
+1 
Not sure if voting is happening with the +1 button via zenhub or just commenting +1..

**Comment by luckychild305** [comment]
+1

**Comment by codeblooded** [comment]
+1

**Comment by haoliu119** [comment]
:+1: 
Nor sure how the +1s are tallied so i'm clicking the +1 button on the original comment and also commenting +1 here :)

**Comment by Tlvenn** [comment]
+1 as well, this is very much needed imho.

**Comment by Tlvenn** [comment]
And it does not have to be treated as a Label, could have its own style below the labels on the cards.

**Comment by laughedelic** [comment]
+1

**Comment by wreyniers** [comment]
+1 :+1:

**Comment by rreynier** [comment]
:+1:

**Comment by HeathNaylor** [comment]
+1 :+1:

**Comment by thejadmaster** [comment]
:+1:

**Comment by turner-btp** [comment]
:+1:

**Comment by anfomin** [comment]
:+1:

**Comment by Anvil102** [comment]
While this is an interesting idea, labels can get unwieldy in board view rather quickly. Would not want this feature unless I could turn this on/off with a preference selection.

**Comment by thisisfranciswu** [comment]
+1

**Comment by azenMatt** [comment]
Milestones are now shown on issue cards :)  (v2.23.17)


![image](https://cloud.githubusercontent.com/assets/7584089/17795621/e87192ca-656e-11e6-883e-0ed11a1ffb6e.png)
