### ISSUE TITLE
Option to not pop-up issues in an iframe

### ISSUE THREAD

**Issue by tuance** [ZenHubIO/support#269]
Is there an option to revert back to the old behavior of opening up an issue detail in a new browser tab/page?

**Comment by azenMatt** [comment]
Hi @tuance - the best way to do this is do use the 'new tab' functionality as you would with selecting a link on a webpage. So either cmd/ctrl + click or a middle mouse click will let you open into a new tab. 

Hopefully this will give you the best of both worlds :smile:
