### ISSUE TITLE
Ability to dismiss the trial over banner (or disable zenhub per-org)

### ISSUE THREAD

**Issue by jesseditson** [ZenHubIO/support#270]
Hey, I use zenhub for my open source projects, and while I certainly will consider it for my non-personal use, I work for a few companies that I can't control the purchasing decisions at. Recently I started seeing this banner at the top of all the pages when I visit private repos in those organizations:

![Banner](http://oi.pxfx.io/image/2M253L0S3m43/Image%202015-06-24%20at%203.48.04%20PM.png)

I'd love to be able to disable this banner for the orgs I know are never going to become subscribers (well... never say never, but I'd at least like to avoid that banner in the meantime).

Alternatively, just the ability to disable zenhub entirely for certain organizations - it could go in my org settings, and would greatly improve my experience.

**Comment by azenMatt** [comment]
Hi @jesseditson - a fix is coming very soon for this, so you will be able to work undisturbed in orgs where you are not using ZenHub. 

Should be live in roughly 1 week. 

If you would like some help pitching ZenHub to your private orgs, let @aupright know :smile:

**Comment by jesseditson** [comment]
That's great to hear! Thanks for making this awesome tool!

**Comment by azenMatt** [comment]
Fixed in version 2.2.15 

Apologies for the disruption! :beers:
