### ISSUE TITLE
Ability to link in issues from other projects

### ISSUE THREAD

**Issue by iBeliever** [ZenHubIO/support#271]
Often, for larger projects, an issue that affects the project is actually an issue in another project, such as a library or framework the project uses. It would be really awesome if we could "link in" an issue from another project and display in the boards and milestones (and possibly the issues list if that's technically possible). These linked in issues could have a special pipeline titled something like "Upstream bugs".

This could possibly be implemented as creating a new issue with special content that gets rendered as a reference to an upstream issue.

**Comment by azenMatt** [comment]
Hi @iBeliever 

Thank you for your feedback here, currently we are doing this the 'manual' way where we create a new issue and then use the GitHub linking markdown to reference the upstream issue. 

On out roadmap we do have #219 - Cross Org repository linking - that will be really useful here to bring a repository of issues over. 

To do this for individual issues (Guest issues?) isn't on the near term roadmap as we are focused on providing full repository views - but I will make sure it is issued up for future planning sessions.
