### ISSUE TITLE
Duplicate/Move issue to other repo

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#274]
It would be awesome to have the ability to "move" issues to other repos like [github issue mover](https://github-issue-mover.appspot.com/).

It would be nice for this action to be accessible from the hamburger icon on each issue on the board view as well as within the issue page itself.

And then an additional level of awesomeness would be to have the ability to control what it transferred over. Comments after the first one, labels, pipeline, estimate, and assignee would all be options to transfer over or not. And then what to do with the issue that you are copying from, pipeline and label would be awesome to change and control.

**Comment by seperman** [comment]
I need to move a board from somebody's private repo to another organization. This would be great to have.

**Comment by aupright** [comment]
Thanks for the feedback here @jefforshalick and @seperman!

I'll take a closer look into the tool that you've recommended here to see if we might be able to explore something similar for ZenHub related meta-data (estimates, pipelines, +1's, etc.) In the meantime, let's keep this issue open in the discussion column to see if we can get more input from the rest of the community and make a stronger use-case for adding this type of functionality going forward.

To the rest of the community - be sure to +1 if this would be useful for your team as well!

**Comment by fakewaffle** [comment]
How many votes are needed to get this implemented?

We have a lot of repos, and moving issues across them to the correct repo is a must.

**Comment by azenMatt** [comment]
I've actually been testing this one today - 

![image](https://cloud.githubusercontent.com/assets/7584089/12998575/4301a7f2-d0fa-11e5-87e7-d6c1ca6a7758.png)

so should be with you very soon!

**Comment by fakewaffle** [comment]
Love it!

**Comment by jefforshalick** [comment]
Awesome!

**Comment by azenMatt** [comment]
Hi all, this one just went live :smile: 

On version 2.15.47 you can now see a 'move issue' button on the sidebar which will let you move an issue to any other repo that you have issue creation access to within the organization. 

Let me know any feedback!
