### ISSUE TITLE
Copy direct link to issue in modal view

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#278]
First off, let me say that I love the new modal type view for issues when looking at a board.

The only thing it doesn't allow me to do is to copy the link to the specific issue with one click. When viewing the issue on its own screen, I just press cmd+L, cmd+C and it's copied. Sure, I can right click on the issue number link and click copy link, but ain't nobody got time for that! :wink: 

I don't know if you would be able to change the url when viewing the issues in a modal but maybe another solution would be to add a little chain link icon in the position noted below in red that copies the direct issue link with a left click.

![boards giftcardzen general issues](https://cloud.githubusercontent.com/assets/5415204/8415046/f9c0a662-1e50-11e5-8c3c-0975d01cc826.png)

**Comment by aupright** [comment]
Hey @jefforshalick - thanks for the suggestion here! 

Going forward there's still a few pieces of functionality that we're hoping to add to the new issue modal to improve things even further. I'll make sure that your feedback here makes it into the mix as we continue to discuss the different updates that we're hoping to go live with in future itterations. In the meantime, it sounds like you've figured out a quick work-around for this yourself :wink:
