### ISSUE TITLE
As a user, I want to be able to re-bind or disable hot-key bindings - ZenHub configuration panel

### ISSUE THREAD

**Issue by Rican7** [ZenHubIO/support#280]
Typing a ``` key when commenting on a PR or writing an issue will immediately move to the boards page and destroy all back-stack history, therefore making an accidental press a very destructive (and very frustrating) operation.

I'm still perplexed as to how ZenHub's extension doesn't have a settings/configuration panel at all. It would go a long way for a lot of its usability.

Related:
- #81
- #192

**Comment by azenMatt** [comment]
Hi @Rican7 - we are working on bringing a config panel to ZenHub soon to help with these usability issues

**Comment by kendramoroz** [comment]
👋  Hey @Rican7 Closing as we've [launched our new keyboard shortcuts](https://www.zenhub.com/guides/keyboard-shortcuts), which should prevent any future potential navigation woes. Don't hesitate to let us know if anything else has come up!
