### ISSUE TITLE
Minimize / Collapse Pipeline columns

### ISSUE THREAD

**Issue by caseykoppes** [ZenHubIO/support#281]
Would like the ability to minimize / collapse stages in pipeline so do not have to show very long columns of backlog and such. this would also reduce horizontal scroll

**Comment by aupright** [comment]
Hey @caseykoppes thanks for the suggestion!

You'll be happy to know that we're actively working on a 'collapsing and expanding' pipeline feature for ZenHub and are very close to going live with an update! Make sure to keep an eye #122 and #163 as we'll be updating those two threads as soon as this feature hits production :beers:
