### ISSUE TITLE
When created issue, set to place at top or bottom of pipeline

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#283]
When creating a new issue, it would be helpful to be able to add the issue to the top OR the bottom of a pipeline.

**Comment by aupright** [comment]
Hey @jefforshalick  - by default, the new issues you create are added to the bottom of the left-most pipeline (usually titled New Issues) on your boards. If you've manually dragged an issue to the bottom of that pipeline, you may notice that recently created issues will then appear above that issue. We do this as a way to preserve the order of issues that you've manually positioned within pipelines. 

I'll close out this issue for now, but feel free to add an additional comment if you have any further questions here. Thanks again for reaching out!
