### ISSUE TITLE
Hide column(s)

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#284]
Having the ability to temporarily hide columns out of view would be awesome for organizing and focusing when looking at boards.

**Comment by jefforshalick** [comment]
Dupe of #281

**Comment by aupright** [comment]
Thanks @jefforshalick for the suggestions!

You'll be happy to know that this one is a high priority for us right now, and that we're actively working on a collapsing and expanding pipeline feature for ZenHub. We're hoping to go live with this functionality soon, and will be updating the original threads #122 and #163 as soon as we launch!

**Comment by jefforshalick** [comment]
Thanks @aupright !
