### ISSUE TITLE
Decrease hover time on +1 users list tooltip

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#289]
The current hover time over `zenhub-hipaw-popover-item` to show a user's name is quite long. I didn't even realize that their name would appear on hover.

**Comment by aupright** [comment]
Hey @jefforshalick - I'll bring this one back to the rest of the team to see if this is something we can address with a quick update in our next version of the extension. I'm going to close this issue here for the time being as we've documented this internally. Thanks again :beers:
