### ISSUE TITLE
'Close Issue' button is inadvertently clicked with new Modals

### ISSUE THREAD

**Issue by payammeyer** [ZenHubIO/support#290]
The new modals to view an issue or add a new issue are nice, but I've seen so many users inadvertently close the issue when they really just meant to close the modal and then end up reopening the issue. Perhaps a confirmation would be nice to make sure they really wanted to close it.

**Comment by aupright** [comment]
Thanks for the suggestion @payammeyer - I can see where this might be a bit confusing for new users who aren't familiar with the native 'close' and 'comment' buttons in GitHub. I'll move this one to the discussion pipeline to see if we can get a few more votes and +1's!

**Comment by azenMatt** [comment]
Hi @payammeyer - I feel a modal would get very frustrating for users that do what to close an issue - as we are adding an extra event and an extra click every time the user takes this action - and here at ZenHub our goal is to make everyone more efficient! 

I'm going to close this one and keep an eye out for further feedback. Let me know if you are still seeing this issue occur a lot of if it has settled down now the team are used to the modal feature

**Comment by payammeyer** [comment]
Honestly it has settled down, so I agree with your approach.
