### ISSUE TITLE
Padding on right menu group

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#291]
It's been driving me a little crazy that the sunken menu group buttons on the right have no padding between them and the edge of the window when the zenhub board is open.

Something as subtle as 10px would alleviate my stress :smiley:.

And I guess it would have to be conditional, based on whether or not the boards is selected.

**Comment by aupright** [comment]
Appriciate the suggestion @jefforshalick!

I'll take this one offline with our product design team to see if they can work a quick fix in here. While I can't make any promises (you know how designer are :wink:), I'll try my best to push for this one!

**Comment by jefforshalick** [comment]
Hey, @aupright, I'm a designer! :wink: :art:
