### ISSUE TITLE
pipeline selection switches back to default pipeline

### ISSUE THREAD

**Issue by jjungle** [ZenHubIO/support#292]
When I select a pipeline other than the default pipeline it now and then switches back to the default pipeline while editing the issue. Everything else (Assignee, Labels) stays the same.

**Comment by aupright** [comment]
Thanks for the feedback @jjungle!

Are you still noticing this problem when using the pipeline selector, or has the error resolved itself? If this is still occurring, would you be able to let me know whether this is happening in the new issue modal (popover) or whether you are seeing this error in the regular issue view in GitHub? Thanks!
