### ISSUE TITLE
Clicking on milestone in filter selects wrong milestone

### ISSUE THREAD

**Issue by robamaton** [ZenHubIO/support#293]
I have two repos linked together, and each has a milestone. However, if I try to select one milestone, it selects the other one instead. This only works one way; one milestone is inaccessible. This just started happening today, although we've had the repos linked for longer. I've tested it on multiple computers/accounts, all Mac OSX. 

[zenhub-bug.mov | uploaded via ZenHub](https://files.zenhub.io/5593ff5627ca35b74f68d74f)

**Comment by azenMatt** [comment]
Hi @robamaton - we have put several improvements out to milestones recently and have been unable to re-create your issue. 

To confirm, a linked repo will match a milestone together if it has all the same properties - name + start/end date. 

Can you email me at support@zenhub.io if you are still having this issue and we will get it fixed for you!
