### ISSUE TITLE
i would like a daily email (schedule say at 7AM), with status updates

### ISSUE THREAD

**Issue by jovo** [ZenHubIO/support#295]
specifically, i want 
 - a list of everything that i am assigned to do, across all repos, organized by date
 - a list of activity from yesterday on all repo's that i contribute/follow

if i had this, i'd never have to use asana or basecamp or anything else ever again :)

**Comment by aupright** [comment]
Hey @jovo! 

You'll be happy to know that we're actually working on an MVP for this feature right now. At first, we're planning to release this as an email digest (either daily or weekly depending on activity) that summarizes all the ZenHub activity across a repo or organization by individual. 

As there is a lot of room for customization here, we'll be testing a few different formats and presentations to see what type of content resonates the most with our users. While I'm closing this thread out for now, I'll aim to provide an update here as we get closer to launching! :rocket:
