### ISSUE TITLE
Issues rule filtering

### ISSUE THREAD

**Issue by shahmirj** [ZenHubIO/support#296]
In Gmail I can redirect my emails into different areas/folders. I can also make them more important than others.

It would be great to have a similar concept in ZenHub. A few good example we can personally benefit from, but might apply to all communities using ZenHub:
- Anything with label:bug is highest priority
- A pull request always goes to the OnReview Column
- Any thing created by @support-user goes to the

**Comment by aupright** [comment]
Thanks for the suggestion @shahmirj! Would you be open to expanding some of your ideas above on how you see this taking shape within ZenHub? For example, is an issue with a label:bug automatically moved to the top of it's current pipeline to denote priority, or is there a better way to denote priority as it relates to your workflow? 

I'd love to hear what kind of approach would be most helpful for you and your team and see if we can get some comments from a few other groups as well!

**Comment by shahmirj** [comment]
What I really meant was it would be nicer to allow users configure their rules if you provide a sudo filter language such as in gmail.

## Our workflow
The board we use are defined as

    Backlog > Sprint Backlog > In Progress > On Review

The **On Review** bit is just pull requests. Because we don't merge till its reviewed. 

## Issue Rules example

So some logical issue filters which would help can be:

 - Issue with `label:bug` is `toppriority|lowpriority`
 - Issue with `label:bug` is moved to `Sprint Backlog` (This will work as a combination to the above rule)
 - Issue created by `@user1, @user2` are marked as `label:requests`. (The u1, u2 is just an idea but we could split it out as two rules and it will still work)

## Pull requests Rules example
Moving on we could have we can extend it to pull requests

 - Pull Request moved to `On Review`
 - Pull Request with `label:bug` is `toppriority`

---

Event with a small set of examples above the user of ZenHub can define a million ways of doing things, without you having to generalise different workflows.

**Comment by laughedelic** [comment]
+1

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports to give teams in ZenHub a stellar workflow and workspace home to manage projects. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
