### ISSUE TITLE
Improve the ZenHub Badge

### ISSUE THREAD

**Issue by wespday** [ZenHubIO/support#297]
"Suprecharged By" is cute but maybe "Organized With" is more informative?

![zenhub-organized-with-badge](https://cloud.githubusercontent.com/assets/8332125/8483222/cb26e364-20b4-11e5-9c8c-ad6aecaa61a5.png)

**Comment by aupright** [comment]
Hey @wespday we're always open to change :smile: 

Let's see if we can get some more feedback from the rest of the community before I bring this one back to our design team! If you have any other suggestions, feel free to add them below as well!

**Comment by Mottie** [comment]
I was hesitant to use the badge because "superchanged" is non-specific. I also like "Organized With" or maybe even "Managed By". A choice would be nice... or I could design one myself.

**Comment by pv8** [comment]
About the design of the badge, wouldn't be better to use [shields.io](https://shields.io/) instead of creating a svg file? 

![ZenHub](https://img.shields.io/badge/Shipping_faster_with-ZenHub-5e60ba.svg?style=flat-square "Shipping faster with ZenHub")
