### ISSUE TITLE
Estimates are only visible to person who created it.

### ISSUE THREAD

**Issue by UtahDave** [ZenHubIO/support#299]
My team members have all added estimates to their issues and most of those estimates are not showing up when I look at those issues.

Team member: Estimate shows as "3"

Me: Estimate shows as "No estimate yet"

**Comment by aupright** [comment]
Hey @UtahDave - just wanted to follow up from my email to see if you were still noticing these errors and (if so) if you could provide some more info here:

- Were these errors occurring in the modal view, or main issue view?
- Was the repo you were working in private or public?
- Are the users who are assigning these estimates repo owners?

**Comment by azenMatt** [comment]
We have put some improvements live around estimates and are unable to replicate this issue.

@UtahDave - If you are still getting this problem please re-open this or contact ZenHub support directly and we will get it sorted for you
