### ISSUE TITLE
Relating Boards and Milestones

### ISSUE THREAD

**Issue by bluepete** [ZenHubIO/support#301]
As an organization, we would like to have the ability to relate Boards and Milestones in such a way that when we drag an issue to a Board that is related to a particular Milestone, the association is made automatically on the issue itself.

We have created Milestones and Boards that relate to development sprints. If they were related it would save us from having to manually update the Milestone for each issue that gets moved from our Backlog board to a particular sprint's board.

**Comment by azenMatt** [comment]
Hi @bluepete 

It sounds like #46 - the ability to view pipelines as a milestone would be really useful for you here? 

As would the ability to automatically set different rules for issue movements (for example, if moved to X state - assign Y and set milestone Z) 

Making the updating of issues easier is a high priority for us - both of these and more are on our roadmap!
