### ISSUE TITLE
plugin fails to pull recent activities, stuck in loading

### ISSUE THREAD

**Issue by kodermike** [ZenHubIO/support#307]
We finally migrated/upgraded from the old Chrome store extension to the new extension that's provided via the self-hosted enterprise interface. But when we go to either github.com or our github enterprise instance after authenticating the plugin, we are presented with a spinning ying/yang icon that recent activity is being loaded.

It never loads.

Chrome 43.0.2357.132 (64-bit) on a Yosemite late 2012 iMac in my case (I have another user that confirms). I made sure to remove the old plugin, and even tried restarting chrome after installing.

**Comment by aupright** [comment]
Hey @kodermike thanks for reaching out here as well!

I'm going to close this one out as we just shipped the upgrade package for this today and will continue to help you get up and running over email. Thanks :beers:
