### ISSUE TITLE
Ability to make gantt charts

### ISSUE THREAD

**Issue by jovo** [ZenHubIO/support#308]
using milestones and tasks, possibly using instagantt, like asana does.

**Comment by aupright** [comment]
Thanks for the suggestion @jovo - let's leave this one open for a bit longer in the discussion column to see if we can get some more feedback from the rest of the community here. Even if we don't end up exploring this functionality ourselves, another approach we could take is to make meta-data for milestones and estimates available to users so that they can create these type of reports themselves!

**Comment by jovo** [comment]
@aupright my current work around is to make milestones with dates.
the issues with this are:

1) i can't re-use milestones across repos, and sometimes (often), multiple repo's have the same milestones.  the boards allow me to create pipelines across repos's, but i can't use milestones from one repo on another repo.

2) even if this issue were fixed, the visualization of milestones is quite limited, i can't see all of them (even for a single repo) because of the way github natively shows milestones. even better would be a unified view of all milestones on all repo's i'm in.

so, should i create 2 new feature requests, which are simpler and perhaps more general than this one?

**Comment by aupright** [comment]
Thanks for the follow up @jovo!

We've actually heard both of these requests before and are exploring them internally! While cross-repo milestones present a bit of a technical challenge (as they aren't currently supported by GitHub), we are very interested in supporting them going forward for both our boards and burndown charts. 

Rather than creating two separate issues for these requests, let's keep things consolidated for now. There are a few other threads (see #247) that we'll aim to update when we have new information!

**Comment by runofthemill** [comment]
fyi @jovo, I just found this repo which is a node.js github issue-to-gantt chart server. might be useful!

https://github.com/neyric/gh-issues-gantt

**Comment by jovo** [comment]
that does look cool!
hopefully soon it will be integrated so i don't have to set it up :)

On Wed, Sep 2, 2015 at 5:24 PM, jeremy <notifications@github.com> wrote:

> fyi @jovo <https://github.com/jovo>, I just found this repo which is a
> node.js github issue-to-gantt chart server. might be useful!
>
> https://github.com/neyric/gh-issues-gantt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/308#issuecomment-137248779>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
<https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York>

**Comment by azenMatt** [comment]
Taking a look at this as well - nice find @runofthemill :smile:

**Comment by runofthemill** [comment]
👌

**Comment by gunta** [comment]
+1

**Comment by benortiz** [comment]
I would love to use a gantt chart-like interface for planning milestones and be able to more succinctly communicate with others where we are in the process than the kanban style board.

**Comment by laughedelic** [comment]
+1!

**Comment by jonathanrocher** [comment]
+1!

**Comment by thisisfranciswu** [comment]
+1

**Comment by joejulian** [comment]
:+1:

**Comment by stewartwebb** [comment]
👍

**Comment by dluciano** [comment]
(y)

**Comment by InfiniteCoop** [comment]
+1

**Comment by kramer65** [comment]
+1

**Comment by rodsfreitas** [comment]
+1

**Comment by rduque1** [comment]
+1

**Comment by alaincoletta** [comment]
+1 Please!

**Comment by acafourek** [comment]
👍 

Some notes my team has put together as we look for a tool to make timeline visualizations of the roadmap:
* We don't need complexity, most needs for roadmap planning and execution are currently served by ZenHub+GitHub
* A basic timeline view of the roadmap would allow us to spot overloaded development cycles with a glance. 
* Child phases within epics (gantt style) could further improve resource planning
* Drag-n-drop editing of assigned dates would make for easy flow of editing (move epic horizontally across timeline to re-assign dates)
* Template - we have the same phases inside each major roadmap item: planning development, testing, documentation, etc, etc. A perfect world would allow us to "create new epic from template" with child phases pre-populated. (bonus points if those child phases have default timespans)

This is by no means a list of demands, just some notes we put together after assessing where we have holes in our current toolset.

**Comment by Noah-Huppert** [comment]
I would be super interested in this feature. ZenHub is awesome and this is just about the only thing missing in my opinion.

**Comment by thisisfranciswu** [comment]
👍

**Comment by rpbaguio** [comment]
👍

**Comment by DanielePucci** [comment]
👍

**Comment by TrevorSayre** [comment]
Don't respond with a +1 or thumbs up. Add a thumbs up reaction to the original post. This is how you help quantify interest in a feature. By simply responding, you aren't improving the interest metrics, only spamming the issue followers who may choose to ignore the issue due to spam.

**Comment by ArmorDarks** [comment]
I wonder, are there any plans to implement this feature in nearby future? There were no updates regarding this for 2 years... wow...

**Comment by azenMatt** [comment]
Hey @ArmorDarks 

No firm timelines on implementing this at the moment. It is on the roadmap of what ZenHub should be able to do in the future, but we don't have an implementation timeframe at this point

**Comment by Noah-Huppert** [comment]
If an API were provided for issue dependencies ([ZenHubIO/API#58](https://github.com/ZenHubIO/API/issues/53)) then someone might be able to make Gantt chart with [Google Charts Gantt Charts](https://developers.google.com/chart/interactive/docs/gallery/ganttchart).

**Comment by Noah-Huppert** [comment]
I have documented this undocumented API endpoint in my [GitHub Gantt project reamde](https://github.com/noah-huppert/gh-gantt#dependences).  

I have written the code to retrieve a repo's GitHub issues and query the unofficial ZenHub API endpoint  for its dependencies. The project provides an API endpoint to get all issues and their dependencies at `/api/issues`.  

I got tripped up in creating the actual Gantt chart in HTML. At this point I think Gantt charts are low priority for ZenHub. If anyone would like to help me create this ZenHub gantt chart generator tool that would be awesome.

**Comment by Noah-Huppert** [comment]
I'm not quite sure. I found out about this endpoint by navigating to zenhub.com and opening the network inspector in browser debug tools. I would do the same and then create a dependency and see what API call it makes. 

Good news though, it looks like after a long break, I will be completing this GH Gantt project.

**Comment by ljm22** [comment]
Hey, @azenMatt are you guys giving @Noah-Huppert any support on this? It's a good extension...

**Comment by Zhuinden** [comment]
That Gantt chart extension looks very interesting. Double nice if it supports "blocking issues" across repositories (like what Zenhub is doing).

**Comment by kendramoroz** [comment]
Hey everyone! This repo is now sunset 🌆 - We've migrated discussion on this topic in our new portal, here: https://portal.productboard.com/zenhub/c/45-view-a-timeline-gantt-style-chart-for-issues 🚀
