### ISSUE TITLE
Comments link in modal

### ISSUE THREAD

**Issue by hadrienl** [ZenHubIO/support#309]
Hi,

When an issue is opened in a modal, then the comments link (right click on a comment date) are not good. They are the current page url with the comment anchor. And the current page is not often the modaled issue.

![capture d ecran 2015-07-15 10 35 39](https://cloud.githubusercontent.com/assets/225382/8694204/9161a2da-2add-11e5-92b4-e9e9688c88b7.png)

**Comment by azenMatt** [comment]
Hi @hadrienl - this is a known issue with how we are generating these URL's 

A fix is in the pipeline

**Comment by hadrienl** [comment]
:+1:

**Comment by azenMatt** [comment]
@hadrienl - 2.5.26 just hit the Chrome store and solves this issue! :smile:

**Comment by hadrienl** [comment]
Ty ;)
