### ISSUE TITLE
Mass assign issues to a milestone

### ISSUE THREAD

**Issue by willrax** [ZenHubIO/support#310]
It would be good to be able to select multiple issues at a time and change attributes on them in one go. Some examples i can think of:

- Milestone
- Move to a new column
- Adding a flag
- Assigning a user.

**Comment by daemonsy** [comment]
:+1: Also to hijack this, :stuck_out_tongue: ,if you select a milestone on the Burndown chart and reload the chart, it might show another milestone because the state of the selector is not reflected on the URL.

**Comment by aupright** [comment]
Hey @willrax thanks for the suggestion! We've had a few other users reach out with a similar request to mass/bulk update issues from the board view. To try and keep everything centralized in one place, I'm going to move our discussion here over to https://github.com/ZenHubIO/support/issues/118. I'd love it if you could add a +1 and any other requirements that you might have in that issue there!

Thanks again for the suggestion :beers:

**Comment by willrax** [comment]
Great. Thanks @aupright just +1 it.
