### ISSUE TITLE
Fail to sign in ZenHub.

### ISSUE THREAD

**Issue by slajax** [ZenHubIO/support#311]
Currently having an issue where the boards would not load, so I tried to log out and login back in and I simple get the message:

`Fail to sign in ZenHub.`

Looks to be an issue with the oauth process. Can't use any boards. Tested on multiple computers.

**Comment by slajax** [comment]
Issue is fixed now.

**Comment by paigepaquette** [comment]
Hi @slajax. As a follow-up to your issue,  we looked into your account and saw that you had exceeded the API rate limit, rendering you unable to log in to ZenHub. You were then able to log in again when the limit was resolved.  We're looking into a workaround to help prevent this from happening, but for now, waiting a short while before logging in again should work.  Let us know if you have any other questions or concerns!

**Comment by slajax** [comment]
Hi @paigepaquette 

Thanks for the update. I just came in for the day and the issue is re-occurring so I'm reopening for further clarification.

What seems strange about the rate limit answer is that I actually just came into the office for the day and haven't done anything or any activity to GH since last night. I'm trying to think of what automated processes I have in place that might be consuming the API such as our docker build, but those are all things that are only triggered if code is pushed.

Can you take another look at my account today and see if this is happening again? If so can you provide me with the rate limit error message you get back from github? 

I would expect if I hit my limit, for everything to stop working, but I think it's just ZH right now so I'm a bit confused why this keeps happening all the sudden as of yesterday. It makes ZH rather useless for me and seemed to start suddenly.

**Comment by slajax** [comment]
Could the fact that I am using it to manage 25 repos mean I'm consuming API requests significantly faster then expected?

**Comment by paigepaquette** [comment]
Thanks for reaching out, @slajax . To answer your question: 

>Could the fact that I am using it to manage 25 repos mean I'm consuming API requests significantly faster then expected?

Correct. On a quick calculation, if you have merged ~20 repositories into one Multi-Repo Board, the rate limit will be reached within 15-20 minutes. This is a likely reason why you're reaching the rate limit shortly after you begin working. 

> If so can you provide me with the rate limit error message you get back from github?

Sure. Here's the message on our end: 

`{"message":"API rate limit exceeded for slajax.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}`

We're currently looking into a fix that would reduce the usage of GitHub tokens, which should help mitigate the issue. Hope this helps!

**Comment by slajax** [comment]
Yeah I've confirmed on my end that the rate limit resets then within 15-20 minutes I've hit the rate limit again. For now I'll try to reduce the facets in the search to preserve rate limits and get around this, but as soon as you have a potential fix for the reduction, let me know and I'll test.

Feels good to be a `power user`!

**Comment by mattyjones** [comment]
@paigepaquette As a followup with a use case and a solution.

## Use Case
I have a total of ~170 repos.  I will hit the rate limit very quickly if I put these on one board.  The big thing for me is that many times I could care less if the board gets updated only once every 5 minutes, as I am an Open Source project.  I may only work on it for a few hours a week.

## Solution
Lets start simple.  Knowing how the GH api works, how about in the Account Management interface there is a box for a number.  This would correspond to the check rate for all my repos.  Keeping it with how you guys do your updates, we can use seconds.  I will set mine initially to 3600, which is every 5 minutes.  Then on the backend you would have a rolling job that checks each repo in a board every 3600s.

If we bring it more into how other people may use it. You could have a button that will force a refresh of all repos, with the understanding this may take a few seconds if you have a large amount of repos.

In a perfect world the you would be able to poll a repo for changes and then only refresh when needed.  This may even be what you do know but this method will still hit the rate limits that GH sets.

While not an ideal situation this would at least move some of the burden of rate limits that are out of your control to the user and give them an option as to how they want to deal with it.

I have been hacking on the GH api for a while managing nearly 200+ repos in an automated fashion so i am aware of the challenges involved but there is a solution to this.  It may not be the solution we deserve, but it is the solution we need.

**Comment by slajax** [comment]
@mattyjones' proposed solution would certainly provide a welcome band aid for me over the short term. For longer term it might make sense to allow someone to look to see if the rate limit can be extended for power users with multiple tokens or something.

**Comment by mattyjones** [comment]
@slajax The thought of using multiple tokens brings an interesting point into the mix. GH has a convention known as a [machine user](https://developer.github.com/guides/managing-deploy-keys/#machine-users) for use with automated accounts. If things like this become an issue you and the rest of the automated world can start pinging github to see if they can remove or at least increase the rate limit for these types of accounts. I use a machine user for my build&release stuff as a way to remove the need for individuals to have write access everywhere or using my personal creds to manage builds.

They would need additional protections in place to prevent abuse but if the request was coming from an approved app, such as zenhub, then they would at least know what to expect.  As I said above this is lee a zenhub issue and more a GH issue, one I have been fighting with for quite some time as I have hit the rate limit a few time when do massive org-wide automated builds with Codeship.

**Comment by slajax** [comment]
@paigepaquette can we please reopen this? It continues to be a problem and now not only affects our ability to use ZH it also makes it so we can't leverage our accounts to do any other interactions with GH because ZH has saturated the rate limit so quickly and consistently.

**Comment by meinharrd** [comment]
please reopen, this is an issue for us, too (28 repos)
