### ISSUE TITLE
Automatically subscribe to an issue when you +1

### ISSUE THREAD

**Issue by nesl247** [ZenHubIO/support#312]
When you +1 an issue, I would expect to be subscribed to it so you can track it. Unsubscribing from an issue should not remove the +1 though.

**Comment by aupright** [comment]
Hey @nesl247 - great suggestion! At the risk of ruffling feathers by automatically subscribing people, perhaps we could offer this as an option when a user +1's a comment in a repo that they aren't currently subscribed to. I'll leave this one open in the discussion pipeline to see if we can get some more feedback and +1's on the different options here.

As a quick (but relevant) side note, we're also going live with a Slack integration soon (https://github.com/ZenHubIO/support/issues/119) that will allow users to track things like +1's, issue movements, etc. in a channel within Slack. In addition to subscribing to a repo, this will also be a great way for you and your team to keep track of different issues and comment's that you +1.

**Comment by azenMatt** [comment]
We have removed the +1s today in favour of the GitHub reactions so this will no longer be possible!
