### ISSUE TITLE
Enable reassignment of Admin role on the Account Manager

### ISSUE THREAD

**Issue by robertoandrade** [ZenHubIO/support#314]
When I signed up for ZenHub for one of my organizations in Github, I was made into the Admin for that org from the ZenHub account management perspective: https://dashboard.zenhub.io/

Is there a way I could change the role to another member of the team? I see you can change the billing email but I don't think that has any effect, does it?

Additionally, it'd be nice if I could add more than one admin if that's a possibility.

**Comment by azenMatt** [comment]
Hi @robertoandrade - you can add additional admins to the account via the user tab, here: 

![image](https://cloud.githubusercontent.com/assets/7584089/8782737/4afcb4ea-2ecc-11e5-9457-b08ecc5f4074.png)

You are right, the billing email is separate, this just allows you to pick which email your monthly receipt will be sent to. By default, this is the first admin.

**Comment by azenMatt** [comment]
Hi @kevwilde - this is still working when I check. 

Would you be able to email support @ zenhub.com with a screenshot of what you see and we can get this fixed for you. 

Thanks,
Matt
