### ISSUE TITLE
Don't clear the switch repository search field when results have loaded

### ISSUE THREAD

**Issue by toddmedema** [ZenHubIO/support#315]
It's very annoying to press F to /quickly/ switch repositories, start typing....and then, a few seconds later, have what I typed disappear. Would be much better to just not erase it, and immediately narrow down the results based on what's already in the search field

**Comment by azenMatt** [comment]
Hi @toddmedema - I 100% agree! 

A fix is in the queue for this one

**Comment by azenMatt** [comment]
Hi @toddmedema - fixed in v2.4.1

It will now keep the text and auto filter when the contents are ready. 

It could still be faster... and we will keep working to make it so :smile:

**Comment by toddmedema** [comment]
Thank you!
