### ISSUE TITLE
View merged issues from repositories in multiple organizations

### ISSUE THREAD

**Issue by lbergelson** [ZenHubIO/support#316]
Is there any way to merge issues across repos from different organizations?  We have tickets that cross organizational lines and it would be nice to track those together.

**Comment by aupright** [comment]
Hey @lbergelson thanks for reaching out! Although we don't support that functionality right now, it is something that we're very interested in taking a closer look at going forward. As we already have a very similar open issue for this feature (see https://github.com/ZenHubIO/support/issues/219), it would be great if you could add your +1 there :beers:
