### ISSUE TITLE
Tracking comments and comment resolution in pull requests

### ISSUE THREAD

**Issue by lbergelson** [ZenHubIO/support#317]
This might be out of scope, but we've been looking for a tool which will help our code reviews.  We make comments on pull requests, but there's no easy way to track if those comments have been addressed or not.  When a pull request is rebased or more commits are added comments are become hidden and hard to review.  Is tracking pull request comments something that zenhub does/could support?

**Comment by azenMatt** [comment]
Hi @lbergelson - we are currently focused on helping teams increase their productivity through improved collaboration - but our ethos has always been to help solve developer pain points :smile: so I see no reason ZenHub couldn't do this! 

Adding this one into the backlog for community vote on how useful this would be to other teams

**Comment by gordol** [comment]
+1

**Comment by benjamincharity** [comment]
@lbergelson in the meantime I've been using the chrome extension github-with-a-cape. Among other tweaks, you can set it to not collapse outdated comments: https://github.com/NicoSantangelo/github-with-a-cape#show-outdated-diff-comments-by-default

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
