### ISSUE TITLE
Custom estimate of 0.5 value not being saved

### ISSUE THREAD

**Issue by vsinghkpcc** [ZenHubIO/support#318]
Trying to assign 0.5 as an estimate value, the value is seemingly set. 

![screen shot 2015-07-23 at 4 35 21 pm](https://cloud.githubusercontent.com/assets/13337277/8864631/02d858d8-3159-11e5-8535-2bf7e127606a.png)
![screen shot 2015-07-23 at 4 35 31 pm](https://cloud.githubusercontent.com/assets/13337277/8864636/0aede2c2-3159-11e5-8587-a3247870b88d.png)

However, after closing and then re-opening the issue edit view, the estimate value has been cleared.

![screen shot 2015-07-23 at 4 35 45 pm](https://cloud.githubusercontent.com/assets/13337277/8864638/1ed75642-3159-11e5-887d-4a31b3fb9e92.png)
 
I tested with other, natural numbers and it does seem to store those. Is 0.5 not allowed as a value? 

IMHO It's a seemingly common agile point value - at least with the teams I've worked with. It would be nice, if this wasn't a bug, to support having 0.5 as an accepted value.

**Comment by azenMatt** [comment]
Thanks @vsinghkpcc - this is a bug, we are looking at updates so that you can use point values!

**Comment by azenMatt** [comment]
Hi @vsinghkpcc - this has just gone live in version 2.5.5 :smile:
