### ISSUE TITLE
Closed issues not showing up in the closed pipeline on the board

### ISSUE THREAD

**Issue by twangboy** [ZenHubIO/support#320]
Here's my board:
https://github.com/saltstack/zh#boards?repos=37135680,1390248&milestone=Be%201-2015-08-04T05:59:00Z&assignee=twangboy&search=

Here's the closed issues:
https://github.com/saltstack/salt/issues/25437
https://github.com/saltstack/salt/issues/25144 (this one is the only one that shows up)
https://github.com/saltstack/salt/issues/25351
https://github.com/saltstack/salt/issues/25532

**Comment by azenMatt** [comment]
Thanks @twangboy - we are still investigating this one

it is a top priority for us!

**Comment by twangboy** [comment]
@azenMatt It looks look the last update you pushed fixed it. I had to go through all my issues (I have a lot of issues) and edit the labels to get them to show up correctly... but I think it's fixed. You can probably close this issue.

**Comment by azenMatt** [comment]
Thats great news 

Please let me know if you see any problems in the future!
