### ISSUE TITLE
Opera Plugin

### ISSUE THREAD

**Issue by endophage** [ZenHubIO/support#321]
Chrome on Linux leaks processes and eats RAM to the point my system becomes unusable. I've been forced to switch to Opera which has turned out to be awesome.

An Opera plugin would be great as most of my team is on Linux and we'd love to be able to use Zenhub without necessarily needing to use Chrome.

**Comment by aupright** [comment]
Hey @endophage thanks for the suggestion!

Multi-browser support (including Opera) is still a top priority for us moving forward—in fact, we're hoping to release a few new updates very soon on some of the work that we've been doing on a stand alone web app. As we're not quite ready to go live with the details just yet, I'll keep this issues open in our community backlog and reach out again when we're ready with more info!

**Comment by azenMatt** [comment]
Hi @endophage - I have heard success stories from users who have installed ZenHub Chrome via this Opera plugin - https://addons.opera.com/en/extensions/details/download-chrome-extension-9/

I haven't had much chance to give this a full test myself, but could be worth trying?

**Comment by malkomich** [comment]
There is even another option:

http://www.crx4chrome.com/

Through this site you can download the Chrome extension files, and opening them with Opera you can install it. It seems the extensions keep updated.

I hope it helps :smiley:

**Comment by shwetank** [comment]
@azenMatt I'm PM for extensions in Opera. Opera shares the same chromium extensions architecture as Chrome, so the Zenhub extension should work fine in Opera too. 

Would love your extension to be submitted to [addons.opera.com](https://addons.opera.com) .  You can even submit it as a .crx file (like chrome). We'd be happy to feature it as a recommended extension.

**Comment by azenMatt** [comment]
Hi @shwetank - that would be great. Would you be able to send me an email - matt at zenhub.com and I can follow up once we have submitted?

**Comment by shwetank** [comment]
@azenMatt Sure 👍

**Comment by tmthyjames** [comment]
+1 for opera support.

**Comment by tmthyjames** [comment]
I got this working in Opera by following the directions [here](https://addons.opera.com/en/extensions/details/download-chrome-extension-9/)

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue now that the [web app](https://app.zenhub.com) is live and we're focused on improving core experiences for Boards and Reports. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
