### ISSUE TITLE
ZenHub Dashboard displays: `You are not part of any organizations.`

### ISSUE THREAD

**Issue by GeertHauwaerts** [ZenHubIO/support#322]
See: #207 

I have the same problem, when going to the ZenHub Dashboard, I receive the `You are not part of any organizations.` message.

I have already revoked all the access, authorized it again; all the permissions on `Personal Settings :: Applications` appear to be configured correctly.

![zenhub_access](https://cloud.githubusercontent.com/assets/7902071/8939491/00206990-3565-11e5-91ef-11a262d64a30.png)

* My account has ZenHub fully authorized
* Irssi organization has no restrictions on external tools (large opensource project)
* Thinfactory organization has ZenHub fully authorized
* My account is admin of both the Irssi & Thinfactory organizations

Do you guys have any idea on how to resolve the issue?

PS: I tried the auth/revoke/auth method on 2 different workstations.

**Comment by aupright** [comment]
Thanks for reaching out here @GeertHauwaerts, I'm sorry that you're not able to see your organizations in the payments dashboard. One approach I'll have our team try is to manually re-trigger our org-scraper for your account to try and pull these organizations into the dashboard. I've issued this up internally, and will follow up with you here as soon as we've run the script. Thanks for your patience!

**Comment by GeertHauwaerts** [comment]
It appears the script has been executed; I am now able to see the ZenHub Dashboard.

**Comment by aupright** [comment]
Great to hear @GeertHauwaert - thanks for following up!

**Comment by seanwhe** [comment]
Hi There. I am experiencing the same problem. When I look at Authorized Applications within my Organization all looks good. But when I visit the ZenHub Dashboard I get "You are not part of any organizations."

Any advise?

**Comment by Cassidy-Robertson** [comment]
Hi @seanwhe, as an initial attempt at troubleshooting here, could you temporarily revoke access for ZenHub then re-allow? The permissions cache may need to be triggered. If you're still having problems, could you send a screen shot of your dashboard with the dev console open to support@zenhub.io or reply here?

**Comment by diminator** [comment]
@Cassidy-Robertson, @aupright 
Same problem here

![image](https://cloud.githubusercontent.com/assets/6178597/12416789/c7c19eac-bea3-11e5-8e5b-86180c47efb2.png)

I am an admin for ascribe, and allowed for access:

![image](https://cloud.githubusercontent.com/assets/6178597/12416811/e5bc346c-bea3-11e5-8676-ec94a631203a.png)

**Comment by diminator** [comment]
> I am an admin for ascribe, and allowed for access:

also tried revoking and re-allowing access, no luck

**Comment by avido** [comment]
Same here... revoked.. retried .. no results

**Comment by azenMatt** [comment]
Hi @avido - do you get any errors in the console when you try and access the board within the organization that doesn't appear on the dashboard?

**Comment by pakistan** [comment]
@azenMatt I am having the same issue. Has a fix for this come out yet? I can access the board but do not see the organization in my dashboard.

**Comment by ran729** [comment]
Same issue here... can access board but not part of any organization... what to do ?

**Comment by kendramoroz** [comment]
Hey @pakistan and @ran729 the Dashboard won't display personal repositories that are setup that aren't in a GitHub organization! Since personal plans on GitHub are actually free for users using ZenHub, you don't need to worry about accessing the billing or user portal on the dashboard :).

**Comment by ran729** [comment]
@kendramoroz  thanks for the reply, but i want to integrate my dashbaord with slack, and from your guide it seems i need to access the dashboard for some configuration. 
https://www.zenhub.com/blog/add-to-slack/ 
so what should i do ?

**Comment by diminator** [comment]
>
> so what should i do ?
>
maybe put me in BCC? ;-)

**Comment by ran729** [comment]
@diminator what do you mean ?

**Comment by diminator** [comment]
ooh, didnt notice this was an active thread 
couldnt remember the issue as it is quite old

**Comment by kendramoroz** [comment]
@diminator Looks like you're participating in the thread from a previous convo which is why you're getting the emails! Sorry about the distraction here—I'd recommend the mute/removing yourself from the participation section. Should be all squared up after this reply. 

@ran729 The integration is only available currently for organizations—this is something we have on our radar to open up, but unfortunately it can currently not be set up for personal accounts. Feel free to get in touch at support@zenhub.com with anything else we can help with :)

**Comment by ran729** [comment]
can they help me set up slack integration ?  :)
