### ISSUE TITLE
Rapid Repo Switcher is no longer rapid.

### ISSUE THREAD

**Issue by jfhamlin** [ZenHubIO/support#323]
__Expected behavior:__ While viewing a repository of an organization (or user) with many repositories, after typing `f`, a list of the current organization's (or user's) repositories immediately appears in the "Switch Repository" view.

__Actual behavior:__ While viewing a repository of an organization (or user) with many repositories, after typing `f`, the text "Loading your repositories" appears for several seconds before a list of the current organization's (or user's) repositories appears in the "Switch Repository" view.

This behavior means that it's often faster for me simply to type the repo name in the search bar and rely on the web browser's autocomplete feature.

As far as I can tell, this is a regression. I recall the repo switcher performing much better a couple of weeks ago. I'm guessing it used to be prefetching the repo list.

**Comment by azenMatt** [comment]
Hi @jfhamlin - we made this switch recently to try and limit the API calls we needed to make. 

We just released an update in 2.4.1 that saves the text you type in whilst we are fetching the repo switcher - so you can start to filter before the fetch is completed. 

Meanwhile we will keep working to improve the speed of both the repo switcher and the general board load performance - it is a top priority for us
