### ISSUE TITLE
Combine multiple repository milestone

### ISSUE THREAD

**Issue by zippeurfou** [ZenHubIO/support#325]
Hi,

In our team we are using multiple repositories with the same milestone name. We would like to be able to see them together in one board.
Is that possible?

Best,

**Comment by andycleff** [comment]
Another approach would be to allow "Multi-select" functionality for the milestone selector, similar to how the pipeline selector works now.

This approach might be less effort to implement, as the milestone field is not just simply a text string, like it is for the labels field. Milestone has date meta info as well.

Multiselect list FTW!!!!

**Comment by azenMatt** [comment]
Hi @zippeurfou @andycleff 

Our current method is to group together milestones that have the same variables - so if you name milestones the same thing and give them the same end date - we will show all of them as part of the issues returned in the multi-repo milestone. 

Multiselect is another good approach to this! 

We have been looking at how to make these easier for everyone so we will keep making improvements here!
