### ISSUE TITLE
+1 button on new global Pull requests and Issues Github pages

### ISSUE THREAD

**Issue by crazydog115** [ZenHubIO/support#326]
Hi there! The following pages:
https://github.com/pulls
https://github.com/issues

Were recently added to Github. Would be nice to have +1 buttons there!

**Comment by azenMatt** [comment]
Thanks @crazydog115 - we will look into it!

**Comment by azenMatt** [comment]
We depreciated the +1 functionality in favour of GitHub reactions today, we will leave those spaces to the new reactions :smile:
