### ISSUE TITLE
Ability to create 'sub-task' issues

### ISSUE THREAD

**Issue by aupright** [ZenHubIO/support#327]
Issuing this up as a question for the community:

A few users have reached out recently requesting the ability to create a new class of 'sub-task' issues and link them with other existing issues on the board. The goal with this functionality would be to provide a more granular view of a team's projects and more accountability in terms of what part of the project individuals are responsible for. 

Is this a piece of functionality that you and your team would find useful, or do you prefer the current approach of using linkable lists (with markdown) inside of issues? Let us know with a +1 or by leaving a comment below :beers:

**Comment by chrslwrnc** [comment]
Linkable lists are great, but they need to be kept up to date manually which can be hard to manage. The hierarchy you get from actual 'sub-tasks' is really useful! Coming from using Jira this a feature that I really miss!

**Comment by mono0926** [comment]
+1

**Comment by KalleDK** [comment]
+1

**Comment by cristinasantamarina** [comment]
PLEASE!

**Comment by andycleff** [comment]
Epics feature does this.

**Comment by azenMatt** [comment]
good point @andycleff 😄 

closing this in favour of using Epics for Subtasks
