### ISSUE TITLE
Github keyboard shortcuts don't work on the boards page

### ISSUE THREAD

**Issue by shawninder** [ZenHubIO/support#328]
Repro:

- Go to your favorite repo
- Go to _boards_ page
- Use a GitHub keyboard shortcut (like `g+i`)
- *Expected* works (goes to _issues_ page in the case of `g+i`)
- *Observed* fails (does nothing)

**Comment by aaronwest** [comment]
Yep, seeing the same thing on Chrome 44.0.2403.107 on Macbook Pro.

**Comment by azenMatt** [comment]
We are looking at a fix for this one :)

**Comment by toddmedema** [comment]
Looks like a duplicate of https://github.com/ZenHubIO/support/issues/313

**Comment by azenMatt** [comment]
Yes, this one is now also live in 2.5.16!

**Comment by aaronwest** [comment]
Working great. Thank you ZenHub team!
