### ISSUE TITLE
Close and Comment does not generate Slack webhook notification

### ISSUE THREAD

**Issue by aaronwest** [ZenHubIO/support#329]
A bit earlier I clicked on an issue in the `In Progress` pipeline and wrote a comment. Then I clicked the Close issue button. The issue was marked closed in the normal GitHub Issues screen and it was moved to the `Closed` pipeline in the ZenHub board.

But no notification was generated to Slack via the new webhook integration. By contrast, when I moved the same issue from ToDo to In Progress (only a few minutes before the close) a notification *was* generated to Slack.

**Comment by azenMatt** [comment]
Hi @aaronwest this one is by design (it's not a bug, it's a feature!) 

The reason being is that we didn't want to duplicate GitHub slack events and cause unnecessary clutter in your slack channels. 

Working under the assumption that most team who wanted to use slack integration would also have it set up for GitHub:

![image](https://cloud.githubusercontent.com/assets/7584089/9012199/dd8d8584-3767-11e5-8d5f-30cbbb399a7f.png)

**Comment by aaronwest** [comment]
Thanks @azenMatt. Your explanation makes sense and is probably okay for most teams. Our process has us using two different channels, one for `commits` and one for issue status changes. The `commits` channel is for engineers only since most of what gets posted is confusing to everyone else in the company. So we created a separate channel for notifications on new issues, issues moving from one pipeline to another, etc.

Given this implementation and how ZenHub works, our `commits` channel will receive the issue closed notification while all other status changes will appear in `git-status`. I'd like stakeholders to know (via Slack) when things are closed but they don't want to be exposed to all the other stuff happening in `commits`.

Anyhow, just wanted you to have context to our use case.

**Comment by azenMatt** [comment]
Thanks for the context - I can see how this would be useful! 

I took a look at the existing GitHub notifications, and you can replicate the behaviour that you want with a combination of ZenHub and GitHub integrations. 

The screenshot below is the GitHub slack integration set up screen, if you turn off all notifications apart from create / close issue you can get these messages sent to the status change channel and leave all the commits to the engineers :smile: 

I hope this helps! 

![image](https://cloud.githubusercontent.com/assets/7584089/9014252/1617b5ba-3776-11e5-996c-c15be0f6c034.png)

**Comment by aaronwest** [comment]
Thanks @azenMatt! I've set up what you suggest and we'll see how it goes. Not a perfect solution but might be workable, which is good enough for me. Thank you again.
