### ISSUE TITLE
Repo switcher should work on private repos even if trial period is over

### ISSUE THREAD

**Issue by shawninder** [ZenHubIO/support#330]
The free version only works on private repos. I think the repo switcher should work everywhere, mostly because you can want to switch from a private repo to a public repo, but then that features isn't available on the public repo...

Repro steps:
1. Log into a free account (trial period expired)
2. Go to a public repo
3. Do stuff
4. Click the repo switcher button (repo switcher opens)
5. Select a private repo
6. Observe that it works
7. Now click the repo switcher button again
Expected: Repo switcher should open again
Observed: Error message because trial period is over, which feels strange because the repo switcher DID work in step 4

**Comment by azenMatt** [comment]
Thank you for the feedback @shawninder - for the moment we are going to keep with the existing structure of having paid features within private repos. 

If you need some help getting set up with a paid plan - or would like some help convincing the rest of your team to switch to ZenHub so you can use it on private repos please send an email to support@zenhub.io and we will see what we can do!
