### ISSUE TITLE
Repo switcher should be available on github.com

### ISSUE THREAD

**Issue by toddmedema** [ZenHubIO/support#332]
I want to be able to go to my repos as fast as possible - and right now, I have to accomplish that by clicking on a random repo on the side (so that I'm on a repo page that has the repo switcher) - only once the second page has loaded can I start searching. Would be MUCH faster if the switcher was available on the homepage!

**Comment by azenMatt** [comment]
Good idea @toddmedema ! 

Added to the backlog :smile:
