### ISSUE TITLE
Ability to collapse a column visually.

### ISSUE THREAD

**Issue by CreativeNotice** [ZenHubIO/support#336]
A simple click on the column header or an icon in the column header would work.
The attached image shows what KanbanTool.com does and it's been quite handy for my team.
![screenshot_081115_115235_am](https://cloud.githubusercontent.com/assets/168185/9203926/ac65b920-401f-11e5-921c-a755897eaa2d.jpg)

**Comment by azenMatt** [comment]
Hi @CreativeNotice - this one is on our 'To-Do' list! 

It is currently being tracked in #163 - so please feel free to add a +1 there!

**Comment by CreativeNotice** [comment]
Great. I ended up +1ing #122 since it appears to be the original issue.
