### ISSUE TITLE
Ability to create swim lanes that span columns.

### ISSUE THREAD

**Issue by CreativeNotice** [ZenHubIO/support#337]
Swim lanes are an essential part of the kanban way of thinking. They allow one to subdivide columns vertically. I've seen people use them to visually manage everything from individual developers to milestones to epics.

**Comment by azenMatt** [comment]
:+1: @CreativeNotice 

This would be very useful! adding into the backlog pipeline for more community feedback to see if others would also find this helpful

**Comment by lavanut** [comment]
+1

**Comment by kennethkoontz** [comment]
Useful! As an example usecase -- "who's working on what". But could see other segments as well.

**Comment by apatrida** [comment]
+1

**Comment by tlaukkanen** [comment]
+1 for better epic support, now it feels a hacky to do it with labels or milestones

**Comment by Anvil102** [comment]
From my point of view, a key part of this is that a swim lanes should support a few critical features:

0. They can span an arbitrary set of columns with arbitrary starting and ending points.
0. (This is the tougher part) They can support sub columns / pipes within them. 
  1. This means that a swim lane can have a set of pipeline statuses that don't exist as "global" columns on the broader board. Example: If the global board has "ToDo, In Progress, Done" the swim lane would have all these statuses, but could also only contain within itself "Ready for QA, In QA." 
0. Swim lanes can be moved to any vertical position along the height of the board, and ordered in any vertical arrangement relative to themselves and the larger board.

**Comment by robneville73** [comment]
Would be critical for us and frankly this is what's holding me back from implementing zenhub in my org. Our team is small and wears many hats (R&D, project implementation, QA & support). They all have to perform all functions so we use a manual kanban board to split work into swimlanes by category and use swimlane limits to make sure that our efforts are allocated in appropriate proportions to all of these areas at any one time.

**Comment by leandrodvd** [comment]
I would like to have lanes based on labels. We use labels here to separe items by subteams and we keep ZenHub board in a 49 inch TV, would be good to have one lane for each team (label) so we can clearly separate it and make it visible. Without that we would need two TVs (no way) to separate it in two boards.

**Comment by JIMENOFONSECA** [comment]
This is the best functionality one can ask for Zenhub right now.

**Comment by bbcollinsworth** [comment]
Was just looking at ZenHub since we want to try a new digital scrum service, and GitHub/Slack integration is great.

But we need swim lanes, so we'll have to go with another product. If ZenHub had these, we'd go with it instead!

**Comment by kokosta** [comment]
Lack of swimlanes is the only reason we are not able to use ZenHub. When could we expect a decision on this?

**Comment by ioreper** [comment]
Any idea of when swimlanes may arrive to ZenHub?

**Comment by alexmitc** [comment]
+1

**Comment by sderrico** [comment]
+1

**Comment by daniellemoorhead** [comment]
+1

**Comment by schneiderderek** [comment]
+1

**Comment by kendramoroz** [comment]
👋 this repo is now archived. Feel free to add your feedback, votes, and comments to our new feedback portal here: https://portal.productboard.com/zenhub
