### ISSUE TITLE
Easy to lose changes in modal

### ISSUE THREAD

**Issue by mjonas87** [ZenHubIO/support#338]
Due to the proximity of the `esc` key to the `backtick` key, it is **super** easy to accidentally press `esc` and close the issue modal. As long as my next action is to reopen the modal, I don't lose any work, but I have lost work in the past. Moreover, though, its an annoyance. I feel like a confirmation prompt would be best where `esc` would cancel the closing of the modal and `enter` would confirm it. That way `esc` + `esc` would keep the modal open, and `esc` + `enter` would close it.

**Comment by snario** [comment]
+1

**Comment by azenMatt** [comment]
Hi @mjonas87 - we have discussed this one internally at length - and have decided that we want to optimize for reducing the number of clicks / interactions. Given that you will not lose any work as long as you go back into the issue we are going to stay with the current flow.

At least, that is, until we get to the point of rolling out a settings page to let users opt into ESC to cancel - then we can give the best of both worlds :grinning:

**Comment by mjonas87** [comment]
@azenMatt Just (re)discovered how/when changes are lost. Creating a ticket is fine. However, when editing a ticket, all changes are lost if you accidentally press `ESC`

**Comment by azenMatt** [comment]
so far I am unable to replicate this, if i: 

1) Go to a Board 
2) Select an issue 
3) Enter text into the comment box but do not press 'comment' or 'close and comment'
4) Press ESC
5) Re-select the issue 

Result = My text is still present in the comment box. 

Am I missing any steps to reproduce?

**Comment by mjonas87** [comment]
Right, it persists for the initial comment, but not any after that.
