### ISSUE TITLE
Show sum of estimations in pipeline

### ISSUE THREAD

**Issue by matejkastner** [ZenHubIO/support#339]
Hallo,
would it be possible to show sum of estimates on top of pipeline?

Like now you show how many issues is in pipeline, it would be great to show also estimation summary in round next to it.

Thx a lot :)

**Comment by snario** [comment]
+1

**Comment by azenMatt** [comment]
Hi @matejkastner - it's in the backlog :)

**Comment by mono0926** [comment]
+1

**Comment by sbadugu** [comment]
+1

@matejkastner Do you know when you are planning to release this feature ?

**Comment by matejkastner** [comment]
Hallo @sbadugu, no, its more question to @azenMatt since he commented https://github.com/ZenHubIO/support/issues/339#issuecomment-130887792 thats in the backlog, so one day it will be on production :)

**Comment by MarkJepson** [comment]
+1

**Comment by aneilbaboo** [comment]
+1 !

I would also ask that this feature be responsive to filters.  This allows the user to see how many points are in a particular stage of the pipeline for a particular developer and for (a) particular milestone(s).

**Comment by stevenchanin** [comment]
+1

**Comment by azenMatt** [comment]
> I would also ask that this feature be responsive to filters. This allows the user to see how many points are in a particular stage of the pipeline for a particular developer and for (a) particular milestone(s).

Agreed!

**Comment by marcdavi-es** [comment]
Woooooop. 

In sprint planning on Monday we were like "They should totally have the sum of estimates at the top of each list" then all of a sudden...

Thanks for this :)

**Comment by MarkJepson** [comment]
I've seen the release. Saving me an hour plus of work each week now. Thanks
to all in the office for getting this delivered

Mark Jepson
Consultant Business Analyst
Tel - +44 (0)151 556 6546
createthegroup.com

**Comment by azenMatt** [comment]
Thanks @marcdavi-es @MarkJepson - glad you like it!

**Comment by aneilbaboo** [comment]
Woohoo!
