### ISSUE TITLE
"not assigned" hover text does not go away sometimes

### ISSUE THREAD

**Issue by snario** [ZenHubIO/support#340]
There is a bug that makes the label never disappear

![boards_ _piinpoint_piinpoint](https://cloud.githubusercontent.com/assets/1933029/9255625/9a7fb6bc-41b8-11e5-85eb-99f08274b534.png)

**Comment by azenMatt** [comment]
Any ideas on how to replicate this @snario ? 

I am unable to trigger it here

**Comment by azenMatt** [comment]
This should be resolved with the new board code. Please let me know if you spot it again!
