### ISSUE TITLE
ZenHub+ Stylish - GitHub stylesheet

### ISSUE THREAD

**Issue by omnidan** [ZenHubIO/support#341]
Some elements that ZenHub adds just don't look like other elements on github. This has been bothering me a lot, so I [wrote a CSS stylesheet that can be installed with Stylish](https://userstyles.org/styles/117621/zenhub) that makes those elements look more like native github elements.

![https://i.imgur.com/wCUSqJE.png](https://i.imgur.com/wCUSqJE.png)
_(ZenHub+: https://userstyles.org/styles/117621/zenhub)_

**Comment by azenMatt** [comment]
very cool @omnidan :grinning: 

il leave this one open for a while so that other users can see it and add it if they wish!

**Comment by omnidan** [comment]
@azenMatt thanks a lot! Would be cool to get it merged into the extension code. I understand it might not be what you want (corporate identity, etc) - if that's the case, maybe make it an option in the settings?

**Comment by azenMatt** [comment]
Yes, it is something we have wrestled with a lot. We used to be more in-line with the GitHub styles - but this caused a lot of user confusion with what exactly was ZenHub vs GitHub. 

The idea of settings to let a user pick which style they would like to work with is an idea we have thrown around before and is currently sitting in our backlog. So yes, one day!

**Comment by Mottie** [comment]
@omnidan We have a [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark) style which includes ZenHub styling... in case you were interested :grin:
