### ISSUE TITLE
Middle-clicking board or burndown icon should open new tab

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#342]
Currently middle-clicking on either the boards or burndown icon does nothing (except in windows where the page scroll icon appears).

I would like to request that a middle click on either icon opens that page in a new tab.

This issue is **not the same** as #145!

**Comment by aupright** [comment]
Thanks for the suggestion @Mottie - it doesn't look like we've got any additional feedback from the rest of the community here, so I'm going to move this one to the `community icebox` for now to keep in mind going forward. Thanks again for the feedback - keep it coming :beers:

**Comment by Mottie** [comment]
Community icebox, or closing?

**Comment by Nowaker** [comment]
+1 for that. Pretty annoying I cannot open the board in a new tab.

**Comment by Nowaker** [comment]
This is actually so trivial to implement that I don't see a reason why "Boards" button isn't a link that points to issues#boards.

**Comment by azenMatt** [comment]
This one is (finally) fixed 😄
