### ISSUE TITLE
Mousewheel horizontal scrolling in boards

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#344]
I would like to request to make the mousewheel horizontally scroll the boards page when a pipeline doesn't have a scrollbar or is already at the scroll limit. More specifically:

* If a pipeline is at the bottom, or doesn't have a scrollbar, then moving the mousewheel down will scroll the boards right.
* If a pipeline is at the top then moving the mousewheel up will scroll the boards left.

I think it would make the boards page easier to use.

**Comment by aupright** [comment]
Thanks again for the suggestions @Mottie!

We went live with a related update in a recent version of ZenHub that we pushed out. While we'd still like to explore further improvements here, our goal is to get more feedback on our current update (changing the scroll bar width) before prioritizing any further additions! Thanks again, and keep that feedback coming :raised_hands:

**Comment by Mottie** [comment]
So, closing this suggestion because it's never going to happen?

**Comment by aupright** [comment]
Hey @Mottie,

This is still something we're open to exploring going forward—I'm just closing this one out for now until we have a chance to evaluate the impact of our most recent scrollbar changes. We'll continue trying to balance your request here along with all of the other requests from the community, and our own internal roadmap of improvements. Thanks again for all of your support and feedback :smiley:
