### ISSUE TITLE
As a developer, I want to attach a PR to an issue. 

### ISSUE THREAD

**Issue by kennethkoontz** [ZenHubIO/support#349]
Part of our process is attaching a PR to an issue in so that the PR "travels" with the issue. 

It'd be great if the PR could be merged/attached and as you are viewing the board you could see the PR's that are attached to the issues.

**Comment by kennethkoontz** [comment]
Along the same lines, a PR could automatically close attached issues when merged.

**Comment by snario** [comment]
This is default GitHub issues behaviour, just reference the issue in the PR and say 'closes #XXX' when you commit or close the PR.

**Comment by kennethkoontz** [comment]
@snario Sweet. Thanks!
