### ISSUE TITLE
Support the ability to move issues between repos

### ISSUE THREAD

**Issue by jync** [ZenHubIO/support#350]
It would be nice to be able to move issues between repos.

**Comment by aupright** [comment]
Definitely agree with you @jync! In addition to exploring this ourselves, this is also something that we're very interested in working with the GitHub team on to see if we can better support. I'd love to see a few more +1's and comments from the rest of the community here, so I'll move this into the discussion pipeline for more feedback :+1:

**Comment by iBeliever** [comment]
I'd love this as well. I develop an OS with GitHub and ZenHub, and people sometimes file bugs in the wrong repos, so I'd love to be able to move issues to the correct repository. :+1:

**Comment by codeblooded** [comment]
This is a big one. :+1:

**Comment by janajri** [comment]
+1

**Comment by ccann** [comment]
This is the only thing keeping us from using ZenHub!! +1

**Comment by gmontard** [comment]
:+1:

**Comment by azenMatt** [comment]
This is now live - via the move issue button on the bottom of the sidebar :beers:

**Comment by jdolan** [comment]
Is this feature still available? I'm unable to find it.

**Comment by kendramoroz** [comment]
@jdolan it's available in the extension only, via the sidebar of any Issue!

![image](https://user-images.githubusercontent.com/11036230/33497736-b8bf1dfe-d683-11e7-88ab-a5ee86017677.png)
