### ISSUE TITLE
Merging multiple repositories collapses pipelines across them

### ISSUE THREAD

**Issue by jync** [ZenHubIO/support#351]
If you have a repo for support issues, and use that repo to triage issues by moving them to relevant pipelines, it would be nice on the merged boards to
1. nominate which pipelines would be visible
2. keep the pipelines in each repo different rather than merge them together
3. control visibility in a board when a given pipeline is flagged to be visible in the merged board.

**Comment by aupright** [comment]
Thanks @jync - great suggestions!

>nominate which pipelines would be visible

We're actually working on a collapsing and expanding pipeline feature for ZenHub that will give teams (and individuals) more control over which pipelines they do/don't see in the boards view. Keep an eye out for this one coming soon!

>keep the pipelines in each repo different rather than merge them together

I understand the use case here, and am interested to see if some of our other users feel the same way about keeping pipelines separate in a multi-repo board. I'll move this one to the discussion pipeline to see if we can get some more feedback :+1:

**Comment by BeyondHyper** [comment]
I think this is critical in order to support large teams with various roles utilizing ZenHub as their tracking system. Merging say, multiple repos and/or coordinating with a large number of distributed teams is a large hurdle, especially if they already have set up ZenHub in a way that supports their workflow.

**Comment by JohanvdWest** [comment]
I am also especially interested in keeping the two boards the same when merging them. This would need some setup as in which order they must be shown if both repo's boards are shown, similar to setting up the merging currently.

**Comment by kendramoroz** [comment]
👋  Hey Everyone! Excited to announce that we're working on Workspaces, captured in #139 which will help with creating multiple Boards per repo :) - to keep the thread focused and updates visible in the same issue, I'm going to close this Issue but anyone still interested in this functionality can follow along at #139 for updates!
