### ISSUE TITLE
Horizontal scrollbar is ridiculously thin and hard to grasp

### ISSUE THREAD

**Issue by CarlMalartre** [ZenHubIO/support#354]
Horizontal scrollbar is ridiculously thin and hard to grasp. Collegues didnt even knew it existed and used the keyboard.

https://screenshots.scolab.com/Public/Jing/CM/2015-08-19_1056.png

**Comment by michaelburtonray** [comment]
Yeah the side scrolling is kind of weird in Windows! Most people have scroll wheels not trackpads.

**Comment by Mottie** [comment]
It is a little bit easier to see if you are using our [GitHub-Dark stylish theme](https://github.com/StylishThemes/GitHub-Dark).

![2015-08-20 10_49_02-](https://cloud.githubusercontent.com/assets/136959/9388169/79ba14ce-4729-11e5-9a1a-e88df9ebd7f2.png)

And I just opened a request to make the mousewheel scroll the boards horizontally when not inside a pipeline (#344).

**Comment by azenMatt** [comment]
Hi all - we are taking a look at what we can do to make this easier

**Comment by CarlMalartre** [comment]
"Most people have scroll wheels not trackpads."

Depends if you are sampling in a café or at an office with desktop.

**Comment by CarlMalartre** [comment]
@azenMatt Thanks!

**Comment by azenMatt** [comment]
We just put a quick fix for this live on 2.5.16 - a thicker bar. 

In the future we are going to make the scrolling easier to resolve this fully, but hopefully the thicker bar should make it easier for the short term!

**Comment by CarlMalartre** [comment]
Thanks. Its still super light and super thin. Did you test with end users if they can grab it?

**Comment by azenMatt** [comment]
We did do some user testing around the office for this one - always happy to take more feedback though! 

This was a 5px change to 8px, which we felt worked best between ease to grab without be so large as to be distracting.
