### ISSUE TITLE
Hide columns (Workflow clarification: column vs milestones)

### ISSUE THREAD

**Issue by CarlMalartre** [ZenHubIO/support#355]
We are wondering if we should be putting our backlog issues into milestones or into columns. For examples, should we have columns called ToPrioritize, HighValue, FrontBurner, Backburner, etc. or should we have milestones named like this?

When we add columns, it becomes very horizontally large. When we add milestones, it becomes confusing because we still need to add columns.

This leads me to ask if we could hide columns based on our role or on a template (Dev, Integrators, QA, etc.)

**Comment by aupright** [comment]
Hey @CarlMalartre, great question!

Based on the info that you've provided, my recommendation would be to separate these different states into different pipelines/columns. We'll be going live with a collapsing and expanding pipeline feature very soon that will make it easier for you to condense certain pipelines and focus on only those ones that are relevant to your workflow!
