### ISSUE TITLE
Create a snapshot of a burndown chart

### ISSUE THREAD

**Issue by bradical** [ZenHubIO/support#357]
If we don't finish everything in our current sprint, we'll frequently move unfinished stuff into the next sprint rather than re-creating new issues. Not sure if this is recommended, but this is what we do.

Problem is that moving them basically kills our historical burndown charts.

Am I missing something in terms of the appropriate way to close a milestone and capture that data? If not, any other ideas? Right now we literally take a screenshot of the burndown chart before we close the milestone and move unfinished stuff.

**Comment by azenMatt** [comment]
Hi @bradical - that is a great point, we will come up with a better way to keep these historical details than having to take a screenshot!

**Comment by bradical** [comment]
Thanks Matt. The way I see other systems like JIRA do this is to basically snapshot on close of milestone (or End of Sprint in their case). Anything that happens after that point will not affect the chart or the list of what was originally there and finished/unfinished.

**Comment by jessevdk** [comment]
We use the same workflow and a snapshot, or some way to track changes would be great.

**Comment by evfishr** [comment]
Our team typically kicks out a handful of issues at our code freeze, 2 days before release, and additional issues as needed at close. Would this type of snapshot potentially allow us to better track what was getting kicked out vs developed/completed? 

Our team does not use JIRA, so I'm not sure how they handle tracking this distinction.

**Comment by zeditio** [comment]
Any solution?

**Comment by kendramoroz** [comment]
@zeditio still on our radar! We'll be sure to add updates as they surface to the issue for everyone to receive :). Let us know if you have any other questions we can support in the mean time!

**Comment by releon02** [comment]
Any updates on this @kendramoroz ?

**Comment by kendramoroz** [comment]
@releon02 thanks for your patience on this one! We're in the midst of scoping out design work for how to better handle scope changes on the Burndown and handle this use case. We'll have more to share shortly :)

**Comment by marcyelhamidi** [comment]
some feedback:
Be very careful about how you handle this and do not confuse "sprint end date" with the current "milestone close functionality".

Currently, if I milestone is closed it becomes very difficult to go in and modify anything in the milestone.
This means that if a team wants a snapshot of what the sprint looks like at the end of the sprint and they have to "close" the milestone to get it, it will be very difficult to then do the next step that most teams do:  which is move items that weren't completed to the next milestone.

Seems like you have 2 choices:
1.  Add an "end milestone" functionality which creates the snapshot of the milestone, but allows you to continue modifying the work in it,  in addition to the current "Close Milestone" capabilities OR

2.  Rename the current "Close Milestone" function to "Archive Milestone" and create a new "Close Milestone" function that takes the snapshot but allows you to continue modifying

**Comment by kendramoroz** [comment]
👋 Hey all - consolidating issues for easier update/progress tracking - please subscribe to #791 to follow along progress on this type of burndown improvement!
