### ISSUE TITLE
Indicator to show number of Comments

### ISSUE THREAD

**Issue by martic** [ZenHubIO/support#358]
I'd like to see how many comments where made in the bottom corner. Like waffle.io use.
![2015-08-21_19-48-45](https://cloud.githubusercontent.com/assets/633920/9405775/0f7ee420-483e-11e5-9399-dded3de173f5.png)

**Comment by aupright** [comment]
Thanks for the suggestion @martic - I can see where this could be a useful addition! While we don't want to risk the issue cards getting too cluttered with different fields (impacting readability), I'll   move this one to our discussion pipeline to see if we can get some more feedback from the rest of the community!
