### ISSUE TITLE
Board view: de-select all but one

### ISSUE THREAD

**Issue by toddmedema** [ZenHubIO/support#359]
Using the board view, we often have 8 or more repos selected at once for team planning. While there's an option to select all, there's no option to reverse this (ie de-select all, or select just a single repo via a kind of "solo view" button). Without the ability to do the opposite of select-all, it becomes much more difficult to navigate through repo boards quickly.

**Comment by azenMatt** [comment]
Good timing @toddmedema - we just released this as part of 2.5.9 :grinning:
