### ISSUE TITLE
GitHub Enterprise support

### ISSUE THREAD

**Issue by cjnygard** [ZenHubIO/support#360]
I'd like to use ZenHub with an internal GitHub Enterprise installation.  How to configure ZenHub to work with a different github URL?

**Comment by azenMatt** [comment]
Hi @cjnygard - We offer a separate solution of ZenHub to connect with Enterprise instances. 

Please send us an email at support@zenhub.io and we can send through the required information or check out https://www.zenhub.io/enterprise for more details.
