### ISSUE TITLE
Cannot create issues in a forked repo

### ISSUE THREAD

**Issue by TomMcCluskey** [ZenHubIO/support#363]
When in a forked repo, attempting to create a new issue from Boards will result in the error "Error: the GitHub page cannot be loaded".

**Comment by aupright** [comment]
Hi @TomMcCluskey thanks for reaching out!

By default, issues are turned off for forked repos, resulting in the error that you mentioned above. To fix this, you can click on the settings button for that forked repo and ensure that the "issues" box in the "Features" section is checked! Cheers :beers:
