### ISSUE TITLE
UI Locked in Narrow container

### ISSUE THREAD

**Issue by xscheiner** [ZenHubIO/support#364]
It looks like Github have changed the structure of their html and now my boards are stuck in a narrow space. See screen shot below.
![screen shot 2015-08-28 at 09 44 24](https://cloud.githubusercontent.com/assets/1236507/9542574/db2384fc-4d69-11e5-9cda-b31cc912ee22.png)

**Comment by hurricane766** [comment]
Just found they posted the solution to Twitter. Update to 2.5.12 -> Go to chrome://extensions/ -> check off developer mode -> update extensions

**Comment by millsbt** [comment]
thanks @hurricane766 . all straightened out for me.

**Comment by xscheiner** [comment]
Mee too. Thanks.

**Comment by azenMatt** [comment]
:+1:
