### ISSUE TITLE
Closing an issue via commit message is sometimes never reflected in zenhub until manual refresh

### ISSUE THREAD

**Issue by erindotio** [ZenHubIO/support#365]
Hey guys,

This seems to be related to an overall spottiness in zenhub's ability to reflect updates to issues, etc... but sometimes when I close an issue via commit message, the issue in zenhub never reflects that until I do a manual refresh, even though the ticket is closed when I click on it from the boards view.

Other times zenhub reflects the change immediately.

Thanks

**Comment by runofthemill** [comment]
+1

**Comment by aupright** [comment]
Thanks for the feedback here @erindotio!

I've pinged the rest of the team so that we can look into what might be causing this inconsistency. I'll update this thread with anything that I hear back from the rest of the team :beers:

**Comment by rmacklin** [comment]
I've experienced something different. If I move an issue to a new column, and then close it by [merging a PR](https://github.com/blog/1506-closing-issues-via-pull-requests), the issue does not move to the Closed column (even if I refresh the page). Worse, I can manually move the issue to the closed column, and it _appears_ to work, but doesn't actually change it--if I refresh it's back in the previous column. The only way I've been able to get it "unstuck" is to manually reopen and re-close the issue (which negates the convenience gained by closing issues via PRs :disappointed:).

**Comment by anilnatha** [comment]
I've experienced this issue on the burndown charts where if I close an issue via commit message, a data point is not reflected in the burndown chart. So I have to then reopen the issue on Github, and then close the issue for the data point to be added.

This occurred for me on Zenhub Enterprise.

**Comment by aupright** [comment]
Thanks for the additional comments here @rmacklin and @anilnatha! We had pushed an update out here in #320 that reportedly solved this issue—given that this seems to be an ongoing occurrence however, I've re-opened our internal investigation into this. 

I appreciate the patience here and will keep you updated as we continue to explore.
