### ISSUE TITLE
Pipelines re-ordering, Issues moved en masse without triggering hooks

### ISSUE THREAD

**Issue by robamaton** [ZenHubIO/support#367]
This morning, several of our Pipelines were mysteriously in the wrong order, and a handful of Issues in our Discussion pipeline had moved to In Progress. We have a Slack integration that triggers whenever an Issue is moved, and it did not trigger for these moves. I don't see any pattern in which Issues moved and which were left in Discussion. Any ideas?

**Comment by robamaton** [comment]
Turns out that when I re-ordered the Pipelines back, the Issues snapped back to their correct Pipelines... So it's not urgent for us, but probably still a bug worth avoiding.

**Comment by aupright** [comment]
Thanks for the feedback here @robamaton - this behaviour wasn't reported by any other users so it looks like this was an isolated case. While I'll close this issue out for now, I'll make sure to bring it to the rest of the team so we can keep track of this error going forward. Thanks again!
