### ISSUE TITLE
Recent update breaks ability to see files changed in a Pull Request

### ISSUE THREAD

**Issue by snario** [ZenHubIO/support#368]
Is this just me?

For the past week or so any time I click Files Changes in the modal / lightbox of a PR on the boards page the modal closes and I am left with a blank white page.

Any time I want to see a PR now I have to open the individual page.

**Comment by aupright** [comment]
Hey @snario apologies for the late reply here!

We noticed this one ourselves, and quickly pushed out a fix to ensure proper linking when users click on the "files changed' tab in pull request modal. As the extension update has fully propagated amongst our users, I'm going to close this one out! Thanks again for the feedback :beers:
