### ISSUE TITLE
Multi-Milestone Board - Bug

### ISSUE THREAD

**Issue by neellukka** [ZenHubIO/support#369]
The new change to the milestones where you click a milestone through the dropdown and it keeps the previously selected milestones tickets active is super frustrating. Causes multiple clicks, confusing of which tickets are in each milestone etc.

Please revert back to previous

**Comment by aj-thilakan** [comment]
If you allow this use case (selecting multiple milestones), it should at least keep the Milestone Filter drop down open so that we can clear the filter and apply a new filter, without having to reopen the drop down after every change.

**Comment by azenMatt** [comment]
Thanks for the feedback here, 

I agree with you - i've raised it as a bug fix to keep the drop down open on select, lets try that and see if it helps. 

In general, do you agree that it is useful to be able to select multiple milestones? Or do you always only want a single one selected?

**Comment by aj-thilakan** [comment]
I rarely need to multiple select milestones, but some of our Devs do. I think they find it useful to see their assigned tickets across different milestones. 

Thanks, I think keeping it open should satisfy both use cases

**Comment by neellukka** [comment]
any update on this @azenMatt  its really ruining our flow for the Board...

**Comment by azenMatt** [comment]
Hi @neellukka - It has been prioritized and is rising to the top of our 'Bugs that we need to fix' list. 

Thanks for your patience, shouldn't be too much longer. Our number one priority right now is improving the board loading time, and then we will be coming back to this and a number of similar issues.

**Comment by azenMatt** [comment]
Hi @neellukka - check out v2.9.10 

We just put a change live to alter the behaviour of our filters. So now when you select a milestone, the filter will stay open. 

We felt this was much better UX as it made it clear that by selecting another value - you were entering into an 'OR' filter. 

This should be the best for all users - those that would like to see multiple lables / milestones / assignees as well as not being misleading for those who just want to see one.

Let me know what you think!

**Comment by neellukka** [comment]
thanks @azenMatt just tried it out, it helps for sure!
