### ISSUE TITLE
Sort Milestones

### ISSUE THREAD

**Issue by VaclavRut** [ZenHubIO/support#371]
Add option to sort milestones on board by further due date etc., like basic sort in github.

Thanks :)

**Comment by aupright** [comment]
Hey @VaclavRut - thanks for the suggestion!

I can see where this could be a great addition to the filters that we already offer. I'll move this one to the discussion column to see if we can get some more feedback and upvotes. Thanks again :beers:

**Comment by Mottie** [comment]
I have a userscript that allows the [sorting of pipeline issues](https://github.com/Mottie/ZenHub-userscripts) which currently allows sorting by assignee, time estimate, issue number, repo name and issue title.

The milestone data isn't currently available inside the issue card. If it gets added as a data attribute or text somewhere, it would be easy to include it for sorting.

**Comment by oevans** [comment]
Sorry if I'm missing something simple, but how do we vote?

**Comment by jlindenbaum** [comment]
I think this is the right ticket for this comment.

On the board, by default, it appears to milestones sort alphabetically. Is there a way to sort them due date (nearest to furthest)?

<img width="305" alt="screen shot 2016-06-23 at 1 13 10 pm" src="https://cloud.githubusercontent.com/assets/197034/16316574/6c3d5e06-3944-11e6-99c6-16887146fdaa.png">

**Comment by azenMatt** [comment]
milestones on the board are now sorted in a more logical manner - so it should be easy to find the one being worked on at the moment at the top of the list

**Comment by ljm22** [comment]
@azenMatt this is a lovely feature but @jlindenbaum is right, milestones should sort in date order. We, uh, have a *lot* of issues against old milestones when we get to our quarterly backlog grooming session...

**Comment by azenMatt** [comment]
Hi @ljm22 - to confirm, are you suggesting a change here to the current ordering? What would work best for you?

**Comment by adamreisnz** [comment]
@azenMatt this doesn't seem to work for me.

The milestone that has the closest due date (a *negative* due date in this case, e.g. it was due a couple days ago), appears at the bottom of the list for us:

![image](https://cloud.githubusercontent.com/assets/490562/20904741/b8721c56-bba5-11e6-9e7b-7b80987a33b4.png)

Any chance this can be fixed so the milestone shows up on top?
