### ISSUE TITLE
Bug: Changing assignee, milestone, or label makes Zenhub controls disappear

### ISSUE THREAD

**Issue by crazydog115** [ZenHubIO/support#372]
To reproduce:

1. Go to an issue
1. Change the assignee, milestone, or label
3. Notice that the "Pipeline" and "Estimate" areas for the issue are now gone.

**Comment by crazydog115** [comment]
This seems to be fixed now.

**Comment by azenMatt** [comment]
:+1: @crazydog115 - 2.5.26 contained a fix for this

Apologies for not getting back to you on this one sooner!
