### ISSUE TITLE
I made a Board called 'Future' my first Board  and it receives my new issues, not New Issues

### ISSUE THREAD

**Issue by mrmayfield** [ZenHubIO/support#373]
The board furthest left on my screen is called 'Future', 'New Issues' is further down on the righthand side, but now 'Future' is receiving New Issues when they are made.

**Comment by aupright** [comment]
Hey @mrmayfield thanks for reaching out!

By default, newly created issues will always end up in the left most pipeline (board) in your workflow—even if the name is something other than 'New Issues'. If you'd like to switch the position of these pipelines (while still retaining all of the issues) you can simply rename them by clicking on the gear in the top right hand corder of the pipleine and selecting 'rename'. Cheers :beers:
