### ISSUE TITLE
Adding multiple owners to a card for paired programming

### ISSUE THREAD

**Issue by gthorsen** [ZenHubIO/support#374]
This should be visible on the face of the card in the dashboard, rather than in the card details.

**Comment by aupright** [comment]
Thanks for the feedback @gthorsen - this is actually one that we've though quite a bit about ourselves. Our primary hesitation to adding multiple owners/assignees to an issue is that it also creates a greater risk for lack of ownership. As we're always open to integrating suggestions from our users however, I'll move this one to the discussion pipeline to see if we can get some additional feedback from the community.

Thanks again for the suggestion - keep em coming! :beers:

**Comment by eskatos** [comment]
Pair-programming is a use case for multiple assignees, another one could be peer-reviews.

For peer-review, we work around the single assignee limit by declaring the *owner* in the issue description and assign the issue to whomever has work on it, back and forth between owners and reviewers.

Ownership is important and our workaround bury the data into the issue description which is far from ideal.

My 2 cents

**Comment by azenMatt** [comment]
this is now supported 👍
