### ISSUE TITLE
Unable to merge repositories

### ISSUE THREAD

**Issue by chrisfree** [ZenHubIO/support#375]
Linking to repositories in our organization appears to be broken at the moment. Clicking "merge" after selecting the repository to merge fails silently. The boards interface refreshes but the boards aren't linked. I'm curious if an existing repository needs to be using Zenhub first (has boards setup, etc.) before a merge can occur.

Is this a known issue?

**Comment by azenMatt** [comment]
Hi @chrisfree - thank you for reporting this one, you are right that it is a bug. We just pushed a fix with release 2.6.2

Please let me know if you have any other issues!

**Comment by chrisfree** [comment]
Huzzah! It worked. Thanks so much.

**Comment by justinwhite** [comment]
I'm on 2.13.20 and I'm having the same issue where I see the refresh, but am unable to merge the repos.
