### ISSUE TITLE
My Zenhub Thoughts After Week 1

### ISSUE THREAD

**Issue by talsafran** [ZenHubIO/support#378]
Zenhub Thoughts
============

Hi all! Overall I love the product. Just wanted to share some quick thoughts.

Love
--------

- I'm switching over from Pivotal Tracker, since we were still using Github Flow and doing a lot of our conversations in Github. Love the integration and philosophy –– hope y'all continue to improve the product!
- Compose Issue Screen –– much faster than regular Github screen.
- Keyboard shortcuts are super helpful.

Could be better.
--------------------------
- Clicking "New Issue" when I'm on a board shouldn't ask me which repo to choose.
- I don't know when someone "finishes" something. I'd like to see an activity log "Zeke finished Issue #103. This could be in-app, or trigger an event in Slack.
- Doesn't always refresh if I close an issue somewhere else.
- What is the "Todo" pipeline? I removed mine because I didn't understand how I should be using it.
- In general, would love to move from one pipeline to the other automagically.
- Kinda slow! When I reload the "Board" it first loads the normal Issues page, then loads the board on top. Same with creating an issue.
- Assigning a person is a lot of clicks (maybe click on the avatar?)
- Moving issues out of Pivotal Tracker into Github was a time suck. Having an Export button could help y'all with switching costs for customers.

This is just a brain dump, I'm sure I'll have more as we continue to try the service.

**Comment by azenMatt** [comment]
Hi @talsafran - Thank you for taking the time to provide this feedback - it is really useful for us! 

To add to some of your points:



> Clicking "New Issue" when I'm on a board shouldn't ask me which repo to choose.

Yes, I agree. Currently, if you are on a 'single repo' board, then you go straight into the issue creation. But if you are on a 'multi-repo' board it will ask you which of those repos you would like to create an issue in - as we did not want to assume which repo it should be created in. I think we can instead treat this like an edge case and assume that the user always wants to create an issue in the repo they entered by and allow an extra click somewhere else if the user would like to switch the repo the issue gets created in. 



> I don't know when someone "finishes" something. I'd like to see an activity log "Zeke finished Issue #103. This could be in-app, or trigger an event in Slack.

We do have slack integration (set up via the dashboard https://dashboard.zenhub.io) which would help with this as issues move through a board. We are working on ways to make this fit more seamlessly in the GitHub experience. 

> What is the "Todo" pipeline? I removed mine because I didn't understand how I should be using it.

The default pipelines are just recommendations based on a typical Agile flow. Feel free to shuffle them around and rename them to fit your workflow! 



> in general, would love to move from one pipeline to the other automagically.

Also agreed! we are working on different ways to make this a more seamless experience




> Kinda slow! When I reload the "Board" it first loads the normal Issues page, then loads the board on top. Same with creating an issue.

This is one of our big priorities at the moment, we pushed out some speed fixes earlier this week and have more coming soon.



> Assigning a person is a lot of clicks (maybe click on the avatar?)

Like with moving issues automagically, unnecessary clicks are the enemy :) We are looking at ways to make all in-board actions easier 

> Moving issues out of Pivotal Tracker into Github was a time suck. Having an Export button could help y'all with switching costs for customers.

got it :+1: same with other systems like Jira, automating this is on our to-do list :) 



> Love the integration and philosophy –– hope y'all continue to improve the product!

Thank you! We have lots of ideas and improvements we want to implement - it's going to keep getting better :grinning: 

Please keep the feedback coming as you use ZenHub more!

**Comment by talsafran** [comment]
Thanks for the amazing response @azenMatt. Installed the Slack notification :)

I couldn't figure this one out though: how do I know if I'm on a multi-repo or single-repo board? How can I toggle?

**Comment by azenMatt** [comment]
>Thanks for the amazing response @azenMatt. Installed the Slack notification :)

Glad it was useful!

> how do I know if I'm on a multi-repo or single-repo board? How can I toggle?

The best way to tell is via the 'repo filter' on the left hand side of the board. 

If it is followed by numbers larger than (1/1) - then you are on a multi-repo board:

![image](https://cloud.githubusercontent.com/assets/7584089/9973689/c87a3624-5e2c-11e5-9e64-13cc657447d3.png)

If it has (1/1) then it is just a single repo board: 

![image](https://cloud.githubusercontent.com/assets/7584089/9973693/e7727ed8-5e2c-11e5-9a56-eeb604484579.png)


This feature lets you group repos together to view on a single board. You can use that drop down to add/remove repos or as a filter if you would just like to see a subset

**Comment by raimo** [comment]
>> Kinda slow! When I reload the "Board" it first loads the normal Issues page, then loads the board on top. Same with creating an issue.

>This is one of our big priorities at the moment, we pushed out some speed fixes earlier this week and have more coming soon.

+1 for the upcoming fixes for this. This accounts for several minutes of waiting per day, but more importantly, it directly affects the motivation to open the board altogether.

**Comment by talsafran** [comment]
@raimo I think this might be a bug then? I only have one repo, but still have to pick it every time:

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/ls6rmh74.png)

**Comment by talsafran** [comment]
Add another to the wishlist!

Since we're organizing into weekly sprints, it'd be great to be able to have the "Closed" pipeline grouped by weeks. That makes it easy to assess the end of the week at retro.

<3 keep up the magic

**Comment by talsafran** [comment]
Another thought:

A lot of times I really only care about one pipeline at a time. For example, during the week I want to focus on "This Week" and make it as easy as possible to make sense of everything. Same when I'm running through the giant backlog.

In other words, seeing all of this together gives me and the team a bit of anxiety:

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/9ftpy6os.png)

A "Pipeline" view would help us focus and see more of the relevant info, since at the moment each pipeline is only given about 1/6 of the possible screen real estate.

**Comment by azenMatt** [comment]
> I only have one repo, but still have to pick it every time:

Yes - that isn't the behaviour we want, we will get that fixed!

 



> Since we're organizing into weekly sprints, it'd be great to be able to have the "Closed" pipeline grouped by weeks. That makes it easy to assess the end of the week at retro.

Thats an interesting idea - do you use milestones for your sprints? Splitting this on a weekly basis is probably too attached to your specific workflow. But we do want to make it easier to perform tasks that we know most of our teams follow - like sprint planning and retros. Milestones work well for this, but I appreciate that managing these on a weekly basis is overkill,  so a way to make this process easier would be :+1: 



> A lot of times I really only care about one pipeline at a time. For example, during the week I want to focus on "This Week" and make it as easy as possible to make sense of everything. Same when I'm running through the giant backlog.

The good news is that we are currently working on this! #122 should be going live very soon (just working on some minor bugs) which will allow you to shrink down pipelines you don't need - and expand those you want to focus on.

**Comment by azenMatt** [comment]
@talsafran 

A quick update on: 

> A lot of times I really only care about one pipeline at a time. For example, during the week I want to focus on "This Week" and make it as easy as possible to make sense of everything. Same when I'm running through the giant backlog.

The ability to collapse and expand pipelines just went live on version 2.8.1, let me know if this helps!

**Comment by zeke** [comment]
> collapse and expand pipelines just went live

:clap:

**Comment by talsafran** [comment]
@azenMatt Thanks for the collapsies. We dig them.

> Thats an interesting idea - do you use milestones for your sprints? Splitting this on a weekly basis is probably too attached to your specific workflow.

We do use Milestones but organize into weekly sprints. It's nice at the end of the week to see what we did (and what we didn't).

A lot of tools have this, including our previous tool Pivotal Tracker which (maybe too opinionatedly) organizes everything into weekly iterations based on estimation points + average velocity.

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/lvoujhxa.png)

I personally think a lot of folks in the agile world would want this. But I'm biased :)

**Comment by talsafran** [comment]
Had some more feedback about collapsing/expanding.

A lot of times I find myself wanting to see more issues within each pipeline. Most of the time I can usually see 5.

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/lgml0sac.png)

The problem with expanding is that when I do it, I love sense of the ordering. We (try to) use ordering to dictate "what's next important"). When things are side by side, it's really hard:

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/vifn-ybi.png)

Part of the problem is that the top ~250px of the window (~30% of vertical space on a Macbook) are wasted on navigational stuff.  It'd be great if there was a way to "maximize" a pipeline and see more stories top-down, while preserving their order.

Maybe a maximized pipeline could look like this?

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/youitego.png)

I get double the information! And if we could find a nifty way to remove the vertical space at the top, we'd get up to 3x!

Just a thought :)

**Comment by azenMatt** [comment]
Interestingly, we used to have 'zen mode' that stripped out most of the data to make a card a single line so they you could get greater 'card density' on the board. But we removed during our beta as no one liked it :smile: 

But I agree, being able to see more data here is a good thing. A full screen board is on our radar and I will take a closer look at the idea of having an expanded pipeline 'stretch' the cards rather than put them side by side. 

If it helps, the cards in the grid are still ordered - left to right. So if you have a single width pipeline with 8 issues: 

[1,
2,
3,
4,
5,
6,
7,
8}

If you went to a '3 width' pipeline, it would retain the order: 

[1, 2, 3,
4, 5, 6,
7, 8]

But I appreciate your point that this is harder to base an ordering on.

**Comment by talsafran** [comment]
Hi @azenMatt @raimo.

We have a lot of pipelines so there's a fair amount of horizontal scrolling to get to certain pipelines.

I think there was a new bug introduced that's making Zenhub really really really hard/annoying to use.

1. Scroll to the right to, say, the "This Week" pipeline
1. Open up an issue
1. Close the issue (either with ESC, the X, or clicking away)
1. The page scrolls all the way to the left.

This means we have to re-scroll to the right to the "This Week" pipeline. Right now we're trying to run through all of our issues one by one and it's making it super hard to do.

Hope this is enough information! Thanks.

--

cc @zeke @joyjding

**Comment by azenMatt** [comment]
Thanks for reporting this @talsafran - I can replicate (and find it super annoying as well!) 

We will have a patch out for this as soon as we can. 

>Right now we're trying to run through all of our issues one by one and it's making it super hard to do.

Quick question, would you find something like https://github.com/ZenHubIO/support/issues/300 useful for getting through these issues?

**Comment by talsafran** [comment]
@azonMatt totally.

**Comment by talsafran** [comment]
@azenMatt totally.

**Comment by talsafran** [comment]
@azenMatt Any updates on this bug? Still seems to be there and is very debilitating :cry:

**Comment by azenMatt** [comment]
It is being worked on at the moment - should be released for you tomorrow

**Comment by azenMatt** [comment]
OK - fixed! V2.13.9! 

#300 should be following in the not too distant future


Please keep the bugs coming :grinning:
