### ISSUE TITLE
Minimize emphasis on empty pipelines

### ISSUE THREAD

**Issue by Groostav** [ZenHubIO/support#379]
> As a team lead I want to review a set of issues that exist entirely in one pipeline with more screen real-estate so that I can better visualize my board and whats on it.

Currently, using Axiom Zen, when reviewing the status of my epics, I get a board that looks like this:

![waste of space](https://cloud.githubusercontent.com/assets/1680611/9949833/8f743098-5d67-11e5-8eba-5bba561e76a5.png)

This is because, while epics and issues do both go through some of our pipelines, they do not move through all of them (an epic is never in review).

I would really appreciate it if Zenhub would take advantage of the wasted space. This might allow what was a 2-line summary to fit in 1 line, fitting more stuff in the same vertical space, hopefully removing that scrollbar (nobody likes scrollbars).

The way I think to do this is to reduce the width of empty columns, something like:

![zenhub small pipes mockup](https://cloud.githubusercontent.com/assets/1680611/9949934/30abe266-5d69-11e5-81f6-ce5395075de3.png)

Of course, this presents your UX people with a dilemma on how you want to handle the case where you drag an item from a non-empty pipe to an empty pipe. To use fancy css or not to use fancy css. Dont ask me, if I had my way everything would me swooping around like it is on windows phone.

my .02, 

-Geoff
--ps yes, that is a en epic for bugs, I know, the shame. We swapped some pretty hardcore stuff in our persistence scheme, it _ran_ but _not well_. Needed to be done, but it certainly consumed a lot of QA time running all the wierd side effects down.

**Comment by Groostav** [comment]
balsamiq mockup:
[zenhub small pipes mockup.bmpr | uploaded via ZenHub](https://files.zenhub.io/55fb6883fd7194de615a673c)

**Comment by azenMatt** [comment]
looks awesome @Groostav - agreed that would be very useful. 

We are looking at have collapsing / expanding pipelines (ref #163 / #122) which will solve this problem for you. Coming (very) soon :smile:

**Comment by filib** [comment]
> We are looking at have collapsing / expanding pipelines (ref #163 / #122) which will solve this problem for you. Coming (very) soon.

Oh, that would be awesome.

**Comment by azenMatt** [comment]
@Groostav @filib 

We just went live with version 2.8.1 which implements this feature :smile: 

![image](https://cloud.githubusercontent.com/assets/7584089/10205742/c7802a4a-6777-11e5-872d-58d16085fdd5.png)


Enjoy!

**Comment by Groostav** [comment]
Nice work guys!

I was thinking that it would simply be auto-magical for pipelines without any content, but the fact that its persisted across sessions will likely have the same effect.

Thanks!

**Comment by filib** [comment]
@azenMatt :tada: 

/cc @ticktricktrack
