### ISSUE TITLE
Communicate priority during filtering 

### ISSUE THREAD

**Issue by azenMatt** [ZenHubIO/support#380]
ref https://github.com/ZenHubIO/support/issues/285#issuecomment-141217056

> Any requests/thoughts on when I perform the search it just opens up a new "temporary pipeline" with all those issues in it. So don't filter the board, but show all the results in a pipeline that I could then move to a some place on the board and then the board would reflect my desire. 
> 
> The main use case is that when I search for an issue that is in my backlog and it filters down all the boards, that doesn't give me context for where that thing sits in priority in that pipeline. So to me, the search as it is currently implemented doesn't help me anymore than a ctrl+f does. In fact, I probably use the ctrl+f more often since it still gives me the ability to see the context of where the issue sits in the pipeline. When I have a backlog that is 80 issues deep, that is important to me to know where it sits in priority.
> 
> What I proposed would also help with seeing all the issues labeled with a certain feature name in one temporary pipeline so I can more easily see all the those things and then place them next to each other in priority in the backlog pipeline. By filtering it down, they are already next to each other and thus it isn't really effective moving them.

cc @jckime

**Comment by Schoentraumer** [comment]
I definitely agree! I would like to filter the items in either the board or in the issues tab on Priority/Estimate, we're able to do it for the other features but this is very important.
