### ISSUE TITLE
sort issues within a milestone by votes

### ISSUE THREAD

**Issue by michaelglass** [ZenHubIO/support#381]

**Comment by aupright** [comment]
Hey @michaelglass, thanks for the suggestion!

We've had a few other users reach out with a similar suggestion around sorting  and filtering issues by +1's in ZenHub (see https://github.com/ZenHubIO/support/issues/303). Although this is something that we'd be interested to explore further, we'd like to get a bit more feedback from the rest of the community first that this is something they would like to see in the product! It would be great if you could leave any additional feedback/comments that you have in the issue above :smiley:

**Comment by michaelglass** [comment]
closing this as it looks like a dupe of #303
