### ISSUE TITLE
Issue popup text selection

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#383]
While interacting with the popup, such as adding labels, a mouse click causes all text within the popup to be selected/deselected. Here is a gif of the problem:

![zenhub-issue](https://cloud.githubusercontent.com/assets/136959/10075920/0b12b6da-629e-11e5-92e6-f714d2dba1f5.gif)

And as you can see in that gif, the first click is ignored.

**Comment by aupright** [comment]
Hey @Mottie thanks for reaching out. 

Is this error still occurring when you try to interact with the different fields inside of the issue modal? A few of us have tried to replicate this internally and haven't been able to do so. Although it looks like you're using the most recent version of the extension (v 2.7.5), would you be able to let me know which version of Chrome you are using? 

Although we can keep this issue open to try and see if anyone else is experiencing this same problem, could you please send a follow up email to support@zenhub.io if this error is still occurring? I'll keep an eye out for a message from you!

**Comment by Mottie** [comment]
Thanks, this issue is now resolved :fireworks:
