### ISSUE TITLE
When adding a new estimate, the UI still allows me to click continue on an incorrect input when it shouldn't

### ISSUE THREAD

**Issue by curreta** [ZenHubIO/support#386]
A user has the ability to add the following estimate:

```
0 (hi)
```

The estimate saves and creates a NaN submission.

**Comment by aupright** [comment]
Hey @pitzips thanks for issuing this one up! I'll move this to our internal backlog so that we can put together a fix for this in our next update that we push out :beers: 

I'll keep this issue open and update you as soon as this goes live.

**Comment by kendramoroz** [comment]
It's been a while, but we improved this experience! No longer will NaN submissions be allowed - we correctly prompt you through creating a numerical estimate submissions 🎉
