### ISSUE TITLE
New Issue Templates

### ISSUE THREAD

**Issue by jefforshalick** [ZenHubIO/support#387]
We have templates that we use for writing issues and epics.

It would be nice to have these templates accessible from the new issue creation modal or screen. It could be in a dropdown that just inserts the template into the "Write" input box. This would be instead of copying and pasting from our templated issues.

**Comment by aupright** [comment]
Thanks for the suggestion @jefforshalick, I can see where that would be a helpful shortcut to having to copy and paste from your templates issues! I'm moving this one to our Community Icebox for now so that we can re-visit it going forward.

Thanks again for the suggestion :beers:

**Comment by goanpeca** [comment]
This is indeed a great idea!

**Comment by vmarinucci** [comment]
This keeps coming up on my team as something that would be most helpful as well...over and over again. ;) +100 here.

**Comment by vmarinucci** [comment]
Any timeline for this yet?

**Comment by azenMatt** [comment]
Sorry @vmarinucci - no timeline for this one just yet. I will let you know as soon as I do

**Comment by nickiehills** [comment]
This would be of great benefit to us too as issues have to cover new capability and small change the developer is making or defects reported by users, all of which need slightly different details reported (e.g. in defects you want to know specific release/build details)

**Comment by cbpope** [comment]
This is definitely of interest to me as I'm looking to provide a story template for my PO and Stakeholders to ensure they provide all the data required for the development team to deliver successfully.  In the meantime I will create a word template for them to cut and paste into the issues and epics.... Thanks for including the ability to develop templates within Zenhub to your backlog!

**Comment by chris-fa** [comment]
This one would be perfect, even better if it'd let you add 1 or 2 templates, as we use issues for both bugs and user stories.

**Comment by elgris** [comment]
The same story here. My team uses different kinds of issues: "regular" issues, bugs, epics, etc. It would be nice to have support of issue templates for each kind.

I'm too lazy to just copy-paste =]

**Comment by bpenny** [comment]
Currently you can create [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) in GitHub.
The [ZenHub blog](https://www.zenhub.com/blog/best-practices-for-github-issues/) even speaks about this feature.

When you click New Issue in Github, the template works as expected.
When you click New Issue in ZenHub, the template does not appear.

ZenHub can have its own templates and even extend the issue template feature in GitHub (that is enhancement worthy).

If ZenHub can't provide basic feature parity to GitHub (such as new issue creation), that should be a defect.  If I am wrong, please explain why.  Thanks

**Comment by azenMatt** [comment]
The GitHub issue templates are now live in the ZenHub app :) 

More advanced functionality for these templates coming in the future!

**Comment by kendramoroz** [comment]
Hey @ruddell-mbible! Issue templates are still managed via GitHub ([they have a support guide on this here](https://github.com/blog/2111-issue-and-pull-request-templates) that might help!). The ZenHub web app will pick up on the templates you have for your repository during the new Issue creation :). Let me know if you're experiencing otherwise!

**Comment by ruddell-mbible** [comment]
Okay thanks for the followup.  I was thinking Zenhub would have a feature to create templates, or create issues using one of several templates the organization has setup.

**Comment by zealoushacker** [comment]
Letting the user specify an issue template filename via the `?template` param on issue creation from the boards screen would be a great first cut at this functionality.

**Comment by kram0120** [comment]
Hi @kendramoroz ,
I have created a new issue template in my GitHub repo, following the support guide. The template is available when I create a new issue in the GH repo itself, but it does not appear to be available from the ZenHub app. When I create a new issue in ZH, I just get the plain vanilla issue template.

**Comment by TMVector** [comment]
@kendramoroz similar to @kram0120, I do not see issue templates when using either the ZenHub app or the ZenHub chrome plugin and creating an issue via the board interface.

Am I misunderstanding what you meant by ZenHub picking up on templates during issue creation?

Thanks for your help!

**Comment by kendramoroz** [comment]
@TMVector @kram0120  Happy to help further! Can you both send through a screenshot of the template in GitHub and what you're seeing in ZenHub? This will help us debug further 🙏 🕵️‍♀️

**Comment by andykenward** [comment]
Templates defined on a GitHub repo do not show on https://app.zenhub.com .

When using https://app.zenhub.com and creating a new issue I can see in the GitHub graphql request that templates are returned. But are not shown in the dropdown input for templates.

![screen-shot-2018-11-15-11-53-56 26](https://user-images.githubusercontent.com/4893048/48551436-798ca400-e8cd-11e8-8a4e-6a0ebe252526.png)
![screen-shot-2018-11-15-11-52-31 06](https://user-images.githubusercontent.com/4893048/48551438-7beefe00-e8cd-11e8-8027-374ea43edea9.png)
