### ISSUE TITLE
Way to copy issue URL to clipboard from board view

### ISSUE THREAD

**Issue by gabrieljoelc** [ZenHubIO/support#389]
If I want to quickly reference an issue in a different repo or post it in Slack or email, I click on the issue card in the board, Control-click on the link and copy link address
![image](https://cloud.githubusercontent.com/assets/147849/10202542/3b4cf906-6766-11e5-9279-d7553b2831d9.png)
But it'd be nice if I could, just click an option in the hamburger menu or even hover an issue in the board and Command+C (like Trello [does](http://stackoverflow.com/q/17527870/34315)) to get the URL in my clipboard.

**Comment by aupright** [comment]
Thanks for the suggestion @gabrieljoelc—we find ourselves copying links for issues and pull requests into Slack, email, etc. quite a bit as well, and I can see where this would be a useful addition. I'm going to move this one to the Community Icebox so that we can capture it going forward and look at where there might be a good fit in our roadmap.

**Comment by azenMatt** [comment]
The URL when you are in board view now links to the issue view - so you can copy and paste to send a link to the issue directly from there

**Comment by gabrieljoelc** [comment]
@azenMatt I was not requesting getting a link that would open the board-modal-version of the issue. I was requesting an easy way to _quickly copy a link_ with a button or  Command/Ctrl+C like in [Trello](http://stackoverflow.com/q/17527870/34315).

**Comment by azenMatt** [comment]
understood - the link in the URL bar is the link to the actual issue - not a link to the modal. 

So for this issue it is - 

https://github.com/ZenHubIO/support/issues/389 

not the #boards version

So you can use built in shortcuts for this, 

command/ctrl + L to select all in the address bar then command/ctrl + C to copy 

does that help?

**Comment by gabrieljoelc** [comment]
Oh I see. That's sufficient i suppose. Thanks!
