### ISSUE TITLE
Board does not show estimates!!

### ISSUE THREAD

**Issue by matejkastner** [ZenHubIO/support#390]
Hallo @azenMatt, please help!! after last update boards do not show estimate of issues, this is crucial feature for us to keep sprint planning on reasonable level.

Please enable again. THX

**Comment by trueter** [comment]
I'm also having issues with pipelines and estimates ( http://i.imgur.com/C5PA09B.png ). Boards are not loading at all.

**Comment by trueter** [comment]
Nevermore. Thanks.

**Comment by matejkastner** [comment]
Hallo @trueter this seems to be caused by zenhub.io outage about 2-3h ago. That time no boards have been shown (as far as I know).

But anyway, even ZH is back again and working, estimates are still not shown

**Comment by azenMatt** [comment]
Hi @matejkastner @trueter - We experienced some downtime earlier today and are still trying to recover full functionality. 

We will have the estimates back with you as soon as possible

**Comment by azenMatt** [comment]
@matejkastner @trueter - this is now fixed, please let me know if you have any other issues!

**Comment by matejkastner** [comment]
@azenMatt Hallo Matt, thanks a lot, everything is back :) :+1:
