### ISSUE TITLE
Easy way to "mute" integrations

### ISSUE THREAD

**Issue by vsinghkpcc** [ZenHubIO/support#391]
When our team does sprint planning, slack gets overwhelmed with updates all at one time, which is pretty noisy.

It would be great to easily mute / unmute integrations to prevent this. (or some other better idea that solves the problem!)

**Comment by aupright** [comment]
Hey @vsinghkpcc thanks for the feedback! Did you know you can actually temporarily mute channels in Slack if you don't wish to receive updates? Check out the documentation below :smile: 

https://slack.zendesk.com/hc/en-us/articles/204411433-Muting-a-channel-or-private-group

**Comment by vsinghkpcc** [comment]
@aupright thanks for following up! Unfortunately that's not exactly the problem we're trying to solve, as we're more interested in preventing something like this from happening:

![screen shot 2015-10-26 at 1 44 38 pm](https://cloud.githubusercontent.com/assets/13337277/10741987/edd87a38-7be7-11e5-8bfb-c88d384a1574.png)

Some of our channels get overwhelmed with these messages during our sprint planning meetings, or when we groom our backlog. This makes those messages less valuable, being a big block of updates that's less appetizing for people to mentally digest.

However, I do believe perhaps it's something we can solve on the slack side of things (or maybe even somewhere else in the process).

Thanks again!

**Comment by aupright** [comment]
Thanks for the added context @vsinghkpcc!

Although I'll keep this one closed for now, I can definitely bring this feedback to the rest of the team so that we can look at what options we might be able to offer on our side. 

Thanks again for the feedback :beers:
