### ISSUE TITLE
Unrelated estimate being updated

### ISSUE THREAD

**Issue by tshelburne** [ZenHubIO/support#393]
I'm not 100% sure how to recreate - it seems intermittent. But the suggested approach is below:

1. Open a ticket (TICKET 1) with a set estimate (ESTIMATE 1)
1. Click "New Issue" (notice ESTIMATE 1 from the previous page is present)
1. Fill out issue details
1. Change the estimate (ESTIMATE 2) on this issue
1. Save (notice ESTIMATE 2 on this issue is not set)
1. Look at TICKET 1 and notice the estimate is now ESTIMATE 2
1. ESTIMATE 1 has disappeared entirely

**Comment by agardez** [comment]
I was able to reproduce it 100% of the time by having:

* a ticket 1 with an estimate, 
* which is mentioned in ticket 2 which has a different estimate.

So:
1. Go to ticket 1
2. click on link to ticket 2 saying `referenced this issue X days ago`
3. The estimate you'll see there will be estimate for ticket 1, not ticket 2. 
4. When you refresh, the wrong estimate is still shown.

**Comment by azenMatt** [comment]
Hi @tshelburne @agardez - we just pushed out a fix for this, can you upgrade to 2.15.82 and confirm that this is now working for you? 

Thanks!

**Comment by tshelburne** [comment]
@azenMatt My issue is fixed - thanks!

**Comment by agardez** [comment]
looks good, thanks!
