### ISSUE TITLE
Show total sum of all estimations in pipeline

### ISSUE THREAD

**Issue by jkaizer** [ZenHubIO/support#394]
I would love to see how many points all of the cards are that I have in any given
pipeline.

Currently, it shows the number of issues. In this example I have 34 issues in this pipeline.
<img width="284" alt="screen shot 2015-10-06 at 10 56 57" src="https://cloud.githubusercontent.com/assets/597330/10304219/1852f8a8-6c19-11e5-9401-555217ae13d2.png">

Every issue is estimated. Please show the total estimation next to the number of cards.

**Comment by matejkastner** [comment]
hi @jkaizer see #339

**Comment by jkaizer** [comment]
Thanks!
