### ISSUE TITLE
Renamed Repo has lost its board--no pipelines, no issues, nada

### ISSUE THREAD

**Issue by henryyamamoto-concur** [ZenHubIO/support#395]
We have an issue where a team member renamed a repo and now our board has disappeared. and we're not sure how to get it back. The issues are there with the designated pipelines, milestones, etc. and the burndown chart also works. Is there a way to remedy this?

**Comment by azenMatt** [comment]
Hi @henryyamamoto-concur - we have pushed a number of changes this week to improve the rename experience. Can you confirm that this is now working for you? 

The renaming experience is still at the mercy of the GitHub API - but now ZenHub will also pick up a rename either 1) after one hour or 2) when a new issue is create or 3) when an issue is renamed 

Please let me know if you are still experiencing any problems, thanks!
