### ISSUE TITLE
New Issue should make repository selection optional

### ISSUE THREAD

**Issue by darrennix** [ZenHubIO/support#396]
![image](https://cloud.githubusercontent.com/assets/738245/10352302/1d83ca92-6d03-11e5-9998-88e1d5519e61.png)

Having to select a repository (from a list of 1) each time I want to create a new issue (the most common task I do) wastes 5 seconds every time.

**Comment by azenMatt** [comment]
Yes! agreed! 

Being worked on at the moment :smile:

**Comment by azenMatt** [comment]
and done! 

Live on 2.10.3 - select the new issue button to create an issue, or the separated dropdown component to pick a repo
