### ISSUE TITLE
Burndown works wrong

### ISSUE THREAD

**Issue by ihorml** [ZenHubIO/support#398]
Take a look my screenshot - https://www.dropbox.com/s/gr2shz6u2duyef0/Screenshot%202015-10-09%2011.50.39.png?dl=0

I don't understand why my finished(closed) tasks are not displaying on my burndown. What is the `Completed task`? I thought that the `Completed Task = Closed Task`. Correct me if I'm wrong...

**Comment by aupright** [comment]
Hey @ihorml thanks for reaching out—I apologize for the delayed reply here. 

When I went to take a look at the link you posted, I received a 404 error that the file had been removed. Would you be able to re-post the file again, or send the file to support@zenhub.io?

**Comment by azenMatt** [comment]
Hi @ihorml - can you email me at support@zenhub.io and with the screenshot and we can get this fixed for you, thanks
