### ISSUE TITLE
Move an issue to the top of the pipeline

### ISSUE THREAD

**Issue by srossross** [ZenHubIO/support#399]
When we are prioritizing our issues, it is a pain to move an issue to the top of the pipeline. It would be great if the context menu had a "move to top" and "move to bottom" as well as the existing "close".

**Comment by aupright** [comment]
Hey @srossross thanks for the feedback!

We've actually hear this one a couple of times before and are trying to centralize the feedback here #170. It would be great if you could add a +1 and any additional comments you might have there :smiley:

**Comment by azenMatt** [comment]
@srossross - this is now live :smile: 

![image](https://cloud.githubusercontent.com/assets/7584089/12524382/874a31ca-c111-11e5-9fcf-659baa3cac42.png)

**Comment by srossross** [comment]
:+1:
