### ISSUE TITLE
Filter not working on pre-filtered link

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#401]
When opening up a board with pre-defined filters/milestones/board the filter is not filtering and all issues from all boards are shown.

**Comment by aupright** [comment]
Hey @benschac, you'll be happy to know that we currently have a PR ready for this one and are just doing a final review before we incorporate it into a future update. Keep an eye out for this one coming very soon!

**Comment by benschac** [comment]
Wooooooooooooooooooooooooo!

**Comment by azenMatt** [comment]
This one is live :)
