### ISSUE TITLE
Dashboard view for putting on a large display.

### ISSUE THREAD

**Issue by benortiz** [ZenHubIO/support#402]
Would love to display the burndown charts, current issues being worked on, and upcoming issues on a display in the office to communicate our progress with the rest of the team

**Comment by aupright** [comment]
Hey @benortiz thanks for the suggestion!

I've heard from a few teams that are using large displays to show their boards in the office and communicate with rest of the team. Although this isn't on our near-term roadmap for the quarter, I can definitely see this being something we can look at if we can get enough support from the rest of the community.

Moving this one to the Discussion column for more feedback :smiley:

**Comment by benortiz** [comment]
great thanks so much! I'm thinking of something a bit more high level to communicate progress to people who don't need to be aware of the finer details.
