### ISSUE TITLE
Chrome extension button takes a while to load

### ISSUE THREAD

**Issue by Frozenfire92** [ZenHubIO/support#403]
It can take a minute or two for this window to populate

![screenshot from 2015-10-15 14 09 53](https://cloud.githubusercontent.com/assets/5893112/10521477/72ebb096-7346-11e5-819f-fac4b07a9cdc.png)

**Comment by aupright** [comment]
Hey @Frozenfire92 - are you still seeing this issue with loading time on the notifications window? A few of us have tried to replicate this internally and weren't able to do so.

**Comment by Frozenfire92** [comment]
Just tried right now and took ~5 seconds (which is a big increase from when I made the issue)

**Comment by Frozenfire92** [comment]
@philrenaud still experiencing?
