### ISSUE TITLE
Zenhub chrome extension button loads real slow!

### ISSUE THREAD

**Issue by philrenaud** [ZenHubIO/support#404]
About 45 seconds to load content in the #zh-activity-stream. I just see this most of the time:

![image](https://cloud.githubusercontent.com/assets/713991/10521498/291fb726-733e-11e5-9848-016e462d4489.png)

**Comment by Frozenfire92** [comment]
#403

**Comment by aupright** [comment]
Closing to keep the discussion centralized in #403
