### ISSUE TITLE
ability to save / bookmark board views (filter presets)

### ISSUE THREAD

**Issue by haoliu119** [ZenHubIO/support#407]
a common feature in scrum software is the ability to save / bookmark different views so you can quickly access different subsets of your issues. It would be nice if I can save a list of filter settings somewhere and quickly toggle between them without manually tweaking all the filters each time to get the desired view for different purposes. I tried bookmarking the url, because the filters are in the query parameters, but revisiting the url doesn't correctly apply the filters to the board.

**Comment by davidmmanning** [comment]
:+1:

**Comment by aupright** [comment]
Hey @haoliu119 apologies for the late reply here!

This one actually went live a few weeks ago—you can now bookmark filtered views within ZenHub and come back to those bookmarks with all of the filters correctly applied! 

Thanks again for the suggestion here, keep em coming :beers:

**Comment by haoliu119** [comment]
Fantastic. Thank you!

**Comment by AlexandreAWE** [comment]
Hello @haoliu119 

How do you save filter ?

Thx

**Comment by haoliu119** [comment]
hi @AlexandreAWE , once you applied the filters you can save the page url. the filter configurations are saved as part of the url query parameters. hope that helps

**Comment by zahrens** [comment]
@haoliu119 Hello, I was just trying this and it is not working in Firefox 52.2.1, with the plug-in I just re-installed.

**Comment by sumodm** [comment]
@haoliu119 This seems to have a problem with Chrome version 62.0.3202.94: I saved it as bookmark in bookmarks bar. Now if I am already on a Zenhub board and click on the bookmark in the bookmarks bar, it doesn't navigate to the page with url query parameters. It does work when I am on any other page including reports. Not sure if you want me to create a separate issue for this.

**Comment by kendramoroz** [comment]
@sumodm looks like you might be a few Chrome versions behind, which might be the culprit! To get a better sense of what's going on with your chrome version and extension, mind reaching out via support@zenhub.com with screenshots of what's going on so we can debug more in-depth? Looking forward to hearing from you!
