### ISSUE TITLE
Auto-Width Pipelines

### ISSUE THREAD

**Issue by Naatan** [ZenHubIO/support#413]
If I have 4 pipelines the right half of my screen goes unused because the pipelines are fixed-width. It would be nice if the pipelines would use the extra width that is available.

**Comment by aupright** [comment]
Thanks for the suggestion @Naatan! 

Moving this one to the community backlog so that we can look into this going forward :+1:

**Comment by azenMatt** [comment]
Hi @Naatan - hopefully the expand pipelines feature helps you here - as you can now decide which pipelines make the most sense to have a bit more real estate!
