### ISSUE TITLE
Ability to exclude days from milestone

### ISSUE THREAD

**Issue by cvandermeer** [ZenHubIO/support#415]
We dont work on the weekends but the burn down charts suggests we do. I would like to see an ability to exclude days from the burndown milestone

**Comment by aupright** [comment]
Thanks for the suggestion @cvandermeer!

I can see where the ability to exclude weekend days could be helpful when the defined time-range for the milestone is short enough to show individual days. I'm going to move this one into the discussion pipeline to see if other users feel the same way. If we can get enough feedback and +1's here, we can look into creating a toggle to allow teams to exclude weekends :beers:

**Comment by goanpeca** [comment]
We work on weekly sprints and this is definitely helpful! :+1:

**Comment by rafaelhbarros** [comment]
+1

**Comment by kaecyra** [comment]
+1

**Comment by azenMatt** [comment]
weekends are no longer considered as 'burnable' days on the report 😄 

If there is demand we can make this a setting, so far the response has been to keep it as a 5-day week
