### ISSUE TITLE
Bug: Clicking on the 'boards' icon changes the URL but nothing else happens (in private repo)

### ISSUE THREAD

**Issue by jmcmurry** [ZenHubIO/support#418]
Within the same GitHub organization, boards for public repositories seem to work fine, but boards for private repos  do not. Public/Private may not be *the* distinguishing factor, but it is the only one that jumps out to me.

In my private repo, when in the code view (top button), I click on the boards button and the only thing that happens is that the URL changes from https://github.com/monarch-initiative/impact to https://github.com/monarch-initiative/impact#boards. However, nothing else changes. note the discrepancy between the display and the URL. I'm using chrome. Note that there tickets and milestones and team members all exist for this repo so there should be data to populate the board.

![screen shot 2015-10-22 at 14 47 17](https://cloud.githubusercontent.com/assets/3658863/10679218/ea978e14-78cb-11e5-9fe5-40175982c3d0.png)

**Comment by azenMatt** [comment]
Hi @jmcmurry - we are taking a look at this

**Comment by azenMatt** [comment]
Would you be able to post a screenshot of any errors in your dev console?

**Comment by jmcmurry** [comment]
I just went to repeat the error after a hard reboot of my machine and don't see it anymore.

**Comment by azenMatt** [comment]
If I had to guess... this might be an API limit problem. 

If you get it again can you send through a screenshot of any console errors to support@zenhub.io and we will sort it out for you :smile:
