### ISSUE TITLE
When opening an issue from the board, sidebar items are slow to load

### ISSUE THREAD

**Issue by aeromusek** [ZenHubIO/support#419]
When I am viewing a board and click on an issue, the default GitHub controls show up immediately. The ZenHub injections (Pipeline and Estimate) are about a second delayed, which leads me to *often* click to change something like the Milestone and end up getting Labels instead. You'd think I would learn after a while, but it catches me almost every time...

**Comment by aupright** [comment]
Hey @aeromusek thanks for the feedback!

If you haven't already noticed the performance upgrade, we pushed an update this week that improves the speed at which the "pipeline" and "estimate" fields are loaded into the right-hand navigation! 

If your extension hasn't automatically upgraded, you can get this update by navigating  to your extensions window, enabling developer mode, and updated your extension to 2.11.21!

**Comment by aeromusek** [comment]
@aupright looks like I got an automatic upgrade...I just tried it, and the new speed is *wonderful*. Thanks so much!
