### ISSUE TITLE
Burndown charts based on filters

### ISSUE THREAD

**Issue by aneilbaboo** [ZenHubIO/support#422]
Provide the same filters that appear on the Kanban view for Burndown charts.

This enables a huge number of powerful capabilities: multi-repo burndowns, single-developer burndown, multi-developer burndown, multi-milestone burndown.  

I think it addresses features requested in #261 #232.

**Comment by aupright** [comment]
Hey @aneilbaboo thanks for the suggestions!

We're definitely committed to supporting these type of capabilities going forward in the second iteration of our burndown charts. While support for multi-repo milestones is highest on our radar to address this coming quarter, I'll add these other suggestions to the internal thread that we have going!
