### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#423]
I got a load error while trying to view the boards.. it was fine after I reloaded the page, but the first time the text that was displayed was difficult to read due to the opacity on the overlay

![2015-10-27 12_26_34-boards mottie_tablesorter](https://cloud.githubusercontent.com/assets/136959/10766585/3d301e92-7ca6-11e5-9ada-12abe729e42c.png)

**Comment by azenMatt** [comment]
Hi @Mottie 

Sorry to hear you were getting this error. 

Can you let me know if it starts to re-occur and we will dig into it. Thanks
