### ISSUE TITLE
Implement icon for referenced issue status within referencing issue (issue linking dependency)

### ISSUE THREAD

**Issue by jmcmurry** [ZenHubIO/support#425]
Triaging stale tickets is a terrible pain. Help me distinguish at a glance
- issues that used to be blocked
  vs
- issues that are still blocked
## Current view

![screen shot 2015-10-27 at 23 22 24](https://cloud.githubusercontent.com/assets/3658863/10781177/24b73614-7d02-11e5-8ade-eac371e285ec.png)
## Option 1: Icon only

![screen shot 2015-10-27 at 23 24 37](https://cloud.githubusercontent.com/assets/3658863/10781175/24b494a4-7d02-11e5-9319-281553be1c49.png)

Pros:simple
Con: no title. dates may be misleading?

---
## Option 2: Title and status preview

![screen shot 2015-10-27 at 23 23 54](https://cloud.githubusercontent.com/assets/3658863/10781176/24b6c88c-7d02-11e5-976b-9b27d6ccf2e8.png)

pros: title, clarity
cons: busy

At present, I'm _not_ looking for a fancy way to look at dependency graphs or anything crazy, just to do less clicking around. This may be a ticket better suited to GitHub core than to ZenHub, but I'm putting it out there just in case.

**Comment by aupright** [comment]
Hey @jmcmurry thanks for the feedback! 

I think this falls more into the GitHub realm, but given the proximity of the two products, could be an interesting feature to look into going forward. I know we have a few other open issues here around better communicating 'blockers' and 'fixes', I'll leave this one open in the discussion column however to see if we can get some more :eyes: and feedback here!

**Comment by nickbuddendotcom** [comment]
+1

**Comment by kendramoroz** [comment]
👋  Hey all! Closing in favor of https://github.com/ZenHubIO/support/issues/1184 which tracks improvements around ZenHub's dependency feature that are currently inflight to bring visualisation of blocking relationships to the Board. Feel free to send any questions our way!
