### ISSUE TITLE
Why was "hide open issues" button removed?

### ISSUE THREAD

**Issue by snario** [ZenHubIO/support#426]
This was very important for us as we have a PR view and an issue view. Can it remain optional somehow? This causes a big annoyance for our workflow.

**Comment by azenMatt** [comment]
Hi @snario 

We removed this as it was causing a lot of user confusion. We were getting daily support requests from users who could not see any issues because they had accidentally toggled this button. 

As a stop-gap solution, we decided to remove it while we figure out a better UX that makes this functionality clearer. It will be back :smile:

**Comment by snario** [comment]
Okay, would appreciate it as soon as it comes back, even a hacky solution where I have to run some JS code to enable it or something would be great for me; I used this every day

**Comment by snario** [comment]
@azenMatt any update here?

Sorry to pester as I know it is a seemingly tiny feature but this has totally broken my workflow.

**Comment by azenMatt** [comment]
It's on our back log, 

We have a some big releases soon *cough* #30 *cough* that are taking the teams focus at the moment. Once live, the better solution to this problem is at the top of our list.

**Comment by haoliu119** [comment]
@azenMatt, I strongly agree with @snario that a way to hide all issues is very crucial to our workflow. thank you for putting this on your roadmap, I understand how tricky UX is

**Comment by haoliu119** [comment]
just a thought of suggestion, perhaps instead of a group of buttons with ambiguous icons, another dropdown filter to check/uncheck different types of items to show maybe more clear to the users, kinda like a filter for layers of information.

**Comment by azenMatt** [comment]
@snario @haoliu119  And we are back! 

![image](https://cloud.githubusercontent.com/assets/7584089/11876469/b9f49df2-a49e-11e5-9352-2460594858be.png)


when you upgrade to 2.13.18 the ability to hide open issue will be back! 


After trying a few different methods, we ended up going with the same look and feel - the only difference is - ZenHub will no longer remember the state of this button. So if you refresh or exit the board and come back, it will always show your open issues. 

This should let power users like yourselves implement this into your workflow, whilst making sure other users don't get trapped onto a board with no issues from accidentally clicking that button :smile:

**Comment by snario** [comment]
Thanks!
