### ISSUE TITLE
Repos to be used on multiple boards.

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#427]
is there any way possible to link the same repo in multiple boards?

Our use case is that we have many different teams working out of the same repos.  Each team has their own unique flow, which makes things interesting when sharing one large board linked with a few different repos.

I know this might be a super tall order to fill, I just wanted to ask :)

**Comment by ppat** [comment]
This would be useful to us as well.

Consider this scenario:

Repo1 and Repo2 are part of a single project so you need to see them on the same board. But Repo2 contains a codebase that is shared and use by many other projects. So people working on most project may have changes to the shared codebase in Repo2. 

In our case, we have several shared codebases. For example, our automation framework is shared. As is some of our base libraries.

**Comment by dermatobia** [comment]
+1 :+1:

**Comment by kimb90** [comment]
Don't forget all the people who up-voted this issue. We all want it.

![screen shot 2015-11-02 at 2 02 00 pm](https://cloud.githubusercontent.com/assets/6993579/10891172/623b4a54-816a-11e5-8144-b1333addff00.png)

**Comment by azenMatt** [comment]
@kimb90 - these 25 people in #139 also want this :) 

![image](https://cloud.githubusercontent.com/assets/7584089/10987425/0d2ee8f6-83e8-11e5-9d1c-8549720cc596.png)


I understand the scenario here and can see how it would be useful. At the moment we are focused on making the single board experience the best possible, but are open to expanding this to allow multiple boards that can appear in different locations. I am going to close this issue and use #139 to track this through to competition. 


As a stop-gap solution, I would recommend joining the boards together and then using the repo filter on the board to only select those you are interested in. Along with filtering on milestone/label/assignee - this should let you show only the issues you are interested in.
