### ISSUE TITLE
Historical velocity shown when looking at closed milstones

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#428]
Estimating is awesome!  

I would love a way to be able to see the number of total points my team completed quickly when looking at old milestones AND filter by label to adjust that combined total point value because different teams in my organization work in the same repo but filter via label.

**Comment by aupright** [comment]
Hey @benschac thanks for the feedback! 

This one actually looks quite similar to #357 that one of our other users previously issued up. We definitely understanding the user case here and would love to explore this further in some of the v2 itterations to our burndown charts that we have planned in our roadmap. Closing this one out for now, but definitely appreciate the suggestion :beers:
