### ISSUE TITLE
Add checklist progress

### ISSUE THREAD

**Issue by Frozenfire92** [ZenHubIO/support#429]
If I have a checklist in the first post in a github issue like so

- [x] item one
- [x] item two
- [ ] item three
- [ ] item four

I can see it in the default github issues view like so

![screenshot from 2015-10-31 14 57 04](https://cloud.githubusercontent.com/assets/5893112/10865106/e366539e-7fdf-11e5-8730-ace96ae1e826.png)

I would like to see this in the boards view aswell

**Comment by SeanTAllen** [comment]
+1

**Comment by lispmeister** [comment]
:+1:

**Comment by Frozenfire92** [comment]
Maybe duplicate of #197

**Comment by azenMatt** [comment]
Thanks @Frozenfire92 - yes lets track in #197 

At the moment, our main focus is on improving the rendering speed of the board. Once we have this to a level we are happy with - we will start adding more things that need to be rendered :grinning:
