### ISSUE TITLE
Some repos not showing up on boards

### ISSUE THREAD

**Issue by Frozenfire92** [ZenHubIO/support#435]
We have a central repository where we link our other repos to this board. We are at 6 repos now, the most recent repo is not showing up on the board even when clicking show all. I have tried unlinking and relinking the repo

**Comment by Frozenfire92** [comment]
It turns out, having a repo added that wasn't added to the teams in the organization caused issues with zenhub. Once the repo was added to the correct team the board fixed itself

**Comment by aupright** [comment]
Hey @Frozenfire92, happy to see that you were able to solve this one! I'm closing this out in terms of immediate actionables but will keep this issue in my back-pocket if other users reach out with similar feedback. Cheers :beers:
