### ISSUE TITLE
Stop opening a new tab to GitHub

### ISSUE THREAD

**Issue by dlh3** [ZenHubIO/support#439]
I believe this happens every time that the Chrome extension is updated.  It is disruptive and annoying.  I am removing ZenHub from Chrome until this behaviour is changed.

Otherwise, I like what your team has produced.

**Comment by azenMatt** [comment]
Hi @dlh3, 

We are looking into ways to fix this and hope to have a solution soon, 



> Otherwise, I like what your team has produced.

Thank you :smile:
