### ISSUE TITLE
Cross-repo Issue Management/Milestones

### ISSUE THREAD

**Issue by Jessalyst** [ZenHubIO/support#44]
Use case is lots of repos; want a single Kanban for the whole org.

**Comment by whyrusleeping** [comment]
I would love to have this feature.

**Comment by jbenet** [comment]
Same here-- the repo abstraction isn't great for projects that want highly modular systems + code. It would be awesome to be able to have one board which would be
a sort of union of multiple other boards

**Comment by SPopenko** [comment]
Hi guys, any updates here? Plans?

**Comment by azenMatt** [comment]
Hi @SPopenko - our top priority at the moment, expect it soon :smile:

**Comment by azenMatt** [comment]
![image](https://cloud.githubusercontent.com/assets/7584089/7395398/7c00fe0c-ee4e-11e4-844a-fa684a8f7ca6.png)


The ZenHub team are all **very** excited to announce that we are now live with this feature!


The chrome store should be pushing the update through to you at the moment, but if not, you can force an upgrade check via chrome://extensions in developer mode. The feature is in version 2.0.0 and up.

The ability to link existing board together will now appear as a new filter at the top of each board. We have put together a short blog post here - https://www.zenhub.io/blog/multi-repo-boards-have-arrived/ - to help everyone get started. 

I'l keep this issue open for a couple of days incase anyone has any questions or feedback

Enjoy!

**Comment by philips** [comment]
Multi repo boards cross org doesn't seem to be part of the feature :(

**Comment by azenMatt** [comment]
Hi @philips - for V1 of this feature we wanted to keep it as single Org to avoid cross-org permission issues and get it into everyones hands as fast as possible. 

I just opened #219 to track the ability to link these as multi-org boards as a V2 of this feature

**Comment by kevindashgit** [comment]
I didn't see anyone suggest this yet -  It would be very nice to have a `select all` feature here (that remains dynamic as new repos are added).

**Comment by johnmcmillion** [comment]
One Board for tracking issues across multiple repos is helpful.  

But what would be most helpful would be supporting One Issue that involves multiple repos.   Is that possible with Zenhub currently?
