### ISSUE TITLE
Issue Comment Tracking & Resolution

### ISSUE THREAD

**Issue by vmarinucci** [ZenHubIO/support#465]
Hi there.

What does ZenHub think about 'Comment' resolution? 

Problem: Sometimes issue's comment lists can get long and are unclear to what portion of the issue body they impacted. 

1) Might be helpful is if there is a way to relate a question (comment) to a portion of the issue body. Replies to that question (comment) would somehow be visually related.

2) Be able to resolve and hide that comment+its replies if it is resolved, making it still traceable to 'why' a decision was made in the issue body.

This is similar to what Confluence or Google Docs does. 

The ability to have something like this might help reduce another document for a _small features_ or issues requiring any discussion thats could exist just in GH, while keeping history on how said feature shaped up + keeping the issue clean.

Thoughts ZenHub Team?

Thanks!

**Comment by aupright** [comment]
Hey @vmarinucci thanks for the feedback here! We're no strangers to long comment threads ourself, so I can definitely see where this would have a big impact on usability. Internally we try to use +1's as much as possible to cut down on comment clutter and make sure that each comment is actionable; I realize that this isn't applicable in every case however.

As a starting point in the discussion here, I'd like to move this to the discussion column to see if we can  get some more feedback and +1's. If this is a paint felt by the rest of the ZH community (guessing it is), then we'll have some extra motivation to move this one up the chain. 

Thanks again for the suggestion here :beers:

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
