### ISSUE TITLE
When retrospectively adding a New Issues column, some issues leave their existing position in the next column over and appear in the new issues column

### ISSUE THREAD

**Issue by debdoop** [ZenHubIO/support#467]
Our Product Owner changed the name of the first column from New Issues to Parked / Low priority in order to sort his backlog. But we want to re-instate the New Issues column for new issues to appear in before they are prioritized and sorted into a column. When the column is last, there are no issues in it, but when I move it to be first there are 8 issues (created up to 9 days ago) that pop back in there.

**Comment by azenMatt** [comment]
Hi @debdoop - that doesn't sound good! Can you email me at support@zenhub.io and we will get this sorted for you
