### ISSUE TITLE
Bulk move from swimlane to swimlane 

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#468]
Is there any way to move multiple issues from swimlane to swimlane at the same time?

**Comment by azenMatt** [comment]
Soon :) 

This should be live in the near future. It is having the final layers of polish added at the moment!

**Comment by benschac** [comment]
Woooo! :)

On Fri, Nov 13, 2015 at 6:59 PM, Matt Butler <notifications@github.com>
wrote:

> Soon :)
>
> This should be live in the near future. It is having the final layers of
> polish added at the moment!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/468#issuecomment-156593691>.
>



-- 
*Benjamin Schachter *• Project Manager
* <http://www.dramafever.com/>*    |   bschachter@dramafever.com

**Comment by andycleff** [comment]
Yay!

**Comment by vmarinucci** [comment]
Party!!

**Comment by azenMatt** [comment]
v 2.15.1 was just released that allows you to move multiple issues at the same time :smile: 

Just hover over the right hand corner of the card, and select the gear icon:

![image](https://cloud.githubusercontent.com/assets/7584089/12286190/c92f11f2-b976-11e5-85a2-509bce07741c.png)

**Comment by benschac** [comment]
Wooooooo! y'all rule!
