### ISSUE TITLE
Cannot set estimate to "0"

### ISSUE THREAD

**Issue by aneilbaboo** [ZenHubIO/support#471]
1. Set the estimate of an issue to "0"
2. Reload the page
3. The estimate goes back to unestimated.

**Comment by azenMatt** [comment]
This is part of our validation to ensure only positive numbers: 

![image](https://cloud.githubusercontent.com/assets/7584089/11449253/456d4e00-9523-11e5-8b4e-4432ece00683.png)


we are looking into ways to improve this to allow 0, t-shirt sizes, infinity signs - and other more imaginative requests!

**Comment by azenMatt** [comment]
lets close this one and il post updates in the existing issue #438
