### ISSUE TITLE
When reopening issues, you need to refresh to set an estimate

### ISSUE THREAD

**Issue by cromedome** [ZenHubIO/support#472]
The ability to attach an estimate to an issue does not automatically reactivate when you reopen a closed issue. I can work around it by immediately refreshing the page, but that's annoying :)

If course, if you implemented #366, this would be less of a problem for me :)

Thanks in advance!

**Comment by azenMatt** [comment]
Hi @cromedome we are looking into implementing #366 which will solve this issue for you :smile:
