### ISSUE TITLE
ZenHub doesn't seem to work with GitHub's new repository look

### ISSUE THREAD

**Issue by dvicory** [ZenHubIO/support#473]
GitHub [recently launched a new look](https://github.com/blog/2085-a-new-look-for-repositories) for repositories. I opted-in straight away and our team is just now experimenting with ZenHub. I noticed that I can't scroll to see the whole board but others on my team who have not opted in are able to scroll.

I can't find a method to disable the new look for me so for now I'm stuck with it like this. Attached a screenshot with confidential information removed. There are additional pipelines to the right of "Merged".
![screen shot 2015-11-18 at 11 49 23 am](https://cloud.githubusercontent.com/assets/1542454/11252377/c42206fe-8dea-11e5-8d06-f7ff9016b09e.png)

**Comment by KbellTMA** [comment]
I'm experiencing the same issue. The cursor has to be within the columns to scrolls left or right and the cursor has to be in a particular column to scroll up and down within the column. 

My issue is that the grey columns cut off as in the screenshot which means that words are cut off even though I have scrolled as far down as I can.

**Comment by azenMatt** [comment]
Hi @dvicory @KbellTMA - we are working on a fix for this at the moment - will be live ASAP

**Comment by azenMatt** [comment]
2.12.9 is now live with a fix to this issue! 

If chrome hasn't already pushed this update to you, you can update at chrome://extensions under developer mode -> update extensions now

Please let me know if you have any other issues!
