### ISSUE TITLE
estimate and pipline are not saved when creating an issue in the board view

### ISSUE THREAD

**Issue by illfang** [ZenHubIO/support#475]
As the title suggests the estimate and pipline changes are note getting saved when creating a new issue in the board view.
Actually, it also happens that the defined estimate changes the estimate of an other issue.

See the gif below.
![issueissue](https://cloud.githubusercontent.com/assets/2493562/11259343/483dd472-8ea4-11e5-803b-82d4fff6a8b7.gif)

maybe related #292 but the estimate is also affected.

**Comment by aupright** [comment]
Hi @illfang thanks for sending this one through!

Are you still noticing this issue with time estimates and pipeline status not being properly saved? If so, could you please send a message to support@zenhub.io along with the version number of the extension that you are using? We've tried a few times to recreate this one internally and haven't been able to do so with the latest version of the extension - 2.12.23.

**Comment by illfang** [comment]
Unfortunately, the problem still persists until now. I have reproduced the problem using two different systems / browsers

Google Chrome Version 47.0.2526.106 m (Windows 8.1 Pro)
ZenHub for GitHub 2.15.1
Firefox 43.0 (Mozilla Firefox for Ubuntu, Xubuntu 15.10)
ZenHub 2.14.2

**Comment by aupright** [comment]
Thanks for the update @illfang - taking a look into this one again.
