### ISSUE TITLE
Question: Does Priority Order Change When Moving issues from Milestones.

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#477]
Hi,

I was curious how moving issues from one milestone to the next works within ZH.  Ex.  some issues didn't make it in this sprint and next to get moved to the next. If there are issues coming from other boards how does ZH organize/keep track of their position in a swimlane?

**Comment by azenMatt** [comment]
Hi @benschac 

In terms of milestones, ZH treats these as a filter, so if you have a pipeline full of issues, they all exist in a certain order without weight given to which milestone they belong to. 

So if you were to swap which milestone an issue belongs to, it stays in the same relative position in the pipeline against the other issues, it does not move to the top, or bottom against the other issues. 

I hope these helps, if you have a particular example in mind it would be useful for me to demonstrate with, or have a preference of how this should work, please let me know!

**Comment by benschac** [comment]
So if they're all just filtered let's say for arguments stake I have issues ordered in a ready to be scheduled milestone and a backlog milestone and then in move everything in the backlog milestone to the ready to be scheduled milestone.  Would the new issues from backlog just be appended to ready to be scheduled?
