### ISSUE TITLE
Burndown Problems

### ISSUE THREAD

**Issue by cultiva** [ZenHubIO/support#478]
Please take a look my screenshot.

There are three problems.

- "Total story points" is not a sum of estimated points of registered issues.
- "Completed story points" is not a sum of estimated points of closed issues.
- graph doesn't fall although there are some issues closed on Nov17 or Nov18.

Might be similar to what he/she refers in the issue below.
https://github.com/ZenHubIO/support/issues/398

Would you fix them?
And is there anything I can do to solve these problems?

![capture](https://cloud.githubusercontent.com/assets/13759212/11290753/081d82dc-8f7d-11e5-8623-b3c369dc5081.PNG)

**Comment by azenMatt** [comment]
Hi @cultiva - we believe this is a timestamp issue that GitHub supplies, 

@aupright has replied to your support email on this so we will get you back up and running as soon as possible!
