### ISSUE TITLE
Wrong issue title being posted under certain conditions when using ZenHub with Slack

### ISSUE THREAD

**Issue by stefafafan** [ZenHubIO/support#480]
Here is how I got the problem:
1) Click on issue A, then click on the Commits tab to go to that page.
2) Hit the back button on the browser to go back to the boards view.
3) Click on issue B, then click on the Pipeline selector and change issue B's location.
and what I got with this is a post on Slack saying that I moved an issue, which has the issue number of issue B but an issue title of issue A.

**Comment by azenMatt** [comment]
Hi @stefafafan - myself and some other team members have not been able to replicate this issue. 

If it is still occurring for you, can you drop me an email at support@zenhub.io and we will get to a root cause!
