### ISSUE TITLE
Injected "Boards" and "Burndown" navigation elements do not have hrefs, so they cannot be opened in a new tab/window

### ISSUE THREAD

**Issue by rmacklin** [ZenHubIO/support#482]
Often times I like to open different GitHub pages in a new tab or window (e.g. to refer to a pull request while commenting on an issue).
GitHub's standard Navigation items are all links with hrefs, which enables me do this (via Cmd+click or right-click -> open in new tab). ZenHub's injected navigation items do not have hrefs, so you cannot do this. These screenshots illustrate the difference:

GitHub standard navigation item:
<img width="613" alt="screen shot 2015-11-20 at 11 56 31 am" src="https://cloud.githubusercontent.com/assets/1863540/11310395/2f032b8a-8f7e-11e5-9469-990362e5f1a5.png">

ZenHub injected navigation item:
<img width="707" alt="screen shot 2015-11-20 at 11 57 02 am" src="https://cloud.githubusercontent.com/assets/1863540/11310403/37e96976-8f7e-11e5-967b-5e462c9d02ae.png">

Notice that there are no options to open "Boards" in a new tab or window (same goes for "Burndown"). This would be immediately fixed by giving these links hrefs of `"#boards"` and `"#burndown"`, respectively. I edited the DOM myself to verify this fix. Please implement it in ZenHub :)

**Comment by azenMatt** [comment]
hi @rmacklin 

As the boards and burndowns work as overlays, we have had issues with getting the open in new tab functionality working, 

We are tracking this in #342 and hope to have a better way that enables this soon

**Comment by rmacklin** [comment]
Hi @azenMatt,

> As the boards and burndowns work as overlays, we have had issues with getting the open in new tab functionality working

Can you clarify this? What are the issues? (I didn't see it in #342.) I'm curious because, as mentioned above, manually adding the hrefs allowed me to open the boards/burndown in a new tab.
