### ISSUE TITLE
Add a confirmation to ticket modal

### ISSUE THREAD

**Issue by OBCENEIKON** [ZenHubIO/support#491]
If the ticket text has been changed, a confirmation dialog should pop up when closing the modal if ticket has not been saved.

**Comment by aupright** [comment]
Hey @OBCENEIKON thanks for the feedback here - we automatically save a draft for new issue comments, so I don't think it would be difficult to extend this functionality when editing existing comments. Moving this one to the community backlog as something to look at going forward :beers:

**Comment by sbearcsiro** [comment]
@aupright Our BA likes to work directly in the Zenhub board UI and edit story descriptions within the issue popup window.  Automatically closing the popup when she clicks outside it (to eg bring the browser window back into focus) has lost her work numerous times.  Would it be possible to add a quick confirmation first before dismissing an issue with an active description editor?

**Comment by kendramoroz** [comment]
@sbearcsiro Kendra here from the support team! The dialog window from the Board will automatically save the information that has been typed in should you accidentally click off of it (similar to navigating away from an issue in GitHub and then returning to the same issue to find your comment still in draft mode). Would you be able to confirm if you're using ZenHub for cloud, or a version of ZenHub Enterprise? Happy to dig deeper into why your colleagues are not finding the dialog save your work. Feel free to send through this information to support@zenhub.com if you'd like to keep it private as well.
