### ISSUE TITLE
Horizontal scroll resetting

### ISSUE THREAD

**Issue by dpgover** [ZenHubIO/support#492]
Every time I close an issue modal, the horizontal scroll resets to the start of my panel.

**Comment by azenMatt** [comment]
I get this one as well - it is very annoying! 

We will get a patch out very soon!

**Comment by srossross** [comment]
please fix this soon. this is very disruptive.

**Comment by rafaelhbarros** [comment]
:+1:

**Comment by azenMatt** [comment]
this is now fixed on the latest version 2.13.9 :beers:
