### ISSUE TITLE
Burndown does not show

### ISSUE THREAD

**Issue by srossross** [ZenHubIO/support#494]
Our burndown is no longer visible https://www.dropbox.com/s/l6uet1ye6elv4ml/Screenshot%202015-12-04%2013.49.14.png?dl=0

**Comment by austinshenk** [comment]
Is your board broken as well?

**Comment by srossross** [comment]
Yes, they both seem to be broken.

**Comment by austinshenk** [comment]
I'm experiencing the same issues on both chrome and firefox versions.

**Comment by DropMotion** [comment]
Same here. And boards is broken too

**Comment by millsbt** [comment]
Zenhub posted an announcement to twitter that they are experiencing interruptions.

**Comment by srossross** [comment]
In case it helps here is the browser log:

![screenshot 2015-12-04 14 39 18](https://cloud.githubusercontent.com/assets/741611/11603198/e8e12e96-9a94-11e5-9d35-4560c84dc1ba.png)

**Comment by Cassidy-Robertson** [comment]
Thanks for reaching out! We've just issued a fix for Chrome, please update your extension to version 2.13.5. 

For those of you using Firefox you can expect an update shortly and I will reach out here with any new information.

**Comment by Cassidy-Robertson** [comment]
Firefox has also been updated, please update to version 2.13.6. 

cc: @srossross @millsbt @DropMotion @austinshenk

**Comment by srossross** [comment]
Works for me. Thank you for the quick turn around
