### ISSUE TITLE
Everytime I open GitHub, the ZenHub notifications pop up (the product tour notifications)

### ISSUE THREAD

**Issue by stevepessah** [ZenHubIO/support#498]

**Comment by azenMatt** [comment]
Hi @stevepessah - that shouldn't happen! 

Can you let me know what version you are on? Can you try and update (via chrome://extensions/ -> Developer mode -> Update extensions now) to the latest version 2.13.5 and see if you still get this? 

Thanks

**Comment by stevepessah** [comment]
@azenMatt I think it was at 2.13.5 but I updated any way. So far so good! Will let you know if it pops up again.

**Comment by diafygi** [comment]
Happens to me, too. Could have something to do with having Firefox settings to never allow 3rd party cookies?

**Comment by azenMatt** [comment]
> Happens to me, too. Could have something to do with having Firefox settings to never allow 3rd party cookies?

possibly - we are looking to come up with a better solution here than relying on this - we should have something live shortly

**Comment by stevepessah** [comment]
@azenMatt so I've only been using Chrome.. The issue has for the most part stopped, although it shows every now and then still.

**Comment by clemensch** [comment]
also happens to me using chrome. This is pretty annoying and NOT "awesome" ...

**Comment by azenMatt** [comment]
Hi All - this should now be resolved in the latest version (v2.15.77) as the logic for this has been removed from local storage so won't be lost on a cache clear. 

Please let me know if you have any further issues once upgraded and I will get them fixed! thanks
