### ISSUE TITLE
Bug: Upload file icon gets massive

### ISSUE THREAD

**Issue by robeastwood** [ZenHubIO/support#499]
I've noticed a bug in firefox when leaving an issue open for a while in my browser that the "click or drag files here powered by zenhub" icon gets huge like this:

![capture](https://cloud.githubusercontent.com/assets/2145180/11654679/8da9bd78-9d9f-11e5-85b2-7af1d2ded7d5.PNG)

I'm not 100% sure what triggers it when it happens, some kind of delayed-reaction CSS error or something maybe. If i refresh the page everything is back to normal.

**Comment by Mathieuu** [comment]
Hi, thanks for the bug report. 

Did it often happen to you ?

An extension update could be responsible of that. When Firefox updates an extension, the previous version is completely removed and a new one is installed. 

When the previous version is removed, ZenHub css is removed from GitHub causing ZenHub elements to be displayed without any formatting. 

Disabling the ZenHub extension while a GitHub issue is opened in another tab should reproduce the same behavior.

A fix to reduce the size of the icon should be out soon.

**Comment by robeastwood** [comment]
Sorry, I didn't take note, other than I've noticed it a few times.

And yep I see what you mean about disabling the addon, it does indeed trigger it.

Thinking about it, i noticed it mostly over the weekend when you had issues with the service. I didn't know that at the time so I was disabling/enabling/reinstalling the addon a few times.

Probably a very minor edge case then! Cheers

**Comment by azenMatt** [comment]
the latest version of ZenHub depreciated the file uploader so this bug will be resolved!
