### ISSUE TITLE
BUG: Board view not keeping place when issue popover exited

### ISSUE THREAD

**Issue by justmatt** [ZenHubIO/support#500]
__Context__
15 boards.

__Background Steps__
- Open `Boards`
- Scroll to board near far right (Board No12)
- Click and open issue popover
- Do work
- Close issue popover

__Expected Behaviour__
- Stays focused on `Board No12`
- Keeps scroll position within board

__Current Behaviour__
- View resets to focus on `Board No1` (far left)
- Loses scroll position within board

**Comment by azenMatt** [comment]
thanks @justmatt - we are fixing this right now

**Comment by azenMatt** [comment]
Just fixed on v2.13.9! 

Live now for Chrome, 

Processing for approval on Firefox, it will be live there as soon as it is signed (normally a couple of hours slower than the chromestore approval)
