### ISSUE TITLE
ZenHub-able

### ISSUE THREAD

**Issue by kevinSuttle** [ZenHubIO/support#504]
I just put a label on things that I thought ZenHub could reasonably add. https://github.com/kevinSuttle/github/labels/Zenhub-able Feel free to cherry-pick or comment.

**Comment by azenMatt** [comment]
very cool! I will take a look :smile:

**Comment by kevinSuttle** [comment]
:+1:

**Comment by kevinSuttle** [comment]
A few more have been added. Thanks.

**Comment by azenMatt** [comment]
Hi @kevinSuttle - thanks for collating these, I added some comments in that repo. 

I'm going to close this issue - but please keep the ideas coming! I am also watching that repo now so should get updates.
