### ISSUE TITLE
Updates made to the labels are not being shown in the Boards view

### ISSUE THREAD

**Issue by rtoor** [ZenHubIO/support#506]
Specifically after changing the name of a label, I'm finding the old name is still being shown on the board.

**Comment by aupright** [comment]
Hi @rtoor - it's likely that this has to do with a similar caching issue to what some users have experienced here: #244. As an initial attempt to troubleshoot this, can you try visiting an issue with the old label attached and updating an element of that issue (such as changing the title)? This, followed by a manual refresh, should update the label cache and force the new labels to be visible.

**Comment by azenMatt** [comment]
We have a new caching process live for this now - please let me know if you still see issues but it should now be much smoother!
