### ISSUE TITLE
Accidentally hitting "Esc" key looses my issue edit.

### ISSUE THREAD

**Issue by ijstokes** [ZenHubIO/support#507]
If I'm in the midst of adding or updating a comment on a ticket then I **do not** want an accidental key stroke over `ESC` to abort my carefully crafted (but not yet complete) comment.

**Comment by azenMatt** [comment]
Hi @ijstokes - this should be cached - so if you jump back into the issue after accidentally exiting it, your un-submitted comment will still be present. 

Does this not work for you?
