### ISSUE TITLE
Add ability to create Milestone/Label on a multi-repo board once for all repos.

### ISSUE THREAD

**Issue by ydaniv** [ZenHubIO/support#512]
It makes a lot of sense to have a milestone/label created in the context of a board to be available immediately on all connected repos.

**Comment by wreyniers** [comment]
:+1:

**Comment by azenMatt** [comment]
making multiple repos work better together is one of our themes for 2016, so expect to see improvements here! 

#298 already covers the general theme here so I am going close this issue and will keep updating there!

**Comment by ydaniv** [comment]
:+1:
