### ISSUE TITLE
Clicking card on the board throws an error

### ISSUE THREAD

**Issue by wzin** [ZenHubIO/support#515]
How to reproduce:

1. Chrome Version 47.0.2526.80 (64-bit)
2. Click an issue on the board e.g.

![screen shot on 2015-12-16 at 17-44-55](https://cloud.githubusercontent.com/assets/353944/11847305/046c93da-a41d-11e5-912b-b9cae19413f6.png)
3. Quick view is going to hang like that:
![screen shot on 2015-12-16 at 17-42-11](https://cloud.githubusercontent.com/assets/353944/11847278/e82509e6-a41c-11e5-8a2e-a5a30e52689b.png)

Throwing following error:

Screenshot:

![screen shot on 2015-12-16 at 17-42-22](https://cloud.githubusercontent.com/assets/353944/11847295/f992ae04-a41c-11e5-807c-e15bf8a8badd.png)

Text:

```
chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:15 Uncaught TypeError: e.match is not a function
chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:15 Uncaught TypeError: e.match is not a functionc.extractIssueContentFromGHPage @ chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:15s.Model.extend.handleSuccessRequest @ chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:25(anonymous function) @ chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:25h @ chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:3d.fireWith @ chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:3n @ chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:4(anonymous function) @ chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:4
4chrome-extension://ogcgkffhplmphkaahpmffcafajaocjbd/js/built/main.js:15 Uncaught TypeError: e.match is not a function
```

**Comment by azenMatt** [comment]
Hi @wzin - we are looking into this right now, we should have an update out very soon

**Comment by azenMatt** [comment]
v2.13.17 just went live which contains the fix for this! Your browser should push an update to you shortly, else you can manually ask it to update via the extensions page!
