### ISSUE TITLE
Can't open issues from board

### ISSUE THREAD

**Issue by calvinps** [ZenHubIO/support#519]
When I click on an issue, it doesn't open but rather stops here:

![image](https://cloud.githubusercontent.com/assets/6371960/11850495/9e150444-a3fb-11e5-9713-f55c94f8de65.png)

The error is that "e.match is not a function"

Environment: Chrome on Windows 10 pc. 
Zenhub version 2.13.17

**Comment by azenMatt** [comment]
Hi @calvinps 

v 2.13.17 should contain a fix for this, 

Would you be able to do a refresh and try again on a fresh board - then it should work for you? 

It was broken for everyone, but this new version is back working: 

![image](https://cloud.githubusercontent.com/assets/7584089/11850661/9da8a7d0-a3e3-11e5-8c4c-1194986a6eb8.png)

**Comment by calvinps** [comment]
Sorry I looked in the wrong place for the version number; I was still on .16. 

After updating all is good.
