### ISSUE TITLE
Github error loading issues in board modal

### ISSUE THREAD

**Issue by diafygi** [ZenHubIO/support#521]
When you click on an issue in the Board interface (both Firefox and Chrome), it opens a modal with that issue. However, recently it started showing an error in the modal instead of the issue contents.

Here's the error:
```
Error: the GitHub page cannot be loaded.

Make sure Issues are enabled in the repository settings.
```

**Comment by azenMatt** [comment]
Hi @diafygi - can you update to v2.13.17? We release that this morning to fix this bug

**Comment by dogancelik** [comment]
I have this issue in Firefox version, doesn't occur in Chrome version.

![board-error](https://cloud.githubusercontent.com/assets/486818/16929521/d4de8da8-4d40-11e6-80b3-f5e7c61857ee.png)

ZenHub version: `2.20.10`
Firefox version:  `49 Dev`

**Comment by azenMatt** [comment]
Hi @dogancelik - is this a reproducible error? We sometimes see this if there is no internet connection when the modal tries to load - or if it is a poor connection and times out. 

We will take a look into what else could be causing this

**Comment by dogancelik** [comment]
According to my colleague, he doesn't have this issue. The cause may be that I was added to the team and the repository recently, when the related repository was created long time ago. I have write access to this repository.
