### ISSUE TITLE
Issues sometimes stuck in loading state

### ISSUE THREAD

**Issue by robinwelsh** [ZenHubIO/support#522]
"ZenHub is loading your issue..."

*gets coffee*

"ZenHub is loading your issue..."

*makes lunch*

"ZenHub is loading your issue..."

O___o

**Comment by azenMatt** [comment]
you will be waiting a while :smile: 

this is a bug in 2.13.16 -> we released 2.13.17 this morning to fix it. 

If you can upgrade your extension to that version and then refresh the page - you should find it fixed!

**Comment by robinwelsh** [comment]
well 💩 — Thanks, Matt!

**Comment by dwijnker** [comment]
Happening for me currently. From the console:

> main.js:12 WebSocket connection to 'wss://api.zenhub.io/socket.io/?token=fe098e96d4454712f52677b362ff2b1eaa31edb278f65b2dce8909bb5ff77b6369ae58def2ca485a&EIO=2&transport=websocket' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1

**Comment by azenMatt** [comment]
Hi @dwijnker - that looks to be the same issue as -  https://github.com/ZenHubIO/support/issues/720#issuecomment-218046236

Are you able to follow those steps and see if it is resolved?

**Comment by dwijnker** [comment]
@azenMatt : thanks, that resolved it for me as well.
