### ISSUE TITLE
ZenHub issues aren't loading

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#523]
![screen shot 2015-12-17 at 12 15 59 pm](https://cloud.githubusercontent.com/assets/2502947/11876619/c59c519e-a4b8-11e5-8151-cf379021329c.png)

and it's still loading!

**Comment by mmoraes** [comment]
I was having the same problem but finally got it working again.

It seems like your browser (mine too) didn't update the Zenhub extension to the latest release. You just have to uninstall and reinstall it.

**Comment by benschac** [comment]
Ooooooooooooo thx!

On Thu, Dec 17, 2015 at 12:30 PM, Mateus Moraes <notifications@github.com>
wrote:

> I was having the same problem but finally got it working again.
>
> It seems like your browser (mine too) didn't update the Zenhub extension
> to the latest release. You just have to uninstall and reinstall it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/523#issuecomment-165522089>.
>



-- 
*Benjamin Schachter *• Project Manager
* <http://www.dramafever.com/>*    |   bschachter@dramafever.com

**Comment by azenMatt** [comment]
:+1: 

We are working on a way to better update for these urgent fixes. Chrome checks every 5 hours, and Firefox once per day. So it is easy to get stuck with an old version for too long. 

Glad this is woking for you now!

**Comment by benschac** [comment]
working here too.  Thanks!

On Thu, Dec 17, 2015 at 12:42 PM, Matt Butler <notifications@github.com>
wrote:

> Closed #523 <https://github.com/ZenHubIO/support/issues/523>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/523#event-494958185>.
>



-- 
*Benjamin Schachter *• Project Manager
* <http://www.dramafever.com/>*    |   bschachter@dramafever.com
