### ISSUE TITLE
New label colors aren't reflected on Boards

### ISSUE THREAD

**Issue by aneilbaboo** [ZenHubIO/support#525]
To reproduce:

1. Go to Boards, create an issue and label it
2. Go to Issues tab, select labels and change the label color
3. Go back to Boards and observe that the label hasn't changed color

**Comment by azenMatt** [comment]
Hi @aneilbaboo - have your label colours updated? 

We don't include updates to label colours in our issues cache, so to see these on the board, either an update will need to occur that will invalidate the cache (such as a change to the label name) or it will need to expire (after an hour) 

please let me know if these still haven't updated and I can look into it further. 

We made this decision based on limiting the number of API calls we need to make to GitHub - to make sure what we class as the 'must have' updates (issue name, assignee etc) always make it though. Happy to re-think this if you disagree :smile:

**Comment by aneilbaboo** [comment]
@azenMatt They did eventually update.  Thanks!

**Comment by azenMatt** [comment]
:+1:
