### ISSUE TITLE
New issues not appearing on board until refresh

### ISSUE THREAD

**Issue by barrywark** [ZenHubIO/support#528]
# Description

New issues are not appearing on our board until after a page reload. The board has multiple repos shown.
# Repro
1. Click "New issue"
2. Enter information, selecting pipeline (e.g. "Backlog")
3. Submit new issue
4. Search page for issue title

**Comment by aupright** [comment]
Thanks for the feedback here @barrywark - I've issued this one up internally so that we can take a closer look into what might be causing this. Stay tuned for an update!

**Comment by ydaniv** [comment]
@aupright what's causing this is browser cache. You have huge problems with this all  over, mostly with boards but also with the ToDo list.
Start with cache busting your XHRs. This causes major dissatisfaction with service when things just don't update, even after subsequent refreshes.

**Comment by Anvil102** [comment]
+1: ~50% of the time issues either have a high latency to update in general (either new issues or edited issues) or do not update at all (in the case of newly created issues).

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board. If anyone is experiencing issues with New Issues not populating, get in touch via support@zenhub.com or ping me here and we'll take a look!
