### ISSUE TITLE
Firefox addon crashes tabs

### ISSUE THREAD

**Issue by robinwelsh** [ZenHubIO/support#530]
In the past few releases of FirefoxDeveloperEdition 45.0a2 (2015-12-22) (aurora) and Firefox Nightly 46.0a1 (2015-12-22), the ZenHub Firefox add-on crashes most if not all tabs indefinitely.

To repro, ensure you're running one of those channels, and that you have zenhub installed. Go to GitHub and log in to your boards.

Thankfully it's working in Firefox 43.0.1 stable release channel.

**Comment by hly990** [comment]
Issue moved to [ZenHubIO/API #26](https://github.com/ZenHubIO/API/issues/26) via [**ZenHub**](https://www.zenhub.com/)

**Comment by azenMatt** [comment]
@robinwelsh - the root cause of this has now been fixed by the firefox team and so will start filtering down in the dev / nightly releases and won't impact the stable release
