### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#531]
I was trying to map out which keys GitHub uses and found the <kbd>z</kbd> opens up ZenHub's To Do page... this isn't shown in your [list of keyboard shortcuts](https://www.zenhub.io/moreFeatures#KeyboardShortcuts).

I think a really cool idea would be to allow us to add custom shortcuts... basically allow us to set a key combo like <kbd>z</kbd> + (<kbd>0</kbd> through <kbd>9</kbd>) to go to a set page.

Here are some example ideas:

* <kbd>z</kbd> + <kbd>0</kbd> - open ZenHub settings panel
* <kbd>z</kbd> + <kbd>1</kbd> set to `"{repo}/network"` - go to network page
* <kbd>z</kbd> + <kbd>2</kbd> set to `"{repo}/graphs/traffic"` - traffic page
* <kbd>z</kbd> + <kbd>3</kbd> set to `"{repo}/pulse"` - pulse page
* <kbd>z</kbd> + <kbd>4</kbd> set to `"{repo}/wiki/ChangeLog"` - custom wiki page
* <kbd>z</kbd> + <kbd>5</kbd> set to `"{root}/stars"` - go to my stars
* <kbd>z</kbd> + <kbd>6</kbd> set to `"{parent}"` - go to parent of forked repo

**Comment by aupright** [comment]
Hey @Mottie good catch - we'll make sure to update our documentation there :smile: 

In terms of defining custom shortcuts, I can definitely see where that would be useful addition. Let's open this one up to the rest of the community to see if we can get some more upvotes and feedback on this one :beers:

**Comment by Mottie** [comment]
So, I ended up creating a [GitHub custom hotkeys](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-custom-hotkeys) userscript which will allow you to define hotkeys to go to pretty much any page.

![hotkey-settings](https://cloud.githubusercontent.com/assets/136959/14413597/63a1fe1c-ff44-11e5-9697-fdfaa85b4fcd.png)

Do you want me to close this issue?

**Comment by Mottie** [comment]
I also noticed that the <kbd>`</kbd> (backtick) key opens the boards... it isn't listed as a keyboard shortcut either.

**Comment by stevelacey** [comment]
I just lost yet another comment I had written because I pressed *something* on a repo I don't even use ZenHub on – please add an option to turn all of these off.

**Comment by drphilmarshall** [comment]
In the last month or so ZenHub keyboard shortcuts seem to have gone crazy (chrome, Mac OS X): when editing a file in the browser, my regular keypresses are interpreted as ZenHub shortcuts, replacing my edit view with boards, milestones etc etc. This is a _major_ bug: I'll be disabling ZenHub and advising others to do likewise until it gets fixed. BTW there seems to be no documentation on the ZenHub webpage, FAQ, or blog about keyboard shortcuts, and if there is online help, it's not easy to find...

**Comment by aupright** [comment]
Hey @drphilmarshall - ZenHub cofounder here.

Just wanted to jump into to apologize to you (and anyone else looking here recently) for any frustration that we might have caused. You're right, we did introduce a major bug last week which caused people to unintentionally be re-directed to the boards or burndown pages when pressing `b` or `d` keys when typing in an issue. We noticed this mistake immediately and pushed a patch (2.24.12) that same day. 

As there's an auto-update process for both Chrome and Firefox, its possible that this upgrade may not have reached you in time. Regardless, we take full responsibility for any frustration caused and will be working harder to ensure that these types of bugs don't make there way into the product.

Thanks for your continued support, and let me know if there's anything else I can help with.

**Comment by drphilmarshall** [comment]
@aupright 👍 

HI Aaron,

Thanks for getting back to us! I just checked my extension version and it now says 2.24.12, and sure enough, no more keyboard shortcut problems :-) Thanks very much for resolving this issue - it must be frustrating that it takes longer for Chrome to auto-update its extensions than it does for you and your team to fix bugs... 

Also, sorry for being so terse this morning! Reading my message back, I sound very grumpy indeed, and there was really no need to be. Best wishes with the ongoing development, and thank you for making such a useful product.

Best wishes,

Phil Marshall

**Comment by collinvine** [comment]
Is there a keyboard shortcut to move from one issue to another when the modal is open on the Board view? Left arrow or right arrow, for eg?

Is there a way to navigate from card to card within a column when modal isn't popped open?

**Comment by azenMatt** [comment]
Hi @collinvine - not at the moment

**Comment by troyibm** [comment]
@aupright  I still have keyboard shortcut problems using Zenhub Enterprise on Firefox.  Is there a different patch for it?  I'm using 2.10.2

**Comment by kendramoroz** [comment]
@troyibm Kendra here from the ZenHub team! To maintain privacy of your team's ZenHub Enterprise information, would you mind sending us an email via support@zenhub.com with what team you're on and what shortcuts aren't working for you?

**Comment by finnribm** [comment]
@troyibm I had this issue, also on 2.10.2   That version is pretty old now - auto-updating and manually checking for new versions did not discover the latest version available within IBM, which is 2.18.2 (internally you can get it from https://zenhub.innovate.ibm.com/)

**Comment by aupright** [comment]
Hey @finnribm - just wanted to sent over a friendly reminder that this is a public thread :). As I'm not sure if you intended to share that internal link above, I've removed your comment for now.

**Comment by jhe-** [comment]
This is still happening in Github's edit file feature.

**Comment by kendramoroz** [comment]
@jhe- Kendra here! We recently launched a suite of new keyboard shortcuts and fixed the `b` shortcut issues, but sounds like we might have missed a spot! To better debug, would you be able to list out the steps you're taking and provide a screenshot of where you are when you hit `b` causing the Boards to load? I was attempting to edit a file and hit b, but it stayed on the page so I want to make sure I'm following the same steps :) - once we pinpoint it, we'll issue it up to be fixed as it shouldn't be behaving like that anymore! 

Please get in touch with us at support@zenhub.com with further details 🙏

**Comment by jhe-** [comment]
Hi Kendra! I'm using Zenhub Enterprise 2.10.2. If this has since been fixed, I'll have to ask my sysadmin to distribute the updated chrome extension. (Seems like it's not listed in the Chrome store like the Github.com one is)

**Comment by kendramoroz** [comment]
@jhe- We launched shortcuts to Enterprise in 2.20! This is why it's still heading over with the `b` shortcut. If you send through an email with more details on your team to kendra@zenhub.com I can dig more into the account and next steps to work with the admins to get your team updated 😊
