### ISSUE TITLE
recurring issues

### ISSUE THREAD

**Issue by jovo** [ZenHubIO/support#532]
i have documented the request here with github:
https://github.com/isaacs/github/issues/537

i also mentioned you guys in the issue,
do you have any solutions for this?

many thanks, j

**Comment by azenMatt** [comment]
Hi @jovo - no good solutions for this at the moment ... however, we do have some new changes coming soon around #424 that will add in a much better management interface for the problem you described in that issue. 

Lets check in when that is live and see if it has the potential to help out with this problem
