### ISSUE TITLE
Search field highjacking input.

### ISSUE THREAD

**Issue by jonathansimmons** [ZenHubIO/support#533]
When viewing boards if you use the search field to search for an issue that input stays focused and I'm unable to select the comment box in the issue to add a comment. 

**Steps to Reproduce**
- Open boards
- Click search field and search for a issue. 
- Click an issue
- Scoll to comment box and attempt to comment

**Expected Result:** 
I should be able to comment on the issue

**Actual Result:** 
The search input retains focus and my comment is typed there instead. This clears the search and as stated prevents the ability to comment. 

**Computer Details**
Chrome: Version 47.0.2526.106 (64-bit)
OS: Mac OS X 10.11.3 Beta (15D9c)

**Comment by azenMatt** [comment]
Thanks @jonathansimmons - we are on it :smile:

**Comment by azenMatt** [comment]
Hi @jonathansimmons the fix for this is live in 2.13.27
