### ISSUE TITLE
Suddenly ALL closed issues show in closed column, despite selected milestone

### ISSUE THREAD

**Issue by spemmons** [ZenHubIO/support#535]
This didn't used to happen, and is a problem because this is the way I list milestone-specific issues that are closed to publish.

**Comment by spemmons** [comment]
OK, this is weird. My "closed" column again reflects only the closed issues for my selected milestone.

The failure was real, but now it seems like some kind of refresh inconsistency issue.

**Comment by azenMatt** [comment]
Hi @spemmons - we have a bug fix for this going live today - il let you know when it is  available.

**Comment by azenMatt** [comment]
Fixed in 2.13.27 :beers:
