### ISSUE TITLE
Support for multiple repos in milestones' burndown charts

### ISSUE THREAD

**Issue by wzin** [ZenHubIO/support#539]
When clicking on a burndown chart for a milestone with common name that exists in all repos that were conencted to the board, I'm seeing only the main repo's issues. 

I'd love to be able to see a burndown containing all issues for a milestone that exists across all merged repos.

**Comment by azenMatt** [comment]
Hi @wzin - we are working on this :smile: 

We have this captured in #247 so i'l close this issue to keep the conversation in one place. 

Expect to see it live during Q1!

**Comment by wzin** [comment]
Thanks @azenMatt!
