### ISSUE TITLE
Labels display incorrectly on board

### ISSUE THREAD

**Issue by jordanbuffaloe** [ZenHubIO/support#543]
We have letters and colons before our labels... example (F: Rule). Somehow, the "F: Rule" label shows as "G: Rule" on the board for some issues, while others retain their "F: Rule" label. Since the board does not allow for OR conditions, we cannot display both. When I click on "G: Rule", the issue shows the correct label "F: Rule", so reassignment is not possible. A call to the Github API also reveals the correct label. Zenhub board appears to be the problem.

**Comment by azenMatt** [comment]
Hi @jordanbuffaloe 

This is due to issue #279 - which we will have a fix for soon. 

Whilst we get this live - we can do a manual issue cache flush to resolve this problem if you can let me know the org and repos that are impacted
