### ISSUE TITLE
New issues not visible on board view

### ISSUE THREAD

**Issue by RodneyTurnham** [ZenHubIO/support#546]
As of mid-day 1/13/16, new issues are not (consistently) visible on Board view.

I added new issues to 3 of our Github repositories. One of those issues was visible on the Board view, after a page refresh. For the other 2, the new issues _are_ visible in the Issues list, but not in Boards.

Tried to fix by removing ZenHub from Chrome, re-starting Chrome, then re-adding ZenHub. This did not fix the problem.

Update: tried logging out of Github, bouncing Chrome, and logging back in. Did not fix the issue.

**Comment by azenMatt** [comment]
Thanks @RodneyTurnham - as per your comment on #286 - we can condense the discussion into that issue. 

In the very worst case scenario, if these issues did not get picked up in the cache - it should completely reset after one hour. If you find that the issues are still not appearing after that, please let me know!
