### ISSUE TITLE
My account shows: You are not part of any organizations

### ISSUE THREAD

**Issue by schellkenig** [ZenHubIO/support#549]
I can see zenhub under authorized applications and I am part of an organization (also owner) and still the zenhub accounts keeps showing the "You are not part of any organizations"?

**Comment by schellkenig** [comment]
Seems to work now but don't know why.

**Comment by devinbalkind** [comment]
I'm having this issue as well. I'm part of two organizations. One with an active Zenhub repo. But on https://dashboard.zenhub.io/#/organizations it says:

"You are not part of any organizations.

Can't see your organization? You or an admin may need to enable permissions for ZenHub in GitHub's application permissions. Then, come back and refresh this page!"
