### ISSUE TITLE
Interest in ZenHub For GitHub Enterprise

### ISSUE THREAD

**Issue by Jessalyst** [ZenHubIO/support#55]
Hey ZenHub lovers, 

We've had some interest in ZenHub for GitHub Enterprise. The more interest in this feature, the sooner we can make it happen!

**Comment by geekdave** [comment]
@roham : Any updates?  We'd love to use ZenHub with an on-premise Github Enterprise instance.

**Comment by roham** [comment]
@geekdave we have ZenHub Enterprise live with a select few marquee customers right now. We'd love to loop you into the process: please look out for an email on your @walmart address, once we get some basic information we can set your team up with a build to try.

**Comment by rasjani** [comment]
:+1: for ghe support

**Comment by leereilly** [comment]
![](http://ak-hdl.buzzfed.com/static/enhanced/webdr06/2013/7/4/11/anigif_enhanced-buzz-29313-1372950034-32.gif)

 :ship: Nice [ship](https://www.zenhub.io/blog/zenhub-enterprise-launches/), ZenHubbers!!!

**Comment by azenMatt** [comment]
Thanks @leereilly ! 

Now we are live, I am going to close this issue. 

If you are interested in ZenHub Enterprise - please contact us via https://www.zenhub.io/enterprise
