### ISSUE TITLE
Support task-list progress display on boards

### ISSUE THREAD

**Issue by stepanstipl** [ZenHubIO/support#551]
If you add a task-list to a GitHub issue, GitHub will display handy little progress bar on the issue list page. Would be nice if ZenHub would support displaying same on boards. It's very useful for tracking progress.

<img width="225" alt="screen shot 2016-01-18 at 18 34 33" src="https://cloud.githubusercontent.com/assets/3027227/12399536/8b2616f8-be12-11e5-8960-694bc35a9f3e.png">

**Comment by azenMatt** [comment]
Hi @stepanstipl 

Thanks for the feedback - this is a popular request! You can follow updates in #126 

I am going to close this one so we can centralize discussion on that issue :beers:
