### ISSUE TITLE
User named "todo" appears briefly before todolist displays.  Name still in tab

### ISSUE THREAD

**Issue by mgsloan** [ZenHubIO/support#553]
Pressing Ctrl-R a couple times:

![recorded](https://cloud.githubusercontent.com/assets/22570/12436062/c883c504-bec6-11e5-9b8f-fd85508416e0.gif)

Note "Yu-Lun Chen" still appears in the name of the tab.

**Comment by mgsloan** [comment]
Heh, also via Ctrl-F:

![recorded](https://cloud.githubusercontent.com/assets/22570/12442268/84603be0-bf03-11e5-8774-18d21a6ad1ea.gif)

**Comment by mgsloan** [comment]
I guess this is expected behavior.  Not sure how I ended up on that url.

**Comment by azenMatt** [comment]
that is very strange! the logic should just add #todo to the end of whichever link you are at 

Il see if I can find a way to replicate

**Comment by mgsloan** [comment]
@azenMatt Yep, this is why I closed the issue, it was a misunderstanding on my part. The explanation here is that:

* I was trying to type the URL for #todo from memory, but missed out on the `#`

* I was navigating to the todo page by typing todo in my url bar, which would bring up this URL as the first result

I do find the visual flicker annoying, but I realize it's hard for the plugin to do anything about that.

**Comment by azenMatt** [comment]
Got it - thanks for confirming!
