### ISSUE TITLE
How I can move issue between pipelines using API?

### ISSUE THREAD

**Issue by jpascal** [ZenHubIO/support#554]
I want move some issues between pipelines using API. How I can do it?

**Comment by justbaker** [comment]
@jpascal [The API](https://github.com/ZenHubIO/API#endpoints) currently supports only GET requests, so not possible at this time.

**Comment by azenMatt** [comment]
The write version is on our roadmap, we will keep everyone updated here - https://github.com/ZenHubIO/support/issues/172

and in the API repo https://github.com/ZenHubIO/API

No timelines for this just yet
