### ISSUE TITLE
API status page

### ISSUE THREAD

**Issue by camilleriluke** [ZenHubIO/support#555]
A view where anyone can see the status of all ZenHub's APIs. 

A couple of status pages:
- GitHub: https://status.github.com/  
- Google: http://www.google.com/appsstatus
- RiotGames: https://developer.riotgames.com/status

**Why this might be beneficial?**
- Having a status page would avoid unnecessary support queries regarding the availability of the service.
- Subscription to the status feed will notify clients when the service is down and back up.

**Comment by azenMatt** [comment]
Makes a lot of sense to me! 

I will get this added to the teams backlog

**Comment by pawelad** [comment]
Your API is down right now (502 Bad Gateway) and it should _really_ have a status page.

**Comment by kendramoroz** [comment]
Thanks @pawelad  - the team is on the case! A status page is still in our backlog, but we'll post back here/on Twitter once the API is back up and running.

**Comment by zachfeldman** [comment]
Can we have a status page plz. Backlog is no longer acceptable charging for your software and having it in wide use....plus I'm sure your support team is being overwhelmed right now. Sorry for the issues though and best of luck solving them!

**Comment by kendramoroz** [comment]
🙏 we hear you! We'll see what we can do here to get this up and running sooner than later... but first, we're going to get you back into your Boards today 💃 !

**Comment by kendramoroz** [comment]
Everything is back on track! Let me know if there's anything else that comes up today that I can help with.

**Comment by zachfeldman** [comment]
API appears to be down again....still no status page so I'm not really sure

**Comment by kendramoroz** [comment]
@zachfeldman we just tweeted about it! https://twitter.com/ZenHubHQ/status/986377612242006016 We're also working on ramping up a status page, it's coming 🙏

**Comment by kendramoroz** [comment]
@zachfeldman Everything should be up and running once more!

**Comment by richarddli** [comment]
Any update on this? I'm trying to use ZenHub and can't figure out if the service is actually working ...

**Comment by kodaj** [comment]
@kendramoroz Could you provide an update on the ETA for the status page? ZenHub boards appear to be down at the moment, but there's no way for me to confirm that - there's no outage note on your Twitter page, you haven't responded to my direct Twitter message, and your support team hasn't replied to my email.

**Comment by dlondero** [comment]
@kodaj had issues as well because of a 404 error on a css for quite some time earlier. But no place where to check if it was just me or not...

**Comment by kodaj** [comment]
@dlondero Is this the error you saw ?

![image](https://user-images.githubusercontent.com/4332563/50689575-2bb93000-1022-11e9-86d5-b974ae8bff20.png)

**Comment by dlondero** [comment]
@kodaj yep!

**Comment by kendramoroz** [comment]
Hi everyone, this is still planned. You can follow along and vote for this [in our new community portal for feedback here.](https://zenhub.productboard.com/portal/tabs/0e365274-272b-4040-ae22-43a988602e26/features/1364511/portal/expanded) 🚀
