### ISSUE TITLE
[wish] Github issue templates in the Zenhub extension

### ISSUE THREAD

**Issue by twardoch** [ZenHubIO/support#556]
It would be wonderful if Zenhub added an ability to specify templates for new Github issues. One would be enough. Basically, someone on my team should be able to create/edit this template and then whenever any of my team members who has the Zenhub extension installed creates a new Github issue, the (otherwise empty) text area for the issue gets prepopulated with the template. Something like this is already available at: 
https://github.com/skidding/github-issue-template
but the contents of that template is not editable unless I fork this, modify and deploy a custom Chrome extension, which is a bit much work. 

Having this as part of the Zenhub extension would be great.

**Comment by azenMatt** [comment]
Hi @twardoch - I think this is a great idea. We already have #424 - Epics in the pipeline. The ability to add other custom cases would be very useful. 

We already have issue #387 open to track custom templates, so i am going to close this one so we can centralize discussion. :+1:
