### ISSUE TITLE
Kanban Metrics - Cycle and Lead Time (Control Points)

### ISSUE THREAD

**Issue by jeffreywescott** [ZenHubIO/support#559]
While the Burndown chart is a "nice to have", it is mainly showing us how good we are at milestone-setting and how we're tracking toward it, but not really how things are "flowing" in terms of development productivity. Kanban has some much better metrics for this. Specifically:
- **Cycle Time (most important)**: how long it takes for a card to move from the "start" lane (e.g., "To-Do" or "Ready") to the finished lane (i.e., "Closed").
- **Lead Time**: how long does it take for a card to move from the lane 1-to-the-left of the "start" lane (e.g., "Backlog" or "New Issues") to the finished lane (i.e., "Closed").
- **Work-in-Progress**: how many cards / stories are currently in active development (bonus points if you also tally the story points here)
- **Throughput**: in a certain time-range, how many cards / stories were completed (bonus points if you also tally the story points here)

Ideally, we'd be able to see **Cycle Time** and **Lead Time** on both a Card basis, but what's _most important_ is a rolled-up average for the whole board.

**Side-note:** It would be possible for us to use the API to tally these ourselves, except your rate limit prevents that from being feasible, since we need to get [issue events](https://github.com/ZenHubIO/API#user-content-get-issue-events) for each issue that is "Closed" in a certain timeframe. See also: #560

**Comment by azenMatt** [comment]
Thanks for the feedback @jeffreywescott - we are lining up an overhaul of our reporting to improve from just having a burndown chart. 

i'l make sure these are included in the review of what should be in phase one of this. :+1:

**Comment by jeffreywescott** [comment]
Thanks!

**Comment by nickbuddendotcom** [comment]
+1

**Comment by ambynair** [comment]
+1

**Comment by ambynair** [comment]
These are pretty basic feature that should be available with Zenhub by now. You cant do a kanban without two basic metrics : Lead time and Throughput. I am hoping Zenhub understand this and will prioritize to get this feature deployed.

**Comment by azenMatt** [comment]
I hear you @ambynair - we are working hard to get to a point where this can be prioritized

**Comment by jeffreywescott** [comment]
Any updates here? We'd love ZenHub and would really love to see this feature implemented. Burndown and story points are really insufficient for teams using true Kanban.

**Comment by azenMatt** [comment]
Hi @jeffreywescott - no updates right now on this, we are still heads down on performance improvements, we will be able to get back to enhancing the reporting suite once this has been resolved

**Comment by DavidASA** [comment]
Would LOVE this update

**Comment by JohnAtJetPack** [comment]
+1

**Comment by kennyklee** [comment]
+1 +1 +1 

Por favor

**Comment by markpasternak** [comment]
From my point of view some true kanban metrics added to this product would make it perfect for us. Story points and burndowns is soooo 2009 :)

**Comment by baratrion** [comment]
Hi @azenMatt, is there any update on this?

**Comment by markwilkie** [comment]
It's hard to use ZenHub for Kanban without these reports

**Comment by baratrion** [comment]
Hello everyone, we've developed cycle time charts for ZenHub using aforementioned ZenHub issue events API: https://github.com/Adphorus/zenhub-charts

It might still be rough around the edges but feel free to poke around it.

**Comment by azenMatt** [comment]
@baratrion Looks amazing! Thank you for sharing 😄

**Comment by djlebersilvestre** [comment]
+1

**Comment by keremispirli** [comment]
Yes please!

**Comment by toland** [comment]
This ticket is almost two years old. Is this something that you are actually planning to do?

I really need this kind of metrics and have started evaluating other tools because Zenhub doesn't have it.

**Comment by fdenkens** [comment]
+1

**Comment by bhack** [comment]
I think that also an historgram chart of story points/users could be useful to always quickly overview the team workload distribution.

**Comment by TreONeill** [comment]
I like ZenHub, but one of my teams is all Kanban (no scrum) and we really need these metrics. Trying the open source project for the time being, but would be nice to have out of the box support

**Comment by anitaderiane** [comment]
I've been using ZenHub with one of my teams at Liferay for a year now. We are 24 people and have a lot of tickets to follow-up. More and more, as we've been fine tuning our processes with ZenHub features. 
I've been using a spreadsheet aside, to collect manually the kanban metrics and analyze how the team is doing. But it's too much manual work. 

That's why I totally support this feature request from @jeffreywescott. 

@ ZenHub team, if you're not convinced yet, please watch that video: [Metrics you should use but don't](https://vimeo.com/242201835/13ed83e3fe)

**Comment by rupachup** [comment]
+1

**Comment by kendramoroz** [comment]
👋 Hey everyone! I know this issue includes discussion of all the Kanban-centric reporting, but wanted to provide an update that we're now moving towards supporting more Kanban centric reports, starting with cumulative flow ✨(I updated the Issue to reflect this, and moved it to in progress. post-cumulative flow we will update the issue back to reflect the other reportrs!) . 

This is now in development ✨ we should be launching this report in a few sprints from now. When it comes to the other reports, we'll continue to share updates on specifics post-cumulative flow!

**Comment by KZafeiropoulosN** [comment]
Hey. Please share if there is any news about this is issue. We are looking forward!!

**Comment by kendramoroz** [comment]
👋 A little update for y'all! We're nearly there 🙏 and are in the home stretch with tidying, polishing, and connecting the backend. 

We are aiming for a launch in the next few weeks, but will post back with a more concrete timeline early October. After Cumulative flow, we're going to be introducing #1214 and Control Point Charts (which will add Cycle and Lead time!)

Here's a screenshot from our latest PR (the test data makes it spiky, but rest assured the ideal diagram is up and to the right!).

![image](https://user-images.githubusercontent.com/11036230/46042038-37af6080-c0c9-11e8-8835-7b92b7f0df7c.png)

And if you haven't yet seen it, [don't forget to check out our roadmap here](https://view.attach.io/H1TPiia-7)!

**Comment by kendramoroz** [comment]
And as a bonus, here's a screenshot of the upcoming Control point chart! It will cover lead and cycle time 🎉  - We will have more updates to share on timing and details (including joining a beta program for this report!) in the next few weeks 💃 

![screen shot 2018-09-25 at 1 53 03 pm](https://user-images.githubusercontent.com/11036230/46042524-71cd3200-c0ca-11e8-9868-667847955377.png)

**Comment by kendramoroz** [comment]
👋  Now that Cumulative Flow is live, I've updated the title here to reflect the additional report the team is now working on: Control Point (which will highlight cycle and lead time!) We're kicking off our first sprint shortly and will post back with more timeline updates in the next few weeks.

**Comment by kendramoroz** [comment]
👋 Hey all - quick update! We're on track to launch Cycle and Lead time in January, but a quick update on where to get updates. We're going to be sunsetting this repo and moving to a new product feedback portal, [hosted here](https://portal.productboard.com/zenhub) to streamline requests and share our roadmap more openly. You can follow-along and add your feedback [directly to the Cycle Time insights card here in the new portal](https://portal.productboard.com/zenhub/c/23-tracking-cycle-and-lead-time-through-the-control-point-chart?utm_medium=social&utm_source=portal_share).

We encourage everyone interested in this next chapter of ZenHub to vote, add feedback, and join the conversation 🎄! Upwards and onwards to 2019 🚀
