### ISSUE TITLE
increase rate-limit for API or add a way to get "issue events" for multiple issues at once

### ISSUE THREAD

**Issue by jeffreywescott** [ZenHubIO/support#560]
We want to use the API to calculate true Kanban Metrics (see also: #559).

However, your rate limit prevents that from being feasible, since we need to get [issue events](https://github.com/ZenHubIO/API#user-content-get-issue-events) for each issue that is "Closed" in a certain timeframe. If more than 10 issues have been closed, it will take more than 10 API calls to get the information.

The "dumb" solution is to increase the rate limit, but as projects and teams grow, that will eventually be unsustainable.

A smarter solution would be to add an API endpoint something like:

```
GET https://api.zenhub.io/p1/repositories/:repo_id/issue-events?issue_numbers=1,23,74,102,112,114
```

**Comment by azenMatt** [comment]
Thanks for the feedback, il make sure this is included for the team when we do our next pass on improving the API.

**Comment by jeffreywescott** [comment]
Thanks!

**Comment by azenMatt** [comment]
Also - do you know what rate limit you would need?

**Comment by jeffreywescott** [comment]
As I mentioned, it's impossible to know, as it would depend on (a) team size, and (b) average throughput per team member. But, by way of example, let's imagine:

- *team size:* 3 people
- *average throughput per team member:* 5 stories per sprint

For my particular metrics calculation resource with these assumptions, I'd need to:
- query the ZenHub API once to get the repos in a given board (1 API call)
- first use the GitHub API to find any issues that have been closed during the last sprint (1 api call per repo)
- query the ZenHub API once per issue to get the "issue events" for each issue (15 API calls)

If the team size were 5, it would be 25 API calls. If the throughput per team member was 10 stories, it would be 50. As you can see, it grows and grows.

This is why I was suggesting a way to pull event information for _multiple_ issues at once, e.g.:

```
GET https://api.zenhub.io/p1/repositories/:repo_id/issue-events?issue_numbers=1,23,74,102,112,114
```

That way, regardless of team size and throughput, I'd need only `R+1` API calls where `R == number of repositories on a board`.

**Comment by jeffreywescott** [comment]
To reiterate, the key for calculating Kanban metrics is the issue events ... that's the only way we can compute cycle time, lead time, etc.

**Comment by rockymadden** [comment]
In addition to improving the API as @jeffreywescott suggests, I'd like to echo the idea of increasing the API limit from 10 per minute to something closer to GitHub's own 5,000 per hour (i.e. rough order of magnitude higher). Not only are we interested in generating reports like @jeffreywescott, but also custom dashboards that leadership and stakeholders can use. Would also be cool to do a NOC-style dashboard in our lobby. Even simple personal queries (via https://github.com/rockymadden/zenhub-cli) hit the current limit very easily.

**Comment by azenMatt** [comment]
It might be possible for us to do a 'quick' change here to increase the limit for the 'events' end point. The Issues endpoint is a little more complicated because of its reliance on the GH API (and we want to make sure we don't go over those request limits) 

Would that be a useful stop-gap solution while we get the new multi-issue end points onto the roadmap?

**Comment by jeffreywescott** [comment]
If you are referring to the `/issue-events` endpoint, then yes -- that is the most crucial for my particular use case. I'd probably directly use the GH API (rather than ZH API) to find closed issues, anyway.

As I mentioned above, the better solution is to avoid the multiple network / API round-trips in the first place.

Actually, the best solution would be to address #559. ;-)

**Comment by rockymadden** [comment]
```Issues endpoint is a little more complicated because of its reliance on the GH API (and we want to make sure we don't go over those request limits)```

It could be possible to remove this 1:1 by keeping the current state of GH issues in a warm cache and then using GH's web/service hooks to keep them up-to-date (vs calling the GH API every time the ZH API is called): https://developer.github.com/webhooks/

**Comment by azenMatt** [comment]
> If you are referring to the /issue-events endpoint, then yes -- that is the most crucial for my particular use case.

Great - we just changed this to be 100 per min :smile: 



> I'd probably directly use the GH API (rather than ZH API) to find closed issues, anyway

Agreed - that was what our assumptions were during design 



> Actually, the best solution would be to address #559. ;-)

A slightly longer change! But leave it with me!

**Comment by azenMatt** [comment]
Hi @rockymadden @jeffreywescott - we just upped all of our API end points to 100, we have a separate issue here - https://github.com/ZenHubIO/API/issues/9 to discuss adding in an additional /issues endpoint to query for specific issues. 

I'm going to close this issue to help keep all API discussion on the API repo
