### ISSUE TITLE
ZenHub "pipeline change" event shown multiple times on GitHub pull request

### ISSUE THREAD

**Issue by stefafafan** [ZenHubIO/support#562]
On any pull-request, every time you click on a commit and go back to the pull request page by hitting the  back button on the browser, the "pipeline change" event is shown that many times.

When I first go to the pull request:
![pipeline1](https://cloud.githubusercontent.com/assets/3520520/12571590/10f3dbda-c426-11e5-9783-762cc2063e20.png)

After I "click a commit and go back" 3 times without refreshing the page:
![pipeline2](https://cloud.githubusercontent.com/assets/3520520/12571598/225f7c76-c426-11e5-8d44-f3bc43b87964.png)

**Comment by azenMatt** [comment]
good spot - we will get this fixed!

**Comment by azenMatt** [comment]
Hi @stefafafan - this one is now fixed in v2.15.97 :beers:
