### ISSUE TITLE
feature request: filters for pipelines

### ISSUE THREAD

**Issue by Pomax** [ZenHubIO/support#564]
Right now if I look at our board, the  "new issues" pipeline has about 200 issues from 20 people with many labels, which makes it hard to run through and move issues to the relevant pipelines - it would be super useful if pipelines could come with some filters like "only issues filed by [user]" or "only issues with label [...]" for faster kanban'ing

**Comment by azenMatt** [comment]
Thanks for the suggestion @Pomax 

Does the label filter for the whole board help here? Or is it useful to see every issue elsewhere on the board, and only filter the single pipeline?

we also have ZenHubIO/support#508 for filter by Author which will be useful to add

**Comment by Pomax** [comment]
no, filtering the entire board is too much. I still need to see the real pipelines properly, just knowing there's 2 issues in a pipeline with matching label doesn't tell me if a milestone or workload is too big while triaging the "new issues" pipeline.

**Comment by azenMatt** [comment]
makes sense - thanks for confirming

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue as there's the option to sort the pipeline via the settings menu on each pipeline 🎉  . To see what else we're up to, keep an eye out on `Priorities` and `In Progress`! 😄
