### ISSUE TITLE
Support integrations for gitter chat

### ISSUE THREAD

**Issue by JLLeitschuh** [ZenHubIO/support#565]
Gitter works off of webhooks just like slack.
This would be awesome for our project.
https://gitter.im

**Comment by azenMatt** [comment]
Thanks for the suggestion @JLLeitschuh 

Happy to add in Gitter integration :smile: I have spoken to the Gitter team about this before and they assure me it will be easy! 

i've added the 'needsVotes' label to get some more community feedback. i'd love to do this if we have more users of both systems it will be useful for - so please keep the '+1s' coming!

**Comment by laughedelic** [comment]
+1

**Comment by azenMatt** [comment]
Integration with Gitter is live! 

accessible via the 'integrations' tab on the ZenHub dashboard

**Comment by JLLeitschuh** [comment]
Awesome! Great work!
