### ISSUE TITLE
ZenHub board is not opening

### ISSUE THREAD

**Issue by vikeshpadarthi** [ZenHubIO/support#566]
i am unable to open ZenHub board in my system. Please let me know the issue

**Comment by vikeshpadarthi** [comment]
please check it

**Comment by azenMatt** [comment]
Hi @vikeshpadarthi - did you get this sorted? 

If this is still a problem, please send me an email at support@ZenHub.io and we can take a closer look

**Comment by emilenriquez** [comment]
Hi ! 

I can't seem to load zenhub on chrome.

**Comment by emilenriquez** [comment]
@azenMatt

**Comment by azenMatt** [comment]
Hi @emilenriquez - would you be able to update your extension to the latest version? 2.15.87 - this should fix the problem!

**Comment by aliceriot** [comment]
hey folks,

I'm experiencing this issue on chromium 49 running version  2.16.36 of the extension (which looks like the latest version available in the chrome store). Host OS is debian testing.

behavior of the extension: I just see the 'We are loading your issues' page indefinitely. If I inspect the background page the extension uses (from the chrome://extensions menu) I see some activity in the console:

![zenhub_console](https://cloud.githubusercontent.com/assets/6207644/14761792/e4a70794-0937-11e6-8cd2-645c0cda91f2.png)

the repo in question is public, you can check it out [here](https://github.com/ex-frasis/thingumy).

any ideas what's going on?

**Comment by azenMatt** [comment]
Hi @aliceriot - do you have an errors in the javascript console when the page is trying to load?

**Comment by aliceriot** [comment]
@azenMatt I didn't see any. however, I coincidentally installed a different OS over the weekend and the problem is gone.

**Comment by aliceriot** [comment]
I'm seeing this again! Hooray.

Now on chromium 50, running on Arch Linux.

There aren't any errors in the JS console, just this:

![zenhub_why](https://cloud.githubusercontent.com/assets/6207644/15050649/015df5d4-12c3-11e6-8214-414152f0348a.png)

**Comment by azenMatt** [comment]
Hi @aliceriot - we will take a look into this, although it is worth noting that due to team capacity issues - we don't officially support chromium. This means we don't run any tests against it before a release and so can't guarantee you if it will keep working in the future. 

We hope to expand support in the future as the team grows. The ultimate goal is to have all browsers supported with their own extension.

**Comment by aliceriot** [comment]
I think I figured it out - privacy badger blocks `api.zenhub.io` by default! so I don't think it has to do with chromium per se, but anyway unblocking that domain seems to make it work.

**Comment by azenMatt** [comment]
ah - good to know! Thank you for the update :)
