### ISSUE TITLE
No icons for issue filters and repos, labels, milestones and assignee selector buttons

### ISSUE THREAD

**Issue by junketjim** [ZenHubIO/support#570]
The latest build has blank buttons where there used to be icons.
![screen_shot_2016-02-01_at_13_27_38](https://cloud.githubusercontent.com/assets/2206147/12718729/61245942-c8e8-11e5-8a97-48dd7e50c163.png)
I'm on a dev. build of Chrome - 50.0.2633.3 dev (64-bit)

**Comment by wzin** [comment]
same here - official stable chrome on osx `Version 48.0.2564.97 (64-bit)`

**Comment by aaronwest** [comment]
I'm seeing the same on Mac OS X 10.10.5 using Chrome version 47.0.2526.111 (64-bit).

I've also noticed the Pipeline associated with an issue can no longer be changed from the right nav/menu. The only way to change the Pipeline now is drag-and-drop. For what it's worth I have ensured I'm running the latest ZenHub plugin.

If these two issues are not related I'm fine with filing a separate issue.

![pipeline-screenshot](https://cloud.githubusercontent.com/assets/231569/12723620/cc718c38-c8cf-11e5-87f8-9b08bf89706b.png)

**Comment by azenMatt** [comment]
Hi all - looks like this happened to all users - we have lined up a fix and it is just being pushed through the deployment process at the moment. 

Will be live ASAP in v 2.15.17

**Comment by aaronwest** [comment]
Thanks @azenMatt. As usual, you guys deliver. I really really appreciate you guys and how you respond to issues like this. :+1:

**Comment by azenMatt** [comment]
Thanks @aaronwest :smile: 

And you can now update to v2.15.18 via the extensions menu for both Chrome and Firefox to update and get these icons back for the board. 

We are still working on it for the sidebar selectors - the functionality does still work, you just need to click where the icon should be!

**Comment by aaronwest** [comment]
Thanks for the tip on clicking the hidden icon. Good stuff.

**Comment by Mottie** [comment]
I see the icons have been added! One issue is the "Estimates" gear in repos in which you are not an owner or collaborator.

The icon both shows and opens a popup

![2016-02-01 20_59_36-no icons for issue filters and repos labels milestones and assignee selector b](https://cloud.githubusercontent.com/assets/136959/12738486/c6d2ac1a-c926-11e5-88b1-8a7b9d928294.png)

**Comment by azenMatt** [comment]
Thanks @Mottie - nice spot :) 

We are working though adding these back in one by one and pushing updates live as we have them (for example we still need to add the 'selected' and 'delete' icons back into the estimate drop down.) 

We are aiming to have these all resolved by the end of day Tuesday 

cc @pnavarrc

**Comment by azenMatt** [comment]
Hi everyone, all these icons should now be back :)
