### ISSUE TITLE
Pipeline option popup not useable

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#571]
The pipeline option popup immediately disappears after clicking... with a sustained mousedown, then release, it remains open but won't close until an option is selected, or another option gear is clicked.

![zenhub](https://cloud.githubusercontent.com/assets/136959/12738602/bebc5872-c927-11e5-9fdf-82553b4576d7.gif)

**Comment by azenMatt** [comment]
Thanks @Mottie 

We are also on this one as part of the icon changes from GH 

cc @pnavarrc

**Comment by Mottie** [comment]
It would also be nice to not show this gear in pipelines that you aren't able to rename or delete - they serve no purpose for me when I peruse these ZenHub issues... or are you planning on using them to add an option like "search" this pipeline (see #564)?

**Comment by azenMatt** [comment]
At some point it would be great to use this for advanced pipeline options! But we can certainly hide it for pipelines you can't action until then. 

Im going to close this issue as the original problem has been resolved - i've opened a new issue internally to remove the cog when you are unable to perform an action :+1:
