### ISSUE TITLE
Save toggle settings

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#572]
I don't really want to see closed issues in the board view. Almost every time I open the boards view, I have to click on the "Hide Closed Pipeline" toggle. I remember that the state of the button used to be saved. Please fix it!

**Comment by azenMatt** [comment]
Hi @Mottie, 

We removed some of these save filters based on being flooded by support request from users that had 'hide closed issues' toggled from a previous session, and were now confused as to why no issues were shown. 

But I think we can make sure that the closed issue pipeline remembers its state - il get this added to the backlog :+1: 

for the other toggles, we will come up with a better solution :)

**Comment by azenMatt** [comment]
Hi @Mottie - as of the latest version (2.15.79) - the closed issue selector is now remembered in your browser local storage! 

The other two buttons here are still refreshed each time 

Let me know if you have any issues!

**Comment by Mottie** [comment]
Thanks!
