### ISSUE TITLE
Cannot close an issue after making a comment

### ISSUE THREAD

**Issue by evfishr** [ZenHubIO/support#573]
If I click into an issue from the board and comment, the option to `Close Issue` becomes disabled

Steps:
1. From the board, click into an open issue. Observe that `Close Issue`  and `Comment` are both clickable at the bottom of the issue feed.
2. Comment on the issue

Observed
`Close Issue` becomes disabled
![screen shot 2016-02-03 at 4 56 21 pm](https://cloud.githubusercontent.com/assets/10353530/12803068/a5814ea0-ca9c-11e5-993a-c51260327e9e.png)

My options are:
1) I can refresh the page to have `Close Issue` clickable again, and close the issue. However, refreshing brings me to the issue full view in GitHub and away from the ZenHub board view with the issue only as a pop-up, where I can easily close out to return to the board view
2) I can close out of the issue, then click back in to have `Close Issue` clickable and close the issue

Expected
After each comment or action, all options still clickable
- While issue open, `Close Issue`  and `Comment` are both clickable
- When issue is closed, `Re-open Issue` and `Comment` are both clickable

**Comment by azenMatt** [comment]
Hi @evfishr - I can replicate this as well 

We will get it fixed :smile:

**Comment by azenMatt** [comment]
Hi @evfishr - this is fixed in the latest version! (v2.15.44)

Please let me know if you have any problems with it!

**Comment by evfishr** [comment]
woot! thanks @azenMatt :tada:
