### ISSUE TITLE
BUG: stop ignoring "modifiers" on mouse clicks

### ISSUE THREAD

**Issue by jeffreywescott** [ZenHubIO/support#575]
For example, on OS X, when I CMD-click on the "Boards" or "Burndown" tabs, my expectation is that the "Board" or "Burndown" will open in a new tab. However, it's ignoring the CMD-key modifier and replacing the current content. This is an annoying (but easy to fix) bug.

**Comment by azenMatt** [comment]
Hi @jeffreywescott - agreed. This is on to todo list :smile: 

We have it recorded here #342, so I will close this issue. But we are aware this needs fixing!
