### ISSUE TITLE
Organization Level Features For Managers

### ISSUE THREAD

**Issue by khalidabuhakmeh** [ZenHubIO/support#576]
We use ZenHub to manage multiple repos. Some projects are related while others are not. I would like to see a few features added to allow me to see what is happening within my organization.
## Master Board

<img width="912" alt="screenshot_2_5_16__3_30_pm" src="https://cloud.githubusercontent.com/assets/228256/12858336/6d11621c-cc1d-11e5-915a-44bc93619136.png">

All of our boards are the same, so it makes sense to see which _features_ are _ready_.
## Current Team Makeup based on Repository

Based on the issues currently being _worked_, it would be nice to see the current make up of each team for each repo. I normally know this, but stakeholders would like to know "hey what is developer X working on right now?".
## Organization Report

While GitHub offers statistics at a repository level, it would be nice to have reports based on the organization. Some of these numbers may be the following:
1. Total of estimates across all repositories based on swimlane selection.
2. Total per swimlane
3. Work distribution per developer based on assigned tickets
4. Label totals
5. Most upvoted issues

![please](https://da8lb468m8h1w.cloudfront.net/v2/cpanel/9174784-123944942_7-s4-v1.png?palette=1&width=246)

**Comment by azenMatt** [comment]
Hi @khalidabuhakmeh - these are great ideas

We are currently going through an improvement process for our reporting, getting some information at the organization level for this would be a big improvement. I'l make sure we dig deeper into what we can do here :+1:
