### ISSUE TITLE
Diagonal Burndowns

### ISSUE THREAD

**Issue by Thormidable** [ZenHubIO/support#578]
Diagonal Burndowns - Using latest absolute effort point value at the end of each day as sample point, rather than having a new point for each closed issue.

**Comment by azenMatt** [comment]
Hi @Thormidable - we are currently getting ready for a reporting overhaul - so we will make sure this idea is put into discussion. 

each approach has pros and cons - do you have a particular reason why you would prefer it this way vs a new point each time?

**Comment by Thormidable** [comment]
We prefer the diagonal line as it shows the velocity of our work in the
same manner as the velocity of the milestone is plotted,
We find it a clearer indication of whether we are on target or not as an on
target line will closely follow the target velocity and being slightly
ahead or behind, becomes quite clear

Adding points for each update means, the plot of work done is rarely close
to the milestone velocity, even when we are on target.

Out of interest, could you tell me what the pros are of the current
approach? It is hard to formulate arguments without understanding the other
side.

Cheers,

Will

On 16 February 2016 at 23:23, Matt Butler <notifications@github.com> wrote:

> Hi @Thormidable <https://github.com/Thormidable> - we are currently
> getting ready for a reporting overhaul - so we will make sure this idea is
> put into discussion.
>
> each approach has pros and cons - do you have a particular reason why you
> would prefer it this way vs a new point each time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/578#issuecomment-184917787>.
>



-- 

Best Regards,

Will Thorley



*Will Thorley*                                       Tel:       (01740)
625526

*Senior Software Engineer*              Email:
w.thorley@ibexinnovations.co.uk



Discovery 2,

NETPark,

William Armstrong Way,

Sedgefield, Co. Durham

TS21 3FH

**Comment by azenMatt** [comment]
I have thought about this one some more, and decided that I am on your side :) I will get this included in our impending reporting changes

**Comment by azenMatt** [comment]
Burndowns are now diagonal :grinning: 

All closed issues are grouped into a single 'day' point. 

I think it looks much tidier!
