### ISSUE TITLE
Export issue & sticky sidebar

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#581]
It looks like GitHub just make the sidebar sticky, the "Export Issue" button doesn't stick with the rest of the elements

![zenhub](https://cloud.githubusercontent.com/assets/136959/13024865/7f4c0b4a-d1c1-11e5-90ba-962bf25916ac.gif)

**Comment by azenMatt** [comment]
thanks @Mottie - fix just released :) 

v2.15.40 

very cool that GitHub have updated this for Chrome, it has been on Firefox for ages :smile:
