### ISSUE TITLE
Export Issue Button Doesn't scroll with side panel + issue bump

### ISSUE THREAD

**Issue by JLLeitschuh** [ZenHubIO/support#582]
I know that Github just changed their UI so you'll probably notice this pretty quickly but I figured I'd open an issue about it.
<img width="264" alt="screenshot 2016-02-12 21 35 07" src="https://cloud.githubusercontent.com/assets/1323708/13025251/aecdb5da-d1d0-11e5-9d3a-f4adfa006b7a.png">

Additionally, when scrolling to the bottom of a very short issue the screen "bumps" upward when you hit the bottom. (Chrome on OSX).

To reproduce the second bug, create a really small issue and scroll to the bottom of the page.

**Comment by azenMatt** [comment]
thanks @JLLeitschuh - we just pushed a fix for the scrolling - v 2.15.40 - that you can update to now. 

for the second bug - we will take a look at the now!

**Comment by azenMatt** [comment]
This is now fixed. Please let me know if you have any further issues with this
