### ISSUE TITLE
Zenhub board scrollbar issue

### ISSUE THREAD

**Issue by aliceinwire** [ZenHubIO/support#583]
when you change the window screen size the horizontal scroll-bar disappear.
Vertical scroll bar doesn't exist.

**Comment by azenMatt** [comment]
Thanks @aliceinwire - we will get this fixed!

**Comment by aliceinwire** [comment]
any progress?

**Comment by azenMatt** [comment]
Not yet, it is moving it's way up our bug queue and should be prioritized soon. Thanks for you patience - I will keep you updated

**Comment by azenMatt** [comment]
Hi @aliceinwire  we just pushed a fix to this in v2.15.86, can you update and see if this is working for you?

Any problems, let me know!

**Comment by aliceinwire** [comment]
Horizontal scroll bar is working correctly, the vertical one still dosen't exist, maybe just scrolling the box as is doing now could be enough.
so as far as i know, is ok for me.

**Comment by azenMatt** [comment]
glad to here everything is now working for the horizontal scroll bar.

For the vertical scroll bar problem, do all of the different pipelines work for you? 

we don't have a 'master' pipeline scroll bar that will scroll the whole page - although it has been discussed here - https://github.com/ZenHubIO/support/issues/258 - does that match what you would like here?

**Comment by aliceinwire** [comment]
yes thanks
