### ISSUE TITLE
Board doesn't reflow when resizing the page

### ISSUE THREAD

**Issue by colindean** [ZenHubIO/support#584]
No reflow on resizing the window or adjusting font size.

We're experimenting with doing our daily standup directly from our Zenhub boards. One thing we've noticed is that the board doesn't resize when any aspect of the browser changes. This is most noticeable when going into fullscreen mode. I have to refresh each time.

**Comment by azenMatt** [comment]
Thanks @colindean - I can replicate this as well, we will get a fix in

**Comment by colindean** [comment]
Yinz are great.

**Comment by azenMatt** [comment]
Hi @colindean - we just pushed a fix to this in v2.15.86, can you update and see if this is working for you? 

Any problems, let me know!

**Comment by colindean** [comment]
I'm still awaiting update of our ZenHub Enterprise extension. I'm tracking it internally, so I'll chime back when it's been updated and I can verify it on my end.

**Comment by azenMatt** [comment]
great! we should be shipping out a new version of ZHE with support for our new Epics feature in Mid-April that will contain this bug fix as well
