### ISSUE TITLE
Markdown Task Link pipeline

### ISSUE THREAD

**Issue by tholum** [ZenHubIO/support#586]
It would be nice if there was a way like

``` markdown
#123:pipeline
```

to show the pipeline of a specific bug It may be a replacement for #585

**Comment by azenMatt** [comment]
i'm not sure I totally understand the use case here, would you be able to expand a little? 

is it the same as #585, but where 585 would show it in the referenced issue, this would show it in the original issue (where the #issueNumber was entered)?

**Comment by tholum** [comment]
Basically some way to add something in a comment or status that gets replaced with which pipeline that issue is currently in ( todo, in progress,  qa ext )
