### ISSUE TITLE
Save state as GitHub Labels (ex: HuBoard)

### ISSUE THREAD

**Issue by smiller171** [ZenHubIO/support#587]
By putting the current state of a ticket in a label, you can see more information on a ticket without having the ZenHub extension. This is good for external users. If you use the same naming schema as HuBoard you would enable simple transition from HuBoard to ZenHub

**Comment by azenMatt** [comment]
Hi @smiller171, we have an issue open for this here - #19 

We don't have any plans to do this in the short term, to avoid overloading labels. However we haven't ruled it out completely - i'l post any updates into #19 



> If you use the same naming schema as HuBoard you would enable simple transition from HuBoard to ZenHub

In terms of this transition, the quickest way at the moment to do this, is to filter by a huboard pipeline label, then use the multiple issue feature: 

![image](https://cloud.githubusercontent.com/assets/7584089/13128746/0644b362-d58d-11e5-8ee2-269ef88ed744.png)

to grab all the issues and drag them to the corresponding pipeline in one go. You can then repeat for each pipeline label.

**Comment by smiller171** [comment]
Thanks for the info
