### ISSUE TITLE
Adding issues to pipeline midway through completion

### ISSUE THREAD

**Issue by Thormidable** [ZenHubIO/support#588]
Would it be possible to have a burndown step up when work is added part way through a project? (possibly as an option)

Having both the required velocity and the current work done, step up, would make it visually clear, when planning is good, but outside work has come in to disrupt the plan.

**Comment by azenMatt** [comment]
Hi @Thormidable - I 100% agree it should do this! We are currently working on improving the reporting functionality in ZenHub, of which this will be included

**Comment by deruelle** [comment]
Is there any plan to implement this in a coming sprint ?

**Comment by kendramoroz** [comment]
@deruelle we're working to release some great enhancements around reporting and will have more updates to share over the next few Sprints 🙌

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and you can follow along with scope changes in reports via #791!
