### ISSUE TITLE
Labels don't update properly onto the Zenhub board when edited.

### ISSUE THREAD

**Issue by HPRoss** [ZenHubIO/support#590]
I edited my Github labels to shorten them up (e.g. Library to Lib).  Now Zenhub is using both labels within the board view.  It cleans up each Issue separately as soon as an issue has an action performed against it (e.g. new comment).  When clicking on an issue within the board the issue displays appropriate labeling.

It appears there is a cache of the old labels? On a Zenhub server?  How can this get refreshed?

**Comment by azenMatt** [comment]
Hi @HPRoss - this is a cache issue on our side - we are currently working on a better label cache that will resolve this 

We had the same issue on Milestone changes - #244 - which we just fixed today, we just need to implement the same process for labels - il keep you updated!

**Comment by HPRoss** [comment]
Any short term workaround.

**Comment by azenMatt** [comment]
If you can let me know the org / repo names, I can reset the cache for you

**Comment by HPRoss** [comment]
Org is MopriaAlliance

Repo is:  MopriaPlugin


Thanks,
Ross

**Comment by azenMatt** [comment]
done :smile:

**Comment by HPRoss** [comment]
Thank you!

**Comment by moezbhatti** [comment]
@azenMatt any chance you also reset the cache for Oneset/oneset-android?

Also, is there an ETA on the patch?

Thanks!

**Comment by moezbhatti** [comment]
+ Reset request for QKLabs/QKSMS :)

**Comment by azenMatt** [comment]
@moezbhatti - done 

The patch is in development at the moment, so expect something in the next couple of weeks :smile:

**Comment by vicentebolea** [comment]
+1 Reset request DICL/EclipseMETA

**Comment by azenMatt** [comment]
Hi @vicentebolea - this has be reset! 

We are in the final stages of testing the full fix for this so it should be with everyone this week!

**Comment by apike** [comment]
+1 reset request for steamclock/spies, thanks! Great to see a more general fix for this is incoming soon.

**Comment by azenMatt** [comment]
@apike - done!

**Comment by rockymadden** [comment]
Please:
- cloud-elements/hykes-spec
- cloud-elements/hykes-blueprint
- cloud-elements/hykes-provision
- cloud-elements/hykes-engine
- cloud-elements/onecle.monitoring.oneneck.net

**Comment by azenMatt** [comment]
Hi all, this is now fixed! :tada: 

@rockymadden - If you can update to version 2.15.93, we now have an updated check that will keep all your labels in sync. 

This means all labels will be correct when a board is first loaded, and if a change happens to a label elsewhere, it will be updated on the board within ~10 seconds. 

Please try it out and let me know if you have any problems!

**Comment by rockymadden** [comment]
@azenMatt Thanks, seems to be working! :tada:

**Comment by peter-tse** [comment]
@azenMatt I am still noticing this issue.  I updated labels across 5 repos hoping to use them on multi repo boards and they are not showing up. I am using  v2.16.11 of the extension.  Thoughts?

**Comment by azenMatt** [comment]
Hi @peter-tse - would you be able to email me at support@zenhub.io and we will take a look into this for you

**Comment by peter-tse** [comment]
Hey Matt!

Picnic error, I realized I was looking at the boards and they were only showing labels that had been previously used rather than available.  My bad.

**Comment by azenMatt** [comment]
Thanks for the update Peter!

**Comment by mitriw** [comment]
I'm running Version 2.37.47 and this still happens
renamed a label in github and it seems the change has not propagated to the zenhub board, i can now filter by the old and the renamed label
