### ISSUE TITLE
Styling: Lighten the color of unused +1 buttons; they are too loud

### ISSUE THREAD

**Issue by joeytwiddle** [ZenHubIO/support#591]
When an issue or comment has not received any +1's, I think the +1 button could be made much less intrusive. I don't think this will reduce their usage, but it might increase our zen.

I applied this to my page, and I feel it is much calmer and less distracting.

    .zh-paw-btn.zh-paw-count-0 .zh-paw-btn-inner {
      background-color: rgba(0,0,0,0.05);
      border: 1px solid rgba(0,0,0,0.2);
      color: rgba(0,0,0,0.7);
    }

(I used alphas instead of absolute greys, because I think this fades better (contrasts less) with the slightly blueish headers above a user's own comments.)

Before:

![Current style](https://cloud.githubusercontent.com/assets/911799/13297006/3187263e-db6b-11e5-94bf-eb0d8e11285f.png)

After:

![Proposed style](https://cloud.githubusercontent.com/assets/911799/13297009/33b3725a-db6b-11e5-9cfc-015ef8639c05.png)

**Comment by joeytwiddle** [comment]
My above proposal compared to "Owner" tag:

![Compared to "Owner" tag]()

Tweaked version, slightly 3D/raised, using ` background-image: linear-gradient(#fff, #ddd) `:

![3D button](https://cloud.githubusercontent.com/assets/911799/13297469/8233b2e4-db6d-11e5-8db7-c4354b0ffc30.png)

**Comment by azenMatt** [comment]
Thanks @joeytwiddle - il pass this onto our design team :+1:

**Comment by azenMatt** [comment]
Hi @joeytwiddle - we removed the +1 buttons from ZenHub today in favour of GH reactions :+1:
