### ISSUE TITLE
Non-existent milestones or milestones with closed tickets persist in the filter

### ISSUE THREAD

**Issue by wzin** [ZenHubIO/support#593]
Hi,
I've noticed that we have (several) milestones that are persistent on the filter list. There are following cases in which milestones are persistent but they should (probably) dissapear from the filter:
- all tickets belonging to this milestone in all repos were closed
- all tickets belonging to this milestone were removed from the milestone so all milestones in all repos are just empty
- milestone was **deleted** in all repos
- milestone was **closed** in all repos

I've tried all of the above to make the milestone go away but it's still there.

![screen shot on 2016-02-29 at 13-43-17](https://cloud.githubusercontent.com/assets/353944/13394794/f7f5b5b0-deea-11e5-9572-f3b8e4ffb020.png)

Above example is for a milestone that we've closed all tickets in. When we've noticed that it still there, we've removed all tickets from it. It was still on the filter list so we've closed the milestone and later deleted it from all repos because it's still there.

**Comment by azenMatt** [comment]
Hi @wzin 

I agree with you that those 4 use cases *should* be how this works. 

Let me take a closer look at this and find out what has broken

**Comment by azenMatt** [comment]
Hi @wzin - we recently released some updated milestone cache logic that will keep this in-sync with the GH milestone list more efficiently. 

Please let me know if you are still seeing problems

**Comment by wzin** [comment]
@azenMatt this fixed the issue for me. Thank you so much for this fix.
