### ISSUE TITLE
Time tracking and invoicing?

### ISSUE THREAD

**Issue by metasoarous** [ZenHubIO/support#594]
I love estimates, burndown, velocity, boards, and all that jazz. But for those of us (contractors) who need to keep their eyes on billable hours more so than turnaround dates, being able to compare estimates and time entries, as well as produce invoices, would be a real boon. I've been looking for something that integrates issues/todos and time tracking, and have found nothing nice; if you built it integrated with github and zenhub, I'd be in... Zen :-)

**Comment by azenMatt** [comment]
Hi @metasoarous - the ability to log time is on our long-term roadmap and we have an issue here - #218 - that is currently tracking this. 

i'l keep that updated with our progress :+1:
