### ISSUE TITLE
Feature Request: Ability to log/view issues that didn't get completed in a sprint.

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#595]
## There isn't a way to log what _wasn't_ completed in a sprint.

So my current work flow is:

- commit to a sprint with the team.
- Work though our iteration cycle.
- review our progress and revise our backlog for our next cycle.

From the burndown view in a closed out milestone I can only see what's been **completed** because everything that wasn't finished is moving to our next sprint.

Is there anyway ZH could log what was committed to the sprint?

**Comment by azenMatt** [comment]
Hi @benschac - this is a really important piece that we do need to build. I have had lots of interest from different teams that need to see this. 

I have got this included in up upcoming reporting changes, so expect to see this during Q2 :+1:
