### ISSUE TITLE
Edit and Close multi-repo milestones from zenhub board

### ISSUE THREAD

**Issue by karlcz** [ZenHubIO/support#597]
We have over a dozen technology repos in one organization and under one board. If we define milestones with the same name and due-date, they get merged into a single milestone in the milestone filtering facet, etc.  However, this is tedious and prone to error. If the due-date is slightly off, we get multiple milestone entries with the same name in the filter facet.

It would be a nice enhancement to be able to define new milestones from the board and have a checklist to broadcast this to as many or as few repos as you like (across the repos on the board for which you have sufficient privilege).

**Comment by azenMatt** [comment]
100% agree @karlcz 

It is on it's way :smile:

**Comment by goanpeca** [comment]
Hi @azenMatt, any update on this feature :-p ?

**Comment by azenMatt** [comment]
No updates right now other than to say that it is a confirmed feature that will be moving into development in the near term. I am hoping to have something live to address this during Q2-3.

**Comment by Anvil102** [comment]
This feature is something I would love to see ASAP. Milestone management across multiple repo's is a common issue at Leap Motion. Having an elegant tool to swiftly add/remove multi-repo milestones would make planning extremely flexible and allow us to collaborate better in real time while backlog grooming. The issue only grows worse with time as we add more repos.

It would be nice, too if ZH plussed the overall milestone editing in GH if you add the multi-repo milestone creation. The UX/UI flow for editing milestones in GH is a bit antiquated at the moment:
 0.  too many clicks to do what I want when editing a single milestone in a single repo via the list view for milestones,
 0. not being able to see a list of issues in the milestone while editing milestone details.

**Comment by sap1ens** [comment]
+1. This is currently a big blocker.

**Comment by jszroberto** [comment]
Please, implement this soon

**Comment by maparrar** [comment]
+1.

**Comment by daka1510** [comment]
+1

**Comment by blacksails** [comment]
Much excite <3

**Comment by jimm1419** [comment]
+1

**Comment by bvsatyaram** [comment]
+1

**Comment by mathesond2** [comment]
+1

**Comment by jakeleboeuf** [comment]
+1

**Comment by levithatcher** [comment]
+1

**Comment by cgole** [comment]
+1

**Comment by ldabiralai** [comment]
Would be good to get an update for this!

**Comment by azenMatt** [comment]
Hi @ldabiralai - this one is still a big priority for us and will be worked on once Issue/PR linking - #568 - is live. 

I can't make a firm time commitment on that - but my guesstimate would be January 😄

**Comment by ldabiralai** [comment]
Awesome, thanks @azenMatt 

Look forward to using it once it's available!

**Comment by jakeleboeuf** [comment]
@azenMatt doooopee.

**Comment by simonwh** [comment]
If anyone needs a temporary solution for syncing/creating milestones across repos while we wait for this (awesome) feature, [this does the trick](https://github.com/Xiphe/github-sync-labels-milestones).

**Comment by azenMatt** [comment]
Hi everyone - thank you for the continued patience as we get this one live! 

version 2.25.21 just got released which allows the creation of a milestone in all connected repositories at the same time - 

![image](https://cloud.githubusercontent.com/assets/7584089/21726794/03d7192a-d3f3-11e6-90cd-703f6e019ebd.png)

![image](https://cloud.githubusercontent.com/assets/7584089/21726824/2d34079c-d3f3-11e6-8f5a-5a5ac36f4b20.png)

This is a first pass at this functionality to make sure that at least new milestones can be created. I appreciate the pain point still exists for edit milestone and close milestone - which we will be adding to this functionality in the future (assuming the create proves useful for everyone!) 

Let me know if this works for you and if it would be useful to expand to edit/close 🎆

**Comment by daka1510** [comment]
@azenMatt - thanks, that's really a great enhancement.

regarding your comment:
> Let me know if this works for you and if it would be useful to expand to edit/close

Long-term, I'm sure that would be very useful, too!

**Comment by mchavarriae** [comment]
Hi

I make an small nodejs program, It uses the github api to do the job.

https://github.com/tevix/zenhub-milestone-updater

**Comment by joihelgi** [comment]
Close and edit all connected repositories at the same time would be awesmoe

**Comment by giladgrush** [comment]
@azenMatt the multi-milestone feature is great, however not being able to close the multi-milestones makes this feature not ready for use yet...

**Comment by getvega** [comment]
Taking on @mchavarriae's script 👍  a little bit further:
https://www.npmjs.com/package/ghm-cli - Node 7 only atm, sorry.

**Comment by mhelvens** [comment]
Yep, please give us Edit and Close. :-)

**Comment by shenghu** [comment]
I failed to create multi-repo milestone. Zenhub prompts me that 'there was error creating milestone in x,y,z'  Is there known issue about this? @azenMatt

**Comment by azenMatt** [comment]
Hi @shenghu - do you have permissions for all the repos you were trying to add to? Please drop me an email to support@zenhub.com and we can take a closer look. Thanks

**Comment by shenghu** [comment]
@azenMatt Sent mail. I have permssions to all repos, which are created by me.

**Comment by magtastic** [comment]
The edit/close milestones feature would make my life so much easier! 😇

**Comment by katparejko** [comment]
edit/close please!

**Comment by j0nscalet** [comment]
This is awesome Zenhub team, great work! 👍 😄 🎆

**Comment by apbassi89** [comment]
+1 for edit/close, we could absolutely benefit from it

**Comment by wulfgar61** [comment]
+1 for edit/close

**Comment by rjhilgefort** [comment]
Is there any update on timing for this or if it's in the works? Thanks!

**Comment by azenMatt** [comment]
@rjhilgefort - it's 'confirmed' in the sense that we know we need to take care of it. But I don't have any timing updates for you right now. 

#156 is our biggest focus right now - once that is live I should be able to give a date on this as it will become one of the top priorities

**Comment by rjhilgefort** [comment]
@azenMatt Thanks so much for the communication and the great product. Looking forward to seeing it get even better.

**Comment by shacharz** [comment]
eta?

**Comment by emilysnothere** [comment]
+1 for edit/close

**Comment by joshgosselin** [comment]
Another +1 for the multiple edit/close.. closing 54 milestones each week is a tedious jobs...

**Comment by theoutlander** [comment]
+1 for edit/close milestones!

**Comment by kashifnoorani** [comment]
+1 for edit/close milestones!

**Comment by azenMatt** [comment]
Moving this into 'In Progress' now that the ZenHub Web app is live

😀 

It will be live during out current sprint so 1-2 weeks 🤞

**Comment by shenghu** [comment]
@azenMatt What is 'ZenHub Web app'? Is there link to doc or access to it?

**Comment by kendramoroz** [comment]
@shenghu if you're looking to get started on an account that is tied to github.com, you can access the ZenHub web app via [app.zenhub.com](https://app.zenhub.com). If you're using ZenHub Enterprise, get in touch with us at support@zenhub.com with the organization and team you belong to and we'll be able to point you to the right URL for your team!

**Comment by TimirWHCC** [comment]
I created milestone with 4 repository. I created 5th repository after I created milestone. How to add this new repository to existing milestone? Thanks!

**Comment by azenMatt** [comment]
Hi @TimirWHCC, while we push this functionality to be able to do this in the application over the finishing line during the next couple of days, the best way to add it now is to create a new milestone in the 5th repository that has a matching title and end date to the others. ZenHub will then treat it all as the same milestone based on these details matching.

**Comment by danstepanov** [comment]
+1 on edit/close

**Comment by azenMatt** [comment]
The first version of this is now live! 

we just launched a milestone page inside app.zenhub.com to make it easy to manage multi-repo milestones via create / edit / delete 

This can be access via the 'milestone' section on the top-bar menu. 

Currently, this is only accessible via the web app version, we are working on how to get the same functionality accessible via the extension

**Comment by joshgosselin** [comment]
PERFECT! I've just closed all my old milestones in a couple of clicks! Thank you!

**Comment by jakeleboeuf** [comment]
But I no see itttt

**Comment by jakeleboeuf** [comment]
Oohhh, found it in the app- it's just is not available in the github extension. Reading is hard.

**Comment by mhelvens** [comment]
Wait, there's an app? What happened to "context-switching is costly"?

**Comment by kendramoroz** [comment]
@mhelvens we here you! 

Echoing Matt's note above, we're working on porting this into the extension so you don't have to context switch to manage milestones in bulk 😊 ! We'll post updates to this issue once we port it over.

**Comment by caharding** [comment]
+1

**Comment by DanielePucci** [comment]
+1 for edit/close in the extension

**Comment by pjatx** [comment]
+1 for edit/close in the extension as well

**Comment by martinbethann** [comment]
+ 1 for edit/close - we have 25 connected repos under one milestone.  Thank you!

**Comment by leonzucchini** [comment]
+1 for edit/close
