### ISSUE TITLE
Burn Down Chart Request: Option to Toggle PR's as issues

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#598]
## Toggle on and off PR's from Burndown Chart

```gherkin
As a project manager
I want to have the option of hide/showing PR's in my burn-down
So that I don't see a whole bunch of unestimated issues when in reality they're all estimate.
```

**Comment by azenMatt** [comment]
Thanks @benschac - we have this in our bucket for reporting improvements coming in Q2 :+1:

**Comment by azenMatt** [comment]
This is now possible - on the latest version (2.23.15) you can toggle between showing and not showing PR's 

![image](https://cloud.githubusercontent.com/assets/7584089/17605721/aeb569ce-5fd0-11e6-84a2-623e4b3f778d.png)


![image](https://cloud.githubusercontent.com/assets/7584089/17605739/c309cc3a-5fd0-11e6-8679-dd0d6da387dd.png)
