### ISSUE TITLE
Can't see burndown for closed milestones

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#600]
Any way closed milestones can be shown in burndowns? Currently only open milestones are the only ones showing in the dropdown.

**Comment by azenMatt** [comment]
Hi @benschac - we can have a look into this. 

We also want to improve velocity tracking in the near future - which could be a more useful way to review closed milestones?

**Comment by benschac** [comment]
Both of those features would be just dandy for me and the teams I work with.  :)

**Comment by azenMatt** [comment]
Hi @benschac - we just released 2.15.72 which will show you the last 5 closed milestones. 

Better velocity tracking coming soon!

**Comment by benschac** [comment]
:)

On Fri, Mar 11, 2016 at 12:51 PM, Matt Butler <notifications@github.com>
wrote:

> Closed #600 <https://github.com/ZenHubIO/support/issues/600>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/600#event-586737452>.
>



-- 
*Benjamin Schachter *• Project Manager
* <http://www.dramafever.com/>*    |   bschachter@dramafever.com
