### ISSUE TITLE
Support the ability to copy issues between repos

### ISSUE THREAD

**Issue by gabrieljoelc** [ZenHubIO/support#602]
The addition of #350 is awesome! It would also be great to copy the title and description of an issue to another repo. Sometimes we have common configuration that needs to get updated in all of our applications or we have CVEs that need to get resolved in all of our applications, and creating one issue in one repo and copying them to other ones with a click would be great.

**Comment by azenMatt** [comment]
thanks @gabrieljoelc, should be pretty easy to implement as it is the 'move' functionality just without the 'close' action to the original issue. 

Moved into discussion to see how useful this would be to the rest of the ZenHub community

**Comment by kevinSuttle** [comment]
Would it be easier to have org-level issues? https://github.com/kevinSuttle/github/issues/51

**Comment by gabrieljoelc** [comment]
> Would it be easier to have org-level issues?

@kevinSuttle that might be handy for some things but for the examples I mentioned, I would rather have it in each repo because then 3 different people can be assigned and open 3 different PRs to close them.

**Comment by kevinSuttle** [comment]
@gabrieljoelc Interesting. Can you go into more detail or provide a more concrete example? (I don't work for ZenHub. Just genuinely curious.)

**Comment by gabrieljoelc** [comment]
> Can you go into more detail or provide a more concrete example?

@kevinSuttle sure here's a couple from the issue description

> Sometimes we have common configuration that needs to get updated in all of our applications or we have CVEs that need to get resolved in all of our applications

**Comment by kevinSuttle** [comment]
I guess in the meantime, you could use [task lists](https://github.com/blog/1825-task-lists-in-all-markdown-documents) in an over-arching issue, with individual or @ [team mentions](https://github.com/blog/1121-introducing-team-mentions). The [new issue templates](https://github.com/blog/2111-issue-and-pull-request-templates) would probably be useful too.

**Comment by gabrieljoelc** [comment]
Yea, we use task lists all the time but I don't see that as a replacement for a specific issue in each repo when a common task is needed for each repo. A copy feature would be helpful.

**Comment by azenMatt** [comment]
Another example of this, from a separate team, was the ability to have a set of issues in a repo that you know are going to be repeated several times. 

For example, if you have an onboarding repo - that contains a number of issues that must be completed every time a new team member joins. By being able to copy a number of issues, the team can assign out what needs to be done each time. 

As they find steps that had been missed, they just need to create an issue in the master repo to capture it. 


---------

Task lists could also work for this... but I think they are held back by the lack of audit trail. You don't know who marked them as closed

**Comment by azenMatt** [comment]
Thoughts on adding a simple check box to the current functionality so you can decide if it should be left open or not? 

In theory, closing = move issue whereas leaving open = copy issue

![image](https://cloud.githubusercontent.com/assets/7584089/13938763/eda7fa6c-ef8b-11e5-938b-87d6990cacdc.png)

**Comment by mogul** [comment]
Better I think if you show two buttons, one for "move" and one for "copy", with hover on them to explain what will happen.

**Comment by azenMatt** [comment]
oops, I forgot to close this one after we implemented a specfic copy option some time ago! 

![image](https://cloud.githubusercontent.com/assets/7584089/21198506/8819b6b8-c1f4-11e6-99f5-5b2f505a40e5.png)

**Comment by tweckstromatswap** [comment]
We are working on a bigger additional bunch of functionality, related to a single theme. I've split the implementation into three phases. I've planned to have one epic per phase. I'd like to copy the description, title, dependencies, and labels from the first epic to two new epics, and then edit the titles of the 2nd and 3rd phase epics. Can this be done within a single repository somehow?
