### ISSUE TITLE
Notify when someone +1's your contribution

### ISSUE THREAD

**Issue by rainboxx** [ZenHubIO/support#603]
I'm missing some response to +1's from others on my contribution. At least it would be good if it would either send me an email or post it to Slack (maybe to me personally as a bot, if that is possible).

**Comment by azenMatt** [comment]
I guess we should close this one now that GitHub has reactions! I like the idea though!

**Comment by rainboxx** [comment]
Yeah, I should have waited some hours so that GitHub would have had the time to announce their feature :smile:.
