### ISSUE TITLE
Closed burndown charts not available

### ISSUE THREAD

**Issue by spemmons** [ZenHubIO/support#604]
In the past, I could select a closed Milestone to review the burndown chart. Now the closed milestones no longer display in the selection list.

**Comment by azenMatt** [comment]
Hi @spemmons - we are just prepping a fix to allow you to see the last 5 closed milestones. It should be live shortly

**Comment by azenMatt** [comment]
2.15.72 has just been released which shows the last 5 closed milestones in the burndown menu. 

Better options for looking back at historic velocity are coming soon!

**Comment by spemmons** [comment]
Wow. Open loop confirmation process. Disappointing. I still can't see any of my closed milestones in the burndown menu.

**Comment by azenMatt** [comment]
Sorry to hear that @spemmons, you may need to trigger a milestone cache refresh to force this through. Do you mind renaming a milestone and then taking a look at the burndown page? This should force a cache refresh and cause these to show. They should then have a closed icon next to them like this: 

![image](https://cloud.githubusercontent.com/assets/7584089/13732865/de0ec8f0-e947-11e5-9539-9c610c6d8bfb.png)

The milestone can then be renamed back. This should only be needed to be done the first time, it will then stay in sync.
