### ISSUE TITLE
Native Github Reactions to Pull Requests, Issues, and Comments

### ISSUE THREAD

**Issue by dmakhno** [ZenHubIO/support#605]
Would be nice to integrate "+1" with recently released https://github.com/blog/2119

**Comment by azenMatt** [comment]
Integrate or remove? 

Currently, we were looking to depreciate the +1 functionality in favour of the GitHub reactions. 

Personally I think the new reactions cover the same use case, so I am happy to use this as an opportunity to 'tidy up' the interface. Removing +1's, the file uploader and the export issue button (replaced by the move issue functionality) 

Open to thoughts though if they are still useful?

**Comment by dmakhno** [comment]
@azenMatt,
**remove** from single issue/prs
**integrate** for issue/pr lists

![image](https://cloud.githubusercontent.com/assets/1913863/13753952/d4899f72-ea1d-11e5-87b6-826426a85af0.png)

**Comment by azenMatt** [comment]
Hi @dmakhno - No API has been provided for these reactions yet (although i believe on is on its way) I would also expect GitHub to be thinking about how these reactions can be better exposed to users in the issue list. 

Due to this, we have decided that we will be removing the ability to +1 any new issue. If an issue already has a +1 against it, you will still be able to see it - so that you do not lose any data stored in these votes (for example all the +1's in this repo!) 

We are expecting to roll this out this week!

**Comment by aensley** [comment]
Great news! Thanks for tidying up. Hoping the file uploader follows suite.

**Comment by azenMatt** [comment]
@aensley - it is! 

+1's, file uploader and export issue are all being 'spring cleaned' out :smile:

**Comment by rockymadden** [comment]
@azenMatt IMO, this was a hasty and non-optimal:

- The marketing website, documentation, and this very project readme all mention ZH voting as a feature
- Nothing was mentioned on the blog about it's removal
- One the major "features" of ZH's voting was its at-a-glance properties throughout GH, only one of which exists in GH today
- Hoping that GH will open up this API very soon is okay, but what if it doesn't happen?

**Comment by azenMatt** [comment]
Hi @rockymadden, 

Thank you for the feedback, I appreciate your thoughts here, they will be very useful in facing future situations like this. Adding features is something we have had lots of practice with, removing them - not so much.

I will make sure that we do a much better job in communicating these changes with a meaningful amount of lead time for feedback in the future. 


> The marketing website, documentation, and this very project readme all mention ZH voting as a feature

I have just removed this from the readme, and we have a PR in progress for the website. Thanks for pointing these out
