### ISSUE TITLE
Add activity notifications to Issues on the Board

### ISSUE THREAD

**Issue by hiphapis** [ZenHubIO/support#607]
![image](https://cloud.githubusercontent.com/assets/18629/13734010/d5ec51c0-e9dc-11e5-90be-b82916ec1b68.png)

The blue border on the left side which means 'activity' is very helpful to figure out my new tasks. So, it will be great if this appear on Zenhub Board as well. It's an awesome feature really

**Comment by azenMatt** [comment]
Agreed @hiphapis - we actually used to have this for a while - but scaled it back while we work on board performance. 

Once we have the board running faster (which will be soon!) we will look to bring this back!

**Comment by hiphapis** [comment]
Hi Guys~
Still waiting for your react ;)

**Comment by kendramoroz** [comment]
We recently launched new activity notifications on Issue cards! [Dig into the guides here](https://zenhub.freshdesk.com/support/solutions/articles/43000030576-view-issue-activity-in-real-time-on-the-board). And of course, let us know what you think!

![image.png](https://images.zenhubusercontent.com/5833aa0bb9dc3c6220225356/bc5c8616-fd8a-4816-a30d-11971141c32e)
