### ISSUE TITLE
Add 'closed' attribute to pipeline

### ISSUE THREAD

**Issue by hiphapis** [ZenHubIO/support#608]
I have a problem in tracking my performance using burndown chart, because it only counts 'closed' issues.

I would suggest another type of pipeline as below:
- Backlog
- Todo
- In progress
- Need feedback
- Ready for test
- Completed (closed)
- Released (closed)

Completed: task is done. but it's not deployed
Released: task is done too and it's deployed

The reason is that there are some cases that some tasks are being delayed to be released due to release timing or other related tasks to be done, even if those are already have been finished.

Burndown chart now is unable to track the exact status of current proceedings.

It can be a solution of this problem to create a new pipeline which works the same as 'closed'.

**Comment by azenMatt** [comment]
Hi @hiphapis - that makes a lot of sense. We have an issue here - https://github.com/ZenHubIO/support/issues/433 - to track how to specify which pipeline should count as closed which will allow you to do this
