### ISSUE TITLE
Disable "new issues" column

### ISSUE THREAD

**Issue by justinabrahms** [ZenHubIO/support#610]
My group has 14 repos. When we look cross-repo, zenhub freezes for multiple folks' computers. This makes working really difficult. If we could disable the left-most "new issues" column, it would probably make it better, given there are a few hundred issues there. We've already disabled the close column and PRs.

Help? cc @pdpinch

**Comment by azenMatt** [comment]
Hi @justinabrahms - understood. 

We have a big refactor going live in a couple of weeks that should really improve performance. 

Are you ok if we check in once that is live and see if that has solved the problem, or if hiding the new issues would still be useful?

**Comment by justinabrahms** [comment]
Sure thing.

On Wednesday, March 16, 2016, Matt Butler <notifications@github.com> wrote:

> Hi @justinabrahms <https://github.com/justinabrahms> - understood.
>
> We have a big refactor going live in a couple of weeks that should really
> improve performance.
>
> Are you ok if we check in once that is live and see if that has solved the
> problem, or if hiding the new issues would still be useful?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/610#issuecomment-197629289>
>


-- 
Sent via mobile phone.

**Comment by azenMatt** [comment]
Hi @justinabrahms - how is this looking for you now? We just pushed some updates that should improve the performance in board. Further updates are coming next week to improve the initial load time. 

Do you still see ZenHub freezing on v2.21.2?

**Comment by justinabrahms** [comment]
I'm no longer using your product.

**Comment by azenMatt** [comment]
Sorry to hear that :( 

well it is much faster now if we can tempt you back! 

All the best - Matt

**Comment by pdpinch** [comment]
I'm still using it. We're up to 21 repos now and it doesn't freeze up anymore. Thanks!

**Comment by azenMatt** [comment]
Glad to hear it @pdpinch 😄  we should have another big speed boost over the next two weeks that should give an even bigger bump
