### ISSUE TITLE
Exclude a label from the board view

### ISSUE THREAD

**Issue by jdelStrother** [ZenHubIO/support#611]
Hi - is there any way of temporarily excluding issues with a given label from the boards view?   I was hoping I might be able to just mess with the URL (eg changing `&labels=foo` to `&labels=-foo`), but no such luck.

**Comment by azenMatt** [comment]
Not yet! but we will improve our filtering soon to make it easier to build and/or/not queries on labels!

**Comment by azenMatt** [comment]
We have an issue tracking this here - https://github.com/ZenHubIO/support/issues/68 - so i will close this one to keep it in one place. Please subscribe to that issue to know as soon as this is ready!
