### ISSUE TITLE
Plans of backing ZH voting via GH reactions?

### ISSUE THREAD

**Issue by rockymadden** [ZenHubIO/support#612]
With the recent release of GitHub Reactions<sup>TM</sup> (https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments), are there any plans to back the ZenHub voting feature via GH :+1: and :-1: reactions in the future or will they simply remain discrete concepts?

**Comment by azenMatt** [comment]
Hi @rockymadden - at the moment, I think these work well as discrete concepts - but i'm always interested to explore different areas - so I wouldn't rule our us doing something cool with the reactions :smile:
