### ISSUE TITLE
Voting button not visible

### ISSUE THREAD

**Issue by rockymadden** [ZenHubIO/support#613]
### Chrome 49.0.2623.87 with ZH 2.15.76:
![chrome](http://share.rockymadden.com/111I2T3r2I3T/Image%202016-03-16%20at%2012.00.11%20PM.png)

---

### Firefox 45.0 with ZH 2.15.76:
![firefox](http://share.rockymadden.com/3N0l231w2N1D/Image%202016-03-16%20at%2012.01.45%20PM.png)

**Comment by aensley** [comment]
They removed it on purpose because it was redundant to GitHub's new built-in reaction system. Been noted several times.

**Comment by rockymadden** [comment]
@aensley Thanks! I notice it is still on the website many times, is noted in this very repo readme as being a feature, is still in the API, isn't on the blog, and multiple issue searches yielded nothing obvious. Where did you see this noted?

**Comment by rockymadden** [comment]
To answer my own question, noted in closed issues: https://github.com/ZenHubIO/support/issues/605
