### ISSUE TITLE
Feature Request: UI way to filter issues by label exclusion

### ISSUE THREAD

**Issue by JcMinarro** [ZenHubIO/support#615]
Allowing to filter the issues that doesn't have a specific label is really powefull, especially if combined with other label filters.

It works very well with tags like "nice_to_have" "improvements" "later" that are very powerfull to help you when you start having way too many issues to handle

Github allow you to do it on their search box:
`-label:myLabel`

**Comment by azenMatt** [comment]
Hi @JcMinarro - we are looking into how we can improve this, so that using the filters you can build up an 'And' 'Or' 'Not' query for what you want to see. 

I'm going to close this one as we are tracking this in issue #68 , I will keep that issue updated with our progress!
