### ISSUE TITLE
Burndown won't show up with no error

### ISSUE THREAD

**Issue by wzin** [ZenHubIO/support#616]
Hi,

this is what I'm seeing today for one of our projects.

<img width="1071" alt="screen shot 2016-03-18 at 12 38 50" src="https://cloud.githubusercontent.com/assets/353944/13876709/653cf1c8-ed06-11e5-8484-761a56c4c373.png">

That's the error in console:

<img width="427" alt="screen shot on 2016-03-18 at 12-36-17" src="https://cloud.githubusercontent.com/assets/353944/13876712/6dc12846-ed06-11e5-9210-5c2f8ad118bd.png">

**Comment by azenMatt** [comment]
Hi @wzin - Would you be able to update to the latest version - 2.15.84 - and see if this is resolved? We pushed a change which will fix this :+1:
