### ISSUE TITLE
Empty Burndown

### ISSUE THREAD

**Issue by pdpinch** [ZenHubIO/support#622]
I'm having trouble with burndown charts for the (open) repository at https://github.com/mitodl/micromasters/

Our [current milestone](https://github.com/mitodl/micromasters/milestones/Something%20on%20a%20Stick%20Day) has 9 issues in it:

![working-milestone](https://cloud.githubusercontent.com/assets/430126/13918627/ffbb54c6-ef3e-11e5-8c60-4ecbc3761184.png)

But the burndown chart is empty:

![broken-burndown](https://cloud.githubusercontent.com/assets/430126/13918642/0fb064c0-ef3f-11e5-8922-91cd8b69e3ea.png)

**Comment by azenMatt** [comment]
Hi @pdpinch - we are taking a look into this now

**Comment by azenMatt** [comment]
@pdpinch - can you update to 2.15.87 and try this again? We just pushed a fix for it. 

it is working for me - 

![image](https://cloud.githubusercontent.com/assets/7584089/13939076/b8e83f50-ef8e-11e5-9ec0-c76254485a9d.png)

**Comment by pdpinch** [comment]
Working for me now with 2.15.87. Thanks.
