### ISSUE TITLE
Blank boards tab

### ISSUE THREAD

**Issue by karlcz** [ZenHubIO/support#624]
Using Firefox with the Zenhub extension updated today, the "Boards" tab is completely blank and the browser seems inactive (none of the 100% cpu spinning we'd usually see if the board tab was just slowly loading).

**Comment by azenMatt** [comment]
Hi @karlcz - look like something is broken on the ZenHub side following the GitHub downtime this morning. 

We are on it and should have a fix live within the next hour

**Comment by azenMatt** [comment]
Hi @karlcz - we just pushed a fix to this, can you manually update to - 2.15.86 - and see if this is fixed for you now?

**Comment by delynn** [comment]
@azenMatt Working for me now. Thanks!

**Comment by manzettidenis** [comment]
working for me too at Chromium. :+1:
