### ISSUE TITLE
Boards have disappeared!

### ISSUE THREAD

**Issue by hbenoit** [ZenHubIO/support#626]
Trying to open Boards on our repos - and we get a blank screen - 

video - http://screencast.com/t/Eb38QxYtSym

**Comment by lab3** [comment]
Ditto

**Comment by lab3** [comment]
I just update to version: 2.15.86 and that seems to have resolved it.

**Comment by paigepaquette** [comment]
Hey folks, glad to see you've upgraded to the latest version. Shortly after GitHub's outage this morning, we noticed this issue affecting a portion of our users and immediately began working on a fix. We released 2.15.86 shortly after which restores this functionality.

For anyone else who has yet to update: you can do this manually in Chrome by visiting Chrome://extensions, clicking "Developer mode", then clicking "Update extensions now". On Firefox, visit the Addons window. The update will roll out automatically to all users shortly, and we apologize for the interruption. 

[Follow us on Twitter for real-time status updates](https://twitter.com/ZenHubIO). If there's anything else we can do help, just let us know!
