### ISSUE TITLE
Keyboard shortcut to cycle through Assignees

### ISSUE THREAD

**Issue by docwhat** [ZenHubIO/support#630]
During our standup we go person-by-person instead of by issue.

Currently, we have to click on assignee for each person one-by-one (deselecting the previous person).  It would be nice to have a keyboard shortcut to go to the next/previous assignee.

**Comment by azenMatt** [comment]
Thank you for the suggestion @docwhat - added into the discussion pipeline for more feedback!

**Comment by kendramoroz** [comment]
@docwhat we've just launched a suite of 35 new keyboard shortcuts, including a new `z` `a` combo for interacting with the assignee filter on the Board 🎉  - This combined with being able to navigate the dropdown using the arrow and enter keys should help with the issue you raised of quickly navigating the Assignee list. 

You can check out the other shortcuts here: https://www.zenhub.com/guides/keyboard-shortcuts

Let us know what you think ✨
