### ISSUE TITLE
Firefox extension stops responding

### ISSUE THREAD

**Issue by karlcz** [ZenHubIO/support#633]
In my typical review flow of opening a board, clicking an issue so its details pop up, and then go to another window to look at stuff related to the review, the extension starts to misbehave.
1. I'll notice the grayed out background starting to twitch
2. When the issue details are dismissed, the word "Disconnected" will be flashing on the main board repeatedly, sometimes replaced by "Updated!" (I think, it flashes quickly)
3. Some functions continue to work for a while, like opening another issue's details, but it happens much more slowly
4. Doing something expensive like switching from "Show one" to "Show all" repo mode will just hang.
5. Reloading the page will get stuck in the moment of zen and never show the board.
Only existing the browser and restarting from scratch seems to fix the problem, until it repeats...

**Comment by azenMatt** [comment]
Hi @karlcz - would you be able to let me know how many repos you have on this board and how many issues in total you are working with? 

This sounds like it is a performance issue - for which we have been working on several update for and hope to have some big improvements out over the next few weeks.

**Comment by karlcz** [comment]
On this board we have 15 repos, about 250 open issues (across a few cross-repo milestones and many untriaged with no milestone) and about 600 closed issues (which I noticed it already truncates with a "load more issues..." link, which is nice).

**Comment by azenMatt** [comment]
got it, 250 open issues should be really fast - but 15 connected repos is going to have a big speed impact. 

The refactoring we are working on at the moment should really help the performance when a large number of repos are connected. I will keep you updated as we roll these out

**Comment by karlcz** [comment]
I don't think I've seen this happen for quite some time. I'm not sure how you like to manage your issues, so not sure if I should close it...

**Comment by kendramoroz** [comment]
Thanks for the update, @karlcz I'll close out this issue, but don't hesitate to be in touch on the community board or via support@zenhub.com if you have any questions or issues pop up! 

Have a great weekend 🎉
