### ISSUE TITLE
How to delete an issue?

### ISSUE THREAD

**Issue by masterdbpereira** [ZenHubIO/support#634]
I've created one test issue. Now I can't delete the issue.

I do not find any delete button/option.

**Comment by azenMatt** [comment]
Hi @masterdbpereira - it is currently impossible to delete an issue in GitHub. 

The only option provided is to close the issue :smile: 

What we often do to work around this if we don't want an issue to persist, is to close it and edit the details so it has no comments and no name (or just a single character for the name)
