### ISSUE TITLE
Please add the ability to use label filtering in burndown charts.

### ISSUE THREAD

**Issue by georgec-s** [ZenHubIO/support#635]
We have a number of large projects that are planning and tracking work in a single issue tracker.

They use labels to filter by Squads (small teams of 8-10 people)

Please add the ability to use label filtering in burndown charts so we can generate more meaningful charts...

(George from IBM Watson)

**Comment by azenMatt** [comment]
Hi @georgec-s 

Thank you for the suggestion - we are currently working on the designs for improved reporting in ZenHub and the ability to filter on dimensions which are not just milestones is a very common request. So this is something that we will be working on to improve our reporting. 

Would you be able to let me know if you want to see the burndown just as a label filter? Or do you want to see a certain milestone and then be able to filter within that by label?

**Comment by georgec-s** [comment]
We'd like to see a certain milestone and then filter by label. 

Additionally, we'd also like to see burnup - story point progress (filterable by label) across multiple milestones.  In that scenario, we'd be using milestones for sprints, and a collection of sprints as a release.

**Comment by azenMatt** [comment]
Thanks - that makes sense!

**Comment by mogul** [comment]
I'd like to be able to see the burndown for a single epic.

**Comment by danmosemsft** [comment]
+1 for burndown graph for a single epic. My project has 50 engineers working to the same milestone: my sub-project involves 5 of them, and I want it to burn down to zero on its own. As far as I can see my options is to have a fake milestone for the tasks in my sub project. (Right now nobody else is using ZenHub so their issues don't have estimates but if anyone starts using it, they'll appear in my burndown.)

Either filtering the burndown by epic or by label would work.

**Comment by azenMatt** [comment]
Label filtering for burndowns is now live on 2.23.19:

![image](https://cloud.githubusercontent.com/assets/7584089/17913448/c9512e9e-694e-11e6-9b76-0e5c2f510988.png)

we need to add a bit of polish to the user feedback on what the current filter is, but wanted to get it live once the functionality was working so it would be put into use

@mogul @danmosemsft - for the epic burndown we have issue #665 which we can continue to track this in

**Comment by danmosemsft** [comment]
Nice, thanks @azenMatt !
