### ISSUE TITLE
+1 button does not appear

### ISSUE THREAD

**Issue by vicentebolea** [ZenHubIO/support#639]
I am using zenhub in Firefox and Chrome under Opensuse and Ubuntu and I realized that the +1 button does not shows. Did you guys removed that feature? 

Thanks!

**Comment by tuance** [comment]
Same here, +1 button does not appear, but shows legacy totals on issues that had +1's before it stopped working.

**Comment by aensley** [comment]
https://github.com/ZenHubIO/support/issues/605#issuecomment-196584390

**Comment by azenMatt** [comment]
Hi everyone, yes we removed this functionality to reduce clutter given that the GitHub reactions provide the same (or at least similar) service.

**Comment by SamHasler** [comment]
Github reactions to the opening post aren't visible on the issues list, which was my main use-case for ZenHub's +1s. It allowed me to see which issues I was interested in easily.
