### ISSUE TITLE
Decimal on column time estimate

### ISSUE THREAD

**Issue by JeanLebrument** [ZenHubIO/support#640]
Hey guys, 

Problem that easily occurs when I play with 0.x time estimates!

<img width="506" alt="screen shot 2016-03-29 at 2 02 30 pm" src="https://cloud.githubusercontent.com/assets/3106676/14107213/018eb2ba-f5b7-11e5-938d-269447abae43.png">

**Comment by azenMatt** [comment]
We just want to make sure you can be as accurate as possible with your estimates :smile: 

But yes, we can add a better limit to this!

**Comment by Aurontwist** [comment]
.
