### ISSUE TITLE
Zenhub doesn't work on Firefox

### ISSUE THREAD

**Issue by agriffis** [ZenHubIO/support#643]
I'm not sure how to phrase that differently. Zenhub used to work on Firefox for me and seemed to stop with a FF update. No amount of re-installing or checking of about:addons is making a difference. None of the enhanced functionality is available in Github, but it works fine in Chrome for the same repositories.

Running Firefox 45.0.1 with Zenhub 2.15.94

**Comment by azenMatt** [comment]
Hi @agriffis - sorry to hear that. I just checked this and have been unable to replicate. 

Can you send an email to support@zenhub.io and the team will take a look to get this working for you? If you can send through some times you are available, a quick screen share would be the best way to trouble shoot - we will get this working again for you!

**Comment by agriffis** [comment]
@azenMatt Thanks. I tried one more thing that I hadn't tried before: explicitly removing the extension, then restarting the browser, then re-adding the extension. Now it's working again...

**Comment by azenMatt** [comment]
Thanks for letting me know @agriffis - please let me know if this happens again, I know a few people are getting this but we haven't been able to replicate yet - so any info helps!

**Comment by avitebskiy** [comment]
+1

**Comment by kendramoroz** [comment]
Hey @avitebskiy - are you having trouble getting started with Firefox? Feel free to follow up via support@zenhub.com with details if you're encountering any issues!
