### ISSUE TITLE
Wrong text color for labels with custom background color

### ISSUE THREAD

**Issue by moezbhatti** [ZenHubIO/support#644]
I've got labels with colors #FF5A57 and #FF5A57

Github shoes the text on them to be white when I'm looking at an issue, but the text is black when I'm looking at my boards

<img width="988" alt="screen shot 2016-03-31 at 12 22 22 pm" src="https://cloud.githubusercontent.com/assets/4358785/14182849/4cb8910e-f73b-11e5-8981-220461368c4d.png">
<img width="246" alt="screen shot 2016-03-31 at 12 22 39 pm" src="https://cloud.githubusercontent.com/assets/4358785/14182851/4ee2e81c-f73b-11e5-8993-0f6857624cb2.png">

**Comment by azenMatt** [comment]
Thank you for reporting this @moezbhatti - we will take a look into this to make sure that the experience is seamless between the issue page and the board. 

I have added this into the icebox pipeline as whilst it is a bug, it is (hopefully) not a showstopper for you

**Comment by moezbhatti** [comment]
Thanks, I appreciate the support

**Comment by lukescott** [comment]
Something changed recently. This is what I'm seeing now:

On board:
<img width="236" alt="screen shot 2016-07-25 at 9 09 28 am" src="https://cloud.githubusercontent.com/assets/486224/17106182/a934a384-5247-11e6-99a1-44fdaf198b02.png">

On Github:
<img width="222" alt="screen shot 2016-07-25 at 9 09 37 am" src="https://cloud.githubusercontent.com/assets/486224/17106188/b4def734-5247-11e6-996b-1d5a9f7f370e.png">

The orange labels used to have white text just like Github shows it now.

**Comment by azenMatt** [comment]
We just pushed out some updates to the board that could have caused this - we are taking a look now

**Comment by azenMatt** [comment]
How does this look for you now? We altered the method used to determine the custom colours slightly so it should be closer to GH... but we don't know exactly the threshold that GitHub switch from white to black text so it may still be different in some cases - but they should be easier to read now

**Comment by lukescott** [comment]
Looks good! Thank you 👍
