### ISSUE TITLE
Burndown trajectory

### ISSUE THREAD

**Issue by tj** [ZenHubIO/support#645]
It would be cool to have your trajectory plotted, it's usually pretty obvious anyway, but a nice quick addition :)

**Comment by azenMatt** [comment]
Hi @tj - adding in a trendline based on the current velocity in a sprint is on our roadmap as part of a number of reporting improvements we want to make. 

Our plan is to start release improvements to the existing burndown towards the end of April, with new reports (cumulative flow,  cycle time, velocity tracking) following soon after

Issue #261 is current open for trajectory so I will close this issue and we can use that to track the implementation. :+1:
