### ISSUE TITLE
Integration with Github Teams

### ISSUE THREAD

**Issue by lcguerrerocovo** [ZenHubIO/support#646]
We are using github teams at my company, are you guys planning to integrate boards with teams in the sense that I can setup a board and bring all the repositories where the team has admin rights? If not do you provide a public API where I can set up this kind of integration?

**Comment by azenMatt** [comment]
Hi @lcguerrerocovo - I think that is a great idea. We have it on our roadmap to improve the experience of integrating repos, I think basing this on teams (for those using them) would be really helpful

**Comment by almeidamarcell** [comment]
I would love that too. It's good to know that this is already on your roadmap, but when you expect to deliver it? This is important for my team, this way we can migrate to Zenhub with no problem.
