### ISSUE TITLE
Custom estimate value 0 cannot be saved

### ISSUE THREAD

**Issue by cbeams** [ZenHubIO/support#648]
I am seeing precisely the same behavior reported by @vsinghkpcc in #318, but with value `0` instead of `0.5`.

Repro steps:

1. Create a new story point value of `0`
1. Notice that the value persists in the set of available story points.
1. Assign a `0` estimate to a new or existing issue.
1. Notice that the assignment is reported in the issue timeline, e.g. "@cbeams changed the estimate from 1 to 0"
1. Notice that `0` does appear as expected in the estimate section of the issue immediately after assignment
1. Refresh the page
1. Notice that the `0` value has disappeared from the estimate section

**Comment by azenMatt** [comment]
Hi @cbeams - you are right, this is happening - we will get it fixed

**Comment by cbeams** [comment]
Thanks!

**Comment by cbeams** [comment]
Update: it appears that `0` value estimates are now persistent, i.e. survive the page refresh in step 6 of the issue description. That is, after page refresh, one still sees the blue dot in the estimate section of the issue detail page.

However, `0` value estimates still do not show up when looking at the board. That is, one does *not* see the blue dot on these issues from that perspective.

**Comment by azenMatt** [comment]
Well spotted ;) we are half way through the fix - il let you know once it is completed

**Comment by azenMatt** [comment]
v2.16.23 is now live which has both 0 estimates working in the issues pages and on the board :)

**Comment by cbeams** [comment]
I've [upgraded](http://lifehacker.com/5805239/how-to-manually-update-your-chrome-extensions) to v2.16.23 and confirmed the fix. Thanks! /cc @bamboo.
