### ISSUE TITLE
Zero issues - boards JS error

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#650]
A javascript error occurs while attempting to open the boards on a repo that has zero issues (no new & no old).

> Uncaught TypeError: Cannot read property 'name' of undefined - main.js: 29

Here is where I noticed this issue: https://github.com/Mottie/ZenHub-userscripts/issues#boards

**Comment by azenMatt** [comment]
Thanks @Mottie - I get this as well - 

![image](https://cloud.githubusercontent.com/assets/7584089/14229863/1af354b2-f8f6-11e5-8a4c-ea0adcaff15e.png)

We are supposed to just show a blank board in this case, we will get it fixed :)

**Comment by Mottie** [comment]
Found another error.... while trying to open this page:

https://github.com/isaacs/github/issues/18

which has over 1400 comments, the page times out and shows a mad unicorn. In the console, I see this JS error:

> Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'. - main.js:21

**Comment by azenMatt** [comment]
I also see the Unicorn - but with the error 

>Failed to load resource: the server responded with a status of 502 (Bad Gateway)

We will take a look at this to make sure that it isn't ZH causing the problem, but it happens to me on Chrome and Firefox even without ZenHub installed, so this might be on the GitHub side with that many comments. 

It loads on mobile for me, and on Safari - but then the page is really laggy

**Comment by azenMatt** [comment]
> on Safari - but then the page is really laggy

I take that back :) It works on Safari when I am not logged in, but once I log in, it falls over (perhaps because it has to load extra content like reactions that it didn't when you are logged out?) 

![image](https://cloud.githubusercontent.com/assets/7584089/14234496/e74674fc-f998-11e5-92e2-c86f5ef1443d.png)

so I am going to declare ZH innocent for this :stuck_out_tongue_winking_eye:

**Comment by Mottie** [comment]
LOL I know ZH isn't causing the problem... it is definitely a GH issue. I was just reporting the console error that I saw that was associated with ZH.

**Comment by azenMatt** [comment]
Thanks @Mottie - we are now handling this better with an empty board rather than a forever loading screen! 


live in 2.16.25
