### ISSUE TITLE
Discussion Sidebar

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#655]
I normally have my GitHub browser window zoomed to 110% and it now makes the sidebar take up too much height - ZenHub is adding Pipeline, Estimate, Epics and a Move Issue button. With more labels, the move issue button would not be visible until you scroll to the bottom of the issue:

This screenshot at 100% zoom is 820px in height; at 110% it grows to 890px.

![sidebar](https://cloud.githubusercontent.com/assets/136959/14266714/bfce9c18-fa8f-11e5-9bca-4909b7cb7978.png)

**Comment by azenMatt** [comment]
Thanks for the feedback @Mottie - it is an area we are trying to be very careful with. 

Our general thought was that this list is ordered roughly by 'importance' with the most used information at the top. For example, a pipeline will be updated several times during an issues lifecycle, as will will labels and milestones. Estimates and Epics may only be used once. And lock, unsubscribe and move would only be used for special circumstances (not every issue) 

As such, having to scroll down to reach the move issues was ok (not ideal, but ok) 

Happy to look into alternative options here?

**Comment by Mottie** [comment]
This is just an idea... I'm sure it'll make your designer cringe :laughing: 

![compressed-sidebar](https://cloud.githubusercontent.com/assets/136959/14333981/09bd6470-fc17-11e5-9eea-b261b1b039a2.png)

**Comment by azenMatt** [comment]
I like it :) 

We will take a closer look next time we are performing a redesign and see if we can incorporate something like this to make selecting easier
