### ISSUE TITLE
Create Epic button

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#656]
When opening an issue here on ZenHub, I am seeing the "Create an epic" button, was this intentional?

**Comment by Mottie** [comment]
Guess not... it lets me try to add stuff, but it doesn't work :stuck_out_tongue_winking_eye:

**Comment by phillipadsmith** [comment]
Seeing the same thing. Seeing it referenced elsewhere in this repo. What's up?

**Comment by azenMatt** [comment]
Thanks - we are fixing :)
