### ISSUE TITLE
Way to push 10 requests per minute API restriction 

### ISSUE THREAD

**Issue by benschac** [ZenHubIO/support#657]
Hey,

Is there any way we could bump up the request limit?  I would happily pay for it :).

Thanks.

**Comment by Mottie** [comment]
From https://developer.github.com/v3/search/#rate-limit

> The Search API has a custom rate limit. For requests using Basic Authentication, OAuth, or client ID and secret, you can make up to 30 requests per minute. For unauthenticated requests, the rate limit allows you to make up to 10 requests per minute.

**Comment by benschac** [comment]
thank you!

On Mon, Apr 4, 2016 at 7:27 PM, Rob G <notifications@github.com> wrote:

> From https://developer.github.com/v3/search/#rate-limit
>
> The Search API has a custom rate limit. For requests using Basic
> Authentication, OAuth, or client ID and secret, you can make up to 30
> requests per minute. For unauthenticated requests, the rate limit allows
> you to make up to 10 requests per minute.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ZenHubIO/support/issues/657#issuecomment-205539740>
>



-- 
*Benjamin Schachter*
Project Manager
bschachter@dramafever.com
<https://www.dramafever.com/>

**Comment by azenMatt** [comment]
Those are for the GitHub API's, @benschac - I assume you want this for the ZenHub API? I have opened an issue for this in our API repo here - https://github.com/ZenHubIO/API/issues/16 

As it is a common request, would you be able to reply in that issue with a rough idea of what limit would be useful for you? We are looking to improve these but need to do some more testing to make sure we don't impact performance elsewhere. 

Getting an idea of what limit is useful for everyone would be very helpful in making sure we benchmark against the right data
