### ISSUE TITLE
Pressing escape key while viewing expanded board leaves broken GH UI

### ISSUE THREAD

**Issue by lsloan** [ZenHubIO/support#659]
I was viewing a ZenHub board in the full page mode activated by clicking the "Expand Board" button.  When I pressed the escape key on my keyboard, the ZenHub board was removed from view and I was left with a page that showed only the GitHub site footer.  That is, only those page elements that are contained within the `<div class="container site-footer-container">...</div>` element were visible, like "© 2016 GitHub, Inc. Terms Privacy Security", etc.  I could not navigate back to the repo short of reloading the page.

I don't remember exactly what I had been doing just before the problem occurred.  I know I can close the display of an issue by pressing escape, so maybe I accidentally pressed it twice.  While I think it might be useful for full page mode to terminate when escape is pressed, it shouldn't render the rest of the UI useless.

**Comment by aspushkinus** [comment]
Same problem here. Browser: Google Chrome.

**Comment by ljm22** [comment]
More specifically...

Hitting escape in normal Zenhub boards view removes the boards view, leaving you back with the github page you started with. That's a good thing.

Same happens in 'expanded' view except the Github page you return to has the top lopped off by the 'full page mode' function. I saw more that the footer, just didn't see the top fex hundred pixels of the viewport. Browser: Google Chrome, 49.0.2623.110 m.

Suggested fix would be for escape to remove the boards *and* the expando viewport shift.

**Comment by lsloan** [comment]
I disagree with @ljm22 that ZenHub boards should close when the escape key is pressed.

Boards (and Burndown) appear to be tabs on repo pages, like the ones for Code, Issues, etc.  When we view one of those other tabs, like Issues, the tab doesn't close when we press escape.  For ZenHub to close those tabs when escape is pressed violates POLA (the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)).

Since Axiom Zen apparently wants ZenHub Boards to act like a modal dialog box, they shouldn't make it appear to be a GH tab.  The link to activate the board shouldn't appear among the GH tab links, but should be a button near the repo title, like their repo switcher button/menu.  The board display should appear as an overlay to the page, like those that appear when we click on an issue in the Board.  However, these are problems with the UI, not really the issue I was reporting, and I should report this as a different issue.  (And I will.)

To be specific about the escape key issue, I should also state that I'm using Google Chrome Version 49.0.2623.110 (64-bit) on OS X 10.11.

**Comment by azenMatt** [comment]
Hi all, 

I can also replicate this issue. We will get it fixed so that the escape takes you to a usable page. 

while this may be a POLA violation, I feel this is the best user experience - @lsloan - happy to discuss further on the separate issue for this.

**Comment by azenMatt** [comment]
This is fixed in the latest version so the 'esc' on an expanded board take you to a non expanded board. From which escape takes you back.

**Comment by sebastiaanluca** [comment]
Pressing escape when an issue is open on the board also breaks things, but it requires a certain flow. Only a refresh can solve the issue since it completely breaks all JS and Ajax requests GitHub is built upon.

1. Go to your repository and navigate to the board
2. Open an issue
3. Command+click the title link to open the issue in a new tab (I have to do this because Chrome plugins like Harvest don't render inside the ZenHub issue modal).
4. Press escape once
5. The issue modal is closed, the board is closed, the URL is that of an issue, I'm on the code tab, but the entire page is empty and all links, JS, Ajax, etc are broken.

Using Chrome on Mac OS X.

**Comment by azenMatt** [comment]
Well spotted @sebastiaanluca 

We will take a look. As a temporary work around - you can command+click the issue cards and they will open in a new tab as well, so it doesn't have to be from the modal.
