### ISSUE TITLE
[bug] Epics everywhere!

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#663]
Umm, something changed today... **every issue** is now showing up as Epic.

**Comment by azenMatt** [comment]
This was a bug with how we were rending issues, looks like the Epic template was being assigned to everything :disappointed: 

We just pushed 2.16.21 which contains the fix for this if you can update your extension?

**Comment by Mottie** [comment]
Apparently I was still using v2.16.17. All fixed now, thanks!

**Comment by azenMatt** [comment]
Great :smile: 

I'm just going to leave this open until tomorrow so that anyone else with the issue can find it

**Comment by LadySerenaKitty** [comment]
I had this issue just a couple minutes ago.  Apparently I already have 2.16.21, so I turned the extension off and on again.  That fixed it.

**Comment by PaulWoitaschek** [comment]
Is it possible to turn the whole epic and other features thing off? 

Zenhub is adding more and more features at so many places so the whole thing does not feel like zen any more ;-)

**Comment by azenMatt** [comment]
@PaulWoitaschek - you can subscribe to #192 where we are tracking the request to disable features. 

We are keeping a close eye on this to avoid bloat!
