### ISSUE TITLE
Disable ZenHub issue attribute menus for unauthorized users

### ISSUE THREAD

**Issue by lsloan** [ZenHubIO/support#666]
While viewing other ZenHub support issues in this repo, I noticed the "Pipeline", "Estimates", and "Epics" attributes all had gear icons.  I found that each of them showed me a menu when I clicked on the headings.   The "Pipeline" one showed me a filter field, but no options to select.  "Epics" let me choose the "Convert to epic" option, which added the message "lsloan converted this to an epic 2 minutes ago" to the issue display, but when I reloaded the page, that message was gone.  Likewise, "Estimates" let me choose a number from the menu and added a message to the display, but that was gone when the page was reloaded.

It appears that I'm probably not authorized to use those menus.  I'm not allowed to change the regular GH issue attributes, like "Label", "Milestone", etc., but those attributes don't show the menus because I'm not authorized.  ZH should check the user authorization before displaying menus for the issue attributes.  Although it doesn't appear to let unauthorized users actually alter the issues, it is very confusing and is a POLA violation.

**Comment by azenMatt** [comment]
Thanks @lsloan - we will get better handling of these cases live

**Comment by kendramoroz** [comment]
Looks like this is an older issue that's since been fixed! When you're a read-only user, you shouldn't see the gear icon anymore. If you (or anyone in the future) notice anything otherwise please ping us once more 🚀
