### ISSUE TITLE
Boards and Burndown should appear as page overlays, not GH tabs.

### ISSUE THREAD

**Issue by lsloan** [ZenHubIO/support#667]
The regular GH tabs available in repos ("Code", "Issues", "Pull requests", etc.) all have these characteristics:

0. They all have their own distinct URLs.
0. They can be bookmarked or linked to directly.
0. In many browsers, holding down a modifier key while clicking on them can make them appear in a new tab or window.
0. When they're being displayed, pressing the escape key or some other keyboard shortcut doesn't make them disappear or reappear.

On the other hand, ZH "Boards" and "Burndown" appear to be like regular GH tabs, but they do not share any of those characteristics.  That's a POLA violation.

The ZH features feel as though they were intended to be like modal displays, like dialog boxes.  The behavior that they disappear when the escape key or their keyboard shortcut reinforces this impression.

Therefore, since they don't act like GH tabs, they shouldn't be displayed with them.  They should be displayed as buttons.  For example, alongside the ZH repo picker menu button.  (See attached image for mockup.)

![zh ui proposed](https://cloud.githubusercontent.com/assets/20786/14356084/67161f1e-fcb1-11e5-8fcb-9aa6bde2d518.png)

Likewise, instead of changing the content of the current page in order to display the ZH board or burndown, display them in a modal overlay, like the kind used to display issues when they're clicked on the board.

**Comment by azenMatt** [comment]
Thank you for the feedback @lsloan - il add this one to the discussion pipeline to get some 👍  from other ZenHub users to see what design they prefer

**Comment by fotoflo** [comment]
disagree. Its important to use all the screen realestate - a modal wastes 30% + of horizontal space.

**Comment by azenMatt** [comment]
We updated ZenHub so the 'open in tab' functionality now works making this feel more like an actual 'proper' page. Along with more distinct URLs that can be bookedmarked - these are now much closer to a real page other than the 'escape' issue

I agree that the most important thing here should be making the best use of screen real-estate. I am going to close this as we are not planning on changing from overlays to modals
