### ISSUE TITLE
Cannot load board (500 internal server error)

### ISSUE THREAD

**Issue by wzin** [ZenHubIO/support#668]
Hi,
when I'm trying to load my board with different repos, it stales like that:

![screen shot on 2016-04-07 at 20-48-55](https://cloud.githubusercontent.com/assets/353944/14362963/2e0bf13e-fd02-11e5-94bb-57d29a3d5626.png)

The console error is:

main.js:4 GET https://api.zenhub.io/v4/repositories/27930869/issues 

500 (Internal Server Error)ue.support.cors.e.crossDomain.send @ main.js:4ue.extend.ajax @ main.js:4o.ajax @ main.js:9u.extend._executeRequest @ main.js:9(anonymous function) @ main.js:9(anonymous function) @ main.js:3h @ main.js:3d.add @ main.js:3(anonymous function) @ main.js:3ue.extend.each @ main.js:2(anonymous function) @ main.js:3ue.extend.Deferred @ main.js:3i.then @ main.js:3u.extend._request @ main.js:9e.extend.getIssues @ main.js:9e.(anonymous function) @ main.js:4o.Model.extend.getIssues @ main.js:6(anonymous function) @ main.js:35(anonymous function) @ main.js:3h @ main.js:3d.fireWith @ main.js:3s.(anonymous function) @ main.js:3h @ main.js:3d.fireWith @ main.js:3s.(anonymous function) @ main.js:3(anonymous function) @ main.js:10i.onack @ main.js:12i.onpacket @ main.js:12(anonymous function) @ main.js:12n.emit @ main.js:12i.ondecoded @ main.js:11(anonymous function) @ main.js:12i.emit @ main.js:11a.add @ main.js:10i.ondata @ main.js:11(anonymous function) @ main.js:12n.emit @ main.js:12i.onPacket @ main.js:11(anonymous function) @ main.js:11n.emit @ main.js:12i.onPacket @ main.js:12i.onData @ main.js:12ws.onmessage @ main.js:12

**Comment by azenMatt** [comment]
Hi @wzin - we are taking a look

**Comment by azenMatt** [comment]
Hi @wzin - can you refresh and try again... we think we have the problem fixed ....

**Comment by azenMatt** [comment]
Ok -we should be back now!

**Comment by wzin** [comment]
Thanks!
