### ISSUE TITLE
Freeze On Loading

### ISSUE THREAD

**Issue by absolutkarlos** [ZenHubIO/support#669]
![screen shot 2016-04-07 at 03 38 58 pm](https://cloud.githubusercontent.com/assets/15717603/14366141/e84ae3e2-fcd6-11e5-871c-f5a0d4db1b7a.png)

freeze on loading your issues...
What to do?

**Comment by azenMatt** [comment]
Hi @absolutkarlos - would you be able to try again? 

This should be working now, we were impacted by a mongolab outtage :(

**Comment by absolutkarlos** [comment]
Thanks for that quick response...
in fact, I hard refresh after I post the issue.
but it regularly freeze... so, I just hard refresh again...
Very impressed with this. Very Good Job guys

**Comment by azenMatt** [comment]
Thanks! :beers:

**Comment by PaulWoitaschek** [comment]
For me its most of the time not usable. Really unstable tool 👎

**Comment by absolutkarlos** [comment]
Too sad to hear that. It`s an amazing tool...

**Comment by PaulWoitaschek** [comment]
My bad. It gets detected as an ad network by the privacy badger extension.
