### ISSUE TITLE
Problem with issue summary display on epics

### ISSUE THREAD

**Issue by oevans** [ZenHubIO/support#671]
Some text elements are overlapping in the Epic issue summary...

![2016-04-08 at 8 17 12 am](https://cloud.githubusercontent.com/assets/3215530/14383350/81821f9a-fd62-11e5-9476-f99b73958773.JPG)

**Comment by azenMatt** [comment]
the latest version v2.16.25 contains better handling of this - so you should no longer get this overlap.

Please let me know if you are still having problems!

**Comment by oevans** [comment]
Thanks -- definitely better now,  but there are still too many things to fit on the same line with longer repo names. The pipeline gets cut off.

![2016-04-13 at 7 07 12 am](https://cloud.githubusercontent.com/assets/3215530/14491414/9acb5e20-0146-11e6-868a-207a7d6f00a5.JPG)

**Comment by azenMatt** [comment]
that's a long repo name :)  - we will move that to be a hover-over when no more space is available
