### ISSUE TITLE
Repo switcher button alignment

### ISSUE THREAD

**Issue by maya** [ZenHubIO/support#672]
Hi, can you fix the alignment of the icons inside the button? The space between the top and bottom are different, it would be great if they were the same.

<img width="316" alt="screen shot 2016-04-08 at 6 35 40 pm" src="https://cloud.githubusercontent.com/assets/5249443/14401034/ceeeb9cc-fdb8-11e5-9845-91450d497916.png">

**Comment by azenMatt** [comment]
agreed 😄  we will take a look at this

**Comment by Mottie** [comment]
To me, adding some padding makes it look a lot better - at least in Chrome:

```css
.zh-repo-switcher .select-menu-button {
  padding: 1px 6px 2px 4px;
}
```

![switch-repo](https://cloud.githubusercontent.com/assets/136959/14576041/831780e2-032b-11e6-982c-f8767a0549d3.png)
