### ISSUE TITLE
Milestones Filter on Board view displays a non existent milestone

### ISSUE THREAD

**Issue by goanpeca** [ZenHubIO/support#673]
I created a milestone and then deleted it, but it still appears in the milestones filter list in the **Boards** view.

**Comment by azenMatt** [comment]
Thanks @goanpeca - we are fixing this at the moment, it should be live shortly

**Comment by goanpeca** [comment]
Awesome, thanks :+1:

**Comment by azenMatt** [comment]
we just pushed v2.16.27 that contains an update to make sure deleted milestones are removed from the cache so you should be good with this now! let me know if it is still sticking around!
