### ISSUE TITLE
The title of the assignee filtering dropdown is wrong

### ISSUE THREAD

**Issue by stof** [ZenHubIO/support#676]
Currently, the dropdown allowing to select the assignee filtering on the board has a title set to ``Filter Issues by label``

**Comment by azenMatt** [comment]
😱  you are right! that's no good - we will get it fixed! 

Thanks for reporting! 🍻

**Comment by azenMatt** [comment]
fixed in v2.16.27 :) 

![image](https://cloud.githubusercontent.com/assets/7584089/14514186/509d7448-01a3-11e6-8b11-12e08a623197.png)
