### ISSUE TITLE
Coloured boards to differentiate repos

### ISSUE THREAD

**Issue by biddster** [ZenHubIO/support#678]
I have several repos all using ZH. I might be just me but I find it hard to distinguish between the boards. I was musing about being able to colour the boards on a per-repo basis to help differentiate. I've no idea how this would work with merged boards.

**Comment by azenMatt** [comment]
Thanks for the feedback @biddster - interested to think more on how this could work! 

Feel free to add in any additional thoughts / user stories that would be useful here.
