### ISSUE TITLE
+1 view from the issues screen

### ISSUE THREAD

**Issue by jjwyse** [ZenHubIO/support#681]
## Description

I noticed that the `+1` view from the issues screen (viewing all issues) was recently removed, due to the GH "reactions" that were recently added.  It seems that GH reactions and the `+1` support you guys used to have are a bit different and the inability to quickly see the top issues based on `+1`s is causing a lot more work for our team to see which features, ideas, etc. have the most votes.

Is there any possibility you guys could re-add in the `+1` support or does GH expose the reaction counts in their API for you to consume?

Any help would be much appreciated.  Thanks!

**Comment by azenMatt** [comment]
Hi @jjwyse - we are currently waiting for GH to open the API for reactions - and then we will look to do something like this. 

While we wait for this, you can filter by reactions on the issue page (although you have to click through to see the raw numbers) like this:

![image](https://cloud.githubusercontent.com/assets/7584089/14577679/cf791ad6-032b-11e6-9d91-3b5eab4ee2af.png)

does that help for your use case at all?

**Comment by jjwyse** [comment]
@azenMatt - Great, thanks for the response.  That is a step in the right direction for our use case.  As you mentioned, it would be nice if we didn't have to click through to see the raw numbers but at least we can see an ordered list.  Thanks again, much appreciated!  Would love to see support once GH has the reactions available in their API.

Thanks again!

**Comment by SamHasler** [comment]
Githubs reaction sort doesn't allow me to see which issues **I** have reacted to. If you could add that back it would make up for the removal of the +1 feature.

**Comment by azenMatt** [comment]
i'm going to close this one as most teams have now fully migrated over to the reactions feature. We don't have any plans to work with the old +1 data other than keeping it in the UI so it isn't lost
