### ISSUE TITLE
Milestone names are truncated too aggressively in the milestone filter box

### ISSUE THREAD

**Issue by cbeams** [ZenHubIO/support#684]
See the screenshot below. The name of the milestone being filtered is "Iteration 3". Notice how in the actual milestone drop-down, only `Iterati...` is displayed. This makes it difficult to maintain context about which milestone (or milestones) are being shown on the board at any given time.

Suggested fix is to allow for at least some additional horizontal expansion of the milestone drop-down, such that reasonably short names (like "Iteration 3") don't get truncated.

There are a number of other open issues here on the support board regarding displaying milestone metadata on each card. That would be helpful here, too.

![image](https://cloud.githubusercontent.com/assets/301810/14556594/3cda6b44-02f9-11e6-9fb9-83b7a0b3a368.png)

**Comment by azenMatt** [comment]
Thanks for the feedback @cbeams 

I agree we need to make these queries easier to understand. Especially with the addition of And/Or/Not filtering which is a very popular request. 

what are you thoughts on using the space above these filters to explicitly explain the current query? 

![image](https://cloud.githubusercontent.com/assets/7584089/14834938/f7ef2e40-0bbb-11e6-959c-c7d12e940a6d.png)

**Comment by cbeams** [comment]
This would be fine, I suppose, if only perhaps as an interim improvement.

Perhaps the ultimate direction for this is to make that query interactive—just like GitHub's own native Issues UI does:

![image](https://cloud.githubusercontent.com/assets/301810/14845760/af11db6e-0c60-11e6-8420-efaf29342c06.png)

Perhaps this is actually what you have in mind; based on your comment, however, it appears you're suggesting the query would be read-only. Thanks.

**Comment by azenMatt** [comment]
@cbeams - hopefully the new filter boxes have helped solve this issue for you by making it easy to see what you are currently filtering by!

**Comment by cbeams** [comment]
They do, thanks!
