### ISSUE TITLE
Fix 'Create an epic' button when creating a new issue.

### ISSUE THREAD

**Issue by DragosIorgulescu** [ZenHubIO/support#686]
The most frustrating thing just happened: I was adding a new issue, with a rather long and complex description. When I hit the `Create an epic` button to create it and transform it into an epic, the issue was created with NO DESCRIPTION.

This sort of bug is unacceptable.

**Comment by azenMatt** [comment]
Hi @DragosIorgulescu - sorry to hear you had this issue. 

Would you be able to email me on our support address - support@zenhub.io with any further details you have (for example, does this happen every time? Replication steps would be very helpful) And we will look into this further. 

Thanks
