### ISSUE TITLE
All new issues disregard pipeline

### ISSUE THREAD

**Issue by tj** [ZenHubIO/support#687]
This used to happen occasionally, but now seems to be consistent. All new issues seem to disregard the pipeline all-together, so you have to go find it and drag it over.

**Comment by tj** [comment]
Actually no it seems to be all ZenHub state, the estimates don't get set the first time on creation either.

**Comment by azenMatt** [comment]
Hi @tj - we just fixed this on v2.16.32 - hopefully for good this time! 

We have been having intermittent issues with this, and today it went full crazy and every issue created from the board didn't get a pipeline assigned. 

Earlier this week we fixed another version of this bug where by if you created an issue where you referenced an issue open in another tab - the pipeline/estimate wouldn't save. 

Hopefully we have all the edge cases around this now. But please shout if you see it again!

**Comment by tj** [comment]
Just a heads up that it's happening again (seemed fine before today) in case that stuff doesn't show in logs etc

**Comment by azenMatt** [comment]
Hi @tj - do you have any replication steps for this? I just tried and it was working fine .... 

- Does it happen for all new issues? 
- Created from the board or issue page? 
- Any other meta-data included, labels milestones etc that need to be present?

**Comment by tj** [comment]
Hmm im not sure, I haven't noticed a pattern, just tried two and it worked fine. They're always created  from the board haha, not much help

**Comment by azenMatt** [comment]
OK - il keep an eye on this, if you see it again, let me know! 

> They're always created from the board

😀 👍
