### ISSUE TITLE
Switching from Epics label filter to individual Epic Filter

### ISSUE THREAD

**Issue by talsafran** [ZenHubIO/support#690]
I'm not sure if this is a feature or a bug, but sometimes I want to look at all of my Epics and then drill down on one.

Here all all of my epics (filtered by the Epic label):

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/4y1w7r3h.png)

But then when I click an Epic, I see nothing!

![](https://dl.dropboxusercontent.com/spa/gcrmzi51hzw4tnm/5eh4u5rd.png)

This is because I'm now filtering by both the Epic label as well as the issues particular to the Cook Payout 2 epic I've selected.

Again not sure if this is the intended behavior but wanted to report! My .02 is to have it remove the Epic label filter :)

**Comment by azenMatt** [comment]
Thanks @talsafran - this is a really good point!  we just shipped a change to that if you hit 'filter by this epic' it will automatically remove the 'epic' label filter if it is applied. 

This is live in v2.16.32 😀

**Comment by talsafran** [comment]
👏🏻
