### ISSUE TITLE
Remove truncation on kanban card titles.

### ISSUE THREAD

**Issue by brandonreid** [ZenHubIO/support#691]
Our team prefers when the cards show the whole title. The truncated title forces us to open the issue to read what the issue is, which slows us down especially because the modal takes a second to open. IMO, defeats the purpose of a kanban visualization when stuff is hidden (wouldn't truncate on a post-it note).

**Potential Solutions**
1. Remove the truncation, show the whole title on the card.
2. Display the whole title on hover.

**Comment by azenMatt** [comment]
Thanks for the feedback @brandonreid - this does seem to be a very popular request. 

Do you have a preference on two solutions you offered?

**Comment by brandonreid** [comment]
@azenMatt  1, for sure.. 2 would slow me down too. People just won't make obnoxiously long titles.

**Comment by azenMatt** [comment]
Truncation for issue titles, including in expanded pipelines, is now gone :)
