### ISSUE TITLE
Unable to load Pipeline.

### ISSUE THREAD

**Issue by licatajustin** [ZenHubIO/support#692]
_Perhaps related to https://github.com/ZenHubIO/support/issues/166._

#### Description

As a user _with_ `push` access to a repository,
I am not able to load and change the Pipeline of an Issue.

#### Error

*Message*: `"No 'push' access for this Repo"`
*URL*: `https://api.zenhub.io/v2/ProctorU/repo-name/issues/40/pipelines`
*ZenHub version*: 2.16.33

#### Screenshots

![unnamed-2](https://cloud.githubusercontent.com/assets/3933204/14714594/35099b9a-07ab-11e6-8ffd-90e441a01529.png)

![unnamed](https://cloud.githubusercontent.com/assets/3933204/14714597/382078ee-07ab-11e6-9dac-4505b8bb117a.png)

**Comment by azenMatt** [comment]
Hi @licatajustin - we are taking a look into this. 

Would you be able to let me know if you have always had push access here? Or has it just been granted?

**Comment by licatajustin** [comment]
Great question. Push access was granted this morning for this particular user.

**Comment by azenMatt** [comment]
ah, that will be it then - it does take some time for the permissions cache to update. 

We will look at pushing out an improvement for this so that we can pick up permission changes faster. In the meantime, the cache for this should have expired by now, so it should work for this user now?

**Comment by licatajustin** [comment]
That was it. Appreciate your help @azenMatt. 🙇

**Comment by mjcarden** [comment]
@azenMatt Thank you so much! It's working!

**Comment by azenMatt** [comment]
🍻  😀
