### ISSUE TITLE
Filter epics in boards with dropdown

### ISSUE THREAD

**Issue by Frozenfire92** [ZenHubIO/support#693]
Currently the only way to filter by epic is by finding the issue card and clicking filter by this epic. I would like the Epics to be a dropdown just like milestone/assignee

**Comment by azenMatt** [comment]
Thank you for the feedback @Frozenfire92 

To help find it quicker, you can filter by the epic label. But I appreciate a pure epic filter would be even faster.

**Comment by noahmanger** [comment]
I'd love this as well. It would enable the ability to not have epics on the board, but still be able to filter by them.

**Comment by azenMatt** [comment]
cc @brianleung11-3 - who has been getting lots of emails on this topic 😀 

No firm ETA yet, but we will bring this into it's own drop down in the near future

**Comment by azenMatt** [comment]
This one is now live 🎉 

![image](https://cloud.githubusercontent.com/assets/7584089/19776693/00c5acf2-9c2a-11e6-918d-e9bd987d782f.png)

😁
