### ISSUE TITLE
Add ability to filter the board by author

### ISSUE THREAD

**Issue by stof** [ZenHubIO/support#697]
This is especially useful on open-source projects. When opening issues on such project, being able to filter only my own issues allows to follow their progress easily. Github has such filter for their issue tracker, but ZenHub does not.

**Comment by azenMatt** [comment]
Thanks @stof - #508 is currently covering this usecase, so in the interests of collating information I will close this issue and post any updates there. You can subscripe to 508 and I will let you know once this is live :)
