### ISSUE TITLE
Ability to filter board by "no estimate" or "no story points"

### ISSUE THREAD

**Issue by aaronwest** [ZenHubIO/support#698]
I looked around in the open and closed issues to see if this already existed and perhaps I was just missing it. I see no way to filter a ZenHub board by issues which do **not** have an estimate.

I spend a fair amount of time using ZenHub to evaluate new issues and keep them moving forward each week. Part of this exercise includes finding issues which haven't been estimated. I either estimate these myself immediately (once or twice a week) or queue them up for other team members to estimate.

It'd be great if there was a quick way to find these issues.

**Comment by fotoflo** [comment]
:+1:

**Comment by aaronwest** [comment]
@fotoflo please press the 👍  emoji in the bottom left of the original issue description/body. That makes it easier for the ZenHub team to tally the responses vs individual replies. Thanks!

**Comment by fotoflo** [comment]
Thanks aaron... done.

**Comment by paltman** [comment]
Any status on this?

**Comment by kendramoroz** [comment]
@paltman Thanks for following up on the status here! I'll be sure to bring this up with our product team again. There's no immediate enhancement in the pipeline related to additional filtering options for estimates, but definitely understand the pain point and something we're consider going forward once #1076 / #156 is launched! 

One way to sort issues today is by using the pipeline filtering to sort by estimation. Issues with no story points get placed at the bottom of the pipeline.

Let me know if this filtering helps at all with what you are hoping to achieve! 

![image](https://cloud.githubusercontent.com/assets/11036230/25967770/0f4e2e5c-3644-11e7-8778-23df3db3ab91.png)

**Comment by aaronwest** [comment]
@kendramoroz that's a fairly useful workaround while we wait on the larger board filter for `no estimates`. It's a little cumbersome in that you have to perform a manual action to filter each pipeline vs the entire board but it's better than nothing. Thanks for posting this.

**Comment by benjamincharity** [comment]
@kendramoroz I've noticed that the `icebox` column doesn't have sorting ability.. was that a conscious design decision?

**Comment by benjamincharity** [comment]
Ok, so possibly it's not about the icebox, but about the column expansion...

![sort](https://user-images.githubusercontent.com/270193/38427944-9edae07c-3988-11e8-883a-11d54470790a.gif)

Still unsure why this would be implemented. There is still a clear sort order when the column is expanded.

**Comment by kendramoroz** [comment]
👋 quick update! We're excited to let everyone subscribed here know that we've moved estimate filtering into our current Sprint. We'll have more to share on when it'll be launched into production soon, but here's a sneak peak:

![image](https://user-images.githubusercontent.com/11036230/42651315-e7c0b8ca-85c3-11e8-9eb4-787d372575b1.png)

_(PS. There's also going to be `author` filtering 💯 #508 and updates to #865_ 😉 _)_

**Comment by kendramoroz** [comment]
🎉Happy to announce that this is live now! Let us know if you have any questions, or check out our latest blog post on the new filters: https://www.zenhub.com/blog/two-new-ways-to-filter-your-boards/

![image](https://user-images.githubusercontent.com/11036230/44746427-31749700-aabf-11e8-80b9-98cb066b73cb.png)
