### ISSUE TITLE
Listing multiple issues in one call

### ISSUE THREAD

**Issue by garyharan** [ZenHubIO/support#699]
Right now I'm making the following call multiple times:

```
GET https://api.zenhub.io/p1/repositories/:repo_id/issues/:issue_number
```

It would be beneficial if we could do something akin to this:

```GET https://api.zenhub.io/p1/repositories/:repo_id/issues/:issue_number,:another_issue_number,:etc...```

**Comment by azenMatt** [comment]
Hi @garyharan we have a request similar to this in our API repo here https://github.com/ZenHubIO/API/issues/9

I will keep that updated with progress 👍

**Comment by HarveyEV** [comment]
Why was this closed? Can I retrieve multiple issues with one call? I know this is old but is there any resolution I haven'r seen in the docs?
