### ISSUE TITLE
Do you have a API that can get all the issues in a particular pipelines ?

### ISSUE THREAD

**Issue by smartmouse** [ZenHubIO/support#704]
Is there a way to get issues in a particular pipeline? and may be filtered by  certain "labels" ?

**Comment by azenMatt** [comment]
Hi @smartmouse - our API is detailed here - https://github.com/zenhubio/api

You;l need to do some trickery to get that exact filter, but we do offer an API that lets you extract data that can be used for this

If you have any questions, please open an issue in the API repo and il get an answer for you :)
