### ISSUE TITLE
New issue's pipeline is reset to Icebox on create

### ISSUE THREAD

**Issue by dukedave** [ZenHubIO/support#707]
1. When creating a new issue I sometimes also set the pipeline:

  ![selection_251](https://cloud.githubusercontent.com/assets/48232/14930397/80d8f750-0e18-11e6-8212-51f5a4357b2e.png)

1. However the pipeline is immediately changed back to **Icebox** when created:

  ![selection_249](https://cloud.githubusercontent.com/assets/48232/14930413/9d809de0-0e18-11e6-8de8-c3640c033124.png)

***

I believe this is a regression, has anyone else seen it?

**Comment by azenMatt** [comment]
Hi @dukedave 

We have seen this problem before - but thought we had all edge cases that were causing it - there must be one more out there! 

Would you be able to describe any other common patterns you have seen when creating these issues that cause them to go into the first pipeline?

And if this happens everything for you, or just occasionally? 


For example, the last bug we fixed related to this was caused when you opened a new issue and created a # reference to another issue that was already open in a separate tab. If you did that, the pipeline did not save. 

cc @pnavarrc

**Comment by dukedave** [comment]
>  opened a new issue and created a # reference to another issue that was already open in a separate tab

Wow, that is a mighty specific repro, and it exactly matches my circumstances! 

This is the first time I've noticed it, but it's not unlikely it's the first time I've met those conditions too.

**Comment by azenMatt** [comment]
Do you have any other details of what the issue looks like (milestones, labels etc)? 

I just tried to reproduce for that case and was unable to.

**Comment by azenMatt** [comment]
Any further instances of this? I think we have all the edgecases now.... (but the trouble with edgecases is you can never be sure!)

**Comment by dukedave** [comment]
I haven't seen it in a while, so feel free to close.
Thanks! :tada:
