### ISSUE TITLE
Is there a way to avoid Pull Requests from showing up as new issues?

### ISSUE THREAD

**Issue by eddiethefoot** [ZenHubIO/support#716]
Functionally it's no big deal, but if there's an existing issue on the board, it seems like creating a PR creates a new issue (even if we do specify it to close the original issue). It's just a little annoying since it creates more visual noise.

**Comment by stof** [comment]
There is a button on the board to toggle the display of PRs

**Comment by eddiethefoot** [comment]
Thank you! I totally missed that. I will close this.
