### ISSUE TITLE
Features: Issue export and moving issues between repos

### ISSUE THREAD

**Issue by roham** [ZenHubIO/support#72]
Is there demand for either an Issue export feature or a full-fledged Issue migrator as a feature in ZenHub?

The implementation we are thinking for the Issue migrator is a sort of  'teleport' button and drop-down repo selector to issues which would basically close the active issue and reopen an identical one in the new repo selected. 

We could then either embed the comments in the new issue body,  create comments from the migrator's account with the original author embedded in the body of each comment, or -- for ZenHub users -- auto-post the comments on their behalf via the GitHub API.

Thoughts?

cc @dete

**Comment by TobyAbel** [comment]
Export is good, but there doesn't seem to be a means by which to import them again? Would make this feature much more useful. Not opening an issue in case I've missed something.

**Comment by abrkn** [comment]
:+1:

**Comment by zachumo** [comment]
This function would be highly useful. Right now siting with a bothersome scenario where we have to move issues from one repo to another. Simply dropping the json export file to the first comment on a new issue would be sweet as apple pie. Would also like the exported file to have more intuitive name than "download".

**Comment by Naatan** [comment]
> will punt Issue "teleport" for now

So, is this tracked somewhere?

**Comment by azenMatt** [comment]
Lets reopen this one to track. 

Right now, issue export is very rarely used - making it hard to justify building the 'import' side of this. 

But I do often find myself needing it! 

Will keep tracking interest in this request vs others in this repo - so please +1 the OP

**Comment by rgwozdz** [comment]
+1

**Comment by lhavel** [comment]
+1

**Comment by Maxhodges** [comment]
>Right now, issue export is very rarely used - making it hard to justify building the 'import' side of this.

Are you kidding? What's the point is "exporting" if there is no import? It's useless without import so it's rarely used. doh!

**Comment by kevinSuttle** [comment]
+1

**Comment by juanlu91** [comment]
+1

**Comment by juanlu91** [comment]
+1

**Comment by azenMatt** [comment]
A question on this, 

What would you want to do with the issue being moved in it's original location? 

Automatically close it? or leave it open?

**Comment by kevinSuttle** [comment]
I would say close upon successful move. 

https://github.com/kevinSuttle/github/issues/37

**Comment by azenMatt** [comment]
Agreed, that is what I was thinking as well. 

Throwing together some quick wireframes here - this could work like:

 'Move issue' button above the 'Export Issue' button

![image](https://cloud.githubusercontent.com/assets/7584089/12366310/2c08f346-bb8f-11e5-81f6-962a37d3d02e.png)

When clicked, this will give you a list of repos in that org that you have push access to - similar to the repo merge tool: 


![image](https://cloud.githubusercontent.com/assets/7584089/12366892/f6a75d1a-bb92-11e5-8482-1d2df8795497.png)


When selected, display a confirmation:

`This issue will be closed and moved to [repo name]. Are you sure?`

`Cancel` `Move issue`

When move issue is selected, two things should happen: 

1) A new issue is opened - by the user who selected 'move issue' in the selected repo. This issue:
   - Has the same title 
   - An opening comment linking towards the original issue
   - A single comment containing the following for each comment in the original thread
          - Posted by: [user name] On [time]
          - Content: [content]
   - for V1, none of the meta data on labels, estimates, milestone etc will be moved over (we can look into that later based on use and feedback)

2) The existing issue is closed with the comment: 

`Issue moved to [GH link] 

The page redirects to the new issue. 


----------------

Obviously a lot we can do to improve that for future releases, but I think that should at least solve the main pain point here - and be pretty fast for us to implement. Anything I am missing that is a 'must have' for this to be useable?

**Comment by kevinSuttle** [comment]
That looks awesome.

**Comment by kevinSuttle** [comment]
I also think that there is value in exporting everything from one repo (say on GitHub.com) and into another (e.g. GitHub Enterprise). 

However, there is a lot more to it than you'd think. 
https://help.github.com/enterprise/2.4/admin/guides/migrations/exporting-the-github-enterprise-source-repositories/

**Comment by azenMatt** [comment]
I think that might be better as an API feature :wink:

**Comment by kevinSuttle** [comment]
It _sort_ of is already, but it's a huge hassle.

**Comment by jeoffw** [comment]
Bulk move from the Issues list would be grand.

**Comment by katlongo** [comment]
would be grand indeed +1

**Comment by azenMatt** [comment]
This just went live in v2.15.47 

This will give you access to a 'move' button on each issue here - 

![image](https://cloud.githubusercontent.com/assets/7584089/13127857/a90dc91e-d586-11e5-8b87-f29c4220f0aa.png)


it is just a v1 of this functionality which allows moving within orgs only, so please let me know any feedback on how well it works! 

Also - we will likely follow this up by removing the export button - so please also let me know if you still use the export functionality and why if you'd rather we kept it! :smile:

**Comment by kevinSuttle** [comment]
NICE!

**Comment by Cervator** [comment]
Very cool feature, thank you :-)

Maybe "Export" would be handy if you could aim it at something like an internal JIRA instance (workplaces not entirely 100% on GitHub yet) but that is probably too much work.

**Comment by ljm22** [comment]
Wishlist for v2:

 - Bulk moving a whole set of issues.
 - Maintaining references between issues.
 - Allow moving from a user to an organization, from an organization to another organization, from an organization to a user

**Comment by hellobrian** [comment]
Is there a timeline for bringing this feature to Zenhub Enterprise?

**Comment by azenMatt** [comment]
Hi @hellobrian - this will be in our next Enterprise release, scheduled for mid-April

**Comment by chrbradley** [comment]
Love this feature.

Any reason why the default behavior is to close the issue though? Could we get a select lane option instead? Or at least a toggle to close on migrate check box?

I haven't wanted to close any of the issues I migrated yet.

**Comment by azenMatt** [comment]
> Or at least a toggle to close on migrate check box?

Yes - we are going to add this in 👍

**Comment by kevinSuttle** [comment]
Did 'bulk move' make it into the April release?

**Comment by azenMatt** [comment]
> Did 'bulk move' make it into the April release?

Hi @kevinSuttle - we haven't had a chance to work on this yet. To be fully transparent - the whole team have been heads down on a front end refactor to vastly improve performance. We are going to be able to get back to shipping updates once this is live - targeted for the end of June. 

> Any reason why the default behavior is to close the issue though? Could we get a select lane option instead? Or at least a toggle to close on migrate check box?

We did manage to sneak this one in recently - so you can now decide if you would like the issue to remain open. 


![image](https://cloud.githubusercontent.com/assets/7584089/16167753/f1901cf6-34ad-11e6-94d3-1417f698a823.png)

This part will be in our next enterprise release which we will start packing up once the refactor is live.

**Comment by orbanbalage** [comment]
@ljm22 - did your v2 whishlist get incorporated in a different Issue? I'm looking to move Issues between organisations, but not sure at this point if Zenhub is considering implementing it or not. Thanks

**Comment by azenMatt** [comment]
> did your v2 whishlist get incorporated in a different Issue? I'm looking to move Issues between organisations, but not sure at this point if Zenhub is considering implementing it or not. Thanks

it hasn't yet - this is something we still want to improve - but right now we have a number of higher priority issues that we want to tackle first.

**Comment by gsantopaolo** [comment]
Is there a way to move more than one issue at a time?

**Comment by azenMatt** [comment]
Hi @gsantopaolo - it is currently single issue

**Comment by samclachlan** [comment]
Would love ability to do a mass export of all issues in a Repo to CSV or other file format.  Had a recent ask to do so and can not find a way to do an export of all issues.

**Comment by azenMatt** [comment]
Hi @samclachlan - we have an issue for this here - #679

No time frame on this right now, but it is something that we want to offer as part of our reporting suite

**Comment by isugif** [comment]
Was hoping there was a way to git clone or branch the repo that contains all the Issue/Epic information still displayed in zenhub.  I suspect a mass export is what I am looking for.  Is this correct?

**Comment by isugif** [comment]
In this way I could create a template of Epics with issues and milestones etc and then clone that repo with all the info and then start filling in the information.

For example, the steps in writing a paper are pretty much identical
Epic - write materials and methods
issue
issue
issue
Epic - write results
Epic - write introduction
etc 
etc

**Comment by ajdlinux** [comment]
Another vote for being able to move issues between organisations (or in my case, from a user's private fork back to the organisation that the repo was forked from).

**Comment by trevars** [comment]
I was just really thankful for this feature. I would love to see the feature include option to copy assignees (and other GitHub/ZenHub attributes like estimate, label, etc). Maybe a check list of what to include in when copying?

**Comment by Petermarcu** [comment]
Looks like this works within an organization. Is there a way to move issues from one organization to another?

**Comment by richnsoos** [comment]
This looks promising for our use case. We have GHE ... I will do more digging, but can anyone here share if you know whether moving issues from one repo to another w/i an org works in GH Enterprise?

**Comment by kendramoroz** [comment]
Hey @richnsoos it should definitely work! You should see the `Move Issue` button on the sidebar in the extension on the Board Modal/GitHub Issue page 🎉  - let us know if you don't see it!

**Comment by Petermarcu** [comment]
Hi @kendramoroz can you confirm whether there is any way to move issues across organizations? I work on a very large product that aggregates from many open source organizations on Github and we're currently left copying and pasting issues around. Many times the issue will come into a central repo but the fix needs to go into a different organizations code.

**Comment by kendramoroz** [comment]
> can you confirm whether there is any way to move issues across organizations

Not currently across organizations - the repositories have to be within the same organization to be transferred.

**Comment by richnsoos** [comment]
hi @kendramoroz , we do not see it. which version of GHE has the Move Issues button? Thank you!

cc: @rdifrango

**Comment by kendramoroz** [comment]
@richnsoos Hey Susan! It was implemented quite sometime ago - can you send us a note through support@zenhub.com using your work email to confirm the team you're on using ZenHub Enterprise and we can check to ensure you're on the latest version for your team?

**Comment by richnsoos** [comment]
My mistake, I thought this was an add on Service for GitHub Enterprise but it sounds like ZenHub is entirely separate. Thanks for quick response.

**Comment by Yeshasvitvs** [comment]
> > can you confirm whether there is any way to move issues across organizations
> 
> Not currently across organizations - the repositories have to be within the same organization to be transferred.

@kendramoroz Any update on the feature to move issues between repos of different organizations ?
