### ISSUE TITLE
As a ZenHub user I want the ability to mark the estimate field for an issue with a '?' character (or other reasonable indicator) when the estimate of an issue is unknown or not yet sized.

### ISSUE THREAD

**Issue by fddugard** [ZenHubIO/support#724]
Title is self-explanatory the estimate field does not allow anything other than positive integers to be entered into it. '0' does not work since '0' could represent an issue that requires very minimal effort. '?' would be most appropriate but I imagine this has impact into how burn down charts are calculated.
Thanks!

**Comment by junketjim** [comment]
Just out of interest - what's the difference between an unestimated (but marked with "?") and a no estimate applied? Is it because you wish to differentiate between unestimated and unknown estimate?
