### ISSUE TITLE
Use your Wiki to provide better documentation on features.

### ISSUE THREAD

**Issue by eddiethefoot** [ZenHubIO/support#725]
Just a request for you guys to use your GitHub wiki to provide a centralized place for documentation. I love the product so far, but I don't want to spend this much time searching for answers and discovering what's possible or not.

Your main site also doesn't have enough documentation to get started, and I imagine that if you're a company looking to vet the right project management tool, you want some more detailed questions answered in order to allow for an informed decision. Making changes from one project management tool to another are costly, and trial and error is not a privilege that is afforded to most companies.

**Comment by azenMatt** [comment]
Thanks for the feedback @eddiethefoot  - I really appreciate it as I agree this is a big pain point. 

We are working to address this at the moment by improving the documentation available on our website - and we will also look into using this wiki. 

If you have examples of specific questions that you had to search for answers to, that would be really helpful in making sure we get the detail level right here. 

cc @paigepaquette
