### ISSUE TITLE
Would love the ability manipulate estimates and epics programatically

### ISSUE THREAD

**Issue by rajsesh-msft** [ZenHubIO/support#726]
CRUD operations on epics would be very useful.  My wishlist in priority order:

1. Update Estimates on issues.
2. Update Epic affinity of issues.  That is, add to an epic or remove from an epic.
3. Create new epics.

**Comment by azenMatt** [comment]
Hi @rajsesh-msft - bringing the epics into the API is something we are very keen to do  - we have an issue on our API repo here - https://github.com/ZenHubIO/API/issues/19 to track this 👍
