### ISSUE TITLE
Export sprint backlog

### ISSUE THREAD

**Issue by RonRademaker** [ZenHubIO/support#727]
Hi,

We've been using zenhub for a few weeks now and really like to way we can integrate our work process in Github. However, I'd like to give our clients access to our sprint backlog, but not to our github repo's. So, is it possible to export the backlog of a sprint (milestone) using zenhub? 

Thanks,
Ron

**Comment by azenMatt** [comment]
Hi @RonRademaker 

Currently we don't have an export function - however this is something we are looking at as part of expanding our reporting suite. 

This will allow you to export your GitHub and ZenHub data into a csv to send onto clients. 

In terms of timeframes on this, Q3 is looking likely 

We have an issue tracking this here - https://github.com/ZenHubIO/support/issues/679 - which I will keep updated
