### ISSUE TITLE
Display pull request on the issue card

### ISSUE THREAD

**Issue by ibips** [ZenHubIO/support#731]
It would be helpful to show if an issue has a pull request associated with it when a PR mentions the issue with `Closes #` or `Fixes #`, with a link to the actual pull request. This can be powerful with `Hide Pull Requests` feature on the board.

<img width="264" alt="pr-in-issue-card" src="https://cloud.githubusercontent.com/assets/896854/15188854/791e10b4-176d-11e6-8052-de0bbffefa22.png">

**Comment by azenMatt** [comment]
Hi @ibips - the good news is this functionality is currently in code-review :) 

You can find more details on the design here - https://github.com/ZenHubIO/support/issues/466#issuecomment-194584927 

It is quite a complex change so I would expect code review and testing to take at least another week - but we are aiming to get it live ASAP. 

i'l update #466 once this is live!
