### ISSUE TITLE
Ability to Ctrl-click/Command-click several issues on board, to drag all

### ISSUE THREAD

**Issue by edmapd** [ZenHubIO/support#734]
Right now on the board, if you click anywhere on the issue card, it pops open a modal to show you the issue.  It would be desirable to be able to select several issues at once using Command click/control 
click, to drag them from one pipeline to another.

I'd suggest you have clicking on the card _title_ launch the modal to show you the issue, but reserve the rest of the space on the card for a "select click" using Command/Control.  This would allow you to be able to select several cards at once, for some other action such as drag (or close, apply label, whatever).

**Comment by azenMatt** [comment]
Hi @edmapd - you can currently use the 'cog' icon on the top right hand corner of the card (on hover) to go into 'multi-select' mode 

Using cmd+click to do this in addition to selecting from the menu would be awesome as well :)

**Comment by edmapd** [comment]
Hi Matt,
It looks like you guys have lost  this feature?  I now see only Close Issue
and Move to Top/Bottom.

-Ed

Ed O'Donnell
917-608-7770


    MapD named Gartner Cool Vendor in DBMS!  Read the report
<http://www.mapd.com/?gartner>.

**Comment by azenMatt** [comment]
Hi @edmapd - yes, we have had to briefly remove it to refactor a bunch of the board code to improve performance - it should be back with you shortly (probably late sept / October)

**Comment by azenMatt** [comment]
You can now click on the assignee part of a card and enter a multi-action menu to move them all at once 

https://www.zenhub.com/blog/task-board-bulk-actions/

I hope this helps!

**Comment by edmapd** [comment]
Thank you!
