### ISSUE TITLE
Ability to link to issues within an Epic from other repos without merging the boards.

### ISSUE THREAD

**Issue by eddiethefoot** [ZenHubIO/support#735]
Not sure if this has been requested, but whether linking issues or adding issues to an epic, it'd be really helpful to be able to search and link issues from any repo from the organization without having merge boards. 

We have applications across several different devices and platforms, and often we'll have platform-wide changes that need to make and we'd love some visibility across all of the projects without having to merge all of the boards (8+). 

I guess an option available to us to address this use case is to create an empty repo that's called something like _Core_ and merge all of the repos into that single view, and do all of the issue management from a single board. But that would mean intelligently using repo filters as we work, and that leaves a lot of room for human error (e.g. people creating issues in the wrong board/repo, getting a cluttered view of the projects, etc.)

**Comment by azenMatt** [comment]
Thanks for the feedback @eddiethefoot - I agree this is the ideal situation. I have added this request to our feedback for v2 of epics 👍

**Comment by kendramoroz** [comment]
With the development of #139, this should soon become possible! Going to close this one, but please subscribe to our workspaces issue for updates closer to launch 🚀
