### ISSUE TITLE
Feature Request: How can show "Created date" on the issue card on zenhub board ?

### ISSUE THREAD

**Issue by ambynair** [ZenHubIO/support#737]
I have multi-repo setup on zenhub, I would like to show created-date on issue card and be able to sort it by created-date, most recent shows up first.

**Comment by azenMatt** [comment]
Thanks @ambynair 

We will look into this, the issue cards already have a lot of data shown, so adding in created date could be quite confusing here. 

Adding in the ability to sort by this metadata makes a lot of sense, and helping to provide this is something we are looking to do soon. 

Would you be able to let me know more about the use case of where it would be useful to see the created date on the card its self?

**Comment by ambynair** [comment]
@azenMatt I don't agree if there already lot of data shown on the card.  Right now , I see Assignee, Issue #, Issue Description and labels ( which user defined). And also, "lot of data" is relative, what you need to provide is the ability to select or de-select the information that user wants to see on their card. Let use decide if it lot or less. 

Created date is fundamentally very important in kanban world, in our standup, we want to be able to look at the issue card and based on the created date ( how long it has been since created) as well as Date issue was moved to current status, we can prioritize and extend our discussions.
Both these information you are already showing inside an issue but one has to click on it. 

> xxxx opened this issue 4 days ago  
&
> changed the pipeline from Ready to Work In Progress 7 hours ago

One thing we are trying to do is to look at the issues that are aging in WIP and Wait queue longer than we think it should  and want team to discuss and seek action to maintain the flow instead of moving on to take up new issues. 

This two information if we can have it on our issue card, it will be huge for us.  Sorting will help us keep old issue in top , that is issues have been in that queue longer than newer issues.  We cannot sort by numbers since our zenhub has multiple repos connected to it.

Hope this helps.

**Comment by azenMatt** [comment]
Hi @ambynair - as a quick updated here, we will be getting the ability to sort by created data into the application in the near future. 

Custom fields on cards is not prioritized yet, but il keep you updated once it is

**Comment by azenMatt** [comment]
> and be able to sort it by created-date, most recent shows up first.

Hi @ambynair - we just released v2.24.36 that contains created date as a sorting option which moves us closer to completing this ticket :) 

![image](https://cloud.githubusercontent.com/assets/7584089/20734150/5e0c0d5c-b64c-11e6-910e-418b131b23d3.png)

**Comment by kendramoroz** [comment]
Closing to consolidate with #700 - please subscribe there!

**Comment by KyleAMathews** [comment]
Something similar to Trello's "aging" feature would be spectacular https://help.trello.com/article/820-card-aging
