### ISSUE TITLE
Should child epics contribute to strory points of parent epics

### ISSUE THREAD

**Issue by goanpeca** [ZenHubIO/support#739]
I am starting to group smaller stories (using an epic and a different label) within a epic (using epics and the normal label).

I was kinda expecting that the story points of an epic were calculated based on all the child issues it contained so if I had something like this

![image](https://cloud.githubusercontent.com/assets/3627835/15335247/284cd5f2-1c37-11e6-9313-ab7b842a63c9.png)

I would expect to see right in that view that
- Epic is 7 story points      (Epic contains Story 1 and Story 2)
- Story 1 is 5 story points  (Story 1 contains Issue 1 and 2)
- Story 2 is 2 story points  (Story 2 contains Issue 3)

I would also expect too see the same in the issue view
![image](https://cloud.githubusercontent.com/assets/3627835/15335345/869ec8d6-1c37-11e6-9fc3-b570517a1d8b.png)

---

**Comment by Anvil102** [comment]
+1 - similar to #804. See my comment there.
