### ISSUE TITLE
Milestone not displaying any tickets in Boards view - Not until we update labels

### ISSUE THREAD

**Issue by aj-thilakan** [ZenHubIO/support#740]
- Board View
- Filter by specific milestone
- Not showing all the tickets in the milestone
  - The hidden tickets will appear once i update their labels (I can find them in github's issue view with a milestone filter)
  - This milestone is currently still not displaying a few tickets (which have not been updated. Only showing 22 out of 25 tickets in the milestone)

This only happened with one of our milestones, not sure how it happened or how to reproduce

**Comment by zhangchiqing** [comment]
Hi @aj-thilakan, could you try refreshing the board page, and see if that milestone is still not display some tickets?

**Comment by aj-thilakan** [comment]
its fine now. Didnt make a difference if i hard refreshed/cleared cache when i tried yesterday (also saw the same issue on another user's device)

**Comment by azenMatt** [comment]
Hi @aj-thilakan - please let me know if you have any further problems with this!
