### ISSUE TITLE
Display Each Issues Epic

### ISSUE THREAD

**Issue by hbenoit** [ZenHubIO/support#742]
When looking at our board, we'd like the ability to see each issue's epic - just as you can see each issue's labels.

![image](https://cloud.githubusercontent.com/assets/2464368/15432886/03b7486e-1e7e-11e6-94c6-61bd47e018b7.png)

The workaround we are using, which is a bit redundant, is in addition to assigning an issue to an Epic, we then tag the issue with a label that has the epic's name.  

![image](https://cloud.githubusercontent.com/assets/2464368/15432961/474a3e9c-1e7e-11e6-8519-5dda4055de7a.png)

**Comment by azenMatt** [comment]
Thanks for the feedback @hbenoit - I have had a lot of requests for this, we will find a better way to communicate child issues on the board 👍

**Comment by azenMatt** [comment]
Hi @hbenoit - this one is finally done :) the latest version being released at the moment has - 

![image](https://cloud.githubusercontent.com/assets/7584089/21206729/bc287628-c218-11e6-806d-87ef0189fd1d.png)

enjoy!
