### ISSUE TITLE
Updating an existing issue with an epic deletes issue

### ISSUE THREAD

**Issue by rickysahu** [ZenHubIO/support#745]
Steps to reproduce:
1) create an issue (either through zh or gh interface)
2) view issue once created by going to https://github.com/:user/:repo/issues/:issueid
3) attach issue to an epic
4) refresh page

Result: issue page cannot be found
Expected Result: issue page is found epic attachment updated

**Comment by kendramoroz** [comment]
@rickysahu Hey Ricky, Kendra here from the ZenHub team! Doing some cleaning here and wanted to know if you're still experiencing this issue? Just did a test myself and wasn't able to repo, but before closing wanted to make sure nothing weird is happening on your end!
