### ISSUE TITLE
Will the trial work for private repos?

### ISSUE THREAD

**Issue by jasonjohnsonSA** [ZenHubIO/support#746]
Hi Guys,

I want to demo the product (non enterprise) on a private repository we have. Does this work? Is there any reason that only I can see the zen features and another admin on the same repo can't?

**Comment by azenMatt** [comment]
Hi @jasonjohnsonSA - this should be fine - as long as everyone has the extension installed and has accepted the permissions it will work for everyone. 

The best way to troubleshoot this is to see if there are any errors in your browsers javascript console when you try and load the board. If you can send me a screenshot of this we can get to the bottom of it! 

Would you be able to email our support address and we will help get everyone on the team up and running - support@zenhub.io 

Thanks!
