### ISSUE TITLE
Make it easier to direct people without the browser extension to a board

### ISSUE THREAD

**Issue by mogul** [ZenHubIO/support#754]
The fact that the data on public repositories is not visible without our stakeholders first installing the plugin and authenticating with GitHub has been very frustrating. Waffle.io is far less usable and integrated than ZenHub, but one benefit it offers is the ability to broadcast a canonical URL for a board and have anyone able to view it, whether they have a GitHub account or not... As it stands every time I refer to a ZenHub view from anywhere (wiki, email, IM) I have to loudly caveat it with "install this plugin or you won't see anything!" every... single... time. 

I'd be very happy to instead refer people to a documented, canonical ZenHub.io URL where if they have the plugin installed they get redirected to the right URL in GitHub to view the board, and if not they see a message that they have to have the plugin installed. (You can use this space to advertise the benefits and safety of installing the plugin if you like.) 

Even so, many of our stakeholders are in a heavily regulated environment where they won't be able to install the browser extension at all. So even better if you can actually show them a read-only view like waffle.io does at that canonical URL! :)

**Comment by mogul** [comment]
Ideally this would be exposed as a "Share this View" button in GitHub, which would give the presser of the button the zenhub.io-based URL to copy.

**Comment by mogul** [comment]
See also ZenHubIO/support#178

**Comment by kendramoroz** [comment]
Great discussion going here, thanks for the feedback! We're looking forward to enhancing ZenHub over 2017 to be a powerful asset your entire organization and stakeholders can enjoy and get value from. Moving this over to discussion so other members of the ZenHub community can add their thoughts as well! 

Happy new year 🚀

**Comment by kendramoroz** [comment]
@mogul The ZenHub team is really excited to announce the launch of the ZenHub web app today,
 accessible via [app.zenhub.com](https://app.zenhub.com). The web app can be used to access ZenHub across all web and mobile devices ⚡️, which means you can now share a link to a stakeholder without them needing to download an extension. 

You can learn more and invite any of your stakeholders to join you by sharing: [zenhub.com/web](https://zenhub.com/web)

Let us know what you think or if you have any questions we can help with!

**Comment by azenMatt** [comment]
> Is it possible to access a public board without signing in?

Not yet - due to how our permission model was built. But this is something that we would love to make happen in the future
