### ISSUE TITLE
Make it easier to filter by recent activity on boards

### ISSUE THREAD

**Issue by karlcz** [ZenHubIO/support#755]
When you have a sprawling board with dozens of repos and hundreds of open issues in a large team, it would be convenient to filter issues by recent activity (or conversely issues w/o recent activity). A few quick choices from a menu button would be useful, like "changed in last 12 hours, 1 day, 1 week" and "hasn't changed in 1 day, 1 week, 1 month". Ideally, there would be an option to enter your own criteria if these canned ones are not close enough.

This would cross-cut the pipelines to zero in on where discussions are happening (even on backlog issues), which items have changed pipeline state, etc.  It can be hard to sort that out in a busy board.  Filtering by milestone only gets you so far.

**Comment by joehanna** [comment]
+1

**Comment by kamura** [comment]
I would like to sort by updated pipeline date so that we can find stacked issues.

**Comment by kendramoroz** [comment]
We're currently working on ways to visualize activity on the Board! Stay tuned for more updates shortly ✨

**Comment by kendramoroz** [comment]
We recently launched new activity notifications on Issue cards! [Dig into the guides here](https://zenhub.freshdesk.com/support/solutions/articles/43000030576-view-issue-activity-in-real-time-on-the-board). And of course, let us know what you think!

![image.png](https://images.zenhubusercontent.com/5833aa0bb9dc3c6220225356/bc5c8616-fd8a-4816-a30d-11971141c32e)
