### ISSUE TITLE
Epics persist in Epics menu after closing

### ISSUE THREAD

**Issue by EnFinlay** [ZenHubIO/support#756]
Loving the epics, makes things way easier than the old "Ref: 170, 171, 172" style that I was using.

One issue I've encountered:  
When viewing an existing issue/PR, there's a menu for "Epics" to the right, right under "Assignee".  I like this menu.  The trouble is that once an Epic issue has been closed, the Epic still shows up in this menu.  

The way I've found to get it out of this menu is to click the "Delete this Epic" button on the original Epic.  The downside of this is that the history of what was accomplished with that Epic is now lost.

For my purposes it would be best if closing the Epic issue also removed it from the sidebar menu.  However, this might create an edge case for closing Epics while their child issues are still open.

**Comment by slajax** [comment]
👍 I would like this too.

**Comment by thalesfsp** [comment]
Very important, so it don't pollute the Epic box

**Comment by azenMatt** [comment]
this is going through our code review work flow right now :) 

cc @Mathieuu

**Comment by azenMatt** [comment]
This has been live for some time - apologies I missed the update here!
