### ISSUE TITLE
Show GitHub's multiple assignees on a card

### ISSUE THREAD

**Issue by mogul** [ZenHubIO/support#758]
GitHub finally supports [multiple assignees on an issue](https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests). Can you please show all those people on the card on the board, exactly as Trello does? 

![image](https://cloud.githubusercontent.com/assets/47762/15622671/ed0aad16-241f-11e6-9778-abeb4cfe9e35.png)

This would make it MUCH easier to understand who's pairing up on which stories.

**Comment by oevans** [comment]
👍  I was just coming to request this myself. Definitely would be a big help to add this soon.

**Comment by dwijnker** [comment]
I don't think ZenHub completely supports multiple assignees: if you filter the ZenHub board by assignee, you only see issues where that assignee is the first in the list

**Comment by oevans** [comment]
@dwijnker -- that's why we were requesting that ZenHub adds this. :-)

**Comment by dwijnker** [comment]
@oevans, agreed!

**Comment by azenMatt** [comment]
Hi all - we are looking to add this soon, based on the following use cases: 

![image](https://cloud.githubusercontent.com/assets/7584089/15729175/a196f8da-2816-11e6-9afc-72106de09ceb.png)


The filters will show you all issues where you are any of the assignees. 

We are finishing off our performance updates to the board - as soon as that is live, this will follow. ETA June/July - i will keep everyone updated

**Comment by azenMatt** [comment]
This is live - apologies i missed this issue when providing updates - but I am sure everyone noticed the extra faces appear 😄
