### ISSUE TITLE
Hovering over a card or column with a truncated title should show the full title in a hover

### ISSUE THREAD

**Issue by mogul** [ZenHubIO/support#761]
Looking at this support board I see this:

![image](https://cloud.githubusercontent.com/assets/47762/15624077/5b4743ee-2433-11e6-897a-5ee75c38c7c4.png)

Note that both the column title and the card titles are truncated. Hovering over them gives you no additional information... You have to click in (for cards) or edit (for columns) to see the full text. And you can't even edit column titles without write permissions on the repository!

It's tedious to click into each card just to read the full title, especially when you've got a long list of cards that all start with the same few words. Hovering over a card (or column title) should show the full title in a hint.

**Comment by azenMatt** [comment]
these now all have the full titles :) 

![image](https://cloud.githubusercontent.com/assets/7584089/17832603/08130eb2-66bc-11e6-8f0c-4b6d607ce11f.png)
