### ISSUE TITLE
[bug] ZenHub sidebar overlapping

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#763]
This is related to issue #655. But now it appears that GitHub has disabled the stickiness of the sidebar in Chrome. And now the sidebar is too tall when ZenHub is enabled

![zenhub-sidebar](https://cloud.githubusercontent.com/assets/136959/15716361/9729a552-27e7-11e6-9eff-9363b279b986.gif)

**Comment by azenMatt** [comment]
Hi @Mottie - which view is this in?

**Comment by Mottie** [comment]
Odd, it seems to have been fixed since this morning... the sidebar is sticky again. Oh well, maybe my browser was having a seizure.

**Comment by azenMatt** [comment]
:/ ok - I couldn't replicate either. 

Give me a shout if it happens again :)
