### ISSUE TITLE
Tag Issues within an Epic with an Indicator of What Epic(s) it Resides within

### ISSUE THREAD

**Issue by Anvil102** [ZenHubIO/support#764]
#### Description

Currently, when I view all the issues in a sprint / milestone its hard to see the "big picture" - i.e. which issues are in which epics without using epic filters. However, there are many times when I need to speckle the children of an epic at varying priority order in a sprint. I need more visual help in doing this effectively and swiftly.

</spacer>
</spacer>
###### User Story

As a user, I should be able to view all issues on a board within a particular milestone and quickly see which issues are attached to which epics without using the epic filter. Ideally either each issue within in epic as a _small_ tag or icon to associate it with it's parent epic. If the GH issues is a child of an epic that is nested in another epic, the issue is tagged with multiple labels / icons to indicate the entire epic chain it resides in.

</spacer>
</spacer>
###### Requirements
- There is a clear way to indicate / tag that an issue resides in multiple epics AND nested epics.

</spacer>
</spacer>
#### From
- Leap Motion

**Comment by azenMatt** [comment]
Hi @Anvil102 - are you happy for this to be closed based on the other updates here - ?

![image](https://cloud.githubusercontent.com/assets/7584089/21206808/259fb760-c219-11e6-9c61-5126115d5d6b.png)

**Comment by azenMatt** [comment]
closing this one - @Anvil102 new ZHE version with this included coming your way by Jan 17th :)
