### ISSUE TITLE
`Expand Board` Mode Should Stick After a Browser Refresh

### ISSUE THREAD

**Issue by Anvil102** [ZenHubIO/support#769]
###### Current Behavior
Currently when I have a ZH or ZHE board expanded using the "Expand / Collapse Board" button in the top left of the boards and I refresh said board using my browser's refresh button, the ZH board reloads in collapsed mode rather than retaining its expanded state.

###### Expected Behavior / User Story
As a user, when I go to refresh my ZH board via my _browser's_ refresh button, the "_Expand / Collapse Board_" selection I made prior to reloading should carry over on refresh. Thus if the board was in expanded mode, it should reload on refresh as expanded (and the same for collapsed mode).

#### From
* Leap Motion

**Comment by azenMatt** [comment]
We now encode the the full screen status into the URL so that a refresh will save the state. 

This will be in the next (August) Enterprise release

**Comment by Anvil102** [comment]
Great to hear! Thank you, Matt!
