### ISSUE TITLE
Ability to Filter For Full Nesting Structure of Epics

### ISSUE THREAD

**Issue by Anvil102** [ZenHubIO/support#770]
#### Description

As a user I should have the option to not only filter down to the first level of children in an epic, but also have a button or UI element that would allow me to filter for the entire nested structure of an epic.

Instead of seeing this:
1. **Epic of Epics**
   1. Epic 1
   2. Epic 2
   3. Epic 3
   4. Story
   5. _Implementation Task_

I would instead see something like this when I filtered for the entire nested structure:
1. **Epic of Epics**
   1. **Epic 1**
      1. Sub-Epic 1
         1. Subsub-Epic 1
         2. Subsub-Epic 2
            1. Story
               1. _Implementation Task_
               2. _Implementation Task_
            2. Story
               1. _Implementation Task_
               2. _Implementation Task_
            3. Story
               1. _Implementation Task_
               2. _Implementation Task_
      2. Sub-Epic 2
         1. Story
            1. _Implementation Task_
            2. _Implementation Task_
            3. _Implementation Task_
         2. Story
            1. _Implementation Task_
            2. _Implementation Task_
         3. _Implementation Task_
   2. **Epic 2**
      1. Story
         1. _Implementation Task_
         2. _Implementation Task_
         3. _Implementation Task_
      2. Story
         1. _Implementation Task_
         2. _Implementation Task_
         3. _Implementation Task_
   3. **Epic 3**
      1. Story
         1. _Implementation Task_
   4. Story
      1. _Implementation Task_
      2. _Implementation Task_
   5. _Implementation Task_
   6. _Implementation Task_
#### From
- Leap Motion

**Comment by kendramoroz** [comment]
Hey @Anvil102 some great improvements have been made over the last few releases to address nested epics and better handling of epic lists!

**Over the past few weeks we introduced board support for nested epics!** Before this change, when filtering by an Epic, only the direct children of that epic would be shown on the Board. Now, when adding an Epic, all its 'descendants' will be shown as well.

**And just yesterday we launched our new epic list enhancements.** When viewing an epic, you'll now see which pipeline issues fit into, as well as all nested epics. 

![image](https://cloud.githubusercontent.com/assets/11036230/22364019/4b9eeb58-e423-11e6-8503-0be71a443517.png)

With this change, you'll also see the addition of **epic points** which is the sum of all estimate points within that specific epic. If you click `show all issues` it'll display the issues that belong to that epic as well. 

![image](https://cloud.githubusercontent.com/assets/11036230/22364031/5262ce96-e423-11e6-8384-ee293819ec07.png)

Let me know what you think! 🚀
