### ISSUE TITLE
ZenHub Board Navigation Improvements

### ISSUE THREAD

**Issue by eddiethefoot** [ZenHubIO/support#772]
None of these are critical, but they would greatly improve my experience as I have a large monitor and always have lots of items on the board. Just throwing them out there for consideration 😺 

(1) As the user, I'd like the board view to not reset when I apply or remove filters so that I don't lose my place visually and get that jarring feeling. 
(2) As the user, I'd like an easier way to scroll the board left-right so that I don't have to use my arrow keys or the bottom scroll bar. (e.g. click and drag on an empty space in a column to scroll)
(3) As the user, I'd like a softer and more clear transition when filters are applied so that I don't lose myself and can visually track cards as they disappear or reappear. (i.e. I'd like to see cards move into place rather than just suddenly appearing or disappearing).

**Comment by azenMatt** [comment]
Hi @eddiethefoot - sorry for the late response here, 



> (1) As the user, I'd like the board view to not reset when I apply or remove filters so that I don't lose my place visually and get that jarring feeling.

Can you confirm if this is still the case? I have been unable to replicate





> (2) As the user, I'd like an easier way to scroll the board left-right so that I don't have to use my arrow keys or the bottom scroll bar. (e.g. click and drag on an empty space in a column to scroll)

We made the bottom scroll bar slightly larger to make it easier to 'grab'. Is this something you still find as a problem?



> (3) As the user, I'd like a softer and more clear transition when filters are applied so that I don't lose myself and can visually track cards as they disappear or reappear. (i.e. I'd like to see cards move into place rather than just suddenly appearing or disappearing).

The current filters still have the 'snapping' into place, rather than a soft fade - so I am assuming that this is still a problem with the new filter design?

**Comment by kendramoroz** [comment]
Hey @eddiethefoot, Kendra here following up on the notes from Matt above! Any additional insights or feedback you'd be open to sharing :)?
