### ISSUE TITLE
Is there a POST API for Zenhub enterprise for creating new issues?

### ISSUE THREAD

**Issue by arsarana** [ZenHubIO/support#773]
Is there a way (or an example you can point me to) where I can create new issues/epics for Zenhub boards via an API?

I reviewed the API docs here (https://github.com/ZenHubIO/API) but only found docs get GET requests.

Appreciate your help on this. Thanks.

**Comment by joeyfigaro** [comment]
Would also be interested in `POST`/`PUT` endpoints for modifying the pipeline a task belongs to when an action occurs.

**Comment by azenMatt** [comment]
Hi @arsarana @joeyfigaro - right now we only have the GET requests live for our API. 

But we do want to expand the functionality to include POST / PUT - likely early 2017. 

The best place to follow updates is the API repo, specifically this issue - https://github.com/ZenHubIO/API/issues/24 - which will get updated as we release these updates
