### ISSUE TITLE
New feature ,  hide sub issues of a epic 

### ISSUE THREAD

**Issue by timotanhong** [ZenHubIO/support#775]
In the boards scenario, if we can have a feature that only display a epic issue in the board, and all it's sub issues hidden , will be very helpful .

**Comment by azenMatt** [comment]
Hi @timotanhong - we are going to shortly add an explicit 'epic' downdown filter into the board. It sounds like this would be a good feature to include in the drop-down?

**Comment by azenMatt** [comment]
also - does the current label filter for 'epic' help out here at all?

**Comment by azenMatt** [comment]
Hi @timotanhong - this can be done with the new Epic filter :)
