### ISSUE TITLE
Clicking "Clear Estimate" removes the estimate, but not from the Kanban board.

### ISSUE THREAD

**Issue by LimitedWard** [ZenHubIO/support#777]
Clicking the "Clear Estimate" button will remove the estimate from that issue, but the changes do not propagate on the Kanban board without reloading the page.

**Comment by azenMatt** [comment]
Hi @LimitedWard - we have released a round of improvements to the board which include much faster updating so you will not need to refresh any more to see this. 

Please let me know if you see any issues here still
