### ISSUE TITLE
Issues used as Agile Cards - need tags / value

### ISSUE THREAD

**Issue by matthewtanner** [ZenHubIO/support#780]
As a Scrum Master dealing Agile Project Management, I would like to utilize ZenHub for allowing cards to be tagged ("#sales #po2.1"), and to provide business value on the cards (core value item in all Agile Management).

Example:
Card Info contains the following key criteria to make it a great card for being Agile.
- Title
- The WHO , the WHAT, the WHY
- Estimated Effort (xs, s, m , l , xl or 1 , 3 , 5, 8, 13 etc)
- Labels (great for epic tracking)
- Tags (great for system / app specific tracking, code reviews, delays, etc.)
- Estimated Value (value relevant to a $ amount, so $ or $$ might mean something, or 1,2,3,4,5 to be simple)

**Comment by kendramoroz** [comment]
@matthewtanner great idea here! I've bumped this over to discussion to get more insight from the community. Keep the 👍 's coming!
