### ISSUE TITLE
Maximized/Full Screen Link for Boards?

### ISSUE THREAD

**Issue by rprovost** [ZenHubIO/support#783]
I love the new(ish) maximized board view! I find myself always in that mode now.

I was wondering if it would be possible to add a query-string parameter so that a board can be maximized/full-screen by default (through a bookmark, for example) rather than needing to load the board and then hit the button?

**Comment by andycleff** [comment]
@azenMatt any thoughts on this one?

**Comment by azenMatt** [comment]
Hi @andycleff @rprovost - we are just about to roll out our new board architecture, shouldn't be too much of a stretch to add this to the number of board improvements we want to make over the coming weeks once this is live 😄  

Let me see what I can do

**Comment by azenMatt** [comment]
Hi @rprovost @andycleff  - this just went live as part of some board changes we released with v2.21.1 - I hope it helps!
