### ISSUE TITLE
Install for Firefox 47.0 not working

### ISSUE THREAD

**Issue by benred42** [ZenHubIO/support#784]
I am attempting to install ZenHub on Firefox 47.0 and when I click "Add ZenHub to GitHub" I am presented with this pop-up:

![zenhub_firefox47_install](https://cloud.githubusercontent.com/assets/5168385/16050905/6e9e0c6a-322b-11e6-878c-0a5b7f82b847.png)

It states that clicking "Allow" will enable ZenHub, but there is no Allow to click or any other elements to interact with that let me accept the install.  Perhaps I am missing something about the process, in which case this may be an issue of documentation.  Either way this is probably something that should be addressed.  Please let me know if you need any more information from my end.

**Comment by notriddle** [comment]
The certificate on firefox-extension.zenhub.io expired

**Comment by benred42** [comment]
Ah, that would be it.  It looks like the cert has been renewed now, so this issue is resolved for me.

**Comment by azenMatt** [comment]
Thanks for pointing this out! we are on it....

**Comment by azenMatt** [comment]
Everything is back to working here - thanks again for letting us know 😄
