### ISSUE TITLE
New issues add "wontfix" label by default

### ISSUE THREAD

**Issue by tannerwelsh** [ZenHubIO/support#785]
When creating a new issue, the `wontfix` label is applied by default and cannot be removed.

Adding/removing this label works just fine when I'm not signed into ZenHub.

Using version 2.18.2

**Comment by tannerwelsh** [comment]
Whoops, nevermind looks like it has to do with another extension.

**Comment by azenMatt** [comment]
> When creating a new issue, the wontfix label is applied by default and cannot be removed.

That's one way to keep the backlog short!

**Comment by billboga** [comment]
Also have similar behavior. Tracked it to the LastPass extension.

**Comment by tannerwelsh** [comment]
Thanks for the notice @billboga, I'll keep my eye out for a reoccurrence. Haven't noticed the issue lately.
