### ISSUE TITLE
Public API CORS

### ISSUE THREAD

**Issue by joseandrespg** [ZenHubIO/support#792]
Hi!

I'm creating a custom Chrome extension that needs to load data from your public API. But in both, in my localhost and in the chrome extension I'm receiving CORS errors.

> XMLHttpRequest cannot load https://api.zenhub.io/p1/repositories/NUMBER/issues/NUMBER?access_token….
 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://CHROMEID' is therefore not allowed access. The response had HTTP status code 404.

Do you have any idea why it's happening?

Thanks!

**Comment by joseandrespg** [comment]
If I pass the token using the header "X-Authentication-Token" the error is the same but ended in:

> The response had HTTP status code 401.

**Comment by joseandrespg** [comment]
Using Postman is working fine.

**Comment by azenMatt** [comment]
Hi @joseandrespg - apologies for the slow reply here, do you mind sending an email to our support team - support@zenhub.com and we will get this working for you - thanks!
