### ISSUE TITLE
Don't have Esc key exit zenhub board

### ISSUE THREAD

**Issue by edmapd** [ZenHubIO/support#793]
Since the zenhub board is presented as a tab within Github, it's a surprising/undesired user experience to have hitting the escape key drop you out of the board and back to the Issues tab.

A typical situation: I'm at the board and I click an issue, which gives me a modal overlay of the issue.  I smack the escape key to get out of the issue and b/c of force of habit, I wind up hitting the escape key twice.  Result: I'm confusingly dropped all the way back to the Github Issues tab.

**Comment by azenMatt** [comment]
I agree it would make more sense for this to be esc only on the modal 

We will take a look

**Comment by azenMatt** [comment]
This one is now fixed and the esc key will no longer exit the ZenHub board, so it should make it much easier to use the esc key to close modals / filters without worrying about the board closing :D

**Comment by edmapd** [comment]
Thank you!
