### ISSUE TITLE
Allow list issues in the public API

### ISSUE THREAD

**Issue by joseandrespg** [ZenHubIO/support#794]
Hi!

I'd suggest to allow list issues within the public API, ex with filter:

> https://api.zenhub.io/p1/repositories/13550592/issues?issue_numbers=234...

As it already exist in your private API, ex with filter:

> https://api.zenhub.io/v4/repositories/13550592/issues?issue_numbers=234...

It'll save tons of calls to "https://api.zenhub.io/p1/repositories/13550592/issues/NUMBER" for every issue that I want to retrieve the additional info (all of them indeed).

Good for your servers, good for us.

Thanks!

**Comment by azenMatt** [comment]
Thanks @joseandrespg  - moving this over to the API repo

**Comment by azenMatt** [comment]
Issue moved to [ZenHubIO/API #29](https://github.com/ZenHubIO/API/issues/29) via [**ZenHub**](https://www.zenhub.com/)
