### ISSUE TITLE
Unable to filter by assignee when issue has multiple assignees

### ISSUE THREAD

**Issue by wreyniers** [ZenHubIO/support#798]
Github recently released a feature that enabled you to select multiple assignees to an issue. https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests

When using the Zenhub Kanban board, filtering by assignees does not display issues where the assignee is not the 1st assigned. 

How to reproduce:

1. Create an issue and assign user 1 and 2
2. Filter Kanban board to only show issues assigned by user 1
3. Issue is displayed as expected
4. Filter Kanban board to only show issues assigned by user 2
5. Issue is not displayed despite the fact that user 2 is assigned.

**Comment by HeathNaylor** [comment]
:+1:

**Comment by wreyniers** [comment]
This is a duplicate of #765 and #758. Sorry about that.
