### ISSUE TITLE
Support issue  'Voting' and make it visible on issue cards on the board

### ISSUE THREAD

**Issue by andycleff** [ZenHubIO/support#802]
Allow users to vote on a card, remove their vote, and display the total number of votes received.

**Comment by andycleff** [comment]
![votes ala trello](https://cloud.githubusercontent.com/assets/7416277/16335710/16c0419a-39d6-11e6-83dd-8fddad5290d4.png)

**Comment by azenMatt** [comment]
Hi @andycleff - do you see this as being connected to existing GitHub reactions?

**Comment by andycleff** [comment]
Connecting to the existing GitHub reactions would be a nice way to go!

Total up the thumbsup's reactions on the issue, anywhere in the comment thread, 
display the total count of thumbsup on the zenhub board view.

As an added bonus, enable auto ordering by count....

**Comment by Alexander01998** [comment]
> As an added bonus, enable auto ordering by count....

I'd be looking forward to that as well. Having some kind of screen or board setting that shows the most popular issues would be extremely useful for me.

@azenMatt Should I make a separate issue for sorting by votes?

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports to give teams in ZenHub a stellar workflow and workspace home to manage projects. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
