### ISSUE TITLE
Burndown breaks when board is large  (Request-URI Too Large) 

### ISSUE THREAD

**Issue by danmosemsft** [ZenHubIO/support#803]
The burndown chart for this milestone fails to render:

https://github.com/dotnet/corefx/milestones#burndown?milestoneId=4

the Chrome console suggests a bug in Zenhub:

GET https://api.zenhub.io/v4/repositories/26295345/issue_estimates?issue_number…C862%2C858%2C851%2C839%2C820%2C780%2C754%2C668%2C636%2C536%2C392%2C71%2C52 414 (Request-URI Too Large)

**Comment by paigepaquette** [comment]
We've implemented a fix that should resolve this issue. Let us know if you run into any other snags!

**Comment by danmosemsft** [comment]
Works great, thanks!
