### ISSUE TITLE
Generate "flattened" Markdown summary

### ISSUE THREAD

**Issue by hughdickinson** [ZenHubIO/support#805]
This facility may already exist, but if it does not it would be useful to be able to generate "flattened" (and ideally filterable based on Milestone) summaries the state of a ZenHub view of a repository. 

My primary use case for such a feature it to accommodate particularly recalcitrant members of my team who are habitual Safari users and are not willing to transition to Chrome or Firefox. 

I would like to be able to straightforwardly provide a static summary of current progress using the GitHub wiki interface. Being able to automatically generate the required markdown would be a substantial timesaver and enable concurrency between the ZenHub and Wiki representations to be much more easily maintained. 

If filtering by milestone were possible, then a separate wiki page could be generated for each milestone, making navigation and segregation in the wiki more straightforward.

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports to give teams in ZenHub a stellar workflow and workspace home to manage projects. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
