### ISSUE TITLE
Intermittent issues loading Boards caused by Javascript errors

### ISSUE THREAD

**Issue by jacobtabak** [ZenHubIO/support#810]
Very often when attempting to load our boards, I encounter a javascript error that causes the page to sit on the loading screen infinitely.  

```
main.js:36 Uncaught TypeError: Cannot read property 'get' of undefined
```

Here's a screenshot of the console:

![image](https://cloud.githubusercontent.com/assets/1854831/16459131/5fa384d4-3de7-11e6-9274-02772675d433.png)

It looks like the problem is in this function:

```
            isFilteringThisEpic: function() {
                if (!this.isEpic()) return !1;
                var e = this.getEpicFilterModel().get("settings");
                return e && e.repo_id && e.issue_number && e.repo_id === this.get("repo_id") && e.issue_number === this.get("number")
            },
```

`this.getEpicFilterModel()` is undefined.

Reloading the page (sometimes several times) fixes it, and I can't always reproduce it.

**Comment by aupright** [comment]
Hey @jacobtabak - Aaron from the ZenHub team here.

I've issued this one up internally, and we're currently taking a look - thanks for sending this through!

**Comment by azenMatt** [comment]
Hi @jacobtabak - we had some fixes go live for this one - would you be able to confirm if it is still occurring for you?
