### ISSUE TITLE
As a user, I want to consume data via webhooks vs a strict API

### ISSUE THREAD

**Issue by thomasrockhu** [ZenHubIO/support#811]
The API is very good regarding retrieving data about my boards and issues, but I want to be able to receive JSON to a callback URL whenever I an event has occurred (e.g. an issue has been moved to a new pipeline).

Having webhooks helps me from running a script every `x` minutes to discover what issues may have been moved around, which can be very costly in terms of # requests being made (and thus hitting the rate limiting barrier)

**Comment by azenMatt** [comment]
Hi @thomasrockhu - we now have webhooks live for each of the events you can get a slack notification for - so issue transfer, estimate changes etc. 

You can find out more here - https://github.com/ZenHubIO/API#webhooks
