### ISSUE TITLE
Freezes when changing board

### ISSUE THREAD

**Issue by JeanetteNielsen** [ZenHubIO/support#812]
Repo steps:

- Go to boards
- Repo > select/deselect a repo
- click on a issue

After these steps I can't close the ticket, or click anywhere. I need to reload the page to continue.

**Comment by azenMatt** [comment]
Hi @JeanetteNielsen - we just released a full board refactor that should have improved the performance and taken care of this problem. Would you be able to confirm if you can still replicate?

**Comment by JeanetteNielsen** [comment]
Hi @azenMatt, 
Sorry for the long response time, I was on vacation.
It's working, thx :)
