### ISSUE TITLE
Doxygen integration

### ISSUE THREAD

**Issue by dderiso** [ZenHubIO/support#815]
Thanks for the great product! I would like to suggest a feature. For complicated stacks, I like to write the docs as I code, usually with Doxygen. Each class description is a small story about use cases and future work, which contains Doxygen to-do lists. That is my natural workflow, and it would be nice to have this sync with my PM software. Specifically, I would love if these to-do lists automatically appear in my PM task board such that team members can see and comment and even upvote/downvote. I realize it would be fairly straightforward to write a Python script that parses my Doxygen generated docs and simply posts the tasks to ZenHub after each make or commit, but I thought it might also be a good (though not-so-small) feature to have in your product. What are your thoughts? Thanks for considering!

**Comment by azenMatt** [comment]
Hi @dderiso - thank you for the suggestion, we can certainly take a look into this in the future as Docygen looks very interesting 

For the moment - I have added the 'needs votes' label to get some feedback from everyone else as to how useful this would be to help us prioritize
