### ISSUE TITLE
Feature request - Kanban charts

### ISSUE THREAD

**Issue by andrebrov** [ZenHubIO/support#816]
Hello guys,

Thank you for the great tool. I'm big fan of Kanban and I'm really missing two charts - [Cumulative flow diagram and Control chart](http://www.swiftkanban.com/kanban/what-can-kanban-metrics-tell-me-about-how-well-we-are-doing/). TargetProcess team also described them [very well](https://www.targetprocess.com/blog/2013/09/take-5-visual-reports-for-kanban/). Without this tool it's hard to do any estimation.

**Comment by azenMatt** [comment]
Thanks for the kind words @andrebrov - cumulative flow is a report we would like to get live in the near future as i think it would prove very useful for all teams. 

I will take a look into how we could integrate a control chart as well

**Comment by robneville73** [comment]
+1 for this for those of not doing scrum but doing pure kanban both cumulative flow and control (or some other way to view variations in cycle and lead time) would be AWESOME

**Comment by EliasKokkinis** [comment]
@azenMatt the fact that Zenhub doesn't offer any metrics for non-scrum agile methods (especially a cumulative flow diagram) is the only thing that really keeps our team from making the transition. Someone from your team mentioned in some e-mail communications back in November that this was something planned for Q4 of '16. Any updates on this?

**Comment by kendramoroz** [comment]
Hey @EliasKokkinis Kendra here from the ZenHub team! Adding cumulative flow diagrams is still on our roadmap! We'll be working on providing more information over the next few weeks on our roadmap via the support repo here, so stay tuned for more information.

**Comment by baratrion** [comment]
Hi @kendramoroz any updates on this?

**Comment by yatespeakof** [comment]
Hi @kendramoroz I'm also interested in CFDs for our teams.  Have you shared the roadmap, as I can't see it if you have.  Thanks

**Comment by kendramoroz** [comment]
Hey @yatespeakof thanks for pinging us! We use the Support Board as a public roadmap currently - CDF's are still in discussion! We'll be sure to post updates to this Issue as things evolve around this enhancement 🚀

**Comment by jonhorton** [comment]
Another request here for more Kanban related reporting. Cumulative flow & control charts, and a way to track time in a column would be super useful to our team!

**Comment by Charlenes1** [comment]
Yes please, add me to the group requesting Cumulative Flow Diagrams :-)

**Comment by kendramoroz** [comment]
Doing some Issue clean up! Please subscribe to https://github.com/ZenHubIO/support/issues/559 for kanban metric updates :)

**Comment by kendramoroz** [comment]
👋 Hey everyone! I know this issue is closed, but wanted to provide an update since a few people here asked for Cumulative Flow. This is now in development ✨ we should be launching this report in a few sprints from now. Stay tuned for updates on #559!
