### ISSUE TITLE
z-order issue with list of repositories when viewing PR

### ISSUE THREAD

**Issue by milipili** [ZenHubIO/support#817]
The "Showing changes from.." from the github page is displayed in front of the menu
(firefox 47 - linux ubuntu)

![zenhub-z-order](https://cloud.githubusercontent.com/assets/5516919/16673736/c9cea496-44eb-11e6-81a5-ca2fee4f292e.png)

**Comment by azenMatt** [comment]
Hi @milipili - I haven't been able to replicate this one... can you confirm if it is still happening?

**Comment by milipili** [comment]
Indeed, I am no longer able to reproduce the bug.
I currently only have a Firefox 45 ESR but it should not change the result.

**Comment by azenMatt** [comment]
Thank you for confirming
