### ISSUE TITLE
Show/Hide columns based on role

### ISSUE THREAD

**Issue by saberprivateer** [ZenHubIO/support#819]
We use one massive pipeline for our process.  It begins with the product icebox, goes through design, and ends with engineering, test, and release.  The designers sometimes reference things in engineering and vice versa.   As a product manager, I'm constantly jumping all around.  It'd be great to be able to select from a dropdown "design" and it would minimize the columns I've set that aren't design.  Our designers would want this as a default.

**Comment by azenMatt** [comment]
The use case for this makes a lot of sense, I know a lot of our team will always have different pipelines collapsed or expanded depending on role / task - an easy way to switch would be helpful

**Comment by zavreb** [comment]
+1

**Comment by kendramoroz** [comment]
Very excited to provide an update here! We're working on workspaces, which can be tracked via #139! Workspaces will allow teams to create custom view by pipeline based on what's most important to them :). Subscribe to #139 and take a look at the latest comments for more details about this upcoming feature!
