### ISSUE TITLE
Issues not showing up in pipelines

### ISSUE THREAD

**Issue by hexgnu** [ZenHubIO/support#820]
Hello there,

So I've tried a few different tricks such as browser refresh, another machine, firefox vs chrome.

But it seems that when I create a new issue it will not show up in any pipelines. Our new issues are empty except we have plenty of new issues with the pipeline "New Issue" associated. When I try and change the pipeline to something like "Pending" it still doesn't show up there.

What should I try next?

Thanks!

**Comment by azenMatt** [comment]
Hi @hexgnu - can you let me know which org/repo you are having this problem on?

**Comment by hexgnu** [comment]
Hey @azenMatt it's on Etison/infrastructure (which was recently renamed maybe that's it?)

**Comment by azenMatt** [comment]
A rename shouldn't impact it... let me take a look and I will get back to you shortly

**Comment by azenMatt** [comment]
Ok - we should be back in business.... can you refresh and confirm?

cc @jkan2

**Comment by hexgnu** [comment]
Alright thanks!
