### ISSUE TITLE
support for Edge browser

### ISSUE THREAD

**Issue by danmosemsft** [ZenHubIO/support#822]
In the Summer 2016 release of windows 10, Edge will apparently support Chrome extensions with few or no modifications. I am not sure of the criteria they use for putting extensions on the Edge store, but you might consider getting ZenHub up there.

**Comment by azenMatt** [comment]
Hi @danmosemsft - would love to get this working, I need to follow up with a few contacts on the edge team to test out the current ZH build and find out how close we are to being compatible

**Comment by danmosemsft** [comment]
Let me know if you need a contact over there. I worked on the F12 support for extensions in my last job.

**Comment by azenMatt** [comment]
Thanks Dan - will do 😄

**Comment by danmosemsft** [comment]
How's it going @azenMatt ? :)

**Comment by azenMatt** [comment]
Hi @danmosemsft - no big updates here right now, I am still looking to understand from the edge team what the update process will be (aka will it be dev friendly like Chrome, or the opposite like Safari). Let me send some follow ups out to see if there is any further clarity on that yet

**Comment by danmosemsft** [comment]
No hurry on my part at all :)

**Comment by azenMatt** [comment]
For everyone else following along here, please 👍 the original comment if edge support would be useful for you or other team members as it will really help us prioritize this

**Comment by morsh** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions

**Comment by CIPop** [comment]
> https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions

@morsh tried it but it didn't work. The only errors I got were some CSS relative paths that I've ignored (it's missing the icons in the main display - not a big deal).

The problem is that it hangs at "Signing in..."

**Comment by morsh** [comment]
@CIPop  - bummer, I thought it would help advance the issue...

**Comment by danmosemsft** [comment]
@morsh do you have necessary support from the Edge team?

**Comment by morsh** [comment]
I might be able to push it though with the Edge team, would you like to contact them?

**Comment by CIPop** [comment]
Sure. Let's take this offline.

**Comment by danmosemsft** [comment]
@morsh Colleen from Edge just now reached out to someone on your team they worked with before.

**Comment by morsh** [comment]
@danmosemsft - thanks for picking this up.
@CIPop - we will continue this thread once we move forward

**Comment by azenMatt** [comment]
Hi @danmosemsft @CIPop @morsh - thanks for getting the ball back moving with this! 

I just had an email from Colleen - but just so we are all on the same page - the three of you are all MS employees right?  I believe Colleen reached out as she thought the ZenHub team were having issues with the porting? 😄 

We would love to get a version of this working for MS Edge - right now, we are focused on #156 (which will include edge support) but would be happy to pick this back up after (assuming the issue above are still persisting)

**Comment by danmosemsft** [comment]
Yes we are, but @cipop is on networking and I am on .NET.

**Comment by Groostav** [comment]
So I'm mainly a firefox user, and the Zenhub Plugin on firefox _works_ although it occasionally crashes and requires a restart of firefox. But Edge is now _so much faster_ at rendering large pull requests that I really want to switch to it, but Zenhub is a really big reason not to.

_I'm really looking forward to this feature_

**Comment by azenMatt** [comment]
Hi @danmosemsft @morsh - we just released the web-app version of ZenHub - https://www.zenhub.com/web - which is edge compatible. 

We had to fix some compatibility issues to get everything displaying correctly, which should make a future version of an extension easier. 

Until then hopefully this web view helps! Let me know your thoughts!

**Comment by danmosemsft** [comment]
Thanks @azenMatt !

**Comment by morsh** [comment]
@azenMatt - thanks for the update!

**Comment by Sparkx120** [comment]
Just started using ZenHub Enterprise where I work and as far as I know the web interface can't access GitHub Enterprise resources. Is there still any effort going into porting the extension to Edge or a standalone app that would be able to access Enterprise GitHub?

**Comment by azenMatt** [comment]
@Sparkx120 - we have a version of the webapp that works with ZHE / GHE, but you will need the custom domain for within your organization. If you can email us at enterprise@zenhub.com , we can let you know how to access this.
