### ISSUE TITLE
Boards Assignees empty tooltip

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#823]
An empty tooltip opens when hovering over the select button.

![2016-07-12 15_58_17-boards mottie_tablesorter](https://cloud.githubusercontent.com/assets/136959/16783494/e6ce2f92-4849-11e6-98a8-0d709892974f.png)

**Comment by azenMatt** [comment]
Hi @Mottie - this one should now be fixed with the new board code. 

Let me know if you see it come up again!
