### ISSUE TITLE
Closing issue modal also closes boards

### ISSUE THREAD

**Issue by justmatt** [ZenHubIO/support#825]
**Steps to reproduce**
1. Go to Zenhub boards on Github repo
2. Open modal for issue with assignee
3. Clear all assigness
4. Close modal

**Expected**
Boards stay open

**Actual**
Github redirects to dedicated issue page (closes Zenhub Boards) for issue from modal which was just closed

**Comment by azenMatt** [comment]
That is not what we want to happen! 

We will get this fixed!

**Comment by azenMatt** [comment]
Hi @justmatt - as a quick update here, this looks to be a bug in GitHub - as you can trigger a full page refresh with the same action from a plain issue page. 

I have reported to the GH team so lets keep an eye on if they will fix it, which would be the better solution vs us trying to override the action from there side
