### ISSUE TITLE
Critical Bug: Unable to create Epics

### ISSUE THREAD

**Issue by porta-antiporta** [ZenHubIO/support#826]
Hello,

I am experiencing an issue (across multiple repos) where when I attempt to create an Epic, it is only created as a GH Issue (all metadata indicating an issue is an Epic is lost).

Steps to Reproduce:

1. On board view, click on `New Issue`
2. Enter a Title and click on 'Create an Epic` 
3. The Epics screen appears, it doesn't matter if you associate issues to the epic or not
4. Click on `Create Epic`
5. Issue gets created as an Issue, not an Epic.

**Comment by porta-antiporta** [comment]
(Fyi I followed the same steps to recreate the bug when creating this issue, same deal unable to create an epic)

**Comment by porta-antiporta** [comment]
Also, I should add that the issue only seems to affect new Epics; I can still see/manipulate previous epics I had created.

**Comment by azenMatt** [comment]
Hi - I can recreate this, we will get this fixed ASAP

**Comment by azenMatt** [comment]
Hi @porta-antiporta - we just push a fix for this which you can get by updating to 2.20.10

Please let me know if you have any other problems or if this doesn't work for you! 

Thank you for letting us know about this one!

**Comment by porta-antiporta** [comment]
@azenMatt Fix works!  Note I had to reload the repo's board page for the fix to take effect.  Thanks for the quick turnaround on this!
