### ISSUE TITLE
BUG? Issue Editing: the epic selector in the right nav column broken if issue is in repo gropued with other repos on board

### ISSUE THREAD

**Issue by stephenakearns** [ZenHubIO/support#828]
Hi @azenMatt ,
When I'm editing an issue and want to add it to an existing epic, I click the gear icon and am expecting to see a list of epics in that repo. I have lots, but the list is always blank. I don't know if this is a time-out/performance issue or something, but it works on new issues, but never for existing issues. Scanned the list of issues for epics but didn't see it. if this isn't user error, then this is a big bug/usability issue for us. Please fix asap. thx!

**Comment by stephenakearns** [comment]
Ok - @azenMatt  isolated it a bit furhter... it seems that when I have multiple repos grouped together on a board, it stops working. When I have a single repo not grouped with others, it's still working. See screenshots below... 

For this one, I have 8 boards grouped together - Not working - list of epics not appearing: 
![image](https://cloud.githubusercontent.com/assets/13372164/16956136/325a57fa-4da5-11e6-85e7-e3403247f1f7.png)


Single Board - it works! 
![image](https://cloud.githubusercontent.com/assets/13372164/16956247/b4a2d048-4da5-11e6-988d-2a7466aeed85.png)

**Comment by azenMatt** [comment]
Hi @stephenakearns - we are taking a look at this now 

I'l keep you updated

**Comment by azenMatt** [comment]
We are having a hard time replicating this one... 

Do you get any errors in the dev console (view -> developer -> java script console -> errors) when you try and load this drop down? 

If so, can you share them here? 

If not, can we jump on a quick screenshare to debug? Let me know and I will send you an email

**Comment by azenMatt** [comment]
Hi @stephenakearns - any luck with this?

**Comment by stephenakearns** [comment]
Hi @azenMatt - went back to try it out and everything is working now! I'm now getting full lists of available epics in the dialog. Closing the issue.
