### ISSUE TITLE
Marketing: Your last email was suuuuuper buggy when viewed on unroll.me

### ISSUE THREAD

**Issue by dsifford** [ZenHubIO/support#829]
See here: https://www.opentest.co/share/8f9a7b704e1311e68356998afd9fab62

Doesn't seem like an unroll.me thing, since all other emails are fine.

**Comment by paigepaquette** [comment]
Hey, @dsifford -- marketing here!  Curious: Have you viewed other ZenHub emails in UnRoll.me before and experienced no issue? Thanks for passing this on. We'll look into it.

**Comment by dsifford** [comment]
@paigepaquette Hi there. Yep, that's where I've always read them. 

This might be some crazy anomaly. Not totally sure. Figured I'd toss it your way nevertheless.

Tell you what: If you can't immediately spot the problem, close this issue and I'll keep an eye out for any future issues. If I come across this issue again, I'll open this back up. 👍

**Comment by paigepaquette** [comment]
Thanks for the clarification. I'll dive in to see if anything's out of the ordinary from our end. 

Appreciate you bringing this up! Cheers.

**Comment by dsifford** [comment]
@paigepaquette Unfortunately, this issue is still happening on you latest Software Estimates email.

Happy to help out wherever I can to get this figured out.

**Comment by paigepaquette** [comment]
Appreciate your follow up! I'll see if they have any insight as to what could be the root cause here.

**Comment by dsifford** [comment]
My pleasure.

Details about me: 

```
Google Chrome	54.0.2810.2 (Official Build) dev (64-bit)
Revision	84cc4cdf21633b6209f2561e78fea87d40e84329-refs/branch-heads/2810@{#5}
OS	Linux 
JavaScript	V8 5.4.278
Flash	22.0.0.209
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2810.2 Safari/537.36
```

**Comment by dsifford** [comment]
@paigepaquette 

The last email was affected as well, so I just figured it out for you guys.

Here's the issue:

Your email template is essentially two tables, one for all the content, the other for the footer.

![image](https://cloud.githubusercontent.com/assets/5240018/17758341/75181658-64bc-11e6-9629-0cce53cc76c6.png)

The main content table (pictured above) has inline css that sets `height: 100%`. Removing that (or changing it from `100%` to `auto`) solves the issue completely. I'm guessing that the Unroll.me email window has some dynamic height handler that freaks out with relative height units.

Consider changing that in your template. Thanks so much.

**Comment by paigepaquette** [comment]
Thanks @dsifford ! This is super helpful. +1 

We'll change that in the next email.
