### ISSUE TITLE
Add support to Gitlab

### ISSUE THREAD

**Issue by ayr-ton** [ZenHubIO/support#83]
Gitlab is a open source Github alternative made with Ruby on Rails.

There's some plans to add support for it?

**Comment by carlbarrdahl** [comment]
+1

**Comment by sghribi** [comment]
+1

**Comment by computeus** [comment]
+1

**Comment by manusajith** [comment]
+1

**Comment by titanomachy** [comment]
+1 at work.

**Comment by sefrankel** [comment]
+1

**Comment by chiavegatto** [comment]
:+1:

**Comment by chiavegatto** [comment]
:+1:

**Comment by martinhecher** [comment]
+1

**Comment by ferricoxide** [comment]
:+1:  (GitLab at work - thinking of setting one up on my VPS for private projects)

**Comment by mellotronrust** [comment]
+1

**Comment by leokun** [comment]
Hi, you still need votes ? :-D

Using GitLab at work and at home, this is a big +1 :+1: 

_there is an open source project trying to do this but still really poor : [GitLab Kanban](http://kanban.leanlabs.io/)_

**Comment by pascalandy** [comment]
+ a thousand time ... meanwhile, I will sign up for Jira and trello is getting limited for our CI/CD needs

**Comment by misteral** [comment]
Hi, we are using Gitlab at ITBeaver. 
:+1:   +1

**Comment by Deathgazeroo** [comment]
so much +1

**Comment by simonrenoult** [comment]
Any news about this?

**Comment by ginfuru** [comment]
+1 Gitlab would be super!

**Comment by jollychang** [comment]
+1

**Comment by calen-legaspi** [comment]
+1

**Comment by kiettisak-angkanawin** [comment]
+1

**Comment by phuttha-k** [comment]
+1

**Comment by drewcrawford** [comment]
+1

**Comment by tiagohillebrandt** [comment]
+1

**Comment by vga-** [comment]
+1

**Comment by abelino** [comment]
:+1:  :smile:

**Comment by jeffersonxavier** [comment]
+1

**Comment by michalgritzbach** [comment]
+1

**Comment by dustinblackman** [comment]
:+1:

**Comment by liquidstate** [comment]
:+1:

**Comment by andyshephard** [comment]
+1

**Comment by ares86** [comment]
+1

**Comment by TheYorickable** [comment]
+1

**Comment by berik** [comment]
+1

**Comment by iJanki** [comment]
+1

**Comment by sakebook** [comment]
:+1:

**Comment by pascalandy** [comment]
+1

**Comment by alcidesqueiroz** [comment]
+1... We're using GitLab at work!
cc: @brunoplima

**Comment by brunoplima** [comment]
+1

**Comment by gabejohnson** [comment]
+1 using at work

**Comment by viranch** [comment]
+1

**Comment by adithyabenny** [comment]
+1

**Comment by liangshan** [comment]
+1

**Comment by tilleryd** [comment]
+1

**Comment by lidiaCirrone** [comment]
+1

**Comment by Northys** [comment]
+1 both

**Comment by pdefreitas** [comment]
+1

**Comment by milipili** [comment]
+1

**Comment by tjbenneche** [comment]
+1 just switched to Gitlab at work

**Comment by qldocao** [comment]
+1

**Comment by DiegoCoronel** [comment]
+1

**Comment by suchitpuri** [comment]
+1

**Comment by goocastro** [comment]
+1

**Comment by marker68** [comment]
+1

**Comment by hamway** [comment]
+1

**Comment by huymaile1991** [comment]
+1

**Comment by jwebcat** [comment]
+1
 please oh pretty please

**Comment by rifotu** [comment]
+1

**Comment by mccool** [comment]
+1 use it for work

**Comment by Thanood** [comment]
+1

**Comment by giraudvalentin** [comment]
+1

**Comment by niklassletteland** [comment]
+1 switching to gitlab for a work project

**Comment by JperF** [comment]
+1 we use gitlab for work repos!

**Comment by subicura** [comment]
:+1:

**Comment by ET-Bent** [comment]
+1

**Comment by Desnouck** [comment]
+1

**Comment by pnull** [comment]
+1

**Comment by dannoso** [comment]
+1

**Comment by Ziul** [comment]
+1

**Comment by lfarkas** [comment]
+1

**Comment by tholum** [comment]
+1

**Comment by MCoLoL** [comment]
+1

**Comment by petrnemec** [comment]
+1

**Comment by derekperkins** [comment]
+1 We use it for work

**Comment by briancooper** [comment]
+1

**Comment by kendrikat** [comment]
+1 (both)

**Comment by blueknightone** [comment]
+1 (Both work and personal)

**Comment by Armageddonas** [comment]
+1 (both)

**Comment by lilfaf** [comment]
+1

**Comment by nicolas-bastien** [comment]
:+1:

**Comment by briggleman** [comment]
+1 MILLION.  Make it happen ZenHub.

**Comment by Mebius973** [comment]
+1 Would be very useful at work as well as for personnal projects

**Comment by hwinkel** [comment]
:+1:

**Comment by phuong3030** [comment]
+1

**Comment by mostafahussein** [comment]
For all, please use the voting system which added by Github at the main question of this issue so the developers will know the number of votes easily instead of commenting with +1 or any similar comment.

**Comment by Soufien** [comment]
+1

**Comment by Sergiodfdez** [comment]
+1 we use it at work too

**Comment by liorkesos** [comment]
+1

**Comment by hondak** [comment]
:+1:

**Comment by bcooney** [comment]
+1 would love to be able to host my own gitlab and use zenhub in the browser.

**Comment by liorkesos** [comment]
A reminder to all the feature supporters . Vote at the top od the issue.
Lior

**Comment by vongosling** [comment]
+1,great work,if can support gitlab. according to the information I have,some companies using Gitlab Community Edition as the open source software to collaborate on code  inside their company

**Comment by cage1016** [comment]
+1

**Comment by okuyiga** [comment]
+1

**Comment by mayurp** [comment]
+1

**Comment by cdnewbee** [comment]
+1

**Comment by psychaos303** [comment]
+1

**Comment by nanernunes** [comment]
+1

**Comment by jesusabarca** [comment]
+1

**Comment by voidsteed** [comment]
+1

**Comment by thalesfsp** [comment]
Two years... and who cares? "Needs Votes"?  LoL

**Comment by vadimjustus** [comment]
+1

**Comment by ze-phyr-us** [comment]
Guys, can you please stop the comment spam and vote by clicking the thumbs up at the top of the issue? Thank you.

![screen shot 2016-05-16 at 5 03 56 pm](https://cloud.githubusercontent.com/assets/4436927/15285156/35229c3a-1b88-11e6-9dc8-4b1927f3b4c4.png)

**Comment by lesio** [comment]
+1

**Comment by leonardoherbert** [comment]
+1

**Comment by pauloFernandes** [comment]
👍

**Comment by alex-ception** [comment]
:+1:

**Comment by snroki** [comment]
+1

**Comment by guillemcanal** [comment]
+1

**Comment by eko** [comment]
👍

**Comment by Pouzor** [comment]
+1

**Comment by bdefore** [comment]
plz! +1

**Comment by zckrs** [comment]
https://twitter.com/gitlab/status/767775719422300161


Yesterday Gitlab release a issue board.

**Comment by ecasilla** [comment]
+1

**Comment by tstsogoo** [comment]
+1

**Comment by jaysoifer** [comment]
👍

**Comment by RBT-imie** [comment]
+1

**Comment by danielealbano** [comment]
+1

**Comment by jaffacake** [comment]
+1

**Comment by dusta** [comment]
+1

**Comment by vbogretsov** [comment]
+1

**Comment by hezamu** [comment]
+1

**Comment by ijbcatimpo** [comment]
+1

**Comment by ayr-ton** [comment]
+1 =x

**Comment by petrosp** [comment]
+2

**Comment by rafaellemes** [comment]
+1

**Comment by thatch45** [comment]
+1

**Comment by azenMatt** [comment]
Lot's of +1's here :) 

In the interest of saving everyones notification system, the best way to show support for this issue is to subscribe for updates and use reactions in the opening comment to provide a 👍 

Having said that.... GitLab already supports ZenHub style functionality, so it seems unlikely at this point that we would port ZenHub to GitLab as GitLab already has issue boards. 

What am I missing that means you don't want to use the GitLab issue boards?

**Comment by mateusmarquezini** [comment]
+1

**Comment by mehdijjz** [comment]
+1

**Comment by AndreaPravato** [comment]
+1

**Comment by marcel12bell** [comment]
+1

**Comment by leszekbulawa** [comment]
+1

**Comment by dannoso** [comment]
@azenMatt Gitlab Issue board is very basilar. You can only tag your issues and not much more.
You don't have tag category so ie. you can't tell what is "difficulty" and "priority" at glance.
We need something more advanced here :)

**Comment by hedcler** [comment]
+1

**Comment by jtuchek** [comment]
+1

**Comment by joshgrib** [comment]
+1

**Comment by JaouherK** [comment]
+1

**Comment by ismaelgobernado** [comment]
+1

**Comment by junketjim** [comment]
@azenMatt to answer your question specifically about GitLab here are the things that GitLab boards don't appear to do at the moment (not comprehensive but as I think of them):
* You can't merge boards - so having a view across multiple project repositories isn't possible.
* The board menu is buried down in the issues pages - meaning there are too many steps to quickly see the board.
* There is no support for "epics" currently - which means we can't get a good view of a piece of work which may include several sub tickets across different projects / teams (this is related to the previous point). An example would be a security incident which resulted in tickets being raised on the different product teams)
* You can't prioritise cards by changing their position in the board
* You can't expand and collapse pipelines - seems a trivial feature but it's really useful
* There are no reports for board activities - for example, burndown charts or velocity charts. These are really useful if managing sprints
* ...and lots of other UX things that ZenHub has worked hard on getting right!

**Comment by bigcrowd** [comment]
+1

**Comment by rcarmonad** [comment]
+1 We still need this!

**Comment by sokardys** [comment]
+1

**Comment by limestreet** [comment]
+1

**Comment by clystian** [comment]
+1

**Comment by na0ya** [comment]
+1

**Comment by aurerua** [comment]
+1

**Comment by mateusmarquezini** [comment]
+1

**Comment by davidCarlos** [comment]
+1

**Comment by Poncho09** [comment]
+1

**Comment by auiog413** [comment]
+1

**Comment by sls-lnluksa** [comment]
+1

**Comment by Miail** [comment]
+1

**Comment by cactail** [comment]
+1

**Comment by kevinmichaelchen** [comment]
👍

**Comment by joshuairl** [comment]
+1

**Comment by thalesfsp** [comment]
3 years... lol. Also, GitLab has better built-in tools - unsubscribing.

**Comment by azenMatt** [comment]
> 3 years...

Good point @thalesfsp , we do have a ton of open feature requests in this repo that have been open a long time. This is a great example of a feature request that is both 1) Very big to implement 2) In a new direction for the product. 

This leads to it becoming stale as while it is something we would love to do... we just don't have the bandwidth to take on or commit to a date for. 

So, as expanding to GitLab is not currently part of ZenHubs strategy in the short-medium term, i'm going to close this issue. 

This doesn't rule out ZenHub supporting GitLab in the long-term but right now we are fully focused on creating the best experience possible for GitHub users.

**Comment by iam-merlin** [comment]
#sad 
Still +1

**Comment by LouisLoode** [comment]
+1

**Comment by IntegerMan** [comment]
GitLab support would be nice, but ultimately I found GitLab because I was disappointed with the clunkiness of adding a new issue via ZenHub at the moment. If GitLab support could be snappier than GitHub support for building new issues, it'd be worth it for sure, but it's probable that ZenHub missed its window to influence that market anyway and the rewards for venturing into that space are not worth the costs.

**Comment by rajiff** [comment]
+1

**Comment by alyssontkd** [comment]
+1

**Comment by iatanasov77** [comment]
+1

**Comment by lacostenycoder** [comment]
You might wanna reopen this since Microsoft is acquiring Github and many teams will be looking for alternatives.

**Comment by Guppster** [comment]
+1

**Comment by yka8247** [comment]
+1

**Comment by code-vagabond** [comment]
+1

**Comment by Chronocast** [comment]
+2. One of my former teammates who also used ZenHub migrated to GitLab as soon as the acquisition was announced and I followed shortly after.

**Comment by henry-hz** [comment]
+1

**Comment by maxatcn** [comment]
+1
