### ISSUE TITLE
Support changed usernames

### ISSUE THREAD

**Issue by moofive** [ZenHubIO/support#830]
I changed my username the other day and discovered that while tickets are correctly assigned to my new username and display as being assigned to it, they still show up in the kanban board only when I filter based on my old username.

For what it's worth when I clear the assignment for one of the affected tickets and then immediately reassign it to myself it shows up correctly.

**Comment by azenMatt** [comment]
Hi @moofive - let me take a look at this

**Comment by azenMatt** [comment]
would you be able to let me know your old username, and org name that is impacted by this?

**Comment by LilMinmax** [comment]
@azenMatt I created a new issue before I saw this. https://github.com/ZenHubIO/support/issues/1395

It has a workspace and usernames where you can see this behavior. sorry for the duplicate
