### ISSUE TITLE
operations on multiple cards

### ISSUE THREAD

**Issue by phil-homecu** [ZenHubIO/support#831]
there several features needed that allow operations on multiple cards
After selecting multiple cards:
- [ ] assign all to one person
- [ ] move to pipeline/close
- [ ] assign label
- [ ] assign to milestone/epic
- [ ] other?

**Comment by azenMatt** [comment]
Thanks @phil-homecu - this makes a lot of sense

**Comment by drenalin23** [comment]
Not sure if this belongs here - but haven't found a better related issue.  This seems to be similar.  I would like to select a pipeline (and all stories in it) and then either assign or de-assign a label.  This is somewhat similar to automatically assigning a label when a story moves into a pipeline (guessing this is a feature request somewhere - it is something that waffle.io does) - but I also want the follow on which is either to be able to manually or automatically remove a label when the story moves to another pipeline or closed.

As an example if I have a review column, would be nice to automatically add a 'needs review' tag.  Then when I move it to staging/deployed/done columns that tag should be automatically removed.  Being able to do this manually in the interim would be a good step.

**Comment by torkiljohnsen** [comment]
Absolutely agree with this. I want to finish an Epic now and all its remaining issues during the next sprint, so selecting many cards and assigning all to a milestone would be ideal.

**Comment by azenMatt** [comment]
This is now live via https://www.zenhub.com/blog/task-board-bulk-actions/ 👍
