### ISSUE TITLE
Unable to scroll within pipelines or scroll left to right

### ISSUE THREAD

**Issue by cgutekunst** [ZenHubIO/support#834]
We have been using ZenHub awhile now and love it, however starting this morning, I am unable to scroll within the pipelines or left to right. I tried deleting the extension and reloading but that did not help.  Any help would be appreciated.

thank you

**Comment by azenMatt** [comment]
Hi @cgutekunst - would you be able to update your version of chrome? 

I have heard a couple of instances of this when chrome is out of date - upgrading to the latest version should fix it? 

> We have been using ZenHub awhile now and love it

Thank you 😄

**Comment by cgutekunst** [comment]
OH WOW!  That was it.  Thank you so much.
