### ISSUE TITLE
Add GET request to retrieve all the events for all the issues from a repo

### ISSUE THREAD

**Issue by tdumitriu** [ZenHubIO/support#836]
The API includes a GET request to get the events for a certain issue: 
`{repo#}/issues/{issue#}/events`
Returning all the events for all the issues from a repo can be very useful for all kinds of statistical analysis. 
Can you add a new API GET request that looks like this:
`{repo#}/issues/events`
It should return all the events for all the issues for the given repo. If possible, the request should use paging in order to manage the data transfer volume.

**Comment by azenMatt** [comment]
Hi @tdumitriu - thanks for the request - moving this one over to our API repo 👍

**Comment by azenMatt** [comment]
Issue moved to [ZenHubIO/API #36](https://github.com/ZenHubIO/API/issues/36) via [**ZenHub**](https://www.zenhub.com/)
