### ISSUE TITLE
All boards expanding every time something changes.

### ISSUE THREAD

**Issue by aensley** [ZenHubIO/support#838]
I typically have 2 to 3 boards collapsed because they don't usually pertain directly to me.

I've noticed today that every time an update to the boards is pushed (issue moved between boards, reprioritized, closed, etc.), every board gets expanded.

Using ZenHub Chrome extension 2.21.1.

**Comment by azenMatt** [comment]
Hi @aensley - thank you for pointing this one out. I can replicate it. We will get this fixed asap

**Comment by azenMatt** [comment]
This is now fixed in v2.21.2 - please let me know if you have any problems!

**Comment by aensley** [comment]
My ZenHub extension updated to 2.21.4. The problem's gone. Thanks!
