### ISSUE TITLE
When the repo name is too big, the front-end breaks and a horizontal bar appears on each pipeline

### ISSUE THREAD

**Issue by miguelperez** [ZenHubIO/support#839]
This is kind of an annoying bug, since it breaks all the pipelines that have cards with long repo names.

<img width="273" alt="screen_shot_2016-07-25_at_10_42_08_am" src="https://cloud.githubusercontent.com/assets/141042/17107457/f177243e-5254-11e6-96d4-8379ccaab0c6.png">

Could it be possible that you guys implemented some truncating on project names, maybe adding ellipsis.

Thanks,

**Comment by azenMatt** [comment]
Hi @miguelperez - this is likely related to new updates we just pushed to the board, we will get this fixed.

**Comment by miguelperez** [comment]
Great, thanks @azenMatt!

**Comment by azenMatt** [comment]
This is fixed in v2.21.2 - please let me know if you have any problems!

**Comment by miguelperez** [comment]
Hi, 

I do not know if its a cache issue, but I am still seeing the board like that, even after many refreshes.

I will check later, if the problem persist I will let you know.

**Comment by azenMatt** [comment]
It can take a while for your browser to pick up the new version, can you check on your extension page to see if you have it?

**Comment by miguelperez** [comment]
I have currently 2.21.1.
I will wait until it updates. 
Thanks again,
