### ISSUE TITLE
Permissions to create a board

### ISSUE THREAD

**Issue by albfan** [ZenHubIO/support#84]
To create a board is needed to add issues feature to github, Am I right?

But when you get an error saying

> You don't have permissions to create a board

Could be rather puzzling, Maybe this is for something about collaborators, or the like, but zenhub should detect you can add this feature and suggest to do it

> Add issues feature to create a board

Or simply add it automatically

**Comment by kendramoroz** [comment]
👋 Doing some clean up of our community Board and closing this issue as it's quite outdated! If you have any further feedback about error handling, chat with us via support@zenhub.com or bumping this issue with a comment. We're always working on improving friendly messaging for error encounters 🎉
