### ISSUE TITLE
Chrome extension in Linux switches to board upon update

### ISSUE THREAD

**Issue by eaceaser** [ZenHubIO/support#840]
It seems that the Chrome extension in Linux will "automatically" switch users to the Board display when it updates in the background.

At best, this means that a user interacting with the issues list will swap back to the board immediately after manipulating an issue.

At worst, this means that all users using Linux will switch to the board view when anyone does ANYTHING that causes the board to update.

**Comment by azenMatt** [comment]
😱  We are on this one @eaceaser - we will have an update out ASAP

**Comment by azenMatt** [comment]
we just release 2.21.4 that has a fix for this! 

Il leave the issue open for anyone else having the problem before the update kicks in

**Comment by eaceaser** [comment]
you tha real mvp

thanks
