### ISSUE TITLE
+1 button placement

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#841]
The +1 button (`zh-paw-btn`) placement can be seen at the bottom right corner of the issues page. All buttons are placed there stacked on top of each other.

Example: https://github.com/ZenHubIO/support/issues?page=13&q=is%3Aissue+is%3Aopen

![2016-07-26 13_29_45-issues zenhubio_support](https://cloud.githubusercontent.com/assets/136959/17150653/dbb2fb28-5335-11e6-85f0-b9a3cc71ff0b.png)

(Chrome + Windows 10 64 bit)

**Comment by azenMatt** [comment]
Thanks @Mottie - we are taking a look at this now
