### ISSUE TITLE
Collapsed Pipelines Expanding Without Action

### ISSUE THREAD

**Issue by Ellisande** [ZenHubIO/support#842]
Since the latest update (where it looks like you moved to a primarily optimistic update model) the collapsed pipelines on my board will occasionally expand to one row for no apparent reason. I haven't seen it in action yet, so I can't tell if it was an issue being added to one of the closed pipelines that triggered it. It is extremely common now though that when I click back over to my board I have all the pipelines expanded though.

**Comment by azenMatt** [comment]
Hi @Ellisande - sorry to hear that - we will take a look now and see what could be causing it

**Comment by Ellisande** [comment]
I did see it happen earlier today, seemed to be a reaction to a colleague rearranging issues inside a pipeline

**Comment by Mottie** [comment]
This includes the "Show/Hide Closed Pipeline" toggle button state which is no longer saved.

**Comment by azenMatt** [comment]
Thanks @Mottie - we will take a look at that as well 

@Ellisande - a fix for this is coming up, we identified some cases that can cause it that are being fixed

**Comment by azenMatt** [comment]
this issue are now resolved :)
