### ISSUE TITLE
Question about the REST API - how to get a list of all issues?

### ISSUE THREAD

**Issue by jamesgilmoursimpson** [ZenHubIO/support#843]
Hi, 
Is there a way via the API to get a list of all issues for a repo? 

The ( hoped for ) response is that there is a way to collect all issues that have been modified between  2 dates.  i.e. "give me all issues modified between last Monday 9am and now".

The information we are hoping for in the response is the issue title, status, priority, estimate, assignee, and maybe component-name if that is captured.

Thanks!
Regards,
James

**Comment by azenMatt** [comment]
Hi @jamesgilmoursimpson 

This isn't current an endpoint that we have - i'm going to move this issue over to the API repo so we can track it there

**Comment by azenMatt** [comment]
Issue moved to [ZenHubIO/API #37](https://github.com/ZenHubIO/API/issues/37) via [**ZenHub**](https://www.zenhub.com/)
