### ISSUE TITLE
Burndown Chart for multiple milestones across multiple repos

### ISSUE THREAD

**Issue by bradynpoulsen** [ZenHubIO/support#845]
In the same way that you can view the issues/pull requests on a task board, it's pretty important for us to be able to view the burndown chart for those tasks.

I'm proposing for Burndown Charts to include multiple milestones from multiple repos

**Comment by azenMatt** [comment]
Hi @bradynpoulsen - this should already be working... 

If you have a milestone that has the same name / end date - it will show together on the task board. The same milestone should show together on the burndown chart as well - for example:

![image](https://cloud.githubusercontent.com/assets/7584089/17195032/6c75f360-5410-11e6-855f-54f8354f85e2.png)


For this to work, the repos need to be merged into the same board and the milestones must have matching data (we are working on something to make this less manual)

**Comment by bradynpoulsen** [comment]
@jasonmadrid @bradc77 @jjamminjim

**Comment by gvilarino** [comment]
Awesome stuff! @azenMatt is there an ETA on the 'less manual' approach?

**Comment by azenMatt** [comment]
> is there an ETA on the 'less manual' approach?

As a rough guesstimate ... sometime over the next 1-2 months for this. It is one of our higher priorities

**Comment by azenMatt** [comment]
please subscribe to - https://github.com/ZenHubIO/support/issues/597 - for updates on when this is available
