### ISSUE TITLE
Incorrect URL in issue/PR pop over windows of different source organization

### ISSUE THREAD

**Issue by drenalin23** [ZenHubIO/support#846]
When I have multiple repositories from multiple organizations in a Boards view - the pop over windows will have a base URL which uses the organization of the repository where the Board is being launched from.  

The attached screenshot shows that in the URL locator bar of my firefox browser the correct organization/repository is mmi-cookbooks/elasticsearch-chef - but in the popover window is shown as (and the link takes to a 404 as) racker/elasticsearch-chef when I am viewing this board from a starting point that isn't the Organization of the repository.

![screen shot 2016-07-27 at 5 09 22 pm](https://cloud.githubusercontent.com/assets/12398902/17196966/51b24e72-541d-11e6-8758-32669df2cf67.png)

**Comment by azenMatt** [comment]
Thanks for spotting this @drenalin23 - we are taking a look now

**Comment by drenalin23** [comment]
no problem.  I tested in Chrome and Firefox as additional testing notes.  message me if you need any help testing further.

**Comment by azenMatt** [comment]
hi @drenalin23 - this is now fixed, let me know if you have any issues!

**Comment by drenalin23** [comment]
Sweet!  @azenMatt Tested in Chrome on OS X and verified fixed on my end.
Thank you for the quick turnaround.
