### ISSUE TITLE
Enhancement: Integrate Zenhub shortcut keys into the GitHub shortcut keys help

### ISSUE THREAD

**Issue by junketjim** [ZenHubIO/support#847]
Pressing `?` on GitHub displays a contextualized shortcut key help page.
<img width="883" alt="screen shot 2016-07-28 at 11 19 19" src="https://cloud.githubusercontent.com/assets/2206147/17209505/35de3b6e-54b5-11e6-9944-2321b18cab93.png">
It would be great if the ZenHub keys were incorporated into this page (contextualized) and the expanded view contained all the ZenHub shortcut keys

**Comment by kendramoroz** [comment]
Hey @junketjim we've just launched a suite of new Keyboard shortcuts! 

You can review the full list here: https://www.zenhub.com/guides/keyboard-shortcuts
As well as access shortcuts at anytime by heading to the `Settings` dropdown on the Board (or hitting `z` `s` in the web app)

![screen shot 2017-10-13 at 4 20 51 pm](https://user-images.githubusercontent.com/11036230/31569809-cb309c1e-b032-11e7-89a0-47565dc1221d.png)

Let us know what you think!
