### ISSUE TITLE
Issues with multiple assignees shouldn't require all assignees to be selected for it to display on the boards page

### ISSUE THREAD

**Issue by DSh3p4rd** [ZenHubIO/support#849]
The problem is when viewing the boards page and only my user is selected, only the issues I am solely assigned to display. I don't believe you should have to select all users assigned to an issue to view it on the boards page.

**Comment by azenMatt** [comment]
Hi @DSh3p4rd - I agree this shouldn't be how the board behaves... 

I just tried to replicate but when I filter by assignee, it does show me issues that I am assigned to along with someone else. 

For example, on this repo - https://github.com/ZenHubIO/support/issues#boards?repos=13550592&assignees=azenMatt

Issues assigned to, also shows this issue where Aaron is assigned as well:

![image](https://cloud.githubusercontent.com/assets/7584089/17257380/b190079e-5576-11e6-9c0a-4fff384eaa76.png)

Is this not how it works for you?
