### ISSUE TITLE
Aggregated organization view

### ISSUE THREAD

**Issue by slajax** [ZenHubIO/support#85]
We work in across a large number of repos and working within each specific repo to do task planning is nice if it's an active repo or has multiple users. However it would be really nice if there was a organization level view of the Zen Hub board that allowed business owners to manage tasks across repos at the organization level.

**Comment by posabsolute** [comment]
Have some news? 
we are a small team here that work on multiple repos in a sprint, very hard for us to use zenhub with each repo separately organizing a sprint

**Comment by azenMatt** [comment]
> Have some news?

All I can share at this point is that the issue is in the 'In Progress' column of our ZenHub board. 

More news coming soon :)

**Comment by jorisnoo** [comment]
Please share the news as soon as there will be some – we'd also love to use zenhub if this was possible!

**Comment by cristinasantamarina** [comment]
Hi there! This feature would be very useful - do you have an idea of when this will be made available?

**Comment by posabsolute** [comment]
PING! been more than a month!

**Comment by tjconnelly** [comment]
started a 30 day trial today; given this feature, will eagerly become a paid customer. thanks @roham @azenMatt @aupright

**Comment by azenMatt** [comment]
thanks for the kind words @tjconnelly :) 

@posabsolute and everyone else waiting for this... it is still out highest priority and we are aiming to have this in your hands for the end of Q1 

Without wanting to bore you all with implementation details, we have had to make a number of changes to our data structure to be able to provide this functionality. Which unfortunately means it has taken longer than anticipated, but on the positive side, when released it is going to make all the boards lightning fast :zap: 

more updates on the way!

**Comment by ziadsawalha** [comment]
+1 and to make sure the request is clearly documented, we'd like the ability to include _**multiple repos from multiple orgs/users into one board**_. That's because we have a number of teams who each need a board to track their work, and each team works on a selection of projects from a number of orgs.

**Comment by SPopenko** [comment]
@azenMatt I wish I could help with implementation of this great feature but it's impossible to do with my iOS tech stack :) So, just thanks for great product and for working at this great extension!  Let us know if you need help with beta testing.

**Comment by devinus** [comment]
I can't switch to ZenHub until this feature is ready. Waffle.io and HuBoard both support this feature, but I really like ZenHub a lot.

**Comment by aupright** [comment]
Hi @devinus, @SPopenko and @ziadsawalha  - still great to see all the support coming in for this feature! 

We're closer than we've ever been to launching this one and are beginning to switch our focus towards heavy testing. @azenMatt and I both know how eager everyone here is to see this land, so we'll make sure to spread the word as soon as we release!

Thanks again for all the support everyone :beers:

**Comment by mycue1981** [comment]
I also would rather use Zenhub then waffel or huboard. will be paying customer again when I can view multiple repos in one board.

**Comment by azenMatt** [comment]
![image](https://cloud.githubusercontent.com/assets/7584089/7395398/7c00fe0c-ee4e-11e4-844a-fa684a8f7ca6.png)


The ZenHub team are all **very** excited to announce that we are now live with this feature!


The chrome store should be pushing the update through to you at the moment, but if not, you can force an upgrade check via chrome://extensions in developer mode. The feature is in version 2.0.0 and up.

The ability to link existing board together will now appear as a new filter at the top of each board. We have put together a short blog post here - https://www.zenhub.io/blog/multi-repo-boards-have-arrived/ - to help everyone get started. 

I'l keep this issue open for a couple of days incase anyone has any questions or feedback

Enjoy!

**Comment by ziadsawalha** [comment]
@azenMatt In the drop down I can only see repos from the current org I am in. Can I merge repos from other orgs?
