### ISSUE TITLE
Bug: after you "clear assignees" and close issue it jumps to the issue view instead of back to board

### ISSUE THREAD

**Issue by stephenakearns** [ZenHubIO/support#854]
When you clear assignees... 

![image](https://cloud.githubusercontent.com/assets/13372164/17424126/e25c41ae-5a8e-11e6-86a6-d5af054b4f89.png)

Then close the issue by clicking the "X" in the top-right corner of the modal, you expect it to go back to the board view, but for some reason, it jumps into the detailed issue view.

**Comment by azenMatt** [comment]
Hi @stephenakearns - this is a GitHub bug, for more info you can see - https://github.com/ZenHubIO/support/issues/825

I have reached out to GH support and am waiting on a timeline as to if this is going to get fixed... If they are unwilling to fix then we will support a work around. Il keep the updates coming in #825
