### ISSUE TITLE
Burndown issue count is wrong

### ISSUE THREAD

**Issue by bdubaut** [ZenHubIO/support#855]
I noticed this a few weeks ago, but sometimes the Burndown chart counts appear to be wrong:
on the screenshot below you will see:
- The total story points is **8**
- If you add the points of each issues, the total is actually **22**

![screen shot 2016-08-05 at 11 25 48](https://cloud.githubusercontent.com/assets/798319/17432471/c03bcb3c-5aff-11e6-9056-14554351e755.png)

Are we doing something wrong? Or is there a way to fix this?
Thanks a lot.

**Comment by azenMatt** [comment]
Hi @bdubaut 

Would you be able to confirm if all of these issues were closed in the period between Jul 25th - Jul 29th? 

The list will show all issues in the milestone, but the chart will only show data for issues captured between the start and due date

**Comment by bdubaut** [comment]
Hi @azenMatt 
It looks like it's fine now. I think you can close this, I will re-open if it behaves again.

**Comment by azenMatt** [comment]
great - thanks for confirming!
