### ISSUE TITLE
Introduce a possibility to filter issues by using OR condition

### ISSUE THREAD

**Issue by toukoeramaja** [ZenHubIO/support#856]
Currently we filter issues with using only AND conditions. However this doesn't always allow us to filter relevant issues effectively. Sometimes defining priorities between different areas would require more advanced filtering, i.e. being able to filter issues that for example have a Label "Frontend" AND either "Bug" OR "Enhancement".

**Comment by azenMatt** [comment]
Hi @toukoeramaja  - this one is confirmed for inclusion in the next couple of sprints - you can follow along here - https://github.com/ZenHubIO/support/issues/68

it should be live over the next month
