### ISSUE TITLE
How do we remove a board

### ISSUE THREAD

**Issue by ghost** [ZenHubIO/support#86]
OK, had a play and love it, but I want to change the columns and start again.

How do I remove the current board I have?

**Comment by bsipocz** [comment]
It seems that deleting workspaces is still not possible. Would you please consider it as a feature? As others above I was experimenting with new workspaces and created ones for repos that don't need one, but now those are stuck with me. It makes no sense whatsoever to repurpose those, and even with renaming, etc, the name of the original repo stays in the link for the workspace.
