### ISSUE TITLE
OR filter in ZenHub Boards

### ISSUE THREAD

**Issue by sahiltalwar88** [ZenHubIO/support#865]
For some reason, ZenHub currently treats multiple selections as `AND` - meaning, it only shows items that have _both_ selections. For example, if I have two labels - `A` and `B` - if I select both in ZenHub, it'll only show me items that have both labels. 

To me, this is the opposite of what should be happening - it should show _all_ labels that have _either_ of them (it should OR them together). That's the more common and natural use case, in my opinion; and has been a daily cause of frustration at our company for the past few months. 

Could you please add a means to switch between the type of filtering, or as a short term fix, change the default to `OR`?

**Comment by azenMatt** [comment]
Hi @sahiltalwar88 

> it should show all labels that have either of them (it should OR them together)

Thank you for your thoughts here - I agree that in some situations an OR would make the most sense.... the trouble is in the other 50% an AND does... 

We have a change being worked on at the moment to include NOT filtering in the dropdowns, once that is live and we have had a chance to get some feedback on it, if it works well we will look to use the same method for OR filtering

**Comment by sahiltalwar88** [comment]
@azenMatt - thanks for the reply! That sounds great - any idea what the timeline for that would be?

**Comment by azenMatt** [comment]
Let me loop back on that once we have the NOT filter live as that should give us a good idea of the complexity!

**Comment by bradical** [comment]
Reiterating desire for this. `not:` is great. Would really love an "OR". Good example for us: I want to review all issues on our Board that are "Customer Requested", "Regressions", "Blocker", or "Major".

**Comment by bradical** [comment]
Reiterating desire for this. `not:` is great. Would really love an "OR". Good example for us: I want to review all issues on our Board that are "Feature" or "Improvement".

**Comment by rnarian** [comment]
Any update on this?

**Comment by mrengy** [comment]
I'm particularly interested in the ability to switch between "and" and "or". Please keep me posted.

**Comment by Thorien** [comment]
My team has ran into similar problems with labels. Or for labels would be great.

**Comment by kendramoroz** [comment]
👋 We're super excited to announce that `or` filtering is coming VERY soon. We're almost done development on this. We're going to be introducing the ability to switch between `any` and `all` filtering, across all filters.

**Comment by bradical** [comment]
YAY!

**Comment by kendramoroz** [comment]
Any/All filtering is in the wild 🐯 🌴 ! Now, with any filter combination you can toggle between filtering for results that match `all` filters, or `any` filters. 

Let us know if you have any questions or combinations you need help with! 

![image](https://user-images.githubusercontent.com/11036230/44823421-2f8cff80-abb5-11e8-9104-91f92efa950e.png)

**Comment by rnarian** [comment]
🎉🍾

Though it's nice that it's out now, I don't think it's particular useful. 😭

At least in our case. Although I can now view all issues matching any of the selected labels I can't narrow it down to only show the ones I am assigned to.

Is there anything planned to make the filter even more customizable?

In my mind I would need to be able to also set AND/OR between the different option groups. So I can set it up like this:

```
(filter:a OR filter:b) AND assignee:name
```

**Comment by bradical** [comment]
Excited about this but either I'm not quite understanding or it' not working 100%. Here's a filter for "bugs" or "tasks" that's showing things that aren't either. Let me know if you'd like me to give you more details somewhere.

![filtering](https://user-images.githubusercontent.com/191132/44851866-b1217380-ac2f-11e8-8f14-32b9922fd99b.png)

**Comment by kendramoroz** [comment]
@rnarian great enhancement suggestion! I've copied over your comment here to track this separately so it doesn't get lost when this one gets closed: https://github.com/ZenHubIO/support/issues/1499

---
@bradical thanks for reporting!

Based on your filter, the far left Issue matches the `bug` label, but the others in the Icebox do not seem to match. Mind booking a quick 15 minutes with me here: https://calendly.com/zenhub/quick-chat to debug what's going on?

**Comment by bradical** [comment]
Hi @kendramoroz, I've provided more details here too: https://github.com/ZenHubIO/support/issues/1497 in case that helps.
