### ISSUE TITLE
No warning when changing org wide repo pipelines

### ISSUE THREAD

**Issue by marcusmotill** [ZenHubIO/support#868]
Today I changed our support repo pipelines... without warning the change effected every repo thus un-organizing hundreds of issues.  

Our founder decided to leave zenhub for JIRA shortly thereafter.   I can't say I blame him because we cannot have external software that is supposed to make us more efficient cost us days of work.     Hope this gets resolved to save teams in the future. 

✌️ out

**Comment by azenMatt** [comment]
Hi @marcusmotill - thank you for the heads up with this, the warning message for this change is working it's way through review right now and will be live today

**Comment by azenMatt** [comment]
Hi Marcus - as per out email conversation, apologies again for this impact on your workflow. 

We just release our latest version 2.23.19 that brings back the warning message here
