### ISSUE TITLE
Ability to have default 'labels' for every repo

### ISSUE THREAD

**Issue by sanchexx** [ZenHubIO/support#869]
Right now, every time we create a new repository, we need to setup the labels to have all the options we need (bug, enhancement, critical, etc.). As an agency who creates a lot of repository, it's really annoying and we often end up with different patterns on different repositories.

It would be great to have an option to configure your prefer labels and have every new repository use these

**Comment by azenMatt** [comment]
Hi @sanchexx - I feel your pain on this one :) 

One thing we are looking to do here is #298 to allow you to sync your labels across a multiple repository board. 

For new repo creation, I think this would be best as a GitHub feature as the default set of labels is long over due an overhaul!
