### ISSUE TITLE
Board doesn't remember Milestone

### ISSUE THREAD

**Issue by jdubhub** [ZenHubIO/support#87]
ZH used to remember the milestone when the board was loaded. It has stopped doing that in recent weeks.

Thanks

**Comment by Mottie** [comment]
This might be related, but if I click on the "View closed issues" link in the header, it does not include any of my set labels, milestone nor assignee. The link always shows `issues?state=closed`.

**Comment by azenMatt** [comment]
Thats correct @Mottie - we just pass you onto the GitHub closed issue page when you hit that button. 

Some nice improvements to the closed issue experience coming soon!

**Comment by nickbuddendotcom** [comment]
+1

**Comment by adamreisnz** [comment]
I think the issue I raised (https://github.com/ZenHubIO/support/issues/972) is related to this one.

**Comment by kendramoroz** [comment]
👋  Doing some clean up of our community Board and as this is quite outdated, we've decided to close out this Issue as we continue to focus on core workflow experiences around Boards and Reports. We'll be sure to keep our eye on community support for Board Improvements and if this one pops up we'll keep everyone updated!
