### ISSUE TITLE
"Filter by this Epic" Usability

### ISSUE THREAD

**Issue by sburns** [ZenHubIO/support#870]
In Board, when I want to find issues within a certain epic, I'll often filter for the 'Epic' label and then click the "filter by this epic" for my Epic of interest. But because I still have the 'Epic' label filter, nothing shows up because my children issues aren't labeled with 'Epic' (nor should they be) so I have to then remove the 'Epic' filter before seeing anything.

It might be helpful to remove the "Epic" label filter when the "filter by this epic" button is clicked. Or there's a better way to find Epic issues?

Regardless, :heart: ZenHub, thanks for your work :)

**Comment by azenMatt** [comment]
Hi @sburns - agreed, we actually used to do this but it must have been missed in the board refactor. 

We will add this back in

**Comment by georgec-s** [comment]
@azenMatt - while you're at it, I'm seeing people create Epics of Epics (!), in that case, would it be possible to (optionally) view "grandchildren" in addition to the children?

**Comment by cbeams** [comment]
I've just added #895, which looks related to this issue.

**Comment by azenMatt** [comment]
Hi @sburns - this is now back in!

When filtering on an epic, the epic label will be automatically removed. 

@georgec-s - we will take a look at better sub-nesting of epics. i've created a separate issue for that (#903)

@cbeams - that does look like a bug related to this, i'l reply now in #895
