### ISSUE TITLE
Bulk move of issues and Reprioritizing in pipeline via side bar are broken

### ISSUE THREAD

**Issue by porta-antiporta** [ZenHubIO/support#871]
Since starting to use Zenhub a few months ago there are a few features that seem to be missing now.

1. Bulk move of issues.  When I hover over an issue in the board view and the gear (settings) icon appears.  However, the option `Select Multiple` is no longer there.  https://github.com/ZenHubIO/support/issues/118#issuecomment-171177930

1. Reprioritizing Pipeline issue via sidebar (as part of 2.18.8 release) is also no longer visible.  I can set the pipeline while viewing an issue, but can't send it to the top or bottom anymore.

**Comment by azenMatt** [comment]
Hi @porta-antiporta 

For 1) you can track the progress of bringing this back in #832 

For 2) we removed this as it wasn't working well, we are working on better ways to communicate priority that will help replace this
