### ISSUE TITLE
Pipelines

### ISSUE THREAD

**Issue by wellingk** [ZenHubIO/support#872]
Is there a way to make a pull request appear within a specific Zenhub pipeline?  i.e. I have created a pipeline called "Code Review", and I would like them to appear in there without having to choose the pipeline manually.

**Comment by azenMatt** [comment]
Hi @wellingk - we recently put the following live - https://github.com/ZenHubIO/support/issues/142#issuecomment-238709317

Which allows you to select a default pipeline for all PRs to go into when created -

![image](https://cloud.githubusercontent.com/assets/7584089/18331172/c6f663b6-7511-11e6-8068-f0ede0aaa3dc.png)

You should be able to select code review here and have all PRs automatically get added into that area. 

Let me know if you have any questions on how to get this working!
