### ISSUE TITLE
Order labels in label selector/filter by color

### ISSUE THREAD

**Issue by torkiljohnsen** [ZenHubIO/support#875]
Would be great to have a manual order on labels or to just order them by color code. Especially useful if one is following your suggestion from [your book](https://www.zenhub.com/book/github-project-management) on label organizing.

That way, the label dropdown/selector could actually list labels grouped by type too, if color = type in your label style guide.

So while this looks good and well-organized in theory…
![skjermbilde 2016-08-29 kl 15 05 49](https://cloud.githubusercontent.com/assets/318089/18052347/224f1196-6dfa-11e6-9a03-bfa400eea5ee.png)

… in reality, labels are organized alphabetically when being used:
![skjermbilde 2016-08-29 kl 15 03 47](https://cloud.githubusercontent.com/assets/318089/18052309/e5a59fe4-6df9-11e6-939d-f15c086fb72a.png)

**Comment by akruijff** [comment]
When writing tickets I personally look more at the words and there for prefer the current setup. For me color comes in to play when looking at the board and allows me to quickly identify the type of issue.

**Comment by azenMatt** [comment]
Hi @torkiljohnsen - adding this on into the discussion section to get some 👍 / 👎  on how useful this would be fore everyone. In general we like to keep GH features 'as-is' and the order of the label drop down is directly governed by GitHub labels. But i'm happy to explore if it has lots of support :)
