### ISSUE TITLE
Drop targets on dragging have stopped working

### ISSUE THREAD

**Issue by jwpeddle** [ZenHubIO/support#876]
As of maybe two weeks ago, I can no longer drag issues to reorder them or switch pipelines. I can drag the issue, but no hot spots appear for dropping. Releasing the mouse button simply returns the issue to where it came from.

Chrome, Linux, Version 52.0.2743.116 (64-bit)
No javascript errors.

Issue doesn't seem to be affecting my coworkers, and I'm assuming from the lack of open issue, it's not affecting most people. I'm happy to provide any debugging. It's currently impossible for me to reorder issues.

**Comment by jwpeddle** [comment]
With no change in my browser or behaviour, I do not appear to be affected by this bug today :confused:

**Comment by azenMatt** [comment]
Hi @jwpeddle - thank you for the update here. We were unable to replicate at all on ourside... please let me know if it starts happening to you again!
