### ISSUE TITLE
Can't see pipeline and label options

### ISSUE THREAD

**Issue by johnaowen** [ZenHubIO/support#877]
Recently for one of the projects on our dedicated GHE service, Zenhub is no longer displaying the contents of the Pipeline or Labels dropdowns.  Both remain empty, although other users who are using the repository can see the options as expected.  This means I can't use the Boards tab to move issues between pipelines and can't associate label(s) with issues.  If other people try this they don't have any problems, e.g. for example moving a new issue to the in progress lane works for them but whilst graphically it looks like it has worked for me the associated state change doesn't happen.  So in this case other users will still see the issue as a New issue.

* I've cleared my browser cache,
* I've reinstalled the ZenHub extension

Neither of these have changed the situation.  

Note in the other GHE respositories I can access the pipeline and labels dropdowns display the options available as expected.

**Comment by azenMatt** [comment]
Hi @johnaowen  - apologies for the late reply here. 

For Enterprise support - can you send me an email to enterprise@zenhub.com and we will get this resolved for you ASAP

**Comment by johnaowen** [comment]
Thank you for your reply @azenMatt, I've sent an email as requested.
