### ISSUE TITLE
Error while opening TODO list

### ISSUE THREAD

**Issue by erickpintor** [ZenHubIO/support#878]
![image](https://cloud.githubusercontent.com/assets/813042/18212357/37531e4e-7119-11e6-9046-962051e4b869.png)

**Comment by erickpintor** [comment]
No sure what do you need to track down this bug. I just see this message while opening the todo list.

Hit me up if you need anything.

I'm using zenhub on my mac book on google chrome.

**Comment by dopplershift** [comment]
Dragging and dropping issues no longer works for me, and I see this message in the javascript console as well. Also on osx + chrome.

**Comment by azenMatt** [comment]
Moving this one through to In Progress. We are looking at this and the other issues in #879

**Comment by azenMatt** [comment]
This is fixed in version 2.23.34 :)
