### ISSUE TITLE
ToDo does no longer archive ticked item

### ISSUE THREAD

**Issue by pattacini** [ZenHubIO/support#879]
Hi all,

First off, thanks for your great job in providing us with such nice tools :smiley: 

I've recently noticed that when I enter the `ToDo` section, the first screenshot I'm presented with is the one below:

![capture](https://cloud.githubusercontent.com/assets/3738070/18223648/2de697fa-71be-11e6-909e-caaac2813c4d.PNG)

while in the past I could see the **Inbox list selected** with all my issues.

More importantly, if now I tick out an item in the Inbox, this item gets correctly removed from the list. However, upon my subsequent visit of the Inbox the same item is still there.
Unfortunately, this misbehavior makes the whole `ToDo` unusable.

Clearing browsing data entirely within Chrome did not help.

---
My system is a `Windows 10 1607 (14393.105)` with `Chrome 53.0.2785.89 m`.

**Comment by pattacini** [comment]
One more actions I'm not able to perform is to **drag an item** to change its position in the list or to move it in a different list

**Comment by zachumo** [comment]
We're having the same issues, todo is broken. 

- Fails to load most of the time.
- Drag and drop not working.

![image](https://cloud.githubusercontent.com/assets/6388197/18252280/1586ee0e-738e-11e6-803f-066fead78055.png)

**Comment by pattacini** [comment]
#878 is of the same kind.

**Comment by azenMatt** [comment]
Hi @pattacini @zachumo - I can recreate all three of these issues 

- [ ] Loading problems 
- [ ] Drag and drop
- [ ] Issues not completing 

We will take a look and get these resolved

**Comment by maartenwodan** [comment]
Same issues here, tested in Chromium, Chrome, and Firefox.

**Comment by pattacini** [comment]
Thanks @azenMatt 
I can confirm it's now working.
