### ISSUE TITLE
Track ZenHub activity for a single issue

### ISSUE THREAD

**Issue by KathleenLD** [ZenHubIO/support#88]
I'm really enjoying using Zenhub, but one thing I'd love is to somehow be able to view an issue's history within ZenHub. It would be really awesome if this could show up in the timeline along with comments and mentions in other issues, but even if I could somehow see its history in the browser dropdown, that would be awesome too. I just want to know who changed what, and when.

**Comment by azenMatt** [comment]
![image](https://cloud.githubusercontent.com/assets/7584089/12185341/4292847e-b54f-11e5-9c7b-006b51529816.png)

Now live in v 2.14.2 :grinning: 

At the moment, this requires a page refresh - but we will be making it real time (as labels are) as our next step. 

Any feedback - please let me know!
