### ISSUE TITLE
Filter is not working for some assignees

### ISSUE THREAD

**Issue by bunyk** [ZenHubIO/support#880]
We have issue, which clearly says that volodya-buryy is assigned to it:

![image](https://cloud.githubusercontent.com/assets/244042/18278543/2bd8a012-745b-11e6-9703-6230396e1cac.png)

But that issue is not displayed on boards when filtered by assignee:

![image](https://cloud.githubusercontent.com/assets/244042/18278600/6c59c8be-745b-11e6-8955-012ce4a5ca3b.png)

**Comment by roman-curse** [comment]
Well on my account I've got the same issue

**Comment by azenMatt** [comment]
Hi @bunyk  @roman-curse  - would you be able to email support@zenHub.com with this issue and we will get it sorted. Thanks!
