### ISSUE TITLE
Help link in the zenhub dropdown has an outdated target

### ISSUE THREAD

**Issue by stof** [ZenHubIO/support#884]
On firefox the Help link in the ZenHub dropdown points to https://github.com/axiomzen/zenhub-now/issues#board
This redirects to this support repo, so it is not a critical issue, but it would be better to have the right link directly

**Comment by azenMatt** [comment]
Thanks for reporting this @stof

**Comment by devinmcinnis** [comment]
We have updated this in the latest extension. 

It now points toward out support site: https://help.zenhub.com
