### ISSUE TITLE
Can't modify Epic (undefinedundefined)

### ISSUE THREAD

**Issue by Gabriel-p** [ZenHubIO/support#885]
When I click the `Add or modify issues in this epic` button, I get this:

![captura de pantalla de 2016-09-07 15 26 16](https://cloud.githubusercontent.com/assets/6054951/18323788/8ba7171c-750f-11e6-97cd-b737d5ce7254.png)

What is going on here?

elementary Freya 64-bit + Chrome v53.0.2785.89 (64-bit)

**Comment by NoopDog** [comment]
I also get this trying to create an epic. Using chrome on a mac.

**Comment by azenMatt** [comment]
Hi @Gabriel-p @NoopDog - it looks like this is a bug on the latest version - we are on it

**Comment by azenMatt** [comment]
ok and we are fixed :) 

if you can manually update to v2.23.33 this should be back working 👍
