### ISSUE TITLE
Create an Epic is broken right now.  Takes you to a weird page with "undefined" 

### ISSUE THREAD

**Issue by bmgallant** [ZenHubIO/support#887]
I've been trying to add a new epic to our boards all day.  

Steps to reproduce: 
1. Click "New Issue" in top right. 
2. Type in the title
3. Click "Create Epic" purple button.

This is what I see: 

![targetprocess-screen-capture 77](https://cloud.githubusercontent.com/assets/16417356/18396006/fffb6a0a-7686-11e6-8394-a02361a2bf4b.png)

**Comment by azenMatt** [comment]
Hi @bmgallant - which version number are you on? 

We shipped a fix for this on Wednesday so you might need to force your browser to upgrade? anything about 2.23.33, this should be fixed

**Comment by bmgallant** [comment]
Ours is 2.23.30 so I'm updating the extension and will try again.

**Comment by bmgallant** [comment]
Fixed!  It was a little strange.  Initially I tried to just go to the list of extensions in Chrome and click the "update extensions" button but it wouldn't work.  

Eventually I had to remove the ZenHub extension and then update Chrome, then relaunch and then re-install Zenhub.  I'm on 2.23.34 now.

**Comment by azenMatt** [comment]
strange - chrome can be a little strange when trying to manually update - I often find that the update button responds well to being spammed with clicks :) 

Glad this is working for you now, let me know if there is anything else I can help with!
