### ISSUE TITLE
Critical Bug: Unable to create Epics

### ISSUE THREAD

**Issue by porta-antiporta** [ZenHubIO/support#888]
When I look to create an epic in my repo I get the following error: 

![image](https://cloud.githubusercontent.com/assets/16668007/18403964/5d2d0636-76ad-11e6-830e-ba6673065838.png)

**Comment by porta-antiporta** [comment]
Few more notes after looking at a few things:

1. This happens in Chrome (Windows machine).  Firefox looks like its working
2. Workaround is to create the issue, then use the "Move to an epic" under the Epics drop down on the right nav.  (not very intuitive by the way)

**Comment by azenMatt** [comment]
Hi @porta-antiporta - can you try and update your extension, it should fix this as we pushed out an update earlier in the week. 

Anything above 2.23.33 and you should be good here!

**Comment by porta-antiporta** [comment]
Thanks!  that worked. closing
