### ISSUE TITLE
Bug: Creating an epic - description not forwarded when in preview

### ISSUE THREAD

**Issue by giladg4** [ZenHubIO/support#889]
To recreate:
1) Create a new issue in your repository
2) Add some content in the description field
3) Change to 'Preview' mode in the editor
4) Click on 'Create an Epic'
In the new form click on the comments - the field is empty. This does not occur when creating an epic while in 'Write' mode

**Comment by azenMatt** [comment]
well spotted @giladg4! 

we will get this one fixed, apologies if you lost comments when you found out about this one 😬

**Comment by azenMatt** [comment]
Hi @giladg4 - this has just been fixed in version 2.24.18 🙌
