### ISSUE TITLE
can't drag issues on ToDo page from Inbox to lists

### ISSUE THREAD

**Issue by mcbouslog** [ZenHubIO/support#891]
Can't drag issues on ToDo page from Inbox to lists.

ToDo page works fine on Firefox.

Chrome Version 53.0.2785.101.

**Comment by azenMatt** [comment]
Hi @mcbouslog - which version of ZenHub are you on? 

You might need to force a manual update, we fixed a bug connected to this recently. 

If it is still happening on the latest version let me know and we will investigate further!

**Comment by mcbouslog** [comment]
Manual update worked, thanks! Big fan of the product, keep up the great work. =)
