### ISSUE TITLE
Be able to see what epic an issue belongs to

### ISSUE THREAD

**Issue by noahmanger** [ZenHubIO/support#893]
As a product manager, I want to be able to see which epic an issue belongs to on the issue card itself so that I can understand which issues are not in epics and visually gauge the progress of epic issues without having to filter.

I searched through the issues and didn't find a similar request, so apologies if this is a duplicate. I love the styling of the Milestone label on issues and think a similar treatment would work well for Epics. 

IMO, along with the request here https://github.com/ZenHubIO/support/issues/693 would make epics way more usable and useful.

**Comment by azenMatt** [comment]
I agree with you here @noahmanger - this is one of a number of issues along with #693 that I would like to prioritize into a 'epics' sprint to update a whole bunch of the functionality related to epics.  (I will start collating all these issues on here over the next few weeks so everyone can see the changes) 

We were thinking of including a 'sub-task' label for issues in Epics, but that wouldn't include the meta-data for which particular epic it was in. 

We will play around with some different ideas here and find something that works. 

At a high level, it sounds like we need to: 

- [ ] Show on a card which epic an issue belongs to 
- [ ] Make it easy to find all issues not in an epic

**Comment by mogul** [comment]
> Make it easy to find all issues not in an epic

Oh man, I have wanted that for sooo long.

**Comment by azenMatt** [comment]
We just added in a new drop down for epics, that includes the ability to filter by different states: 

![image](https://cloud.githubusercontent.com/assets/7584089/19776735/29e4020a-9c2a-11e6-99b7-1d6f0dcd4f9c.png)

This is a great addition, but filtering by these states really makes it clear that 

> I want to be able to see which epic an issue belongs to on the issue card itself

needs to be done - we will aim to get this into the next sprint so it should be live during November

@mogul 



> Make it easy to find all issues not in an epic

Check out the `Show all issues not in an Epic` option in the filter 😀

**Comment by mogul** [comment]
> Check out the `Show all issues not in an Epic` option in the filter 😀

Saw that, and I'm delighted... Thanks!

**Comment by azenMatt** [comment]
We just push out the second part of this, to enable epic names to be seen on the child cards. It should be working it's way through the chrome / firefox process to you soon! 

![image](https://cloud.githubusercontent.com/assets/7584089/21206666/6a0e7b9e-c218-11e6-90fc-58fa962740f6.png)

I think it makes it much easier to see what is happening!

**Comment by noahmanger** [comment]
These last several rounds of changes have been _excellent_ . Thank you!
