### ISSUE TITLE
ToDo list: switch checkbox for something more intuitive?

### ISSUE THREAD

**Issue by smowton** [ZenHubIO/support#896]
I accidentally deleted a todo item because I ticked the checkbox on its left-hand side, and am now raking through a few Issues boards to track it down again.

In retrospect I get that you were going for the "ticking things off a paper to-do list" metaphor, but only in retrospect. In advance I supposed that checkboxes are for selecting things, not for deleting them (at least not without an extra click, "delete selected item(s)". I suggest you should use a dustbin icon or similar, as I had also been wondering how I'm meant to take things off to-do lists!

**Comment by azenMatt** [comment]
Thanks for the feedback here @smowton 

If it helps you can also use the 'recently completed' bucket to find the issues which have been recently 'ticked off'

We don't have any changes planned for the to-do view at this point (our main focus is on the board and reporting) but i have made a note in our backlog to review this when we do come back to make improvements to todo 👍
