### ISSUE TITLE
Avatar transparency

### ISSUE THREAD

**Issue by modelga** [ZenHubIO/support#898]
I'm using transparent avatar, but as you can see, looks ugly when some issue is assigned to me. 
I'm not certain if it is a bug or my mistake

Using Chrome, latest version.

<img width="255" alt="screen shot 2016-09-15 at 10 56 45" src="https://cloud.githubusercontent.com/assets/5791952/18544039/2523f382-7b33-11e6-9c8f-df9166dd73fa.png">

**Comment by azenMatt** [comment]
ah - very interesting, thanks for reporting this @modelga ! 

I have added it as a bug, but in the interested of transparency (ha!) it is unlikely to be resolved in the near future as it is a low impact and can be resolved by editing the avatar to have a white background (unless that causes other issues im not aware of?)

**Comment by kendramoroz** [comment]
Closing in favor of #1021
