### ISSUE TITLE
Milestone filter not filtering all pipelines

### ISSUE THREAD

**Issue by oevans** [ZenHubIO/support#899]
Milestone filter isn't filtering the `Review / QA` pipeline, but is working for other pipelines.

![2016-09-19 at 8 33 53 am](https://cloud.githubusercontent.com/assets/3215530/18632189/30e6e59e-7e44-11e6-9365-763a5555d0f9.JPG)

![2016-09-19 at 8 33 58 am](https://cloud.githubusercontent.com/assets/3215530/18632193/329990f8-7e44-11e6-97ea-aa7a42684b74.JPG)

**Comment by azenMatt** [comment]
Hi @oevans - that is a really strange bug....


Would you be able to let me know if you see any errors in your browsers developer console when you load this filter?


cc @pnavarrc

**Comment by oevans** [comment]
This happened the day you guys reported slow responses from the GitHub API. Seems it was just a temporary glitch...

**Comment by azenMatt** [comment]
phew 😅 

Thanks for confirming!
