### ISSUE TITLE
Missing issues in boards and slow loading

### ISSUE THREAD

**Issue by 7omasz** [ZenHubIO/support#900]
New issues no longer appear in the appropriate `Awaiting triage` swimlane. Changing the pipeline has no effect on visibility. New issues remain hidden from boards view.

Example switching an issue from `Awaiting triage` to `On deck`, the pipeline changes, but the issue is not shown in the boards view.
![image](https://cloud.githubusercontent.com/assets/860546/18636976/d7bd0efc-7e58-11e6-991c-783502b9fbbc.png)
![image](https://cloud.githubusercontent.com/assets/860546/18637313/f80d06d4-7e59-11e6-9fee-ed2d57cdc82d.png)

May be unrelated to projects, but the project calls are taking several seconds now:

![image](https://cloud.githubusercontent.com/assets/860546/18636929/a95a6f64-7e58-11e6-8ede-1e0d81ae4f87.png)

**Comment by azenMatt** [comment]
Hi @7omasz - the GitHub API is down today - https://status.github.com/

Which is impacting ZenHub. As soon as this is back up from GitHub, we will be back

**Comment by 7omasz** [comment]
Thanks @azenMatt !
