### ISSUE TITLE
Pipelines deleted and merged repositories removed

### ISSUE THREAD

**Issue by aaronwest** [ZenHubIO/support#901]
Sometime between yesterday and today our custom pipelines and merged repositories have been removed from our main ZenHub board.

We had created a custom left-to-right pipeline workflow which includes pipelines named: In Review, Prioritized/Queued, On "Next", and more. Now, all but the default ZenHub pipelines have been deleted and all the issues in these pipelines were moved to the Backlog pipeline. Additionally, we had about 19 repos merged into one "product management" repo/board. Now, all but one of these have been unmerged/removed.

I'm thinking this has something to do with the GitHub issues that occurred yesterday morning (US time). While I can go through our entire board and recreate everything I'm hesitant to do so. Any feedback from the ZenHub team would be appreciated.

**Comment by azenMatt** [comment]
Hi @aaronwest - can you send me an email - support@zenhub.com and we will pick this up straight away. 

If you can provide the organization and repos impacted that will really help

**Comment by aaronwest** [comment]
On it.

**Comment by aaronwest** [comment]
Email sent. Thanks Matt.
