### ISSUE TITLE
Zenhub stopped working "Oops - your GitHub permissions aren't set up for ZenHub"

### ISSUE THREAD

**Issue by schellkenig** [ZenHubIO/support#902]
<img width="977" alt="screen shot 2016-09-21 at 9 32 04 am" src="https://cloud.githubusercontent.com/assets/3272986/18701702/57a56340-7fde-11e6-809e-0da7cd1464dd.png">

I am the owner of the organization and nothing has changed since yesterday from our side?

**Comment by azenMatt** [comment]
Hi @schellkenig - this might be as someone else in your org has changed the permissions? 

Would you be able to follow the instructions at - 

https://www.zenhub.com/faq#faq-permissions-privacy under `Why can't I see my organization on the ZenHub dashboard?`

That should get you back up and running. 

If not, can you provide a screenshot of any browser dev console errors that show when you get this error message?

**Comment by kelw** [comment]
Hi @azenMatt,

Am having the same issue.  One minute everything was working fine and the next minute it wasn't.
<img width="1280" alt="screenshot 2016-10-05 21 42 02" src="https://cloud.githubusercontent.com/assets/6099134/19140775/b59cacda-8b44-11e6-8aee-79d2565bfa1c.png">

**Comment by kelw** [comment]
p.s.  I did try your advice from the post above and went to "https://www.zenhub.com/faq#faq-permissions-privacy under Why can't I see my organization on the ZenHub dashboard?"  Didn't help.

**Comment by paigepaquette** [comment]
Hey @kelw , thanks for reaching out and sorry you're having trouble here! Could you try again now?

**Comment by kelw** [comment]
Hi @paigepaquette -- tried again this morning and everything is working just fine again.  Is there something I can do / watch out for so it doesn't happen again?  Thanks!

**Comment by paigepaquette** [comment]
Hey @kelw . It seems you’ve discovered an edge case with GitHub’s Projects API. In this case, it appears you had lost your pull permissions for a specific repo that is connected here, causing GitHub to return a 404 Not Found. We manually reset your permissions cache and that fixed the issue. In the future, we should work on having more granular error messages on the board to accommodate more cases!

**Comment by kelw** [comment]
Thanks for the speedy reply!  And thanks very much for reseting my permissions cache and getting me back on board.  Much appreciated!

**Comment by barrda554** [comment]
@paigepaquette I am actually receiving this exact same issue.  It occurred after switching my account to an organization.  I tried revoking and re-authorizing permissions.  It seems that it does not clear on your end.  Is it possible to get my permissions cache refreshed as well?  

Error message:

```
https://api.zenhub.io/v3/repos/55203285/boardload Failed to load resource: the server responded with a status of 404 (Not Found)
https://api.github.com/repos/particlespace/app.particlespace Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by paigepaquette** [comment]
Hey @davidbiga, sorry to hear you're having some issues here. Just to confirm, can you see the correct GitHub organization(s) on the left-hand side of your [ZenHub dashboard?](dashboard.zenhub.com)

 If not, you may need to follow the steps to whitelist ZH as an extension. It sounds like you've re-authorized your personal permissions for ZH, but whitelisting an extension must be done on an organizational level as well. 

As a next step here, can you confirm whether you've followed the steps the FAQ titled ["Why can't I see my organization on the ZenHub Dashboard"](https://www.zenhub.com/faq#faq-permissions-privacy)? 

Looking forward to getting you up and running again! (P.S - The best way to respond is via email to save other folks' inboxes in this thread 😄 . I'm at paige AT zenhub DOT com)

**Comment by azenMatt** [comment]
please contact support@zenhub.com for any similar issues - thanks 😄
