### ISSUE TITLE
Chrome extension is hiding some GitHub tabs in a dropdown

### ISSUE THREAD

**Issue by genachka** [ZenHubIO/support#904]
I use the Pulse tab a lot on the various GitHub repos I follow. Recently the Pulse tab (and usually Graph, and Settings if I have the rights) get pushed into a dropdown which is annoying to have to click, find in click and click again for something I use a lot. And there's still plenty of room on the right to still have the Pulse tab label shown.

How can the Pulse still be shown as a tab directly? Is there a configuration that controls which items to hide in the dropdown?

![zenhubhidingtabs](https://cloud.githubusercontent.com/assets/7947294/18809496/1cec7a58-824b-11e6-9b1c-52d590b19210.png)

**Comment by azenMatt** [comment]
Hi @genachka - yes we had some problems here with the new tabs GH is introducing to make sure everything fits! 

We are still taking in feedback on this change and experimenting with other ways to handle it.

**Comment by tusmester** [comment]
This is practically the _only_ unconvenient thing I encountered using ZenHub :) - but it is very annoying. 

I use the built-in **Graphs-->Network** GitHub tab very often (meaning many times a day), and that is also hidden after installing ZenHub. Of course I can always keep open browser tabs for that page, but that is only a workaround, especially when you have _many_ repositories and you are constantly switching between them.

**Comment by azenMatt** [comment]
Hi - this has been fixed, all tabs are now shown in the latest version which was just published

**Comment by tusmester** [comment]
Sorry, I do not see the change - the **Graphs** page is still hidden inside the **Insights** menu. Maybe I did not refresh something.

**Comment by azenMatt** [comment]
you might need to head to chrome://extensions and force an update. v2.35.31 and above should have the change. 

It can take a little while for the browser to pick up by itself!
