### ISSUE TITLE
How to cancel a subscription?

### ISSUE THREAD

**Issue by freezy** [ZenHubIO/support#905]
From your FAQ:

> On the “Billing” tab, you can view and edit billing information (including credit card details), cancel subscriptions, and view billing history.

I got "Subscription" (no links), "Customer Information" (lets me change my name and address), "Billing Information" (lets me change email and card number) and "Billing History" (a table). 

Nothing that lets me cancel my subscription. Anything I'm missing?

**Comment by azenMatt** [comment]
Hi @freezy - if you are an admin, and are on a paid plan. Then under the billing tab you will get:

![image](https://cloud.githubusercontent.com/assets/7584089/18843966/18c61c5a-83d0-11e6-87bb-3cf732a0ad16.png)

If you don't see this, and believe you should, please drop me an email at support@zenhub.com


Please note - that as we recently moved lots of teams down to the free tier, if you are in a team of 5 or less you no longer have a paid account to cancel.

**Comment by freezy** [comment]
Oh, you're right, I was wondering about the -$8.63 invoice. Thanks!
