### ISSUE TITLE
Zenhub dropdown menu is conflicting with github watch dropdown menu

### ISSUE THREAD

**Issue by ravinderk** [ZenHubIO/support#907]
<img width="660" alt="screen shot 2016-09-27 at 9 47 54 am" src="https://cloud.githubusercontent.com/assets/1784821/18877277/5ab444c8-84ea-11e6-86dd-d9cd412a5307.png">

**Comment by azenMatt** [comment]
Thanks for letting us know @ravinderk - we are working on a fix 👍

**Comment by azenMatt** [comment]
Hi @ravinderk - this is now fixed if you upgrade to v2.24.12
