### ISSUE TITLE
New feature: Drag and drop to assign multiple issues to another user

### ISSUE THREAD

**Issue by pauldaustin** [ZenHubIO/support#908]
Would it be possible to add functionality to assign multiple issues to another user. For example when issues have been fixed by the developer they would be assigned to another user for verification.

Another option would be to have a default user for each pipeline so assigning it to another pipeline would change the assigned user.

**Comment by azenMatt** [comment]
Hi @pauldaustin - we have 'multi-action' functionality coming soon https://github.com/ZenHubIO/support/issues/832#issuecomment-249014855 that should help here. 

triggered actions (for example, when you move to pipeline x) are a bit further out but are something we would like to deliver

**Comment by azenMatt** [comment]
HI @pauldaustin - multi-action is now live (via the cog icon on a card, or clicking the avatar) this will let you perform a multi-assignment 😄
