### ISSUE TITLE
Board view assignee filter should use OR rather than AND

### ISSUE THREAD

**Issue by willclarktech** [ZenHubIO/support#909]
As a developer I sometimes want to see what issues two or more specific people have been assigned (e.g. myself and another developer). When I filter by assignee and select us both I expect to see issues which have been assigned to either one of us, but in fact I see only issues which have been assigned to both of us (usually no issues).

**Comment by azenMatt** [comment]
Hi @willclarktech - we are going to update this filter to work this way in an upcoming release - shouldn't be too far in the future

**Comment by azenMatt** [comment]
Hi @willclarktech - we just switched this around in the latest version - 2.24.14, which your browser should be pushing out to you over the next couple of hours.
