### ISSUE TITLE
Board assign fields not visible in issue form

### ISSUE THREAD

**Issue by lionel-deglise** [ZenHubIO/support#912]
Hello

The board field is no more visible in issue form.

Thanks, Lionel

![image](https://cloud.githubusercontent.com/assets/19615637/18945313/3bd5a6e6-862a-11e6-875e-502b67379c8c.png)

**Comment by azenMatt** [comment]
Hi @lionel-deglise - Does clicking on the board work for you here? 

This looks like it might be a permissions issue - if you can confirm any errors that occur on board load that will help us to isolate the problem

**Comment by azenMatt** [comment]
Hi @lionel-deglise - if you are still seeing this issue, please drop me an email - support@zenhub.com and we can take a deeper look, thanks
