### ISSUE TITLE
ZenHub boards disappear after upgrading to Firefox 31.7

### ISSUE THREAD

**Issue by cary-anne** [ZenHubIO/support#915]

**Comment by azenMatt** [comment]
Hi @cary-anne - are you able to update to the latest version of firefox and try to re-install ZenHub? 

31.7 is a very old version! 

If you have to use 31.7, can you try and re-install ZenHub on a clean Firefox profile and see if that helps?

**Comment by cary-anne** [comment]
Thanks for letting me know! It seems I have two versions of FF installed,
and somehow managed to open the superold one. Everything's fine. Thanks for
checking!

cary-anne olsen
Master of Science in Information Studies | The University of Texas - School
of Information
cary-anne.com
LinkedIn <http://www.linkedin.com/in/caryanneolsen> | Twitter
<https://twitter.com/_caryanne>
