### ISSUE TITLE
Unexpected redirects when editing files on github: ZenHub 2.24.9

### ISSUE THREAD

**Issue by mikhail-denisenko** [ZenHubIO/support#917]
The hotkey hook is triggered when editing markdown files on github with Zendesk plugin enabled.

Steps to reproduce:
 - Navigate to some repositrory
 - Click on `Create new file` button
 - start typing in the file editor something like `The purpose of this document`

Actual result:
 - when you press `d` (for typing a word _document_) you get redirected to the `Burndown` tab

Expected result:
 - no redirects are happening as long as the file editor has focus

When ZenHub extension is disabled, the problem is gone.

This happens in Chrome `Version 53.0.2785.116 m` combined with `ZenHub for GitHub 2.24.9`

Note: luckily when I press `back` for a few times I can return to my document without loosing the data. However this is still a quite annoying issue as it makes file editing nearly impossible when ZenHub is enabled.

**Comment by azenMatt** [comment]
Thanks for reporting this @mikhail-denisenko -  I can recreate this, we will get it fixed 👍

**Comment by azenMatt** [comment]
Hi @mikhail-denisenko - this is now fixed if you upgrade to v2.24.12
