### ISSUE TITLE
Disable keyboard shortcuts on the `/edit/` pages

### ISSUE THREAD

**Issue by armish** [ZenHubIO/support#918]
When editing a file directly on the GitHub page, keyboard shortcuts seem to interfere with the typing, which is extremely annoying. 

For example, go this page where you can start editing the README file:
https://github.com/ZenHubIO/support/edit/master/README.md

and try to use `b` or `d` while editing:

![shortcut interference](https://d3vv6lp55qjaqc.cloudfront.net/items/3T44390a2S441L1M371i/Screen%20Recording%202016-10-07%20at%2005.56%20PM.gif?X-CloudApp-Visitor-Id=1759383)

**Comment by azenMatt** [comment]
Thanks for reporting this @armish - we are looking at this now

**Comment by azenMatt** [comment]
Hi @armish - this is now fixed if you upgrade to v2.24.12

**Comment by armish** [comment]
that was fast! Thanks, @azenMatt.
