### ISSUE TITLE
Merged repositories board broken after deleting one of the repos

### ISSUE THREAD

**Issue by Alexander01998** [ZenHubIO/support#919]
I had several repositories linked together in a single board, then deleted one of the repositories. Now I can no longer access the board from any of the remaining repositories.

Whenever I try to open the board from any merged repo, I get this message:
![image](https://cloud.githubusercontent.com/assets/10100202/19215590/884b8bba-8da2-11e6-97bf-16030ad251a4.png)
(Accessing the board of any non-merged repository is still working.)

I have followed the steps in the guide, even though my permissions for ZenHub were already working properly, and it didn't change anything.

I believe ZenHub is trying to access the deleted repository, which of course it can't, and then thinks that it lost permission to access it.

This bug completely prevents me from using ZenHub, as I had all of my most important repositories merged together in one board.

I am using ZenHub on my organization with only public repositories (free plan). I am also using ZenHub's Chrome extension.

**Comment by Alexander01998** [comment]
One day later, it is working again.

**Comment by azenMatt** [comment]
Hi @Alexander01998 - apologies for this issue we are working on a fix at the moment. 

For anyone else experiencing the same issues, as @Alexander01998 found out, it will start working again after a 4 hour timeout period
