### ISSUE TITLE
Make it easier to add an issue to a specific pipeline and epic

### ISSUE THREAD

**Issue by Nostrus** [ZenHubIO/support#920]
At the moment if I want to add a new issue to a pipeline I have to create the issue first and select the pipeline there. It would be simpler and more intuitive for me if I could just double click an empty area in the pipeline (or have a button there for this purpose) and the issue would be automatically added to that pipeline. 

This feature could be even more useful if I have a view that's already filterd by an epic, and the new issue could be automatically added to that selected epic, saving the hassle of selecting the epic every time at a new issue, when adding multiple issues after each other.

**Comment by zachumo** [comment]
I like this idea, sort of like how Trello does it.

**Comment by azenMatt** [comment]
Thanks for the feedback @Nostrus - I agree that this would be really helpful, both from automatically adding in issues to a pipeline and making it easier to create lots of issues that have the same meta data attached to them. 

We already have this issue open here - https://github.com/ZenHubIO/support/issues/406 - if you subscribe to updates there il keep it updated as we work towards it!

**Comment by Nostrus** [comment]
I subscribed to the other issue, thanks @azenMatt :)
