### ISSUE TITLE
NO "boards" displayed

### ISSUE THREAD

**Issue by ZHANGLINI** [ZenHubIO/support#921]
I installed Zenhub successfully for firefox 45.4.0, but NO "boards" displayed. How to fix it? Thanks.

![untitled1](https://cloud.githubusercontent.com/assets/22743391/19233196/9b439486-8f16-11e6-8567-c022edd2a2c0.png)

![untitled](https://cloud.githubusercontent.com/assets/22743391/19233159/65d44f20-8f16-11e6-9664-2dbc6836899a.png)

**Comment by azenMatt** [comment]
Hi @ZHANGLINI - would you be able to try this on a clean firefox profile to see if something is blocking ZenHub?

**Comment by ZHANGLINI** [comment]
@azenMatt , your solution is working well. The boards appears now. Thank you and have a good day.
