### ISSUE TITLE
Can The API Do THis?

### ISSUE THREAD

**Issue by gamename** [ZenHubIO/support#927]
Hi,

Can your API associate issues with an epic?
Also, can your API convert an issue into an epic?

Thanks,
-T

**Comment by azenMatt** [comment]
Hi @gamename - currently the ZenHub API is read only access so we can't perform either of those actions. 

Im going to move this issue over to the API repo where we will be providing updates on write access as we work towards it

**Comment by azenMatt** [comment]
Issue moved to [ZenHubIO/API #35](https://github.com/ZenHubIO/API/issues/35) via [**ZenHub**](https://www.zenhub.com/)
