### ISSUE TITLE
Printable zenhub issues

### ISSUE THREAD

**Issue by fotoflo** [ZenHubIO/support#928]
Hi Guys,
 Zenhub Issues are awesome, but having a printout makes sorting much easier.

THis morning i was doing sprint planning and i found this: https://github.com/pocketworks/git2pdf/ -- some slight modification to add zenhub points would be great

**Comment by azenMatt** [comment]
Hi @fotoflo - that is pretty cool 😄 

This seems like it could be a good use case for our API - https://github.com/zenhubio/API - as it should be possible add ZenHub integration to that tool this way. 

I'l keep the issue open for user feedback as to if it will be useful for everyone if we baked this functionality into ZenHub

**Comment by kendramoroz** [comment]
Closing in favor of #922 — @fotoflo please feel free to 👍 / comment over there to stay in the loop on the conversation related to PDF/printable enhancements!
