### ISSUE TITLE
JS error on github issue page

### ISSUE THREAD

**Issue by iskandr** [ZenHubIO/support#929]
I just installed the ZenHub for GitHub chrome extension and now see this JS error on a GH issue page: 

```main.js:60 Uncaught TypeError: Cannot read property 'find' of null```

This seems to happen in the `_setRepoSwitcherFilter` function. 

I'm on OS X 10.10.5, Chrome 53.0.2785.143 (64-bit) with ZenHub for GitHub 2.24.14

**Comment by azenMatt** [comment]
Hi @iskandr  - thanks for reporting this, I can also replicate this issue.

**Comment by azenMatt** [comment]
This is now fixed on 2.24.18 which was just released (might need a manual update while your browser pushes it out over the next few hours)
