### ISSUE TITLE
Multi-repo merge

### ISSUE THREAD

**Issue by hammer** [ZenHubIO/support#930]
The reason we chose ZenHub was for multi-repo Task Boards. Unfortunately, when I want to add 10+ repos to a single task board, I have to add them one by one. It would be nice to have a multi-repo selector when merging repos into a single Task Board.

**Comment by azenMatt** [comment]
Hi @hammer - agreed! 

We have spoken about cleaning up the multi-repo merge in the future as right now it is not the cleanest part of ZenHub. Allow for multiple repos to be merged at the same time as part of this makes a lot of sense

**Comment by hammer** [comment]
@azenMatt any progress on this one?

**Comment by azenMatt** [comment]
Not yet @hammer 

One of the big blockers is speed of very large multi-repo boards. The user experience of ZenHub is much better as several smaller boards than a single large one. We would need to make sure users understand the performance trade off they are making when looking to work with just very large boards

**Comment by kendramoroz** [comment]
@hammer 👋  Update here from the team! We are excited to be working on Workspaces, where teams can create multiple project views and multiple Boards per repo, which should help with this use case when merging multiple repos at once :) - You can follow #139 to stay updated.
