### ISSUE TITLE
Feature Request: Show Pipeline as Label for non-Zenhub users

### ISSUE THREAD

**Issue by jeoffw** [ZenHubIO/support#931]
As an occasional user of Github issues, I'm not in Zenhub kanban boards every day. But I sometimes receive email updates about specific issues. When I click the links, they open the github issue in Safari (where Zenhub isn't supported). Yes, I could switch to Chrome, but often I'm browsing from my mobile phone, where the Zenhub plugin simply isn't available on any browser. I need to see the Pipeline an issue is in, but without the plugin, the Pipeline field isn't displayed.

I propose including Pipeline as a label so occasional users of issues who don't have Zenhub installed aren't completely blind to the pipeline status of an issue.

The label could potentially be prefixed, e.g. `Pipeline: Testing` or `Zenhub Pipeline: Testing`. When Zenhub plugin is enabled, it could hide those labels so they don't clutter things up.

This would allow for [graceful degradation / progressive enhancement](https://www.w3.org/wiki/Graceful_degradation_versus_progressive_enhancement).

**Comment by azenMatt** [comment]
Hi @jeoffw - thank your for the request - we have an issue here - https://github.com/ZenHubIO/support/issues/19 - that covers the same high-level concept that you can follow for updates.

I do understand the pain point here, but to be transparent right now this is not something we are looking to implement in the near future. 

I'm going to close this to consolidate the conversation in #19
