### ISSUE TITLE
Milestones stuck in Boards

### ISSUE THREAD

**Issue by jeanrajotte** [ZenHubIO/support#932]
In Github, I deleted a bunch of milestones, which had been duplicated across repos so we can use them seamlessly in Boards.
- The github issues themselves, following referential integrity, got unassigned from the deleted milestones. 
- The cards on Boards don't show the deleted milestones either.

However, 
- The Github native Issues listing shows the dead milestones w/ the Boards icon next to them.
- The Boards Milestones dropdown shows the dead milestones also.

And yet, these milestones don't exist in any of the repos registered with Boards anymore.

Lest we re-add the milestones to repos, formally unhook affected issues (the closed ones included) and then remove the milestones, these ghosts will stay there. This isn't good.  

Seems you have a bug in that you're holding on to the milestone externally to the Github issue persistence.

That's not right, right?

**Comment by azenMatt** [comment]
Hi @jeanrajotte - it sounds like the milestone cache has got caught for you, can you let me know the org/repo name impacted and I can get this fixed for you

**Comment by jeanrajotte** [comment]
All repos for ToplineVentures

/SBS-API
/SBS-Manager
/SBS-Gateway
/Tools
/SBS-Chronos
/Docs

tx

--
*Jean Rajotte*
+1 647-525-4836

**Comment by azenMatt** [comment]
Hi @jeanrajotte - apologies for the delay here, this should all be taken care of now. would you be able to confirm it is back working?

**Comment by jeanrajotte** [comment]
Matt,

it's hard to test at this point. The milestones I see are those that exist.
I don't see those that don't exist (anymore).  Seems fine.  Thanks.

--
*Jean Rajotte*
+1 647-525-4836

**Comment by azenMatt** [comment]
great - thanks for confirming, just let me know if anything else comes up
