### ISSUE TITLE
Unable to sign in to Zenhub

### ISSUE THREAD

**Issue by kjw000** [ZenHubIO/support#933]
All of a sudden I am unable to sign in to zenhub.  We have been using this successfully for 6 months and now it looks like we can not be authenticated. It is stuck loading - https://api.zenhub.io/auth/github?redirect=https%3A%2F%2Fgithub.com

I am using chrome and also tried firefox - same issue it is stuck on the authorization.

**Comment by azenMatt** [comment]
Hi @kjw000 - we were hit by the DNS downtime - https://news.ycombinator.com/item?id=12759520 

Everything should be back working now?

**Comment by azenMatt** [comment]
The internet bounced around a few more times.. but everything seems to be fixed now! 

Im going to close this issue but let me know if you are still suffering ZenHub being down and we can pick it back up
