### ISSUE TITLE
Reordering in a pipeline (dragging an issue) is quite slow

### ISSUE THREAD

**Issue by ihodes** [ZenHubIO/support#935]
I don't think it's a perf issue at all, just feels unresponsive. I could be doing it wrong, though.

Video example http://link.isaachodes.io/2I1J3l1y233m

**Comment by azenMatt** [comment]
Hi @ihodes 

Would you be able to let me know how many repositories you have connected, and the total number of issues on the board?

**Comment by ihodes** [comment]
That board has one repository showing (10 connected), 39 issues in the single repo showing.

**Comment by kendramoroz** [comment]
@ihodes Kendra here from the success team at ZenHub! How's the boards speed these days with drag-and-drop? Hope you're having a great new year 🚀 !

**Comment by kendramoroz** [comment]
@ihodes  Hey Isaac! Hope performance is back to normal for you these days. Closing this issue since we haven't heard back from you in a few weeks, but don't hesitate to be in touch if something comes up or you're still experiencing issues—happy to reopen!

**Comment by ihodes** [comment]
Thanks for looking into it; sorry I missed your earlier message!
