### ISSUE TITLE
Implement move issues for private github repositories

### ISSUE THREAD

**Issue by benoitries** [ZenHubIO/support#938]
steps to reproduce:
- create an issue in a private repository
- move this issue to another private repository
- "Loading your repositories..." is displayed forever

**Comment by kendramoroz** [comment]
Hey @benoitries Kendra here from the ZenHub team following up on this! Are you still experiencing trouble with the move issue workflow?

**Comment by benoitries** [comment]
Hi @kendramoroz . I have re-tested this issue:
1) This issue is not appearing anymore => "Loading your repositories..." is displayed forever
2) BUT It seems that I can still not move the issue (for example https://github.com/thibaultsmnt/SEP-g02-usermanual/issues/55) in any of the other private repos of the same user, eventhough I am contributor on these other private repositories.

**Comment by lamaral** [comment]
I'm experiencing the exact same issue from the first post.
I'm trying to move an issue from a private repository that I don't own but have access to, to another repository from the same user that I also have access.

**Comment by kendramoroz** [comment]
@lamaral and @benoitries when you're moving issues, do you see any console errors pop up?

**Comment by lamaral** [comment]
I got a 404 error, where ubiplaces is the username of the repository owner. 
![screen shot 2017-01-31 at 15 46 58](https://cloud.githubusercontent.com/assets/1342887/22477298/a390cadc-e7cc-11e6-8aa6-0878b7bd455f.png)

**Comment by lamaral** [comment]
Hey @kendramoroz, just a complement.
Today, I tried to add another repo to my board by clicking on the little list button next to the repository name. I added repositories in the past that same way, but today, it didn't show up any. 
Looking at the console, the same error I posted previously is being thrown, what makes me think that maybe an update in ZenHub is what is causing this issue.
![screen shot 2017-02-02 at 15 18 23](https://cloud.githubusercontent.com/assets/1342887/22560268/1d620422-e95b-11e6-9c3c-f83bb09b23a3.png)

**Comment by kendramoroz** [comment]
Hey @lamaral thanks for sending this over! Would you be able to try creating a new profile in your browser and re-downloading ZenHub on a fresh profile to see if you're encountering the same issue? The fact that ubiplaces isn't an org shouldn't be causing any issues here. Just want to rule out interference from another extension!

**Comment by lamaral** [comment]
Hey @kendramoroz, I just created a brand new profile and tried the same step from previous comment. No success :(
Still the same 404 error in a call to an endpoint /orgs/ubiplaces.
I tried looking at the Network tab and I can see two calls for the /repos endpoints, both returning a 304 - Not modified. 
![screen shot 2017-02-02 at 19 57 06](https://cloud.githubusercontent.com/assets/1342887/22570303/eb98f4f6-e981-11e6-9284-31666b9edcd5.png)
I don't know a lot about the ZenHub architecture, but maybe a header to ignore the cache could be added.

**Comment by kendramoroz** [comment]
@lamaral Just to clarify here,

> Today, I tried to add another repo to my board by clicking on the little list button next to the repository name.

Are you looking to create a multi-repo board? If so, you can leverage the **repo filter** on the top left of the board. The repo switcher dropdown is meant to re-direct you to a separate repo. 

![image](https://cloud.githubusercontent.com/assets/11036230/22612817/f4cc02ce-ea27-11e6-9b2e-2340a977ffe1.png)

Is the dropdown not working at all for the repo switcher, or just taking a bit of time to load the other repos you belong to?

**Comment by lamaral** [comment]
Hi @kendramoroz, I have 9 repos on my board. I was trying to add another repo to it using the dropdown you showed but the other repo is not showing up. When I try filtering, all repos disappear and the list doesn't get populated at all.

**Comment by kendramoroz** [comment]
Ah! Do you have write access on that repo? You're only able to merge board that you have write access for @lamaral

**Comment by lamaral** [comment]
Yeah, I have write access in all the repos, @kendramoroz.

**Comment by kendramoroz** [comment]
@lamaral The repo switcher picks up the repos connected typically by organization—in the case that they're assigned to users, you might have better luck using the manual connector. When you click on the repo filter, select **merge another repository** from there, select the **merge from another organization** option. 

![image](https://cloud.githubusercontent.com/assets/11036230/22663414/5b65b6ac-ec61-11e6-9c92-e4b030937a94.png)

This will pop up the manual repo connector modal where you can type in the organization (or in your case the user) and the name of the repository. 

![image](https://cloud.githubusercontent.com/assets/11036230/22663446/785957be-ec61-11e6-92fb-c67aa2a89d84.png)

The list will pick up only those boards associated with the organization/user that you're currently on, so this is potentially why it's not picking it up. Let me know if this works 🎉

**Comment by lamaral** [comment]
Hi @kendramoroz, that worked perfectly. 
Is the Move issue feature broken because I'm using a user instead of an organization?
