### ISSUE TITLE
Add to todo-list buttons went missing

### ISSUE THREAD

**Issue by zachumo** [ZenHubIO/support#939]
When inside an issue, either in the board overlay mode, or in the inline view, the add to todo list buttons seem to have gone missing. Confirmed by two users.

**Comment by azenMatt** [comment]
I can also reproduce  - we will get on this right away

**Comment by azenMatt** [comment]
Hi @zachumo - this is fixed on v2.24.23 which is live now on Chrome, the firefox version is just going through the release process and will be with you shortly. 

It take a while for the browsers to push the updates live, so you may need to manually request an update via the browser

**Comment by zachumo** [comment]
Great, thx!
