### ISSUE TITLE
ToDo Button Disappeared

### ISSUE THREAD

**Issue by patmagee** [ZenHubIO/support#941]
Can no longer add Issues to my todo list

![screen shot 2016-10-28 at 10 36 15 am](https://cloud.githubusercontent.com/assets/8960037/19810189/7cc09dd2-9cfa-11e6-97ce-d6a91dfccf8a.png)

**Comment by azenMatt** [comment]
Hi @patmagee 

We have just pushed a fix for this, v 2.24.24, would you be able to try and manually update and it should be working again?

**Comment by patmagee** [comment]
Hi @azenMatt, It seems to be working well!

**Comment by azenMatt** [comment]
Thanks for confirming 😀
