### ISSUE TITLE
Cannot view issue detail from board in Firefox.

### ISSUE THREAD

**Issue by briandailey** [ZenHubIO/support#943]
- Open a ZenHub board.
- Click on an individual issue.
- You will get this:

>  The GitHub page cannot be loaded. Make sure that Issues are enabled on the repository settings.

The same board(s) work fine in Google Chrome.

Ran into this issue on multiple OSs (macOS, Ubuntu).

**Comment by briandailey** [comment]
This is not an intermittent issue - I've been having issues with it for weeks (maybe months? At some point it worked.)

I'm running version 2.24.24.

**Comment by azenMatt** [comment]
Hi @briandailey - do you get any errors in the dev console when the issue fails to load?

**Comment by briandailey** [comment]
@azenMatt I sure do.

> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”).

**Comment by azenMatt** [comment]
Thanks @briandailey  - can you try this with a clean firefox profile and see if the error still occurs? 

It seems likely that something else is not playing nicely with ZenHub that is causing this

**Comment by briandailey** [comment]
A clean profile works fine.

I narrowed it down to an option in preferences where I disabled all third party cookies.

![screenshot from 2016-11-11 14-02-41](https://cloud.githubusercontent.com/assets/2156/20228588/8d829a3a-a817-11e6-87e6-fb435fc7f8b2.png)

Once I changed that to "Visited" all is well.

**Comment by briandailey** [comment]
Thanks for the help narrowing it down!
