### ISSUE TITLE
Filter Milestones from Velocity Tracking

### ISSUE THREAD

**Issue by jonahwh** [ZenHubIO/support#944]
We have multiple teams with their own sprints/milestones within one repo. This makes the Velocity Tracking page useless, because we can't filter out milestones by team.

I'd like to see a feature where I can remove a milestone from the "Velocity Tracking" page, or the ability to filter by milestone names - we use prefixes to tell them apart.

**Comment by azenMatt** [comment]
Hi @jonahwh - 100% agree, this was one of the use-cases that we had as part of our initial scope but removed in favour of shipping it sooner and gathering feedback. 

I'l add your support for this change into our backlog

**Comment by kendramoroz** [comment]
@jonahwh Following up on your original feature ask—this is now available in the product! You're able to unselect a milestone from the velocity report simply by toggling it off in the checklist below the chart. Let me know if you have any questions or other feedback you'd like to share 🎉 

![velocity outliers](https://cloud.githubusercontent.com/assets/11036230/23441717/db024b36-fdd8-11e6-987e-f793bca7d164.gif)
