### ISSUE TITLE
Merging repositories > Deleting the pipeline causes it to be deleted throughout merged repos

### ISSUE THREAD

**Issue by aamorozov** [ZenHubIO/support#946]
### Issue specifics
if your repository has ever been merged with another repo you will be able to see all other repos that are going to be merged with that 2nd repo in yours.

That is not a huge issue, but it is getting there once changing the pipeline structure in one merged repository can affect the pipeline structure in all of them. 

### Preconditions
1. All the repositories have been created inside of one organization;
2. A repository was created for maintenance items;
3. Then we merged all necessary repositories where we'd like to pull the issues from with the maintenance repo. 
 
### Steps-to-reproduce
1. Open a repo "xxxx";
2. Go to that repo; 
3. Start using zenhub pipeline; 
4. Add a pipeline "yyyy";
5. Create another repo "zzzz";
6. Make sure Zenhub pipeline is active there as well;
7. Add a pipeline with the same name "yyyy";
7. Merge "zzzz" with "xxxx";
8. Go to the first repository "xxxx";
9. Delete the "yyyy" pipeline; 
10. Go to the second repo 'zzzz".

### Expected behavior
The pipeline ""yyyy" in the "zzzz" repo stays the same. 
 
### Actual behavior 
The pipeline "yyyy" that has been deleted from the first repo "xxxx" is also deleted from the second one "zzzz".

I described the case with only two repos in steps-to-reproduce, because the amount of them is not affecting the specifics of this issue. The bug is very annoying, specifically for us as an agency, since we usually have 50+ active repositories and if one change can sequentially affect all of them - that becomes a problem.

**Comment by aamorozov** [comment]
Nothing?(

**Comment by azenMatt** [comment]
Hi @aamorozov - this is an important update for us that we hope to look into soon. 

We have an issue open to track this - #139 - which you can subscribe to for updates.

**Comment by aamorozov** [comment]
@azenMatt Thank you!
