### ISSUE TITLE
Missing the "Collapse" button on pipeline headers

### ISSUE THREAD

**Issue by aradiatek** [ZenHubIO/support#947]
As a product manager / team leader I frequently use the expand/collapse button that used to exist in the pipeline header, but logged in today to do some backlog grooming and it is gone! I see the capability is now under the "settings" - but this adds more clicks and will be annoying/distracting during sprint planning with a group. Is this a setting somewhere now? How can I get it back?

Thanks in advance.

**Comment by cbeams** [comment]
Agreeed, @aradiatek. FYI, I've added similar usability concerns here https://github.com/ZenHubIO/support/issues/609#issuecomment-258310617.

**Comment by azenMatt** [comment]
Hi @aradiatek - as @cbeams noted in #609 this was moved into the cog to allow for the pipeline sorting to live in the issue bar. 

We want to see which one is more useful to live in the 'first click' space. 

To try and reduce the clicks somewhat, we added this change last week:

![image](https://cloud.githubusercontent.com/assets/7584089/20160957/03687194-a6a0-11e6-8b52-4330026700b0.png)


so that the expand / collapse options appear when a pipeline is zero width or greater than one width - does that help at all? It should reduce some clicks for this operation.

**Comment by cbeams** [comment]
I can see the challenge you're facing, wanting to keep the number of affordances in the column title bar to a minimum, but I don't think this hits the mark, with usability / discoverability in mind.

I see two main issues:

1. Hiding the resizing controls when a column is at its default single-card width nearly ensures that new users—especially less curious and proactive ones—will never discover the feature in the first place. At best, they will stumble upon it someday, when they happen to click the cog for some reason. I'm afraid the approach above optimizes for the already-knowledgeable user. As someone who is always ramping up new people on ZenHub within my company, I really appreciate it when the product's features present themselves effectively to the uninitiated.

2. Perhaps I've missed an explanation elsewhere, but I don't understand why the sort arrows would disappear at column widths greater than 1 card, as it does on the right side of the screenshot above. Why wouldn't sorting continue to work on a wider column in the same fashion it does on a narrow column? And if it does still work, why wouldn't I want to have the control equally as available?

From your response to my feedback in https://github.com/ZenHubIO/support/issues/609#issuecomment-259574169:

> What I really want is to grab the side of the column with my mouse and stretch it.
>
>> This would be the best solution!

Perhaps the usability challenge we're discussing here is really best seen as evidence of how important mouse-based manipulation of column widths really is. I can imagine it's a taller order from an implementation perspective, but if it's the right solution in the longer run, then maybe the right compromise for now is to simply keep both sorting and column width controls persistent on columns of all widths greater than zero.

**Comment by adambuczynski** [comment]
+1 for displaying the collapse button in the header.

Coming from Waffle, that's a feature I have grown attached to. It's very handy to quickly switch views and hide/open various columns.

**Comment by azenMatt** [comment]
We just made a change here so that now the expand / collapse buttons are the ones that are always shown

**Comment by adamreisnz** [comment]
Awesome thanks!
