### ISSUE TITLE
Is there a way to only show the comments and hide the journals, the journals?

### ISSUE THREAD

**Issue by jeanrajotte** [ZenHubIO/support#948]
If there is, what, how?

If there isn't, how soon will there be? :)

The journaling can be tall, what with all the knobs provided, showing the transitions of assignment, pipeline, label, oh my!  The comments is where the action is until you want more. I'd like a default to only show the audit on demand.

**Comment by jeanrajotte** [comment]
I could see ellipsis show up by default, begging to be clicked on demand, only to reveal that I changed the title twice twice -- who cares?

**Comment by kendramoroz** [comment]
We've launched collapsing of issue events after 3 entries to the web app and extension to help with collapsing events and showing more comments/issue references. Closing!
