### ISSUE TITLE
Ability to add custom tabs to create more than one board page

### ISSUE THREAD

**Issue by loewenstein-zz** [ZenHubIO/support#950]
Hello, if there are plenty of content on the board one might want to create a custom page that shows an additional board page that holds for example the backlog or risks or epics pipeline that are needed not as often or by other roles as those actively used for the sprint actually.
Or is that already possible?

Thanks in advance.

**Comment by azenMatt** [comment]
Hi @loewenstein-zz - this isn't currently possible, it would be great to understand more about your usecase here to help us prioritize this?

**Comment by kendramoroz** [comment]
👋  @loewenstein-zz Update here from the team! We are excited to be working on Workspaces, where teams can create multiple project views and multiple Boards per repo, which should help with this use case :) - You can follow #139 to stay updated.
