### ISSUE TITLE
Pipeline Reverts to Different Location with Certain PRs

### ISSUE THREAD

**Issue by MadBurgess** [ZenHubIO/support#951]
As a User, I have my local repo which connects to my company's repo; I make PRs from my local repo to the company repo. When I make a pull request I set all my drop down items from ZenHub before making the PR. The default is 'Isssues' and I change it to 'Code Review'. When I make the PR the Pipeline reverts from 'Code Review' back to the default 'Issues'. This didn't happen about 2 months ago and started happening after ZenHub's release that changed some of the reporting tools. Really annoying issue having to check and re-check after the page loads to see if my PRs are in the correct pipeline.

**Comment by azenMatt** [comment]
Hi @mburgess-civicsolar 

Thank you for reporting this, 

to confirm, when you say the default is issues - is this your furtherest left pipeline? Or has it been set as the custom 'default pipeline' for PRs?

**Comment by mburgess-civicsolar** [comment]
Sorry the default IS NOT Issues, the default has been Code Review. I have it set for my local repository that the Default Pipeline is Code Review. We have Issues set as the first option, and the furthest left pipeline, is Issues. This is shown in the screenshot below.

This issue where I set it to Code Review and it reverts to Issues happens for about 50% of my PRs after I reload the page. For the other 50% it stays as Code Review but while the page is loading the drop down list flashes/glitches Issues as if it was going to change it but then just keeps it as Code Review. The flashing/glitching between Issues and Code Review in the dropdown while the PR is being made just started this week. The reverting from what I select to Issues has been an on-going issue. 

![screen shot 2016-11-16 at 11 40 33 am](https://cloud.githubusercontent.com/assets/20895460/20362770/9694b1c0-abf1-11e6-9dac-779ec256ddb0.png)

**Comment by mburgess-civicsolar** [comment]
@azenMatt 

I couldn't catch it reverting from Code Review to Issues because it's a 50/50 shot, but I did record the issue where it glitches for a second, but I have it as a webm video which cannot be uploaded here.

**Comment by kendramoroz** [comment]
@MadBurgess following up on this bug report here! Everything should be working normally with the issue and PR functionality, but let us know if you've still been noticing otherwise :)
