### ISSUE TITLE
"Add Issues to an Epic" view doesn't add issues to an epic.

### ISSUE THREAD

**Issue by fotoflo** [ZenHubIO/support#953]
It creates issues, but they are not added to an epic. (BUG)

Additionally it woudl be cool if you could add labels and change pipeline status in bulk in this screen

**Comment by azenMatt** [comment]
Hi @fotoflo 

To confirm, are you talking about this screen here - 
![image](https://cloud.githubusercontent.com/assets/7584089/20276696/3043219a-aa52-11e6-872c-61b6647d329b.png)

I'm unable to recreate the issue if you could provide some recreation steps that would be helpful

**Comment by kendramoroz** [comment]
@fotoflo Hey Alex, Kendra here from the success team 👋  Are you still experiencing the Bug that Matt was helping you with above?
