### ISSUE TITLE
Filter by points

### ISSUE THREAD

**Issue by fotoflo** [ZenHubIO/support#954]
I want to be able to filter my board by points

My use case is to find issues without points assigned.  Secondary use case would be to find big issues that should be broken into epics.

**Comment by azenMatt** [comment]
Hey @fotoflo 😄 

We have issue #698 which is recording this. 

Hopefully the new 'sort' functionality is somewhat helpful here as you can easily group estimated and non-estimated issues in a pipeline? 

I appreciate that isn't quite as powerful for your usecase as your suggested implementation but should hold you over until we have estimate filtering?

**Comment by azenMatt** [comment]
closing to keep the discussion in #698
