### ISSUE TITLE
Can't scroll to bottom of label list in new issue view

### ISSUE THREAD

**Issue by CRCChelsea** [ZenHubIO/support#957]
When I open a new issue from the Boards page, the overlay window isn't big enough for the label dropdown. I can scroll within the dropdown and see most of the list, but the overlay window also needs to be scrolled in order to see the bottom, and when I click out of the label list to scroll it, it closes.

So I can't see the bottom of a long label list if I create the new issue from the ZenHub boards tab, I have to create it from the GitHub Issues tab instead.

See screenshot, the inner scroll bar is all the way down but the outer one is preventing me from seeing the rest of it. Clicking the outer bar at this point closes the label dropdown.

![zenhubissue](https://cloud.githubusercontent.com/assets/1341726/20356575/e969c1fa-abf2-11e6-861b-999f3d29c437.png)

**Comment by azenMatt** [comment]
Hi @CRCChelsea - thank you for reporting this. It is a known issue for how this modal works. 

Would you be able to confirm that you are able to work around this by scrolling the modal window while the label options are open?

**Comment by CRCChelsea** [comment]
I am not able to do that, no. As soon as I click the outer scroll bar, the label options close. I cannot use the arrow keys to scroll the outer bar either. If I had scrolling enabled on my trackpad (I'm not using a mouse) then I can scroll that way, but I typically keep that disabled.

**Comment by adambuczynski** [comment]
This is a severe problem for me as well, especially on a laptop screen, and especially when I am trying to set the estimate of a story:

![image](https://cloud.githubusercontent.com/assets/490562/20846433/7160569e-b92e-11e6-80af-9132cdb0fc88.png)

Only the first value is visible, and as long as the dropdown is open, I can't seem to scroll down on the modal area left or right of it, only when I hover over the dropdown itself, or the sidebar element, this guy:

![image](https://cloud.githubusercontent.com/assets/490562/20846514/e7c67c28-b92e-11e6-925d-9104e7be8483.png)

@CRCChelsea I'm afraid a trackpad won't help either. I'm using one with scrolling (macbook air) and it's still very problematic to scroll.

I think there's some scroll prevention on the parent item going on when the dropdown is visible.

**Comment by azenMatt** [comment]
Hi @CRCChelsea @adamreisnz 

GitHub have recently pushed out some updates to change how the side bar works that appears to have resolved this issue for now. 

If I open the board on a small laptop screen and create a new issue, scrolling the labels drop down causes the whole window to scroll when i hit the bottom of the list - giving me access to everything 

Would you be able to confirm this also works for you now?

**Comment by adamreisnz** [comment]
@azenMatt I'm still experiencing a similar issue as described in the comment above, https://github.com/ZenHubIO/support/issues/957#issuecomment-264535096

I can't scroll the issue modal contents down by scrolling on the issue background when the label dropdown is open. It only allows me to scroll *on top of* the label dropdown, which is awkward at best and quite annoying when you run into it over and over again.

**Comment by CRCChelsea** [comment]
No, it doesn't work for me still. How did you scroll down? As soon as I try to click the outer scroll bar, the labels list closes for me. I tried this in my GitHub Enterprise instance and in a personal test repository to make sure that I was using up-to-date GitHub.

To be clear, the steps are to click the New Issue button **from the boards tab** - it has to be in the modal window to reproduce the issue and then scroll down using the scroll bar (not a scroll wheel or trackpad).

**Comment by azenMatt** [comment]
ah, I see - yes the comment I made above was based on scrolling on-top of the label drop down, using a track pad

I can not get to the bottom of the list using either the scroll bar, or arrows keys

**Comment by adamreisnz** [comment]
@azenMatt I've updated my comment above with an illustration.

I've also noticed that clicking on Milestone, in fact *auto scrolls* the modal so all milestones come into view. If you could implement that for labels, that would solve the issue probably:

This is what happens after I clicked Milestone:

![image](https://cloud.githubusercontent.com/assets/490562/21236489/166d2550-c360-11e6-9799-cab161ff2fc5.png)

The modal scrolled down to allow the bottom of the milestone dropdown come into view. Is this github controlled or done by zenhub?

**Comment by athermalin** [comment]
Hi,
I also have this issue in  Chrome Version 55.0.2883.87 m. running on Windows 7.

When I click on the boards, it goes to my only board.
The scroll bars are momentarily visible, then disappear after the pop-up that says "loading your issues"

I read some other posts about missing scroll bars. One suggested that pop-ups could cause the problem, and that refreshing might help. However that causes the pop-up to appear again, so it doesn't help.

Another suggestion was to turn off the "use hardware accelerator" option, but that did not help.
It  didn't help

(see https://productforums.google.com/forum/#!topic/chrome/gSdUqNs3m6I)

- Aaron
