### ISSUE TITLE
Sign in now to use Zenhub

### ISSUE THREAD

**Issue by Tamarabyte** [ZenHubIO/support#958]
Every time I go to a new page on github the little 'Sign in now to use ZenHub' prompt appears. No matter how many times I click it, it always comes back. I get the following JS errors:

`auth:error:not_authed main.js:41`

It's redirected me to the 'https://github.com/login/oauth/authorize' screen half a dozen times, and each time I've clicked 'Authorize Application'. It doesn't seem to have any effect. I've followed the 'Why can't I see my organization on the ZenHub dashboard?' several times to no effect. Zenhub is in my Authorized application list on my personal github account and listed as approved for third-party access in my Organization's settings. I've tried accessing it on chrome from my el captain mac, and on chromium from arch linux.

**Comment by paigepaquette** [comment]
Hey Tamara, thanks for reaching out and I'm sorry to hear you're having trouble here. I just wanted to drop you a note and let you know we've been troubleshooting this, and will be in touch if we need any further info from you. 

So we can contact you directly, do you mind shooting us an email (support@zenhub.com) and we can continue the convo there? 

Thanks!

**Comment by Tamarabyte** [comment]
Thanks Paige! Moving this to email.

**Comment by fureigh** [comment]
I've been having the same problem. I'll email support@zenhub.com.
