### ISSUE TITLE
[Request] Label issues with their parent epic

### ISSUE THREAD

**Issue by tayapage6** [ZenHubIO/support#960]
Given that issues within an epic can be in many statuses (not started, in progress, done, etc.) While the epic itself has only one status, it would be helpful to have the epic name reflected on the issue so that for a given sprint one would know what epics are being worked on, without having to create separate labels for each epic.

Jira does this very well with short names:

![image](https://cloud.githubusercontent.com/assets/23346526/20442353/483f85ee-ad96-11e6-8014-f40f182d02d2.png)

/cc @alloy

**Comment by azenMatt** [comment]
Hi @tayapage6 - we have an issue open for this here - https://github.com/ZenHubIO/support/issues/893

That you can follow for updates. It is currently scheduled for Q4 so we will have it live by the end of the year for you 😄
