### ISSUE TITLE
Removing an assignee from an issue with multiple assignees, doesn't actually reflect on zenhub board.

### ISSUE THREAD

**Issue by sbadugu** [ZenHubIO/support#961]
If I assign multiple assignees to an issue (For e.g. a, b and c). When I goto the board and filter issues with assignee `b`, then I see all the issues assigned to `b` and it works as it is supposed to be.

**Problem:**
Now, if I remove assignee `b` from the issue and then go back to the `zenhub` board and filter the issues with assigned to `b` it still makes it to the board. It should not appear on the board as the assignee `b` is now removed from the issue.

**Comment by azenMatt** [comment]
Hi @sbadugu - that is very interesting... 

I haven't been able to recreate :/ would you be able to let me know if the users avatar still appears on the card or is it just the filter?
