### ISSUE TITLE
ZenHub is not available on new Firefox 52.0a2 (2016-11-23) (64-bit)

### ISSUE THREAD

**Issue by Aliaxander** [ZenHubIO/support#964]
http://joxi.ru/YmEna1nfZ4L9Z2

**Comment by azenMatt** [comment]
Hi @Aliaxander - thanks for reporting, we will take a closer look into this - although it is worth noting we only support the official releases as the release candidate builds like v52 tend to have compatibility issues like this that are fixed before they hit general release

**Comment by jgillman** [comment]
Balls, I ran into this today too :(

Thanks for the heads up about support though, @azenMatt!

**Comment by azenMatt** [comment]
Hi @jgillman - I was just about to reply to your email :D 

glad you found the root cause - we will keep you all updated on how this works it's way through the pipeline.

**Comment by azenMatt** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1320201#c14 

The root cause has been identified and resolved :D 

So ZH should be back to working on nightly builds very soon!
