### ISSUE TITLE
Zenhub Boards plugin can not get the github issue milestones we added days ago

### ISSUE THREAD

**Issue by goupeng212** [ZenHubIO/support#968]
We added new milestones in the github issue days ago. WE can not see the Zenhub boards tab page can get the added milestones in the milestone filter

**Comment by azenMatt** [comment]
Hi @goupeng212 - would you be able to confirm if the milestone has any issues inside it? 

also, to force a refresh of this cache, please try to edit a label name to something else in this repo and it will force labels / milestones to update

**Comment by goupeng212** [comment]
@azenMatt 
Thank you! You are correct! We don't have the issue associate to the milestone. After doing that, we can see the milestone in the boards
