### ISSUE TITLE
Unable to download ZenHub Enterprise for Firefox

### ISSUE THREAD

**Issue by nbanerj** [ZenHubIO/support#969]
I am not being able to download Zenhub enterprise for Firefox ESR V45.5.1. is there a download link somewhere for that? I cannot view the boards without Zenhub enterprise. thanks

**Comment by azenMatt** [comment]
Hi @nbanerj - can you please email enterprise@zenhub.com along with the name of the company for which you have Enterprise installed and we can provide you with the appropriate extension access. 


cc @aupright
