### ISSUE TITLE
ENH: alert/add to todo when upon addition to pipeline

### ISSUE THREAD

**Issue by CJ-Wright** [ZenHubIO/support#970]
Would it be possible to have certain people subscribed to pipelines?
For example, when I add an issue/PR/etc to the QA/Review pipeline would it be possible to notify a group of people that the code is ready for QA/review?

**Comment by azenMatt** [comment]
Thank you for the suggestion @CJ-Wright - agreed this would be very useful! 

Improving the notifications in the board view is one of our priorities for Q1 - I can see this as being a natural extension for that functionality.

**Comment by kendramoroz** [comment]
Closing to consolidate with https://github.com/ZenHubIO/support/issues/827 please subscribe there for future updates!
