### ISSUE TITLE
Refreshing page when Milestone filter is active sets incorrect filter

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#972]
When I filter on a specific milestone, and then refresh the page, I see an empty board:

![image](https://cloud.githubusercontent.com/assets/490562/20904597/25e82f4c-bba5-11e6-94f3-a77aeea34775.png)

The Milestone filter button is coloured purple, yet there is no milestone selected as being filtered on:

![image](https://cloud.githubusercontent.com/assets/490562/20904625/48fd3342-bba5-11e6-8acc-b3d462bc4443.png)

There is also no button to "clear all filters" present.

Only after I select a milestone again manually do the correct cards show again.

Looks like a bug where the correct milestone isn't selected for the filter after refreshing the page.

**Comment by adamreisnz** [comment]
Some more information, this is the hash fragment and query string that is attached to my repo url, and which after refresh results in no issues showing up at all

`#boards?milestones=1.3.0%20Online%20payment%20&repos=44588405`

The app clearly thinks a Milestone filter is active, as it's marking it purple, but nothing is selected.

**Comment by adamreisnz** [comment]
Probably the same issue as #982 

The URL for our Milestone filter is:

`#boards?milestones=1.3.0%20Online%20payment%20&%20sub%20mgmt#2016-12-03&repos=44588405`

Which should be escaped as:

`#boards?milestones=1.3.0%20Online%20payment%20%26%20sub%20mgmt#2016-12-03&repos=44588405`

I can confirm that this is causing the problems after refresh. Once I replace the ampersand with the escaped value, and hit enter, the board loads properly.

**Comment by azenMatt** [comment]
well spotted 👍

**Comment by adamreisnz** [comment]
@azenMatt @kendramoroz this one can be closed now as well, as it's fixed with https://github.com/ZenHubIO/support/issues/982 🎉
