### ISSUE TITLE
No way to clear milestone of multiple selected issues

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#974]
I have several issues selected that I wanted to remove from the 1.6.0 milestone, however this was impossible:

![image](https://cloud.githubusercontent.com/assets/490562/20907583/05f2eaf6-bbb4-11e6-83e2-d2951c263e2a.png)

There is no "clear milestone" button, nor is the 1.6.0 milestone checked (even though all the selected issues are in the 1.6.0 milestone)

Apply changes button remains greyed out if I tick and untick 1.6.0.

**Comment by adamreisnz** [comment]
I noticed that this does work properly for Epics

**Comment by cbeams** [comment]
I just ran into this as well. @adamreisnz's description captures the issue exactly.

**Comment by azenMatt** [comment]
thanks for the feedback here, 

the logic to clear the milestones was quite different to the others (due to the 1-2-1 relationship vs the 1-2-many) so we decided to keep it out of scope and make sure people liked the multi-select feature first! 

we can prioritize this as an updated based on feedback (so everyone please 👍  the opening comment!)

**Comment by adamreisnz** [comment]
@azenMatt there are more problems around changing milestone of multiple issues it seems. I've tried to move multiple issues to another milestone, but while after hitting `apply` the milestone gets updated and is displayed correctly when you view one of the affected issues, the issue cards on the board itself *don't* seem to get update, and the filter still shows them (even if active for another milestone). I've had to refresh the board to fix this.

**Comment by kendramoroz** [comment]
@adamreisnz @cbeams 👋  We just launched a new feature in the multi-action, Assign to Milestone section to clear Milestones in bulk 🎉 

This should auto-update in your extension shortly. Let us know what you think! 

![image](https://user-images.githubusercontent.com/11036230/26994059-d7717f5a-4d1a-11e7-868f-48420ec4c181.png)

**Comment by adamreisnz** [comment]
Doesn't seem to be in yet, but I'll check again later. Looks promising, thanks!
