### ISSUE TITLE
How to vote?

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#978]
Sorry for the probably obvious question, but I can't seem to figure out how to vote for issues that have the label "need votes". I've tried using the +1 reaction, but that didn't add my vote to the list. Clicking the votes box didn't do anything either. Watching the thread ditto. Is this something that needs to be enabled somewhere?

**Comment by azenMatt** [comment]
Hi @adamreisnz - adding a reaction is the best way to do this, as it lets the team here filter by 'most reactions' to get an easy glimpse into what is popular. 

The downside is that adding a reaction doesn't subscribe you to an issue - so you will need to manually do that if you would like to see a notification when an update is posted.

**Comment by adamreisnz** [comment]
@azenMatt cool, but I was wondering how you add your vote here:

![image](https://cloud.githubusercontent.com/assets/490562/21128226/f6dd2658-c15d-11e6-8707-fadf1468c679.png)

It shows +22 on that issue, while it only has +2 reactions, and my face didn't show up after I put a reaction.

**Comment by azenMatt** [comment]
ah that piece! that is from long, long ago when ZenHub used to have reactions in the form of adding a '+1' to an issue or issue comment. 

We removed the ability to do this when GitHub introduced reactions. So we didn't lose the meta data on the older issues, we left the total count present and removed the ability to add to it.

**Comment by adamreisnz** [comment]
Ah I see, thanks!
