### ISSUE TITLE
After renaming an epic, it disappeared from the milestone filter

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#979]
I renamed an epic issue, and after that it disappeared from the view, even though it still matched the correct milestone filter. 

I then tried to refresh the board, but that caused all issues to disappear except 2.
Not sure what was happening, but it seems something is messed up with the filters after a refresh.

Had to browse to issues, refresh there, then go back to board for everything to come back to normal again.

**Comment by azenMatt** [comment]
Interesting... the only filter active was a milestone filter and the epic was in that milestone?

**Comment by adamreisnz** [comment]
Yes, correct. I tried to replicate it later though, and it didn't happen again. Will investigate some more.

**Comment by kendramoroz** [comment]
@adamreisnz hope this still isn't happening for you! Going to close this one out, but if it reoccurs, feel free to submit a new issue. 🚀

**Comment by adamreisnz** [comment]
I haven't encountered it, but then again renaming an Epic is not something we do that frequently. If It happens again I'll raise the issue, thanks!
