### ISSUE TITLE
Ability to hide the top bars of the github page

### ISSUE THREAD

**Issue by peterix** [ZenHubIO/support#98]
When looking at the board, the bars on top take up plenty of space and provide no benefit.

The bars could be toggleable, or somehow slide out when needed.

**Comment by snario** [comment]
![boards_ _piinpoint_piinpoint](https://cloud.githubusercontent.com/assets/1933029/9254874/e4278e3e-41b3-11e5-9231-2048b90504a8.png)

I was gonna make a new issue but instead will add it here

**Comment by azenMatt** [comment]
Thanks for the feedback - a 'full screen' board view is on the roadmap :smile:

**Comment by snario** [comment]
For anyone that ends up here, I wrote a bookmarklet to do it for me

```js
javascript:(function(){$('.header.header-logged-in').remove();$('.pagehead').remove();$('.zh-board-wrapper').css({height: ($(window).height() - 80)});})()
```

**Comment by geoffrey** [comment]
Nice! Here is a toggleable version so that you can revert once you are done with the board.

```javascript
javascript:(function(){ if ($('.header.header-logged-in').is(":visible")) { $('.header.header-logged-in').hide(); $('.pagehead').hide(); $('.zh-board-wrapper').css({height: ($(window).height() - 80)}); } else { $('.header.header-logged-in').show(); $('.pagehead').show(); $('.zh-board-wrapper').css({height: ($(window).height())});}})()
```

**Comment by snario** [comment]
Thanks @geoffrey, very helpful

**Comment by NicholasTD07** [comment]
@geoffrey Thanks for the great work! Works perfectly!

BTW, is it possible to put a button on the screen which would call the function when tapped?

**Comment by guido4000** [comment]
Please add this toggle button to the plugin.

**Comment by azenMatt** [comment]
This is really helpful :) We will get it added to the plugin!

**Comment by azenMatt** [comment]
and done :smile: 

![image](https://cloud.githubusercontent.com/assets/7584089/12524607/14e419e6-c113-11e5-9c92-ca24b5b25654.png)

live on v2.15.12 

Thank you @snario and @geoffrey for your help with this one :beers:
