### ISSUE TITLE
Milestone and estimate appear too low

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#980]
I think this got messed up in one of the recent releases;

![image](https://cloud.githubusercontent.com/assets/490562/20999283/5d84d110-bd78-11e6-8332-1e893ce54c23.png)

The milestone and estimate now appear way at the bottom, even below the list of participants and conversation lock options. I don't think this was intended? It's very hard to reach them now if you want to change them, and they are the only two options you can't properly change yet via multi select.

**Comment by azenMatt** [comment]
Hi @adamreisnz - this looks like a GitHub issue:

![image](https://cloud.githubusercontent.com/assets/7584089/20999863/5bbc7b6e-bccc-11e6-87fb-6198f2df7073.png)

I have already reported it, it would be great it you could as well :)

**Comment by adamreisnz** [comment]
@azenMatt interesting, yep will do!

**Comment by adamreisnz** [comment]
@azenMatt I got the following reply;

> Hi Adam,

> We changed the UI recently and this is expected behaviour.

> I can pass on your feedback to our team to consider though!

I find that really hard to believe, no ux designer would approve of that. 

But in light of them thinking it's by design, can Zenhub "fix" it for us (even if temporarily) and move it back by overriding css?

**Comment by adamreisnz** [comment]
I've asked for more details and clarification, because I simply can't imagine this being intended.

**Comment by azenMatt** [comment]
Looks like it was just fixed by GitHub:

![image](https://cloud.githubusercontent.com/assets/7584089/21031755/fe79b33e-bd59-11e6-9f6e-5ab357899b6d.png)

**Comment by adamreisnz** [comment]
Yep seems to be fixed, thanks for looking into it.

**Comment by azenMatt** [comment]
no worries - it does appear to have reordered some of the elements on the new issue page so we will push out a fix this week to put the ZenHub elements back into place
