### ISSUE TITLE
Organization wide and cross organization board

### ISSUE THREAD

**Issue by viktorbenei** [ZenHubIO/support#981]
It'd be awesome to have an easy way to create a board for a whole organization. In our case, we have well over 50 repos in some orgz, merging all into a single board is.. Quite painful.

In addition, we have more than one organization and we'd benefit from a single board, unifying the issue management of our organizations (we use a third party service - Trello - pretty much only for this reason).

**Comment by azenMatt** [comment]
Thank you for the feedback @viktorbenei 

Would this be the only view that you would want of the data? Or would you also be looking to create smaller boards for individual teams?

**Comment by viktorbenei** [comment]
For now probably only this view - it'd make our lives at https://github.com/bitrise-io way easier, as we have multiple open source organizations as well as a private one, and managing issues in a centralized way would speed up our process significantly.

**Comment by kendramoroz** [comment]
Very excited to announce that Workspaces, tracked via #139 will help easy the pain of creating multi-repo Boards more effectively when you need to merge more than 1 repo, as well as much more! Subscribe to 139 to stay updated with the latest ✨
