### ISSUE TITLE
[Bug] URL may contain unescaped ampersands.

### ISSUE THREAD

**Issue by alloy** [ZenHubIO/support#982]
One of our labels contains an ampersand. When filtering by this label, the URL gets rewritten to add the filter as a query parameter, but the ampersand is not escaped leading to the query parameters being interpreted incorrectly after re-visiting the URL.

For example, this incorrect URL:

`https://github.com/artsy/force#boards?labels:not=PS&R,publishing`

Should have been:

`https://github.com/artsy/force#boards?labels:not=PS%26R,publishing`

**Comment by adamreisnz** [comment]
I think that https://github.com/ZenHubIO/support/issues/972 is probably related to this issue. Our Milestone name also contains an ampersand, which is probably getting parsed incorrectly after a refresh, and hence the incorrect filters.

**Comment by alloy** [comment]
Aye, same issue 👍

**Comment by azenMatt** [comment]
Thanks for reporting 👍  we will take a look

**Comment by kendramoroz** [comment]
@alloy @adamreisnz We launched a fix for this today! If your browser isn't already updated to 2.26.7 a simple update should do the trick to get this fixed :). Let me know if you're having any trouble still! 🚀

**Comment by adamreisnz** [comment]
Excellent thank you!

**Comment by alloy** [comment]
Ace. Thanks 👌

**Comment by adamreisnz** [comment]
Looks like it is working correctly now 🎉
