### ISSUE TITLE
Top marker not showing story points in burndown chart

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#991]
The top marker on the burndown chart vertical axis is now showing the number of story points:

![image](https://cloud.githubusercontent.com/assets/490562/21283542/f2e23dfa-c468-11e6-9600-f33f81af3a06.png)

It should probably show `160` in this case.

**Comment by azenMatt** [comment]
well spotted - it is only showing to the nearest 'round' number, for example here is ours for the current sprint: 

![image](https://cloud.githubusercontent.com/assets/7584089/21361257/2c208d64-c6db-11e6-8a80-0e03aee39f90.png)

il add this as a low priority bug to get fixed. Let me know if you disagree and think this should be higher priority

**Comment by adamreisnz** [comment]
Actually not nearest, it seems to only show the last round number, e.g. flooring it. If it would round, that would actually be better behaviour. Or ceiling, to ensure that it always shows one tick above where the data point lies.

Low priority is ok!

**Comment by adamreisnz** [comment]
This seems to be fixed now as well
