### ISSUE TITLE
Out-of-Office Feature (Auto-comment on issues when tagged and OOO)

### ISSUE THREAD

**Issue by cshunger** [ZenHubIO/support#993]
It would be nice if I could set an out of office message with the Zenhub plugin. When people tag me in an issue Zenhub would have my permission to post to that issue with my out of office message and tag the users I have covering during my absence.

**Comment by azenMatt** [comment]
great idea @cshunger - i've add the 'needs votes' label so that we get some community feedback on how useful this would be for everyone 👍

**Comment by kendramoroz** [comment]
👋  Doing some cleaning of our community Board, and we've decided to close this issue while we focus on improving core experiences for Boards and Reports to give teams in ZenHub a stellar workflow and workspace home to manage projects. Keep an eye out on `Priorities` and `In Progress` to stay tuned with what we're up to! 😄
