### ISSUE TITLE
Is There Any JAVA API For ZenHub?

### ISSUE THREAD

**Issue by ArthurZ123** [ZenHubIO/support#994]
How can I get my ZenHub Issue information by using JAVA?

**Comment by pnavarrc** [comment]
The ZenHub API (see the [docs here](https://github.com/ZenHubIO/API) can be used with any language or tool capable of making HTTP requests, including Java.

Apache has a [good tutorial](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/index.html) on how to use their HTTP Client library to make requests. 

Note that the ZenHub API is read-only for the moment.
