### ISSUE TITLE
Improve UI for Completed vs. Remaining story points

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#997]
In the burndown chart, I find myself always wanting to know how many points exactly are left in a milestone. This is visible below the chart:

![image](https://cloud.githubusercontent.com/assets/490562/21469487/c73eb608-cab5-11e6-8cd1-2102f39adf0a.png)

However, because the *remaining* points are greyed out, they always escape my attention and I find myself always looking for a while before I spot it.

Since the number of points remaining is at the very least just as interesting than the number of points completed (arguably even more so), I would like to ask if you could make the number of points remaining more prominent and easier to spot.

I also find the repetitiveness of mentioning **story points** and **issues & PR's** three times in the same chart quite cluttering, which further detracts for the actual data.

So I'd like to propose a simple layout tweak as follows:

![image](https://cloud.githubusercontent.com/assets/490562/21469496/8f30bc1a-cab6-11e6-8ea7-d4fcbc840c6d.png)

This is instantly clearer, and makes it easier to spot both the completed and remaining figures.

Thoughts?

<sub>(Happy holidays 🎁 🎄 🎅 )</sub>

**Comment by kendramoroz** [comment]
Hey Adam—Kendra here from the Success team! 

Thanks for the great user feedback here, we're always looking for ways to make small enhancements that have meaningful impact on your workflow. Looks like there's already some 👍  for this change, keep 'em coming!  

I've looped in our design lead to take a look at your suggestions.
@brianleung11-3 

🎄 Happy holidays to you and your team, as well!

**Comment by adamreisnz** [comment]
@kendramoroz thank you :)

Happy to provide the feedback.

**Comment by adamreisnz** [comment]
@kendramoroz any movement on this issue?

**Comment by kendramoroz** [comment]
@adamreisnz Still in our backlog for a few weeks, but on our to-do list! I'll send over an update as soon as it gets launched 🚀

**Comment by adamreisnz** [comment]
Thanks!

**Comment by adamreisnz** [comment]
Hello again, it's been another 6 weeks, any chance of seeing this progress? :D

**Comment by adamreisnz** [comment]
It looks like this has been implemented! I will close it. Thank you!
