### ISSUE TITLE
Closed epics still appear in filter dropdown

### ISSUE THREAD

**Issue by adamreisnz** [ZenHubIO/support#998]
Epics that have been closed should probably no longer appear in the epic filter dropdown, as this will end up needlessly cluttering the filter over time as more and more epics are closed.

Currently, we've closed 2 epics but they are still visible after some time in the filter, even after a refresh.

**Comment by adamreisnz** [comment]
I might add that they *don't* show up in the epic selection for new/existing issues, so the problem seems to be isolated to the epic filter dropdown.

**Comment by brianleung11-3** [comment]
Thanks @adamreisnz. We are looking into fixing this now.

**Comment by adamreisnz** [comment]
@brianleung11-3 excellent, thank you 🎉
